### ISSUE TITLE
Add description about what noxfile.py is

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1000]
### Description of problem and opportunity to address it

**Context to understand the problem**

I'm trying to understand this code base, but find a file like `noxfile.py` without any comments in it making me stumble.

**Problem or idea**

I'd love to have a comment in the top of various standalone files that describes what they are about. For example, I've added that to the read the docs config file in #999 which also clarifies what RTD project should be inspected if something is acting up etc.

**What's the value and who would benefit**

Everyone would benefit - even the person added this file - because over time you forget.

### Implementation guide and constraints

- [ ] Add a comment of some kind to the noxfile.py file describing its purpose etc, allowing someone finding it to understand its role and purpose in this github project.
- [ ] If it was copy-pasted, a source of where it was copy-paste from should be included for example.
- [ ] If there is a known place where you can learn more about something etc that could be worth linking to as well.

**Comment by choldgraf** [comment]
I can add more docs about it when I'm back from vacation! In the meantime just wanted to quickly share that we have this documented in the READMEs of each repository (https://github.com/2i2c-org/infrastructure/blob/216bbced49e8635bab02e6c69467e8b43e4d7056/README.md#automatically-with-nox). If you add suggestions for where you naturally thought to look for this documentation but didn't find it, we can add references.

**Comment by consideRatio** [comment]
I recall you added a intro to what a noxfile is in another repo @choldgraf, do you recall what repo?
