### ISSUE TITLE
Generate token for Health Check service in the z2jh helm chart instead of in the deployer

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1024]
### Background and proposal

**Context**

We currently have two functions in the deployer that generates helm values on-the-fly that get parsed to the `helm upgrade` command:

- [`get_generated_config`](https://github.com/2i2c-org/infrastructure/blob/aa580cb0c28f4ef6599b6ba1a1a3fae9b1ac33f2/deployer/hub.py#L348-L466)
- [`apply_hub_helm_chart_fixes`](https://github.com/2i2c-org/infrastructure/blob/aa580cb0c28f4ef6599b6ba1a1a3fae9b1ac33f2/deployer/hub.py#L479-L518)

In `apply_hub_helm_chart_fixes`, [an API token is generated with admin privileges](https://github.com/2i2c-org/infrastructure/blob/aa580cb0c28f4ef6599b6ba1a1a3fae9b1ac33f2/deployer/hub.py#L492-L499). The deployer script later [uses this API token in the testing phase](https://github.com/2i2c-org/infrastructure/blob/aa580cb0c28f4ef6599b6ba1a1a3fae9b1ac33f2/deployer/hub.py#L600-L627). It uses the token to create a singleuser server on which some notebooks are executed top-to-bottom to ensure the hub is working at a basic level.

**Problem statement:** The more config that is not explicitly stated in a helm chart values file, and is instead generated on-the-fly in the deployer's "black box", the more difficult our deployment process becomes for our engineers to understand, and the more difficult a deployment is to replicate for a customer choosing to leave 2i2c and take their hub with them.

**Proposed solution**

The z2jh helm chart has the ability to automatically generate tokens (if they do not already exist) for registered services and store them as kubernetes secrets. The deployer, using service account credentials, will have permission to read kubernetes secrets in order to retrieve the token and execute its tests as normal. This would reduce the amount of on-the-fly-generated config produced by the deployer's "black box" and explicitly define more config in the form of helm chart values, or direct configuration in the basehub helm chart. Hence improving the comprehensibility of our deployment process and simplifying the amount of tasks the deployer carries out.

**Comment by consideRatio** [comment]
@sgibson91 :100: :+1: this would make me very happy to see.

This kind of complexity made me abandon manually deployed helm chart updates as I needed the deployer to generate certain config for me. I have once or twice quickly copied the temporary generated helm chart values files so I could use them manually, but that was a mess and forced me to also first learn the hidden details about this.

Related to this is that I believe dask-gateway may have a generated api-token as well by the deployer script. That should be solved upstream and is tracked here: https://github.com/dask/dask-gateway/issues/473.

**Comment by sgibson91** [comment]
> Related to this is that I believe dask-gateway may have a generated api-token as well by the deployer script. That should be solved upstream and is tracked here: [dask/dask-gateway#473](https://github.com/dask/dask-gateway/issues/473).

I just added an inline comment about this here! https://github.com/2i2c-org/infrastructure/pull/1025

**Comment by choldgraf** [comment]
So that I understand this, right now the workflow is:

- When the deployer happens, some tokens are generated programmatically, then immediately used, and destroyed when the process completes.

and the new workflow would be:

- When we set up a hub, we use Z2JH to generate the same tokens, but store them in an encrypted state in the cluster
- When deploys happen, they re-use those tokens rather than generating new ones on the fly.

Is that right?

**Comment by consideRatio** [comment]
@choldgraf sounds about right. I would want to clarify that "generated on the fly" is a bit slow. It means also to configure `jupyterhub.hub.services.deployer-script-test-service.apiToken` of the basehub helm chart during a `helm upgrade` redeploying a hub Helm chart. Then, after it has deployed, previously or now with the given specified token - it can be used to interact with the JupyterHub API.

The option in my word with regards to JupyterHub API tokens (like dask-gateway also needs to have registered btw), is to let the JupyterHub Helm chart generate them, and then let the deployer script us its k8s credentials to access whatever API token is needed by reading a k8s Secret created by the JupyterHub Helm chart.

But at the same time, there is a "generated" and "destroyed" part. It is the part of coming up with some API token automatically, save it to a temp file, and then reference that with `helm upgrade --values <my-generated-values.yaml-file>`, and then remove it. I think the API tokens generated and set for each hub is set consistently to the same thing given some seed, so its not random though.

**Comment by yuvipanda** [comment]
> The deployer, using service account credentials, will have permission to read kubernetes secrets in order to retrieve the token and execute its tests as normal.

If my understanding is correct, we are moving the complexity from the deployer generating secrets to the health checker, which will now need to talk to the kubernetes API. Right now, the health checker only needs to understand JupyterHub, and doesn't require kubernetes API at all. Given that we'll *always* have to generate some secrets that won't be in the charts directly - auth0 or CILogon - IMO this increases overall complexity while removing it from one specific part. 

So I think this complexity tradeoff is perhaps worth it if we can eliminate *all* generated config from the deployer, simplifying that vastly. Otherwise, I think we'll end up with a more complex health checker and a deployer that is not significantly less complex.

**Comment by yuvipanda** [comment]
> This kind of complexity made me abandon manually deployed helm chart updates as I needed the deployer to generate certain config for me. I have once or twice quickly copied the temporary generated helm chart values files so I could use them manually, but that was a mess and forced me to also first learn the hidden details about this.

I'm sorry this was your experience, @consideRatio. If this was implemented, you'd still need the deployer to generate auth0 credentials and do sops decryption, right?

**Comment by sgibson91** [comment]
I guess I'm approaching this from a "2i2c engineer" vs "customer leaving 2i2c with their hub" perspective. Having z2jh generate a health token to run test notebooks automatically is a useful feature for a single community running a single hub. The Auth0 config you mentioned is only useful for engineers deploying multiple hubs across multiple communities because it saves the toil of manually setting it up. In the single-community/single-hub case, you only need to do that manual step once and then you can hard-code the details in the helm chart values file (with appropriate encryption).

So I'd like us to have a decision flow of "does this make 2i2c engineers lives easier but would be overly-complex for a single hub scenario?" -> put it in the deployer, "would a single hub scenario make use of this feature?" -> configure it at the helm chart level instead.

That being said, I do want to drastically reduce the amount of config generation the deployer does overall anyway. The health check service (and the dask-gateway token also mentioned here) are just the first steps on that journey.

**Comment by consideRatio** [comment]
@yuvipanda I'm worried my comment was too harshly formulated and it was a negative experience for you to read it =/ I'm sorry!

### Brainstorming about goal conflicts

Hmmm, we want to accomplish a lot of things with the deployer script, and our wishes has also evolved over time and there are plenty of ways the goals we have can come in conflict.

Here are things that comes into mind for me:
- __Automate tasks__
  Easy to deploy multiple hubs etc for 2i2c engineers
- __Honor R2R__
  A strategy to decouple 2i2c from operation of a cluster + hub(s) within it.
- __Make comprehensible__
  To make a system and its parts involving the deployer script easy to comprehend.
- __Make debuggable__
  I have had a need to debug by doing `helm upgrade` / `helm template` with provided chart configuration in isolation from the other things the deployer script have done.
  
I think I've been looking to optimize more towards the last three things in this list, actually the list I made is of course a bias of what I currently value. Maybe by making some things more explicit we can strike better balances in how to compromise when there are goal conflicts? Hmmm...

I'm not sure what makes sense for the health check, but I think I still like the idea of getting a health-test JupyterHub API token from the k8s cluster's secret more than generating and setting it over and over. Here are some thoughts in my mind.

1. If you would do a manual `helm upgrade` you wouldn't include the configuration and force a future deployer script health check - made in a standalone manner without also doing a `helm upgrade` - to fail with missing credentials.
2. If you would inspect the helm chart configuration, you wouldn't know the deployer had injected additional credentials for the hub.
3. Based on my understanding is that we generate the api-token from a 2i2c central secret.
   1. If R2R is used, and we had generated the health check api-token, the user couldn't re-generate that api-token as we do.
   2. If the health check was made doable in a standalone manner using existing k8s credentials, we wouldn't need to also decrypt/pass the secret needed to re-generate the api-token.
   3. I have a gut feeling it would be easier to comprehend a deployer scripts code base if we got the health-test api-token from the k8s cluster.
   4. Clarifying what you would need the "main secret" used to generate other secrets for would be easier as it would be coupled to one less thing.
   5. The "main secret" should probably only be coupled with 2i2c specific things that won't be part of what the user needs after R2R. The health check may or may not be relevant for a R2R decoupled user.

**Comment by yuvipanda** [comment]
Thank you for your clear and helpful responses, @sgibson91 and @consideRatio. Particularly, I'm very happy to see the large focus on r2r (yay!), as well as:

> That being said, I do want to drastically reduce the amount of config generation the deployer does overall anyway. The health check service (and the dask-gateway token also mentioned here) are just the first steps on that journey.

One possible path forward that will also be generally useful is to:

- [ ] Move the tests to a standalone repo and
- [ ] Make those into a helm chart tests - https://helm.sh/docs/topics/chart_tests/. This way, no secret generation needs to happen, as the code can just load the k8s secret directly and easily.

This also is generally useful to the broader OSS community too! What do you think of that?

**Comment by sgibson91** [comment]
I do like this idea and think we should brainstorm more! That could open a path forward to communities who bring their own images to provide specific notebooks for us to test with (I'm thinking of the current situation with Pangeo right now). I'm going to specifically cross-ref with https://github.com/2i2c-org/infrastructure/issues/586

**Comment by consideRatio** [comment]
__Regarding using Helm chart native testing__

Helm chart tests are typically bundled with the Helm chart they are to test right? If so, they should be part of the dask-gateway helm chart, the jupyterhub helm chart, or the basehub helm chart.

I've never used these kinds of tests properly and lack experience with them. Yet, I think that it could be relevant to explore overall for the ecosystem of Helm charts we work with. If z2jh pilots something about them, I would wish it would be a as minimalistic test initially that is likely to be very robust.

The absolute first step I think would be to to understand how `helm test` works when you have a Helm chart that depends on another Helm chart. For example, `basehub` use `jupyterhub`. If basehub declares test templates, and jupyterhub does it also - what will run, and in what order, if you run `helm test` on basehub?

I think a followup step would be to explore the viability of going for helm chart native tests would be to describe the tests to run in English and consider in what context the tests would fit well (z2jh, basehub, daskhub, etc). A second step would be to guess if such tests would be generally helpful enough to motivate their development/maintenance in that context given the UX that would go with it (`helm test` isn't going to be as helpful as `pytest` sadly).

__Regarding if to explicitly specify a JupyterHub API token or get an automatically generated one from a z2jh k8s Secret__

I'm in favor of any progress onwards that makes us not explicitly specify and manage a JupyterHub API token. To do this, the following options are available.

1. Explicitly specify it in secret configuration and read the configuration.
2. Let z2jh generate it and fetch it from the k8s Secret z2jh has created.
   - Option 1: Let a health check test be run via the deployer script using the token from the k8s Secret
   - Option 2: Let a health check test be run via the deployer script using `helm test`, which in turn relies on tests bundled with the Helm chart.
