### ISSUE TITLE
[Incident] Dask Gateway fails with Unavailability of Compute Engine Resources - turned out to be a transient issue

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1031]
# Summary

### Background

The Pangeo community recently tried to update their user environment image via the Configurator. When user sessions started with the new image, Dask Gateway was no longer functional.

When the image was bumped to `2022.02.04` then running the following code:

```
from dask_gateway import GatewayCluster
cluster = GatewayCluster()
cluster.scale(20)
```

Would not function properly. Looking at some of the logs in the GCP console, we saw these errors:

<img src="https://user-images.githubusercontent.com/1839645/155581517-8aedb94f-2526-49c6-8dc3-dec7b4807019.png" width=300 />

### Resolution

Ultimately, we realized that this was likely a **transient issue** due to Google Cloud's resource limits being reached, and the fact that we are not paying for dedicated guaranteed resources.

### Relevant information

- Hub URL: http://us-central1-b.gcp.pangeo.io/
- FreshDesk ref: https://2i2c.freshdesk.com/a/tickets/82
- Pangeo image repo is here: https://github.com/pangeo-data/pangeo-docker-images
- A diff of the repo changes between these two versions: https://github.com/pangeo-data/pangeo-docker-images/compare/2021.10.19...2022.02.04

### Actions to resolve

We'll need to collaborate with folks in the Pangeo community who are familiar with the user environment images (maybe that is @scottyhq and @rabernat ? Please cc others who may have insight). We could then do some combination of:

- Look at the diff in the user image, and try to spot anything that would obviously stop Dask Gateway from scaling: https://github.com/pangeo-data/pangeo-docker-images/compare/2021.10.19...2022.02.04
- If that doesn't work, then work backwards with _earlier releases_ of the image, running the code snippet above to see if it works. When we find an image environment that works, then we can figure out the exact diff that broke it.
- [x] Work with members of the Pangeo team to identify the problem and resolve it
- [x] Incident has been dealt with or is over
- [x] Sections below are filled out
- [x] Incident title and after-action report is cleaned up
- [x] All actionable items above have linked GitHub Issues

# Timeline

All times in US/Pacific.

### 2022-02-17 - First reports

- @rabernat reported that the Dask Gateway cluster was not scaling properly
- After some investigation, we realized that this happened just after bumping the user image to `2022.02.04`.
- Reverting the image made things work again, but now we cannot update the user image without breaking things.

### 2022-02-18 - 2022-02-22 - Investigation

2i2c team investigated what could be going on, and suspect that the issue was a change in the environment image dependencies (see links to relevant diffs etc above). We identified several process / technical improvements that could have prevented this (see below), but still unsure of the specific incompatibility in the image.

### 2022-02-22 - 2022-03-08

Tried various investigations into things that are going wrong, including:

- Trying the same operation on the AWS Hub (surprised that it worked): https://github.com/2i2c-org/infrastructure/issues/1031#issuecomment-1050474979
- Investigating the series of commits to the Pangeo user image: https://github.com/2i2c-org/infrastructure/issues/1031#issuecomment-1051441864

During this time, the Pangeo hub was functional because it was using the _previous_ user image.

### 2022-03-09

- We noted that Dask Gateway hadn't had a release, so it is unlikely that the problem was due to a Dask Gateway incompatibility
- Investigating the error message "
- Concluded that this was a transient issue due to GCP's resources being maxxed out: https://github.com/2i2c-org/infrastructure/issues/1031#issuecomment-1064619883

# After-action report

## What went wrong

- Google's resources on the cluster were maxed out. Because we do not pay GCP for guaranteed cloud resources, occasionally they will not be available. When the Dask Gateway cluster was created, this resulted in the error shown above.
- This happened to coincide with a bump in the user image for this hub, and so we originally thought the error was due to that issue.
- After a lot of investigation, we couldn't figure out why the user environment was the cause of the problem.
- Finally we discovered that this was due to the resource constraints issue above, and that this was transient.

## Where we got lucky

- We were lucky that it was possible to quickly revert the image, when the previous one wasn't working.
- We were **unlucky** that the transient issue happened to coincide with a user action, which led us down the wrong debugging path.

# Future action items

### Process improvements

- Define a policy about what kind of guidance 2i2c can provide to communities who manage their own environments. Tracked in: https://github.com/2i2c-org/infrastructure/issues/1016

### Technical improvements

- We need a way to validate the environment that is present in user images, to ensure some basic validity checks as a part of CI/CD: https://github.com/2i2c-org/infrastructure/issues/1016
- We should automatically test Dask Gateway as part of new hub deploys - doing this could have helped us catch this issue earlier on. Tracked in https://github.com/2i2c-org/infrastructure/issues/152

**Comment by scottyhq** [comment]
Thanks for documenting this @choldgraf! No solutions off the top of my head, but some ideas to get started

I can't tell from the console messages pasted above what could be going on. In the past I've found it necessary to look at the k8s pod logs to figure out whats going on. If there is some way to expose such logs to the community hub admin that could help.

It might also be helpful to hone in on the conda environment changes, which for this particular case you can use the following URL: https://github.com/pangeo-data/pangeo-docker-images/compare/2021.10.19..2022.02.04#diff-ceee658209456cc3bd347679717bdb5d95ee7fb5a91ffa1dc6d2e2d556144987 

For example I see some possibly relevant changes `dask-2021.9.1 -> dask-2022.1.1` and `jupyterhub-singleuser-1.4.2 -> jupyterhub-singleuser-2.1.1` etc.

To fully test for dask-gateway compatibility, it seems like you need some CI to actually launch a small dask-gateway cluster with the new image, right? Could either be with a 'test' cluster or maybe there is even a way to securely connect to the pangeo-hub itself and programmatically launch a cluster with the new image?

**Comment by scottyhq** [comment]
I was able to launch a functional cluster with the 2022.02.04 image on the [AWS hub](https://github.com/pangeo-data/pangeo-cloud-federation/tree/staging/deployments/icesat2), so this seems to be due to some incompatibility with the config (autoscaler version? daskhub chart version?) and image...
<img width="508" alt="image" src="https://user-images.githubusercontent.com/3924836/155645896-954e82f2-2dda-4a00-b4c4-8af729d2410b.png">

**Comment by choldgraf** [comment]
Maybe the thing to do is to intentionally break the user image on the Pangeo staging hub, so that we can look at the logs once somebody tries a scaling event w/ Dask Gateway. I think that the configurator works the same way on https://staging.us-central1-b.gcp.pangeo.io/ as it does on `prod`, so it shouldn't bottleneck on having merge rights to `infrastructure/`.

If we can break staging by upgrading the image, then prod will stay functional and it should be easier to debug

**Comment by rabernat** [comment]
Just wanted to ping here to 
- apologize for not being more involved in the conversation yet...I triggered the initial issue but then got sucked into urgent ocean sciences prep work this week
- say that I strongly support @choldgraf's plan to debug this on the staging cluster. That's exactly what it is for IMO. No one is depending on that for any sort of day-to-day work, so we can temporarily break it all we want as we work though this issue.


> What is the easiest way to answer the question "when did package X get updated in the Pangeo image, and which release is associated with it?"

https://github.com/pangeo-data/pangeo-docker-images/blame/master/pangeo-notebook/conda-linux-64.lock

**Comment by rabernat** [comment]
Thanks for the help here Scott!

My best guess would be that the 2i2c dask gateway version is incompatible with the image version. Is it possible to upgrade dask gateway just for staging? Or is there one gateway for both clusters?

FWIW, the latest image DOES work with dask gateway on the Pangeo AWS binder: https://hub.aws-uswest2-binder.pangeo.io/v2/gh/pangeo-data/pangeo-docker-images/2022.02.04

**Comment by yuvipanda** [comment]
Hello! I'm actually slightly confused about what happened here - dask-gateway hasn't had a new release, and that's what is the most likely culprit here. I'm going to take a look on staging.

**Comment by yuvipanda** [comment]
Googling the first error message in the screenshot posted takes me to https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-vm-creation, which has a lot of useful information. In particular, it states *Because this situation is temporary and can change frequently based on fluctuating demand, try your request again later.*. I think this is because dask workers are [preemptible instances](https://cloud.google.com/compute/docs/instances/preemptible) (similar to spot AWS instances), and hence during the time this scale up was attempted, Google Cloud was just 'full'.

I just tried the latest image on the staging cluster, and could spin up 20 dask workers and do some computation with the newest image (2022.02.04)

<img width="521" alt="image" src="https://user-images.githubusercontent.com/30430/157596740-0e54797b-98da-41f6-9982-5964d64f947b.png">

So I think the image change was pure coincidence, and what really happened was that the cloud was full and put you on hold.

**Comment by yuvipanda** [comment]
https://staging.us-central1-b.gcp.pangeo.io has the new image, and in #1080 I'm pushing it out to the prod hub as well. I want to push this out soon, but wanted to give folks an opportunity to test as well.

**Comment by choldgraf** [comment]
So to summarize, I think this is the situation:

- the user image was bumped on the Pangeo hub via the configurator
- we then tried to scale with a Dask Gateway, and got the error message posted above
- we reasonably concluded that the error was due to something that changed in the image
- debugging the user image didn't yield a clear answer, especially since the same image on the AWS hub worked
- we did some more google on the error message and found it was associated with preemptible nodes (which the dask gateway uses)
- we concluded this issue might have been transient, and only coincidentally related to the user image
- we tried bumping the image in the same way again, and it worked

Is that right?

**Comment by yuvipanda** [comment]
> we did some more google on the error message and found it was associated with preemptible nodes (which the dask gateway uses)

It's associated with both preemptible nodes but also with general cloud capacity. We think of cloud resources as infinity, but physical restrictions do exist - we just don't often run into them. If we *really* want to make sure this never happens, you can buy commitments (https://cloud.google.com/compute/docs/instances/reservations-overview) that you pay for regardless. So it's possible this error would also occur without preemptible nodes - although less likely.


> we concluded this issue might have been transient, and only coincidentally related to the user image

Based on the info we have, I think it was transient (not might have been) and unrelated to the image.

Otherwise, this is right!

**Comment by rabernat** [comment]
We just discovered a serious bug in the 2022.02.04 image (https://github.com/pangeo-data/pangeo-docker-images/issues/297), so we need to go to 2022.03.08.

I would make the PR myself, but I am having trouble understanding where exactly this is configured. I browsed around
https://github.com/2i2c-org/infrastructure/tree/master/config/clusters/pangeo-hubs but couldn't figure it out.

**Comment by scottyhq** [comment]
> I browsed around
https://github.com/2i2c-org/infrastructure/tree/master/config/clusters/pangeo-hubs but couldn't figure it out.

https://us-central1-b.gcp.pangeo.io/services/configurator/

**Comment by yuvipanda** [comment]
@rabernat you can just use the configurator for now. I agree that's confusing on when to use the configurator vs deploy via the hub config here, something to sort out.

**Comment by yuvipanda** [comment]
However, if you wanna make a PR, the tag is specified in https://github.com/2i2c-org/infrastructure/blob/6e66c84176c8d7f91b1a8ad4b9d71b5f2256d076/config/clusters/pangeo-hubs/staging.values.yaml#L64

**Comment by rabernat** [comment]
> you can just use the configurator for now.

My understanding is that the configurator overriding the value in the chart was the source of some problems up thread. So I am reluctant to use the configurator.

> However, if you wanna make a PR, the tag is specified in

This points to staging. Does it also apply to prod? There is no equivalent line in https://github.com/2i2c-org/infrastructure/blob/6e66c84176c8d7f91b1a8ad4b9d71b5f2256d076/config/clusters/pangeo-hubs/prod.values.yaml

**Comment by sgibson91** [comment]
@rabernat Short answer, yes it also gets parsed to prod

**Comment by yuvipanda** [comment]
@rabernat if you see https://github.com/2i2c-org/infrastructure/issues/1031#issuecomment-1063684279, the image change actually had nothing to do with the problem here at all. It was just a coincidence.

**Comment by choldgraf** [comment]
Hey all - I believe that this one is now resolved, and I've updated the top comment with a timeline and overview of the problem. Annoyingly I could not think of too many follow-ups to improve upon, because the root problem here was transient, and we mostly just needed to "try it again". We do have a few issues to track enforcing specifications in the user environment which should help at least narrow down the potential problems in the future.

I'm going to close this one, but if anyone has suggestions for other process / tech improvements we need, please suggest them and/or open issues!
