### ISSUE TITLE
Cleanup our terraform workspaces

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1034]
### Background and proposal

Our terraform state on GCP has a lot of workspaces, some of which seem duplicated:

- [x]  default
- [x]   carbonplan-aws
- [x]   carbonplan-azure
- [x]   cb-1003-1696
- [x]   cloudbank (in-use)
- [x]   grenoble *empty, deleted*
- [x]   justiceinnovationlab *empty, deleted*
- [x]   meom *empty, deleted*
- [x]  meom-ige (in-use)
- [x]  openscapes
- [x]   pangeo-test *deleted*
- [x]   pilot-hubs (in-use)
- [x]   sandbox *deleted*
- [x]   uhackweeks
- [x]   utoronto

We should:

- [x] Evaluate which ones are currently valid
- [x] Cleanup workspaces we no longer use
- [x] Make sure 'delete terraform workspace' is part of the decomission process

**Comment by sgibson91** [comment]
`pangeo-test` can definitely be deleted, this was the `pangeo-181919` cluster

**Comment by yuvipanda** [comment]
Thanks @sgibson91! I've deleted pangeo-test, and several others. I've updated the issue body with current status.

Looks like the default workspace as well as the `cb-1003-1696` workspace have some resources inside that need to be investigated and cleaned up.

**Comment by yuvipanda** [comment]
`default` and `cb-1003-1696` had leftover objects (a 0 node cluster, associated hub / prometheus disks, etc) from before ecb25c3971f4d7c1f9f3523b88d5dd1584915c0f landed and refactored everything. `terraform destroy` will not work without getting the terraform files to the exact state they were in when the last `terraform apply` on these were done, so I checked out ad19ba5c3cb64c17ebdbc7baa0ed3dad60dc4fc6 (one commit above the commit that performed the refactoring), and am running `terraform destroy` after verifying they aren't going to hit critical infrastructure.

**Comment by yuvipanda** [comment]
Should see a slight drop in our costs for these two projects!

**Comment by yuvipanda** [comment]
Deleting terraform workspace is now a part of the decom process
