### ISSUE TITLE
Transition GCP config-connector to terraform - cleanup `cloudResources`

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1046]
## Updated issue

The "config connector" system enabled GKE clusters to define resources of custom types representing GCP resources, where GCP then would create these for us. In practice it enabled [our chart's to emit k8s resources](https://github.com/2i2c-org/infrastructure/blob/HEAD/helm-charts/basehub/templates/cloud-resources/gcp/) that led to the creation of GCP resources outside the k8s cluster, such as a GCP service account and a GCP storage bucket.

We have now transitioned to create such service accounts and buckets via terraform instead, but some clusters still rely on the config connector system. If we can transition to using terraform entirely, we would avoid the complexity of retaining config connector related config that is only relevant to some clusters, and we would avoid the quite significant CPU/Memory overhead requested inside the k8s cluster by the config connector system.

### Action points

From Yuvi's comment https://github.com/2i2c-org/infrastructure/issues/1046#issuecomment-1308202723

* Make sure the cloudResources config is removed from config for:
  * [x]  pangeo-hubs/common
  * [x]  2i2c/dask-staging
  * [x]  2i2c/ohw
  * [x]  2i2c/catalyst-cooperative
* Remove set of resources from our config, under `helm-charts/`
* Remove custom code we have in our `values.yaml` to support this
* Remove terraform code that supported setting up config-connector

## Original issue

<details>

In #1045 I removed this section.

https://github.com/2i2c-org/infrastructure/blob/689db10eee7ac806aa95d0a927953900b98b10fe/helm-charts/daskhub/values.yaml#L1-L6

It wasn't functional and instead silently ignored. It should be located under `basehub.jupyterhub.custom.cloudResources.scratchBucket.enabled` to be functional and not ignored.

In #1045 I opted to not change any behavior but instead remove the misconfiguration that was silently ignored and open this issue to raise awareness about the situation: daskhub won't create a scratch bucket by default etc, and you must enable this for each hub that wants it.

I lean towards thinking that any custom resources that one may want, should be explicit configuration for a cluster's hubs rather than default configuration. If there is agreement about that, there may be no action point at all but to close this issue.

## Action points

Outlined by Yuvi in https://github.com/2i2c-org/infrastructure/issues/1046#issuecomment-1308202723

</details>

**Comment by sgibson91** [comment]
Creating the scratch bucket is something the config connector should be able to do (on GKE), but I never got it to work. We should scope another project, similar to the CI/CD one, that refactors/overhauls our terraform infra to make it consistent.

**Comment by sgibson91** [comment]
> @sgibson91 do you want to create an issue to start writing down a list of things that we can shape into a broader project?

I will put it on my to-do list and get to it when I can

**Comment by choldgraf** [comment]
sounds good - I don't think there's a strong hurry there, just want to make sure that we don't forget about it.

For this issue, it then sounds like we can close it simply by documenting in `infrastructure/` that scratch buckets must be created first before the hub can be configured to use them. Is that right? It seems like [these docs are where we describe the setup process](https://infrastructure.2i2c.org/en/latest/topic/cluster-design.html?highlight=scratch#cloud-access-credentials-for-hub-users) so maybe we can refine those a bit?

**Comment by damianavila** [comment]
> Creating the scratch bucket is something the config connector should be able to do (on GKE), but I never got it to work https://github.com/2i2c-org/infrastructure/issues/669

I would bet this is the underlying issue!

> For this issue, it then sounds like we can close it simply by documenting in infrastructure/ that scratch buckets must be created first before the hub can be configured to use them. Is that right?

IIUC, we are currently creating that bucket with terraform, ie: https://github.com/2i2c-org/infrastructure/blob/master/terraform/gcp/projects/pangeo-hubs.tfvars#L16-L18
@sgibson91 might know better if there is any other place where this is actually already documented.

**Comment by sgibson91** [comment]
> @sgibson91 might know better if there is any other place where this is actually already documented.

I'm not sure there is any documentation yet. I caught this in the LEAP config though. https://github.com/2i2c-org/infrastructure/pull/1074#discussion_r826767521

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/pull/1130 is relevant

**Comment by yuvipanda** [comment]
We need to basically rip out the config-connector stuff completely, as we've moved all scratch bucket stuff to terraform. Unassigning myself as I'm not currently working on it.

**Comment by yuvipanda** [comment]
The tasks to do is:

1. Make sure the cloudResources config is removed from config for:
    - [ ] pangeo-hubs
    - [ ] dask-staging
    - [ ] ohw
    - [ ] catalyst-cooperative
2. Remove set of resources from our config, under `helm-charts/`
3. Remove custom code we have in our `values.yaml` to support this
4. Remove terraform code that supported setting up config-connector
