### ISSUE TITLE
Upgrade our hubs to Z2JH 2 / JupyterHub 3.0

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1055]
### Background and proposal

Our `basehub` chart defines the version of Zero to JupyterHub that we pull in here:

https://github.com/2i2c-org/infrastructure/blob/6da898b2892c9e81b6afa91d1ade3d2a0e56a472/helm-charts/basehub/Chart.yaml#L1-L15

However, Z2JH 2.0 will be released relatively soon, and is going to bring with it **JupyterHub 2.x**.

We should upgrade to Z2JH 2.0 as long as we're confident that it will be fit for production in our hubs. However, there may be some coordination that we need to take with either our `basehub` etc helm charts, or with the user images that we're serving.

This is an issue to track that effort so that we know what needs to be done!

### Implementation guide and constraints

[Here's the issue tracking the release of Z2JH 2.0](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2386). I believe that @consideRatio has been putting a lot of time into this one (thanks 🙏🙏🙏) and maybe he can advise on progress as we near a release. Looking at that issue, it seems quite close.

[Here's an example of a problem that occurred because somebody bumped `jupyterhub-singleuser` too early, on a hub that did not yet have JupyterHub 2.0](https://github.com/pangeo-data/pangeo-docker-images/issues/272#issuecomment-1058390957).

 

### Updates and ongoing work

- [x] Wait for Z2JH 2.0 to be released (and/or help make it happen!) (ref: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2386)
- [ ] Compile a list of things we should double-check in our hub configuration to make sure an upgrade won't break things.
- [ ] Make the necessary upgrades in our config + any community hub configs.
- [ ] Hope that everything doesn't explode.
- [ ] Check if https://github.com/2i2c-org/infrastructure/issues/1643 is actionable now

**Comment by consideRatio** [comment]
> We should upgrade to Z2JH 2.0 as long as we're confident that it will be fit for production in our hubs. However, there may be some coordination that we need to take with either our basehub etc helm charts, or with the user images that we're serving.

To ensure user images have JupyterHub 2 installed ahead of time is a very big deal of the 2i2c prep i think.

**Comment by consideRatio** [comment]
I wonder if https://github.com/jupyterhub/jupyterhub/pull/3809/files#diff-514e695392b67987ea4b144e522365c14062bb806eaa0bfe8f1d24175cabe072R504-R514 could possibly impact if things work or not. I'm super vague on the context and technical details or the errors observed that makes us want to pin JupyterHub 1 for some situations.

**Comment by yuvipanda** [comment]
I upgraded berkeley to master a week or so ago and it worked great.

**Comment by consideRatio** [comment]
JupyterHub 3 beta 1 has been released, and the z2jh Helm chart has started using JupyterHub 3 beta1.

**User images**
Users can have version >=2.3.1 (probably a lower version as well, not sure what version is the lower bound), but the key point is that users doesn't require jupyterhub 3 to be installed.

So, updating to an even more modern version of z2jh should be fine without trouble.

**Comment by sgibson91** [comment]
In Slack, Erik noted that version `2.0.0-beta.1.n024.he38f180b` has been released. This release contains a fix for https://github.com/jupyterhub/kubespawner/issues/627 which was causing us a lot of problems in non-regional clusters. See https://github.com/2i2c-org/infrastructure/issues/1103, https://github.com/2i2c-org/infrastructure/issues/1300, https://github.com/2i2c-org/infrastructure/issues/1616.

**Comment by damianavila** [comment]
I guess this one should be open until we migrate to the released version of 2.0 that actually happened 3 days ago, correct?

**Comment by yuvipanda** [comment]
@damianavila yep!

**Comment by damianavila** [comment]
This is done.
