### ISSUE TITLE
Upgrade k8s version on U of T and Carbonplan clusters

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1067]
### Background and proposal

**Context**

We received an [email](https://2i2c.freshdesk.com/a/tickets/95) via `support@2i2c.org` to bump the version of k8s the U of T cluster is running. Partial content below:

> AKS is retiring v1.20.x on 7 April 2022. We've detected that one or more AKS clusters in your subscription(s) are using Kubernetes v1.20.x or lower. To stay within supported versions <[https://docs.microsoft.com/azure/aks/supported-kubernetes-versions>](https://docs.microsoft.com/azure/aks/supported-kubernetes-versions%3e) and service-level agreements (SLA) you have up to 30 days after the version is removed to upgrade. To avoid ever falling out of support and to keep up with Kubernetes versions we recommend turning on auto-upgrade <[https://docs.microsoft.com/azure/aks/upgrade-cluster#set-auto-upgrade-channel>](https://docs.microsoft.com/azure/aks/upgrade-cluster#set-auto-upgrade-channel%3E).
>
> Required action Please upgrade your clusters <[https://docs.microsoft.com/azure/aks/tutorial-kubernetes-upgrade-cluster>](https://docs.microsoft.com/azure/aks/tutorial-kubernetes-upgrade-cluster%3e) to v1.21.x or higher by 7 April 2022.
> More information
> * To keep up to date with all AKS releases, subscribe the AKS Releases <[https://aka.ms/aks/releases>](https://aka.ms/aks/releases%3e) page.
> * To know when the next versions will be introduced or retired check the Kubernetes release calendar for AKS <[https://docs.microsoft.com/azure/aks/supported-kubernetes-versions#aks-kubernetes-release-calendar>](https://docs.microsoft.com/azure/aks/supported-kubernetes-versions#aks-kubernetes-release-calendar%3E).

**Proposed solution**

We should stay reasonably up-to-date with k8s versions as this will make our lives as maintainers easier. I also acknowledge that finding the right spot on the spectrum between "too old" and "too bleeding edge" is always a challenging question without a clear cut answer.

The `Carbonplan` cluster also runs an older k8s version, so we should update that too.

### Implementation guide and constraints

- [ ] Upgrade UofT cluster k8s version
- [ ] Upgrade Carbonplan cluster k8s version

**Comment by sgibson91** [comment]
cc @GeorgianaElena and @yuvipanda who I believe have access to that cluster

**Comment by yuvipanda** [comment]
We need to do this for carbonplan as well

**Comment by GeorgianaElena** [comment]
I've updated the top comment and issue title to encompass the carbonplan cluster too.

It looks like there are docs about how to upgrade the k8s version of an aks cluster here ➡️  https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster. Is there anything 2i2c specific that needs to happen apart from the instructions in that doc?

**Comment by sgibson91** [comment]
> Is there anything 2i2c specific that needs to happen apart from the instructions in that doc?

_Maybe_ something in terraform? But that might mean upgrading k8s across all our clusters - which is possibly not a bad thing, but we should be mindful about how much we upgrade by. As point out by @consideRatio in Slack:

> What version is the k8s cluster? Dask gateway wont support the newest
> Dont remember if that is 1.23 not being supported or also 1.22

**Comment by consideRatio** [comment]
### Sprint team meeting notes

We should schedule time with them to get this done. Yuvi and Georgiana have relevant tech knowledge.

**Comment by choldgraf** [comment]
@yuvipanda agreed we should schedule a maintenance window, the hub gets enough usage that there are almost always some people.

If we think that there's other work to do, I'm +1 on doing it in that window as well.

I've sent Jeremy an email to ask if there's a good time to do maintenance work in the next month or so. I've cc'ed @yuvipanda and @colliand as well

**Comment by damianavila** [comment]
> Maybe something in terraform? But that might mean upgrading k8s across all our clusters - which is possibly not a bad thing, but we should be mindful about how much we upgrade by

I would rather prefer to upgrade all our clusters to the same version instead of having different versions laying around...
Well, I think having different versions in different cloud providers might be an intermediate step, but all of our gcp clusters, for instance, should run with the same version, IMHO.

**Comment by sgibson91** [comment]
@damianavila I agree, I just meant being mindful in terms of downtime and the aforementioned version mismatch between k8s and dask gateway.

**Comment by yuvipanda** [comment]
This was done!

**Comment by damianavila** [comment]
Did you update this manually, @yuvipanda?
