### ISSUE TITLE
Document how to decomission a cluster

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1070]
### Background and proposal

With https://github.com/2i2c-org/infrastructure/pull/1069, there is now another manual step needed before you can delete a cluster. We should document this.

**Comment by pnasrat** [comment]
I'm taking this on as part of #2173 decision to document decomission process

**Comment by pnasrat** [comment]
Note the global dashboard manually wires in the datasources and needed to be edited (just removal of datasource not sufficient). This probably needs thought as we might need historic data for billing

https://grafana.pilot.2i2c.cloud/d/global-usage-dashboard/global-usage-dashboard?orgId=1

**Comment by yuvipanda** [comment]
There's enough documentation on this now, we can open specific issues if needed.
