### ISSUE TITLE
Simplify UToronto hub deployment so it is easier to manage

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1088]
UToronto was one of our very first hub deployments, and we have experimented with a bunch of different things since that make adminstering to hubs much simpler. A lot of progress has already been made on this front (https://github.com/2i2c-org/infrastructure/issues/638), but a couple more will make our life even easier!

# Remove Dockerfile from UToronto image

The [utoronto-image](https://github.com/2i2c-org/utoronto-image/) uses a custom Dockerfile to build. This was mostly because of missing bits of R support in repo2docker when the image was first constructed - primarily, newer R versions and binary package installs. I've since worked on bringing repo2docker's R support up to par, and we can switch to using it now! This will simplify maintenance of the image

# Switch to using CILogon for auth instead of AzureAD

This would need to be CILogon directly rather than via Auth0, and we should restrict the supported Auth providers to just UToronto + something that 2i2c engineers can use to log on. This makes testing and other adminstration easier for 2i2c engineers, and removes the need to renew the AzureAD credentials once every year. We will need to find a way to match the current user account names (they use oids from AzureAD, not emails) - if we can't, this is a non-starter

**Comment by choldgraf** [comment]
When the issue below is merged, we should be able to start prototyping using CILogon for U.Toronto authentication:

- https://github.com/2i2c-org/infrastructure/pull/1089

**Comment by damianavila** [comment]
From a support ticket where a conversation about the timeline for big changes happened:

> Re: timing, given it's a drastic change, how do you feel about aiming for the next break in classes? Looking at https://artsci.calendar.utoronto.ca/sessional-dates, perhaps first week of January is a good time to deploy those? If that sounds good, we can start planning for that.

And it seems they confirmed it is a good time for them, although I would argue it could be a hard time for us from a capacity point of view.

**Comment by yuvipanda** [comment]
Yeah, I agree - unfortunately that is often the only time to be able to do this (from personal experience at berkeley too). The goal is to spend the next 3 months staging and planning these, so first week of january is *just* rollout.

**Comment by damianavila** [comment]
Shapping this one is necessary, assigned to @yuvipanda.

**Comment by damianavila** [comment]
We can close it by now.
