### ISSUE TITLE
Setup authentication for Grafana

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#109]
We've two grafanas - grafana.cloudbank.2i2c.cloud, and grafana.pilot.2i2c.cloud.

Ideally, we'd only have one grafana - but then we'd have to do some network-foo to expose the other prometheus. We don't actually want do that.

Instead, we should just setup GitHub authentication for both the grafanas.

**Comment by choldgraf** [comment]
We now have authentication for all of our grafanas, so closing this
