### ISSUE TITLE
Outdated comment about `proxy.secretToken`

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1090]
As a followup to #756: We have an outdated comment about `proxy.secretToken`. It can be updated to say that we still set one or two `hub.services.<some-jupyterhub-service-name>.apiToken` values via the common secret. We don't set `proxy.secretToken` like described, but we set:
1. An JupyterHub API token used by the deployer script providing admin access against the JupyterHub to run health checks
2. An JupyterHub API token used by components in the dask-gateway helm chart to authenticate jupyterhub users

### Outdated comment

https://github.com/2i2c-org/infrastructure/blob/31a1d8c2dedb3d58bf61b482112f2fb8856669d6/deployer/deploy_actions.py#L184-L210

### Source code using the common secret seed

https://github.com/2i2c-org/infrastructure/blob/31a1d8c2dedb3d58bf61b482112f2fb8856669d6/deployer/hub.py#L166-L193

---

Hmmm I could probably just have opened a PR to solve this instead of writing an issue about it I realize - sorry!

**Comment by damianavila** [comment]
> Hmmm I could probably just have opened a PR to solve this instead of writing an issue about it I realize - sorry!

Well... the PR is still welcome 😜 ja ja

**Comment by consideRatio** [comment]
I recall Yuvi fixing this
