### ISSUE TITLE
Move off manually maintained NFS servers on GCP

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1105]
### Context

On pilot-hubs cluster as well as cloudbank (I think?) user home directories are on a hand-rolled NFS VM. This is problematic - when it fills up, it is a bit complex to resize, and while resizing a PD is fairly standard, I don't think we have it documented.

We should just switch over to paying money for [Google Filestore](https://cloud.google.com/filestore).

This is one of those issues that isn't an issue until it is, and when it is an issue, it's a big issue.

### Next steps

- [x] Figure out which clusters are using hand-rolled NFS
- [x] Modify appropriate cluster tfvars to enable google filestore creation
- [x] Migrate data from current NFS server to google filestore
- [ ] Decomission old NFS VM

**Comment by yuvipanda** [comment]
Only the shared 2i2c cluster on GCP is still using a manual NFS server now. Let's get rid of it before it goes critical and requires someone with XFS knowledge to fix.

**Comment by yuvipanda** [comment]
rsync takes about 44 minutes now.

**Comment by yuvipanda** [comment]
While doing https://github.com/2i2c-org/infrastructure/pull/2672 I discovered that the cloudbank cluster *also* uses a manually setup NFS server! Good catch, and I'll eventually migrate that one too. This will make our cluster design more uniform everywhere.

**Comment by yuvipanda** [comment]
Am running the same copy steps for cloudbank hubs as well now.

**Comment by yuvipanda** [comment]
Everything on the 2i2c shared cluster has been migrated, and I've shut down the original VM! I'll clean it up in a few days if everything is alright.

**Comment by yuvipanda** [comment]
Copy completed on cloudbank for in about 17h. Will run rsync and prep

**Comment by yuvipanda** [comment]
rsync takes about 50m to complete now! I'll just leave it running in a loop, and find an opportune moment to deploy.

**Comment by yuvipanda** [comment]
still waiting for an opportune moment without any skyline users.

**Comment by yuvipanda** [comment]
Cloudbank fully migrated, and the NFS server there has been shut down! I'll wait for a week then kill it.


I've also deleted the disk of the 2i2c shared cluster, although a snapshot remains. I've left the NFS server on still, just in case we need to bring it back up. I'll kill it in a week.

**Comment by consideRatio** [comment]
Wieeee thank you for working this @yuvipanda!!!! I feel a sense of relief with fewer cluster/hub specific exceptions to consider!

**Comment by yuvipanda** [comment]
All cleaned up now!
