### ISSUE TITLE
Apply credits for the uwhackweeks account

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1142]
### Background and proposal

We have credits for the uwhackweeks account and we should apply them! While we're at it, we should also add some basic docs about how to do this.

### Updates and ongoing work

- [x] @scottyhq : Can you confirm that we should apply the new credits to the **same account** as the one the uwhackweeks are currently running on? (e.g., for future hackweeks do you want to just re-use the same account?)
- [x] Apply the credits
- [ ] Document how to apply credits on AWS in our team docs

**Comment by scottyhq** [comment]
> @scottyhq : Can you confirm that we should apply the new credits to the same account as the one the uwhackweeks are currently running on? 

Confirmed. Would be great to know our total spending and rate over these last couple weeks.

> (e.g., for future hackweeks do you want to just re-use the same account?) 

From our point of view we just need to isolate costs between events. Not sure if it is easier on your end to re-use the account or just create new ones: Maybe easier cost tracking, but other pains such as having to again deal with the default AWS quotas?...

**Comment by choldgraf** [comment]
Here are your costs so far this month (~$620 total)! Curious how this compares to your typical usage.

![image](https://user-images.githubusercontent.com/1839645/160032717-17d8eccf-fb7b-424e-97b5-96967cdfa887.png)

**Comment by choldgraf** [comment]
I'll plan on just applying the credits to the same account, otherwise it's going to generate a bunch of toil if we need to create a new account for each event. If @scottyhq is OK with it, we can guesstimate the cloud usage via the plot above.

**Comment by choldgraf** [comment]
OK credits are applied!

I've also got https://github.com/2i2c-org/infrastructure/pull/1148 to document this process a bit.
