### ISSUE TITLE
rstudio on utexas image?

### ISSUE THREAD

**Issue by jameshowison** [2i2c-org/infrastructure#1147]
### Background and proposal

**Context**
The utexas image is non-default due to the postgres stuff.  I thought rstudio was available, but it seems it is not?  I base that on going to https://utexas.pilot.2i2c.cloud/user/jameshowison/rstudio which shows a 404.

**Proposed solution**
While I don't plan to use rstudio for the current course, it would be useful to demo to people. Could we add 

(btw, let me know if this should be posted as an issue at https://github.com/2i2c-org/utexas-image or is here preferred?)

**Comment by yuvipanda** [comment]
@jameshowison you should be able to add a `runtime.txt` file to your image and get RStudio! I just updated docs on how to do that here: https://github.com/jupyterhub/repo2docker/pull/1147. Can you try that out? 

We're trying to figure out a process to make image changes as sustainable and self-serve as possible (https://github.com/2i2c-org/infrastructure/issues/1145), so would love for you to trial this process out with us :)

**Comment by jameshowison** [comment]
Thanks.  Got around to this today :)  I'm having a little trouble following the sequence.  See commentary here: https://github.com/2i2c-org/infrastructure/issues/1158

**Comment by yuvipanda** [comment]
Thanks a lot for helping us test and make this better, @jameshowison! Do you have it working now?

**Comment by damianavila** [comment]
AFAIK this is actually live, so I am closing this one.
Feel free to reopen if you disagree @jameshowison.
