### ISSUE TITLE
[AWS] Email alert about free-tier limit being reached

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1152]
### Background and proposal

We recently got an AWS alert email that the "free tier" limit for storage will be reached soon. Here is an image:

![image](https://user-images.githubusercontent.com/1839645/160461401-6681a676-a90a-4fd2-9b0b-87aef899cec4.png)

This is for account `746653422107`, which is our "main" AWS account, not the uwhackweeks one.

We should confirm that this is expected and will not result in a problem with one of our hubs. Does anybody have an idea?

**Comment by yuvipanda** [comment]
Hmm, interesting that it came from the 'main' account - there are no EFS resources there. I verified there are none in any region using https://stackoverflow.com/questions/44391817/is-there-a-way-to-list-all-resources-in-aws. So perhaps the usage in uwhackweeks triggered an alert in our main account?

**Comment by damianavila** [comment]
> So perhaps the usage in uwhackweeks triggered an alert in our main account?

Probably... 
Since you have verified there is no EFS resource there, I think we should just close this one.
Feel free to reopen if you disagree.
