### ISSUE TITLE
Deploy pd-balanced change to cloudbank & pangeo-hubs repo

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1153]
_Originally posted by @yuvipanda in https://github.com/2i2c-org/infrastructure/issues/1124#issuecomment-1072252732_

This change hasn't been deployed to cloudbank and pangeo-hubs repos yet, as they seem to always have users on when I look :) It's not urgent, but I'll keep an eye on it and do it as soon as I can.

Deploy to following clusters:

- [ ] cloudbank
- [x] pangeo-hubs

**Comment by yuvipanda** [comment]
pangeo-hubs will also need #1130 to be deployed

**Comment by damianavila** [comment]
> pangeo-hubs will also need https://github.com/2i2c-org/infrastructure/pull/1130 to be deployed

Happened in #1160.

**Comment by yuvipanda** [comment]
cloudbank still needs this deployed.

**Comment by yuvipanda** [comment]
The enterprising students using cloudbank went to sleep tonight, so I was able to roll this out!
