### ISSUE TITLE
Major documentation structure for helping our team debug issues

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1167]
### Context

In our latest incident on CarbonPlan @yuvipanda and I had some conversation about ways to lower the barrier for people to debug our cloud infrastructure when incidents occur. We agreed it would be helpful to have some basic documentation to help our team members get started with debugging common things.

### Proposal

We've got an outline of major areas of documentation to write to make it easier for people to use our docs in the debugging/operations process. Here's that document:

https://hackmd.io/omFosDsjS3-2UEtAIZstcA

Here are the documents outlined there that we should create

- [x] https://github.com/2i2c-org/infrastructure/pull/1176
- [x] https://github.com/2i2c-org/infrastructure/issues/1891
- [x] https://github.com/2i2c-org/infrastructure/issues/1144
- [x] https://github.com/2i2c-org/infrastructure/issues/1890
- [x] https://github.com/2i2c-org/infrastructure/issues/1893
- [x] https://github.com/2i2c-org/infrastructure/issues/1892
- [x] https://github.com/2i2c-org/infrastructure/issues/1892
- [ ] Howto: Enable shared directory
- [x] https://github.com/2i2c-org/infrastructure/issues/996#issuecomment-1308246131
- [ ] https://github.com/2i2c-org/infrastructure/issues/2272

We should flesh out the major sections in that HackMD, and update this issue as we do so with refs to PRs that implement things. We can close the issue once we've got docs that cover the major parts of that HackMD.

### Updates and actions

- [x] https://github.com/2i2c-org/infrastructure/pull/1177
- [x] https://github.com/2i2c-org/infrastructure/pull/1176
- [x] #1826

**Comment by yuvipanda** [comment]
A more structured way to think about this is in terms of the 'objects' we have and the 'actions' that can be performed on them.

A starter pack would be:

| Object | Verbs |
| - | - |
| Cloud account | Provision, authenticate, view web console, etc |
| Kubernetes cluster | Authenticate, explore objects in `kubectl`, look at logs, etc |
| Hub | View full config of, change config of, create, decomission, deploy change to, look at logs for, find out community rep, etc |
| User image | Create repo, setup image, debug changes, etc |

A lot of these have detailed documentation and trianing provided elsewhere (`kubectl` for example), so we should strike a balance between writing our own custom docs, linking to upstream docs, and improving upstream docs.

**Comment by yuvipanda** [comment]
I think it'll also help us identify *required* training that we can ask folks to take as part of onboarding so they have time set aside to learn how to use and navigate the tools we use. We stand on the shoulders of giants and we gotta use them!

**Comment by damianavila** [comment]
This exercise would also help us identify which pieces we can build to help in the process (ie. a quick way to get a cmd line ready to write `kubectl` commands to start debugging).

**Comment by yuvipanda** [comment]
We are working on structure for more docs to be written to make support steward work less stressful - https://hackmd.io/omFosDsjS3-2UEtAIZstcA.

**Comment by choldgraf** [comment]
I see that the two PRs attached to this one have now been merged. Can we close this one? If not, can we define some deliverables that we can use to know when this issue should be closed?

**Comment by yuvipanda** [comment]
@choldgraf i've lifted the list of documents from the hackmd to the issue body. We can close this when those are written!

**Comment by yuvipanda** [comment]
From https://github.com/2i2c-org/infrastructure/pull/1314#discussion_r874617094, we should also develop guides for GPU debugging.

**Comment by choldgraf** [comment]
added to the list at the top 👍

**Comment by choldgraf** [comment]
I'd like to unassign myself from this one - I am more than happy to help with documentation, but I don't think that I will have the time to _spearhead_ any of the efforts on this one. I would be happy to be tagged-in as a support person though, or to review PRs etc.

**Comment by sgibson91** [comment]
Ok, here's what _I think_ we already have covered in our docs. It may be that these docs don't quite cover what Chris and Yuvi had in mind when they came up with this list, or they are _outdated_.

| List item | Docs link |
| --- | --- |
| Howto: Find where something is configured | https://infrastructure.2i2c.org/en/latest/topic/config.html |
| Topic: Cluster design | https://infrastructure.2i2c.org/en/latest/topic/cluster-design.html |
| Topic: Home directory storage | https://infrastructure.2i2c.org/en/latest/topic/storage-layer.html |
| Topic: GPU configuration (but _not_ debugging) | https://infrastructure.2i2c.org/en/latest/howto/features/gpu.html |

**Comment by yuvipanda** [comment]
I'm going to close this one, as I think whatever improvements that were made during this push are complete by now.
