### ISSUE TITLE
RStudio Plots Panel broken in demo.2i2c.cloud hub

### ISSUE THREAD

**Issue by ibreckhe** [2i2c-org/infrastructure#1172]
### Context

The RStudio plots panel is currently broken in the demo hub, which prevents regular REPL use. For example, running:

``` r
x <- runif(100,0,1)
y <- 0.5 + x * 0.5 + rnorm(100,0,sd=0.5)
plot(x,y)
```
Does not produce plot output, but throws a warning message:
```r
R graphics engine version 14 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
```
This could be due to a mismatch between versions of R (4.1.2) and RStudio (1.2.5042), possibly related to this issue:[[
]https://discourse.jupyter.org/t/solved-latest-rstudio-will-not-work-with-jupyterhub-or-binder-use-r-version-4-0/10957](https://discourse.jupyter.org/t/solved-latest-rstudio-will-not-work-with-jupyterhub-or-binder-use-r-version-4-0/10957)

**Comment by yuvipanda** [comment]
Thanks for letting us know, @ibreckhe! I'll try take a peek.

**Comment by yuvipanda** [comment]
We probably need to use a newer version of RStudio probably. I actually think perhaps an easier way now is to bring back the utexas-demo hub...

**Comment by damianavila** [comment]
We are proposing to decommission the demo hub (https://github.com/2i2c-org/infrastructure/issues/3163) because of researchdelight existence (already with support to R stuff). Closing here.
