### ISSUE TITLE
Feature request: delete list of users in one go in the JupyterHub admin panel

### ISSUE THREAD

**Issue by erinmr** [2i2c-org/infrastructure#1213]
### Context

It would be great if we could delete a list of users as an admin.

**Comment by damianavila** [comment]
Thanks for opening the issue with your feature request, @erinmr.
We will evaluate the request and prioritize accordingly.

**Comment by yuvipanda** [comment]
@erinmr as an alternative, would using GitHub teams to manage access to the hub work better for you?

**Comment by erinmr** [comment]
We would love that!

**Comment by yuvipanda** [comment]
@erinmr i've opened https://github.com/2i2c-org/infrastructure/issues/1222 to track moving Openscapes hub to use GitHub teams based auth. Can you comment there on a timeline that would be helpful for you?

I'm gonna close this one as I think https://github.com/2i2c-org/infrastructure/issues/1222 is the better way to do this.
