### ISSUE TITLE
Add gh-scoped-creds to images

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1220]
### Context

This is a tracker issue for: 
* https://github.com/pangeo-data/pangeo-docker-images/pull/305
* https://github.com/conda-forge/staged-recipes/pull/18710
* 
### Updates and actions

Feel free to provide feedback there, thanks!

**Comment by damianavila** [comment]
Upstream PR was merged, so closing this one.

**Comment by damianavila** [comment]
Reopening to also keep track of this one: https://github.com/conda-forge/staged-recipes/pull/18710

**Comment by GeorgianaElena** [comment]
https://github.com/conda-forge/staged-recipes/pull/18710 seems to be merged so closing this one too.

**Comment by damianavila** [comment]
A follow-up question recently was brought up by conversations with @fperez in Slack.
When do we want to offer this one to all of our hubs?

**Comment by fperez** [comment]
At least for the Eddy one :)

**Comment by yuvipanda** [comment]
@fperez it is already on the Eddy one! I think we should make it standard to everything

**Comment by fperez** [comment]
Ah, perfect, thx! And 100% agreed, I consider that must-have functionality at this point.
