### ISSUE TITLE
Update daskhub's to use dask-gateway version 2022.4.0

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1224]
I've cut a release and updated JMTE to use version 2022.4.0 of dask-gateway.

See [the changelog](https://gateway.dask.org/changelog.html) on how to upgrade the Helm chart. It should not be a breaking change if users have the 0.9.0 dask-gateway client installed in their images still.

**Comment by consideRatio** [comment]
I labelled this as support as its now also something wishes for us to have in the LEAP hub.

I suggest that we get https://github.com/2i2c-org/infrastructure/pull/1251 merged to close #1258, and then whoever in @2i2c-org/tech-team is willing, goes for it by first opening a PR to update the dask-gateway version, and then before merge applies the new CRDs according to the changelog notes to _each cluster_ (once per cluster, not once per hub) we have that maintain that use dask-gateway.

**Comment by GeorgianaElena** [comment]
I've just assigned myself to this since I'm currently investigating the schema validation errors that came up in https://github.com/GeorgianaElena/pilot-hubs/tree/bump-dask-gateway.

Also, I think it's quite important and shouldn't take long, so I'm giving this a try now.

**Comment by consideRatio** [comment]
Looking at dask-gateway's helm chart's default values.yaml file, i see extraConfig listed under `gateway.extraConfig` while I saw an error listed about us declaring `dask-gateway.extraConfig` instead of `dask-gateway.gateway.extraConfig`. The schema catches actual misconfiguration errors wieee!
