### ISSUE TITLE
Howto about migrating a user's directory to another username

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1225]
### Context

This is coming from a Freshdesk support ticket: https://2i2c.freshdesk.com/a/tickets/122

@consideRatio shared a k8s Pod manifest to perform the migration: https://2i2c.slack.com/archives/C028WU9PFBN/p1650560320277699

@yuvipanda shared some edits on the manifest here: https://2i2c.slack.com/archives/C028WU9PFBN/p1650562288977739?thread_ts=1650560320.277699&cid=C028WU9PFBN

### Proposal

Port all this info into a howto section in our infra docs.

### Updates and actions

* [ ] who is willing (and has the time) to write the docs, @consideRatio WDYT? Maybe @yuvipanda can review the PR in-depth since he used it?

**Comment by consideRatio** [comment]
I hope it is okay that I say no to help out further with this.

I'm generally conflicted about how to spend time, but I think I've in generally surpassed the amount of time I can justify spending with 2i2c given my statement of work with JMTE and failing to catch up with JMTE needs.

**Comment by damianavila** [comment]
> I hope it is okay that I say no to help out further with this.

It is totally OK! Thanks for letting us know!
