### ISSUE TITLE
Bug in deploy-hubs.yaml causing upgrade-prod-hubs job to wait for pending jobs that won't arrive

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1233]
## Current understanding

- `upgrade-support-and-staging` job is allowed to fail with the next jobs in the workflow allowed to execute
- However, we need to use `always()` to ensure the next jobs _do_ actually execute and aren't skipped due to some unknown magic happening in GitHub Actions
- Using `always()` alone meant that the `upgrade-prod-hubs` job would be left in a "Waiting for pending jobs" state, even when no jobs were coming because the `prod-hubs-matrix` was an empty list.
- We add a job status check of `filter-generate-jobs` to the conditional of `upgrade-prod-hubs` to ensure this job _only runs if `filter-generate-jobs` was successful` and the rest of the condition is also respected too.
- The overall status of the workflow will always be failed if any of the `upgrade-support-and-staging` matrix jobs fail - even if the rest of the jobs successfully complete.

### Context

We have a bug, probably in the `if` statement for the `upgrade-prod-hubs` job, causing that job to register as failed instead of skipped. See screenshot below.

<img width="1900" alt="Screenshot 2022-04-25 at 13 29 43" src="https://user-images.githubusercontent.com/44771837/165089432-2b2f5a01-8377-4a96-bde4-01580b6e30c9.png">

The output of `generate-jobs` for this run was nothing, so I'm certain the job should have been skipped.

<img width="714" alt="Screenshot 2022-04-25 at 13 32 13" src="https://user-images.githubusercontent.com/44771837/165089612-2350b149-b567-4738-b72f-ae2a2ebe9800.png">

Run in question: https://github.com/2i2c-org/infrastructure/actions/runs/2219349118

`if` block in question: https://github.com/2i2c-org/infrastructure/blob/82c550c818924930b9b17550e3d9b309979d8742/.github/workflows/deploy-hubs.yaml#L209-L212

**Comment by sgibson91** [comment]
My instinct is maybe the `always()` is being evaluated first?

**Comment by choldgraf** [comment]
I think it is pretty cool that this nifty output table makes it easier to debug these kinds of things.

**Comment by sgibson91** [comment]
I did some experimenting over here: https://github.com/sgibson91/testing-gh-actions/blob/main/.github/workflows/chained-failure.yaml

Seems that indeed, any failure causes future jobs to be skipped without `always()` - even when a dependent job that has `always()` completes. It also seems that the overall status of the workflow is fail, even if the rest of the jobs execute successfully. I don't really like this (I think the status could be more nuanced/informative), but I guess we need to know that something went wrong at the support/staging phase either way.

I will update the top comment and have already updated the linked PR.
