### ISSUE TITLE
Move uwhackweeks to a faster EFS server

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1236]
### Context

In https://2i2c.freshdesk.com/a/tickets/113, it was reported that the home directories for the uwhackweeks weren't fast enough for some tasks. We can improve performance here by switching to a higher EFS tier, at some cost. 

### Proposal

- [ ] Make 'tier' an option in our terraform, so we can give different hubs different price / performance ratios
- [ ] Move the uwhackweeks hub to have a faster home directory EFS

**Comment by scottyhq** [comment]
> Make 'tier' an option in our terraform, so we can give different hubs different price / performance ratios 

This would be great in my opinion! The last time I read the EFS docs I found it hard to digest the various options, so even 'fast', 'faster', 'fastest' would be a nice abstraction to chose from :) 

I was thinking it could be good to add a note here on encouraging users to use `/tmp` for temporary (but faster) storage. Thoughts? 
https://docs.2i2c.org/en/latest/user/storage.html

**Comment by damianavila** [comment]
> I was thinking it could be good to add a note here on encouraging users to use /tmp for temporary (but faster) storage. Thoughts?
> https://docs.2i2c.org/en/latest/user/storage.html

I think that would be a nice addition, do you want to try with a PR, @scottyhq? 😉

**Comment by consideRatio** [comment]
I've added notes about the ideas in this issue in the somewhat related issue https://github.com/2i2c-org/infrastructure/issues/2242 for now. Since this mentions uwhackweeks and we have terminated that cluster, I'll go for a close here.
