### ISSUE TITLE
Are there backups to NFS mounted home directories?

### ISSUE THREAD

**Issue by betolink** [2i2c-org/infrastructure#1238]
### Context

A scientist with the Openscapes cohort was working with some notebooks and attempted a `git rebase` that ended up deleting some of her work, she does not have a copy and asked me if we could restore her home directory to how it was yesterday. I don't know if there are backups (daily or otherwise) for our home directories (I think they are EFS mounts).

**Comment by betolink** [comment]
It seems like a little bit of git Kung Fu fixed our problem but the issue remains open, what should we do in those cases where the data loss is beyond git recovery?

**Comment by yuvipanda** [comment]
I don't think there are backups that aren't for disaster recovery only. In general our backups are pretty weak, and this is something we need to fix.

I'm glad you were able to recover this with some git-fu, @betolink!

**Comment by damianavila** [comment]
@yuvipanda, IIRC we are backing up the EFS: https://github.com/2i2c-org/infrastructure/blob/master/kops/setup-efs.py#L62
And, IIRC, AWS backup functionality has some granularity to recover directories on a per-date basis.

> I don't think there are backups that aren't for disaster recovery only.

Do you consider the above functionality I described a DR backup? Just trying to understand if we are talking about the same thing 😉. Thanks!

**Comment by yuvipanda** [comment]
@damianavila the setup-efs.py file is only used for kops, which only farallon uses. Everything else comes from https://github.com/2i2c-org/infrastructure/blob/master/terraform/aws/efs.tf which doesn't have backups enabled. So we don't really have anything :D

**Comment by consideRatio** [comment]
I'm closing this in favor of #2371 and #2370.
