### ISSUE TITLE
API resources interrupted. Error relating to k8s secret on deploy of new hub. 

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1255]
### Context

I was deploying a brand new JupyterHub to the 2i2c cluster and got the following error about not being able to read the Kubernetes secret containing the API token, I assume because it hadn't been made yet so we probably need to leave a pause or check the secret exists before trying to read it. When I ran the deployer a second time it worked fine.

The other thing to consider here is that I'm at the Turing today and (_for some reason_) their firewall doesn't allow me to connect to the k8s API over their Wifi, so I'm tethered to 4G via my phone. So the first thing to check is whether this error occurred due to the weird connectivity conditions at the Turing.

```
Deploying hub dummy...
Running helm upgrade --install --create-namespace --wait --namespace=dummy dummy /Users/sgibson/source/github/2i2c-org/pilot-hubs/helm-charts/basehub --values=/var/folders/hb/3kw2n13d17l7rnljn9jgplr00000gn/T/tmpus2v5s_j --values=/Users/sgibson/source/github/2i2c-org/pilot-hubs/config/clusters/2i2c/dummy.values.yaml --values=/var/folders/hb/3kw2n13d17l7rnljn9jgplr00000gn/T/tmpysx2hmst
Release "dummy" does not exist. Installing it now.
lookup_func.go:111: [ERROR] unable to retrieve resource list for: v1 , error: Get "https://104.198.26.247/api/v1?timeout=32s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
lookup_func.go:85: [ERROR] unable to get apiresource from unstructured: /v1, Kind=Secret , error Get "https://104.198.26.247/api/v1?timeout=32s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Error: template: basehub/charts/jupyterhub/templates/hub/secret.yaml:40:42: executing "basehub/charts/jupyterhub/templates/hub/secret.yaml" at <include "jupyterhub.hub.config.JupyterHub.cookie_secret" .>: error calling include: template: basehub/charts/jupyterhub/templates/hub/_helpers-passwords.tpl:55:26: executing "jupyterhub.hub.config.JupyterHub.cookie_secret" at <lookup "v1" "Secret" .Release.Namespace (include "jupyterhub.hub.fullname" .)>: error calling lookup: unable to get apiresource from unstructured: /v1, Kind=Secret: Get "https://104.198.26.247/api/v1?timeout=32s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/pilot-hubs/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Caskroom/miniconda/base/envs/pilot-hubs/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/sgibson/source/github/2i2c-org/pilot-hubs/deployer/__main__.py", line 7, in <module>
    cli.main()
  File "/Users/sgibson/source/github/2i2c-org/pilot-hubs/deployer/cli.py", line 142, in main
    deploy(
  File "/Users/sgibson/source/github/2i2c-org/pilot-hubs/deployer/deploy_actions.py", line 220, in deploy
    hub.deploy(k, SECRET_KEY)
  File "/Users/sgibson/source/github/2i2c-org/pilot-hubs/deployer/hub.py", line 249, in deploy
    subprocess.check_call(cmd)
  File "/usr/local/Caskroom/miniconda/base/envs/pilot-hubs/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--install', '--create-namespace', '--wait', '--namespace=dummy', 'dummy', PosixPath('/Users/sgibson/source/github/2i2c-org/pilot-hubs/helm-charts/basehub'), '--values=/var/folders/hb/3kw2n13d17l7rnljn9jgplr00000gn/T/tmpus2v5s_j', '--values=/Users/sgibson/source/github/2i2c-org/pilot-hubs/config/clusters/2i2c/dummy.values.yaml', '--values=/var/folders/hb/3kw2n13d17l7rnljn9jgplr00000gn/T/tmpysx2hmst']' returned non-zero exit status 1.
```

### Proposal

- [ ] Verify whether this error is repeatable when creating new hubs on a more permissive network

**Comment by consideRatio** [comment]
The k8s Secret that is read for the deployer scripts health check should be created and be available as soon as the JupyterHub Helm chart is being deployed, which will be even before hub pod etc is starting up.

So assuming we read the token just fetched from the k8s Secret just when are about to make a health test, we are likely not going to have issues with this as the health tests, as they should reasonably only run only when there is a hub deployed with `helm [install|upgrade]` already.

**Comment by sgibson91** [comment]
I wasn't running the health check when I got this error. I was running `deployer deploy` for a new hub.

**Comment by consideRatio** [comment]
@sgibson91 ah okay, this is a failure related to connectivity then I'm quite confident.

You got...

```
lookup_func.go:85: [ERROR] ...
```

This relates to the use of `lookup` here in the JupyterHub Helm chart: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/cedd0be43371a4dd2c554f3efc7a7b8f153b5228/jupyterhub/templates/hub/_helpers-passwords.tpl#L40

This call probably failed by not having proper connectivity, because if it gets a response about "there is no k8s secret" it would have been fine, but now it errors - so I assume its about attempting to lookup a k8s resource in the k8s cluster that fails by connectivity issues.

**Comment by sgibson91** [comment]
Yeah, I need a better plan for not doing k8s-based work if I also happen to be visiting the Turing 😆

**Comment by consideRatio** [comment]
Yeah doh =/
