### ISSUE TITLE
We should not define labels with other projects domain name

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1256]
I've seen a labels like `k8s.dask.org/node-purpose` be declared here in our config:

https://github.com/2i2c-org/infrastructure/blob/45e51afe8335e9f8efc700e3a95f3c21dd2bf36a/helm-charts/daskhub/values.yaml#L124-L125

It is a best practice that these should only be named like that if its a label defined to have purpose by people in dask.org. But, since I think this was defined by us to have meaning to us specifically, it should have been named something like `2i2c.org/...`, for example: `2i2c.org/node-purpose`.

It may be tricky to change this to a new label, so this ticket has no action point beside being read by @2i2c-org/tech-team. Let's close it after next sprint meeting.

**Comment by yuvipanda** [comment]
hmm, IMO we should upstream this into dask docs and suggest these as common labels to use across clusters, similar to how `hub.jupyter.org/node-purpose` is in z2jh config / docs. I think this is an extremely common use case across clusters, and sharing labels here would be helpful.

**Comment by sgibson91** [comment]
I agree that we should avoid 2i2c-specific things as much as is reasonably possible and upstream this practice to dask, or change to whatever best practice the dask community recommends.

**Comment by consideRatio** [comment]
I'm a bit confused about the discussion about upstreaming, as its not explicit what is being discussed to upstream.

> we should upstream this into dask docs

> upstream this practice to dask

If "this" refer to the practice of setting a label named `k8s.dask.org/node-purpose` on nodes, and setting nodeSelector/nodeAffinity on scheduler/worker pods to have an affinity towards the labelled nodes, then I disagree. I think it's out of scope to suggest specific node label names for both node/pod _unless the helm chart ships with coupling to some pre-defined node labels_ set on the pods.

If "this" refers to the JupyterHub Helm chart's feature to declare an affinity for pods towards nodes with a specific pre-defined label, then I agree its a viable enhancement proposal for the dask-gateway helm chart. It doesn't seem unreasonable to plan for such proposal to go through either.

**Comment by sgibson91** [comment]
We should try to avoid 2i2c-specific labels unless it is absolutely necessary, I think. Scheduling dask workers to specific nodes doesn't feel 2i2c-specific enough to warrant our own label as it's a reasonable thing for anyone managing a dask-enabled JupyterHub to desire. Therefore wherever the correct place is for this label to live upstream (dask, z2jh, something else?), we should do that instead.

**Comment by consideRatio** [comment]
There are three naming scenarios:

1. `2i2c.org/something`
2. `something`
3. `external.org/something`

The point I still insist on is that we shouldn't use type 3 named labels like `external.org/something` unless that is a label defined to have some meaning by `external.org`.

**Comment by consideRatio** [comment]
This doesn't have an action point so I'm closing it. It was just about me wanting us to avoid naming labels/annotations that we introduce like `external.org/...` going onwards.

> There are three naming scenarios:
> 
> 1. `2i2c.org/something`
> 2. `something`
> 3. `external.org/something`
> 
> The point I still insist on is that we shouldn't use type 3 named labels like `external.org/something` unless that is a label defined to have some meaning by `external.org`.
