### ISSUE TITLE
Update to dask-gateway 2022.4.0

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1259]
There is a new release of dask-gateway helm chart called 2022.4.0, it is backward compatible with dask-gateway clients versioned 0.9.0.

See [the changelog](https://gateway.dask.org/changelog.html) for notes on how to upgrade, there are manual steps that needs to be taken!

**Comment by GeorgianaElena** [comment]
@consideRatio, I believe this is a duplicate of https://github.com/2i2c-org/infrastructure/issues/1224, no?

**Comment by consideRatio** [comment]
Yepp thanks!
