### ISSUE TITLE
Policy for keeping k8s clusters updated to somewhat a similar version

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1271]
@GeorgianaElena just ran into failures because the k8s client (`kubectl`) used in the github virtual environment was bumped to 1.24.0, and since the version skew policy they have declares that it should be compatible with one minor above and two minor below, we can expect errors if `kubectl` interacts with a k8s cluster versioned <=1.21.

The resolution for now is probably is to pin the kubectl version to 1.23, which is compatible with 1.24 that is the recently released version of k8s, but also lower versions all the way down to 1.21 at least.

I'm not sure if there is a policy on upgrading the k8s clusters, but we should probably have one so that we don't fall behind too far where some clusters have very old versions and others have very new.

**Comment by consideRatio** [comment]
Closing as duplicate of #1271 with more concrete ideas

**Comment by sgibson91** [comment]
> Closing as duplicate of #1271 with more concrete ideas

But... this is issue 1271? What was the duplicated issue?

**Comment by consideRatio** [comment]
Woops thanks @sgibson91, I meant #412!
