### ISSUE TITLE
Deploy the support charts in the remaining three clusters

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1278]
### Context

We still have a few clusters where we don't deploy the supports charts to. This means that these clusters don't have grafana dashboards and can't be monitored through the central grafana at https://grafana.pilot.2i2c.cloud

### Proposal

Deploy the support chart for these clusters following the docs at https://infrastructure.2i2c.org/en/latest/howto/operate/grafana.html#deploy-the-support-chart

Note: we will need to tune their resource requests to match the smaller clusters.

### Updates and actions

Ref: https://github.com/2i2c-org/infrastructure/issues/328

List of clusters without the support chart:
- [x] leap -> is only missing the basicAuth prometheus setup https://github.com/2i2c-org/infrastructure/pull/1310
- [x] meom-ige -> https://github.com/2i2c-org/infrastructure/pull/1320
- [ ] farallon -> will be decommissioned, no need to deploy the support chart anymore https://github.com/2i2c-org/infrastructure/issues/1454

**Comment by sgibson91** [comment]
LEAP has support deployed :) One down already, way to go!

https://github.com/2i2c-org/infrastructure/blob/d4ed3007bd7f51425fe9a15b36c4cfd6e7932a97/config/clusters/leap/cluster.yaml#L8-L10

**Comment by sgibson91** [comment]
Ah good catch!

**Comment by damianavila** [comment]
Related: https://github.com/2i2c-org/infrastructure/issues/594

**Comment by GeorgianaElena** [comment]
Since farallon (last cluster without a support chart deployed) will be decommissioned soon, https://github.com/2i2c-org/infrastructure/issues/1454, I'll close this issue as completed.

**Comment by damianavila** [comment]
Awesome work, @GeorgianaElena!
