### ISSUE TITLE
Investigate jupyter-server-proxy issues on dask-enabled hubs

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1296]
### Ticket
Reported in https://2i2c.freshdesk.com/a/tickets/136

### Scenario

- Use the feature in https://jupyter-server-proxy.readthedocs.io/en/latest/arbitrary-ports-hosts.html
- The specific use case is to access the dask dashboard on *local* dask cluster (NOT dask gateway).
- A minimal reproducer can be found at https://discourse.pangeo.io/t/access-dashboard-for-localcluster-on-pangeo-deployments/2171/7 
- This issue is present on all 3 Pangeo-like hubs we are currently running: Pangeo Cloud, LEAP, M2LiNES

### Problem

Accessing arbitrary ports on the local notebook serverd does not appear to be working. 

**Note**

The Post https://discourse.pangeo.io/t/access-dashboard-for-localcluster-on-pangeo-deployments/2171 has more details and context

**Comment by consideRatio** [comment]
With https://discourse.pangeo.io/t/access-dashboard-for-localcluster-on-pangeo-deployments/2171/10?u=consideratio and #1503 i conclude this can be closed as resolved.
