### ISSUE TITLE
Update original Pangeo cluster with customized profile list based on group membership

### ISSUE THREAD

**Issue by rabernat** [2i2c-org/infrastructure#1307]
### Context

We recently made a lot of improvements to the Pangeo-style hub to support LEAP and M2LInES. We should now apply these retroactively to the original Pangeo community cluster at https://us-central1-b.gcp.pangeo.io/.

### Proposal

- [x] Create a github group in pangeo-data with extra privileges
- [x] Set up a profile list option like LEAP to allow these users to get a bigger notebook server
- [ ] Tweak the dask gateway settings (see #1293)

Alternatively, rather than working to synchronize configurations across three different hubs, we could instead pursue the "one spawner to rule them all" approach that @yuvipanda started to work on. This might be more efficient in the long run.

**Comment by yuvipanda** [comment]
I think for now we should just setup profiles via github groups. If you can create github groups, I can configure the permissions @rabernat.

**Comment by yuvipanda** [comment]
@rabernat so the pangeo hub is in us-central1-b, but that zone does not have any GPU support at all! We relocated m2lines and leap to us-central1-c for this, so if you want GPUs here we'll have to do that. This would involve some downtime and I *think* possibly also some home directory migration.

**Comment by yuvipanda** [comment]
@rabernat ok I changed the size of the instances and restricted the large profiles. Can you test it out?

**Comment by rabernat** [comment]
It works! Fantastic!

I will follow up later about GPUs if we decide that is necessary.
