### ISSUE TITLE
Extra profile_list options on main pangeo cluster

### ISSUE THREAD

**Issue by rabernat** [2i2c-org/infrastructure#1327]
### Context

On both LEAP and M2LInES clusters, we have extra options (large CPUs, GPUs, etc.) for people with certain status.

### Proposal

I would like enable this also for the original Pangeo cluster. Specifically, I would like members of `@pangeo-data/cds-lab` team to have the same `large`, `huge`, and `GPU` options as on the LEAP and M2LInES clusters.

These special privileges correspond to people directly funded by the grant that is supporting the cluster (Moore Foundation Climate Data Science Lab).

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/issues/1307 is related I think?

**Comment by damianavila** [comment]
Maybe a dupe (or maybe this one is a little bit more specific request), @rabernat can you clarify if that is the case?

**Comment by rabernat** [comment]
So sorry, my bad. 🤦
