### ISSUE TITLE
Automate bumping of pangeo images for m2lines / leap hubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1338]
### Context

We want to avoid manually needing PRs like https://github.com/2i2c-org/infrastructure/pull/1318. We also do that for utoronto, and basically any other hub with a separate image repo.

### Proposal

- [x] Setup https://github.com/sgibson91/bump-jhub-image-action to open automated PRs to bump pangeo images automatically
  - https://github.com/2i2c-org/infrastructure/pull/1339
- [ ] Document this as something to do whenever we use pangeo hub images
   - https://github.com/2i2c-org/infrastructure/pull/1433

**Comment by sgibson91** [comment]
@yuvipanda I have opened https://github.com/2i2c-org/infrastructure/pull/1339 to address the first action item

**Comment by damianavila** [comment]
> I'm going to turn off the schedule trigger for the action for now.

Good idea, this is the related PR: https://github.com/2i2c-org/infrastructure/pull/1350

Btw, I still see new PRs being opened, what am I missing here?

**Comment by sgibson91** [comment]
There's a workflow_dispatch trigger that I'm using to test if my updates are working or not - sorry for the noise!

https://github.com/2i2c-org/infrastructure/blob/2cd15169959c2577bab68642444ad0a4fea95272/.github/workflows/bump-image-tags.yaml#L4

**Comment by damianavila** [comment]
No problem, glad you are playing with it 😉

**Comment by sgibson91** [comment]
I finally got a sensible diff! https://github.com/2i2c-org/infrastructure/pull/1376 However, I think we need to be more nuanced with searching for new tags, I don't think the Pangeo community actually do want to pin to the images that have commit refs as tags for instance. So I will leave the schedule trigger off for now and work on that aspect when I come back next week.

**Comment by sgibson91** [comment]
I've got a PR that allows optionally providing a regex for the tags to bump to https://github.com/sgibson91/bump-jhub-image-action/pull/130

**Comment by sgibson91** [comment]
And this PR is bringing that update into this repo https://github.com/2i2c-org/infrastructure/pull/1405

**Comment by sgibson91** [comment]
I added some documentation [here](https://github.com/2i2c-org/infrastructure/pull/1433) which I believe will close this issue
