### ISSUE TITLE
Standardize on nodepool labeling conventions

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#136]
From @consideRatio in https://github.com/2i2c-org/pilot-hubs/pull/134#discussion_r541023273:

> The configuration scheduling.corePods.nodeAffinity.matchNodePurpose=require will make all core pods of the jupyterhub chart have a required node affinity toward the node label hub.jupyter.org/node-purpose=core.
>
> By using hub.jupyter.org/pool-name it seems like there is a predefined meaning of that label and can cause some confusion, it isn't having a predefined meaning right? If it is a label with meaning for the 2i2c.org pilot hubs, I think we should name it like 2i2c.org/pool-name instead.

We should investigate either node-purpose or switch to a different namespace.

**Comment by yuvipanda** [comment]
We'll3

**Comment by consideRatio** [comment]
> By using hub.jupyter.org/pool-name it seems like there is a predefined meaning of that label and can cause some confusion, it isn't having a predefined meaning right? If it is a label with meaning for the 2i2c.org pilot hubs, I think we should name it like 2i2c.org/pool-name instead.

The k8s label `hub.jupyter.org/pool-name` is no longer in use, we are instead referencing the k8s label `node.kubernetes.io/instance-type` for such purposes I think. We have also stopped using the `hub.jupyter.org` label prefix for labels we define (#1256).

I'll go for a close here, lets open a new issue if there is some concrete aspect to focus on remaining that I've failed to capture.
