### ISSUE TITLE
Develop an easy way to provide pangeo hubs for workshops & hackathons

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#137]
Many folks use the pangeo binders or hubs for their workshops. These usually last a week, need access to a notebook + dask + dataset. We should have a trivial way of setting up these hubs.

## Pricing

We should have a fixed labor cost that scales with the number of days the hub is active and then pass through cloud costs. Not sure what the right mix here is, but need to make sure it's sustainable for 2i2c.

## Features

- Cloud cost transparency, with a spending cap
- Dask, via dask-gateway
- Easy setup & spindown
- Environment is based on the pangeo docker images, with customization through the 'ONBUILD' variants
- Persistent home directory for users
- Persistent 'scratch' cloud bucket per-user
- Authentication via auth0. Admins of the hub (hackathon / workshop organizers) can control access without 2i2c staff involvement.
- Cloud bucket storage access for raw data.
- SFTP access to home directories for getting data in or out.
- Shared space, writeable by admins, for any datasets that must be stored on the filesystem rather than in a cloud bucket.
- Supported on GCP & AWS for now. 
- 2i2c controls the cloud account. However, if you have credits from the cloud provider that can be applied here, we can use that too.

## Non-features

- Specific help with the code itself
- Connection to other cloud services (like bigquery, redshift, etc)
- ??

**Comment by yuvipanda** [comment]
Questions to ask folks who want this:

1. Expected number of users
2. Dates of hackathon or workshop
3. Special dataset needs. Does this already exist in the cloud, or do we need to put new things up?
4. Is dask required?
5. What resources do you expect to use per person? If you have some materials already, that'll help.
6. Do you have cloud credits you can apply to this?
7. Pick an authentication provider from a list we support.

In return, we should give them a:

1. 2i2c labor price
2. Cost estimate for cloud usage

If this works out, we should then have a streamlined process for setting this up & tearing it down.

We could turn this into a google form.

**Comment by yuvipanda** [comment]
I've a draft google form here: https://docs.google.com/forms/d/10M3JYmL5vnyu5qp3d7OICJmmKmpuJ9VBkBMrLkoVaaM/edit?usp=sharing

**Comment by choldgraf** [comment]
I'm loving this form @yuvipanda - we should create something like this for each "type" of hub we want to offer.

A few quick thoughts:

- We probably want to charge a higher margin on these hubs to account for the fact that they will be short-lived, and that the "cost of sales" will be similar to the cost of offering a research-focused or edu-focused hub. **unless** we want to treat these hubs as ways to make it more likely for people to want their own dedicated hub.
- We may also want to "bundle" hubs somehow (e.g., if you're already paying for a research/edu hub, then we can provide event-based hubs at-cost or something like that?)
- We should make sure there's a clean story for how people would on-ramp and off-ramp on these hubs.

**Comment by yuvipanda** [comment]
>  we should create something like this for each "type" of hub we want to offer.

Totally!

> We probably want to charge a higher margin on these hubs to account for the fact that they will be short-lived, and that the "cost of sales" will be similar to the cost of offering a research-focused or edu-focused hub. **unless** we want to treat these hubs as ways to make it more likely for people to want their own dedicated hub.

I think we should treat it as a way to make it more likely for people to want their own dedicated hub. 




> We should make sure there's a clean story for how people would on-ramp and off-ramp on these hubs.

I agree!

On-ramp:

1. Authentication control
2. Resource limits tweaking
3. Data to be uploaded (if any)

Off-ramp:

1. Download users' home directories
2. Download any storage buckets present
3. Display a notice that hub no longer exists on hub home page
4. ???

**Comment by arokem** [comment]
- If the data is already in the cloud, it might be worth knowing where it is. It might intersect with the next question (preferred cloud provider). 

- You might want to know what time-zone the workshop is in, so that you can plan how to support it in real-time.

**Comment by scottyhq** [comment]
Nice! thanks for working on this @yuvipanda . A couple quick thoughts:

> Does your workshop need to use dask? 

I think a lot of workshops would work just fine if participants each have a few cores to work with Dask LocalClusters, might want to clarify need for dask-gateway/scalable cluster somehow. 

- it's common to need some specified buffer of time around the event (for example, hub is up 1 week before and 1 month after for a week-long workshop). 

- check out this awesome resource @aaarendt and @dhuppenkothen put together for guidance on running hackweeks at UW, including sample budgets https://uwescience.github.io/HackWeek-Toolkit. would be great to eventually link to 2i2c there!

**Comment by yuvipanda** [comment]
@scottyhq and @arokem - thank you for your feedback. I've made the following changes:

1. Ask explicitly if they need a *distributed* dask cluster, rather than a local one.
2. Explain 'buffer' around the workshop start & end dates.
3. Tweak section asking where the data is already hosted
4. Ask for participants' primary TZ

Experimentally, I've also set up the responses to go to a freshdesk.com setup for 2i2c (see https://github.com/2i2c-org/pilot-hubs/issues/86 for details). Freshdesk can be used almost exclusively by email. Hopefully, this will help us respond to these requests in a timely manner without requiring us to use more tools. We can also [integrate it with GitHub](https://support.freshdesk.com/support/solutions/articles/214680-the-github-app) if we need to.

I'm using Zapier.com to do this integration (see [this](https://zapier.com/shared/835334902a55f75542b61b48dfbaa24c779585ff)), so let's see how it goes.

**Comment by choldgraf** [comment]
@yuvipanda this looks good to me, I had a few minor edits to wording but don't have edit access (note that I believe if you get in the habit of creating google docs from your 2i2c.org account, I believe they will be default be accessible to anyone else with a 2i2c.org account as well...I'm trying to remember to do this myself but must admit it is hard haha).

**Comment by yuvipanda** [comment]
@choldgraf hmm, I did create this from my 2i2c.org account. I've added you as editor, but can't seem to get it to add everyone in 2i2c.org as editor.

Note that if you change any of the questions (not descriptions), I've to edit the Zapier integration. We should share that password too somehow.

**Comment by choldgraf** [comment]
ah sounds good - we should figure out a better integration long-term since editing Zapier each time a question changes feels quite brittle. I was just going to change a couple of small wording changes, I'll list them here so that you can track the changes and make the necessary Zapier edits as well:

- Start / end date questions should be sequential, ask for time zone after
- Why are we calling them "Pangeo hubs" out of the gate? Do we imagine creating a different form for a different kind of workshop? Or is this just a short-term thing and we'll work out a longer-term questionnaire approach via https://github.com/2i2c-org/handbook/issues/12
- we might want to add some caveats to the "we can locate the hub to be in the same cloud provider" question. Correct me if I'm wrong, but when we say "in the cloud" we really mean "in either AWS or GCP, and technically also Azure" right?
- Wanna -> "would like to"
- Perhaps a question about whether they have resources to pay for either cloud compute or labor? We can add a caveat that this isn't a strict requirement, but if somebody has some resources to help offset costs that they'd like to offer, it would be good to know about it.

**Comment by yuvipanda** [comment]
> Why are we calling them "Pangeo hubs" out of the gate? Do we imagine creating a different form for a different kind of workshop? Or is this just a short-term thing and we'll work out a longer-term questionnaire approach via [2i2c-org/handbook#12](https://github.com/2i2c-org/handbook/issues/12)

Good question. I think this can easily be a more generic 'workshop hub' form with some editing for wording, and conditional 'sections' to prevent too many optional questions.

However, I do want to communicate to users that they can use this to 'request a pangeo hub for my workshop' since the pangeo brand is fairly clear to most users. So maybe we can start here and go from there?

> we might want to add some caveats to the "we can locate the hub to be in the same cloud provider" question. Correct me if I'm wrong, but when we say "in the cloud" we really mean "in either AWS or GCP, and technically also Azure" right?

Yeah, totally. Not sure how to properly word this though. 

> Perhaps a question about whether they have resources to pay for either cloud compute or labor? We can add a caveat that this isn't a strict requirement, but if somebody has some resources to help offset costs that they'd like to offer, it would be good to know about it.

Definitely! Not sure how to phrase this either.

**Comment by choldgraf** [comment]
@yuvipanda are you OK with me just editing the form directly? I'm happy to do so but I just don't wanna create a mess with the zapier integration

**Comment by yuvipanda** [comment]
@choldgraf go for it. I'll modify the Zapier setup after you're done.

**Comment by choldgraf** [comment]
ok done, LMK if that looks OK
