### ISSUE TITLE
Deployment of cert-manager and dask-gateway require `kubectl apply -f <crd manifests>` step when version bumped

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1381]
Helm charts that include CRDs such as cert-manager and dask-gateway should typically by upgraded by doing `kubectl apply -f <crd manifests>` before being upgraded.

The "default upgrade procedure" of cert-manager is to do this `kubectl apply` step manually first, and users of dask-gateway upgrading from 0.9.0 to 2022.4.0 were supposed to do that as well at least for that release, probably in general as well.

For cert-manager, this can be done like in mybinder.org-deploy: https://github.com/jupyterhub/mybinder.org-deploy/blob/2db9dbdc8f51356713219dd2ddf72d0bb36723fb/deploy.py#L221-L253, and the same procedure can be used for dask-gateway.

## Action point

- [ ] Ensure automation managing dask-gateway includes `kubectl apply` of CRDs
   - https://github.com/2i2c-org/infrastructure/pull/1486
- [x] Ensure automation managing cert-manager includes `kubectl apply` of CRDs
   - https://github.com/2i2c-org/infrastructure/pull/1479

**Comment by sgibson91** [comment]
I wasn't sure what the manifest URL for dask-gateway was and couldn't find an example in the docs, so I only updated cert-manager for now, but happy to do dask-gateway as well.

**Comment by consideRatio** [comment]
@sgibson91 I made a note in the changelog for 2022.4.0 when an update was needed: https://gateway.dask.org/changelog.html#breaking-changes

**Comment by consideRatio** [comment]
Feel free to ping me for review @sgibson91!
