### ISSUE TITLE
Write validation test to check BinderHub's default values are up-to-date with basehub/daskhub

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1402]
**Action points:**

- [ ] Write Python code to determine whether binderhub helm chart values (and templates?) are up-to-date with basehub/daskhub where needed
- [ ] Write a GitHub Actions workflow that runs this validation whenever changes are made in the helm-charts folder

**Nice-to-haves:**

We could construct the GitHub Actions workflow such that:
* On pushes to master, a simple validation check is run. Fail if the configs don't match.
* On pull requests, commit the changes to the branch in the style of pre-commit

This might be a bit too presumptuous so I won't work towards this yet. Would be interested to know what people think.

**Comment by damianavila** [comment]
And maybe run it as an action periodically?

**Comment by sgibson91** [comment]
Sorry, this is converted from a note into an issue hence why it's sparse. In my head, it would be triggered as any changes happen in the helm-charts folders. Like the validation checks, etc.

**Comment by damianavila** [comment]
> In my head, it would be triggered as any changes happen in the helm-charts folders. Like the hub config validation checks, etc.

Even better! Thanks for the additional info.

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/issues/1280#issuecomment-1155431013 would negate the need for this, as we'd just ignore basehub completely.

**Comment by sgibson91** [comment]
@yuvipanda I think we need to have a discussion on what "ignore basehub completely" means. What features do we expect this BinderHub to have?

**Comment by sgibson91** [comment]
After a call Yuvi and I had "ignore basehub completely" meant "use the values Pangeo Binder was deployed with before" from here https://github.com/pangeo-data/pangeo-binder/blob/staging/pangeo-binder/values.yaml and not port across the templates just yet.

Closing this as this is not part of the MVP for the current BinderHub, we can reopen if needed.

Also closing:

* https://github.com/2i2c-org/infrastructure/pull/1401
