### ISSUE TITLE
Fix crashed prometheus on a few clusters

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1422]
### Context

In https://github.com/2i2c-org/infrastructure/actions/runs/2501414407, we see the support chart has failed in two clusters - pangeo-hubs and meom-ige. Investigating, it's because the prometheus-server is crashing, possibly from out of memory errors.

### Proposal

We should set better memory limits, or put other mechanisms in place to bring prometheus back up

**Comment by sgibson91** [comment]
I believe MEOM-IGE was fixed during the course of the below incident?

* https://github.com/2i2c-org/infrastructure/issues/1423

**Comment by sgibson91** [comment]
I addressed the pangeo-hubs cluster here

* https://github.com/2i2c-org/infrastructure/pull/1447

**Comment by damianavila** [comment]
Both clusters were addressed, so closing here.
Thanks, @sgibson91!
