### ISSUE TITLE
[Incident] MEOM hub is unreachable

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1423]
### Summary

The MEOM hub is currently un-reachable, and there are a number of Kubernetes errors on the cluster.

### Impact on users

The hub is totally unreachable. It returns `503 service temporarily unavailable`.

### Important information

- Hub URL: https://meom-ige.2i2c.cloud/
- Support ticket ref: https://2i2c.freshdesk.com/a/tickets/150
- Slack discussion: https://2i2c.slack.com/archives/C028WU9PFBN/p1655370839409829

### Tasks and updates

- [ ] Discuss and address incident, leaving comments below with updates
- [ ] Incident has been dealt with or is over
- [ ] Copy/paste the after-action report below and fill in relevant sections
- [ ] Incident title is discoverable and accurate
- [ ] All actionable items in report have linked GitHub Issues

<details>
<summary>After-action report template</summary>

```
# After-action report

These sections should be filled out once we've resolved the incident and know what happened.
They should focus on the knowledge we've gained and any improvements we should take.

## Timeline

_A short list of dates / times and major updates, with links to relevant comments in the issue for more context._

All times in {{ most convenient timezone}}.

- {{ yyyy-mm-dd }} - [Summary of first update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of another update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of final update](link to comment)


## What went wrong

_Things that could have gone better. Ideally these should result in concrete
action items that have GitHub issues created for them and linked to under
Action items._

- Thing one
- Thing two

## Where we got lucky

_These are good things that happened to us but not because we had planned for them._

- Thing one
- Thing two

## Follow-up actions

_Every action item should have a GitHub issue (even a small skeleton of one) attached to it, so these do not get forgotten. These issues don't have to be in `infrastructure/`, they can be in other repositories._

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]
```

</details>

**Comment by choldgraf** [comment]
# What we have tried so far

(times CET)

### 11am

Found this error in `templates-clone` init container:

```
Cloning into '/srv/repo'...
fatal: unable to access 'https://github.com/2i2c-org/default-hub-homepage/': Could not resolve host: github.com
```

but confirmed that GitHub status is OK

### 11:10

Re-deployed the hub, but the deploy hanged with several pods in `crashloopbackoff`. This included the hub, support, and cryptonono pods.

also got an OOM killed pod:

```
kube-system    gke-metadata-server-z7rqx                                 0/1     OOMKilled               0          76m
```

### 11:12

Deleted the hub pod, but this resulted in PVC problems

```
Normal   Scheduled           3m43s  gke.io/optimize-utilization-scheduler  Successfully assigned prod/hub-66f4b66579-t52vp to gke-meom-ige-cluster-core-pool-d987f2c6-v85f
  Warning  FailedAttachVolume  3m43s  attachdetach-controller                Multi-Attach error for volume "pvc-1167d029-2350-4ec4-841a-fe5db49c42ff" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedMount         100s   kubelet                                Unable to attach or mount volumes: unmounted volumes=[pvc], unattached volumes=[config secret files pvc custom-templates kube-api-access-jtx85]: timed out waiting for the condition
```

Hub pods now showing a "Repeated api_request to proxy pod" error:

```
[E 2022-06-16 09:59:31.289 JupyterHub app:2989]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2987, in launch_instance_async
        await self.start()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2762, in start
        await self.proxy.get_all_routes()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 898, in get_all_routes
        resp = await self.api_request('', client=client)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 862, in api_request
        result = await exponential_backoff(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 184, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Repeated api_request to proxy path "" failed.
```

we tried a bunch of different things over the next few hours, but it seems that there are non-repeatable and different failures happening each time.

### 15:00

Now seeing Timeouts and connection refused when `describe`ing the hub pod:

```
xceeded (Client.Timeout exceeded while awaiting headers)
  Warning  NodeNotReady            2m49s (x3 over 11m)  node-controller                        Node is not ready
```

and

```
Error from server: Get "https://10.128.15.212:10250/containerLogs/prod/hub-66f4b66579-hkqsk/hub?previous=true": dial tcp 10.128.15.212:10250: connect: connection refused
```

### 16:00

Current team is not sure what is going on, so awaiting other team members signing on to discuss and debug further

**Comment by damianavila** [comment]
The incident is over by now. @yuvipanda communicated the resolution in the support ticket.

> That's not externally accessible, but it will be posted here in the future.

Indeed.

**Comment by yuvipanda** [comment]
Looking at the linked slack messages, the issue was that the core nodepool was on 1.19, and the node was unhealthy - killing the nginx-ingress. Upgrading it (which also bounced the nodes) fixed the issue. #1804 will help with this, but am going to close this issue as done now.

**Comment by damianavila** [comment]
Thanks for writing up the summary, @yuvipanda.
