### ISSUE TITLE
[OpenScapes] Set up user_profiles and the image version updater bot

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1432]
### Context

In a recent conversation with @jules32 and @betolink we discussed some challenges that they're having around their environment as it becomes more complex. In the conversation we arrived at roughly the following:

- They would like to define multiple Docker images for various kinds of environments that they serve (e.g., R, Python, Julia)
- They'd also like each environment to be paired with a few different machine types.
- So they need `user_profiles`, BUT:
- They have been using the `configurator` to modify their image so far, and this is not compatible with `user_profiles`.

### Proposal

Ultimately, the thing they want to do is keep each of their environment images up-to-date as much as possible. We discussed two options:

1. Pin to `latest` somehow in their hub configuration for each image. However I'm not sure if this is possible.
2. Use @sgibson91's recent "helm image updater" action in conjunction with the OpenScapes config in order to keep their images up-to-date.
    - Ref link to the action: https://github.com/sgibson91/bump-helm-deps-action

Are either of those two options realistic? Can we help them out with one of these options?

**Comment by sgibson91** [comment]
We'll want to use the image bumper for this: https://github.com/sgibson91/bump-jhub-image-action The project you linked to bumps version of sub-charts in helm charts, not image tags :)

We already have the image bumper running in this repo so it's just a case of updating openscapes config and then adding the appropriate entries into that matrix: https://github.com/2i2c-org/infrastructure/blob/master/.github/workflows/bump-image-tags.yaml

I am also writing up docs about the two actions as we speak.

**Comment by sgibson91** [comment]
I think next steps are establishing which/how many profiles they would like. For each profile, we would need to know i) which machine type they want that profile to have, and ii) the image name they want that profile to have.

If the environment images don't yet exist, I would recommend the documentation on using our [hub image template](https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html) to create them :)

**Comment by sgibson91** [comment]
> They'd also like each environment to be paired with a few different machine types.

Also reading this again, we may need
* https://github.com/2i2c-org/infrastructure/issues/1253

**Comment by yuvipanda** [comment]
@sgibson91 that is only required if we want to offer 'sub-options' inside a profile. The profiles themselves can each offer an image. See https://github.com/2i2c-org/infrastructure/blob/master/config/clusters/m2lines/common.values.yaml#L94

**Comment by sgibson91** [comment]
@yuvipanda I know - I'm reading "They'd also like each environment to be paired with a few different machine types" as meaning they'd like user profiles with different images, with sub-options of machine types. But some clarity from the openscapes folks would be helpful here.

**Comment by jules32** [comment]
Pinging @betolink as the best person to speak to this :)

**Comment by betolink** [comment]
@yuvipanda @sgibson91 thanks for taking a look at this! 

In an ideal case scenario we would like to see something like this: 


![jhub](https://user-images.githubusercontent.com/717735/175978680-a5f6357c-2cc1-4350-a95f-e7f9348c852b.jpg)

Hub users could select which environment they want to use and then the machine type. These environments will be using whatever the latest tags are in the registry(Dockerhub for now). Ultimately we are looking for a mechanism to sync up our Docker images with the Openscapes hub.

Chris mentioned a Github action you folks were testing, I think it updates `values.yml` (or creates a PR for your infra project?) if there is a new image.

**Comment by sgibson91** [comment]
Thanks @betolink! #1253 is something we've been developing for the Pangeo hubs and basically allows the same thing (although I think the UI looks a little different). So a user can select an image tag from a drop-down and then merge that selection with a machine type.

> Chris mentioned a Github action you folks were testing, I think it updates values.yml (or creates a PR for your infra project?) if there is a new image.

Yes we have that which would be a good fallback option until we unblock the above issue and can roll out the UI you'd prefer.

**Comment by betolink** [comment]
Thanks @sgibson91 ! yeah it's basically the same. If that can be implemented in our hub it would be amazing! So far we have the Python and R images,(Matlab is next).  We can use `openscapes/python`(now called Corn) `openscapes/r` (we're building it this week) and `openscapes/matlab` from Docker hub.

**Comment by sgibson91** [comment]
@betolink we are unfortunately blocked on deploying that particular UI until we migrate all our hubs to z2jh/JupyterHub 2.0, but we can set you up with some "good enough" profiles for now while we push the migration forward? Or would you prefer to stick with what you have until we've upgraded?

**Comment by yuvipanda** [comment]
@betolink awesome! lmk once these are published and I can set these up

**Comment by betolink** [comment]
Hi @yuvipanda!

The Python and R images are now available in Docker hub, if you don't mind setting them up in our [staging hub](https://staging.openscapes.2i2c.cloud/hub/) that would be great! Matlab will have to wait for now. Thanks a lot!

`openscapes/python`
`openscapes/rocker`

the latest tags are using the last commit hash and `main` (maybe we should change it for `latest`)

**Comment by yuvipanda** [comment]
@betolink awesome! I'll get to this soon.

**Comment by betolink** [comment]
our matlab image is now available at `openscapes/matlab`, when you have time to get to this we'd like to include it in the profile as well.

**Comment by yuvipanda** [comment]
Great! I've it working looking like this:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/30430/179098429-8d084357-b90a-46df-ba95-5db7a25da958.png">

Will get it setup shortly, am a little busy at SciPy.

**Comment by jules32** [comment]
Hi @yuvipanda this is awesome, and thanks for thinking about it in between SciPy! 

Would it be possible to re-name the "Rocker" one to R? On our side, we named it "Rocker" because Docker wouldn't allow a single letter ("R"). Not sure that's a constraint here (and I realize it's an extra step to rename it here), but just thinking that many R users likely won't understand "Rocker" to mean R

**Comment by yuvipanda** [comment]
@jules32 absolutely, no problem. Would you want the R one to start on RStudio by default or JupyterLab?

**Comment by yuvipanda** [comment]
Can also have the matlab variant start in matlab.

**Comment by yuvipanda** [comment]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/30430/179119345-148b640e-c9a8-4086-8e6a-ce925ebb2fcb.png">

**Comment by yuvipanda** [comment]
Unfortunately whenever you update the docker image, you've to make a PR to this repo updating the tags here: https://github.com/2i2c-org/infrastructure/pull/1524/files#diff-3e6a6aaa229aa8ec507fc308feb5b502a0683705283d6c0497e3d991339f6a0fR80. The configurator doesn't support profiles yet :(

**Comment by jules32** [comment]
Thanks @yuvipanda ! Let's have R start in RStudio, thanks. 

Is the PR for tags because of this rename to "R" from "Rocker"? I think @betolink was expecting a PR but wanted to confirm it's the same

**Comment by yuvipanda** [comment]
It isn't because of the name change. The configurator ui just doesn't support profiles yet, so the PR is unfortunately necessary until that is added.

**Comment by sgibson91** [comment]
@yuvipanda I can setup the bump-jhub-image-action to automatically open the PRs for these

**Comment by yuvipanda** [comment]
@sgibson91 perfect!

**Comment by damianavila** [comment]
Since #1533 is merged, I think we can close this one now.
