### ISSUE TITLE
[Monitoring] Document the central Grafana

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1438]
### Context

We can now monitor the 2i2c clusters at https://grafana.pilot.2i2c.cloud, also called "the central grafana". However, there is little info about this in the docs https://infrastructure.2i2c.org/en/latest/howto/operate/grafana.html?highlight=central%20grafana#the-central-grafana

### Proposal

I propose adding more info about this central Grafana to our docs.

**Comment by colliand** [comment]
Can I please have access to the central Grafana dashboard? I am not certain how to associate my credentials.

**Comment by GeorgianaElena** [comment]
I opened https://github.com/2i2c-org/infrastructure/issues/1445 to discuss access to central grafana and to signal-boost the request

**Comment by choldgraf** [comment]
A quick thought from me, I think that we should put the "how to log in / use / etc" information in a different place than https://infrastructure.2i2c.org/en/latest/howto/operate/grafana.html . The information on that page is very engineering-heavy, and talks about things like Kubernetes, Helm Charts, etc. We want the documentation about how to use and understand this Grafana to be discoverable for non-engineers.

Maybe the easiest path forward would be to create a **Topic Guide** like "Monitoring and reporting", and add a page under this section like "Grafana Dashboards"...this could cross-link to the "how to deploy with Kubernetes" docs. I'm not positive on that though - if others think there's a better spot for it, please suggest!

**Comment by GeorgianaElena** [comment]
Actually, thinking about it now, how about instead we create these docs upstream, in `jupyterhub/grafana-dashboards` and reference it from 2i2c?
