### ISSUE TITLE
Allow access to multiple s3 buckets from the hub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1455]
### Context

From https://2i2c.freshdesk.com/a/tickets/149,

> We have some folks wanting to connect to existing buckets in other AWS accounts (s3://eis-dh-hydro). 
> 
> In the past we gave groups our service account identifier (arn:aws:iam::783380859522:role/jovyan-serviceaccount) to get permissions, and if I remember correctly I had to also add permissions to the service account policy...
> 
> What is the service account identifier I should use? Can I modify the necessary config, or do I need a 2i2c engineer to modify the policy?

**Comment by yuvipanda** [comment]
Tried to just grant access to the role specified in https://github.com/2i2c-org/infrastructure/blob/5951fb62599a55a8722b720a6ca534843449b371/terraform/aws/buckets.tf#L46 but that didn't work.

**Comment by choldgraf** [comment]
Can you flesh out the issue title? It is unclear what "different" refers to...is it scratch buckets?

**Comment by yuvipanda** [comment]
@choldgraf no idea how those words went missing! Fixed

**Comment by scottyhq** [comment]
I’ll have to loop you into the emails with the NASA account admin to double check the settings on their end...

Last year we also had to add explicit permissions to the hub service account policy, see here https://github.com/snowex-hackweek/jupyterhub/blob/main/terraform/eks/s3-data-bucket.tf 

Could also test with the following requester-pays bucket. I have no problem accessing this with full S3 permissions on my own AWS account, but from the snowex hub it is permission denied.

aws s3 ls --request-payer requester s3://usgs-landsat/collection02/

**Comment by scottyhq** [comment]
Just noting that aws_iam_role.irsa_role[each.value.hub_name].arn ->
https://github.com/2i2c-org/infrastructure/blob/5951fb62599a55a8722b720a6ca534843449b371/config/clusters/uwhackweeks/snowex.values.yaml#L4

..rather than adding each specific bucket though it seems like all S3 list,read permissions could be default (just exclude permissions to create and delete buckets)?

**Comment by yuvipanda** [comment]
Fixed by https://github.com/2i2c-org/infrastructure/pull/1488
