### ISSUE TITLE
Change deployer sub-scripts into deployer actions

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1472]
### Context

Currently, the `deployer` module has lots of useful functions, available as deployer actions https://github.com/2i2c-org/infrastructure/blob/master/deployer/README.md|

But there are also deployer "sub-scripts" like [`update_central_grafana_datasources.py`](https://github.com/2i2c-org/infrastructure/blob/master/deployer/update_central_grafana_datasources.py) or [`cilogon_app.py`](https://github.com/2i2c-org/infrastructure/blob/master/deployer/cilogon_app.py).

Having these sub-scripts in the same place with various deployer utilities makes it hard to know which one is which. 

### Proposal

We should have the sub-scripts ported as deployer actions.

### Updates and actions

Sub-actions to be taken here:

- [x] Move deployer/cilogon_app.py
- [x] Move deployer/update_central_grafana_datasources.py
- [x] Move shared/keys/decrypt-age.py

_No response_

**Comment by yuvipanda** [comment]
Sub-actions to be taken here:

- [ ] Move `deployer/cilogon_app.py`
- [ ] Move `deployer/update_central_grafana_datasources.py`
- [ ] Move `shared/keys/decrypt-age.py`
