### ISSUE TITLE
Revert our use of "Collaborative hub service" temporarily

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1474]
### Context

In these two Pull Requests, I misunderstood a suggestion from @yuvipanda about our use of "Collaborative hub service" instead of "Managed hub service":

- https://github.com/2i2c-org/docs/pull/148
- https://github.com/2i2c-org/team-compass/pull/422

He suggested that we merge the changes *without using the term Collaborative Service* and I accidentally merged before reverting that back.

### Proposal

We should swap back to the use of "Managed hub service"  for now, since Collaborative is a non-precise term. Instead, we should think about the right terminology via the issue below, and then change our docs when we think of something:

- https://github.com/2i2c-org/infrastructure/issues/1473

**Comment by yuvipanda** [comment]
opened PR https://github.com/2i2c-org/docs/pull/149

**Comment by damianavila** [comment]
The reversion was done, do we want to keep this open because of https://github.com/2i2c-org/docs/pull/149#pullrequestreview-1020670366 (team-compass references?). Otherwise, I would suggest closing it.
