### ISSUE TITLE
git permission denied when using gh-scoped-creds to push from hub to repo

### ISSUE THREAD

**Issue by TomNicholas** [2i2c-org/infrastructure#1511]
### Context

Hi, I'm trying to push some notebooks from the leap hub to a [repo](https://github.com/TomNicholas/hero-calc/tree/main), but getting git permission denied errors.

I followed [these instructions](https://docs.2i2c.org/en/latest/user/storage.html#using-git-github), which told me to run `gh-scoped-creds` in a terminal on the hub (fine) and follow the prompts. This is what happened:

```
(notebook) jovyan@jupyter-tomnicholas:~$ gh-scoped-creds
You have 15 minutes to go to https://github.com/login/device and enter the code: 71E5-F4A8
Waiting...........
Success! Authentication will expire in 8.0 hours.

Visit https://github.com/apps/leap-hub-push-access to manage list of repositories you can push to from this location
Tip: Use https:// URLs to clone and push to repos, not ssh URLs!
(notebook) jovyan@jupyter-tomnicholas:~$ git clone https://github.com/TomNicholas/hero-calc.git
Cloning into 'hero-calc'...
warning: You appear to have cloned an empty repository.
(notebook) jovyan@jupyter-tomnicholas:~$ cd hero-calc/
(notebook) jovyan@jupyter-tomnicholas:~/hero-calc$ cp ../hero-map_blocks/map_blocks.ipynb .
(notebook) jovyan@jupyter-tomnicholas:~/hero-calc$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        map_blocks.ipynb

nothing added to commit but untracked files present (use "git add" to track)
(notebook) jovyan@jupyter-tomnicholas:~/hero-calc$ git add map_blocks.ipynb 
(notebook) jovyan@jupyter-tomnicholas:~/hero-calc$ git commit -m "xr.map_blocks notebook"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'jovyan@jupyter-tomnicholas.(none)')
(notebook) jovyan@jupyter-tomnicholas:~/hero-calc$ git config --global user.email "thomas.nicholas@columbia.edu"
(notebook) jovyan@jupyter-tomnicholas:~/hero-calc$ git config --global user.name "TomNicholas"
(notebook) jovyan@jupyter-tomnicholas:~/hero-calc$ git push
error: src refspec refs/heads/master does not match any
error: failed to push some refs to 'https://github.com/TomNicholas/hero-calc.git'
(notebook) jovyan@jupyter-tomnicholas:~/hero-calc$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   map_blocks.ipynb

(notebook) jovyan@jupyter-tomnicholas:~/hero-calc$ git commit -m "xr.map_blocks notebook"
[master (root-commit) 2a7d893] xr.map_blocks notebook
 1 file changed, 4734 insertions(+)
 create mode 100644 map_blocks.ipynb
(notebook) jovyan@jupyter-tomnicholas:~/hero-calc$ git push
remote: Permission to TomNicholas/hero-calc.git denied to TomNicholas.
fatal: unable to access 'https://github.com/TomNicholas/hero-calc.git/': The requested URL returned error: 403
```

I was expecting it to ask for a git password or personal access token or something, but I can't actually find where I'm supposed to supply that.

This is probably something really simple, sorry! Any help appreciated though.

**Comment by yuvipanda** [comment]
@TomNicholas assuming this is the LEAP hub, you need to go to https://github.com/apps/leap-hub-push-access and 'install' it on the github repos you want to push to. gh-scoped-creds should've given you that link when you tried to authenticate - maybe the leap hub is using an older version?

**Comment by rabernat** [comment]
FYI I got it working following these instructions.

I think one challenge here is that this was an org repo and not all org members have the rights to install the app for the org.

**Comment by yuvipanda** [comment]
> I think one challenge here is that this was an org repo and not all org members have the rights to install the app for the org.

Right, I think that's part of the security process I think - so org admins have visibility into which remote systems (like this hub) can push there. In these cases, I'd suggest pushing to a fork and then merging into the upstream repo if pushing directly isn't an option.

**Comment by yuvipanda** [comment]
I'm not sure what the next action item here is. Where in the docs do you think this should go?

**Comment by damianavila** [comment]
I think we might have enough information here: https://docs.2i2c.org/en/latest/data/git.html and here: https://infrastructure.2i2c.org/en/latest/howto/features/github.html?highlight=gh-scoped-creds, maybe?

**Comment by yuvipanda** [comment]
@jmunroe can you provide an update on what happened here?

**Comment by jmunroe** [comment]
Sorry - I don't have a recollection on what else occurred on this issue I suspect it is historical at this point.

We have a new issue just opened about documenting gh-scoped-creds that I'll link to here for the back reference:
- https://github.com/2i2c-org/community-showcase/issues/65

and close this older issue.
