### ISSUE TITLE
Static web content URLs behave differently with trailing slash or not `/`

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1517]
The static web content is available at https://staging.2i2c.cloud/textbook/ but not at https://staging.2i2c.cloud/textbook (note the missing trailing slash)

I would have expected a redirect from https://staging.2i2c.cloud/textbook to https://staging.2i2c.cloud/textbook/ and then see the content.

Maybe something is missing from the nginx config?

**Comment by damianavila** [comment]
cc @yuvipanda

**Comment by yuvipanda** [comment]
Fixed in #1520 :)
