### ISSUE TITLE
Automatically test a dask-gateway notebook for daskhubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#152]
Once #149 is done, we should add a bunch of extra notebooks to validate that things work ok. Prime among them should be a notebook that validates dask-gateway is working. Here's the current code I use for that:

```
from dask_gateway import Gateway

gateway = Gateway()

cluster = gateway.new_cluster()
cluster.scale(1)
import dask.array as da
a = da.random.normal(size=(1000, 1000), chunks=(500, 500))
a.mean().compute()
```

This should print a float that's the mean of this random array we generated. Ideally, we'd also validate the dask gadget, but that's not necessary right now.

#151 should be also taken into consideration since dask clusters can be more expensive!

**Comment by yuvipanda** [comment]
More things to check:

1. Wiget is present: 
   <img width="693" alt="image" src="https://user-images.githubusercontent.com/30430/103059657-bf97b400-45cb-11eb-871c-ca3a52939c58.png">

2. dask dashboard is accessible.

**Comment by yuvipanda** [comment]
@GeorgianaElena do we do this now?

**Comment by GeorgianaElena** [comment]
The notebook part yes, but the widget and dashboard not :(

**Comment by yuvipanda** [comment]
@GeorgianaElena ah. Do you know manually if the widget and dashboard work?

**Comment by GeorgianaElena** [comment]
I'm not sure I'm checking this correctly... But some other things I noticed on dask-staging are:
- the dask-gateway service throws a 404
- the dask labextension and dashboard are available in JupyterLab

**Comment by yuvipanda** [comment]
@GeorgianaElena ah, that service UI is 404. Not sure what it is supposed to point to. I think that's a new UI feature of JupyterHub?

Glad the dashboard works!

**Comment by yuvipanda** [comment]
This is done now https://github.com/2i2c-org/infrastructure/tree/main/deployer/health_check_tests/test-notebooks/daskhub
