### ISSUE TITLE
Enable Coiled Analytics for Dask Gateway clusters

### ISSUE THREAD

**Issue by rabernat** [2i2c-org/infrastructure#1529]
### Context

We are using Dask heavily but don't have a lot of visibility into how exactly the clusters are being used. I'm sitting with @mrocklin at SciPy, and he just told me about [Coiled Analytics](https://docs.coiled.io/user_guide/analytics.html):

> Coiled Analytics lets you track Dask usage wherever Dask is run.
> 
> Motivation
> - When running computations we often ask ourselves questions like the following:
> - Did my computation finish?
> - Did any exceptions occur?
> - How much did that cost me?
> - What is taking most of the time?
> - Why is that cluster still running?
> 
> Experienced users know that Dask presents answers to these questions visually through the Dask dashboard. However, the Dask dashboard only tracks the real-time performance of a single Dask cluster. Coiled extends Dask by tracking many Dask clusters across many users and storing those results over time for later analysis. Coiled analytics provides a team-wide view of all clusters over time.

This would be super useful to all of the 2i2c hubs that run Dask and Dask Gateway

### Proposal

We configure our Dask Gateway clusters to report their data to Coiled Analytics.

**Comment by jmunroe** [comment]
I'm aware of users who have asked for this level of transparency on costs. I agree it is worthy the time to explore it.

**Comment by yuvipanda** [comment]
We are not planning on using coiled analytics on these clusters anytime soon. Closing, can be re-opened if things change!
