### ISSUE TITLE
Pre-warm the neurohackademy hub

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1532]
We should pre-warm the neurohackademy hub before the start of the event on July 25th.

### Checklist before the event:
- [x] create a separate nodepool only for this hub to use https://github.com/2i2c-org/infrastructure/pull/1554
- [x] decide upon the minimum nodes it should have
- [x] decide when to do the actual pre-warm (Friday/over the weekend/Monday morning)
- [x] decide if we should keep it for the entire event (August 3) or we should start/stop them
- [x] make sure the basehub default for singleuser server resources are sensible for this event or we should tweak them

### Checklist after the event:
- [ ] delete the nodepool
- [ ] document the pre-warming process (https://github.com/2i2c-org/infrastructure/issues/787)

Update: I just realized we also had https://github.com/2i2c-org/infrastructure/issues/1300 were we could track the warm-up. But that one it's pretty long already, so I plan to use that to communicate with the community rep and this one for 2i2c interactions if that's ok.

**Comment by damianavila** [comment]
> But that one it's pretty long already, so I plan to use that to communicate with the community rep and this one for 2i2c interactions if that's ok.

That sounds OK to me.

**Comment by GeorgianaElena** [comment]
@damianavila, I opened https://github.com/2i2c-org/infrastructure/pull/1554 with I **think** should be what needs to happen before the event.

However, I didn't do a pre-warming before, and according to https://github.com/2i2c-org/infrastructure/issues/787 we don't have yet docs around best practices around this 😬 so I'll be flying blind a bit 😅 (I also don't have terraform setup on the new laptop so that would be fun too 🤦🏼‍♀️ )

Anyway, I *think* a plan could be:

1. Get approval that https://github.com/2i2c-org/infrastructure/pull/1554 looks good.
2. Run terraform plan and then terraform apply, then re-deploy the hub.

**Comment by damianavila** [comment]
> However, I didn't do a pre-warming before, and according to https://github.com/2i2c-org/infrastructure/issues/787 we don't have yet docs around best practices around this 😬 so I'll be flying blind a bit 😅

In that issue (#787), which we need to address sooner than later, there is a reference to a previous warming PR: https://github.com/2i2c-org/infrastructure/pull/573 (you probably already saw it, but just in case).

>(I also don't have terraform setup on the new laptop so that would be fun too 🤦🏼‍♀️ )

New laptop! Nice... although I agree it might be fun 😛

**Comment by damianavila** [comment]
> I think there were some docs where it's said that if the event happens on Modays we can do the pre-warming on Fridays (even though that means more costs) so we don't do it over the weekend? 😬

Yes, that is true... and I think it makes sense to do it on Friday or on Monday morning... but we should avoid asking people to work on Sunday (my bad to suggest that in a previous message, it will not happen again unless it is absolutely necessary!).

> I can do it Monday morning and also on Sunday, but I'd prefer it to be Monday if that's ok. I'm just a bit concerned about the time-frame remaining to fix things if anything goes wrong. But things should be pretty straightforward so I'm also a bit confident about it :D

If you think you need more time (or want to be more conservative) and IF you have the cycles, just do it today!
Otherwise, Monday morning should be totally OK, IMHO. If you are confident, I am confident as well 😉!

**Comment by GeorgianaElena** [comment]
> In that issue (https://github.com/2i2c-org/infrastructure/issues/787), which we need to address sooner than later, there is a reference to a previous warming PR: https://github.com/2i2c-org/infrastructure/pull/573 (you probably already saw it, but just in case).

I have that documentation task in the checklist of this issue 🚀 
I saw that PR and others similar, but I don't think there's enough info about best practices around this. I'm saying this because I saw some mention setting the nodepool to 0 and then modifying it from the GUI during the event. So I'm not sure about what's the "recommended" way of doing things and what to expect.

**Comment by damianavila** [comment]
@yuvipanda surely has the better practices on his mind, we just need to pull that info from his head 😜!

**Comment by damianavila** [comment]
@consideRatio surely has some thoughts on this specific case because of his previous experience with this event.

**Comment by consideRatio** [comment]
@damianavila could you clarify what you looked for input about?

**Comment by damianavila** [comment]
@consideRatio, if you remember (don't worry if you do not have those details) from the previous event if there was some recognizable usage pattern that can be served better with particular pre-warming conditions (ie. specific peaks, etc).

**Comment by consideRatio** [comment]
Last time it was an open online event with more users etc, now its different enough to say anything based on experience from past event.

I suggest a single node is started ahead of time via a node-sized user-placeholder pod, and each node fits approx 30 of the 120 estimated users. See https://github.com/2i2c-org/infrastructure/pull/1554#discussion_r927732666.

Users may end up waiting for image pulling now still though because of 2i2c bypasses the pre-puller logic by using the jupyterhub-configurator. I'm not sure what makes sense short term.

Hmmm hmmm its a big topic :/

**Comment by yuvipanda** [comment]
Sorry for missing this, @GeorgianaElena and @damianavila. @GeorgianaElena's checklist up top sounds good to me!

**Comment by GeorgianaElena** [comment]
I'm closing this one since nodepool deletion can be tracked in https://github.com/2i2c-org/infrastructure/issues/1300 and pre-warm docs in https://github.com/2i2c-org/infrastructure/issues/787
