### ISSUE TITLE
Allow access to uwhackweeks grafana outside of 2i2c

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1570]
### Context

We recently received a request for Grafana access https://2i2c.freshdesk.com/a/tickets/158.

Currently, the way to do this is to enable GitHub authentication for that particular cluster Grafana and allow access to the community rep either by adding them to our 2i2c org and adding this org to the allowed list, or allowing another organization entirely, where the community rep has access. 

### Proposal

We should enable GitHub auth for the uwhackweeks Grafana and:

- figure out if we should allow an entire org
- or if we should allow only a specific GitHub team

Haven't tested last one, but there are docs about it here -> https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/github/#team_ids.

We would need to grab the id of that team and add that to the allow list instead of the team name. Docs about getting extra info about a team here https://docs.github.com/en/rest/teams/teams#get-a-team-by-name (thanks @sgibson91 ✨ )

**Comment by GeorgianaElena** [comment]
Signaling the discussion in https://github.com/2i2c-org/infrastructure/pull/1830 which I believe is relevant for this one too

**Comment by yuvipanda** [comment]
I think we should just grant people access as described in https://infrastructure.2i2c.org/en/latest/sre-guide/support/grafana-account.html?highlight=grafana

**Comment by consideRatio** [comment]
Closing as uwhackweeks cluster is terminated
