### ISSUE TITLE
Remove default nodeSelector configuration for dask-gateway core pods (`controller` and `api`)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1574]
The dask-gateway helm charts comes with three core pods: `api`, `controller`, `traefik`. Two of these have been explicitly required to schedule on k8s nodes with the label `k8s.dask.org/node-purpose: core`. But not all three pods, only `api` and `controller`.

https://github.com/2i2c-org/infrastructure/blob/840b3bdf6d643ce0f27ed286cbfe78a00492f28d/helm-charts/daskhub/values.yaml#L105-L110

I think everything would be fine if this configuration just isn't done at all for `api` and `controller`. It adds complexity forcing users to create k8s nodes with this label but doesn't add clear value in my mind - just like it doesn't add value to declare a node label specific for grafana, prometheus, cert-manager, and other such pods.

A dedicated nodeSelector for on demand user created `worker` and `scheduler` pods (together makes up a Dask Cluster created on demand) could still make perfect sense. So I'm just suggesting that `controller.nodeSelector` and `gateway.nodeSelector` (api pod) isn't set.

## Related

- https://github.com/2i2c-org/infrastructure/pull/1573#issuecomment-1199181157

**Comment by yuvipanda** [comment]
I just wanna make sure they end up on the core nodepool, and not on any of the user or dask-worker pools.

**Comment by consideRatio** [comment]
If they are tainted, we should be good!
