### ISSUE TITLE
Expose cloud billing dashboards for customers with dedicated clusters

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1575]
I figure exposing details about cloud costs to those with dedicated clusters is reasonable, perhaps by providing read-only access to the clouds provided information about this (in aws, gcp, azure).

I've opened this based on the more specific request in a [freshdesk ticket](https://2i2c.freshdesk.com/a/tickets/158) from @scottyhq to have access to such details. @scottyhq mentioned that https://github.com/2i2c-org/infrastructure/issues/1336#issuecomment-1147433606 was an example of the kind of details that would be very relevant.

## Suggested action points

- Figure out how to provide scoped access to billing reports
  - [x] For GCP projects - see [this comment below](https://github.com/2i2c-org/infrastructure/issues/1575#issuecomment-1398521931)
  - [ ] For AWS accounts (@scottyhq needs this)
  - [ ] For Azure subscriptions
- Decide on procedure to provide such details and document it

**Comment by damianavila** [comment]
@jmunroe, I forgot about this one (as per our today conversation).

**Comment by jmunroe** [comment]
I am assigning this to myself in the capacity as a "product" person.  I'd like to write out a requirements docs and user stories for what this feature will look like. Once that is scoped out, I'll reach out to the engineering team to work through any design/implementation requirements.

**Comment by consideRatio** [comment]
### How to provide GCP console access to a specific project's billing

Grant them a `Basic` -> `Viewer` Role from the project's IAM panel. Don't involve permissions on the linked billing account!

![image](https://user-images.githubusercontent.com/3837114/213731057-5ae90ca2-cd62-44ab-9e80-bf0fea67f2f0.png)

### Background

I've concluded that no permissions need to be granted from the `2i2c Billing` billing account on GCP, but that its sufficient if the user is an Viewer on the GCP project associated with the `2i2c Billing` billing account. Such users won't see other proejcts cost reports etc when visiting 2i2c Billing - only the projects they have access to.

From [this documentation](https://cloud.google.com/billing/docs/how-to/custom-roles#payment_information) we understand the relevant permissions:

> A user with `billing.accounts.getSpendingInformation` permission on the billing account can view costs for the entire billing account as well as any of its projects. If you want to limit a user to viewing only the costs for a specific project, give the user the `billing.resourceCosts.get` and `resourcemanager.projects.get` permissions on the project instead of setting the billing account level permission.

Using the [IAM permission reference tool](https://cloud.google.com/iam/docs/permissions-reference) I conclude that `billing.resourceCosts.get` permission is granted to a project `Viewer` role.

![image](https://user-images.githubusercontent.com/3837114/213729645-ab4f13b5-b52c-43f6-a61c-0424b0916c54.png)

It

**Comment by damianavila** [comment]
I feel the follow-up here is to document it in our docs, @consideRatio @jmunroe WDYT?

**Comment by consideRatio** [comment]
Yepp, I've updated the action points above. We understand how to do this for GCP projects technically now, but need to understand it for AWS accounts and Azure subscriptions as well for full documentation - but we can focus on GCP / AWS initially i figure.

**Comment by damianavila** [comment]
@jmunroe will be an intermediary for particular situations that request this information.
Will use our Eng cycle to push forward Yuvi's work.

**Comment by GeorgianaElena** [comment]
Relevant issue https://github.com/2i2c-org/infrastructure/issues/1921 that [Yuvi's PR](https://github.com/2i2c-org/infrastructure/issues/1921) tackeles

**Comment by consideRatio** [comment]
Closing as outdated and stale.
