### ISSUE TITLE
A series of technical-focused meetings to discuss about the BinderHub-JupyterHub project

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1577]
### Context

Main issue: https://github.com/2i2c-org/infrastructure/issues/1382

We need to have a series of 3 technical meetings (one per week) to discuss specific technical items involving @yuvipanda's proposal, UX/UI needs, underlying technology, pre-existing experiences, etc.

### Proposal

1. Find a good calendar spot so the team can meet in a recurrent fashion.
2. Run the meetings
3. End up with a technical specification/proposal complete enough to create an MVP/prototype

**Comment by damianavila** [comment]
@consideRatio @yuvipanda @sgibson91, please share your availability on the following when2meet: https://www.when2meet.com/?16262802-AGkDQ

Thanks!!

**Comment by damianavila** [comment]
OK, it seems there is a sweet spot on Tuesdays at 4 pm GTM (except for the 3rd week), so I have scheduled the meetings on that range. We can re-schedule the 3rd one when we are closer to that date in case people can't make it.
Thanks for sharing the availability!

Can we agree on an agenda for the first one? Or think about how we want to frame the conversation?
I think a quick intro to @yuvipanda proposal might be useful as a first item or trigger.
Open to others' thoughts!

**Comment by sgibson91** [comment]
### Conversation with Meag Doherty RE user research

Meag is onboard to help us shape some questions we'd like to ask as part of user research, and has shared two resources for designing a user research study which I have added to our shared GDrive here: https://drive.google.com/drive/folders/1KTDi6fF3M0p8ldXo1tD0LjD1ZBZNncoL?usp=sharing

She would also be happy to join one of the meetings for a user research focussed agenda. Next week (Aug 9th) isn't possible, but @damianavila could we include her availability when scheduling a meeting in week 3? (w/c Aug 15).

Additionally, Meag is another SSI Fellow whose [fellowship focus is on UI/UX for research software](https://software.ac.uk/about/fellows/meag-doherty). One of her goals is to capture case studies of people who work in research software that might perform user research as part of feature development (feeding into a longer strategy of pioneering a Research Software Design role to accompany RSEs). I think it would be a great in-kind contribution for us to be a case study in return for her expertise (I can work with her on that if preferred by the team).

cc @meagdoh

**Comment by damianavila** [comment]
Notes from the first meeting live here: https://docs.google.com/document/d/1Z6TppBLjIF2Lv0wubM2833vp92Br_jGAS7LmM35viYM/edit#heading=h.hlwfqtinux36

Accordingly to the actions items at the end of the notes, I am creating 3 new issues:
1. User validation, user research: https://github.com/2i2c-org/infrastructure/issues/1597
2. User validation, deploy tljh-repo2docker: https://github.com/2i2c-org/infrastructure/issues/1596
3. Technical draft (state of the art): https://github.com/2i2c-org/infrastructure/issues/1598

**Comment by damianavila** [comment]
> Conversation with Meag Doherty RE user research

@sgibson91, let's continue that conversation in the specific issue I have created (#1597).

**Comment by damianavila** [comment]
Several meetings have happened (notes shared in existing links) and the plan has changed (see #2120) from what it is originally described above. Further tech meetings, if needed, will be taken on per need basis.
