### ISSUE TITLE
Document reporting options for Dask

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#158]
One of the most common requests we're going to get is helping people avoid spending way too much money with Dask. Ideally, there would be some "guarantees" that we can give people, but I don't believe that this yet exists technically. In the meantime, we should give people guidelines for how they can view summaries of activity on a hub so they know who is using it (and potentially abusing it). This would ideally include dask workers and such.

Is it possible to do this? If not, are there other ways we can document solutions for people who are worried about Dask over-use on their hubs?

**Comment by yuvipanda** [comment]
We can put an upper limit on the total amount of money a cluster's compute costs - by setting max number of nodes in the autoscaler. This is a very coarse but effective method of making sure you don't have a 5million$ bill. I think this satisfies some of the worst-case scenarios people have.

per-user guarantees are harder, although I'm hopeful about https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-per-priorityclass. It might be easier to build something with https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/ instead as well. I'd say someone working on the problem for a few weeks / 1 month could get us something real nice.
