### ISSUE TITLE
Automate updating user images in profile list - temporary solution

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1590]
### Context

Currently, the `configurator` doesn't support to update user images if multiple profiles are used with multiple images.
So the current workflow in this cases, is for 2i2c engineers to update user images whenever they need changing. Alternatively, someone from the community we're serving can update it themselves by opening up PRs against the `infrastructure` repo.

But this will probably change in the future -> you can track progress of this feature here https://github.com/2i2c-org/infrastructure/issues/1253 🚀 

### Proposal

Until a new `configurator` version is released, another approach could be to use https://github.com/sgibson91/bump-jhub-image-action by creating a new GitHub workflow that tracks the images listed in the hub config and updates them whenever new versions are released

We are piloting this idea for the OceanHackWeek 2022 event -> see https://github.com/2i2c-org/infrastructure/issues/1601

### Updates and actions

If the above is considered a valid approach and it turns out useful for the event, then we should:

- [ ] add info about this option to the new Event issue template
- [ ] possible create an events workflow that has a matrix similar to the current workflow so we can easily add/remove entries as we need them instead of creating one per hub (ref https://github.com/2i2c-org/infrastructure/pull/1588#pullrequestreview-1060160824)

**Comment by GeorgianaElena** [comment]
Based on the feedback we got in https://github.com/2i2c-org/infrastructure/issues/1576#issuecomment-1237347124, this wasn't find extremely useful, because it lacked the mechanism of testing fast that a image is working and distribute it asap to the users (*""It would be really nice to have a faster way to test and update the images (for when I get told about packages just before they are used for a tutorial), that didn't require 2i2c's intervention."*)

Some really interesting suggestions that I believe are worth trying to solve the issue above were:

- [ ] provide a test hub without profiles, so that we could use configurator to test images in a live hub ➡️  this could be our demo hub perhaps?

- [ ] a bot or github action that could merge PRs from community representatives to image fields

**Comment by sgibson91** [comment]
I personally would focus more on the first option for a temporary workaround. Option 2 would require maintaining a list of the GitHub handles of all Comm. Reps. who _might_ open an image-based PR. (What could go wrong with auto-merging PRs? How would we validate that the PR was only changing images and not any critical infrastructure?) It would involve more dev work that I think should be dedicated towards working on the configurator to be compatible with profile options, which is the long-term solution here.

**Comment by GeorgianaElena** [comment]
Superseed by https://github.com/2i2c-org/infrastructure/issues/2564 and https://github.com/2i2c-org/infrastructure/issues/3095
