### ISSUE TITLE
Automate updating user images in profile list for OHW using `sgibson91/bump-jhub-image-action`

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1601]
### Context

I realized I hadn't open an issue to track the work of using `sgibson91/bump-jhub-image-action` to automate updating user images in profile list for the OHW hub and has mostly been tracked in scattered comments in issues and PRs.

Context about the reasoning behind this is described in https://github.com/2i2c-org/infrastructure/issues/1590 in more detail.

### Proposal

This is an implementation of [that](https://github.com/2i2c-org/infrastructure/issues/1590) for the OHW hub.

### Updates and actions

- [x] Add support for ghcr.io to https://github.com/sgibson91/bump-jhub-image-action ➡️ https://github.com/sgibson91/bump-jhub-image-action/pull/148
- [x] Use the action above for OHW hub ➡️ 
         - https://github.com/2i2c-org/infrastructure/pull/1587
         - https://github.com/2i2c-org/infrastructure/pull/1588
 - [x] Worflkow doesn't work, fix it ➡️ 
         - https://github.com/2i2c-org/infrastructure/pull/1600
         - https://github.com/sgibson91/bump-jhub-image-action/pull/150
         - https://github.com/sgibson91/bump-jhub-image-action/pull/151

**Comment by sgibson91** [comment]
Thank you Georgiana for adding this extra feature to the action! 🙏🏻 ❤️ ✨
