### ISSUE TITLE
[EVENT] Allen Institute Summer Workshop on the Dynamic Brain

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1621]
### Summary

https://alleninstitute.org/what-we-do/brain-science/events-training/summer-workshop-dynamic-brain/
Lead issue: https://github.com/2i2c-org/leads/issues/79
New hub issue: https://github.com/2i2c-org/infrastructure/issues/1440

### Event Info

- **Community Representative:** @fcollman @mabuice @morriscb @aamster 
- **Event begin:** 20-Aug-2022
- **Event end:** 04-Sep-2022
- **Active times:** US/Pacific
- **Number of attendees:** 24 students plus staff (which will total about 15 on-site at any given time).
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**: allen-swdb.2i2c.cloud
- **Hub decommisioned after event?**: TBD

### Task List

**Before the event**

- [ ] Dates confirmed with the community representative and added to Hub Events Calendar.
- [ ] Quotas from the cloud provider are high-enough to handle expected usage.
- [ ] **One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  
- [ ] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [ ] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by damianavila** [comment]
@fcollman @mabuice @morriscb, do you have a rough idea of the number of participants/attendees?

**Comment by mabuice** [comment]
@damianavila we have 24 students plus staff (which will total about 15 on-site at any given time).

**Comment by morriscb** [comment]
We should also add @aamster to this thread as well.

**Comment by colliand** [comment]
I hope the hub worked well and that the workshop on brain dynamics was a super success. I invite @mabuice and colleagues to share feedback! Did the service work well for the workshop? How can we make it better? Feel free to share input here or we can arrange for a virtual meeting. 

According to the Allen Institute + 2i2c/CSS agreement, this hub is scheduled to be wound down at the end of September. Please let us know if you'd like to extend the service interval. 

2i2c remains available to support the Allen Institute.

**Comment by colliand** [comment]
This event has occurred. The associated hub can be decommissioned at the end of September. I am closing this issue.

**Comment by mabuice** [comment]
The workshop went very well!  Thank you for all of your help!
