### ISSUE TITLE
Remove the openscapes special-casing in the deploy test when issue is fixed upstream

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1643]
### Context

https://github.com/2i2c-org/infrastructure/issues/1611#issuecomment-1219466905

### Proposal

We should remove the fix added by https://github.com/2i2c-org/infrastructure/pull/1639 when/if we use a `kubespawner` version that has  https://github.com/jupyterhub/kubespawner/pull/631.

**Comment by sgibson91** [comment]
I noticed https://github.com/jupyterhub/kubespawner/pull/631 is now merged, but I don't think a release has been made including it yet, from the changelog: https://github.com/jupyterhub/kubespawner/blob/main/docs/source/changelog.md
