### ISSUE TITLE
Merge our two GCP billing accounts into one

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1651]
### Context

Currently we have two billing accounts on GCP that are used for many different communities (and paid by 2i2c):

- `2i2c Billing` (`0157F7-E3EA8C-25AC3C`) is where most of our clusters are attached to, and under the `2i2c.org` organization
- `two-eye-two-see` (`011901-F8160A-68DED7`) is *only* used for the `m2lines` cluster, and has no GCP organization

### Proposal

We should unify these into a single GCP billing account so that we can more easily calculate the cloud bills that each community has incurred. I suggest we move the m2lines hub onto the `2i2c Billing` account and then close out `two-eye-two-see`.

**Comment by sgibson91** [comment]
I would also love to merge the `two-eye-two-see` and `two-eye-to-see-org` projects while we're at it 😄

**Comment by yuvipanda** [comment]
I just moved the m2lines project over.

1. Go to https://console.cloud.google.com/billing/projects?organizationId=184174754493
2. Click the 'three dots' for the project you wanna change
3. Select 'Change Billing'
4. Select New Billing account
5. Done

**Comment by damianavila** [comment]
> I would also love to merge the two-eye-two-see and two-eye-to-see-org projects while we're at it 😄

Thanks @yuvipanda, so I guess there remaining task before closing this issue is the merge proposed by @sgibson91?

**Comment by choldgraf** [comment]
Looking at the billing accounts, it seems like that project is now where it should be, and linked against our 2i2c.org organization, so I think this can be closed.

![image](https://user-images.githubusercontent.com/1839645/190204956-45105070-9282-4ab8-97ee-69116510741f.png)

We still need to invoice m2lines for their cloud bill. @colliand or @jmunroe is there a place where we are tracking the cloud billing pass-through invoices for communities?

**Comment by colliand** [comment]
We need a system to track cloud billing.
