### ISSUE TITLE
Add "Small" server option radio button default for Hub that has language option (python, R, Matlab)

### ISSUE THREAD

**Issue by jules32** [2i2c-org/infrastructure#1658]
### Context

Hello! We now have the option to spin up instances in our Openscapes Hub to support researchers programming in different languages, thank you 2i2c team and @betolink for enabling this! You'll see in this screenshot below that we can now select python, R, or Matlab. 

<img width="1152" alt="Screen Shot 2022-08-25 at 08 43 59" src="https://user-images.githubusercontent.com/5891909/186992732-48a79e9e-97a1-4ae4-a057-689ed4ee4cc4.png">

Currently, however, there is no default radio button selected for "Server Options". When I select a language like R (or Python or Matlab) and press the orange "Start", I get the following error message: "Spawn failed".

<img width="461" alt="image (2)" src="https://user-images.githubusercontent.com/5891909/186992938-b34c6bd8-c9ad-4171-aacb-84c0fe1d78fd.png">

This is fixed when I select a radio button (when I noticed that there is not one selected); I am able to access the Hub with my selected language no problem.

 

### Proposal

The default radio button is selected as "Small" for "Server Options". 

Thank you in advance!

**Comment by jules32** [comment]
Thank you!

**Comment by yuvipanda** [comment]
Yw @jules32

**Comment by jules32** [comment]
Hi @yuvipanda et al, 

We're now seeing the following request from Auth0 when we try to log in. I'm not sure this is related to the default radio button but we wanted to check if this expected before allowing authorization - 

<img width="574" alt="image" src="https://user-images.githubusercontent.com/5891909/187320774-5c207876-a880-4d30-a585-d35d9c802ef1.png">


Auth0 links to https://github.com/iam-login

Thank you!

**Comment by jules32** [comment]
Wonderful, thanks @GeorgianaElena ! I've tested it and confirm we now see the 2i2c-Auth0 authorization. 

Thank you so much!
