### ISSUE TITLE
Issue with adding staff as hub admins if `admin_users` is not explicitly listed in the config (even as an empty list)

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1671]
### Context

When trying out the hub in https://github.com/2i2c-org/infrastructure/pull/1664 I realized that I'm not of admin, even though the config to add 2i2c staff as admins seems to be correct.

### Proposal

Confirm this is a bug and try and fix it somehow

### Updates and actions

- I did some checks on other hubs too (earthlab, staging, demo), each of them using a different authenticator by deleting @damianavila's username (sorry about this) from the admin panel and then I did a re-deploy of that hub, expecting the username to be added back and be shown in the admin panel, but it didn't happen.
- Explicitly adding the admins through `admin_users` from the hub yaml config works
- 2023-01-05: Sarah confirms that problem arises when `admin_users` is not defined in the config, but as soon as it is added, even just an empty list, 2i2c staff members are granted admin access

**Comment by GeorgianaElena** [comment]
I will close this at it appears to have resolved itself for now? ref: https://github.com/2i2c-org/infrastructure/pull/1664#issuecomment-1240356519 and https://github.com/2i2c-org/infrastructure/pull/1664#issuecomment-1240413937

**Comment by sgibson91** [comment]
I am reopening this issue since I have been struggling with this in #1967 I have scoped the problem to just affecting **Google IDs**.

**Comment by damianavila** [comment]
@sgibson91 is Sherlock mode 😉 

![sherlock](https://media.giphy.com/media/3o7TKIgQuu1EfOBcly/giphy.gif)
