### ISSUE TITLE
Lock up the Callysto hub

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1678]
### Context

The Callysto hub is pretty open right now, so we should find ways to protect it against potential abuse.
We currently have [cryptnono deployed](https://docs.2i2c.org/en/latest/about/infrastructure/security.html#cryptocurrency-mining) on all of our clusters, but we should find ways to improve this protection, esp for hubs like the Callysto one.

Ref: https://github.com/2i2c-org/infrastructure/pull/1649#pullrequestreview-1094607859

**Comment by colliand** [comment]
This is a good idea, especially to avoid unauthorized cloud usage explosions. That said, the Callysto use case involves their personnel introducing data science and coding ideas to teachers and students in grades 5-12 across Canada. These users tend to not be organized under CIlogon or InCommon authorization layers. Their usage scenario often involves launching students and teachers they've just met into the hub without forming an allow list in advance.

**Comment by ianabc** [comment]
This is going to come up for us in a couple of weeks. We have a series of workshops where various groups of users will be logging and and trying out the service. Right now, it looks like users are being whitelisted, but that might not be practical for those workshops. As far as I know, we have

* Nov 18th ~ 20-30 users
*  Nov 24th ~ 50-60 users
* Nov 25th ~ 180-190 users
* December 6th ~ 120 users

In all cases, we want to make sure that the hub is ready (the right number of nodes warmed up by 9am) and that users can log in OK. Can you let me know what the best options are for this currently? For warming up hubs, I found [this issue](https://github.com/2i2c-org/infrastructure/issues/787), but I'm not sure what the current status is. If it is appropriate, I think we would be comfortable manually triggering the node scale up if needed.

**Comment by byrcyb** [comment]
For the upcoming hackathons that @ianabc mentioned in November and December 2022, these will be with specific school divisions, is it possible to whitelist all emails associated with those school divisions instead of leaving the hub open for all to sign up? For example, whitelisting `xxxxx@schooldivisionA.ca, xxxxx@schooldivisionB.ca, xxxxx@schooldivisionC.ca, etc`

**Comment by yuvipanda** [comment]
@byrcyb @ianabc if those schools are part of CILogon (you can check via https://technical.edugain.org/entities and https://incommon.org/community-organizations/) we can restrict them to that.

@ianabc re: scale up, what do you feel about us making sure you have rights to trigger the warmup yourself from the cloud console?

**Comment by byrcyb** [comment]
@yuvipanda these are K-12 schools in Canada, so for eduGain via the Canadian Access Federation, these schools are only eligible to be service providers and I don't believe any (at least in Alberta) are participating. As well, I don't see any of the Canadian K-12 schools that will be participating in our hackathons on the community organization list either. I guess we won't be able to restrict then?

**Comment by yuvipanda** [comment]
@byrcyb the other option I can think of is we use auth0's username / password signup, require email verification there (https://auth0.com/docs/manage-users/user-accounts/verify-emails) and *then* restrict the emails that can sign up. What do you think of that?

However, I think auth0 doesn't have a way to limit data to be stored purely in Canada - it comes across to the US. It will store list of usernames, and when they login (but nothing else). Would this be acceptable?

Also, what happens to these users *after* the hackathons are over?

**Comment by byrcyb** [comment]
Thanks @yuvipanda let me run the idea of using auth0 verification with the teachers on our team and that we're collaborating with, and I'll let you know. I'm currently less worried about the data storage / residency as even the most restrictive province's in Canada (British Columbia) seemed to have relaxed their policies recently. 

The after hackathon question is really good. I imagine students and teachers may want to revisit the content a short-time after the event, but not necessarily having the need to. They may want to use more Callysto content from our website but that's currently linked to our other hub.

**Comment by ianabc** [comment]
> @ianabc re: scale up, what do you feel about us making sure you have rights to trigger the warmup yourself from the cloud console, at least for now? In the medium term, I'd like this to become a self-service things admins can do.

Yep, that would be ideal. I found some of the plans in #787, but until that, being able to manually control it would work. @chealion do you already have access?

**Comment by yuvipanda** [comment]
@byrcyb yes, the students would need to create a new login / password for themselves, and verify that via email. So the information auth0 would store would be just their email addresses.

We can possibly unlock it temporarily for the duration of the event, but will need to keep an eye out for crypto miners :( 

What would an ideal workflow look like?

In the past, what we have done for workshops elsewhere is to just make the hub have a 'shared' password that is shown to the users. So everyone logs in with their own username, and the same password. The interface looks a bit like workshop.datahub.berkeley.edu. The disadvantage here is that any user can look at any other user's login too, which perhaps could lead to mischief. So that is also an option available

**Comment by byrcyb** [comment]
> @byrcyb yes, the students would need to create a new login / password for themselves, and verify that via email. So the information auth0 would store would be just their email addresses.

This should be possible, but might be tricky in practice as email permissions for K-12 students will vary by school district, with some not allowing any emails from outside of their own domain. 

> What would an ideal workflow look like?

An ideal workflow would have the students login to the 2i2c callysto hub with their school email addresses (Google or Microsoft authentication) without having to create accounts via auth0 (or CILogon which isn't an option in this case). 

For your reference, a typical in-person hackathon for us is a one day event (9am - 2pm), where in the morning we will introduce the computing environment and Python, and walk through some tutorial exercises together with the students. I imagine if we are to use this auth0 process we can incorporate logging into auth0, creating a new login / password and verifying by email in the morning, before logging into the 2i2c callysto hub. We would also want to explain why we are doing this, which I think I'm a bit a fuzzy on myself. In the afternoon of our hackathons, we let the students loose (individuals or teams) with independent hackathon challenge notebook(s) that we've created. So, we only have the students attention for the one day. 

> We can possibly unlock it temporarily for the duration of the event, but will need to keep an eye out for crypto miners :(

Right! I guess unlocking doesn't help as we still need to figure out the auth0 / CILogon side of it. 

> In the past, what we have done for workshops elsewhere is to just make the hub have a 'shared' password that is shown to the users. So everyone logs in with their own username, and the same password. The interface looks a bit like workshop.datahub.berkeley.edu. The disadvantage here is that any user can look at any other user's login too, which perhaps could lead to mischief. So that is also an option available

This can be an option too although, and would simplify things, but I am a bit worried about the mischief side of it. They will be hacking for prizes so I don't know if that will give them less or more incentive to be mischievous 🤔  Would we need to provide a list of the student emails in-advance to be able to use this login approach?

**Comment by byrcyb** [comment]
That sounds promising! Yes, the vast majority of school districts are using Google or Microsoft, and sometimes both, for example Microsoft for administrative staff and Google for teachers / students. There's only been a couple of other cases that we've encountered so far that haven't been Google or Microsoft (one was Zimbra). 

I'm not sure how restricting by domains works but we may need some flexibility as there seem to be quite a few variations for staff and students within a school, as well as between schools that belong to the same school district (who will be participating at one of our hackathon events) 😅 . Note, we can definitely work with the schools to try to capture all the cases before an event -- how much time in advance of an event would be needed to update and test these restriction lists?

**Comment by damianavila** [comment]
As a side note, folks, I have created an event-dedicated issue here: https://github.com/2i2c-org/infrastructure/issues/1918.

Feel free to continue the conversation about the auth here but when there is an agreement, let's move the discussion to the specific event issue.

**Comment by yuvipanda** [comment]
@byrcyb I made a PR and this works! You can add additional domains like this: https://github.com/2i2c-org/infrastructure/pull/1919/files#diff-79c32574f785c3cc2a19e21e56257fd9a92aca350b63c65940b9a00699b49f1aR105. That PR allows all of `.edu` but we'll probably lock that down a little more. Do you have a list of domains to start with?

**Comment by ianabc** [comment]
@yuvipanda we've been chatting about this today, the latest list we have is almost exclusively .ca addresses and one .org. We suspect that pattern is true in general (we're trying to find out now). Given the short timeline to the event and would it be OK to wildcard the `*.ca` and add a handful of `.org` domains case-by-case?

**Comment by yuvipanda** [comment]
@ianabc ok done, I've merged and deployed this, let's see how it works.

@ianabc @byrcyb for updating this, I'd also consider the option of giving you merge rights within the repo to allow self-merges *specifically* just for adding more domains, so you have autonomy there. How does that sound?

**Comment by ianabc** [comment]
Thank you! It's working for me so far. @byrcyb could you try to find someone from one of the affected school districts to test as well? (i.e. someone who hasn't already logged in)

For the merge permission that would be really useful. The main people would be myself, Michael Jones from Cybera (@Chealion) and @byrcyb.

For a longer term solution Byron, Elmar and I were chatting about some variations on the shared password scheme you mentioned above. I don't want to drag this particular issue out any further, but I think I can see a way to make it work, maybe we can chat about it later on.

**Comment by misterhay** [comment]
I tried it with student accounts from Elk Island Public and Fort McMurray Catholic and both worked perfectly.

**Comment by yuvipanda** [comment]
@ianabc @byrcyb i've invited you both to a team with merge rights to this repo
