### ISSUE TITLE
List of Running Hubs is Incomplete

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#1684]
### Context

The [allen-swdb hub](https://allen-swdb.2i2c.cloud/hub/login?next=%2Fhub%2F) is not appearing in the [list of running hubs](https://infrastructure.2i2c.org/en/latest/reference/hubs.html).

**Comment by sgibson91** [comment]
Because the PR has not bee merged yet

* https://github.com/2i2c-org/infrastructure/pull/1585

**Comment by colliand** [comment]
Thanks @sgibson91. I noticed that https://staging.callysto.2i2c.cloud and https://2i2c.callysto.ca/ are also running and not appearing in the list. I don't see a related PR. 

Am I just landing on edge cases that will shake out over a day or two? If yes, we can close this issue. If instead I'm identifying a systematic gap in the hubs we are running and those in the list, let's keep the issue open and find a nice resolution.

**Comment by sgibson91** [comment]
Callysto is showing up on the table for me. Note that the table only shows 50 entries at a time and we have a total of 56 entries, so you have to advance the page located at the bottom of the table.

<img width="1148" alt="Screenshot 2022-09-06 at 20 08 08" src="https://user-images.githubusercontent.com/44771837/188718922-5b340f0e-f49d-422e-8b60-39e13451f93c.png">

**Comment by sgibson91** [comment]
<img width="934" alt="Screenshot 2022-09-06 at 20 08 59" src="https://user-images.githubusercontent.com/44771837/188719015-3e7b9d61-6d7e-4da0-88af-20246f6aae7c.png">

**Comment by colliand** [comment]
Hmm. I knew there were two pages and also tried the search. Thanks Sarah.

**Comment by damianavila** [comment]
> Because the PR has not been merged yet
> https://github.com/2i2c-org/infrastructure/pull/1585

We should get that PR merged, I will try to push forward that action!

**Comment by colliand** [comment]
Pending the PR, this issue can be closed.
