### ISSUE TITLE
Workflows API rate limited in CI/CD?

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1686]
### Context

I think we are hitting some kind of rate limit in CI/CD. Every now and then the following error message appears.

<img width="529" alt="Screenshot 2022-09-06 at 20 24 35" src="https://user-images.githubusercontent.com/44771837/188721724-714e9b6f-b411-463f-8724-1b89ea17c0a8.png">

Although, one would expect that if it were a rate limiting issue, simply waiting an amount of time and rerunning the workflow should resolve it; however, that is not the case. Often pushing a new commit resolves it.

We mostly use the inbuilt `GITHUB_TOKEN` with workflow-appropriately scoped permissions via the `permissions` block. Except where a workflow would open a PR (e.g., the bump image tags workflow), which instead swaps `GITHUB_TOKEN` for a token generated by a GitHub App. (This is because we went tests to run on the opened PR, but this doesn't happen if it was opened by `GITHUB_TOKEN`.)

### Checkpoints

- [x] The immediate problem is gone because time passed and our limit was reset
- [x] Wait until https://github.com/2i2c-org/meta/issues/417 is resolved
- [ ] Re-ping github if we don't hear by 2022/11/21
- [ ] Further investigation is needed as per https://github.com/2i2c-org/infrastructure/issues/1686#issuecomment-1463985843

**Comment by sgibson91** [comment]
Found this in the docs:

> When using GITHUB_TOKEN, the rate limit is 1,000 requests per hour per repository. For requests to resources that belong to an enterprise account on GitHub.com, GitHub Enterprise Cloud's rate limit applies, and the limit is 15,000 requests per hour per repository.

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-github-actions

**Comment by sgibson91** [comment]
We may need to update _all_ our workflows so that they swap out `GITHUB_TOKEN` for a PAT from our GitHub App: https://github.com/organizations/2i2c-org/settings/apps/2i2c-token-generator-bot

This code already implements this: https://github.com/2i2c-org/infrastructure/blob/72ae1c824b9c6021fc3cd3597c187c549a5f90c5/.github/workflows/bump-helm-versions.yaml#L39-L50

docs: https://docs.github.com/en/developers/apps/building-github-apps/rate-limits-for-github-apps

**Comment by sgibson91** [comment]
**Note:** Chris requested a free non-profit plan for us which would increase the number of requests per hour per repository we can make with `GITHUB_TOKEN`

**Comment by sgibson91** [comment]
We could also refactor the [validation workflow](https://github.com/2i2c-org/infrastructure/blob/master/.github/workflows/validate-clusters.yaml) so that the step that inspects changed files (and hence uses `GITHUB_TOKEN`) is extracted from the matrix and only executed once, we then dynamically generate a matrix of clusters to validate, similar to the deploy-hubs workflow.

**Comment by sgibson91** [comment]
Work proposed in the above comment has been completed I propose we wait and see if:

1. Chris's request for a gitHub non-profit plan is accepted
2. When we next hit this issue (frequency may drop if it doesn't disappear completetly?)

before we decide if further action needs to be taken and if so, what

**Comment by sgibson91** [comment]
We are still seeing this issue. I opened a ticket with GitHub Support: https://support.github.com/ticket/personal/0/1904943

I might be the only one able to see that link, so here is what I asked:

> Hello,
> 
> We are regularly seeing failed GitHub Actions runs with messages such as: "API rate limit exceeded for installation ID 10159873." I'm wondering if there's a way we can track our API usage of the GITHUB_TOKEN per workflow over time so we can identify where in our pipeline is causing this issue?
> 
> Many thanks,
> Sarah

**Comment by sgibson91** [comment]
Response from GitHub support was unhelpful. It was basically to have a step at the start of every workflow that was use GITHUB_TOKEN to request information on how many calls it had left from the API. That wasn't helpful as I wanted aggregate data over time, maybe differentiated by workflow, to understand where the token was being used. So I feel we are edging into "build your own dashboard" territory here and that is not a useful application of our time, IMO.

**Comment by damianavila** [comment]
Quick question, @sgibson91. How frequent the failure is after the improvements/changes landed?

**Comment by damianavila** [comment]
> maybe we should have an issue where people can comment "bump" or something whenever they see this message as a poor proxy?

Maybe this one is the issue to bump it (since it has already the context so it is probably more findable by search).

**Comment by consideRatio** [comment]
@sgibson91 I see the failure on dorny-filter to see if files has changed etc, and I see that we have @actions/checkout that doesn't download repo history.

I wonder if the action may avoid making as many github api requests if we would have the full git history locally available.

Do you have a guess if fetching all of the git repo's history could help us?

**Comment by pnasrat** [comment]
I frequently hit spurious failures due to this on pull requests and would like to advocate for it to be considered to be fixed in an upcoming sprint, we rely on CI/CD for deployments and they are currently brittle due to this issue - cc @damianavila

**Comment by sgibson91** [comment]
I would love for it to be fixed too, the problem is we don't exactly know what the cause is

**Comment by pnasrat** [comment]
Nod - so the story to be put in would need to include that investigation component

**Comment by sgibson91** [comment]
> Response from GitHub support was unhelpful.

Here was the response for context:

> Hi Sarah,
>
> Thank you for reaching out to GitHub Support!
>
> You could add a step in your workflow file to check the GITHUB_TOKEN rate limit through out API.
>
> Something like this:
> 
> ```
> steps:
>     - name: Get our GITHUB_TOKEN API limit usage
>        env:
>          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>        run: |
>          curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit
> ```
>
> https://docs.github.com/en/rest/rate-limit?apiVersion=2022-11-28
>
> We hope this helps! If you have any other questions about using GitHub Actions, we recommend asking in our GitHub Community Forum:
>
> https://github.com/orgs/community/discussions/categories/actions-and-packages
>
> Cheers,
> GitHub Support

**Comment by damianavila** [comment]
The scope for the current 2023_10 sprint is to have a discussion about possible avenues to investigate this problem given the uncertainties that we currently have.

I will call a specific meeting for @sgibson91 @consideRatio and me as required and the rest of the engs as optional to start digging into this one. I will send the invites soon.

**Comment by GeorgianaElena** [comment]
Since I've recently invested time into investigating this, can I please also join this meeting and efforts? Thanks!

**Comment by damianavila** [comment]
OK, invitations were sent for a 50 min slot that was free for @sgibson91, @GeorgianaElena, and @consideRatio.
I might not be available at that time slot but it was a good sport for the 3 of you (and I am pretty sure I am not required for this conversation to move it forward). So, please carry on with the meeting if I do not show myself at the scheduled time.

**Comment by sgibson91** [comment]
### Rate limiting

Some context about how the rate limit applies:

> When using GITHUB_TOKEN, the rate limit is 1,000 requests per hour per repository. For requests to resources that belong to an enterprise account on GitHub.com, GitHub Enterprise Cloud's rate limit applies, and the limit is 15,000 requests per hour per repository.

There are also different rate limits depending on: if you're using a token or an app, whether the endpoint you call generates notifications (e.g., creating comments).

ref: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

### Debugging ideas

1. Request and print the remaining API quota at the start and end of workflow executions, such as the code in https://github.com/2i2c-org/infrastructure/issues/1686#issuecomment-1589512820
2. Inspect multiple workflows and search for failure patterns using a script
3. Inspect a recent failure, e.g., https://docs.google.com/document/d/1QwdEyJZI6866NjOoFYW8IQmKhSc0xouJHMHaCfQSRP4/edit
4. Print information about API quota contained in the headers of all API responses

### Resolution strategies

In [some workflows](https://github.com/2i2c-org/infrastructure/blob/0faa09870a48d852d2278f8837fe5adeb9447c8d/.github/workflows/bump-image-tags.yaml#L37-L48), we exchange the default `GITHUB_TOKEN` for a token from a GitHub App, which has a higher rate limit and does not experience the same restrictions that the default token does. We could implement this in all workflows and see if that helps.

### Action items

- [ ] Sarah to write a script that will pull all failed runs that mention rate limiting in the logs to see which workflows are failing and how often. We should only pull workflow runs that occur _after_ the merge of this PR to de-bias against it's effects https://github.com/2i2c-org/infrastructure/pull/2627#event-9499058419 but that (at time of writing) only leaves us with 2 days worth of data. So should maybe wait a month also to allow data to accumulate.
- [ ] Create some way of visualising how often each of our workflows are executed over time
- [ ] Investigate some other quicker investigative methods while waiting for data to accumulate

**Comment by sgibson91** [comment]
I'm a little bit suspicious of the `paged` function in `ghapi` which we use in a couple of places in our workflows. Sometimes I've seen it loop almost indefinitely (and it makes an API call to a new page on each iteration) when if you inspect the total count of results in the response, all the results fit on a single page and `paged` wouldn't need to loop at all.

I'm opening a PR to replace `ghapi` with straight forward `requests` and we can look for the `Link` variable in the response headers to determine whether pagination needs to happen or not.

**Comment by sgibson91** [comment]
I have compiled some analysis plots as well. Firstly, how many times per month are each of our workflows triggered, and then looking at how many times workflows failed with the API rate limit error in the logs.

- Source code (everything is on a branch at the minute): https://github.com/sgibson91/github-workflow-run-analysis/tree/adding-basic-scripts
- View the visualisation notebook on mybinder: https://mybinder.org/v2/gh/sgibson91/github-workflow-run-analysis/adding-basic-scripts?urlpath=lab%2Ftree%2Fworkflow_run_vis.ipynb

**Comment by sgibson91** [comment]
So far, we have only had one failure related to the API rate limit since the merge of #2627, and the script that caused it has since been updated to use a more trusted method of making API calls.

- #2667 

In the interim, I also fixed a few other bugs that were causing failures in various CI workflows (usually related to missing permissions):

- https://github.com/2i2c-org/infrastructure/pull/2722
- https://github.com/2i2c-org/infrastructure/pull/2698

**Comment by damianavila** [comment]
> waiting for data to accumulate

How much time do we want to wait for data collection?

> So far, we have only had one failure related to the API rate limit since the merge of https://github.com/2i2c-org/infrastructure/pull/2627

1 failure in 3 weeks is less than I was expecting, do you think the refactor helped a little bit?

**Comment by sgibson91** [comment]
> How much time do we want to wait for data collection?

Next Monday will be 28 days since the merge of the PR and I think that is ample time to detect any trends.

> 1 failure in 3 weeks is less than I was expecting, do you think the refactor helped a little bit?

I think #2627 helped a lot

**Comment by damianavila** [comment]
This is awesome, thanks for working on this one @sgibson91!!
