### ISSUE TITLE
Increase the validity of the AzureAD credentials for UToronto JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1693]
Currently, the UToronto JupyterHub has credentials for talking to AzureAD for authenticating end users that expire once a year, on Aug 30. We should either remove this expiration date, or consider increasing it to two years.

**Comment by sgibson91** [comment]
Do we have the ability to make this decision, or is it in the hands of UToronto IT?

**Comment by yuvipanda** [comment]
@sgibson91 I think it's in the hands of University IT. I've opened https://2i2c.freshdesk.com/a/tickets/197 with University IT and Jeremy to discuss.

**Comment by damianavila** [comment]
They replied back in the ticket:

> I’d prefer not to go back and revise it now but would certainly be open to doing two years on next renewal.

So I guess this is not something achievable right now. I would close this one now but feel free to reopen it if you feel we should fight back.
