### ISSUE TITLE
UTexas hub spawn and deploy issues

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1738]
### Context

There are three issues with the utexas hub that are probably related:

- The deploy on the 2i2c cluster fails for some time and it seems to be erroring for the utexas hub.

  - https://github.com/2i2c-org/infrastructure/actions/runs/3172778558/jobs/5167745829#step:4:74
  - https://github.com/2i2c-org/infrastructure/actions/runs/3161567755/jobs/5147401433#step:4:74
  - ....
  - https://github.com/2i2c-org/infrastructure/actions/runs/3102175042/jobs/5024451954#step:4:73

- Spawning a server on the https://utexas.pilot.2i2c.cloud hub fails
- The old `utexas-demo` hub is still running https://utexas-demo.pilot.2i2c.cloud

### Proposal

- [ ] maybe a cleanup of the old namespaces, pods and resources and re-deploy might solve it

### Updates and actions

- I noticed the old hub's namespace (`utexas-demo`) and resources (volumes) still exist
- The claim can't be created  and fails with this error:

  ```
  Warning  FailedBinding  3m4s (x12982 over 2d6h)  persistentvolume-controller  volume "utexas-home-nfs" already bound to a different claim.
  ```
   But the volume appears as `released`

    ```
    35:utexas-home-nfs                            1Mi        RWX            Retain           Released   utexas/home-nfs                                               237d
    ```
    
- Is the `utexas-demo` the hub that has been actually used and not the `utexas` one?

**Comment by damianavila** [comment]
Accordingly to @colliand this hub can be decommissioned: https://github.com/2i2c-org/leads/issues/52#issuecomment-1155728242. Somehow it seems we lost track of that request!

So I will open a decommission issue for this hub and then this one should self-resolve.

**Comment by GeorgianaElena** [comment]
Oh, so this is why nobody complained I guess.

> So I will open a decommission issue for this hub and then this one should self-resolve.

Thanks @damianavila. Can you please also add the `utexas-demo` old resources to the list of things to delete in that issue please?

**Comment by damianavila** [comment]
Created the decomission issue here: https://github.com/2i2c-org/infrastructure/issues/1739 and added the additional utexas-demo removal task.

**Comment by GeorgianaElena** [comment]
Thanks @damianavila!
