### ISSUE TITLE
Document how to create a new AWS project

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1741]
### Context

Currently, we only have documentation describing how to create new, 2i2c-managed cloud projects on GCP: https://infrastructure.2i2c.org/en/latest/howto/cloud/new-gcp-project.html
For https://github.com/2i2c-org/infrastructure/issues/1702, we will need also need to create a new AWS project (account) and connect it to our management account - so we should use this opportunity to document those steps for the future.

### Proposal

@yuvipanda probably has all of this knowledge in his head, we just need to extract it!

Here are some suggested paths forward:

1. @sgibson91 and Yuvi get on a Zoom screenshare. Yuvi goes through the necessary actions to setup the new AWS account while Sarah captures the steps in a document that can be fleshed out and submitted as a PR separately.
2. Sarah gives it a shot herself, documenting as she goes, and asks Yuvi to review/provide insight on steps she's stuck on.
3. [Scribe](https://scribehow.com/) is a great tool for capturing workflows that involve clicking things in GUIs and automatically transforms them into a workflow. We could turn path 1 into an asynchronous option by Yuvi using Scribe as he sets up the account and passing the generated workflow to Sarah to flesh out into proper documentation separately.

**Comment by sgibson91** [comment]
Assigned myself to lead and Yuvi to help

**Comment by yuvipanda** [comment]
@sgibson91 yes I love that! Let’s do it!

**Comment by sgibson91** [comment]
We had a screenshare meeting! Rough notes are here: https://hackmd.io/@sgibson91/SkSwppFGj I also recorded the meeting too to help when writing this up

**Comment by yuvipanda** [comment]
@sgibson91 We should also do a quota check here, and request what we need early on
