### ISSUE TITLE
Pod sandbox warning on pod startup

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1743]
### Context

This is a report coming through support from the lis hub: https://2i2c.freshdesk.com/a/tickets/210

This is just a warning (no usage implication confirmed):

```
2022-10-03T21:25:49Z [Warning] Failed to create pod sandbox: rpc
error: code = Unknown desc = failed to setup network for sandbox
"bb39d6b8d516b658ee0bd2c407cbc249c9176920baa20f489e9ab83379b62823":
stat /var/lib/calico/nodename: no such file or directory: check that
the calico/node container is running and has mounted /var/lib/calico/
```

### Proposal

Investigate the warning cause in case it was a symptom of a problem that needed to be addressed.

**Comment by sgibson91** [comment]
This happens on new nodes when networking (from `calico`) hasn't been pulled yet. If I remember correctly from previous conversations with @yuvipanda, it resolves itself once the `calico` pieces are pulled onto the node and is harmless. But would be great to have that confirmed.

**Comment by yuvipanda** [comment]
Yeah, it is harmless 99% of the time and 1% of the time it means ‘this node is fucked, good luck m8’

**Comment by damianavila** [comment]
Thanks for the quick feedback, folks!
I am going to close this one now since I think we have enough information about this warning.
