### ISSUE TITLE
Change AWS Management Account setup so that verification emails for new accounts go to our support address

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1745]
### Context

During https://github.com/2i2c-org/infrastructure/issues/1741, the verification email for the new project we made was sent to Chris's email. This should go to support instead so that it is not a bottleneck.

I imagine this setting lives somewhere in the AWS Management Account: `2i2c-sandbox`

**Comment by sgibson91** [comment]
Georgiana found a path forward for changing the email address in: https://github.com/2i2c-org/infrastructure/issues/1816#issuecomment-1293656301

**Comment by damianavila** [comment]
I would say the recommended way right now is to use the suffix approach described in step 5: https://infrastructure.2i2c.org/hub-deployment-guide/cloud-accounts/new-aws-account/

> Enter an email address for the account’s owner
> Use support+aws-<aws account name>@2i2c.org, like support+aws-smithsonian@2i2c.org. It will still be delivered to support@2i2c.org but still function as a unique username identifier. This is called [subaddressing](https://en.wikipedia.org/wiki/Email_address#Subaddressing).
