### ISSUE TITLE
Adjust to modern dask-gateway Helm chart and avoid needing to manage an api token

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1754]
I've opened https://github.com/dask/dask-gateway/pull/612 and tried it out in the JMTE deployment with associated changes in the deployer script as found in [this commit](https://github.com/2i2c-org/infrastructure/pull/436/commits/2a0ff8ae116d9bbefec492351bfc83406ae42cc9).

I'm opening this issue to track the work item of:
- [ ] Bumping to using the dask/dask-gateway helm chart to `2022.10.0` and updating configuration etc by cherry-picking [the JMTE commit](https://github.com/2i2c-org/infrastructure/pull/436/commits/50dc2534656be1d09d5ba5c30308318b6bc61857) adjusting the deployer script to no longer specify an api-token manually.

**Comment by yuvipanda** [comment]
YESSSS I LOVE IT

**Comment by consideRatio** [comment]
Dask gateway 2022.10.0 is out and can now benefit from this. As long as dask-gateway and jupyterhub is installed in the same namespace, api tokens doesn't have to be specified.

There still needs to be a hub.services.dask-gateway service defined at all, so let it contain `display: false` for example. An example of how to adjust to the new functionality can be found in https://github.com/dask/helm-chart/pull/331.
