### ISSUE TITLE
Restructure our infrastructure docs

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1757]
### Context

We are getting a lot of docs in infrastructure.2i2c.org now, and I think the "how-to" section is becoming a bit of a "catch-all" area, which ultimately makes the docs you need more difficult to find.

### Proposal

I'm proposing we refactor and split up the "how-to" section into the following, separate sections:

* **Hub Deployment Guide**
  * This contains all the documentation required for deploying hubs and enabling/configuring specific features
  * It should follow, more or less, the order of operations required to deploy a hub so an engineer can just step through the docs in order, i.e., start with "Create new cloud accounts" -> "Create a k8s cluster" -> "deploy support infrastructure" -> "deploy a hub" -> and then we get into the realm of turning on/off specific features so this part can be less structured I think
* **Site Reliability Engineering Guide**
  * This contains day-to-day tasks we do _outside_ of hub deployments, e.g., a lot of the content currently under ["Cloud and Kubernetes infrastructure"](https://infrastructure.2i2c.org/en/latest/howto/k8s/index.html) and ["Support"](https://infrastructure.2i2c.org/en/latest/howto/support/index.html)
  * When we have incidents and work out how to resolve them, the solutions should be documented under this guide for the next occurrence (where the solution is not a "this will never happen again" kind of fix, which obviously we should be aiming for)

What does @2i2c-org/tech-team think? I am happy to implement this if we have consensus.

### Updates and actions

New docs:

- [x] https://github.com/2i2c-org/infrastructure/issues/1757#issuecomment-1285659593
- [x] https://github.com/2i2c-org/infrastructure/issues/1757#issuecomment-1285890909 (#1806)

Common problems and their solutions (troubleshooting/support):

- [ ] ~~https://github.com/2i2c-org/infrastructure/issues/1757#issuecomment-1286117676 (https://github.com/2i2c-org/infrastructure/pull/1780#issuecomment-1282096496)~~
- [x] https://github.com/2i2c-org/infrastructure/issues/1757#issuecomment-1287027429
- [x] https://github.com/2i2c-org/infrastructure/issues/1757#issuecomment-1292666904 (https://github.com/2i2c-org/docs/issues/100#issuecomment-925962073)

**Comment by yuvipanda** [comment]
I LIKE!

**Comment by damianavila** [comment]
Yep, I like it as well!

**Comment by sgibson91** [comment]
Need to ensure the refactor contains info on setting CNAMES when communities want to use their own DNS

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/issues/1806 should also be added as part of this

**Comment by damianavila** [comment]
Another one proposed by @sgibson91: https://github.com/2i2c-org/infrastructure/pull/1780#issuecomment-1282096496

**Comment by sgibson91** [comment]
Another thing to document: "How to 'reset' GitHub OAuth apps when folk are seeing `403 Forbidden` errors" (providing you have access discussed in #1806)

**Comment by sgibson91** [comment]
Another clean-up operation: https://github.com/2i2c-org/infrastructure/issues/1815

**Comment by GeorgianaElena** [comment]
The new cluster section also confuses me a bit.

There are two sections and it's not clear from the start that the `new-cluster` refers to gcp and azure only.

<img width="296" alt="Screenshot 2022-10-26 at 14 52 45" src="https://user-images.githubusercontent.com/7579677/198019415-34dbdf16-98d6-4c99-845c-e8ff9171611e.png">


https://infrastructure.2i2c.org/en/latest/howto/operate/new-cluster/new-cluster.html
https://infrastructure.2i2c.org/en/latest/howto/operate/new-cluster/aws.html

**Comment by sgibson91** [comment]
@GeorgianaElena This is what it looks like in my new structure, is this an improvement or could it use further tweaking?

<img width="249" alt="Screenshot 2022-10-26 at 13 11 08" src="https://user-images.githubusercontent.com/44771837/198022762-bad009fe-8902-4edc-9c66-4d7231807dad.png">

I think the reason that it is not specific that it is GCP and Azure is because it is AWS that has the distinctly different workflow, and, in the long-term, we will work to bring AWS closer to GCP and Azure's workflows (which are almost identical)

**Comment by GeorgianaElena** [comment]
It absolutely better! I would still like to have the `gcp and azure` part in the title though, since I believe that page strictly relates to these providers, right? If not, maybe it's worth to have the common part in an "index.md"?

**Comment by sgibson91** [comment]
A _lot_ of the content is common though - basically all of it. We address the GCP or Azure-specific parts with tabs within that document like so (I think there are parts where these tabs are broken though, so thanks for drawing my attention to that):

<img width="780" alt="Screenshot 2022-10-26 at 13 22 47" src="https://user-images.githubusercontent.com/44771837/198025085-64399073-09c0-4bd6-8f55-a5c14b736910.png">

The idea would be eventually the AWS setup is similar enough that it also becomes a tab and we only have one new cluster page.

**Comment by sgibson91** [comment]
@GeorgianaElena Does this help?

<img width="1106" alt="Screenshot 2022-10-26 at 14 14 59" src="https://user-images.githubusercontent.com/44771837/198035453-f718e8e6-1240-48c8-bc9b-ad7cc20dafd1.png">

**Comment by GeorgianaElena** [comment]
@sgibson91, first of all, thank you so much for your effort for making this less confusing for me, I really appreciate it <3

> The idea would be eventually the AWS setup is similar enough that it also becomes a tab and we only have one new cluster page.

I agree. What do you think about having the two doc pages be called something really simple like:
- Add Kubernetes clusters:
  - New  Kubernetes cluster on GCP or Azure
  - New  Kubernetes cluster on AWS

Adding `terraform` in the picture, made things even more confusing for me, since I though we were using terraform to deploy on aws too now, no? https://infrastructure.2i2c.org/en/latest/howto/operate/new-cluster/aws.html#deploy-terraform-managed-infrastructure

**Comment by sgibson91** [comment]
> since I though we were using terraform to deploy on aws too now, no?

Yeah, not completely. This is complicated and sucks 😭 We don't deploy the cluster with Terraform, only stuff like storage buckets.

I guess I was trying to avoid singling out GCP and Azure because they are so similar and it's AWS that's the pain in the butt. But if it's not helping, let's just do it.

**Comment by sgibson91** [comment]
I have also updated the "attention" box [here](https://infrastructure.2i2c.org/en/latest/howto/operate/new-cluster/new-cluster.html) to read "we do not deploy clusters to AWS _solely_ using terraform"

**Comment by damianavila** [comment]
Another one that could be added to this one (since we are collecting multiple requests here): https://github.com/2i2c-org/docs/issues/100#issuecomment-925962073 as per recent a ccsf outage caused by a full disk.

**Comment by sgibson91** [comment]
I tried to tidy up the Topics section a bit since it was getting long, what do folk think of this?

![Screenshot 2022-10-27 at 16 24 11](https://user-images.githubusercontent.com/44771837/198332016-47fbf190-6c9d-4ce7-81ac-75ceaf1cbc54.png)

**Comment by sgibson91** [comment]
> Another one proposed by @sgibson91: [#1780 (comment)](https://github.com/2i2c-org/infrastructure/pull/1780#issuecomment-1282096496)

I'm not sure I can include this one in my PR, mostly because _I_ don't know how to tell the difference between a WAL failure and an OOM in Prometheus, so someone with that knowledge will need to contribute this piece.

**Comment by yuvipanda** [comment]
@sgibson91 I don't either, and that prometheus is down again. I don't think we should block this PR on that. /cc @damianavila to help figure out how to track that the prometheus for pangeo-hubs is still down.

**Comment by damianavila** [comment]
> I don't think we should block this PR on that. /cc

I agree.

> @damianavila to help figure out how to track that the prometheus for pangeo-hubs is still down.

Yep, sorry for the delay on that one, I have created an issue to track that problem here: https://github.com/2i2c-org/infrastructure/issues/1843.
