### ISSUE TITLE
Is resource usage being monitored?

### ISSUE THREAD

**Issue by betolink** [2i2c-org/infrastructure#1762]
### Context

Last December we had an unauthorized access incident with the Openscapes hub and I was wondering if there are alerts in place in case one of our users gets hacked and starts mining bitcoin (hypothetical). A little related to this, it would be neat if in the admin dashboard we could see the instance type each user is running and maybe this already exist but another thing it would be nice is a weekly/monthly report on usage statistics like CPU/memory/network (inbound/egress) per user.

**Comment by yuvipanda** [comment]
Hey @betolink! Yes we keep a look out, and we are also implementing more active alerts now (see https://github.com/2i2c-org/infrastructure/issues/1804). Sorry we missed this issue - we're mostly looking for support questions and what not from support@2i2c.org.

Perhaps we can give you access to the grafana instance for openscapes and that would help?

**Comment by consideRatio** [comment]
> Perhaps we can give you access to the grafana instance for openscapes and that would help?

I've just given access to @betolink (https://grafana.openscapes.2i2c.cloud).

**Comment by betolink** [comment]
@consideRatio maybe a dummy question but.. how do I login or set my password for the first time?

**Comment by consideRatio** [comment]
> @consideRatio maybe a dummy question but.. how do I login or set my password for the first time? (since there is no "sign with Github" button)

Arrrgh sorry, the state got reset. @yuvipanda do you have time to consider #2178 which includes the openscape changes and more?

**Comment by yuvipanda** [comment]
@consideRatio approved

**Comment by consideRatio** [comment]
@betolink @yuvipanda merged

I think in 10 minutes, it should work again @betolink !

**Comment by betolink** [comment]
This is weird, the OAuth redirect didn't work for some reason. @consideRatio 

![Screenshot from 2023-02-09 09-36-30](https://user-images.githubusercontent.com/717735/217859647-f542125f-608e-4200-8f07-9eb87749123c.png)

**Comment by betolink** [comment]
Yep, I thought it was linked to my Github user and I just noticed it needs the Openscapes read access, since I'm not an admin there I just requested it. Thanks @consideRatio !!

**Comment by consideRatio** [comment]
@betolink ah so the organization must allow the GitHub OAuth application to read whom are members so it can determine if you are part of it. I was thinking it was you that would grant the GitHub OAuth application permission to know if you are part of the organization.

Thank you @betolink for figuring this out and helping me understand this part as well!

**Comment by betolink** [comment]
@consideRatio great news! I can access the dashboard but I don't think I'm an admin so I can't add more users, would it be possible to add @BriannaLind and @amfriesz 
Thanks!

**Comment by consideRatio** [comment]
@betolink from user activity in the grafana instance, I see that this seems resolved on your end - presumably by adding `@BriannaLind` and `@amfriesz` to the nasa-openscapes organization?

Thanks for sorting it out yourself! For anything further, please refer to https://docs.2i2c.org/en/latest/support.html.
