### ISSUE TITLE
Change GPUs to T4s on all Pangeo hubs

### ISSUE THREAD

**Issue by rabernat** [2i2c-org/infrastructure#1765]
### Context

Based on conversations with @ngam over in https://github.com/pangeo-data/pangeo-docker-images/issues/387#issuecomment-1276440089, we have decided that we would like to change from using K80 GPUs to T4 GPUs.

T4s have better support from the highly complex CUDA software stack. As you can see from the above thread, it is very difficult to maintain a functional docker image that allows ML libraries like tensorflow and jax to work with GPUs. Making this change will help reduce this burden. In the words of @ngam

> The best of all worlds (cost, etc.) seem to be T4 and there are free versions for exploratory work (e.g. planetary computer, the never-available sagemaker free tier, and the ever-present colab all have T4s readily) and T4 supports more interesting modern optimizations (I believe)

### Proposal

We redeploy the LEAP and M2LInES with a new (T4) GPU nodepool and update the profile list accordingly.

**Comment by yuvipanda** [comment]
Here are things I've done on the m2lines hub today, in conjunction with https://github.com/pangeo-data/pangeo-docker-images/issues/387

1. Provision T4 GPUs alongside the current K80 GPUs
2. Cleanup the profile list so it shows up as dropdown options to be selected
3. Add ability to select which GPU driver should be installed for GKE - 'latest' or 'stable'
4. Switch m2lines to 'latest' GPU driver
5. Upgrade m2lines k8s cluster to latest available, to get to newest possible GPU driver.

**Comment by rabernat** [comment]
Fantastic! Thanks so much Yuvi!

**Comment by scottyhq** [comment]
Is this only for m2lines? It would be neat to also expose this on https://us-central1-b.gcp.pangeo.io for people to try out GPUs if possible.

**Comment by rabernat** [comment]
That hub is currently open to the entire world. I'd worry about the costs and potential for abuse. That said, we don't have the ability to tie user activity to total hub costs, so it's hard to be quantitative here.

**Comment by yuvipanda** [comment]
@scottyhq @rabernat unfortunately that hub is on us-central1-b, which actually has *no* GPUs at all. We'll need to redeploy it to us-central1-c to get any GPUs ;(

**Comment by scottyhq** [comment]
OK! In that case I'll make a request to try this profile list and nodegroup as well with https://snowex.uwhackweeks.2i2c.cloud since we got the GPU quotas on that AWS account bumped and I'd love to kick the tires :)

**Comment by yuvipanda** [comment]
@scottyhq yay great! Can you actually email to support@2i2c.org so it can go through our regular flow for these requests? Thank you!

**Comment by yuvipanda** [comment]
We now have both T4 & k80 GPUs on all the hubs that have GPUs.

@TomNicholas @dhruvbalwada @rabernat @scottyhq can we get rid of the k80 now and just have T4s?

**Comment by rabernat** [comment]
Fine with me.

**Comment by dhruvbalwada** [comment]
Agreed.
