### ISSUE TITLE
ml-notebook does not have the 'SCRATCH_BUCKET' env variable is not set correctly

### ISSUE THREAD

**Issue by dhruvbalwada** [2i2c-org/infrastructure#1774]
The environment variable 'SCRATCH_BUCKET', which links to users scratch only seems to be configured on the regular notebooks and not the machine learning notebooks (I checked the tensorflow ones).

**Comment by yuvipanda** [comment]
This is caused by https://github.com/2i2c-org/infrastructure/issues/1530 I believe.

**Comment by yuvipanda** [comment]
@dhruvbalwada try now?

**Comment by dhruvbalwada** [comment]
This works, closing now.
