### ISSUE TITLE
dask dashboard does not produce the correct/accessible link in ml-notebooks

### ISSUE THREAD

**Issue by dhruvbalwada** [2i2c-org/infrastructure#1775]
The dask dashboard is not properly configured on the ml-notebook. When I do the following to be able to view the dashboard
```
import distributed

client = distributed.Client()
client
```
I get the dashboard link http://127.0.0.1:46197/status, which not accessible on the cloud. It should instead be something like: https://m2lines.2i2c.cloud/user/dhruvbalwada/proxy/8787/status (as is the case for the regular notebooks).

**Comment by yuvipanda** [comment]
Probably caused by https://github.com/2i2c-org/infrastructure/issues/1530

**Comment by yuvipanda** [comment]
@dhruvbalwada try now?

**Comment by dhruvbalwada** [comment]
This works.
