### ISSUE TITLE
Provide NVIDIA T4 GPU support for `snowex.uwhackweeks` hub

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1784]
### Context

Checout the support ticket https://2i2c.freshdesk.com/a/tickets/219  and https://github.com/2i2c-org/infrastructure/issues/1765#issuecomment-1279360493 for context.

### Proposal

Offer access to [nvidia T4 GPUs](https://www.nvidia.com/en-us/data-center/tesla-t4/) to the https://snowex.uwhackweeks.2i2c.cloud as a profile option (similar to m2lines & LEAP hubs in https://github.com/2i2c-org/infrastructure/pull/1766)

Note:
The https://snowex.uwhackweeks.2i2c.cloud hub is deployed on AWS, where the T4 gpus are provided through EC@ G4 instances https://aws.amazon.com/ec2/instance-types/g4/

**Comment by yuvipanda** [comment]
We have some docs in https://infrastructure.2i2c.org/en/latest/howto/features/gpu.html?highlight=gpu on how to do this for AWS!

**Comment by yuvipanda** [comment]
@GeorgianaElena i took this on since I'm steeped in GPU support over the last few weeks. I've cleaned up docs to remove some steps, and deployed this as well.
