### ISSUE TITLE
Enable Service Quota Request templates on our AWS accounts

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1793]
### Context

For pretty much every cloud account we open on any cloud vendor, we want to bump certain quotas so that usage is not restricted. E.g., total number of CPUs in the region/zone, total GPUs in the region/zone, etc.

AWS provide a [Service Quota Request templates service](https://docs.aws.amazon.com/servicequotas/latest/userguide/organization-templates.html) where a maximum of 10 quota increases can automatically be requested whenever a new account is created within the organisation.

### Proposal

We should enable this feature for our AWS org and remove a manual step from our "new AWS account" setup process.

**Comment by yuvipanda** [comment]
I've enabled the template, and added a default for asking for 4 GPU instances in us-west-2 by default.

**Comment by yuvipanda** [comment]
@GeorgianaElena when you craeted the gridsst hackathon project, did you request quota manually or were the defaults what they are now?

**Comment by yuvipanda** [comment]
and I've manually requested it for the victor project, just in case.

**Comment by GeorgianaElena** [comment]
Thanks @yuvipanda! I didn't request for any of them, they were using the defaults

**Comment by sgibson91** [comment]
> I've enabled the template, and added a default for asking for 4 GPU instances in us-west-2 by default.

Great thanks! Is there anything else to do to close this one? Maybe update the docs [here](https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/cloud-accounts/new-aws-account.html#checking-quotas-and-requesting-increases) to say that this happens now?

**Comment by damianavila** [comment]
> Maybe update the docs [here](https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/cloud-accounts/new-aws-account.html#checking-quotas-and-requesting-increases) to say that this happens now?

Yep, it should be documented.
