### ISSUE TITLE
Transfer Pangeo infrastrcuture from Columbia into 2i2c territory

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1799]
### Context

After failure to get sustainable access to Columbia playground: https://github.com/2i2c-org/meta/issues/348, we decided we need to move forward with moving Pangeo infra to a 2i2c managed account.

We have an agreement from the community representative as per: https://github.com/2i2c-org/meta/issues/348#issuecomment-1279241994.

We need to figure out details about capacity involvement and the timeline.

**Comment by pnasrat** [comment]
Given pangeo access is part of onboarding checklist eg  2i2c-org/team-compass#651 is this likely to transferred anytime soon, and would I need access to existing?

**Comment by yuvipanda** [comment]
@pnasrat I think we have given up on this happening for now, so you'd have to access the existing one I think.

**Comment by jmunroe** [comment]
That's correct. We are now in the last year of that Columbia-held Pangeo infrastructure grant.  I am working on a few avenues on what a PangeoCloud 2.0 may look like (and how it would be paid for) but, for now, going through Columbia IT is still required.

**Comment by choldgraf** [comment]
We did learn from Columbia that it shouldn't be too complex to set up "pass through billing", especially since we already do this with the VICTOR project at Columbia. I think it would require some extra work to figure out the contract details. It might be a significant amount of work and/or several months before it was completed (and I'd recommend @jmunroe spearhead this if we want to go that route). But just sharing here in case people really think the benefit would be worth it.

**Comment by choldgraf** [comment]
Note that we'll need to create an amended version of our contract with Columbia as part of the no-cost extension in https://github.com/2i2c-org/meta/issues/431. So this is the time to explore doing pass-through cloud costs if we want to do it. However if I don't get a strong signal from engineering that we _need_ to do this, I'm not going to push it.

**Comment by damianavila** [comment]
> So this is the time to explore doing pass-through cloud costs if we want to do it. However if I don't get a strong signal from engineering that we need to do this, I'm not going to push it.

To answer that implicit question, I think we need to have a better picture about

> I am working on a few avenues on what a PangeoCloud 2.0 may look like (and how it would be paid for)

@jmunroe, I think this is a topic for our shared agenda in the Comm and Eng meeting (already added it as a point to discuss).

**Comment by choldgraf** [comment]
FYI I've updated the top comment of the original tracking issue and we can use that to track the various steps in the process:

- https://github.com/2i2c-org/meta/issues/279

**Comment by yuvipanda** [comment]
We have decided this is not going to happen, and just make sure we don't get into more of these situations.
