### ISSUE TITLE
Add Additional mount point to LIS hub to support return of graded materials

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#1801]
### Context

A request was raised (https://2i2c.freshdesk.com/a/tickets/228) to allow a hub administrator to upload files directly to users accounts:

> Can I ask for advice about uploading marked notebooks directly to the
> students' storage?
> 
> When I was running my own hub, I would prepare a tar file with marked
> notebooks that would unpack until all the students accounts, giving
> them their submitted, marked notebook, with the OKpy tests, in a
> special folder, `marked`, in their cloud storage. I'd do that by
> ssh'ing into the pod that mounted the cloud storage, and unpacking
> from there.
> 
> Specifically, the tar file would have structure:
> 
> student-1/marked/homework_1/my_notebook.ipynb
> student-1/marked/homework_1/tests/q1.py
> student-1/marked/homework_1/tests/q2.py
> student-2/marked/homework_1/my_notebook.ipynb
> ... etc
> 
> Can you suggest some way I can do the same thing with our current
> cloud setup? Either through an API or by direct access?

### Proposal

I think a solution is to add an additional NFS mount point to allow hub administrators read/write access to all folders on a Google Filestore. 

This additional file access provided to hub administrators is not any more than they previously had (a hub admin can already start and log into the single-user notebook server of any user).  

To achieve this we should add the following keys to `lis.values.yaml`:

```
jupyterhub:
  singleuser:
    admin:
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan/allusers
          subPath: /
```

We also should add documentation to https://infrastructure.2i2c.org/en/latest/topic/storage-layer.html (or elsewhere as appropriate) explaining that it is possible to mount a the Filestore in a way that provided read/write access to all hub admins (if that is ever a feature requested on other hubs).

**Comment by yuvipanda** [comment]
+1. We should also carefully tell them that this means they can completely delete everyone's work accidentally so BE CAREFUL

**Comment by GeorgianaElena** [comment]
The hub admin asked for this feature asap, so I'm self-assigning this and tackle it in https://github.com/2i2c-org/infrastructure/pull/1811
