### ISSUE TITLE
Add hub engineer to GitHub org as admin to facilitate hub setup process

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1806]
When setting up a hub, we have to do an OAuth approval process that requires action from the admin of the GitHub org that is going to be used to log in. This requires a back-and-forth with the GitHub admin that can take sometime (see https://github.com/2i2c-org/infrastructure/issues/1702#issuecomment-1285882952) for example.

Instead, part of our hub setup process should include:

1. Add the hub engineer in question as an org admin to the GitHub org that'll be used for access control
2. They remove themselves once auth is set up

**Comment by sgibson91** [comment]
I have documented this in commit [`53dfe3a` (#1814)](https://github.com/2i2c-org/infrastructure/pull/1814/commits/53dfe3a7cf8ec5a38a9409615dbb525120d427dd) of #1814, but I think to truly close this issue, we also need to update the "New Hub" issue(s) to ensure that this is a checklist item there.

In general, I don't think those issue templates are yet configured to capture whether a community wants github org/team style auth yet. We should upgrade that.
