### ISSUE TITLE
Update/change certain action steps in our workflows that are running old versions of Node

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1807]
### Context

On a recent CI/CD deployment run, I got the following warning(s):

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: jitterbit/get-changed-files
```

I don't think `jitterbit/get-changed-files` is well maintained, so we may need to swap to the `dorny/paths-filter` action we use in our validation workflow which has similar functionality and _didn't_ trigger this warning.

**Comment by sgibson91** [comment]
PR is here:

* https://github.com/2i2c-org/infrastructure/pull/1870

**Comment by sgibson91** [comment]
Reopening because there are other actions that are triggering this warning. They will be more difficult to swap out though, and we may need to wait for upstream releases.

- [azure/setup-helm](https://github.com/Azure/setup-helm)
- [azure/setup-kubectl](https://github.com/Azure/setup-kubectl)
- [mdgreenwald/mozilla-sops-action](https://github.com/mdgreenwald/mozilla-sops-action)
- [nick-fields/retry](https://github.com/nick-fields/retry)

**Comment by damianavila** [comment]
@sgibson91, I just assigned you because you already started to work on this one, we can change the assignment if/when someone else picks this up later down the road.

**Comment by sgibson91** [comment]
Wouldn't it be better to leave it unassigned so that we know someone needs to think about it? I'm worried if we leave my assignment it will just default to being my responsibility to solve.

**Comment by damianavila** [comment]
That's a good point... let me just adjust the priority so we can quickly rediscover it.

**Comment by sgibson91** [comment]
<img width="653" alt="Screenshot 2023-01-11 at 10 03 12" src="https://user-images.githubusercontent.com/44771837/211778219-65b62977-4d39-4484-a732-84ca06c51d7a.png">

Two actions are still giving us this node warning. I checked the releases for both and they have both switched over to Node 16. I'm going to bump our versions of the actions to see if that removes the annotation.

**Comment by damianavila** [comment]
We think it is resolved.

**Comment by consideRatio** [comment]
I checked manually and found one missing piece, resolved fully by merging https://github.com/2i2c-org/.github/pull/13
