### ISSUE TITLE
Update 2i2c Demo Hub

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#1813]
### Context

Our demo hub is currently running at https://demo.2i2c.cloud/

As indicated at the bottom of the page https://infrastructure.2i2c.org/en/latest/reference/hubs.html?highlight=list%20of%20hubs#, "This hub is primarily for the 2i2c team to try things out, and it may change or break occasionally. Team members should feel free to experiment with this hub and try out new functionality and features they’d like to show off to others."

If it is to be used as our "showcase" hub, I think we need to be able to
- demo 'daskhub' helm chart and not just 'basehub'
- support multiple machine sizes on start up
- support multiple images (R environment and a Python environment?)
- support Linux desktop via VNC
- run a demo hub on both GCP and AWS (useful for benchmarking loading large datasets from either provider)
- allow access to a GPU (if possible)
- updated user images
- update JupyterLab with additional extensions (e.g. s3 browser, GitHub integration)
- persistent cloud storage

I see that we already have [dask-staging.2i2c.cloud](https://dask-staging.2i2c.cloud/) but it is not clear to me that hub should be used for demos/testing.

### Proposal

For whatever reason, I am not a hub admin on https://demo.2i2c.cloud/, so my only immediate request from the @2i2c-org/tech-team 

- [x] Add @jmunroe as a hub admin to https://demo.2i2c.cloud

The other items listed about are more for discussion at this this point.  As a motivating example, I think there are lot of great things in the JMTE hub that we should be showcasing in our 'demo' hub.

**Comment by sgibson91** [comment]
@jmunroe You are now an admin on the demo hub.

All `staging` hubs are designed as places to freely test changes without worrying about interfering with users before rolling changes out to prod. So it can absolutely be used for testing. Demos maybe less so, as it could break at any moment depending on what dev work folk are doing.

**Comment by damianavila** [comment]
Thanks for making @jmunroe admin on the demo one, @sgibson91.

Then, I guess we might want to have 2 demo hubs: one base one (the existing one) and another one based on a daskhub with the specification outlined above (resembling the JMTE experience).

Alterntively, we can just make [demo.2i2c.cloud](https://demo.2i2c.cloud/) the powerful one.

Thoughts?

**Comment by sgibson91** [comment]
> we can just make [demo.2i2c.cloud](https://demo.2i2c.cloud/) the powerful one.

The point of the demo hub is that _anyone_ can create an account and start using it. I'd worry that enabling dask would make us more vulnerable to abuse.

**Comment by damianavila** [comment]
So let's keep the current base demo as is and create a powerful dask demo for our stuff.

**Comment by jmunroe** [comment]
As a strategic priority for Product development and for Community/Partnerships it will be useful to have a full-featured "demo" hub available that showcases what is possible with our research hub.

**Comment by GeorgianaElena** [comment]
I noticed that there's a bit confusion about the 2i2c demo hub being opened to the world. It's not anymore:
https://github.com/2i2c-org/infrastructure/blob/f559fbb562302f371f01b0cdf6e1efcfa84101d0/config/clusters/2i2c/demo.values.yaml#L23-L24

I believe we made the auth more strict after some abuse happened. This shouldn't make any difference for the current decision about deploying a new one, but rather some extra info that I just realized

**Comment by jmunroe** [comment]
We now have https://researchdelight.2i2c.cloud which serves the purpose as a "full featured" demo of what a research intensive JupyterHub deployment looks like.  

I'll be continuing to refine that image but it definitely addresses the original intent of this particular issue.
