### ISSUE TITLE
Not able to create another AWS account under the support email

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1816]
### Context

The instructions in https://infrastructure.2i2c.org/en/latest/howto/cloud-accounts/new-aws-account.html?highlight=aws#create-a-new-aws-account suggest that we should use the `support@2i2c.org` email address for the account owner, but this fails with `EMAIL_ALREADY_EXISTS`.

According to aws docs at https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_create.html

```
5. For Email address of the account's owner, enter the email address of the account's owner.
This email address cannot already be associated with another AWS account because it becomes
the user name credential for the root user of the account.
```

### Proposal

We should update our docs and figure out the right way to achieve both creating a new project and also use a shared email address to avoid bottlenecks.

**Comment by GeorgianaElena** [comment]
I have used my 2i2c email address for the gridSST Hack-A-Thon event. Not sure what kind of info is sent to the email address associated with the account, but having the entire tech team as admins should reduce bottleneck as much as possible.

But **this is not scalable** and we should find a way around it somehow.

**Comment by sgibson91** [comment]
This is so weird. We were able to use the support email when Yuvi and I setup the nasa-cryo account. Or maybe it's _because_ we set that up that way that this is now blocking.

The more I learn about AWS, the less impressed I become.

**Comment by GeorgianaElena** [comment]
I think their rule is just that we can't associate an email address that has already an aws account in the 2i2c organization account, with another one.

So, basically, Chris's, Yuvi's, support's and my 2i2c email address can't be used again for a new aws account. As a joke, we might need to hire new people soon to be able to use their email addresses if we'll need more aws accounts 🙄

I believe we should also bump the priority of https://github.com/2i2c-org/infrastructure/issues/1794. I was thinking that, at least for the uw-gridSST hackathon event for example, we already have a uw-hackweeks account and cluster on aws, in the desired region that we could have presented to the community as an option (cc @damianavila )

**Comment by sgibson91** [comment]
Can we change the email address after we create the project, and will that allow us to reuse an email address?

**Comment by GeorgianaElena** [comment]
Hmm, I don't know if there is a way to change it... I just checked all the settings I could find related to the account and couldn't find anywhere 😕

**Comment by yuvipanda** [comment]
https://support.freshdesk.com/en/support/solutions/articles/37637-adding-multiple-email-addresses-to-freshdesk lets us create unlimited aliases that can work. @GeorgianaElena if you'd like, you can also delete & recreate that aws account if you feel like - we can't really do that *after* stuff starts getting used

**Comment by damianavila** [comment]
Another trick that might be useful here is using support+`name_of_hub`@2i2c.org, right?
AFAIK, that should still send emails to support but we have a different email address per hub... unless AWS does not like that one.

**Comment by GeorgianaElena** [comment]
@consideRatio, I didn't try like this, but it seems to be working. As long as the emails come through support, then everything should be ok.

I noticed that they are already https://2i2c.freshdesk.com/a/tickets/635, so we're good I believe 🎉 🎉

**Comment by consideRatio** [comment]
Ah, thank you @GeorgianaElena for your quick review! Then I'll proceed like this and trial it all the way

**Comment by GeorgianaElena** [comment]
@consideRatio, do you want to also update the docs with this new workaround once you're sure it works?

**Comment by consideRatio** [comment]
Yepp!

**Comment by damianavila** [comment]
Nice to see the suffix approach actually worked, thanks for testing it @consideRatio!!
