### ISSUE TITLE
Create a persistent storage bucket for AWI-CIROH

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1819]
Requested in https://2i2c.freshdesk.com/a/tickets/235.

https://infrastructure.2i2c.org/en/latest/howto/features/buckets.html?highlight=persistent#setup-object-storage-buckets has some more info on how to setup the `PERSISTENT_BUCKET`

**Comment by sgibson91** [comment]
PR here:

- https://github.com/2i2c-org/infrastructure/pull/1820
