### ISSUE TITLE
Deploy kubespawner from specific commit into our infrastructure

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1825]
Ref: https://github.com/2i2c-org/infrastructure/issues/1253

@yuvipanda suggested deploying from a specific commit because of breaking changes in kubespwner.

**Comment by GeorgianaElena** [comment]
Before going down this path, just want to first double-check with @consideRatio what's his feeling around a new `kubespawner` release and whether or not I can be of help.

@consideRatio, do you think now is a good time to push for a new `kubespawner` release? I believe I can help out with that.
If not, maybe I can help with pushing forward the blocking pieces of a release.

Nonetheless, I will be deploying an unreleased version for 2i2c until we figure it out.

**Comment by consideRatio** [comment]
> @consideRatio, do you think now is a good time to push for a new kubespawner release? I believe I can help out with that.
If not, maybe I can help with pushing forward the blocking pieces of a release?

@GeorgianaElena do go for it! I think a key point about making a release is to figure out if it is a good time or not. I'd say its pretty much always a good time though - I'm thinking "why not make a release" and don't have a clear answer.

I think if you get started by creating a changelog, you will automatically end up learning about the changes made and can reflect if something is seen as problematic.

Btw here are some added details to what I think of when making a release, not part of RELEASE.md for specific projects. Certainly worth adding to and updating etc if you think of something! https://github.com/jupyterhub/team-compass/issues/563

**Comment by GeorgianaElena** [comment]
Thanks for the guidance @consideRatio!

After speaking with @damianavila, I believe the plan now is:
- get 2i2c on https://github.com/jupyterhub/kubespawner/commit/fa19acdbb056c8d105baab13bbaa2b8b59dfa962 version so we don't block the new profile list options
- get started on building the changelog for a new kubespawner release and see where or if it blocks in the review process. We can then see which are the sensitive or blocking points if any.

**Comment by GeorgianaElena** [comment]
I'm reopening this because the new hub image deploy has broke the staging hubs that used profile options because of bug https://github.com/jupyterhub/kubespawner/pull/662 I've introduced :(

I hadn't time to check the entire changelog of kubespawner. @yuvipanda, do you know if there are any breaking changes for 2i2c hubs specifically there if I were to use latest main commit?

Otherwise, I was thinking to pin to a commit on your fork https://github.com/yuvipanda/kubespawner/commits/async until I figure out the kubespawner changelog and possibly release?
