### ISSUE TITLE
Revisit our documentation to see if the checkboxes are actually relevant.

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1826]
Ref: https://github.com/2i2c-org/infrastructure/issues/1167

These are the ones we need to check:

- [x] Setting up local environment
- [ ] Topic: Logging
- [ ]  Howto: Use Logging
- [ ] Howto: Find where something is configured
- [ ] Topic: Support charts
- [ ] Howto: Deploy, decom and look at charts of support charts
- [ ] Topic: Dask-gateway and dask
- [ ] Topic: Cluster design
- [ ] Topic: Home directory storage
- [ ] Howto: Enable shared directory
- [ ] Topic: GPU configuration and debugging

**Comment by damianavila** [comment]
Moved over a comment from @sgibson91.

---

Ok, here's what _I think_ we already have covered in our docs. It may be that these docs don't quite cover what Chris and Yuvi had in mind when they came up with this list, or they are _outdated_.

| List item | Docs link |
| --- | --- |
| Howto: Find where something is configured | https://infrastructure.2i2c.org/en/latest/topic/config.html |
| Topic: Cluster design | https://infrastructure.2i2c.org/en/latest/topic/cluster-design.html |
| Topic: Home directory storage | https://infrastructure.2i2c.org/en/latest/topic/storage-layer.html |
| Topic: GPU configuration (but _not_ debugging) | https://infrastructure.2i2c.org/en/latest/howto/features/gpu.html |

**Comment by yuvipanda** [comment]
I have gone through the original issue, and created subtasks with specific outlines for documentation that still needs to be created: https://github.com/2i2c-org/infrastructure/issues/1167#issue-1191044434. Thanks for these links, @sgibson91!

**Comment by damianavila** [comment]
> I have gone through the original issue, and created subtasks with specific outlines for documentation that still needs to be created: https://github.com/2i2c-org/infrastructure/issues/1167#issue-1191044434.

Amazing work, @yuvipanda and @sgibson91! I have included them in the board with proper status, type, priority, and associated theme.
