### ISSUE TITLE
Why hubs have kernel time limits

### ISSUE THREAD

**Issue by dhruvbalwada** [2i2c-org/infrastructure#1829]
Why do the kernels on the hub die if they have been sitting idle for a while? I would understand if the hub was killed to save resources, but it doesn't make sense to me why the kernel is killed. I am assuming there is a good reason for this, can someone please explain? 

I am using m2lines hubs.

**Comment by sgibson91** [comment]
Hi. We prefer questions like this to come through `support@2i2c.org` as we open a lot of issues here to track tasks and it's likely questions like this will get missed. Our support email has folk dedicated to watching it and responding to requests/questions there so we won't forget about it. Many thanks!
