### ISSUE TITLE
[Research Hubs] Disable kernel culling when kernel is still connected

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1834]
### Context

This has been raised in response to a ticket https://2i2c.freshdesk.com/a/tickets/243
 

### Proposal

On research hubs, don't kill kernels that are still "connected" but aren't actively running something.

More about the default culling configuration here deployed on 2i2c hubs👇🏼 
https://infrastructure.2i2c.org/sre-guide/manage-k8s/culling/#kernel-culling-configuration

### Updates and actions

- *"Turn `cull_connected` to false for research hubs"* (@yuvipanda's comment in https://2i2c.slack.com/archives/C028WU9PFBN/p1666983756278409)

**Comment by damianavila** [comment]
This is superseded by recent conversations and a PR for a default culling configurable by community needs.

**Comment by yuvipanda** [comment]
@damianavila which PR is that? I don't see any other conversations or PR related to *kernel culling*. I think there's one for setting max-age, but that's unrelated to this.

**Comment by damianavila** [comment]
Yep, you are right!
We were discussing recent culling-related conversations and we missed the point about the *kernel* on this one...
I see we only extended it for the m2lines, we should extend it to other research-like hubs.
Thanks for reopening it.
