### ISSUE TITLE
Document how to test custom JupyterHub images locally

### ISSUE THREAD

**Issue by zaneselvans** [2i2c-org/infrastructure#184]
Before updating the custom image we're using for our JupyterHub, it would be nice to be able to test it locally a bit more extensively, but it wasn't immediately clear to me how to do that... I am building an image with `repo2docker`. Issues that came up for me:
* Our tutorial notebooks (and collaborations) currently depend on data which is stored in the `shared` directory on the JupyterHub. I'd like to be able to mount a local directory into the container while it's running locally to see if the tutorial notebooks run against that data.
* The docker image runs fine and serves up a notebook server when `repo2docker` runs, but after quitting out of that server, I wasn't able to re-start the server from the local image within Docker -- I think it had to do with the port mapping. It would start up just fine and tell me it was running on localhost:8888 but there was no notebook server at that address. Having to run through the entire repo2docker process just to restart the server was a bit of a hassle, as the build takes a long time (slow net connection mostly, but also conda solving)

**Comment by zaneselvans** [comment]
Okay, I got the ports published correctly with
```bash
docker run --publish 127.0.0.1:8787:8888 catalystcoop/pilot-hub:2021.01.22
```
But I see that the connection instructions the notebook server prints out (understandably) refer to the internal port:
```
[I 2021-02-02 17:48:57.795 ServerApp] Jupyter Server 1.2.2 is running at:
[I 2021-02-02 17:48:57.795 ServerApp] http://8528f62c11c8:8888/lab?token=b774c862a598dcfa42158508e17d75db1f573ef53519a650
[I 2021-02-02 17:48:57.795 ServerApp]  or http://127.0.0.1:8888/lab?token=b774c862a598dcfa42158508e17d75db1f573ef53519a650

```
Whereas when the server is started up at the end of the `repo2docker` process, it I think it gave the external port number. Is there an easy way to change this behavior so as not to confuse a user that's trying to run the container locally? Or is there some magic happening in `repo2docker`?

**Comment by zaneselvans** [comment]
I notice that when I run the container locally, all of the files that exist in the GitHub repository are present, but when the same container is used on the JupyterHub, the files aren't present. What's the difference between these two environments as far as the filesystem inside the container?

**Comment by zaneselvans** [comment]
I was getting some "cannot determine build status without nodejs" warnings while running an image built with `repo2docker` that didn't have node as part of its `environment.yml` and so I added node to the environment, and then when I started up the notebook server and went to try running some notebooks, it told me that `jupyter-offlinenotebook` needed to be included in the build. I'm still fuzzy as to whether all of the extensions are supposed to get installed directly from their conda packages, or if we should continue to expect to need to do builds.

**Comment by yuvipanda** [comment]
Available in https://github.com/yuvipanda/test-jupyterhub-image-locally now
