### ISSUE TITLE
[Incident] Prometeus is down in pangeo-hubs

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1843]
### Summary

* PageDuty incident: https://2i2c-org.pagerduty.com/incidents/Q0ZH5DBGBCSUNP (it says resolved but @yuvipanda confirmed this one has recurred).
* Dedicated Slack channel: https://app.slack.com/client/TKHFGBRC2/C046PBG348J

### Impact on users

This is not impacting the users, but we have zero visibility into usage on the pangeo-hubs.

### Important information

- Hub URL: us-central1-b.gcp.pangeo.io
- Support ticket ref: No support ticket, AFAIK this one was caught by the uptime check.

### Tasks and updates

- [ ] Discuss and address incident, leaving comments below with updates
- [ ] Incident has been dealt with or is over
- [ ] Copy/paste the after-action report below and fill in relevant sections
- [ ] Incident title is discoverable and accurate
- [ ] All actionable items in report have linked GitHub Issues

<details>
<summary>After-action report template</summary>

```
# After-action report

These sections should be filled out once we've resolved the incident and know what happened.
They should focus on the knowledge we've gained and any improvements we should take.

## Timeline

_A short list of dates / times and major updates, with links to relevant comments in the issue for more context._

All times in {{ most convenient timezone}}.

- {{ yyyy-mm-dd }} - [Summary of first update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of another update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of final update](link to comment)


## What went wrong

_Things that could have gone better. Ideally these should result in concrete
action items that have GitHub issues created for them and linked to under
Action items._

- Thing one
- Thing two

## Where we got lucky

_These are good things that happened to us but not because we had planned for them._

- Thing one
- Thing two

## Follow-up actions

_Every action item should have a GitHub issue (even a small skeleton of one) attached to it, so these do not get forgotten. These issues don't have to be in `infrastructure/`, they can be in other repositories._

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]
```

</details>

**Comment by damianavila** [comment]
Some notes from @yuvipanda's investigation in Slack:

Stage 1:

* It's been dead for months at least, readiness probe fails and restarts server pod
* Deleted /data/wal and restarted pod, to see if that helps
  * WAL is Write Ahead Log, and is used to recover from crashes.
  * Clearly it isn't helping us here.
* That worked!
  * We still have missing data for a lot of time but the prometheus server should be back up now
* Ok so I think this meant we ran into some kinda bug in prometheus that is triggered on WAL recovery in some cases that caused it to restart. 
  * I ran kubectl top pod -n support and found memory usage is well under the 2G limit, so the problem isn't it running out of RAM.
 
Stage 2:
* This recurred again.
* I deleted the deployment and redeployed to see if it was a mixup in the readiness rules?
  * Well that didn't help.
* So I,m going to just kill the disk by: 
  * 1. editing the PV to set reclaim policy to 'retain' (so raw data is preserved) and 
  * 2. deleting the pvc, 
  * 3. deleting the pod so the pvc is released, 
  * 4. redeploying to get a fresh disk

@yuvipanda can you confirm if you followed the steps outlined in the last item? It is not clear to me from the description in Slack. Also, feel free to edit anything I have written here if I am not capturing things properly.

What would be the next steps here? In terms of prioritization, I think this is a high prio, but not a critical thing... at least not for now. Thoughts?

**Comment by damianavila** [comment]
Comment from @yuvipanda in Slack:

> I was wondering if this was just the disk getting full, so resized it to 200G. IT wasn't that :disappointed:
> /dev/sdb                196.4G      2.9G    193.4G   1% /data

**Comment by yuvipanda** [comment]
@damianavila more detailed fix in https://github.com/2i2c-org/infrastructure/pull/1906
