### ISSUE TITLE
Document pre-pulling user images on a node

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1854]
### Context

There is one more "warm up", optimization step that we could take for events besides spinning up up a number of nodes to be able to be used, i.e. pulling user images on the nodes that we spin, so that users don't wait for that to get downloaded.

More about this option inside the z2jh docs at https://z2jh.jupyter.org/en/latest/administrator/optimization.html#pulling-images-before-users-arrive

### Proposal

We already have this enabled for a few hubs https://github.com/2i2c-org/infrastructure/search?q=prepuller

We should document this step to take before an event and document how to do it.
Example: https://github.com/2i2c-org/infrastructure/pull/1839

**Comment by GeorgianaElena** [comment]
I am inclined to close this issue in favor of  https://github.com/2i2c-org/infrastructure/issues/2541 and https://github.com/2i2c-org/infrastructure/issues/2344 as they same to be more specific. @consideRatio, what do you think? Also, should we nominate them for this quarter's work?

**Comment by consideRatio** [comment]
I agree on the close here.

I'd like us to stabilize practices related to node sharing before thinking about pre pulling, but at the same time we already think a lot about pre pulling for historical reasons. I consider pre pulling a quite fragile and circumstance specific optimization that rarely is relevant for us.

I nominated #2344 seeing it as more foundational than #2541
