### ISSUE TITLE
Document our logging setup

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1890]
(child of https://github.com/2i2c-org/infrastructure/issues/1167)

Logging is *the most* important part of debugging outages, and we need a lot more documentation for that. Here's an outline

- [ ] Looking at 'live' logs (currently running components) #1869 helps with this a little, but needs more docs
- [ ] Where logs are stored *longer term* if at all
   - [ ] GCP (Stackdriver)
   - [ ] AWS (Cloudwatch - is this even set up?)
   - [ ] Azure ???
- [ ] Common things you might find in various logs
   - [ ] 5xx errors during login or server start? hub logs!
   - [ ] Errors about scaling? Autoscaler logs!
   - [ ] Dask errors? dask controller, api, traefik logs

**Comment by damianavila** [comment]
Some sort of cloud-agnostic logging aggregator would be lovely to see in our infra, IMHO.
