### ISSUE TITLE
Allow a new member access to the leap grafana

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1896]
### Context

Access for a new user was requested in https://2i2c.freshdesk.com/a/tickets/261 to the leap cluster grafana.
Currently this grafana, has GitHub authentication enabled, but it authorizes users based on their `2i2c-org` membership.

### Proposal

Prioritize taking a decision about **https://github.com/2i2c-org/infrastructure/issues/1850**

**Comment by jbusecke** [comment]
Hi. I am suspect that this was a ticket raised by my recent email? FYI, I have submitted a [PR](https://github.com/jbusecke/infrastructure/pull/1). Just wanted to mention that here.

**Comment by yuvipanda** [comment]
I responded to your email, @jbusecke!
