### ISSUE TITLE
Create a dask gateway dashboard link that respects named servers

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1912]
### Context

ref: https://2i2c.freshdesk.com/a/tickets/274

> Normally when I start a Local Cluster with:
> ```
> from dask.distributed import Client
> client = Client()
> client
> ```
> I get a link like this: https://leap.2i2c.cloud/user/jbusecke/proxy/8787/status
> 
> This works perfectly if I am on the default server, but if I am on a named server (in this case `test`) I have to modify the link to 
> 
> https://leap.2i2c.cloud/user/jbusecke/test/proxy/8787/status

**Comment by yuvipanda** [comment]
Here's the problematic config, along with a comment about how it doesn't actually work for named servers :) https://github.com/2i2c-org/infrastructure/blob/e351ddd68894a45f778caae7278fb1720056156d/helm-charts/daskhub/values.yaml#L52

We need to find the appropriate hub substitution to use there.

**Comment by yuvipanda** [comment]
Should be fixed by https://github.com/2i2c-org/infrastructure/pull/1920

**Comment by jbusecke** [comment]
Just tested this on the leap hub and can confirm it works. Thanks for the quick fix.
