### ISSUE TITLE
[Incident] LIS hub cannot start user servers

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1915]
### Important information

- Hub URL: https://ds.lis.2i2c.cloud
- Support ticket ref: https://2i2c.freshdesk.com/a/tickets/277

### Tasks and updates

- [ ] Discuss and address incident, leaving comments below with updates
- [ ] Incident has been dealt with or is over
- [ ] Copy/paste the after-action report below and fill in relevant sections
- [ ] Incident title is discoverable and accurate
- [ ] All actionable items in report have linked GitHub Issues

<details>
<summary>After-action report template</summary>

```
# After-action report

These sections should be filled out once we've resolved the incident and know what happened.
They should focus on the knowledge we've gained and any improvements we should take.

## Timeline

_A short list of dates / times and major updates, with links to relevant comments in the issue for more context._

All times in {{ most convenient timezone}}.

- {{ yyyy-mm-dd }} - [Summary of first update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of another update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of final update](link to comment)


## What went wrong

_Things that could have gone better. Ideally these should result in concrete
action items that have GitHub issues created for them and linked to under
Action items._

- Thing one
- Thing two

## Where we got lucky

_These are good things that happened to us but not because we had planned for them._

- Thing one
- Thing two

## Follow-up actions

_Every action item should have a GitHub issue (even a small skeleton of one) attached to it, so these do not get forgotten. These issues don't have to be in `infrastructure/`, they can be in other repositories._

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]
```

</details>

**Comment by sgibson91** [comment]
Matthew reported that the 2i2c-uk cluster wasn't scaling with a "backoff after failed scale-up" message. This usually means a quota problem. I inspected the quotas on the project and saw the Persistent Disk SSD quota was maxed out (500GB), I submitted a request to increase it to 1TB which was accepted but the problem persists. Matthew has some upcoming classes TODAY that he would like to use the hub for.

**Comment by sgibson91** [comment]
I used `deployer exxec-home-shells 2i2c-uk lis` to see if a student had eaten up the SSD. I ran `du -sh *` in the `home/` dir, but there wasn't anything suspicious looking, and the total size of that dir was 13GB so I don't think that's the problem.

**Comment by sgibson91** [comment]
<img width="1629" alt="Screenshot 2022-11-14 at 13 51 34" src="https://user-images.githubusercontent.com/44771837/201676976-7a3ebd5a-fac5-4d85-9cbd-2432a4bda4c3.png">

From the console we've got one pvc with 100GB on it

**Comment by sgibson91** [comment]
I've discovered this PVC is attached to the prometheus server

```
k get pvc
NAME                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
...
support-prometheus-server   Bound    pvc-72a496d7-0b5c-4d5e-90d8-73451c81a15d   100Gi      RWO            standard       52d
```

**Comment by sgibson91** [comment]
Is this a WAL problem?

**Comment by matthew-brett** [comment]
Do you think there's any reasonable hope of this running in the next 30 minutes or so?  Otherwise we will have to scramble somehow.

**Comment by sgibson91** [comment]
No I don't think so. PagerDuty has been pinging Yuvi since I opened the incident, but it's very early in the AM for him. We tracked some complaints from the configurator, and I just cleared the setting there, but don't know if that will help or not

**Comment by sgibson91** [comment]
We have also found a `ZONE_RESOURCE_POOL_EXHAUSTED` error which is apparently GCP's "out of stock" message :(

**Comment by sgibson91** [comment]
Hub is available again.

Here's what we think happened:

- There was an upstream (GCP-based) exhaustion of resources in the `europe-west2-b` zone. The cluster could not scale, because there were no available resources to scale into.
- The cluster was not set up as a zonal cluster, so only respected the zone it was configured to use.
- I hand-edited the nb-user node group in the GCP console, allowing it to create nodes in _all_ zones in the `europe-west2` region. This allowed the cluster to scale up a new node and create user servers

**Comment by matthew-brett** [comment]
Nice - thanks for fixing - and thanks for the explanation.    Would the situation have been different if this had been a regional cluster?

**Comment by yuvipanda** [comment]
This is something I am hoping to document soon as part of https://github.com/2i2c-org/infrastructure/issues/1892.

Our clusters are set to be *regional* masters with nodes in only *one* zone. What does this mean?

1. There is *three* kubernetes masters, one per zone, in the region. This provides a highly available master, so the kubernetes API itself doesn't go down. We need this to spawn users
2. But our *nodes* themselves are only ever in one particular zone. Why? Because we use NFS for our home directory storage (https://cloud.google.com/filestore/docs/regions) and that is unfortunately something that works well only within the same zone the NFS server is in. 

Right now, the NFS server is in the -b zone while the nodes are in -c zone. This would cause performance problems in the medium term, so we'll actually have to either decide that the -b zone is too small and move the filestore to -c, or move the nodes back to -b. 

Ideally, we would be able to say 'bring up our clusters in -b, but if it is full -c is also ok' but unfortunately that isn't an option :(

**Comment by matthew-brett** [comment]
Right - thanks - that's very clear.

**Comment by sgibson91** [comment]
We have published the incident report here: https://github.com/2i2c-org/incident-reports/blob/main/reports/2022-11-14-lis-hub-zone-pool-resource-exhaustion.pdf

**Comment by matthew-brett** [comment]
Just checking - is our cluster still set to create nodes in the other pools?   If so - you predicted that would degrade NFS performance.  Is that the best plan from now?

**Comment by sgibson91** [comment]
Yes, it is still setup that way and #1944 is tracking when to revert that decision, and which zone to constrain to. We also have #1945 to look into an enterprise tier for NFS that would work across zones, but that would increase our base cost.
