### ISSUE TITLE
[Billing] Automatically figure out how much a separate GCP project spends in a month

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1921]
[Yuvi] The **only** real way to automatically figure out how much a **GCP Project** cost is to [export data to BigQuery](https://cloud.google.com/billing/docs/how-to/export-data-bigquery). There is pretty much no other **automatic** way. This fucking sucks, but this is unfortunately the universe we live in. Lots of things suck, and we just have to work around them.

## Output

This issue will track the things we would need to do to write a **script** that when run, can produce a table that lists **all** the projects we have, as well as **how much they cost**, plus  **whom to invoice**. So the output should look a bit like this:

| Month | Billing Account | Project | Invoicing Entity | Cost (in appropriate currency) |
| - | - | - | - | - |
| Nov 2022 | link-to-billing-acct | name-of-gcp-project | name and email of entity to send invoice to | cost |
| Nov 2022 | link-to-billing-acct | name-of-gcp-project | name and email of entity to send invoice to | cost |

### Determine canonical sources of truth for billing information

The entities we have to track are:

- GCP Projects
- Billing accounts attached to them
- Entities that should be billed to these projects

We **must** make sure that each GCP project is mapped to an entity that should be billed for that project. It could be just us, but it needs to be **someone**.

### Enable BigQuery export for each billing account

Every time we create a billing account, we **must** enable [BigQuery export](https://cloud.google.com/billing/docs/how-to/export-data-bigquery) for that account. Unfortunately this must exist in a project inside the billing account, so we have to choose that. I think this will actually be **difficult to automate**, so at least for this quarter's goal, we should not try to do that.

### Write BigQuery queries to sum monthly total cost for a project

We don't usually care about breakdowns in the project, we just need a total cost. Need a bigquery script that will just output sum of cost for a given billing period (month?). Stackoverflow should have examples

### BigQuery billing enabling

- [ ] Add documentation to our 'create new GCP billing account' docs to also enable BigQuery Billing export
- [ ] Enable bigquery billing export for *all* our existing billing accounts

### Source of truth recording

- [ ] Create a new repository (private) that can contain this *source of truth*
- [ ] Add (as YAML) information about the various billing accounts we have

**Comment by yuvipanda** [comment]
I wrote up the description on the issue, got distracted halfway through, and ended up implementing most of it instead :( https://github.com/2i2c-org/infrastructure/pull/1947

**Comment by jmunroe** [comment]
I was part of the motivating conversations on how this data will be used in our billing/invoicing with CS&S.  @pnasrat if there is anything unclear on requirements please let me know.

**Comment by pnasrat** [comment]
@jmunroe thanks I'll pick this up early next week as I'm spending some of my time shadowing support

**Comment by pnasrat** [comment]
Reference of sample BigQuery queries for billing https://cloud.google.com/billing/docs/how-to/export-data-bigquery-tables/detailed-usage#detailed_usage_cost_query_examples

**Comment by pnasrat** [comment]
Updating to reflect @yuvipanda working on dedicated GCP cluster case
