### ISSUE TITLE
[Billing] Automatically figure out how much a shared GCP cluster spends in a month (and map those costs to inner hubs)

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1923]
## Context

Shared hubs have both a shared infrastructure component (kubernetes, prometheus, etc) and utilization of the hub, notebooks, dask-workers, etc.

Automate the manual process done up until March 2023. 

## Formula

Given a shared cluster in GCP (currently two-eye-two-see project) for each hub calculate monthly utilization (RAM model).
Calculate total RAM and Utilization proportion of each naamespace (shared utiliztaion) 
Calculate support cost from  kube-system + support cost 
For each hub Cost = Utilization proportion times total cost plus (Utilization proportion times total support cost)

**Comment by pnasrat** [comment]
Notes

```prometheus
avg(
		label_replace(
			label_replace(
				avg(
					count_over_time(kube_pod_container_resource_requests{resource="memory", unit="byte", container!="",container!="POD", node!=""}[$__interval])
					*
					avg_over_time(kube_pod_container_resource_requests{resource="memory", unit="byte", container!="",container!="POD", node!=""}[$__interval])
				) by (namespace,container,pod,node) , "container_name","$1","container","(.+)"
			), "pod_name","$1","pod","(.+)"
		)
	) by (namespace)
```

https://grafana.pilot.2i2c.cloud/goto/SrIMEnBVk?orgId=1

**Comment by pnasrat** [comment]
Timeselector 90d

```
sum by (namespace) (max_over_time(kube_pod_container_resource_requests{resource="memory",unit="byte",container!="",container!="POD", node!=""}[$__interval]))
```

Step 1d

https://grafana.pilot.2i2c.cloud/goto/rtyVU7fVz?orgId=1

**Comment by pnasrat** [comment]
Opencost worked and was able to generate shared cluster breakdown however it's not calculating all the costs. It might not handle all our initial needs and there might be some bugs in it to fix.  

I've redeployed support from master to clean up for the weekend

```
kubectl get service -n support
NAME                                         TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                      AGE
support-grafana                              ClusterIP      10.3.250.43    <none>          80/TCP                       654d
support-ingress-nginx-controller             LoadBalancer   10.3.246.74    35.223.43.171   80:30226/TCP,443:30605/TCP   654d
support-ingress-nginx-controller-admission   ClusterIP      10.3.240.103   <none>          443/TCP                      654d
support-kube-state-metrics                   ClusterIP      10.3.255.6     <none>          8080/TCP                     654d
support-prometheus-node-exporter             ClusterIP      10.3.243.46    <none>          9100/TCP                     268d
support-prometheus-server                    ClusterIP      10.3.254.186   <none>          80/TCP                       654d
```

**Comment by pnasrat** [comment]
Given the pricing inconsitencies with opencost I'm going to switch next to a timebox investigation of cluster usage metering for GCP using GKE usage metering feature joined with the detailed cloud stats. That will hopefully be more accurate than prometheus but we can fall back to that. 

https://blog.searce.com/visualize-google-kubernetes-engine-usage-and-cost-metrics-using-google-data-studio-97e79ce9e2f4

https://www.cloudskillsboost.google/focuses/7114?parent=catalog

https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-usage-metering#console

https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-usage-metering?&_ga=2.44889252.-1474538276.1677878796#view_in_data-studio

Also https://cloud.google.com/community/tutorials/writing-prometheus-metrics-bigquery

**Comment by pnasrat** [comment]
The GKE resource usage accumulated over the weekend and simple queries work.

```sql
SELECT
  cluster_name,
  labels,
  usage
FROM
  two-eye-two-see.2i2c_shared_cluster_costs.gke_cluster_resource_usage
WHERE
  namespace="staging"
```

**Comment by pnasrat** [comment]
```SQL
SELECT
  DATE(start_time) as date,
  resource_usage.cluster_name,
  resource_usage.cluster_location,
  resource_usage.namespace,
  resource_usage.resource_name,
  resource_usage.sku_id,
  gcp_billing_export.sku_description,
  SUM(resource_usage.usage.amount) AS usage,
  resource_usage.usage.unit AS usage_unit,
  SUM(resource_usage.usage.amount * gcp_billing_export.rate) AS cost_estimate,
  gcp_billing_export.currency
FROM
  two-eye-two-see.2i2c_shared_cluster_costs.gke_cluster_resource_usage AS resource_usage

-- select only workloads matching the defined "drilldown_label"
---  CROSS JOIN UNNEST(labels) AS label ON label.key=drilldown_label

-- join with billing table to get pricing information and sku description
  LEFT JOIN (
  SELECT
    DATE(usage_start_time) as date,
    sku.id AS sku_id,
    sku.description AS sku_description,
    SAFE_DIVIDE(SUM(cost), SUM(usage.amount)) AS rate,
    currency
  FROM
    two-eye-two-see.cloud_costs.gcp_billing_export_v1_011901_F8160A_68DED7
  WHERE
    project.id = "two-eye-two-see"
  GROUP BY
    date,
    sku_id,
    sku_description,
    currency) AS gcp_billing_export
  ON DATE(resource_usage.start_time) = gcp_billing_export.date AND resource_usage.sku_id = gcp_billing_export.sku_id

GROUP BY
  date,
  cluster_name,
  cluster_location,
  namespace,
  resource_name,
  sku_id,
  sku_description,
  usage_unit,
  currency

ORDER BY
  date,
  cluster_name,
  cluster_location,
  namespace,
  resource_name
```

**Comment by pnasrat** [comment]
From prometheus we can quesry programatically to do calendar month - what I think we need to do to match the existing grafana step approach is to

Query at the end of month
Set the duration to be the length of month in days, with a step of 1d
Sum the max over time by namespace

I need to check my understanding of how prometheus is handling this 

```
sum(max_over_time(
        kube_pod_container_resource_requests{resource="memory"}[28d:1d] @1677646800.0
    )) by (namespace)
```

Some further hints https://www.robustperception.io/monthly-reporting-with-prometheus-and-python/

**Comment by pnasrat** [comment]
So to get the bytes ratio we might want to do something like the following 

https://grafana.pilot.2i2c.cloud/goto/jlON7SL4k?orgId=1

```
sum(max_over_time(kube_pod_container_resource_requests{resource="memory"}[$__interval:24h])) by (namespace) / 
ignoring (namespace) group_left 
sum( machine_memory_bytes{}) 
```

**Comment by pnasrat** [comment]
The code to do this is now commited and has been used for Q2 billing.
