### ISSUE TITLE
Investigate enterprise plan for regional NFS

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1945]
### Context

> Our clusters are set to be regional masters with nodes in only one zone. What does this mean?
> 
> There is three kubernetes masters, one per zone, in the region. This provides a highly available master, so the kubernetes API itself doesn't go down. We need this to spawn users
But our nodes themselves are only ever in one particular zone. Why? Because we use NFS for our home directory storage ([cloud.google.com/filestore/docs/regions](https://cloud.google.com/filestore/docs/regions)) and that is unfortunately something that works well only within the same zone the NFS server is in.
Right now, the NFS server is in the -b zone while the nodes are in -c zone. This would cause performance problems in the medium term, so we'll actually have to either decide that the -b zone is too small and move the filestore to -c, or move the nodes back to -b.
> 
> Ideally, we would be able to say 'bring up our clusters in -b, but if it is full -c is also ok' but unfortunately that isn't an option
-- https://github.com/2i2c-org/infrastructure/issues/1915#issuecomment-1314143457

Another way to tackle this is to use regional NFs, but this would require and enterprise plan and increase our base cost. https://cloud.google.com/filestore/docs/service-tiers#enterprise_tier

**Comment by yuvipanda** [comment]
I don't think we are currently planning on doing this, let's close this out.
