### ISSUE TITLE
Openscapes hub image update

### ISSUE THREAD

**Issue by betolink** [2i2c-org/infrastructure#1986]
### Context

At Openscapes we're using different Docker images to support R, Python and Matlab users, I thought there was a github action somewhere at 2i2c to detect when a new image has been pushed and opens a PR to update the [hub config](https://github.com/2i2c-org/infrastructure/blob/master/config/clusters/openscapes/common.values.yaml)

We have a new image for Python `openscapes/python:11de2c5` and we want to test it on staging (staging.openscapes.2i2c.cloud/) is it possible without deploying it to prod? 

Is there a way to streamline these updates to the hub config? is the bot/github action only configured for the Python image? Thanks!

**Comment by sgibson91** [comment]
Hi @betolink You can use the configurator to test the image on staging without affecting prod. Docs are here: https://docs.2i2c.org/en/latest/admin/howto/configurator.html This is probably the quickest way for you to manage your image (it work on both staging and prod)

Using the configurator in this way does not update hub config, though it will always override what is listed in the hub config. Some folk find this confusing and we need to find some dev cycles to put into improving it I think 😕 

https://github.com/2i2c-org/infrastructure/blob/b6ad29f7ee3662cf821dd4b5be2877b4b9c6faf0/.github/workflows/bump-image-tags.yaml#L35-L39

This is how the action is configured to auto-bump your images, and they are looking at all three images. This action only runs _weekly on Monday_ though, it is not triggered by pushing a tag to a Docker repository.

I think eventually, we would like to auto-populate a list of tags from a image repo, but that work is still ongoing https://github.com/2i2c-org/infrastructure/issues/1253

**Comment by sgibson91** [comment]
Also, these kinds of questions are really good to send to support@2i2c.org rather than opening an issue :)

**Comment by betolink** [comment]
Thanks for the info @sgibson9! Before opening the issue I used the configurator and had no effect on the spawned instance =( 
![Screenshot from 2022-12-09 09-21-25](https://user-images.githubusercontent.com/717735/206734978-329c96de-f927-4fc0-b48a-a6b2f88b83c7.png) I can follow up on the email.

**Comment by sgibson91** [comment]
Oh yes - sorry my bad. The configurator doesn't work for profile list options like you've got. Sorry for the false information on my part 🤦🏻‍♀️
