### ISSUE TITLE
Callysto core nodepool rightsizing

### ISSUE THREAD

**Issue by ianabc** [2i2c-org/infrastructure#2005]
### Context

The callysto hub infrastructure is currently running on a pair of `n1-highmem-4` (GCE) nodes which are relatively expensive, and I was asked to check that these are the right size for the job. Poking around in our grafana stats, it looks like they might be a bit underutilized, would it make sense to resize these to `n1-highmem-2` nodes? I think the [default cluster config uses n1-highmen-2](https://github.com/2i2c-org/infrastructure/blob/333d70d17142ca06c1110228bd31b7ffbcaf5099/terraform/gcp/variables.tf#L121) with the caveat 

> For single-tenant clusters, a single n1-highmem-2 node seems enough - if network policy and config connector are not on.  For others, please experiment to see what fits.

but we override that in our [current terraform config](https://github.com/2i2c-org/infrastructure/blob/333d70d17142ca06c1110228bd31b7ffbcaf5099/terraform/gcp/projects/callysto.tfvars#L21). Are there any reasons for us _not_ to resize to `n1-highmem-2` nodes?

If it is possible for us to do this, do we just propose the change to the terraform config? I guess applying the change would tear down our current cluster and redeploy it; that would be OK, but I would the user data (FileStore volume) be preserved and re-attached?

### Proposal

Explore the possibility of resizing the core node pool of the Callysto cluster. If it is feasible, redeploy.

**Comment by yuvipanda** [comment]
@ianabc we can try it out! However, I am curious if that is enough for the prometheus nodes.

**Comment by ianabc** [comment]
Thanks, I think we might give it a go and see what happens. My understanding is we would make the update in terraform and then issue a PR, but I'm a little fuzzy on what will happen when we merge the PR. I think it has to destroy the existing code nodepool and create a new one, but can you confirm that it would leave the user storage intact? i.e. when it adds the new core nodepool and spins things up would existing users see their existing files? Or should we arrange to have them backed up somewhere then reimported?
