### ISSUE TITLE
A way to merge and not trigger CD pipeline

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2009]
- I figured I'd hit merge on https://github.com/2i2c-org/infrastructure/pull/2008, but its not motivating a full redeploy so I'd like to opt out. For example by setting a label on the PR before merge.

1. Is there agreement its worth adding complexity to the CI system to support that kind of feature?

**Comment by yuvipanda** [comment]
IMO, for that PR, we *should* actually do a full redeploy because it might change the version of helm installed and cause issues.

**Comment by consideRatio** [comment]
I think we would only test if they have or havn't introduced a bug in the action itself by running the entire CD pipeline for this PR.

```diff
-    - uses: azure/setup-helm@v3.4
+    - uses: azure/setup-helm@v3.5
       with:
         # version is pinned for helm to avoid an automatic update of its version
         # which would cause something unexpected without an action on our
         # behalf.
         version: v3.8.2
```

But still then, there are situations where it can make sense to not run the CD pipeline by manual intent in my mind. So, should a feature like this be reasonable to support?

Example: you have 4 dependabot PRs updating actions/setup-python, actions/checkout, etc. You could merge them and trigger redeploys x4, or you can merge three with a label to not trigger a redeploy, and then the fourth with a label to trigger a redeploy.

**Comment by yuvipanda** [comment]
> Example: you have 4 dependabot PRs updating actions/setup-python, actions/checkout, etc. You could merge them and trigger redeploys x4, or you can merge three with a label to not trigger a redeploy, and then the fourth with a label to trigger a redeploy.

I would say in this case it makes sense, but only if we make sure that CI is not skipped completely - some human makes a choice on which one to not skip CI on, and if things break, figures out which one to rollback.

The basic thing I want to avoid is if we skip CI, then it breaks the next time someone does a deploy. Generally `noop` helm deploys are fairly quick and do not bounce anything, so my personal preference is to always just let it deploy :)

**Comment by consideRatio** [comment]
A reason to not trigger re-deploy from the docs of decomissioning a hub.

>## 2. Remove the hub values file
>
>Without removing the values file from the repository first, the hub could be redeployed by any merged PR that triggers our CI/CD pipeline.

**Comment by consideRatio** [comment]
Here is perhaps the prime candidate situation for wanting a CI Skip. If this is merged, we will make a full re-deploy of everything. With the health checks we make, it likeley also even triggers server startups in users hub, incurring costs for them.

https://github.com/2i2c-org/infrastructure/pull/2133

**Comment by yuvipanda** [comment]
IMO, #2133 should trigger a redeploy so we know the sops change actually worked!

Can you also help me understand https://github.com/2i2c-org/infrastructure/issues/2009#issuecomment-1400397503? Would we expect *all other PRs* merged in the meantime to skip CI?

**Comment by consideRatio** [comment]
It seems like we are a stuck with a difference of opinion, and we seem to be locked in. I think there should be room for a informed choice to override the decision to deploy to all hubs. It can help in various situations, and I'd like to be trusted to make judgement calls about this.

> Can you also help me understand https://github.com/2i2c-org/infrastructure/issues/2009#issuecomment-1400397503? Would we expect all other PRs merged in the meantime to skip CI?

It was an unclear example by me, this was [the related docs](https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/hubs/other-hub-ops/delete-hub.html?highlight=decomissioning#remove-the-hub-values-file).

The gist was that I found myself in a situation where I wanted to make an informed opt-out of CD for another PR, but couldn't.

Let's not overthink this, if you don't want us to be able to opt-out, lets not!

**Comment by yuvipanda** [comment]
>  I'd like to be trusted to make judgement calls about this.

First, I'm sorry if I came across as as not trusting your judgement about skipping CI. That was not my intention at all, and I'll evaluate and keep that in mind in future communication so my words match my intent better.

I personally think we should never skip CI, but if you feel otherwise I would not block a mechanism + clear guidelines on when it is appropriate to skip CI!

**Comment by damianavila** [comment]
After thinking about this a little bit more, even when opt-out seems tempting for some cases, I am leaning toward @yuvipanda's position here even if we pay an additional price for that.

**Comment by consideRatio** [comment]
I remain in disagreement about this being a strong believer that we should be allowed to opt out. Its a price paid by more than us and our time, its a price paid by end users cloud bills.

I believe for example that we may trigger scale up of large nodes sometimes if we run the hub health check -  depends.

The price is notable in our time and attention, and is a price for communities as well.

Right now here because i'm approving a PR id opt-out on myself - see #2285.

**Comment by pnasrat** [comment]
@consideRatio if the concern is that health check triggers large nodes, then I'd argue that's somethign to fix with the health check to make it more lightweight end to end check, or refine the deployer flow for `discover_modified_common_files`  to not just checking any deployer/* has changed. 

Opting out means that a different SRE might end up  deploying the opted out changes which also adds an element of suprise if something unexpected goes wrong.

If we are using CI/CD I think opting out should be an exceptional case where say github actions are failing and a manual deploy is needed to preserve git as the source of truth for production

**Comment by damianavila** [comment]
> refine the deployer flow for discover_modified_common_files to not just checking any deployer/* has changed.

I feel that is a good compromise... actually, wondering if we should reopen: https://github.com/2i2c-org/infrastructure/issues/970#issuecomment-1453713374 (see @sgibson91's latest comment).

But, in general, I agree with @pnasrat and @yuvipanda's sentiments here...

**Comment by consideRatio** [comment]
Here is perhaps one of the more concrete situations when I think it would have been great to have an ability to label a PR as a PR that shouldn't trigger the deployment of all hubs even though it touched a certain file.

I've done chore maintenance now during the weekend and is continuing with it until people wake up USA. I've changed machine types in node pools and such, which is a change that couples to the profile list configuration of jupyterhub running inside k8s. After I made the machine upgrade, I had to make the profileList update. This is done and I've opened a few PRs for review (#2337, #2340).

Now I know there is also a PR like #2331 open. This PR doesn't need to redeploy all clusters' hubs, it just needs to run the ensure-uptime-checks workflow. But now, its planned to do so when merged. If it is, and all hubs are redeployed using the main branchs state - it would break `nasa-veda` and `leap` as they would get the old reference to the previous machine types.

If I could label existing PRs that doesn't need to redeploy all clusters' hubs to not do so, I wouldn't have to worry about this situation, but now I do. I've written this comment to motivate this feature further, and I've commented a warning about the situation in https://github.com/2i2c-org/infrastructure/pull/2331#pullrequestreview-1336108146.

---

@damianavila I'd like to escalate this conversation to a better medium where we can more easily hear each other. Do you think its okay to add this to the Product and Engineering meeting's agenda?

**Comment by pnasrat** [comment]
@damianavila @consideRatio discussing this sync seems reasonable. I'd also suggest that we take a step back to think about the desired workflow for deployment vs working around CI/CD and the problems we are trying to solve. There are clearly some tactical things we can do re skipping or merging with To Be Reviewed (see link below) however I want to ensure we have a shared understanindg of the problems

There seem to be multiple elements here:

- Changes that un-needed trigger a deploy
- Complex changes that require staging an infrastructure/provisioning change and a later config update that deployer doesn't handle for us so are being rolled out manually - eg the node pool changing above.
- Reviews for infrastructure changes done out of hours (note I've used something similar to https://github.com/tailscale/ToBeReviewedBot in the past but 

I'd also suggest we discuss what the values/principles of CI/CD we aim for would be. One example of this might be:

- Git always should reflect production configuration (other than when the deployment it is happening (this may also be important for compliance for some communities)

**Comment by consideRatio** [comment]
I'm going through all my opened issues and look to find actionable path forward or close them.

> I'd like to escalate this conversation to a better medium where we can more easily hear each other. Do you think its okay to add this to the Product and Engineering meeting's agenda?

We no longer have a regular sync meeting where this could be one item to discuss, and it seems too cumbersome for everyone if I'd request a dedicated meeting for it with all engineers.

I'll close this and settle on manually cancelling triggered workflow runs when I think its the right decision.

**Comment by consideRatio** [comment]
Since we have automation in #gha-failures, the process to manually cancel a deploy now becomes:
- merge PR
- quickly cancel started job
- write in gha-failures that its manually cancelled and not something to worry about

Past discussion related to avoiding needing this in the first place, but I don't think its feasible. We can of course live without this, but its a regularly occurring "paper cut" for me to not have this.

**Comment by yuvipanda** [comment]
fwiw, I continue to believe one should never skip CI. I discovered in https://2i2c.slack.com/archives/C055A1J1DRP/p1716337516500199 that CI was broken for a bunch of hubs about 9 days after it was broken, and I discovered (and fixed this) only because I don't skip CI. I understand @consideRatio that you want to skip some for your own deploys, and I respect that and you can do so as you desire. But I'd generally continue to recommend to other engineers to not skip CI, and debug issues as they come across. @GeorgianaElena did that in https://2i2c.slack.com/archives/C04994X0BPC/p1716293361972159, which helped me notice what was wrong, and that was only because she didn't skip CI. If she had, we may have found this out only when the next time those hubs were touched, which may have been months down the line (and maybe during an emergency). In line with my other comments in this issue, I don't think we should skip CI as a general team practice.
