### ISSUE TITLE
Reflect over the current's `deployer`s package design

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#2024]
### Context

In https://github.com/2i2c-org/infrastructure/pull/1938 @sgibson91 correctly pointed out the naming of the files and possible their location in `deployer/grafana` and `deployer/generate` might need more thought put into it.

### Proposal

Reflect over the design of:
- `deployer/grafana`
- `deployer/generate`
- `deployer/utils.py`

**Comment by sgibson91** [comment]
Copying my comment across for context:

> I have a small wondering on file naming. For example, now that we have a grafana subfolder, I would say that grafana/utils.py and grafana/manage_tokens.py would reduce redundancy compared to grafana/grafana_utils.py and grafana/grafana_tokens.py etc, particularly when importing, i.e. from grafana import utils versus from grafana import grafana_utils. In the utils-specific case we'd need to avoid naming clashes with the top-level utils though. Which indicates to me either (i) we are overusing utils and should be more creative in our filenaming, or (ii) I am overthinking package design :D
