### ISSUE TITLE
[Decommission Hub] binder-staging

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#2026]
### Summary

We had a crypto-mining incident on this hub ages ago. I attempted to lock it up with CILogon [in this PR](https://github.com/2i2c-org/infrastructure/pull/1579/) but was unsuccessful. And I've just spent the last bit of time trying with GitHub OAuth instead, but I just can't get it to work. My suspicion is that the docs [here](https://binderhub.readthedocs.io/en/latest/authentication.html) are outdated because I don't think the `jupyterhub.auth` key exists anymore...

Anyway, in the spirit of cleaning up, I propose we just get rid of this hub now.

#### Phase II - Hub Removal
(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/en/latest/howto/hubs/delete-hub.html.)

- [ ] Manage existing data (migrate data from the hub or delete it)
- [ ] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [ ] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [ ] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [ ] Delete the hub's authentication application on auth0, GitHub or CILogon
- [ ] Also cleanup the deploy-hubs workflow file as I think there's some commented out code related to special-casing binder-staging in there too

**Comment by yuvipanda** [comment]
I'd love for us to instead fixup the instructions - even if we don't run the pangeo binder from here, I think we will run other ones.

**Comment by GeorgianaElena** [comment]
> I'd love for us to instead fixup the instructions - even if we don't run the pangeo binder from here

Opened https://github.com/jupyterhub/binderhub/pull/1646 to update binderhub auth instructions to match the working config in https://github.com/2i2c-org/infrastructure/pull/2393.

> even if we don't run the pangeo binder from here, I think we will run other ones.

Wondering if this is still true or if we should decommission it instead?

**Comment by yuvipanda** [comment]
I still think it is worth it. And thank you for fixing that, @GeorgianaElena!

**Comment by damianavila** [comment]
Given the authentication piece is fixed by @GeorgianaElena, I think there is value in keeping it alive since we are most likely deploying binder instances in the future. So, I am gonna close this one for now.
