### ISSUE TITLE
Rethink the new hub deployment request/provide information

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#2042]
### Context

We currently have two issue templates that should facilitate
- gathering information about a new hub deploying
- presenting the information to the engineer team

But in reality, they are not serving their purpose. For example, the `request information` template has never been used event when not enough information was available about a new hub to request a deployment.
I believe this is because:

- we don't want to be tasking the community representatives with opening an issue themselves
- opening two issues about the same new hub is generating work that's not necessary
- other?

### Proposal

I propose we remove the `request information` issue template and instead replace it with a bot that comments to an incomplete request deployment issue with a message that asks for the missing info and tags both the community rep and the person opening the issue.
(Maybe we can also make it work as a reminder too and ask every week until the top line comment is filled in or something like this?)

### Updates and actions

- remove the `request information` issue template
- create the bot to comment to the `request deployment` issue for any missing info

**Comment by damianavila** [comment]
I agree with the proposal, the two forms are confusing for everyone, I think.
Simplification with just one form and assistance with a bot to remind us to get the info seems like a plausible and interesting next step.
