### ISSUE TITLE
[Duplicated] Feature idea - help customers get read access to their relevant grafana dashboards

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2050]
@scottyhq asked [in a support ticket](https://2i2c.freshdesk.com/a/tickets/158) about providing access to a grafana:

> Is it easy to give hub admins access to grafana https://grafana.uwhackweeks.2i2c.cloud/login ? 

Thinking about this in the most general case where we can have different ways for users to authenticate themselves, I see some options.

For customers with dedicated clusters:
1. We configure one additional user besides the `admin` user and the user created to update the grafana dashboards, and let that user have just read access to the instance. Then, we share those credentials with the community representatives to handle as they please.
2. We let Grafana work against the production JupyterHub as an identity provider

For customers with shared clusters:
0. First of all, I'm really not sure here because we have a shared grafana instance accessing several different data sources and providing a bit more dashboards etc.
1. I think maybe its reasonable to configure one additional user per hub, and a set of permissions for that user to have readonly access to the relevant prometheus data source.
2. I don't think its reasonable to setup auth against all of the jupyterhub's and even if we do, the permissions granted should depend on what hub you authed against etc.

### Investigative work needed

1. Can we via REST API and/or configuration add a user to Grafana? I think yes, because I think @GeorgianaElena has done that already.
2. Can we via REST API and/or configuration make a user be granted permissions to a specific data source, so that a dropdown list will only include the datasources that the user has permissions to? Below is an example of a dropdownlist.
   ![image](https://user-images.githubusercontent.com/3837114/212322821-9dc4d105-4792-4010-b91a-c816cbc8de0d.png)

**Comment by sgibson91** [comment]
I think there are a few related, possibly duplicate?, issues:

- https://github.com/2i2c-org/infrastructure/issues/1850
- https://github.com/2i2c-org/infrastructure/issues/1827
- https://github.com/2i2c-org/infrastructure/issues/1570

**Comment by damianavila** [comment]
Yes, I think this conversation is already captured in other issues, so let's close this one. Feel free to reopen if you disagree.
