### ISSUE TITLE
Allow configuration of the scheduler's memory limit etc

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2051]
I think its possible to configure dask-gateway client/server to have the dask-gateway client provide a UI for the user to configure the started cluster's scheduler's memory requests/limit.

Based on experience, this can need to be very very large, and with modern `distributed` versions, it can be less. Still, it should support something other than the fixed 4GB. Due to that we should support allowing users to specify such settings themselves.

- I've opened an issue in dask-gateway about documenting an example on how to configure dask-gateway client/server to allow for this: https://github.com/dask/dask-gateway/issues/675

Following that, we should also provide something like that here for our daskhubs.

/cc: @jbusecke who is interested in this.

**Comment by yuvipanda** [comment]
I think this is superseeded by https://github.com/2i2c-org/infrastructure/issues/2564, as just having 1 profile should just be the default.

**Comment by jbusecke** [comment]
I am not quite sure I see this addressed in #2564? If I understood correctly this issue was referring to changes end users could make via dask-gateway (e.g. in the notebook itself?). 
Might have also misread this though.
