### ISSUE TITLE
Use a wiki to keep running notes about specific clusters to help with the support process

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2065]
This has come up before, but we don't really have a single point of reference for various special cases and what not we have on a per-cluster basis. A specific example is that we don't use the configurator for UToronto, because their image is really large and the configurator does not actually support any kinda pre-pulling. So we bump tags in the config here. But this is written down in some note in some old freshdesk ticket, or some slack message somewhere. There's no way for rotating support stewards to know it!

So I opened this page: https://github.com/2i2c-org/infrastructure/wiki/Per-Cluster-Support-Notes. It's a GitHub wiki, that we can edit as we go. I'm hoping we can use a wiki here over doc PRs, as it's much quicker - but more importantly, it can be a lot more *unstructured* than a docs PR. Eventually we may formalize parts of that (for example, 'are we supporting this cluster\'s image building?') and move that to docs. But I wanted to start somewhere.

We can make this private if people feel that is better.

**Comment by yuvipanda** [comment]
I'm not really tied to the wiki specifically, but I wanted to put the little bits of energy i had today towards actually starting something :) I personally think wikis are great for this specifically, as it's to be edited by a specific group of people (folks doing support steward rotations) rather than a more 'anyone can edit!' situation that often ends up with 'nobody is editing'.

**Comment by sgibson91** [comment]
What I like less about wikis, specifically how GitHub wikis work (which is my only experience and I would not argue if someone told me it was the worst way to experience wikis), is that because you can't make a PR, you can't make a comment or indicate in any way that you think part of it is incorrect _but you don't know what the correct thing is/should be_. It basically puts all the pressure on a single person to know something is wrong, what the right thing is, and fix it themselves. It's more difficult to distribute that effort across the team.

I feel confident making a trivial change to a Markdown file, opening a draft PR and saying "hey team, this section doesn't look right. Does anyone have context on what it should be?" I don't know how that works on wikis? Maybe it's because I've experienced poor culture around wikis.

**Comment by yuvipanda** [comment]
Indeed, that is a problem that requires specific cultural norm adoption to solve. The way it is at wikipedia is via 'be bold' - https://en.wikipedia.org/wiki/Wikipedia:Be_bold. To quickly summarize how that would be here, I'd say it would end up with a piece of text like 'I *think this is wrong, but this is what I know: <blah>. Please edit to fix'. This looks messy, but that's ok and expected! My personal experience is that this ends up being overall better than waiting for a review, as often *nobody else also knows what the correct answer is* - this lets us close it out and move on, and revisit it next time. The problem sometimes with 'hey team this does not look right' is that now someone else has to find out what is right before it can be merged, and it just sits in indeterminate state until then. This works ok for documentation I think and external facing things that 'need to be right' - you will not expect to find something in a library's document that says 'I think this is wrong, but here is what:'. But IMO that's perfectly reasonable for wikis! Hence the attempt to use it specifically for this one thing.

**Comment by yuvipanda** [comment]
I added ' If you are unsure about something, still write it down but just say 'I am unsure'' to https://github.com/2i2c-org/infrastructure/wiki/Per-Cluster-Support-Notes.

**Comment by yuvipanda** [comment]
> I feel confident making a trivial change to a Markdown file, opening a draft PR and saying "hey team, this section doesn't look right. Does anyone have context on what it should be?" I don't know how that works on wikis?

To summarize my earlier response, this works by writing down exactly what you have written in the quotes in the wiki directly. Whoever encounters it next can do what they want with that information. This hopefully reduces pressure on the individual to be 'correct', but also reduces pressure on the team to have to resolve things that came up in support that might not need to be resolved until a future time. So instead of it just either laying 'hanging' in a freshdesk ticket until someone finds the time to add it to the docs (which was happening a lot to us I think) or lost in a note there, we move it to this centralized place here.

**Comment by yuvipanda** [comment]
I would also say that things should eventually move into something structured. For example, the question of 'do we maintain an image for this organization or do they?' is a structured question that can have a structured answer. However, creating that structure also takes work, and I think over time things can graduate from here to docs once there is a structured place for that to be answered. For that specific question of who maintains an image, for example, I'd say that should come out as part of the process of contract negotiation and handoff. But figuring out that process itself takes time, and in the meantime I think these bits of info are just floating around in folks' heads. So if it's 'unsure' in our heads, it's 'unsure' in the wiki too.

**Comment by yuvipanda** [comment]
I haven't really been able to get any buy-in for this, and I don't currently have capacity to push this forward. Going to close this.
