### ISSUE TITLE
Add missing .jsonnet file representing a eksctl config for 2i2c-aws-us

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2084]
Looking through all the k8s clusters we manage, 2i2c-aws-us stood out among the AWS EKS based clusters for not having a etsctl/2i2c-aws-us.jsonnet file generated from eksctl/template.jsonnet like the others.

Yuvi suspected it was missing from https://github.com/2i2c-org/infrastructure/pull/2022 by accident.

### Action point

- [ ] Let's create such file to match what we have in the 2i2c-aws-us EKS based cluster
  In practice, we need to know what k8s version, region, zones, and maybe node pools setup etc, then we generate it from the template. Perhaps as the template file was at the time of #2022.

**Comment by sgibson91** [comment]
The original file is in this old PR that got messed up due to some got nonsense and then was missed https://github.com/2i2c-org/infrastructure/pull/1967/files#diff-403908a632cba9bb19d70e72661f0490d1e42b2ded86a847236b61fc98bef538
