### ISSUE TITLE
Verify new jupterhub/grafana-dashboard features (free space and oomkiller)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2098]
Yuvi has done work recently to provide a dashboard of free space in the NFS storage we used for home folders and the `shared` folder.

### Tracking free space in NFS

Because of changes I suggested to in the PR adding a dashboard to jupyterhub/grafana-dashboards:
- https://github.com/jupyterhub/grafana-dashboards/pull/51
we need to make changes to what was added here previously in:
- https://github.com/2i2c-org/infrastructure/pull/1992

Action points:
- [x] Update our metrics collection if needed
- [x] Update grafana dashboards
- [x] Verify function
- [x] Communicate progress to Julius in https://2i2c.freshdesk.com/a/tickets/387

### Tracking out of memory issues

I'm not sure if this new grafana dashboard has been trialed in our hubs, so let's assume it isn't and verify it:
- https://github.com/jupyterhub/grafana-dashboards/pull/52

Action points:
- [ ] Update grafana dashboards
- [ ] Verify function

**Comment by GeorgianaElena** [comment]
@consideRatio, I believe for the "Update grafana dashboard" action point, what needs to happen is to manually run trigger the workflow in 
https://github.com/2i2c-org/infrastructure/blob/master/.github/workflows/deploy-grafana-dashboards.yaml
and make sure all the clusters are listed there. That worflow should know to deploy the latest dashboards in `jupyterhub/grafana-dashboards`

_Note:_ An manually created dashboards (if any?) in the grafanas (in the `JupyterHub Default Dashboards
` dir only I belive) will get wiped.

**Comment by consideRatio** [comment]
In https://2i2c.freshdesk.com/a/tickets/415 we would have wanted this resolved!

**Comment by consideRatio** [comment]
## OOMKills

I've used the command `cat /dev/zero | head -c 10G | tail` to either have the process in the container killed or the container itself killed by a pod eviction.

I've failed to see the OOMKills dashboard populated with data, because as part of the user pod getting evicted/OOMKilled which I figure should register, I see that the support-prometheus-node-exporter pod that should observe it is getting evicted itself by the node which is low on memory. Doh!

So I figure we need some memory requests for the node-exporter part of the support chart.

```
staging       104s        Normal    Created                     pod/jupyter-erik-402i2c-2eorg                          Created container notebook
staging       104s        Normal    Started                     pod/jupyter-erik-402i2c-2eorg                          Started container notebook
staging       104s        Normal    Pulled                      pod/jupyter-erik-402i2c-2eorg                          Container image "quay.io/2i2c/2i2c-hubs-image:69b1f9dff7c7" already present on machine
support       5s          Warning   Failed                      pod/support-cryptnono-58v2k                            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: container init was OOM-killed (memory limit too low?): unknown
support       4s          Warning   BackOff                     pod/support-cryptnono-58v2k                            Back-off restarting failed container
support       3s          Warning   BackOff                     pod/support-prometheus-node-exporter-nxcqs             Back-off restarting failed container
support       2s          Warning   Evicted                     pod/support-prometheus-node-exporter-nxcqs             The node was low on resource: memory.
support       0s          Normal    SuccessfulDelete            daemonset/support-prometheus-node-exporter             Deleted pod: support-prometheus-node-exporter-nxcqs
support       0s          Warning   FailedDaemonPod             daemonset/support-prometheus-node-exporter             Found failed daemon pod support/support-prometheus-node-exporter-nxcqs on node ip-192-168-29-112.ca-central-1.compute.internal, will try to kill it
```

**Comment by yuvipanda** [comment]
That's some super cool testing, @consideRatio! I agree that setting requirements for these support components is a great idea.

I did test them, with some results in https://github.com/jupyterhub/grafana-dashboards/pull/52#issuecomment-1397603086. I tested them by starting a user server, and then basically having a user do something that caused their 'kernel to restart'. It registered as an OOM kill on the node. Process kills based on hitting the container's configured memory limit was what I was primarily interested in, rather than nodes dying based on memory pressure.

**Comment by consideRatio** [comment]
@yuvipanda where did you do the tests? I tested on staging.ubc-eoas.2i2c.cloud - AWS EKS. There I can't do `kubectl top node` for example, so I was thinking maybe you did it on GCP where such commands works and metrics is being collected perhaps a bit differently?

My tests were done with a pod that consumed almost the full capacity of the node, which made k8s observe memory preassure which triggered pod evictions. I guess you ran tests on GCP where for example a user is limited to 1GB perhaps - less than the nodes memory - and that your tests therefore didn't lead to memory preassure on the node itself.

Hmm... But I got a lot of `killed` from within the container as well, similar to what you tested before. And that also wasn't captured in the dashboard so something is up at least on the AWS EKS cluster i tested on.

**Comment by yuvipanda** [comment]
> I guess you ran tests on GCP where for example a user is limited to 1GB perhaps - less than the nodes memory - and that your tests therefore didn't lead to memory preassure on the node itself.

I tested on the openscapes hub, which is EKS. The user was testing code that was using a *lot* of memory, so I suspect it was trying to make one big `malloc` and immediately failing, rather than a number of smaller ones that succeed until memory is full?

I would suggest testing on something with an artificial container memory limit perhaps to see how it goes?

**Comment by consideRatio** [comment]
I've extracted a dedicated issue in #2213 for OOMKiller, closing this!
