### ISSUE TITLE
Ask for m2lines GPU quota increase weekly

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#2099]
### Context

m2lines is pushing the boundaries of machine learning.  Recently, they tried to do an adhoc demo/tutorial and were only able to spin up a small number of GPU enabled Jupyter servers (2?) before running out out of quota.

We requested an increase from GCP in quota and received an allocation of 4 "committed" NVIDIA T4 nodes.  We have been asked to increase the number of available GPUs nodes.  Some possibilities:

- [ ] Request additional quota from GCP
- [ ] Create additional machine types (K80, V100, P100, A100?) so that there is more opportunities for GPU enabled processing
- [ ] Explore running hubs in multiple zones (or regions?) where additional GPU resources may be available

For context, the demo was for a group of 20 users, so a quota of 20 GPUs would be potentially required again in the future. And as machine learning intensive community, an allocation of a 100 GPUs would welcomed (potentially over several different machine types)

While increasing the quota of available GPUs is the primary goal, m2lines also wants to understand the limitations imposed by the cloud vendors.

**Comment by yuvipanda** [comment]
I've asked for another increase from the current 4 to 8.

**Comment by yuvipanda** [comment]
the quota was also approved for 8. I think we just need to ask for it once a week? wtf

**Comment by yuvipanda** [comment]
I see they had hit their CPU quota of 128 as well, so I asked (and was approved) a bump to 128.

I also asked for a GPU bump from 8 to 12, and that was approved

**Comment by yuvipanda** [comment]
I ask for about 4 more GPUs each week, and it gets automatically approved! It is upto 16 now.

1. Go to https://console.cloud.google.com/iam-admin/quotas?project=m2lines-hub&pageState=(%22allQuotasTable%22:(%22f%22:%22%255B%257B_22k_22_3A_22Metric_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22compute.googleapis.com%252Fnvidia_t4_gpus_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22metricName_22%257D%255D%22))
2. Select `NVIDIA T4 GPUs` in `us-central1`
3. Click 'edit quotas' on the top right
4. Ask for a higher number. I've been asking for 4 more, but I think we can get a bit more aggressive.
5. Provide a reason such as "We are working on bringing up a bigger workshop for ML training soon"
6. Provide email (and unfortunately) phone number
7. wait

**Comment by yuvipanda** [comment]
I asked for a bump to 20 and was automatically denied :( At this point I would say this requires engagement with some human on the GCP side

**Comment by yuvipanda** [comment]
I asked for a bump to 20 again, and this time i got it.

**Comment by damianavila** [comment]
Is 20 enough or should we make another iteration? Or involved someone else from GCP to grant us a significantly bigger number as suggested in the top message? cc @jmunroe and @yuvipanda

**Comment by jmunroe** [comment]
With the m2lines hub now winding down, I think this issue is no longer relevant to track.

**Comment by jmunroe** [comment]
I might have closed this just a moment too early:

I note that https://2i2c.freshdesk.com/helpdesk/tickets/769 requesting help with "JupyterHub GPU instances not starting" for LEAP.  Since the user group for m2lines is merging into the LEAP, is there a way to use the GPU quota we have already secured for m2lines but apply it to LEAP?

**Comment by yuvipanda** [comment]
>  is there a way to use the GPU quota we have already secured for m2lines but apply it to LEAP?

Unfortunately there is not.

**Comment by yuvipanda** [comment]
@jmunroe if you think we should do this for LEAP, let's open an issue separately? That issue linked in the support ticket was solved in a different way.
