### ISSUE TITLE
Provide a /home/jovyan/allusers folder for leap

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2105]
In [this support ticket](https://2i2c.freshdesk.com/a/tickets/387?lang=en), I proposed mounting a `allusers` folder like I've seen done in 2i2c-uk's lis hub here to meet the nees described by @jbusecke.

https://github.com/2i2c-org/infrastructure/blob/24154d8e0eb52434148e2ec30dbcbf20f60b5b15/config/clusters/2i2c-uk/lis.values.yaml#L31-L36

### Action points
- [x] Get this done
- [x] Communicate progress to Julius in https://2i2c.freshdesk.com/a/tickets/387
- [x] Check if this should be readonly

**Comment by yuvipanda** [comment]
I've done and communicated this, but also waiting to hear back if this should be readonly.

**Comment by consideRatio** [comment]
It should be readonly, and I've made it so in #2151
