### ISSUE TITLE
Q1 2023 Engineering goals

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#2122]
### Context

We have discussed and agreed on Q1 goals for Engineering in previous meetings: https://docs.google.com/document/d/1dUO2USQlRbcjOEkjlCu1gyTaPBZmGZSRF4L-_9xecmA/edit#

### Proposal

We need to come up with dedicated issues for each goal.
They should be small and concrete (try to avoid unrealistic goals from Q4).

Once we create it, we should add it to the org-wide strategy board.

Assigning this one to myself and @yuvipanda (most likely working on this in the upcoming sprint).

### Updates and actions

Given that we are already in 2/3 of the quarter, it does not make sense to have a dedicated issue for each goal and we should sync our _de facto_ goals with the _intended_ ones. So I posted one message per Q1 goal below (so we can update individually) and added this meta issue to the Org board. Also, updated the title and planning to remove it from the sprint board in the next sprint meeting.

**Comment by damianavila** [comment]
# [Intended but not real] Monitoring and alerting

We agreed on this goal during the planning meeting but, realistically, we did not make progress on the unresolved child issues described in https://github.com/2i2c-org/infrastructure/issues/1804.
See my comment at the bottom: https://github.com/2i2c-org/infrastructure/issues/1804#issuecomment-1446389660.
I think we should refine those remaining issues and pick some of them for our next iteration of this goal (proto-Q2).

**Comment by damianavila** [comment]
# Dynamic image building

@consideRatio has been working on a new iteration of this concept. I foresee more cycles being spent on this goal for the rest of the quarter, and surely in Q2 as well (proto-Q2).

**Comment by damianavila** [comment]
# Deployer enhancements

@GeorgianaElena has been leading this effort and I foresee some continuation of the work for the rest of the quarter.

**Comment by damianavila** [comment]
# [Unintended but real] Improve the support process

We had several discussions in meetings and Slack about improvements to our support process with the aim to reduce stress on our engineers and be more efficient in the management of the support tickets.
My original idea was to attack these problems in Q2 but several issues prompt us to start the discussion earlier than planned.

@pnasrat and @damianavila (with the rest of the team's feedback) have been pushing forward this goal during the last few weeks.

**Comment by choldgraf** [comment]
@damianavila I believe that this process is now complete - we've got follow up issues for most of these and a new quarter we're focusing on. I'll close this as completed but please update if you think it needs more action
