### ISSUE TITLE
Ensure our hub pod's templates-sync containers shut down quickly on SIGTERM

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2129]
When `kubectl delete pod` is run for example, a pod's container's entrypoint's are sent a SIGTERM. If they ignore that, they will not understand they are asked to terminate, so they will end up shutting down by force after 30 seconds instead.

I think z2jh's pods, including the hub pod, are optimized to shut down fast. But I think basehub's hub pod is slow to shut down because of the side-car containers we inject via the deployer CLI.

https://github.com/2i2c-org/infrastructure/blob/a9d8816bb423cb3117ef94935f303e4afd1cc9ee/deployer/hub.py#L87-L121

I think we should ensure that our hub pod's extra container can shut down without needing to wait for 30 seconds. If we for example ensure that the hub pod is faster to shut down, it can lead to less downtime during upgrades, faster CI/CD workflow executions, and such.

### Action point

- [x] Start a docker container locally and validate my belief it blocks a fast shut down, as can be seen using `docker stop` [similar to how it was tested in this issue](https://github.com/jupyterhub/configurable-http-proxy/issues/215).
- [x] Make changes until its respecting SIGTERM and shuts down properly.
- [x] Make the equivalent changes in our k8s context

### Related

- https://github.com/search?q=org%3Ajupyterhub+sigterm+author%3Aconsideratio&type=pullrequests

**Comment by pnasrat** [comment]
Some notes from local testing

```sh
# Create volume
docker run -ti --rm  -v custom-templates:/srv/repo -l templates-clone alpine/git clone -- https://github.com/2i2c-org/default-hub-homepage /srv/repo
# Replicate templates-sync container
docker run -ti --rm -v custom-templates:/srv/repo -w /srv/repo --entrypoint /bin/sh alpine/git -c "ls -lhd /srv/repo; while true; do git fetch origin; git reset --hard origin/master; sleep 5m; done"
```

**Comment by pnasrat** [comment]
My signal handling in bash is a little rusty so I am going to refresh how `trap` and `wait` work with `sleep` under `/bin/sh -c`

**Comment by consideRatio** [comment]
Excellent! Note I recall alpine doesnt come with bash anyhow, even though switching to another image is an opion also.

**Comment by pnasrat** [comment]
I've started looking at https://github.com/kubernetes/git-sync as one mechanism to do this. 

An initial stumbling block was that the git-sync container v3.6.4 pulls in a CVE fix in the upgrade to git  1:2.30.2-1 deb11u1  that needed `--git-config=safe.directory:/tmp/git` (or possibly a similar chown type initContainer that the existing templates sync implementation has. I used container-diff to help figure this out.

It's blob size is 58.6 MiB (166.8 MiB) vs `alpine/git` 20.3MB (43.5 MiB) but also comes with prometheus metrics, etc

<details><summary>container-diff</summary>
<p>
<pre>
container-diff diff --type=apt  registry.k8s.io/git-sync/git-sync:v3.6.3 registry.k8s.io/git-sync/git-sync:v3.6.4

-----Apt-----

Packages found only in registry.k8s.io/git-sync/git-sync:v3.6.3: None

Packages found only in registry.k8s.io/git-sync/git-sync:v3.6.4: None

Version differences:
PACKAGE                 IMAGE1 (registry.k8s.io/git-sync/git-sync:v3.6.3)        IMAGE2 (registry.k8s.io/git-sync/git-sync:v3.6.4)
-git                    1:2.30.2-1, 34.2M                                        1:2.30.2-1 deb11u1, 34.3M
-git-man                1:2.30.2-1, 1.8M                                         1:2.30.2-1 deb11u1, 1.8M
-libcurl3-gnutls        7.74.0-1.3 deb11u3, 735K                                 7.74.0-1.3 deb11u5, 736K
</pre>
</p>
</details>

**Comment by yuvipanda** [comment]
Yeah, this setup was designed to have multiple different *repos* rather than branches on the same repo, so that individual hubs can have their own repos with their own merge rights, so it wouldn't require us to do merges. I'm curious to see if we can document and go back to that vs doing per-branch merges? But that shouldn't block this investigation :)

**Comment by pnasrat** [comment]
Given the issues with symlinks and subPaths I think the better thing to do is create a templates-sync image that can be used

Adding bash ontop of alpine/git with the following Dockerfile

```Dockerfile
FROM alpine/git

RUN apk add --no-cache bash
```

```
docker images
REPOSITORY                    TAG          IMAGE ID       CREATED              SIZE
templates-sync                latest       793eb3116b40   About a minute ago   45.2MB
alpine/git                    latest       22d84a66cda4   3 months ago         43.6MB
```

**Comment by pnasrat** [comment]
Actually built with chartpress

```
REPOSITORY                    TAG                              IMAGE ID       CREATED          SIZE
quay.io/2i2c/pilot-hub        0.0.1-0.dev.git.4978.h858bd17c   bad39a2b66db   45 seconds ago   444MB
templates-sync                latest                           793eb3116b40   12 minutes ago   45.2MB
quay.io/2i2c/templates-sync   0.0.1-0.dev.git.1952.h7e971ae8   64eee033d449   12 minutes ago   45.2MB
```

**Comment by pnasrat** [comment]
I've a WIP branch pushed to create the image but I'll do testing to see if I can profile shutdown timing and get TERM handling.

**Comment by pnasrat** [comment]
Built and pushed https://quay.io/repository/2i2c/templates-sync?tab=tag

**Comment by pnasrat** [comment]
Note previous bug has this comment on not wanting to maintain extra images, need to understand that

https://github.com/2i2c-org/infrastructure/issues/443#issuecomment-864968256

**Comment by consideRatio** [comment]
This is an issue I'd like to give priority to, because without solving this, I end up looking to rule it out as the culprit of other issues reported - such as https://2i2c.freshdesk.com/a/tickets/812.
