### ISSUE TITLE
Setup the profile list to allow a user specified image for leap.2i2c.cloud - for all server options

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2146]
As requested in [this support ticket](https://2i2c.freshdesk.com/a/tickets/386), setup the ability for users of leap.2i2c.cloud to specify an image - independent of their server choice.

### Action points
- [x] Implement this
  This was not possible, at least not yet. I've opened https://github.com/jupyterhub/kubespawner/issues/699 for now.
  - [x] This is being worked in https://github.com/jupyterhub/kubespawner/pull/735
    We can help with review efforts
- [x] Followup with Julius in [the support ticket](https://2i2c.freshdesk.com/a/tickets/386)
  I've communicated that we couldn't accomplish a free form text image choice.

**Comment by GeorgianaElena** [comment]
@consideRatio, this sounds like this could be achieved with the configurator? 
If the configurator plays nicely with the kubespawner profiles, then setting the image in the configurator, then choosing a  server option should be enough right?

Otherwise, I'm not sure specifying the image in an input text of some sort is possible with the current profiles implementation

**Comment by consideRatio** [comment]
@GeorgianaElena I understand it as they are aware of the configurator, but still wanted to allow individual users to specify their own image for a specific server startup - also indepentent of being an admin or not.

**Comment by consideRatio** [comment]
Oh no, I thought this was part of profile_options in https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.profile_list.

**Comment by consideRatio** [comment]
I'll close this for now.

**Comment by yuvipanda** [comment]
@consideRatio can we keep this open until we can deploy the change?

**Comment by yuvipanda** [comment]
Currently, manually testing works but our healthcheck fails with:


```
[E 2023-07-25 07:58:24.152 JupyterHub user:884] Unhandled error starting deployment-service-check's server: Expected option image for profile medium-full or image--unlisted-choice, not found in posted form
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/user.py", line 798, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/jovyan/.local/lib/python3.11/site-packages/jupyterhub_configurator/mixins.py", line 45, in start
        return await super().start(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/jovyan/.local/lib/python3.11/site-packages/kubespawner/spawner.py", line 2656, in _start
        await self.load_user_options()
      File "/home/jovyan/.local/lib/python3.11/site-packages/kubespawner/spawner.py", line 3232, in load_user_options
        await self._load_profile(
      File "/home/jovyan/.local/lib/python3.11/site-packages/kubespawner/spawner.py", line 3123, in _load_profile
        self._validate_posted_profile_options(
      File "/home/jovyan/.local/lib/python3.11/site-packages/kubespawner/spawner.py", line 3033, in _validate_posted_profile_options
        raise ValueError(
    ValueError: Expected option image for profile medium-full or image--unlisted-choice, not found in posted form
```

**Comment by yuvipanda** [comment]
This was done again in https://github.com/2i2c-org/infrastructure/pull/3047! Thanks to @GeorgianaElena!
