### ISSUE TITLE
grafana, utoronto: deployer script unauthorized

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2152]
Deploying new grafana dashboards to utoronto failed in https://github.com/2i2c-org/infrastructure/actions/runs/4108418727/jobs/7089089160, it sais 401 UNAUTHORIZED. Maybe its a hub that isn't setup like other hubs?

It would be good to have it aligned with the other hubs! I've not investigated this at all, just opened this to not need to tackle this myself right now.

**Comment by damianavila** [comment]
@yuvipanda may have some quick thoughts since he was actively working on that deployment several weeks before.
