### ISSUE TITLE
Now we use `notebook` - we need to allow for `jupyter_server`

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2156]
In [a slack thread](https://2i2c.slack.com/archives/CKJS000F4/p1675062390719029) @yuvipanda clarified that we are starting all user servers using the classical `notebook` server by configuring this ([see JupyterHub docs](https://jupyterhub.readthedocs.io/en/stable/reference/config-user-env.html#switching-back-to-the-classic-notebook)):

https://github.com/2i2c-org/infrastructure/blob/a9d8816bb423cb3117ef94935f303e4afd1cc9ee/helm-charts/basehub/values.yaml#L181-L186

In [this support ticket from the `temple` hub](https://2i2c.freshdesk.com/a/tickets/423) we conclude that a modern `jupyter/datascience-notebook` image won't work with JupyterLab any more, where the notebook server presents 404 Not found when accessing `/lab`, because of this:

```
[I 2023-02-07 06:17:06.501 SingleUserNotebookApp mixins:609] Starting jupyterhub single-user server version 3.1.1
[I 2023-02-07 06:17:06.502 SingleUserNotebookApp mixins:623] Extending notebook.notebookapp.NotebookApp from notebook 6.5.2

# ...

[W 2023-02-07 06:17:07.775 SingleUserNotebookApp serverextension:13] Loading JupyterLab as a classic notebook (v6) extension.
[C 2023-02-07 06:17:07.775 SingleUserNotebookApp serverextension:18] You must use Jupyter Server v1 to load JupyterLab as notebook extension. You have v2.2.1 installed.
    You can fix this by executing:
        pip install -U "jupyter-server<2.0.0"
```

## What to do

__What we should do no matter what__

- We should overview all things we do that is `notebook` or `jupyter_server` specific.
- We should plan what we to communicate to users managing user environment images

__Four strategies to consider__

1. We can ask users to pin `jupyter_server<2`, but that will come back and haunt 
us when we need them to have `jupyter_server>=2` now or because they request features that only v2 supports.
2. We can start overriding to `JUPYTERHUB_SINGLEUSER_APP=jupyter_server.serverapp.ServerApp` for individual hubs, and along with that also updating configuration of `notebook` classic to configuration of `jupyter_server`
3. We can start overriding to `JUPYTERHUB_SINGLEUSER_APP=` for individual hubs, and along with that make sure to provide configuration to both `notebook` classic and `jupyter_server`
4. We can remove our [configuration forcing `notebook` in the `basehub` chart](https://github.com/2i2c-org/infrastructure/blob/a9d8816bb423cb3117ef94935f303e4afd1cc9ee/helm-charts/basehub/values.yaml#L181-L186)

No matter what we choose, we can introduce breaking changes here as users may include their own configuration of `notebook` or `jupyter_server` specifically. So I think we can only start a transition of individual hubs and communicate ahead when we look to make a certain transition here ahead of time if we are to introduce a breaking change.

I suggest we trial with either 2 or 3, then we communicate that at a certain date we are going for 4 along with technical notes on what they need to update or not in user environment images.

**Comment by yuvipanda** [comment]
@consideRatio thank you for writing this up very nicely! As I put this in place as a 'temporary fix' (https://github.com/2i2c-org/infrastructure/pull/2160), I think it's ok to get rid of it now, and keep an eye out for issues.

**Comment by yuvipanda** [comment]
Unfortunately this was reverted, see #2210 for more details

**Comment by damianavila** [comment]
#2210 was merged, so we can close this one again!
