### ISSUE TITLE
Document procedure and migrate existing GCP GKE based hubs from k8s 1.22+ to 1.24+

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2157]
This is the current status of GCP GKE clusters. We should get them all to 1.24+. This is where the "regular" release channel of GKE is currently at.

- [x] 2i2c, k8s v1.26.4-gke.1400 - [GCP link](https://console.cloud.google.com/kubernetes/clusters/details/us-central1-b/pilot-hubs-cluster/details?project=two-eye-two-see)
  - Node groups at: v1.26
  - Upgrade done by Yuvi 2023-06-09, from v1.22 to v1.26
- [x] pangeo-hubs, k8s v1.26.4-gke.1400 - [GCP link - passport submission for access](https://console.cloud.google.com/kubernetes/clusters/details/us-central1-b/pangeo-hubs-cluster/nodes?project=columbia)
  - Node groups at: v1.26
  - Upgrade done by Yuvi 2023-06-09, from v1.22 to v1.26
- [x] meom-ige, k8s  v1.26.4-gke.1400 - [GCP link](https://console.cloud.google.com/kubernetes/clusters/details/us-central1-b/meom-ige-cluster/nodes?project=meom-ige-cnrs)
  - Node groups at: v1.26
  - Upgrade done by Yuvi 2023-06-09, from v1.22 to v1.26
- [x] cloudbank, k8s v1.26.4-gke.1400 - [GCP link](https://console.cloud.google.com/kubernetes/clusters/details/us-central1-b/cb-cluster/nodes?project=cb-1003-1696)
  - Node groups at: v1.26
  - Upgrade done by Yuvi 2023-06-09, from v1.22 to v1.26
- [x] callysto, k8s v1.25.6-gke.1000 - [GCP link](https://console.cloud.google.com/kubernetes/clusters/details/northamerica-northeast1/callysto-cluster/details?project=callysto-202316)
  - Node groups at: v1.25
  - Maintenance upgrade suggested at https://2i2c.freshdesk.com/a/tickets/562, tracked in https://github.com/2i2c-org/infrastructure/issues/2388, k8s upgraded from 1.23 -> 1.25, node pools from 1.22 -> 1.25
- [x] m2lines, k8s v1.24.5-gke.600 - [GCP link](https://console.cloud.google.com/kubernetes/clusters/details/us-central1/m2lines-cluster/details?project=m2lines-hub)
  - Node groups at: v1.24
- [x] linked-earth, k8s v1.24.5-gke.600 - [GCP link](https://console.cloud.google.com/kubernetes/clusters/details/us-central1/linked-earth-cluster/nodes?project=linked-earth-hubs)
  - Node groups at: v1.24
- [x] leap, k8s v1.25.6-gke.1000 - [GCP link](https://console.cloud.google.com/kubernetes/clusters/details/us-central1/leap-cluster/nodes?project=leap-pangeo)
  - Node groups at: v1.25 (from 1.24 -> 1.25 in #2337)
- [x] awi-ciroh, k8s v1.25.8-gke.500 - [GCP link](https://console.cloud.google.com/kubernetes/clusters/details/us-central1/awi-ciroh-cluster/details?project=awi-ciroh)
  - Node groups at: v1.25 (from 1.24 -> 1.25 in #2554)
- [x] 2i2c-uk, k8s v1.24.7-gke.900 - [GCP link](https://console.cloud.google.com/kubernetes/clusters/details/europe-west2/two-eye-two-see-uk-cluster/nodes?authuser=3&project=two-eye-two-see-uk)
  - Node groups at: v1.24

### Action points

- [x] Upgrade all GKE clusters to k8s 1.24+
  - [x] Control planes
  - [x] Node pools
- [ ] Document a upgrade procedure for GKE clusters (Equivalent of #2142)
  - Preliminary notes in https://github.com/2i2c-org/infrastructure/issues/2388#issuecomment-1479153571.
  - Its likeley relevant to consider https://github.com/2i2c-org/infrastructure/issues/2490, and ensure we don't get two core replicas

### Related

- #2057
- #2158

**Comment by yuvipanda** [comment]
I made a table with all our versions, after opportunistic updates to meom-ige, 2i2c and cloudbank:

cluster | control plane version | nodes version
|- | - | -|
nasa-cryo | v1.25.9 | v1.25.6
carbonplan | v1.24.13 | v1.24.7
gridsst | v1.25.9 | v1.25.6
jupyter-meets-the-earth | v1.25.9 | v1.25.7
pangeo-hubs | v1.24.12 | v1.20.8,v1.21.11
awi-ciroh | v1.25.8 | v1.25.6
meom-ige | v1.26.4 | v1.26.4
utoronto | v1.26.3 | v1.26.3
m2lines | v1.24.12 | v1.24.5
victor | v1.25.9 | v1.25.6
2i2c | v1.26.4 | v1.26.4,v1.24.11
linked-earth | v1.24.12 | v1.24.7
openscapes | v1.24.13 | v1.24.9
qcl | v1.24.12 | v1.24.9
2i2c-aws-us | v1.25.9 | v1.25.6
2i2c-uk | v1.24.12 | v1.24.5
ubc-eoas | v1.24.13 | v1.24.7
cloudbank | v1.26.4 | v1.26.4
callysto | v1.25.8 | v1.25.6
smithsonian | v1.25.9 | v1.25.7
leap | v1.25.8 | v1.25.6
nasa-veda | v1.25.9 | v1.25.6

Looks like pangeo-hubs is the only one that's <1.24

**Comment by consideRatio** [comment]
Closing this as completed, and extracting out the part about documenting the upgrade procedure.
