### ISSUE TITLE
Decomission cluster: uwhackweeks

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2173]
We no longer have a hub comissioned for the uwhackweeks cluster, so the entire cluster should be cleaned up based on @scottyhq's input in https://github.com/2i2c-org/infrastructure/issues/2031#issuecomment-1398637957 and [a discussion](https://2i2c.slack.com/archives/C01GLCC1VCN/p1675293787696439) with @jmunroe and @colliand I opened to ensure that we not only stop the cloud costs, but also the billing to uwhackweeks.

### Action points

Here are a few of the action points I see for 2i2c's engineering team to take.

- Cleanup all resources in our github repo
- Cleanup all template adjustments possibly made in brances to https://github.com/2i2c-org/default-hub-homepage
- Cleanup misc resources mentioned in the guide on decomissioning a hub
- Confirmation and cleanup of cloud accounts or at least disabling of billing in some way to cut all running costs to zero.

### Related

- #1336
- #2031 

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [x] Run `terraform plan -destroy` and `terraform apply -destroy` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [x] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [x] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [x] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [x] [`validate-clusters.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/validate-clusters.yaml)
- [x] Remove the cluster from the list of grafana datasources at https://grafana.pilot.2i2c.cloud/datasources
- [x] Remove A record from Namecheap account

**Comment by pnasrat** [comment]
Additional req: Document the process for cluster decomissioning

**Comment by consideRatio** [comment]
@pnasrat note that this is a AWS based hub and there are be difference between how to tear down AWS / GCP based cloud infra. I suggest narrowing the scope to not consider GCP cloud infra decomissioning.

**Comment by pnasrat** [comment]
```
terraform plan -destroy -var-file=projects/uwhackweeks.tfvars -no-color

No changes. No objects need to be destroyed.
```

**Comment by pnasrat** [comment]
```
 terraform apply -destroy -var-file=projects/uwhackweeks.tfvars -no-color

No changes. No objects need to be destroyed.

Either you have not created any objects yet or the existing objects were already deleted outside of Terraform.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by pnasrat** [comment]
```
terraform workspace delete uwhackweeks
Deleted workspace "uwhackweeks"!
```

**Comment by pnasrat** [comment]
`kubectl get pods -A`

<details><summary>running pods</summary>
<p>
<pre>
kubectl get pods -A
NAMESPACE      NAME                                                READY   STATUS    RESTARTS   AGE
cert-manager   cert-manager-5bb7949947-drmdf                       1/1     Running   2          211d
cert-manager   cert-manager-cainjector-5ff98c66d-mwtgp             1/1     Running   2          211d
cert-manager   cert-manager-webhook-fb48856b5-fxx24                1/1     Running   0          211d
kube-system    aws-node-2vmf9                                      1/1     Running   0          74d
kube-system    aws-node-77j6h                                      1/1     Running   0          378d
kube-system    coredns-85d5b4454c-hblc6                            1/1     Running   0          378d
kube-system    coredns-85d5b4454c-wtjbr                            1/1     Running   0          378d
kube-system    ebs-csi-controller-c477d99b-hx9gv                   6/6     Running   0          14d
kube-system    ebs-csi-controller-c477d99b-v8bbn                   6/6     Running   0          14d
kube-system    ebs-csi-node-5jkbq                                  3/3     Running   0          14d
kube-system    ebs-csi-node-mr5r4                                  3/3     Running   0          14d
kube-system    kube-proxy-f87lp                                    1/1     Running   0          378d
kube-system    kube-proxy-pkmw2                                    1/1     Running   0          74d
kube-system    nvidia-device-plugin-daemonset-tnl8q                1/1     Running   0          125d
kube-system    nvidia-device-plugin-daemonset-vqvd6                1/1     Running   0          74d
staging        api-staging-dask-gateway-8498d8bb97-t968r           1/1     Running   0          46d
staging        controller-staging-dask-gateway-8578cc47c-92tpj     1/1     Running   0          46d
staging        hub-d4995dc55-wz2l4                                 2/2     Running   0          3d15h
staging        proxy-6965f6c955-mlgps                              1/1     Running   0          6d15h
staging        shared-volume-metrics-6db84986d4-f4ngx              1/1     Running   0          18d
staging        traefik-staging-dask-gateway-759bd667b9-4prbg       1/1     Running   0          46d
support        support-aws-cluster-autoscaler-5cdb94689d-5mxcz     1/1     Running   0          12d
support        support-cryptnono-bcckh                             1/1     Running   0          74d
support        support-cryptnono-t987m                             1/1     Running   0          250d
support        support-grafana-7f4bfcd464-jkf4v                    1/1     Running   0          11d
support        support-ingress-nginx-controller-665f77b6cc-j76mm   1/1     Running   0          27d
support        support-kube-state-metrics-7c6fdcb8dc-5wd4z         1/1     Running   0          27d
support        support-prometheus-node-exporter-5b5fb              1/1     Running   0          27d
support        support-prometheus-node-exporter-6l955              1/1     Running   0          27d
support        support-prometheus-server-68d776799b-f8gx7          2/2     Running   0          16h
</pre>
</p>
</details>

**Comment by pnasrat** [comment]
As first time just checking that removing cluster removes uptime checks

```
terraform plan | grep will\ be
  # google_monitoring_alert_policy.hub_simple_uptime_alert["staging.uwhackweeks.2i2c.cloud"] will be destroyed
  # google_monitoring_alert_policy.prometheus_simple_uptime_alert["prometheus.uwhackweeks.2i2c.cloud"] will be destroyed
  # google_monitoring_uptime_check_config.hub_simple_uptime_check["staging.uwhackweeks.2i2c.cloud"] will be destroyed
  # google_monitoring_uptime_check_config.prometheus_simple_uptime_check["prometheus.uwhackweeks.2i2c.cloud"] will be destroyed
```

**Comment by pnasrat** [comment]
```
 eksctl delete cluster --config-file=uwhackweeks.eksctl.yaml 2023-02-22 08:57:53 [ℹ]  deleting EKS cluster "uwhackweeks"
Error: operation error CloudFormation: ListStacks, https response error StatusCode: 403, RequestID: a11dcde8-e15b-448a-abd9-809e4678a49d, api error AccessDenied: User: arn:aws:iam::740010314650:user/hub-continuous-deployer is not authorized to perform: cloudformation:ListStacks on resource: arn:aws:cloudformation:us-west-2:740010314650:stack/*/* because no identity-based policy allows the cloudformation:ListStacks action
```

**Comment by pnasrat** [comment]
```
2023-02-22 09:08:46 [!]  1 pods are unevictable from node ip-192-168-43-174.us-west-2.compute.internal
2023-02-22 09:09:50 [!]  1 pods are unevictable from node ip-192-168-43-174.us-west-2.compute.internal
```

Rerunning with ` eksctl delete cluster --config-file=uwhackweeks.eksctl.yaml  --disable-nodegroup-eviction`

**Comment by pnasrat** [comment]
```
2023-02-22 09:17:06 [ℹ]  serviceaccount "prod/cloud-user-sa" was already deleted
2023-02-22 09:17:06 [ℹ]  deleted serviceaccount "kube-system/aws-node"
2023-02-22 09:17:06 [ℹ]  deleted serviceaccount "staging/cloud-user-sa"
2023-02-22 09:17:07 [ℹ]  will delete stack "eksctl-uwhackweeks-addon-aws-ebs-csi-driver"
2023-02-22 09:17:07 [ℹ]  will delete stack "eksctl-uwhackweeks-cluster"
2023-02-22 09:17:08 [✔]  all cluster resources were deleted
```

**Comment by pnasrat** [comment]
CNAMEs removed looks like there is a *.2i2c.cloud going to 35.223.43.171 (confirmed in namecheap). Done that other than waiting for DNS propagation/caches expire 

```
; <<>> DiG 9.18.1-1ubuntu1.3-Ubuntu <<>> nosuchcluster.2i2c.cloud uwhackweeks.2i2c.cloud
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1179
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;nosuchcluster.2i2c.cloud.	IN	A

;; ANSWER SECTION:
nosuchcluster.2i2c.cloud. 46	IN	A	35.223.43.171

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Wed Feb 22 11:52:13 EST 2023
;; MSG SIZE  rcvd: 69

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46476
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;uwhackweeks.2i2c.cloud.		IN	A

;; ANSWER SECTION:
uwhackweeks.2i2c.cloud.	9	IN	A	35.223.43.171

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Wed Feb 22 11:52:13 EST 2023
;; MSG SIZE  rcvd: 67

```

**Comment by pnasrat** [comment]
TODO

- [ ]  to delete branch https://github.com/2i2c-org/default-hub-homepage/tree/uwhackweeks-prod
- [ ] delete GH Oauth app https://github.com/organizations/2i2c-org/settings/applications/1826369
- [ ] delete uwhackweeks-staging Auth0 https://manage.auth0.com/dashboard/us/2i2c/applications/X7sqvn0DrX4qHmjUR8gfROSt0rnIypEG/settings

**Comment by pnasrat** [comment]
I'm not 100% sure how best to check what @consideRatio suggests beyond iterating over each console

* Confirmation and cleanup of cloud accounts or at least disabling of billing in some way to cut all running costs to zero.

EC2 console for us-west-2 lists nothing other than 3 security groups
Elastic Container Service for Kubernetes console lists no clusters
EFS lists a hub-homedirs but it's not labeled by service 
S3 buckets still exist https://s3.console.aws.amazon.com/s3/buckets?region=us-west-2

**Comment by consideRatio** [comment]
@pnasrat now it becomes very relevant if this project was initially set up and owned by us at 2i2c, or if its owned by for example `@scottyhq`. Do you know?

I think we haven't touched any cloud infrastructure besides some IAM user accounts and what we managed via `eksctl` and `terraform`. The key question for me was if `eksctl delete cluster` successfully cleaned up what was declared in the eksctl cluster config (uwhackweeks.jsonnet).

Due to that, I think its most important that we verify that `eksctl` managed resources and `terraform` managed resources are cleared up.

**Comment by pnasrat** [comment]
Here both `terraform apply -destroy` and `eksctl delete cluster` were successful at their managed resources. If needed I can check would be to get a detached head and rerun terraform plan and `eksctl create --dry-run`.  I don't have a quick answer re the AWS account but it existed under 2i2c.awsapps.com annoted `#740010314650 | yuvipanda+uwhackweeks@2i2c.orgyuvipanda+uwhackweeks@`

I'll continue looking at this tomorrow

**Comment by pnasrat** [comment]
Did some digging and can list the remaining resources using aws cli

`aws resourcegroupstaggingapi get-resources --region us-west-2`

```json
{
    "ResourceTagMappingList": [
        {
            "ResourceARN": "arn:aws:ec2:us-west-2:740010314650:subnet/subnet-017677e0d897a6bc4",
            "Tags": [
                {
                    "Key": "aws:cloudformation:stack-name",
                    "Value": "eksctl-uwhackweeks-cluster"
                },
                {
                    "Key": "alpha.eksctl.io/cluster-name",
                    "Value": "uwhackweeks"
                },
                {
                    "Key": "aws:cloudformation:stack-id",
                    "Value": "arn:aws:cloudformation:us-west-2:740010314650:stack/eksctl-uwhackweeks-cluster/7aedb7b0-87e6-11ec-b21d-06c744833393"
                },
                {
                    "Key": "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
                    "Value": "uwhackweeks"
                },
                {
                    "Key": "aws:cloudformation:logical-id",
                    "Value": "SubnetPublicUSWEST2B"
                },
                {
                    "Key": "kubernetes.io/role/elb",
                    "Value": "1"
                },
                {
                    "Key": "alpha.eksctl.io/eksctl-version",
                    "Value": "0.76.0"
                },
                {
                    "Key": "Name",
                    "Value": "eksctl-uwhackweeks-cluster/SubnetPublicUSWEST2B"
                }
            ]
        },
        {
            "ResourceARN": "arn:aws:elasticfilesystem:us-west-2:740010314650:file-system/fs-0b36aa23f1d92e4da",
            "Tags": [
                {
                    "Key": "Name",
                    "Value": "hub-homedirs"
                }
            ]
        },
        {
            "ResourceARN": "arn:aws:cloudformation:us-west-2:740010314650:stack/eksctl-uwhackweeks-cluster/7aedb7b0-87e6-11ec-b21d-06c744833393",
            "Tags": [
                {
                    "Key": "alpha.eksctl.io/cluster-name",
                    "Value": "uwhackweeks"
                },
                {
                    "Key": "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
                    "Value": "uwhackweeks"
                },
                {
                    "Key": "alpha.eksctl.io/eksctl-version",
                    "Value": "0.76.0"
                }
            ]
        },
        {
            "ResourceARN": "arn:aws:ec2:us-west-2:740010314650:security-group/sg-0573dcf55029bd78c",
            "Tags": [
                {
                    "Key": "aws:cloudformation:stack-name",
                    "Value": "eksctl-uwhackweeks-cluster"
                },
                {
                    "Key": "alpha.eksctl.io/cluster-name",
                    "Value": "uwhackweeks"
                },
                {
                    "Key": "aws:cloudformation:stack-id",
                    "Value": "arn:aws:cloudformation:us-west-2:740010314650:stack/eksctl-uwhackweeks-cluster/7aedb7b0-87e6-11ec-b21d-06c744833393"
                },
                {
                    "Key": "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
                    "Value": "uwhackweeks"
                },
                {
                    "Key": "aws:cloudformation:logical-id",
                    "Value": "ClusterSharedNodeSecurityGroup"
                },
                {
                    "Key": "alpha.eksctl.io/eksctl-version",
                    "Value": "0.76.0"
                },
                {
                    "Key": "Name",
                    "Value": "eksctl-uwhackweeks-cluster/ClusterSharedNodeSecurityGroup"
                }
            ]
        },
        {
            "ResourceARN": "arn:aws:ec2:us-west-2:740010314650:vpc/vpc-0b9fcd48763d420ef",
            "Tags": [
                {
                    "Key": "aws:cloudformation:stack-name",
                    "Value": "eksctl-uwhackweeks-cluster"
                },
                {
                    "Key": "alpha.eksctl.io/cluster-name",
                    "Value": "uwhackweeks"
                },
                {
                    "Key": "aws:cloudformation:stack-id",
                    "Value": "arn:aws:cloudformation:us-west-2:740010314650:stack/eksctl-uwhackweeks-cluster/7aedb7b0-87e6-11ec-b21d-06c744833393"
                },
                {
                    "Key": "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
                    "Value": "uwhackweeks"
                },
                {
                    "Key": "aws:cloudformation:logical-id",
                    "Value": "VPC"
                },
                {
                    "Key": "alpha.eksctl.io/eksctl-version",
                    "Value": "0.76.0"
                },
                {
                    "Key": "Name",
                    "Value": "eksctl-uwhackweeks-cluster/VPC"
                }
            ]
        }
    ]
}
```

**Comment by pnasrat** [comment]
```
aws s3api delete-bucket --bucket uwhackweeks-scratch --region us-west-2
aws s3api delete-bucket --bucket uwhackweeks-scratch-staging --region us-west-2
aws s3api delete-bucket --bucket uwhackweeks-snowex-scratch --region us-west-2
```

**Comment by pnasrat** [comment]
Network interfaces:

Query: ` aws ec2 describe-network-interfaces --region us-west-2`

```json
{
    "NetworkInterfaces": [
        {
            "Attachment": {
                "AttachmentId": "ela-attach-04c5e5ed7fac82ba6",
                "DeleteOnTermination": false,
                "DeviceIndex": 1,
                "InstanceOwnerId": "amazon-aws",
                "Status": "attached"
            },
            "AvailabilityZone": "us-west-2b",
            "Description": "EFS mount target for fs-0b36aa23f1d92e4da (fsmt-079fa5f25d2b3bb80)",
            "Groups": [
                {
                    "GroupName": "eksctl-uwhackweeks-cluster-ClusterSharedNodeSecurityGroup-Z2IXP8VZBDQH",
                    "GroupId": "sg-0573dcf55029bd78c"
                }
            ],
            "InterfaceType": "interface",
            "Ipv6Addresses": [],
            "MacAddress": "06:4a:a6:e2:69:73",
            "NetworkInterfaceId": "eni-097236e3cb0b15f4f",
            "OwnerId": "740010314650",
            "PrivateDnsName": "ip-192-168-59-44.us-west-2.compute.internal",
            "PrivateIpAddress": "192.168.59.44",
            "PrivateIpAddresses": [
                {
                    "Primary": true,
                    "PrivateDnsName": "ip-192-168-59-44.us-west-2.compute.internal",
                    "PrivateIpAddress": "192.168.59.44"
                }
            ],
            "RequesterId": "086616648226",
            "RequesterManaged": true,
            "SourceDestCheck": true,
            "Status": "in-use",
            "SubnetId": "subnet-017677e0d897a6bc4",
            "TagSet": [],
            "VpcId": "vpc-0b9fcd48763d420ef"
        }
    ]
}
```

**Comment by pnasrat** [comment]
ok dependency issues see

https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-dependency-error-delete-vpc/

```
            "InternetGatewayId": "igw-04ebecd58ebbe043f",
            "SubnetId": "subnet-04c2b2a4df43dfe99",
            "SubnetId": "subnet-03c83b31e989f73a8",
            "SubnetId": "subnet-05950ea62b0b361ac",
            "SubnetId": "subnet-0c06f0242bd0c562e",
                    "RouteTableId": "rtb-03b454f62581138ee",
            "RouteTableId": "rtb-03b454f62581138ee",
                    "NetworkAclId": "acl-0c6c9070886d37eb8",
                    "NetworkAclId": "acl-0c6c9070886d37eb8",
                    "NetworkAclId": "acl-0c6c9070886d37eb8",
                    "NetworkAclId": "acl-0c6c9070886d37eb8",
            "NetworkAclId": "acl-0c6c9070886d37eb8",
                            "GroupId": "sg-05f1d313ef3b9beb9",
            "GroupId": "sg-05f1d313ef3b9beb9",
```

**Comment by pnasrat** [comment]
ok EFS is keeping the networking stack live

```
aws efs delete-mount-target --mount-target-id=fsmt-079fa5f25d2b3bb80 --region=us-west-2 
aws efs delete-file-system --file-system-id=fs-0b36aa23f1d92e4da  --region=us-west-2
```

**Comment by pnasrat** [comment]
Next subnet

`aws ec2 delete-subnet --subnet-id=subnet-017677e0d897a6bc4 --region=us-west-2`

**Comment by pnasrat** [comment]
I deleted the VPC and its security group via the web https://us-west-2.console.aws.amazon.com/vpc/home? I'm sure there is a cli way just want to get through this...

**Comment by pnasrat** [comment]
Deleteing cloudformation stack via console https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2

**Comment by pnasrat** [comment]
Deleted default vpc through console (which cascade deleted the internet gateway)

```
aws resourcegroupstaggingapi get-resources --region us-west-2 
{
    "ResourceTagMappingList": []
}
```

**Comment by pnasrat** [comment]
Checked via https://us-west-2.console.aws.amazon.com/resource-groups/tag-editor/find-resources and there was dhcp options remaining

`aws ec2 describe-dhcp-options --region=us-west-2`

```json
{
    "DhcpOptions": [
        {
            "DhcpConfigurations": [
                {
                    "Key": "domain-name",
                    "Values": [
                        {
                            "Value": "us-west-2.compute.internal"
                        }
                    ]
                },
                {
                    "Key": "domain-name-servers",
                    "Values": [
                        {
                            "Value": "AmazonProvidedDNS"
                        }
                    ]
                }
            ],
            "DhcpOptionsId": "dopt-0475edee192340018",
            "OwnerId": "740010314650",
            "Tags": []
        }
    ]
}
```

**Comment by pnasrat** [comment]
I believe that all the turndown is done. I'm using #1070 to track the documentation work attached to this, as this is already a long issue with all the step documentation.

**Comment by consideRatio** [comment]
Nice work on this @pnasrat!!!

**Comment by pnasrat** [comment]
Note the global dashboard manually wires in the datasources and needed to be edited (just removal of datasource not sufficient). This probably needs  thought as we might need historic data for billing

https://grafana.pilot.2i2c.cloud/d/global-usage-dashboard/global-usage-dashboard?orgId=1

**Comment by damianavila** [comment]
OK, forget about this, I already saw: https://github.com/2i2c-org/infrastructure/issues/1070#issuecomment-1472072491. Thanks!!
