### ISSUE TITLE
grafana: learn if github auth supports either org or team authorization

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2179]
The [grafana documentation on github auth](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/github/#enable-github-in-grafana) wasn't clear with regards to if `allowed_organizations` and `team_ids` could be used together, or how a team id would be specified.

If we can verify that we can provide access to github teams as well besides access to us in the github org `2i2c-org`, that will help when asking users if they want a certain group of users to be granted grafana access via github identities.

### Related

- https://github.com/2i2c-org/infrastructure/pull/2178

**Comment by GeorgianaElena** [comment]
@consideRatio, I believe there was some discussion or mention of some relevant docs of some sort in https://github.com/2i2c-org/infrastructure/issues/1570

**Comment by colliand** [comment]
Thanks for creating this issue. I point this discussion out to @jmunroe as it overlaps with support discussions with Luis Lopez (betolink on GitHub). Once the technical issues are resolved, 2i2c Partnerships and Community should adapt [this documentation](https://infrastructure.2i2c.org/en/latest/topic/monitoring-alerting/grafana.html?highlight=grafana) which is mostly focused on 2i2c's internal usage to a wider scope that includes community usage of Grafana dashboards.

**Comment by yuvipanda** [comment]
https://infrastructure.2i2c.org/en/latest/sre-guide/support/grafana-account.html?highlight=grafana is the current method of giving out access to grafana for hub admins, and they can add other users there as desired.

**Comment by consideRatio** [comment]
I think we shouldn't dig into github based authentication further for grafana hubs, but instead resort to jupyterhub as an identity provider or settle with either github org or individual user/pass accounts.

Closing this for now.

**Comment by consideRatio** [comment]
I learned something more, and concluded that use of the GitHub API can reveal IDs of github organization's teams, and they can be used.

Messy though. To inspect things like this via the GitHub REST API, its nice to use `gh` the CLI.

For example, to get info about a github org you can do:

```
gh api /orgs/smithsonian
```
