### ISSUE TITLE
`deployer` to provide a link to the cloud console for engineers convenience?

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2198]
In #2194 I suggested comments to provide cloud console links for various k8s clusters we manage in the cluster.yaml files. @pnasrat suggested in https://github.com/2i2c-org/infrastructure/pull/2194#discussion_r1104586183 that we may want this to be done via a `deployer` script command, and the comments being transformed to variables in cluster.yaml instead.

I think that is a good idea, the variable makes it accessible for a person browsing the file, but also directly from the deployer script.

**Comment by GeorgianaElena** [comment]
I like this idea too. Adding this issue to the checklist in the broader project related to improving the deployer in https://github.com/2i2c-org/infrastructure/issues/2198

**Comment by consideRatio** [comment]
We have a practice established to link to the relevant project via the cluster.yaml file in a comment, sufficient to close this I figure.
