### ISSUE TITLE
Transition LEAP cloud infra to use shared nodes

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2209]
I've together with @jbusecke distilled a support ticket to [improve user startup times] and [this this request for information](https://2i2c.freshdesk.com/a/tickets/446) among other things to this technical work items.

### Node pool changes

- There should only be one dask node pool, and it should use `n2-highmem-16`.
- The user node pools small/medium/large/huge should be removed
- A new user node pool (medium) should be added with a `n2-highmem-16` machine (16 CPU, 128 GB mem)

### New profile list

- The choices for small-huge is to be replaced with _two similar entries_ with slight differences to start on the 16 core machine.
  - This entry should present the image choices already available in the existing profile list
  - One version of the entry should be provided for the `leap-pangeo-base-access` github group, and one for `leap-pangeo-full-access`. They differ in the sense that one provides the node share options (1,2,4 CPU) and the other high (1,2,4,8,16 CPU)
  - The node share options should also set CPU/Memory limits to match the requests. This should also come with a comment that this is to be an exception rather than a default.
  
### Followup of actions

- #2364
- #2051

**Comment by jbusecke** [comment]
Thanks for working on this. Please let me know before any changes are made, so I can make sure that:
- The new user groups `leap-pangeo-base-access` and `leap-pangeo-full-access` are populated (to avoid interruption of service for users
- I give people some heads up warning to not perform any work during the transition period

**Comment by jbusecke** [comment]
Quick update: I have created and populated the new teams in our org: https://github.com/orgs/leap-stc/teams/leap-pangeo-users/teams

These are non-overlapping at the moment.

**Comment by consideRatio** [comment]
@jbusecke I suggest that I work this on Monday morning until mid day, Swedish time UTC+1. Is that okay?

**Comment by consideRatio** [comment]
There is currently three running users so I don't cancel their sessions and start an upgrade. @jbusecke should we aim for next week on monday morning Swedish timezone UTC+1?

**Comment by jbusecke** [comment]
Sorry for the delay. I was really sick all last week and not able to stare at a screen. 

I have notified the LEAP community to log out and stop any long running computation before Sun Mar 12, and said that service should be back to normal on Monday after 8AM. Is that correct @consideRatio? 

I will make another announcement closer to the weekend. Thank you for working on this!

**Comment by consideRatio** [comment]
@jbusecke absolutely correct!!

And you have populated the github teams `leap-pangeo-base-access` `leap-pangeo-full-access` etc with the users already by then, right?

**Comment by consideRatio** [comment]
@jbusecke I've now performed the most disruptive maintenance. As part of this, only users of either `leap-pangeo-base-access` `leap-pangeo-full-access` have access now as only these teams are provided with server startup choices.

![image](https://user-images.githubusercontent.com/3837114/224556869-93353577-9ddd-42dc-883b-3b7238c9c3be.png)

In this issue, the part about dask-gateway option remains but the other parts are addressed.

As part of doing maintenance in #2237, I also saw an optimization for a workshop a while back. That optimization, after the workshop when nodes wasn't started before users arrived, was likeley slowing down startup of user servers unless they started the tensorflow image specifically. So I think in this setup now, there are three reasons for faster startup.

1. Node sharing makes nodes likeley to already be running.
2. The already running nodes likeley already have the image of relevance downloaded to them.
3. When a node needs to be started, the user arriving to it won't risk needing to wait for the pulling of an unrelated image.

If you wish for even faster startups and better performance, I suggest that the for-this-maintenance agreed CPU limitation is revised. I've thought about this tricky topic a lot and summarized some of those thoughts in #2228 and in [this FIXME note](https://github.com/2i2c-org/infrastructure/pull/2337/files#diff-35cb9a4a610a9a98a7947b56a4b017f4865bd2c389b908de79d62e8da455d74dR114-R125).

**Comment by jbusecke** [comment]
So far this is working great. Many thanks @consideRatio. I think the startup times as I (and others experience them) are absolutely sufficient at the moment. 

> In this issue, the part about dask-gateway option remains but the other parts are addressed.

Is there anything that is required from my side to move this change forward?

**Comment by consideRatio** [comment]
> Is there anything that is required from my side to move this change forward?

No I think none!

@jbusecke do you feel strongly about the CPU limits? I want to make sure you have a good user experience, and think limiting CPU can be a significant drawback even for users that requests a lot of CPU to not be limited - this is because they will end up less likeley to fit on a node and then may end up needing to wait for server startup and image pulling etc.

Overall, it seems like a loose / loose / loose in terms of UX / Cost / energy efficiency to me at the moment.

**Comment by jbusecke** [comment]
> @jbusecke do you feel strongly about the CPU limits? I want to make sure you have a good user experience, and think limiting CPU can be a significant drawback even for users that requests a lot of CPU to not be limited - this is because they will end up less likeley to fit on a node and then may end up needing to wait for server startup and image pulling etc.

> Overall, it seems like a loose / loose / loose in terms of UX / Cost / energy efficiency to me at the moment.

I think I would like to give people some time to give feedback on their experience before changing things more, but I am certainly open to iterate on this further. 

I think that from my perspective the dask gateway refactor is of a higher priority. I am not sure if we should track that in a different issue to keep things neat and enable an ongoing discussion here about the CPU limits?
