### ISSUE TITLE
Overview of grafana and prometheus related issues

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2214]
There are several tickets relates to grafana and prometheus that seems relevant to overview, so this is a meta-issue overviewing those.

### Grafana

- https://github.com/2i2c-org/infrastructure/issues/2152
- https://github.com/2i2c-org/infrastructure/issues/2215
- https://github.com/2i2c-org/infrastructure/issues/2191
- https://github.com/2i2c-org/infrastructure/issues/2213
- https://github.com/2i2c-org/infrastructure/issues/2182
- https://github.com/2i2c-org/infrastructure/issues/2179
- https://github.com/2i2c-org/features/issues/25
- https://github.com/2i2c-org/infrastructure/issues/2369
- https://github.com/2i2c-org/infrastructure/issues/2242
- https://github.com/2i2c-org/infrastructure/issues/2243
- https://github.com/2i2c-org/infrastructure/issues/1850
- https://github.com/2i2c-org/infrastructure/issues/535
- https://github.com/2i2c-org/infrastructure/issues/1282
- https://github.com/2i2c-org/infrastructure/issues/53
- https://github.com/2i2c-org/infrastructure/issues/2107
- Example on requesting users authorize the github application for github auth in grafana: https://github.com/2i2c-org/infrastructure/issues/2323#issuecomment-1505721800, and another one from the jupyterhub github auth docs in https://infrastructure.2i2c.org/hub-deployment-guide/configure-auth/github-orgs/#granting-access-to-the-oauth-app

### jupyterhub/grafana-dashboards

- https://github.com/jupyterhub/grafana-dashboards/issues/66
- https://github.com/jupyterhub/grafana-dashboards/issues/62
- https://github.com/jupyterhub/grafana-dashboards/issues/64
- https://github.com/jupyterhub/grafana-dashboards/issues/65

### Prometheus

- https://github.com/2i2c-org/infrastructure/issues/2222
- https://github.com/2i2c-org/infrastructure/issues/2223
- https://github.com/2i2c-org/infrastructure/issues/1785
- https://github.com/2i2c-org/infrastructure/issues/1101
- https://github.com/2i2c-org/infrastructure/issues/1510

**Comment by yuvipanda** [comment]
I tried to collect RED metrics from all user notebooks, and found that it is a bit too much - tracked in the links in https://github.com/berkeley-dsep-infra/datahub/issues/1993. Prometheus crashes quickly.

However, I think we already do collect and store RED metrics from the hub, and nginx-ingress. We should expose these.

**Comment by colliand** [comment]
I learned about [RED metrics](https://www.infoworld.com/article/3638693/the-red-method-a-new-strategy-for-monitoring-microservices.html) today. 

Rate, Error, Duration

**Comment by consideRatio** [comment]
I think this may no longer relevant enough to keep open, most issues are closed.
