### ISSUE TITLE
Make sure we do not have any Pod Security Policies in our deployment

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2226]
We got this notice from AWS https://2i2c.freshdesk.com/a/tickets/456 about PSPs being deprecated and removed (see https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/ for more information).

We need to get rid of pod security policies before we can upgrade to 1.25. That's not happening right now, but should soon!

Right now, on AWS clusters (I used the openscapes one), we have the following:

```
NAME              PRIV    CAPS   SELINUX    RUNASUSER   FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
eks.privileged    true    *      RunAsAny   RunAsAny    RunAsAny    RunAsAny    false            *
support-grafana   false          RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,emptyDir,projected,csi,secret,downwardAPI,persistentVolumeClaim
```

And on GCP clusters:

```
NAME                    PRIV    CAPS   SELINUX    RUNASUSER   FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
gce.gke-metrics-agent   false          RunAsAny   RunAsAny    RunAsAny    RunAsAny    false            hostPath,secret,configMap
support-grafana         false          RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,emptyDir,projected,csi,secret,downwardAPI,persistentVolumeClaim
```

And on Azure cluster:

```
NAME                      PRIV    CAPS   SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
calico-kube-controllers   false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
calico-node               true           RunAsAny   RunAsAny           MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim,hostPath
calico-typha              false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
support-grafana           false          RunAsAny   RunAsAny           MustRunAs   MustRunAs   false            configMap,emptyDir,projected,csi,secret,downwardAPI,persistentVolumeClaim
tigera-operator           false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            hostPath,configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
```

So we don't have any in z2jh itself, but there is one in grafana - tracked in https://github.com/grafana/helm-charts/issues/1006. So we'd need that upstream fix there.

Everything else seems to be managed by the cluster itself, so probably not something we need to take action on. Specifically for the EKS one, AWS states in their email:

>  If you see the eks.privileged PSP in your cluster, it will be automatically migrated to PSS by Amazon EKS. No action is needed on your part.

I'd imagine something similar for Google and Azure.

## TODO

- [ ] Get https://github.com/grafana/helm-charts/issues/1006 fixed?
- [ ] Upgrade our grafana chart to that version

**Comment by consideRatio** [comment]
We are using the latest helm chart and they are still around, so we need to manually configure grafana to not try create these resources via `rbac.pspEnabled=false`.

### Related

- https://github.com/2i2c-org/infrastructure/issues/2182#issue-1576421237
