### ISSUE TITLE
Need to understand how cpu requests/limits impacts software in containers

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2228]
## Updated action points

- [x] Understand this situation
- [ ] Make this understanding be conveyed at least partially as part of documentation in a section related to 2i2c's node sharing configurations.

## Original issue

Kubernetes allows us to specify requests and limits for cpu and memory, but without a very clear understanding on how these influence containers, we can't make good decisions on what we declare.

### Key question

Can and is software like dask's `distributed` running in a k8s pod be aware of:
- contaier's cpu requests
- container's cpu limits
- node's cpu capacity

### Thought example 1

A user pod scheduled by itself on a 4 CPU node with a 0.1 CPU request and 2 CPU limit. What happens when the user runs a Python program using multiprocessing that starts four processes running Python code, each able to load one CPU?

Erik: I think 2 CPU is fully loaded. The Python program wasn't aware of the 0.1 request and 2 limit, and got throttled by the cpu limit.

### Thought example 2

Again a user pod scheduled by itself on a 4 CPU node with a 0.1 CPU request and 2 CPU limit. "Smart" software (dask?) decides somehow how to make use of the available CPU capacity to do work, is it possible that this software self constrains to 0.1 CPU (cpu request), 2 CPU (cpu limit), or 4 CPU (node capacity)?

Erik: I'm really not sure.

### Reading up

- [Kubernetes docs about requests and limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits)
- [Specifying only a limit is a shorthand for specifying request/limit to be the same](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits)
- [A k8s node running `kubelet` tasked to start a pod, starts containers using the container runtime, which on linux typically makes use of cgroups to enforce requests/limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run)
  - [CPU requests are often associated with weighting](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run), so if a 1 CPU request container and a 3 CPU request container competes to consume CPU on a 16 CPU node, the CPU request container will get three times more.

### Key question reformulated

Can and is software like dask's `distributed` be aware of properties about the `cgroup` it runs within?

### Reading up

- It seems [dask's `distributed` is cgroup aware](https://github.com/dask/distributed/issues/6894) in some form at least!
- [Kubernetes notes about cgroup v2](https://kubernetes.io/docs/concepts/architecture/cgroups/#check-cgroup-version)
- [Linux manual pages about cgroups](https://man7.org/linux/man-pages/man7/cgroups.7.html)
  > Control groups, usually referred to as cgroups, are a Linux kernel feature which allow processes to be organized into hierarchical groups whose usage of various types of resources can then be limited and monitored. The kernel's cgroup interface is provided through a pseudo-filesystem called cgroupfs.
- Inspecting `/sys/fs/cgroup/` is a way to inspect information about the current cgroup

### `cgroupfs` provides `/sys/fs/cgroup/` - inspection of cgroup v1

```shell
ls -alh /sys/fs/cgroup
total 0
dr-xr-xr-x 13 root root 340 Feb 18 12:21 .
drwxr-xr-x  7 root root   0 Feb 18 12:21 ..
drwxr-xr-x  2 root root   0 Feb 18 12:21 blkio
lrwxrwxrwx  1 root root  11 Feb 18 12:21 cpu -> cpu,cpuacct
drwxr-xr-x  2 root root   0 Feb 18 12:21 cpu,cpuacct
lrwxrwxrwx  1 root root  11 Feb 18 12:21 cpuacct -> cpu,cpuacct
drwxr-xr-x  2 root root   0 Feb 18 12:21 cpuset
drwxr-xr-x  2 root root   0 Feb 18 12:21 devices
drwxr-xr-x  2 root root   0 Feb 18 12:21 freezer
drwxr-xr-x  2 root root   0 Feb 18 12:21 hugetlb
drwxr-xr-x  2 root root   0 Feb 18 12:21 memory
lrwxrwxrwx  1 root root  16 Feb 18 12:21 net_cls -> net_cls,net_prio
drwxr-xr-x  2 root root   0 Feb 18 12:21 net_cls,net_prio
lrwxrwxrwx  1 root root  16 Feb 18 12:21 net_prio -> net_cls,net_prio
drwxr-xr-x  2 root root   0 Feb 18 12:21 perf_event
drwxr-xr-x  2 root root   0 Feb 18 12:21 pids
drwxr-xr-x  2 root root   0 Feb 18 12:21 systemd
```

- **Memory requests**
  I don't think this is mapped to `cgroupfs`, but its relevant during pod scheduling (and pod eviction if a node is under memory pressure)
- **Memory limits**
  I think this is directly mapped to `memory/memory.limit_in_bytes`, and if no limit is provided this value is extremly large (9 exabytes).
- **CPU requests**
  I think this is directly mapped to `cpu/cpu.shares`, representing the amount of milli-cores requested.
- **CPU limits**
  CPU limits are enforced during a period of time, typically 100 ms or 100 000 μs, read via `cpu/cpu.cfs_period_us`. The `cpu/cpu.cfs_quota_us` relates to the limit. When a limit isn't set, this value is `-1`.

### Related

- #2121

**Comment by consideRatio** [comment]
### Key question branch 1 - `distributed` code inspection

- Is dask's distributed making decisions based on `cpu.shares` from `/sys/fs/cgroup/cpu` that makes us want to set it as high as possible when sharing for example 1/32 of a node's capacity?
- Is dask's distributed making decisions based on `cpu/cpu.cfs_quota_us` making us want to declare it to something like the node's capacity instead of not setting it?

### Related

- [`dask.system` exports `CPU_COUNT` based on a calculation using `cpu/cpu.cfs_period_us` and `cpu/cpu.cfs_quota_us`](https://github.com/dask/dask/blob/0eb4bd0b13e34a9aeb863985480359336ec9e7ab/dask/system.py#L13-L50)

**Comment by consideRatio** [comment]
> ### Key question
> Can and is software like dask's `distributed` running in a k8s pod be aware of:
> 
> * contaier's cpu requests
> * container's cpu limits
> * node's cpu capacity


Yes, yes, and yes.

- Is `distributed` hampered by a low cpu request? I don't think so.

**Comment by consideRatio** [comment]
### Action points

- [ ] Make this understanding be conveyed at least partially as part of documentation in a section about node sharing.

**Comment by damianavila** [comment]
Wow, the fact that dask's distributed is aware of the node CPU capacity is quite interesting!!
I have seen things like that before... I mean from inside the container see some node properties, but I have not seen software purposely be aware of that!

**Comment by consideRatio** [comment]
Too hard to be actionable about.
