### ISSUE TITLE
[Non active][Incident] openscapes: some Chrome users unable to login with GitHub authentication

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2249]
### Summary

User report via freshdesk  Failure to login using GitHub authentication

### Impact on users

Impacted users unable to access service.

### Important information

Here are the steps that reporter has been taken to alleviate their problem. I have tried using both a Mac and Windows OS.

- Cleared cookies
- Logged off VPN
- Tried wifi connections without firewalls
- Repeated the login process using a different computer
- Tried using incognito mode
- Revoking my authorization in GitHub
- The administrator, Julie ( also tried revoking my authorization

- Hub URL: http://oppenscapes.2i2c.cloud
- Support ticket ref: https://2i2c.freshdesk.com/a/tickets/483

### Tasks and updates

- [ ] Discuss and address incident, leaving comments below with updates
- [ ] Incident has been dealt with or is over
- [ ] Copy/paste the after-action report below and fill in relevant sections
- [ ] Incident title is discoverable and accurate
- [ ] All actionable items in report have linked GitHub Issues

<details>
<summary>After-action report template</summary>

```
# After-action report

These sections should be filled out once we've resolved the incident and know what happened.
They should focus on the knowledge we've gained and any improvements we should take.

## Timeline

_A short list of dates / times and major updates, with links to relevant comments in the issue for more context._

All times in {{ most convenient timezone}}.

- {{ yyyy-mm-dd }} - [Summary of first update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of another update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of final update](link to comment)


## What went wrong

_Things that could have gone better. Ideally these should result in concrete
action items that have GitHub issues created for them and linked to under
Action items._

- Thing one
- Thing two

## Where we got lucky

_These are good things that happened to us but not because we had planned for them._

- Thing one
- Thing two

## Follow-up actions

_Every action item should have a GitHub issue (even a small skeleton of one) attached to it, so these do not get forgotten. These issues don't have to be in `infrastructure/`, they can be in other repositories._

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]
```

</details>

**Comment by pnasrat** [comment]
Tested logging in as 2i2c user

```
[I 2023-02-24 11:44:16.223 JupyterHub log:186] 302 GET /hub/ -> /hub/login?next=%2Fhub%2F (@192.168.61.164) 0.50ms
[I 2023-02-24 11:44:16.302 JupyterHub log:186] 200 GET /hub/login?next=%2Fhub%2F (@192.168.61.164) 1.53ms
[I 2023-02-24 11:44:26.611 JupyterHub oauth2:102] OAuth redirect: 'https://openscapes.2i2c.cloud/hub/oauth_callback'
[I 2023-02-24 11:44:26.612 JupyterHub log:186] 302 GET /hub/oauth_login?next=%2Fhub%2F -> https://2i2c.us.auth0.com/authorize?response_type=code&redirect_uri=https%3A%2F%2Fopenscapes.2i2c.cloud%2Fhub%2Foauth_callback&client_id=EUrqVAOXWFF34lNEHGjrE7ie0SWgt1Vs&state=[secret]&scope=openid+name+profile+email (@192.168.61.164) 1.20ms
[I 2023-02-24 11:44:27.853 JupyterHub base:819] User logged in: pnasrat
[I 2023-02-24 11:44:27.853 JupyterHub log:186] 302 GET /hub/oauth_callback?code=[secret]&state=[secret] -> /hub/ (@192.168.61.164) 721.55ms
[I 2023-02-24 11:44:27.956 JupyterHub log:186] 302 GET /hub/ -> /hub/spawn (pnasrat@192.168.61.164) 7.35ms
[I 2023-02-24 11:44:28.045 JupyterHub log:186] 200 GET /hub/spawn (pnasrat@192.168.61.164) 7.46ms
[I 2023-02-24 11:44:28.088 JupyterHub oauth2:102] OAuth redirect: 'https://openscapes.2i2c.cloud/hub/oauth_callback'
[I 2023-02-24 11:44:28.089 JupyterHub log:186] 302 GET /hub/oauth_login?next=%2Fhub%2F -> https://2i2c.us.auth0.com/authorize?response_type=code&redirect_uri=https%3A%2F%2Fopenscapes.2i2c.cloud%2Fhub%2Foauth_callback&client_id=EUrqVAOXWFF34lNEHGjrE7ie0SWgt1Vs&state=[secret]&scope=openid+name+profile+email (pnasrat@192.168.61.164) 2.10ms
[I 2023-02-24 11:44:29.224 JupyterHub base:819] User logged in: pnasrat
[I 2023-02-24 11:44:29.225 JupyterHub log:186] 302 GET /hub/oauth_callback?code=[secret]&state=[secret] -> /hub/ (pnasrat@192.168.61.164) 665.68ms
[I 2023-02-24 11:44:29.378 JupyterHub log:186] 302 GET /hub/ -> /hub/spawn (pnasrat@192.168.61.164) 1.55ms
[I 2023-02-24 11:44:29.463 JupyterHub log:186] 200 GET /hub
```

**Comment by pnasrat** [comment]
hub is using Auth0 https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/configure-auth/auth0.html

**Comment by pnasrat** [comment]
User account appears to be `@jessnicwelch` and hub username matches see below

https://github.com/jessnicwelch

![image](https://user-images.githubusercontent.com/13798/221178306-cf51c1b3-a83c-4da1-a027-9a62e15a2c53.png)

**Comment by pnasrat** [comment]
I see other users logged in that were created > 1year ago but both the users referenced in the issue `@michele-ornl` and `@jessnicwelch` have never logged in user details for reporting user a

```
admin	false
auth_state	
created	7 days ago
groups	
kind	user
last_activity	
name	jessnicwelch
pending	
roles	user
server
```

**Comment by pnasrat** [comment]
Can create the users server manuallyu which updates last_activity.

**Comment by pnasrat** [comment]
Current hub `I 2023-02-24 10:51:26.009 JupyterHub app:2810] Running JupyterHub version 3.1.1` started will try see if can find older logs, but unlike GCP I don't think pod logs go to cloudwatch

**Comment by pnasrat** [comment]
Great find @GeorgianaElena - in particular this looks comment in a linked issue lists a possible workaround (if you haven't found already) 

https://github.com/jupyterhub/jupyterhub/issues/3162#issuecomment-689668002

The issue wondering if the users who are experiencing login failure are going through a site that embeds the hub in an iframe, vs when you tried directly to the hub url with your test user.

**Comment by GeorgianaElena** [comment]
Still unable to replicate :/

**Comment by GeorgianaElena** [comment]
I was thinking to try to propose them to logout out of everything:
- hub at https://openscapes.2i2c.cloud/logout
- Auth0 at https://2i2c.us.auth0.com/v2/logout
- GitHub at https://github.com/logout

The login into the hub following directly the URL https://openscapes.2i2c.cloud and then check if the 400 shows up again and try to get info out of the logs. Unfortunately I don't have any smarter ideas :(
what do you think?

**Comment by pnasrat** [comment]
@GeorgianaElena I think that proposal makes sense as it isn't impacting all users and we can't replicate. Given we don't retain logs and they may be in a TZ where we won't be around is it worth me adding something that captures the logs and run over the weekend. It's probably easiest to use AmazonCloudWatch and FluentBit

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs-FluentBit.html

**Comment by pnasrat** [comment]
Need to add role have done for `eksctl-openscapeshub-nodegroup-co-NodeInstanceRole-1FXJRCFQQ4P4F`

```
Attaching a policy to the IAM role of your worker nodes

Follow these steps to attach the policy to the IAM role of your worker nodes. This works for both Amazon EKS clusters and Kubernetes clusters outside of Amazon EKS.

To attach the necessary policy to the IAM role for your worker nodes
Open the Amazon EC2 console at https://console.aws.amazon.com/ec2/.

Select one of the worker node instances and choose the IAM role in the description.

On the IAM role page, choose Attach policies.

In the list of policies, select the check box next to CloudWatchAgentServerPolicy. If necessary, use the search box to find this policy.

Choose Attach policies.
```

**Comment by pnasrat** [comment]
Having added the roles we now have logs (set to 2w retention for now as this is temp debugging)

Got to cloudwatch in console, log insights, choose the log group `/aws/containerinsights/openscapeshub/applicatio`

query language example 

```
fields @timestamp, @message, @logStream, @log
| filter kubernetes.pod_name like /hub/
| filter @message like /pnasrat/
| sort @timestamp desc
| limit 20
```

Tutorial https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData_RunSampleQuery.html

Syntax docs: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax.html

**Comment by pnasrat** [comment]
Note this related issue for EKS permissions in console https://aws.amazon.com/premiumsupport/knowledge-center/eks-kubernetes-object-access-error/

**Comment by pnasrat** [comment]
The log does retnurn OAuth state mismatch 

```
[W 2023-02-24 17:18:11.625 JupyterHub oauth2:151] OAuth state mismatch:  [secret1] != [secret2]
```

**Comment by consideRatio** [comment]
I logged in as a newly added user `consideratio-demo` in an incognito window, and everything worked out. I really don't understand what is going on.

I'd expect any issues with the OAuth2 client's registered with JupyterHub->Auth0 and Auth0->GitHub should have been erroring systematically if there was any such issue.

---

Hmm... I visit using `openscapes.2i2c.cloud`. Is this possibly an issue related to arriving to the hub using a different domain name or similarly?

I doubt it, I'm just throwing out anything I can imagine to cause a "OAuth state mismatch" error which I don't really understand well.

**Comment by consideRatio** [comment]
https://github.com/jupyterhub/oauthenticator/blob/5e3007841f23a8415e0d9cc6e11af9de056a5793/oauthenticator/oauth2.py#LL139-L152C61

```python
    def check_state(self):
        """Verify OAuth state
        compare value in cookie with redirect url param
        """
        cookie_state = self.get_state_cookie()
        url_state = self.get_state_url()
        if not cookie_state:
            raise web.HTTPError(400, "OAuth state missing from cookies")
        if not url_state:
            raise web.HTTPError(400, "OAuth state missing from URL")
        if cookie_state != url_state:
            self.log.warning(f"OAuth state mismatch: {cookie_state} != {url_state}")
            raise web.HTTPError(400, "OAuth state mismatch")
```

**Comment by consideRatio** [comment]
I think what happens is that a state is set at some point by the OAuthenticator class, and then the user is redirected around, and finally the user is arriving back using some URL where its expected to have the same state in the cookie as in the URL.

https://github.com/jupyterhub/oauthenticator/blob/5e3007841f23a8415e0d9cc6e11af9de056a5793/oauthenticator/oauth2.py#LL104-L112C10

```python
        self.set_state_cookie(state)
        token_params["state"] = state
        self.authorize_redirect(
            redirect_uri=redirect_uri,
            client_id=self.authenticator.client_id,
            scope=self.authenticator.scope,
            extra_params=token_params,
            response_type="code",
        )
```

**Comment by yuvipanda** [comment]
Perhaps we can add them to a staging hub or something that uses github directly (instead of via auth0) to see if the issue persists there too? If it does, we can rule out auth0 as a potential source of the issue

**Comment by consideRatio** [comment]
Pris suggested trying with Firefox instead of Chrome:

> I can authenticate with Firefox. I hope that the Chrome issue can be resolved in the future as it’s my preferred browser.

Hmmm... Chrome extensions? But they are often disabled when using incognito right, so I think maybe that is an unlikeley cause.

**Comment by consideRatio** [comment]
I followed the requests a bit and conclude that the kind of state that the jupyterhub expect is a base64 encoded JSON string starting with `{` -> `ey...`, while I saw the same `hK` state for the auth0 section.

I think the OAuth involved between auth0->github ended up overriding the `state` query parameter of relevance the OAuth involved between jupyterhub->auth0 based on recognizing the state being passed around.

This is based on seeing how my successful login request set a cookie state of `ey...` and got it returned, while when the 400 surfaced, it was a mismatch between `ey...` and `hK...` as summarized in https://2i2c.slack.com/archives/C028WU9PFBN/p1677263372689249.

**Comment by pnasrat** [comment]
I think as we understand the issue is limited to some subset of chrome users with workaround to use another browser we should split off an investigation into understanding if it is an upstream jupyterhub issue, the integration with auth0 to enable use to close the incident. That would allow us to prioritize a more substantial fix alongside the rest of our sprint work. 

This should include writing up a support snippet/canned response with a set of steps users can take when get auth failures that users can take to help us diagnose other auth issues

I'm not sure if we need an After-action report or incident write up in this case as it is a bug rather than an incident.

**Comment by yuvipanda** [comment]
I think @GeorgianaElena is working on getting rid of auth0 completely from our infrastructure, which might affect this too. I wonder if we can have this person test using a non-auth0 github integration to see if auth0 is the problem? One of our staging servers perhaps?

**Comment by pnasrat** [comment]
I'm happy to work with @GeorgianaElena to move from auth0 auth in the openscapes staging and ask the user to retest in Chrome.

**Comment by pnasrat** [comment]
Waiting for #2277

**Comment by pnasrat** [comment]
Migration to CILogin worked for the user logging in to the hub on chrome.

**Comment by pnasrat** [comment]
Cleaned up logging to leave cluster in standard state

```
kubectl delete  -f cloudwatch-logs-openscapes.yaml 
namespace "amazon-cloudwatch" deleted
serviceaccount "cloudwatch-agent" deleted
clusterrole.rbac.authorization.k8s.io "cloudwatch-agent-role" deleted
clusterrolebinding.rbac.authorization.k8s.io "cloudwatch-agent-role-binding" deleted
configmap "cwagentconfig" deleted
daemonset.apps "cloudwatch-agent" deleted
configmap "fluent-bit-cluster-info" deleted
serviceaccount "fluent-bit" deleted
clusterrole.rbac.authorization.k8s.io "fluent-bit-role" deleted
clusterrolebinding.rbac.authorization.k8s.io "fluent-bit-role-binding" deleted
configmap "fluent-bit-config" deleted
daemonset.apps "fluent-bit" deleted
```

**Comment by consideRatio** [comment]
Is this github accounts added manually? They shouldnt include the @ sign if so - adding users without it should do the trick

**Comment by jules32** [comment]
Hi @consideRatio, thanks for your suggestion. I removed that `@` sign, which I hadn't caught before. Thank you!

Unfortunately that didn't solve it. @stefaniebutland has cleared cookies and is still getting the same **403: Forbidden** message. Having cleared cookies she did see this screen and then it prompted her to validate her GitHub username by authorizing in app on her phone

![Screenshot 2023-05-09 at 3 13 16 PM](https://github.com/2i2c-org/infrastructure/assets/5891909/d88264b1-ad07-49ce-972d-dcdddc904882)

**Comment by yuvipanda** [comment]
@jules32 can you have them try to go to https://openscapes.2i2c.cloud/hub/logout (to logout from the hub) and then try login again?

**Comment by stefaniebutland** [comment]
Hi @yuvipanda. [openscapes.2i2c.cloud/hub/logout](https://openscapes.2i2c.cloud/hub/logout) takes me directly to login page with no prompt for action, then clicking "login to continue" takes me directly to 403 : Forbidden

**Comment by consideRatio** [comment]
Hmmmm, Yuvi i think we cant add users via the hub/admin ui to indicate they are allowed, its not somethonly make users admin.

**Comment by stefaniebutland** [comment]
Success!! I'm now logged in. Thanks so much.

For NASA Openscapes Champions, we will collect a list of GitHub usernames and the plan was that @jules32 would add them as she did mine.
