### ISSUE TITLE
Alerts for when our clusters will use up more than forecasted amount of $$$

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#2266]
### Context

We don't have a good forecasting system yet either, but we should at least know beforehand if a ton of money is gonna get used up. And this should also be provided with enough lead time

Ref: https://github.com/2i2c-org/infrastructure/pull/1782
Parent issue: https://github.com/2i2c-org/infrastructure/issues/1804

**Comment by yuvipanda** [comment]
Replaced by https://github.com/2i2c-org/meta/issues/1239
