### ISSUE TITLE
Prepare Q2 2023 Engineering goals

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#2269]
### Context

Let's agree and prepare/refine the goals we want to pursue in Q2.
And let's make that plan happen before Q2 starts!!

### Proposal

I have signaled a few proto-Q2 goals in https://github.com/2i2c-org/infrastructure/issues/2122 (and previous goal issues).

* Monitoring and alerts: https://github.com/2i2c-org/infrastructure/issues/1804#issuecomment-1446389660 (1)
* Billing: https://github.com/2i2c-org/infrastructure/issues/1853#issuecomment-1446409761 (2)
* Dynamic image building: https://github.com/2i2c-org/infrastructure/issues/2120 (3)

That is essentially a mix of making our infra more robust (1), recovering back some money (2), and building something new (3).

I am open to discussing and bringing up other things, but I think we need to collectively focus on more concrete goals. These topics are already big ones, so I am proposing to aim for small improvements on each of those topics! And those concrete small steps should be well specified before we enter the next quarter.

cc @2i2c-org/engineering so we start dropping ideas!!

### Updates and actions

For the Q2 goals definition, we followed the process outlined in https://github.com/2i2c-org/team-compass/issues/697.

Our notes about this process live in the Prod and Eng meeting notes:
* 21/3: https://docs.google.com/document/d/1dUO2USQlRbcjOEkjlCu1gyTaPBZmGZSRF4L-_9xecmA/edit#heading=h.n1c8g3lu1cuy
* 28/3: https://docs.google.com/document/d/1dUO2USQlRbcjOEkjlCu1gyTaPBZmGZSRF4L-_9xecmA/edit#heading=h.ycnyhh6g1ri6
* 4/3: https://docs.google.com/document/d/1dUO2USQlRbcjOEkjlCu1gyTaPBZmGZSRF4L-_9xecmA/edit#heading=h.xtkt0wlnotkd

**Comment by damianavila** [comment]
# Monitoring and alert

Non-paging ticket alerts (idea from @pnasrat): https://github.com/2i2c-org/infrastructure/issues/2288#issuecomment-1451747723 and slack discussion: https://2i2c.slack.com/archives/C01GLCC1VCN/p1677759173803229?thread_ts=1677746693.014559&cid=C01GLCC1VCN.

**Comment by consideRatio** [comment]
@damianavila I opened https://github.com/2i2c-org/infrastructure/issues/2293 as a goal proposal for Q2.

I also think it would be very valuable if we could make node sharing a default and help hubs transition towards it, but I'd like to not outline that in more detail right now, but its represented by #2121.

**Comment by choldgraf** [comment]
@damianavila I believe that this process is now complete, so I'm going to close the issue. Let me know if you wanted to keep it open throughout the sprint or something, but I believe that these goals are now incorporated into the strategic objectives board: https://github.com/orgs/2i2c-org/projects/34/views/7

**Comment by damianavila** [comment]
I also have captured our Eng goals in the Eng board: https://github.com/orgs/2i2c-org/projects/22/views/50.
And for the record, all the planning around Q2 goals lives in the following document: https://docs.google.com/document/d/1dUO2USQlRbcjOEkjlCu1gyTaPBZmGZSRF4L-_9xecmA/edit#heading=h.ycnyhh6g1ri6
