### ISSUE TITLE
AWS: draft notes on getting local CLI access with a temporary session token

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2301]
It is not obvious to me how to get credentials to work against an AWS account that enforces use of MFA on the CLI level, but below is the procedure I've followed outlined.

### Action point

- [ ] Collectively refine or confirm how to go about this
- [ ] Document this

### How I've went about it so far

I've tried the following, but only for `nasa-veda`'s AWS account.

1. Setup CLI access like if MFA wasn't enforced via [these 2i2c docs on aws account access](https://infrastructure.2i2c.org/en/latest/topic/access-creds/cloud-auth.html#aws-access)
   It could be that if we can use AWS SSO via https://2i2c.awsapps.com/start#/, that we get valid MFA tokens directly. I'm not sure.
2. Look up the AWS IAM users associated MFA device's serial number
   Visit the AWS cloud console, go to IAM -> Users -> username -> Security credentials tab -> Multi-factor authentication (MFA) -> Read the identifier, should be for example `arn:aws:iam::111222333444:mfa/my-pixel3a-mobile`
3. Use `aws sts get-session-token` like this:
   ```
   MFA_DEVICE_SERIAL_NUMBER=arn:aws:iam::111222333444:mfa/my-pixel3a-mobile
   aws sts get-session-token --serial-number=$MFA_DEVICE_SERIAL_NUMBER --token-code=<just-in-time-generated-code-from-mfa-device>
   ```

**Comment by yuvipanda** [comment]
Here's the script I just made for this, specific to nasa-veda and my MFA:

```
#!/bin/zsh
MFA_TOKEN=${1}

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY

export AWS_PROFILE=nasa-veda
export MFA_DEVICE_ID=arn:aws:iam::444055461661:mfa/phone 

SESSION_CREDS=$(aws sts get-session-token --serial-number ${MFA_DEVICE_ID} --token-code ${MFA_TOKEN})

export AWS_ACCESS_KEY_ID=$(echo ${SESSION_CREDS} | jq -r .Credentials.AccessKeyId)
export AWS_SECRET_ACCESS_KEY=$(echo ${SESSION_CREDS} | jq -r .Credentials.SecretAccessKey)
export AWS_SESSION_TOKEN=$(echo ${SESSION_CREDS} | jq -r .Credentials.SessionToken)
```

I can then call this as `source nasa-veda-mfa.bash <mfa-code>`

**Comment by consideRatio** [comment]
This what was I used

```
function nasa_esdis () {
    export CLUSTER_NAME=nasa-esdis
    export AWS_PROFILE=$CLUSTER_NAME
    export TF_WORKSPACE=$CLUSTER_NAME
    echo Setting CLUSTER_NAME and TF_WORKSPACE to $CLUSTER_NAME
    CODE=$1
    TMP=$(aws sts get-session-token --profile $CLUSTER_NAME --serial-number arn:aws:iam::942325726017:mfa/mobile-authy --token-code $CODE)
    export AWS_ACCESS_KEY_ID=$(echo $TMP | jq -r .Credentials.AccessKeyId)
    export AWS_SECRET_ACCESS_KEY=$(echo $TMP | jq -r .Credentials.SecretAccessKey)
    export AWS_SESSION_TOKEN=$(echo $TMP | jq -r .Credentials.SessionToken)
}
```
