### ISSUE TITLE
Remove NAT gateway option for our AWS clusters

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2313]
### Background

We received this email about the `nasa-cryo` cluster, probably we'll receive it for all AWS clusters we have coupled to the support email soon. I'm not sure if this is a relevant optimization for us, but maybe.

I understand that a NAT often helps translate a range of local IP addresses to one or more publicly available IP addresses. So, if the k8s nodes (representing pods on it) for example doesn't have public IPs themselves, they can route traffic through the NAT which has a public IP.

### Action points

- [ ] Dig into if this is relevant for us to consider in order to minimize cost

### Email

Hello,

We have observed that your Amazon VPC resources are using a shared NAT Gateway across multiple Availability Zones (AZ). To ensure high availability and minimize inter-AZ data transfer costs, we recommend utilizing separate NAT Gateways in each AZ and routing traffic locally within the same AZ.

Each NAT Gateway operates within a designated AZ and is built with redundancy in that zone only. As a result, if the NAT Gateway or AZ experiences failure, resources utilizing that NAT Gateway in other AZ(s) also get impacted. Additionally, routing traffic from one AZ to a NAT Gateway in a different AZ incurs additional inter-AZ data transfer charges. We recommend choosing a maintenance window for architecture changes in your Amazon VPC.

The following is a list of your VPCs and NAT Gateways that are shared across AZ(s), in the format: 'VPC | NAT Gateway':

vpc-052f77e7a342aef18 | nat-080955a4715fbb99b

Please refer to the AWS public documentation on how to create a NAT Gateway [1], and how to configure routes for different NAT Gateway use cases [2].

Should you have any questions or concerns, please reach out to the AWS Support team [3].

[1] https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html#nat-gateway-working-with
[2] https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-scenarios.html
[3] https://aws.amazon.com/support

Sincerely,
Amazon Web Services

Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210

---
Reference: https://phd.aws.amazon.com/phd/home?region=us-east-1#/event-log?eventID=arn:aws:health:us-west-2::event/NATGATEWAY/AWS_NATGATEWAY_OPERATIONAL_NOTIFICATION/AWS_NATGATEWAY_OPERATIONAL_NOTIFICATION_f0c13ac4fdcc0cb01ff9db978e82a47681aa7ab6ad87020e5cf690603775e81a&amp;eventTab=details

**Comment by yuvipanda** [comment]
I took a quick look at this, looks like we're being charged about 5$ for NAT gateways per cluster

<img width="483" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/cec0aab5-cc89-42aa-82b1-fee2b87c584c">

We don't actually use this, as all our nodegroups are public instances than private instances. We can disable it (https://eksctl.io/usage/vpc-configuration/#nat-gateway), and probably should.

**Comment by consideRatio** [comment]
> Note: Specifying the NAT Gateway is only supported during cluster creation. It isn't touched during a cluster upgrade. There are plans to support changing between different modes on cluster update in the future.

With that in mind, I opened a PR to make us not get setup with a NAT gateway by default for new clusters - #4412.

**Comment by consideRatio** [comment]
To review that something works is relatively easy, but here to review that nothing changes in any circumstance by disabling this is notably harder.

I'm inclined to say we close this issue and #4412 without further action as the cost is relatively low (~5 USD/month) for the AWS clusters, and the cost of doing work to figure out a discrepancy between clusters were we end up realizing we actually need it in some situations may be high.

I'm almost confident nothing changes in any circumstance, but am I confident enough?

I can forsee situations where we would like to make some cluster able to egress traffic from a specific IP in order to allow list that specific IP for being allowed to connect to a external database for example, then the NAT gateway may be relevant.

Tricky... I'll go for a close.
