### ISSUE TITLE
Revise uptime check configuration as exceed free quota

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2320]
### Context

We have 92 checks every 5 minutes from 6 regions (US = 3 by self)

```
So (24*60/5) * 92 *  6 * 30 = 4769280
$0.30/1,000 executions (free monthly allotment is in theory 1 million executions per Google Cloud project, however these are all in one project)
4769280-1000000 = 3769280
```

Pricing from October 1 2022 monitoring uptime checks are charged
https://cloud.google.com/stackdriver/pricing

### Proposal

Back of the envelope calculation for a 100 hubs to give num checks per hour to fit in free tier

```math
\begin{equation}
x = \cfrac{1e6}{(100*24*31*3)}
\end{equation}
=4.48
```

**Comment by pnasrat** [comment]
See https://cloud.google.com/monitoring/uptime-checks#monitoring_uptime_check_create-api for region list 

We currently check from all 6:

-  usa-virginia
-  usa-oregon
-  usa-iowa
-  eur-belgium
-  apac-singapore
-  sa-brazil-sao_paulo

**Comment by pnasrat** [comment]
Created draft PR to consider - need to confirm the selected_regions use in terraform is correct

**Comment by pnasrat** [comment]
Breaking down my other changes

`google_monitoring_uptime_check_config.period: ="900s"`

[period](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_uptime_check_config#period)- (Optional) How often, in seconds, the uptime check is performed. Currently, the only supported values are 60s (1 minute), 300s (5 minutes), 600s (10 minutes), and 900s (15 minutes). Optional, defaults to 300s.

`google_monitoring_alert_policy.duration = "1860s"`

[duration](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#duration) - (Required) The amount of time that a time series must fail to report new data to be considered failing. Currently, only values that are a multiple of a minute--e.g. 60s, 120s, or 300s --are supported.

`google_monitoring_alert_policy.aggregations.alignment_period = "900s"` https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#alignment_period

**Comment by pnasrat** [comment]
Old apparently fixed issue re this https://github.com/hashicorp/terraform-provider-google/issues/3132

**Comment by pnasrat** [comment]
API docs and web ui state 15m period is valid

Web ui allows update vs terraform config

![image](https://user-images.githubusercontent.com/13798/224070165-3211b8bd-11c9-41ef-a3ed-761e06af521b.png)

**Comment by pnasrat** [comment]
Just reducing the regions in #2330 rolled out successfully and should half our costs

https://github.com/2i2c-org/infrastructure/actions/runs/4384589522/jobs/7676245979

Will validate my testing of destroy/create for period changes, test, document, and create a new PR and deployment plan to get out safely.

**Comment by pnasrat** [comment]
See below that only checking from one region (3 locations)

![image](https://user-images.githubusercontent.com/13798/224328689-ce2b8550-4d22-4eed-ad62-dacf378dcebc.png)

**Comment by pnasrat** [comment]
As of this morning checks are running every 15 minutes from the 3 US locations. This should make us closer to the free quota. As we are already halfway through march we are already over, but should be much lower on stackdriver costs. 


https://console.cloud.google.com/monitoring/uptime/

**Comment by damianavila** [comment]
AFAIK, all relevant PRs are being merged and changes are deployed, so going to close this one.

@pnasrat, this is awesome (and super impactful)!
Thanks for pushing forward on this important "on the fly" task that you have "discovered" during the current sprint.
