### ISSUE TITLE
nasa-cryo: setup shared folder for all users to read/write to

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2350]
In https://2i2c.freshdesk.com/a/tickets/543 Tasha Snow asked for a shared folder that all users can read/write to by April 25th.

In the support ticket I'll ask for a wished name of this folder.

**Comment by pnasrat** [comment]
Update from support ticket https://2i2c.freshdesk.com/a/tickets/543

Folder name:  public-readwrite

**Comment by yuvipanda** [comment]
done in https://github.com/2i2c-org/infrastructure/pull/2384
