### ISSUE TITLE
[Support] nasa-veda: remove small option, set min_nodes to 1 for medium node pool

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2352]
There was a request in https://2i2c.freshdesk.com/a/tickets/502 for faster node startups etc, so I proposed that we keep a node running at all times.

### Action points

- [ ] `nasa-veda` is a EKS based cluster, so we need to handle #2351 for this
- [ ] Remove the small option and node pool
- [ ] Communicate back to Greg in https://2i2c.freshdesk.com/a/tickets/502

**Comment by yuvipanda** [comment]
@batpad something for you to look at and see if this is to be done.

**Comment by yuvipanda** [comment]
Yeah, let's move it @batpad and I can close this here.

**Comment by batpad** [comment]
@yuvipanda moved issue: https://github.com/NASA-IMPACT/veda-jupyterhub/issues/31 - feel free to close here - thank you.
