### ISSUE TITLE
Systematically setup redirects for x.2i2c.cloud to community specified domain names

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2356]
I believe we don't yet have practices regarding custom domain names as provided by the communities. Among handling custom domain names, I appreciate what @pnasrat did for the new QCL hub.

@pnasrat made use of the support chart's templates configured via `redirects` values to render additional Ingress resources that our ingress controller would use to redirect for example `staging.qcl.2i2c.cloud` to `staging.quantifiedcarbon.com`. Like this, we as 2i2c engineers doesn't have to remember the hubs custom domain names!

I think by doing this, we can avoid some complexity of remembering domain names for us in 2i2c mostly, but we also add a bit of extra chore work. I've found myself very often looking in cluster.yaml to know what URL to visit, but that is perhaps acceptable. I think I'd rather do some extra chore work for each hub to never have to remember custom domain names as the amount of clusters we handle grow.

### Action point

- [ ] Go through all clusters and their defined hubs and look for custom domain names
- [ ] If needed, add A or CNAME records via namecheap.com for `<something>.2i2c.cloud`, and then configure clusters' support charts via `redirects` to redirect from a `<something>.2i2c.cloud` domain to the community preferred domain name.

**Comment by pnasrat** [comment]
I based my config off UToronto and the docs here

https://infrastructure.2i2c.org/en/latest/howto/manage-domains/index.html

**Comment by yuvipanda** [comment]
This is now codified as part of https://github.com/2i2c-org/infrastructure/pull/3683 for any new hubs we set up.

**Comment by consideRatio** [comment]
Closing as stale for now
