### ISSUE TITLE
Audit 2i2c + community image use for Docker Hub risk due to removal of Free Team orgs.

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2361]
### Context

Docker, Inc. has announced it is stopping supporting Orgs (ie open source communites) free usage of Docker Hub on April 14, 2023.  This heavily impacts OSS communities and could mean risk when they start deleting repos - cf other forms of [dependency attachs such as on PyTorch](https://pytorch.org/blog/compromised-nightly-dependency/)

https://news.itsfoss.com/docker-dropping-free-team-orgs/

https://twitter.com/alexellisuk/status/1635679295891812359

### Proposal

We should audit current image usages across deployments to ensure all images are on quay.io, github, or other (eg private repositories). Upstreams may also be moving so we should ensure images are updated to the correct repository. 

This might involve needing to liase with communities who build and push their own images.

**Comment by pnasrat** [comment]
Maybe something like the following PromQL

`count by (namespace,image)(kube_pod_container_info{})`

**Comment by sgibson91** [comment]
A follow-up announcement was made which may answer some questions https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

**Comment by yuvipanda** [comment]
We have been slowly just moving people to quay.io wherever possible. I think we can close this one out.
