### ISSUE TITLE
daskhub: prometheus scraping of worker pods?

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2366]
I see from our dask-gateway client configuration, we make annotate our worker pods to be scraped. Is that used by us? If not, we should not do this because prometheus can easily be overloaded with scraping work I think. Especially if someone starts 100-1000 workers with 100 or so nodes that also have node metrics to be scraped.

https://github.com/2i2c-org/infrastructure/blob/cf7bfc3778001791bd83472b943fc695ea5e314d/helm-charts/daskhub/values.yaml#L189-L190

**Comment by consideRatio** [comment]
pangeo-hubs have a prometheus-server with 20Gi memory request/limit, but they ran out of it recently again. I couldn't increase it further enough, so I whiped it clean by removing the PV and PVC.

pangeo-hubs have n1-highmem-4 machines with memory specified to 26 GB as compared to the n2-highmem-4 machines with 32GB of memory. If we had n2-highmem-4 we could have increased the pod request quite a bit more, but we would run into issues in a matter of time - just like we will by resetting this.

I think pangeo-hubs heavy use of dask-gateway, where I saw ~200 nodes etc startup with probably significantly more k8s pods overloads our prometheus-servers in various ways in general. Prometheus-server will require a large unbounded amount of memory when that much logs has been scraped historically, and may become unresponsive if its scraping from 200 nodes's node-exporters and even more dask-worker pods.

If we stopped scraping the worker pods for metrics, we may avoid issues like this, maybe not. I'm not sure what metrics they emit.

**Comment by consideRatio** [comment]
### Action point

- [ ] Conclude what metrics dask-worker pods expose, and if we are presenting such metrics anyhow
- [ ] Make a decision to stop scraping metrics or not from them

**Comment by consideRatio** [comment]
I've concluded that prometheus-server is crashing during normal operation by being `OOMKilled` when its trying to bug failing to scrape huge amounts of things, which it does when loads of dask worker pods are running.

**Comment by yuvipanda** [comment]
> I couldn't increase it further enough, so I whiped it clean by removing the PV and PVC.

Does this mean we have lost all usage data for these hubs? In the future, if the PV is full, it can be resized (https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/)

**Comment by consideRatio** [comment]
@yuvipanda hmmm hmm wait, maybe not correct that we lost the data. The PV had `retain` I think. So the actual disk is retained somewhere when I deleted the PV, and we got a new?

**Comment by yuvipanda** [comment]
@consideRatio if possible, we should try to recover that, as without it reporting on how much the hub is used (and possibly justify further usage) is impossible :(

**Comment by consideRatio** [comment]
@yuvipanda hmmm so I was about to look into the cloud console and inspect what ID etc the disk had, but, its pangeo-hubs. I don't have access =/ I opened https://github.com/2i2c-org/infrastructure/issues/2688
