### ISSUE TITLE
Overview of NFS storage backup for disaster recovery

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2370]
I think backup of the NFS storage where user home directoires and shared folders are kept is reasonable to provide by default, but should at least be something we can offer users to opt-in to. Backup implies cost, so its not obvious in any way still. Further, if backup is wanted, its not obvious how frequent the backup should be made, when they should be made, and how long they should be kept around.

My understanding is that handling backups are complicated overall, and that we should perhaps prefer to rely on the cloud providers services we use to do it for us.

### Action points

I think we should start out by exploring the options a bit further. Once more technical overview is gained, we try to figure out what policies we could and think is reasonable to support for individual or all cloud providers.

- [ ] Explore the technical options available on AWS, GCP, and Azure and update the individual issues with the findings.
- [ ] Discuss the options feasebility with a technical implementation and maintenance perspective
- [ ] Discuss disaster recovery backup from a service perspective
  - Are all communities to have to some degree of disaster recovery backup, for example one weekly backup, even if it incurs cost?
  - How to introduce this to community representatives of existing and new hubs?

### Related issues

- https://github.com/2i2c-org/infrastructure/issues/624
- https://github.com/2i2c-org/infrastructure/issues/623
- https://github.com/2i2c-org/infrastructure/issues/2372

### Related support interactions

- [Ian at Callysto, 2023-03-17](https://2i2c.freshdesk.com/a/tickets/562) about making a backup before adjusting the core node pool.
- https://github.com/2i2c-org/infrastructure/issues/1238

**Comment by yuvipanda** [comment]
Superseeded by https://github.com/2i2c-org/infrastructure/issues/4390
