### ISSUE TITLE
cloudbank - logging API disabled meaning no GKE pod and container logs

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2386]
### Context

Not sure if this is deliberate but when investigating I'm not seeing much in the GKE logs (and it looks configured for system and workloads) for Cloudbank ccsf. Anyone any idea why k8s_pod and k8s_container resource logging just seems to vanish unless I look further back in time

https://2i2c.freshdesk.com/a/tickets/567
https://cloudlogging.app.goo.gl/3WZVnnZmAxvZxPmF6

Via troubleshooting guide I see vs a working cluster logging API is not enabled https://cloud.google.com/kubernetes-engine/docs/troubleshooting/troubleshooting-gke-logging

```
 gcloud services list --enabled --filter="NAME=logging.googleapis.com"
Listed 0 items.
```

**Comment by pnasrat** [comment]
Web link for enabling is https://console.cloud.google.com/apis/library/logging.googleapis.com?project=cb-1003-1696 however I want to understand why this cluster differs. Possibly need to update https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/new-cluster/new-cluster.html

**Comment by yuvipanda** [comment]
I don't think this was intentional, I think we should enable it!

**Comment by pnasrat** [comment]
Auditing - Callysto, also required it enabled and I have done so but all other GCP projects have Cloud Logging API on. Doc update PR coming

**Comment by pnasrat** [comment]
Enabling made container logs come back. 
https://cloudlogging.app.goo.gl/S9Rz15drPUrG7KaAA

**Comment by pnasrat** [comment]
@consideRatio see the earlier link re costing for default retention of container logs 30 days it should be free https://cloud.google.com/stackdriver/pricing#logging-costs

Looking at [MEOM](https://console.cloud.google.com/billing/015AF3-346967-3DD18B/reports;timeRange=LAST_MONTH;grouping=GROUP_BY_SKU;projects=meom-ige-cnrs;skus=services%2F5490-F7B7-8DF6%2Fskus%2F143F-A1B0-E0BE?project=meom-ige-cnrs) or [LEAP](https://console.cloud.google.com/billing/01A164-923D17-3199D9/reports;timeRange=LAST_90_DAYS;grouping=GROUP_BY_SKU;skus=services%2F5490-F7B7-8DF6%2Fskus%2F143F-A1B0-E0BE?organizationId=184174754493&project=leap-pangeo) LEAP has a smalll log spike for a day or two in Feb that might be somethign unrelated but cost less than 3 dollars. I think this is safe from a cost risk on GCP at least

**Comment by consideRatio** [comment]
> @consideRatio see the earlier link re costing for default retention of container logs 30 days it should be free https://cloud.google.com/stackdriver/pricing#logging-costs

Yes but we still pay for the ingestion cost, 0.5 USD/GB of logs stashed away. I've seen this cost go up to over 1k USD due to a larger set of containers spamming logs.

**Comment by pnasrat** [comment]
Filed #2394 to enable APIs consistently through automation not through docs
