### ISSUE TITLE
Document terraform help from Yuvi someplace suitable

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2401]
**Erik wrote:**
```
(base) ➜  gcp git:(master) terraform init          

Initializing the backend...
╷
│ Error: Backend configuration changed
│ 
│ A change in the backend configuration has been detected, which may require migrating existing state.
│ 
│ If you wish to attempt automatic migration of the state, use "terraform init -migrate-state".
│ If you wish to store the current configuration with no changes to the state, use "terraform init -reconfigure".
╵
```

Should I do `terraform init -migrate-state` here? I'm not sure what this is about.

**Yuvi wrote:**

ah, look for hidden files in your current directory
you most likely do not want -migrate-state
this usually means terraform is not looking for state files where it should - which is on GCS remotely, but locally.

**Erik wrote:**
Ah
I moved away my found `.terraform` folder, and did (from `terraform/gcp`): `terraform init -backend-config=backends/default-backend.hcl`

---

This resolved the situation, but I don't understand the details here. What caused this? Had I made changes to terraform state that wasn't captured by the remote state or similar?

**Comment by yuvipanda** [comment]
> Had I made changes to terraform state that wasn't captured by the remote state or similar?

Most likely not, as terraform prints out this error precisely to prevent that from happening.

**Comment by yuvipanda** [comment]
I just ran into this again because I upgraded my terraform version.

**Comment by consideRatio** [comment]
Stale, going for a close.
