### ISSUE TITLE
Stop paying for auth0

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2422]
I think we pay some money to auth0 now. After @GeorgianaElena's work, we no longer need to! We should stop paying them.

**Comment by jmunroe** [comment]
I think @choldgraf is the only one with the admin/password for that ([reference](https://docs.google.com/spreadsheets/d/1NSaAKLG2_njXxs6JlGUAhSWeHONz9QSGLVwEK790IZo/edit?usp=sharing)).

Chris -- did you want to check if there is a automatically billed plan that need to be cancelled?

**Comment by GeorgianaElena** [comment]
With the permissions I have, I was able to switch the 2i2c subscription to the `free` plan 🎉 
<img width="729" alt="Screenshot 2023-03-29 at 14 11 12" src="https://user-images.githubusercontent.com/7579677/228516597-2b3f0e6d-c527-4070-a8cb-d97e74506570.png">

**Comment by colliand** [comment]
2i2c's ramp credit card was charged $23 on March 11. This leads me to expect that the next charge will take place during the second week of April. I suggest the following next steps:

- [ ] Engineering confirms Auth0 can be turned off (pending `jmte` question posed by @GeorgianaElena to @consideRatio above). Proposed deadline April 4.
- [ ] Auth0 payment is turned off by @choldgraf . Proposed deadline April 7.

**Comment by choldgraf** [comment]
Happy to turn it off when somebody pings me (please assign me to an issue or ping me directly on Slack, as if it's just a mention I'll likely miss it)

**Comment by consideRatio** [comment]
jmte-prod and jmte-staging as auth0 applications, coupled to github, is actively in use still based on infrastructure config found in #436, so deleting them will break JMTE which currently actually works I think.

Maybe they can take up 2 of the ten free slots for now until we have migrated the JMTE hub as tracked by #2201?

**Comment by GeorgianaElena** [comment]
> Maybe they can take up 2 of the ten free slots for now until we have migrated the JMTE hub as tracked by https://github.com/2i2c-org/infrastructure/issues/2201?

Of course! Then, next thing is to delete all the other ones that we don't use, to make sure that the jmte ones work. Thanks for the info @consideRatio

**Comment by choldgraf** [comment]
What is the action to stop paying them that is needed? Do I need to take that action now?

**Comment by damianavila** [comment]
I think we are currently in a free tier. I suppose the next step would be to get rid of the account.
@GeorgianaElena (might have more information) can you confirm I am actually correct about this one?

**Comment by GeorgianaElena** [comment]
Yes, we're not supposed to be paying anything to Auth0 currently as we're on the free tier. So we might as well delete the account entirely?

**Comment by choldgraf** [comment]
Ah no we have been paying Auth0 roughly $23 a month for the last 2 years...

**Comment by GeorgianaElena** [comment]
> Could we have just recently begun the free tier and were paying before?

@choldgraf, totally. [I changed us to the free tier](https://github.com/2i2c-org/infrastructure/issues/2422#issuecomment-1488402171), once the move to cilogon was complete.

So if you have available the button that deletes the account feel free to push it as we aren't using Auth0 anywhere I believe

**Comment by choldgraf** [comment]
Sounds good - if we delete our Auth0 account, we won't be able to use the name `2i2c` in the future. Can we imagine a situation where we'd want to re-use this? If so, we can just park it in `free tier` mode and document this decision for future reference.

**Comment by consideRatio** [comment]
👍 for not deleting it, ifs free after all for us to retain it now, and we have accounts and credentials in it setup etc already.
