### ISSUE TITLE
Subscribe to githubstatus notifications on slack

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2425]
### Context

As an SRE I want to be informed if there is an issue/outage with GitHub so that decisions such as if operational work can be deployed manually or queued up can be made depending on needs. 

### Proposal

https://www.githubstatus.com/# supports slack subsscription  to `#maintenance-notices` channel

Possibly also define a light weight DR process for when CI/CD is down.

**Comment by yuvipanda** [comment]
I've moved it to `#external-tools-status` to prevent it from spamming #maintenance-notices too much, so that can be preserved as a channel for human made notices.
