### ISSUE TITLE
[victor] High verbosity when conda activate/deactivate their custom env

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#2439]
### Context

Ref https://2i2c.freshdesk.com/a/tickets/607

It has been reported that lots of INFO messages get generated every time their user defined conda environment gets activated/deactivated, which is also every time they open a new terminal. Example below:

<img width="602" alt="Screenshot 2023-03-30 at 14 13 07" src="https://user-images.githubusercontent.com/7579677/228818928-fef09374-e396-4af6-86b9-aa533bc02c6c.png">

### Updates and actions

I've been able to track this down to https://github.com/conda/conda/issues/6945, which from what I understand means:
- the `INFO` messages are to inform the users about conda compiler being used and not system one
- the `INFO` messages might be related to newer compiler versions
- should have been solved by conda by not piping this meesages to the user when `CONDA_BUILD` is not set, which is true for the victor hub, but doesn't look to be working

Does anyone on the @2i2c-org/engineering team has any thoughts about fixing this? Thanks

**Comment by GeorgianaElena** [comment]
Thanks a lot @pnasrat! 

> as the upstream bug suggests there isn't a plan to actually fix this.

They do say that _The compilers only echo this info now when CONDA_BUILD is set to 1_ in https://github.com/conda/conda/issues/6945#issuecomment-389773340

And according to [these conda docs](https://docs.conda.io/projects/conda-build/en/stable/user-guide/environment-variables.html#environment-variables-set-during-the-build-process) CONDA_BUILD is set always set to 1 during build. But I believe that's it, then the var appears to be unset.

>  cc @yuvipanda who was suggesting just downloading from mozilla in the most recent note as the state of snap in ubuntu means this is going to be non-trivial via apt.txt

@yuvipanda do you want to send your note in https://2i2c.freshdesk.com/a/tickets/527 as a ticket response, maybe?

**Comment by GeorgianaElena** [comment]
I came back to this issue today and tried various ways to surpress the warning. Apparently, conda supports an env var called `CONDA_QUIET`, but only for conda > 4.2 and we're at conda 4.1.*.

It's not clear to me what is the file that we need to edit to redirect conda activate/deactivate output to `/dev/null` every time a new terminal is opened. If I add it to `~/.bashrc`, it still shows because I believe it's set from somewhere else also, which takes precedence or gets called later (maybe from `/srv/conda/etc/profile.d/conda.sh`)?

Does anyone on the @2i2c-org/engineering has any advice about this one? Wee need to follow up to https://2i2c.freshdesk.com/a/tickets/607

**Comment by GeorgianaElena** [comment]
So, there's an [`/etc/profile.d/activate-conda.sh`](https://github.com/jupyterhub/repo2docker/blob/c5be2a7e3ab10efead7c207e309e6232274f9a92/repo2docker/buildpacks/conda/__init__.py#L170) that's referenced from `/etc/profile` where the `notebook` env gets activated each time a new terminal is opened.

**Comment by damianavila** [comment]
Mmm... I do not think you will be able to do much on this one until it gets fixed upstream (which seems unlikely).

**Comment by GeorgianaElena** [comment]
Yes, agree. I just wanted to explore how to give them the option to redirect the output to `/dev/null` when a new terminal is opened and the conda env activated, if they wished. But I don't think that's possible either... Is the answer to this one "we can't do anything about it? :/ "

**Comment by damianavila** [comment]
>  Is the answer to this one "we can't do anything about it? :/ "

Unless someone else has further ideas (which do not add a lot of future pain), I think that is the case...

**Comment by GeorgianaElena** [comment]
I'm closing this as I've updated https://2i2c.freshdesk.com/a/tickets/607 with the resolution here.
