### ISSUE TITLE
[utoronto] Investigate report of slow/unresponsive hub

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2445]
### Context

via https://2i2c.freshdesk.com/a/tickets/608

The U of T JupyterHub seems to be slow and/or unresponsive right now. I
got a few reports from some TAs and students just now, and confirmed it
myself.

**Comment by pnasrat** [comment]
Some server start failures
https://grafana.utoronto.2i2c.cloud/d/hub-dashboard/jupyterhub-dashboard?orgId=1&from=1680112235570&to=1680198635570&viewPanel=13

**Comment by pnasrat** [comment]
One node was slammed on CPU

https://grafana.utoronto.2i2c.cloud/d/Qx58n92nk/cluster-information?from=1680113838028&to=1680200238028&viewPanel=9&orgId=1

![image](https://user-images.githubusercontent.com/13798/228928064-e200b4d5-394e-49c0-9a2a-a95c465b3ea0.png)

**Comment by pnasrat** [comment]
Note debug shell can be obtained via

```
kubectl debug -it  node/aks-nbdefault-34239724-vmss0000nw  -n prod --image=ubuntu
```

**Comment by yuvipanda** [comment]
I notice that the JupyterHub pod itself has had 16 restarts - this is probably what triggered the pagerduty alert.

It restarted because *the hub automatically restarts upon 5 spawn failures*.

```
[C 2023-03-30 17:05:15.030 JupyterHub base:1046] Aborting due to 5 consecutive spawn failures
[E 2023-03-30 17:05:15.030 JupyterHub gen:630] Exception in Future <Task finished name='Task-4212' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.11/site-packages/jupyterhub/handlers/base.py:963> exception=TimeoutError("Server at http://10.244.10.227:8888/user/570308c0-141b-4dd6-b816-18cf4d4b1716/ didn't respond in 120 seconds")> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/tornado/gen.py", line 625, in error_callback
        future.result()
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/handlers/base.py", line 970, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/user.py", line 863, in spawn
        await self._wait_up(spawner)
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/user.py", line 907, in _wait_up
        raise e
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/user.py", line 877, in _wait_up
        resp = await server.wait_up(
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/utils.py", line 288, in wait_for_http_server
        re = await exponential_backoff(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/utils.py", line 236, in exponential_backoff
        raise asyncio.TimeoutError(fail_message)
    TimeoutError: Server at http://10.244.10.227:8888/user/570308c0-141b-4dd6-b816-18cf4d4b1716/ didn't respond in 120 seconds
```

I think we should consider a couple of things:

1. A graph (or even grafana events maybe) for hub pod restarts
2. We can tune this number. This was put into the hub as a sort of 'well, something is fucked, maybe restarting ourself will fix this'. I think the hub codebase is in a much better state now than it used to be, so perhaps we can increase this number?
3. We don't set a CPU limit for these pods, and we should.

**Comment by yuvipanda** [comment]
I think we should just make sure that CPU and memory limits are set for literally everything.

**Comment by yuvipanda** [comment]
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/30430/228950367-7d7008e1-fade-44cc-b63f-a5584487974f.png">

Can confirm that this was caused by one user using 8 CPUs. The CPU limiter would fix this.

**Comment by yuvipanda** [comment]
That graph is from https://grafana.utoronto.2i2c.cloud/d/user-pod-diagnostics-dashboard/user-pod-diagnostics-dashboard?orgId=1&viewPanel=3 and was just added last week!

**Comment by yuvipanda** [comment]
I think what we should do is some CPU guarantee that makes sure some useful minimum slice for everyone.

**Comment by yuvipanda** [comment]
I opened https://github.com/2i2c-org/infrastructure/issues/2447 to set CPU limits for all edu hubs

**Comment by yuvipanda** [comment]
Note that at Berkeley we have extensive experience of this happening on GKE too (https://github.com/berkeley-dsep-infra/datahub/pull/3837, https://github.com/berkeley-dsep-infra/datahub/pull/2345 and a lot more)

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/issues/2430 is related but for memory.

**Comment by pnasrat** [comment]
Just adding on the isolation story IO throttling/IOPS can also be an area where we can get bitten

For a great example of an investigative issue around this on AKS 

https://github.com/Azure/AKS/issues/1373

**Comment by consideRatio** [comment]
Super curious to know if the nodes are using ["ephemeral OS" disks](https://learn.microsoft.com/en-us/azure/aks/cluster-configuration#ephemeral-os), as mentioned in the https://github.com/Azure/AKS/issues/1373 - I think I can't check without permissions in azure though.

**Comment by pnasrat** [comment]
It wasn't iops throttling in this case as far as I can tell. That issue was
more for longer-term reference on understanding isolation

Also it's from 2019/2020 so the underlying infrastructure may have improved
on that front.

**Comment by yuvipanda** [comment]
At least for me, this was an exact replica of something we had encountered at Berkeley many many times (https://github.com/2i2c-org/infrastructure/issues/2445#issuecomment-1491504604), and matches what I expect from my understanding of how cgroups work with respect to CPU limits & how the kube scheduler works with respect to CPU requests. 

Regardless, I look forward to @consideRatio filling out https://github.com/2i2c-org/infrastructure/issues/2448, as based on prior experience with z2jh, it usually leads to a deep dive where I still learn something I didn't already know.

**Comment by pnasrat** [comment]
@damianavila I am fine with closing this
