### ISSUE TITLE
Produce an 'accounts recievables' google sheets upto March 2023 for cloud costs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2467]
We want to do a one-time billing pass to recover whatever cloud costs are possible from our customers for whom we passed through cloud costs.

We should produce a google sheet with the following headers:

- Invoicing Month
- Hub
- Cost
- Dedicated (Y/N?)

We should account manually for all dedicated clusters (https://github.com/2i2c-org/infrastructure/issues/2465) and with some amount of automation for shared hubs (https://github.com/2i2c-org/infrastructure/issues/1923)

**Comment by yuvipanda** [comment]
This is now done: https://docs.google.com/spreadsheets/d/1nZlrIsnqjC41uRVts368V2x3k2BnH1hgCUiCTykGAfk/edit#gid=0

**Comment by colliand** [comment]
Thanks @yuvipanda. Your response exactly addressed my question. The `accounts receivables` sheet sets the stage for my next actions toward recovering outstanding cloud billing costs. I will follow up with questions or other issues if required. I believe this issue can now be closed.
