### ISSUE TITLE
PENDING END OF SEMESTER: Update utoronto image for  geopandas, pyproj, PROJ_LIB/PROJ_DATA environment variables on build

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2479]
### Context

Ref: https://2i2c.freshdesk.com/a/tickets/594 

Community reports PROJ_LIB/PROJ_DATA environment variables aren't being set, so first time they load a GeoDataFrame, we see a warning message:

```python
import geopandas as gpd
gpd.read_file("Toronto_Neighbourhoods.geojson")

ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/share/proj
failed
```

### Proposal

@yuvipanda suggested image refresh at the end of their semester I didn't see an issue here or on https://github.com/2i2c-org/utoronto-image/issues

**Comment by damianavila** [comment]
@yuvipanda, when it will be the end of the semester for UToronto? Is that late April? (university semesters/terms are always difficult for me because over here - in Latin America - the periods are quite different 😉).

**Comment by pnasrat** [comment]
It's probably best to refer to the academic calendar (I also wonder if we should be importing these somewhere and exposing via shared Google Calendar for educational hubs)

https://registrar.utoronto.ca/policies-and-guidelines/#academic-calendars

Note utoronto terms depend on division:

https://artsci.calendar.utoronto.ca/sessional-dates
https://ischool.utoronto.ca/wp-content/uploads/2023/03/2023-Summer-Sessional-Dates_Undergraduate-BI_posted-4.pdf

There is a very small window between end of deferred exams on May 5 in Arts and Science and start of Summer term on May 8. 

Do we actually have info on which courses are using the hub by semester?

**Comment by damianavila** [comment]
> There is a very small window between end of deferred exams on May 5 in Arts and Science and start of Summer term on May 8.

Well, that is not a window we are going to use.

> Do we actually have info on which courses are using the hub by semester?

I do not think we have that information available.

**Comment by jmunroe** [comment]
There is another PR currently being acted on to change the image
- https://github.com/2i2c-org/utoronto-image/pull/51

Should this issue be included in that PR? (or at least deployed at the same time?)
