### ISSUE TITLE
[WIP] Hackathon hub checklist

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#248]
Goals to meet:

1. Each hackathon should be in its own billing unit, so we can transparently pass cloud costs through. 
2. When a hackathon is wound down, it should cost us 0$
3. Hackathon hub should be up for a bit before the hackathon itself, but costing as little money as possible
4. Minimal changes during the hackathon itself, to maximise stability.

Pre-hackathon checklist:

1. ASK HOW TO HACK
2. HACK
3. ???
4. PROFIT
5. Make sure project has enough quota to satisfy possible peak demand during the hackathon. Quota increases can sometimes take days.

Post hackathon checklist:

1. Bring cluster back to minimal baseline cost state
2. Ensure that users know how to get a copy of their work (home directories, any buckets)
3. (A week later) Destroy all infrastructure, validate that bill is down to 0

**Comment by choldgraf** [comment]
I think we've resolved this one in https://docs.2i2c.org/en/latest/usecase/events.html
