### ISSUE TITLE
autocomplete issue on m2lines hub

### ISSUE THREAD

**Issue by dhruvbalwada** [2i2c-org/infrastructure#2486]
### Context

The autocomplete on the m2lines hub currently doesn't work properly. It does this: 

Step 1: 
<img width="315" alt="Screen Shot 2023-04-12 at 6 22 22 PM" src="https://user-images.githubusercontent.com/18236610/231599116-62358a4b-aa96-44c6-b350-c32b53fefb8f.png">

Step 2: 
<img width="250" alt="Screen Shot 2023-04-12 at 6 22 27 PM" src="https://user-images.githubusercontent.com/18236610/231599135-1960ce98-61e5-4e49-bdf8-631208d749a7.png">

Instead of just completing the final bit, it basically adds an extra `variable name =`. 
I am not sure where the problem comes from, but hopefully someone with more experience can help. 

I am using the Tensorflow notebook on GPU. The problem is not there in the Base Pangeo case on small CPU. Maybe the problem is upstream?

**Comment by damianavila** [comment]
> I am using the Tensorflow notebook on GPU. The problem is not there in the Base Pangeo case on small CPU. Maybe the problem is upstream?

That feels like an upstream issue. In fact, it seems you reported upstream a related issue some time ago: https://github.com/pangeo-data/pangeo-cloud-federation/issues/923.

**Comment by scottyhq** [comment]
@dhruvbalwada @damianavila It looks like this is actually an `hvplot` problem (https://stackoverflow.com/questions/75772203/jupyterlab-tab-complete-duplicates-assignment). so I'd suggest opening an issue in https://github.com/holoviz/hvplot

**Comment by damianavila** [comment]
Thanks for your feedback, @scottyhq!
@dhruvbalwada, I am going to close this one since this is an upstream issue.
