### ISSUE TITLE
Create alerting for remaing free space in hub home dir

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#2528]
### Context

The [LEAP hub recently ran out of free space](https://2i2c.freshdesk.com/a/tickets/684) for their home directories.

Thanks to https://github.com/2i2c-org/infrastructure/pull/1992, we have grafana dashboards to see this:
<img width="697" alt="Screenshot 2023-05-04 at 21 15 51" src="https://user-images.githubusercontent.com/7579677/236293923-dc9e9a92-144d-4383-be7b-14ffc3c07a7c.png">

### Proposal

We should also create an alert for when the remainig space gets closer to zero to catch this before it causes disruptions.

**Comment by pnasrat** [comment]
I'll take this on as part of the alerting work for this Q.

**Comment by yuvipanda** [comment]
Fixed in https://github.com/2i2c-org/infrastructure/pull/3088
