### ISSUE TITLE
[Support] Help configure user pods or user nodes to make Syncthing work better

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2540]
We got a request from QCL in https://2i2c.freshdesk.com/a/tickets/689 about increasing what is believed to be a node or kernel level configuration as compared to something that can be changed inside a container.

It appears this has been solved by using a privileged daemonset in https://stackoverflow.com/a/69199577/2220152.

>Some users on our Hub have seen errors when syncing large numbers of files with syncthing
>
>"Filesystem watcher errors" from syncthing point to thier documentation https://docs.syncthing.net/users/faq.html#inotify-limits
>
>where it recommends increasing the max_user_watches. I see on our hub it is 12288
>
>```
>cat /proc/sys/fs/inotify/max_user_watches
>12288
>```
>
>I tried modifying our docker image, but it seems to be controlled by the host. Would it be trivial to increase?

### Proposal

We add an opt-in DaemonSet template to run on user nodes in the support chart, allowing us to reconfigure some details such as this.

### Action points

- [ ] Seek agreement towards piloting this
- [ ] Trial install in QCL and ask for feedback from QCL, specifically Joseph in https://2i2c.freshdesk.com/a/tickets/689

**Comment by pnasrat** [comment]
@consideRatio I believe the k8s way to do this is via  the security context https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/

I think our chart already allows for setting this via  `securityContext` in the singleuser container

Is there a particular reason this didn't work for you and you are advocating for a daemon set.

**Comment by pnasrat** [comment]
If it iis a DaemonSet due to the sysctl needing to be set on the node, an alternative might be as we are already using initContainers we could also do this via a privileged initContainer

**Comment by consideRatio** [comment]
I haven't overviewed how it can be done and just described the first technical path that seems doable in order to get an issue written to iterate from. I figure that step 1 is to explore options on the implementation! Thanks for sharing things about `sysctl` via securityContext, I've never done something like that and wasn't aware about it!

In the k8s docs you linked they mention only some things can be configured first without configuring them to be allowed on the node, and I didn't see `fs.inotify.max_user_watches` listed there as safe and something that only influences a single pod.

**Comment by pnasrat** [comment]
Got it, if we've not commited to an implementation maybe consider renaming the issue to reflect that by focusing on the desired outcome not implementation.

**Comment by pnasrat** [comment]
Maybe lets test our assumptions and start with a daemonset for QCL to test it works, and then extract to more generic feature.

**Comment by yuvipanda** [comment]
As I thought, inotify does not work on NFS - https://stackoverflow.com/questions/4231243/inotify-with-nfs. So i'm not sure increasing those *specific* sysctl params will help. So,

- [ ] Determine *where* they are storing their files for syncthing, and verify it is under `$HOME`.
- [ ] If under `$HOME`, let them know that this particular setting will not help, as inotify doesn't support NFS
