### ISSUE TITLE
Q2 goals checkpoint

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#2543]
### Context

This is a checkpoint issue trying to collect high-level information about the status quo on the existing Q2 goals.

### Proposal

If you are an engineer leading one of the existing goals (gdoc: https://docs.google.com/document/d/1dUO2USQlRbcjOEkjlCu1gyTaPBZmGZSRF4L-_9xecmA/edit#heading=h.ycnyhh6g1ri6 and https://github.com/orgs/2i2c-org/projects/22/views/50), please respond to this issue with:

```
# Goal title
# Status (a summary of the work done and the current state, no more than a paragraph)
# Execution plan for the rest of the quarter (a summary as well, no more than a paragraph).
```

cc @2i2c-org/engineering

**Comment by pnasrat** [comment]
# Billing

https://github.com/2i2c-org/infrastructure/issues/2431

## Status 

Historic cost analysis done manually with @yuvipanda and handed over to @colliand who has been doing cost recovey.
Automation work in progress and nearing completion.

# Execution plan for the rest of the quarter 

@pnasrat Complete GCP shared cluster code and merge (support has taken up my time this last week post Paris)
@pnasrat complete documentation tasks 
@pnasrat Co-ordinate Q2 billing with @colliand for early July

**Comment by pnasrat** [comment]
# Monitoring and Alerting

#2267

## Status

Unstarted - @yuvipanda and I want to request pushing a Quarter as billing took far more cycles plus travel/vacation

**Comment by yuvipanda** [comment]
# JMTE normalization

#2201 

# Status

It's now integrated into our infrastructure! They have also been asked to use the 2i2c support process, rather than ping us on slack.

The image needs to be moved to something matching what we do for all our other images.

**Comment by consideRatio** [comment]
# GESIS

# Status (a summary of the work done and the current state, no more than a paragraph)

The project has established a place in the existing ecosystem of open source projects that fits quite well. A github repo for the binderhub-service chart is setup with relevant automation, and we have one for the UI side of things. The chart and UI is separately demoed to a degree.

# Execution plan for the rest of the quarter

- chart: Handle pushing to docker registries that requires credentials
- Deploy for testing as a opt-in basehub dependency
- End to end test setup including use of Yuvi's UI
- Help binderhub towards 1.0.0
- Document critical things to enable contributions
- Ensure UI repo gets relevant automation

**Comment by consideRatio** [comment]
# k8s cluster upgrades

https://github.com/2i2c-org/infrastructure/issues/2293

# Status

Its me and Georgiana who is allocated time towards this goal, me at 10% and Georgiana at 5%. I've worked more than the allotted time already and can't focus on this much going onwards.

- All EKS clusters are upgraded, with a guide on how to upgrade, seven clusters were upgraded
- Not all GKE clusters are upgraded, with preliminary notes on how to upgrade established
- The AKS cluster (utoronto) is not upgraded, and needs to be recreated

# Execution plan for the rest of the quarter

- Schedule cluster upgrade time slots with remaining clusters' communities, prioritizing utoronto

**Comment by damianavila** [comment]
Remaining updates:
* Write proposal for support steward/triager responsibilities, and processes: https://github.com/2i2c-org/team-compass/issues/674#issuecomment-1589544607
* [Targeted hire] Bring Yuvi as a senior developer/engineer for our 2i2c Eng team ://github.com/2i2c-org/meta/issues/511#issuecomment-1591195987
* Q2 2023 Goal: Move CloudBank hubs to their own data8 style image://github.com/2i2c-org/infrastructure/issues/2435#issuecomment-1597607481

Closing this one since Q2 is already behind us!
