### ISSUE TITLE
Define Q3 proto-goals

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#2544]
### Context

We are repeating (and hopefully improving) our goal definition process for Q3.
As part of that process, we need to start collecting proto-goals that we can eventually move forward into well-defined goals as we previously did in several sync meetings, although we will add now some async processes to provide feedback as well.

### Proposal

Let's start collecting ideas (proto-goals) that we can start discussing down the road as part of the "shaping" process in dedicated existing (or new) issues. Please respond to this issue with:

```
# Proto-goal title
# Brief description
# Intent to lead the goal
# Link to an existing or new issue
```

During the next 2 weeks, you will have time to create the proto-goals and provide async feedback on them.
During the 1st week of June, we will have a first sync meeting with the whole @2i2c-org/engineering team to present the proto-goals and hopefully reduce the set to a few candidates.
Then, there will be ~2 weeks for async feedback to work on those (lead assignation, team formation, realistic definition of done, etc).
And finally a sync meeting during the 3rd week of June to finalize the process (ie. check resources allocation).

cc @2i2c-org/engineering

**Comment by pnasrat** [comment]
Before we do this do we have high level priorities, and a strategy as an org for Q3 to be able to evaluate proposals against.

I'd also ask we have some clearer guidelines of the scoping and structure proto goals - should they be at the outcome level (what we want to do) vs implementation detailed to help wrriting. Ie description is about the change we want to see not a task level detail.

**Comment by choldgraf** [comment]
Just quickly popping in from vacation to say that yes I think this should be an org wide process, not specific to engineering.  I will try to write up higher level direction and guidance when back from vacation. Will also think on @pnasrat's other questions and participate in discussion I'm when I'm back but want to protect my vacation time now

**Comment by choldgraf** [comment]
### Proposed quarterly goals system

I wrote out a [proposed process for our quarterly goals setting](https://docs.google.com/document/d/1EukvDeBk1JUiWQl30tFwhmXbY_It8RZhGAAS0NlhA2Q/edit#). It tries to clarify some questions around what form goals should take etc. Can we quickly iterate and align on this process, and then follow it for our current goals planning for Q3?

If so, I'd suggest that we create a new issue following the process described in the proposal, and close this one. But I'm open to alternative suggestions.

**Comment by choldgraf** [comment]
I've created a planning issue for Q3 2023 below:

- https://github.com/2i2c-org/meta/issues/596

I'd suggest that we close this issue and focus our efforts over there, OR leave this as an engineering-specific issue to define proto-goals if @damianavila wishes.

**Comment by yuvipanda** [comment]
Did you have a goal in mind for re-opening this, @consideRatio?

**Comment by consideRatio** [comment]
Ooops no this is a missclick from mobile =/
