### ISSUE TITLE
[leap] Create new ro bucket to hold leap-persistent data

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2546]
### Context

Ref: https://2i2c.freshdesk.com/a/tickets/712

Filed via support needs to be done by Thursday 2023-05-18

Can I/we create another bucket that is read-only for all users, and then move the data from `leap-persistent` to the new bucket via the cloud console?

In fact we could integrate this workflow with the [google groups based upload](https://leap-stc.github.io/leap-pangeo/jupyterhub.html#uploading-data-from-an-hpc-system) (and the PGF recipe based data-management [repo](https://github.com/leap-stc/data-management) I am currently spinning up) by only uploading to that ‘read-only-persistent’ bucket (If something needs to be deleted, I could always do that as admin).

**Comment by yuvipanda** [comment]
Will amend https://github.com/2i2c-org/infrastructure/pull/2406 to fix this as well

**Comment by yuvipanda** [comment]
I've updated #2406 to:

1. Create a `leap-persistent-ro` bucket
2. Provide the hubs *readonly* access to this
3. Start a transfer of the 34TB from `leap-persistent` to this.

However, (2) doesn't work yet - I'll work on fixing that tomorrow.

**Comment by pnasrat** [comment]
@yuvipanda I believe you sorted this - can this be closed?

**Comment by damianavila** [comment]
Looking at the support ticket in Freshdesk, this seems to be resolved, so I am gonna close it now.
Reopen it if you disagree.
