### ISSUE TITLE
Enable access to grafana for linked-earth JupyterHub

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2557]
### Context

Ref: https://2i2c.freshdesk.com/a/tickets/723

Enable access to linked-earth JupyterHub for grafana via [GitHub authentication](https://infrastructure.2i2c.org/howto/grafana-github-auth/#grafana-dashboards-github-auth) for [viewer access](https://infrastructure.2i2c.org/topic/monitoring-alerting/grafana/) to Grafana Dashboards for the linked-earth hub? 

```
Deborah Khider GitHub: @khider  
Julien Emile-Geay GitHub: @CommonClimate


```

**Comment by pnasrat** [comment]
According to our docs it looks as if we do this at an org level not individual user accounts.

**Comment by consideRatio** [comment]
> According to our docs it looks as if we do this at an org level not individual user accounts.

I've looked for allowing individual users, but I don't think grafana's github auth system supports it.

For reference, notes like those in point 1 in [this comment](https://github.com/2i2c-org/infrastructure/issues/2323#issuecomment-1505721800) may be helpful.

(Those preliminary notes are referenced from https://github.com/2i2c-org/infrastructure/issues/2214, where I've written down all things todo related to grafana)

**Comment by pnasrat** [comment]
Resolved

**Comment by pnasrat** [comment]
@consideRatio thanks for the pointer to your notes in that issue comment. We definitely should include that in community facing docs with sample screenshots and add to the infrastructure guide also
