### ISSUE TITLE
Identify where 2i2c engineers spend time on image management

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2582]
There's a general feeling that we spend a lot of time on image management that counts as toil. We should investigate what exactly we are spending time on, and use that to *inform* toil reduction work we do. It shouldn't be the *only* thing we use, but should help us validate wether something we work on will actually help or not. Doing things purely off this list would be too *reactive* and might not be exactly what we need.

Taking the last 6 months as a study period, I'm going through the following and collecting image related work we have done in this google spread sheet: https://docs.google.com/spreadsheets/d/1sWUsWvgkKsQKs1grvvL1BS3Ee4ufyAYq7blNK4zd0S4/edit#gid=0

- [x] Freshdesk tickets
- [x] GitHub PRs to this repository
- [x] New Hub issues that result in work in other repositories

Here is a summary of my coding from the Sheet

# Support tasks, GH PRs related to image management

Task Type | Count 
-- | --
UI Install | 3 
Package Install | 7
Image Consult | 3
Deploy profileList | 31
Deploy image | 8
Debug notebook infra | 2
Change default UI | 2
Build New Image form Scratch | 2
Add repo2docker-action to an existing repo | 2

Note that a limitation here is that we don't know *how much time* was spent on each of these, just that we got these many of them. For example, image consult probably took more time than deploying a profile list!

# How images are built

We have a total of 36 unique images, several of which I couldn't actually find the source for.

Type | Number of Hubs using them 
-- | --
Default Image (on Cloudbank) | 20
Default image (not on Cloudbank) | 5
Full Dockerfile | 1
Upstream Pangeo Image | 17
repo2docker | 10
NA | 7
Modified rocker, pangeo, matlab | 8 (3 + 3 + 2)
Modified conda/mambaforge | 4
Full fork of jupyter/docker-stacks | 1

# Profile Lists
Type | No. of Hubs
-- | --
Present | 18 (34% of all hubs)
Image selected as a profile, no dropdown | 2 (11% of hubs with profileLists)
Image selected as a dropdown on a profile | 7 (38% of hubs with profileLists)

Code used for a lot of this data is at https://gist.github.com/yuvipanda/7bca69d42d7b849fa17d9e8c3da4404f

**Comment by pnasrat** [comment]
@yuvipanda this is great and really informative. One of my initial takeaways here is that if we maintained the current spread of things scaling for 10 x that would mean a large number of images!

I'm wondering if we could create a global dashboard for imagesusing something like

```
sum by (namespace,image_spec)(kube_pod_container_info{namespace=~".+prod",container="notebook"})
```

**Comment by yuvipanda** [comment]
Given I couldn't figure out where a few images were built from, I opened https://github.com/jupyterhub/repo2docker-action.

**Comment by damianavila** [comment]
> I opened https://github.com/jupyterhub/repo2docker-action.

Maybe the link is wrong?

**Comment by yuvipanda** [comment]
@pnasrat I considered using the prometheus query, but it doesn't work if there isn't a user server currently running (or run in the recent past). I also wanted to differentiate between the different ways the image has been set.

**Comment by damianavila** [comment]
@yuvipanda, I think the goal of this issue is already achieved by the report in the first message.
Additionally, you have a WIP PR (https://github.com/2i2c-org/infrastructure/pull/2711) to include automatic reports in our deployer codebase. Do you want to close this one when that PR is merged (otherwise I would advocate to close it)?

**Comment by yuvipanda** [comment]
Yeah, I think this has produced very useful info and time to close this.
