### ISSUE TITLE
Bump Julia to v1.9 in JMTE image

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#2596]
### Context

Ticket ref: https://2i2c.freshdesk.com/a/tickets/751

A request to bump the version of Julia in JMTE has come in.

- Are we fully managing the image or should we be encouraging them to attempt this kind of bump themselves?
- I don't think the JMTE image repo has been migrated over to the 2i2c GitHub org - where does it live?

**Comment by yuvipanda** [comment]
@sgibson91 it lives currently in https://github.com/pangeo-data/jupyter-earth, and we are currently responsible for the image as well.

**Comment by yuvipanda** [comment]
I have:

- [ ] Opened https://github.com/pangeo-data/jupyter-earth/issues/167 to split the image off that repo, move it into this org
- [ ] Opened https://github.com/pangeo-data/jupyter-earth/pull/165 to pin the image to a specific base version, so upgrading Julia doesn't also bring in 6 months of changes for everything else
- [ ] Opened https://github.com/pangeo-data/jupyter-earth/pull/166 to upgrade version of Julia

**Comment by damianavila** [comment]
Closing as per https://github.com/pangeo-data/jupyter-earth/pull/166.

**Comment by yuvipanda** [comment]
Not deployed yet

**Comment by yuvipanda** [comment]
Done!
