### ISSUE TITLE
Update Authentication method for JMTE ?

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#2601]
### Context

I was looking at the authentication set ups for JMTE  compared to how most (?) other hubs are set up.

For JMTE, it is only has hard-coded list of users and does not included the 2i2c-org staff.  Should this be updated?  (I noticed this when I tried to log on to that hub to check how something was configured and realized that I don't have access.)

### Proposal

Convert JMTE to a CILogon and/or GitHub team authentication (or confirm that a hard coded list of users remains the recommended authentication method)

**Comment by yuvipanda** [comment]
@jmunroe fixed in https://github.com/2i2c-org/infrastructure/pull/2602 i think

**Comment by yuvipanda** [comment]
@jmunroe try again now?
