### ISSUE TITLE
Exploring how to track upstream work

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2662]
In discussing with @damianavila we've concluded that we want to explore how to provide insights on open-source contributions made. Understanding that it will be hard to capture all kinds of contributions, we've opted to explore trying to capture something specific: **merged PRs in the jupyterhub github organization**.

### Initial action points

- [ ] @damianavila creates a GitHub project in https://github.com/orgs/2i2c-org/projects
- [ ] @consideRatio defines columns: url, org, proj, author, merged at
- [ ] @consideRatio trials populating the project with self-authored PRs using a script that both acquires relevant info and adds entries to the project
  - Notes on how the `gh` CLI was used to acquire a list of self-authored and merged PRs in a github org/project between a set of dates can be found in https://hackmd.io/cLDYNuu5TTm1r3PZ7dfWyg.
- [ ] Discuss with @damianavila and consider further action points

**Comment by consideRatio** [comment]
Wow! That is a great overview and system @choldgraf!

@damianavila seeing that makes me think we should re-evaluate adding another github project as planned. What so you think?

**Comment by choldgraf** [comment]
I do think that simply _tracking_ our activity is mostly accomplished by that `upstream/` page. Though if we wished, we could improve it to break things down by author for example.

If I put on my 2i2c impact communications hat on, I'd probably communicate this externally either monthly or quarterly. If I did that, I wouldn't want a list of PRs or numbers of comments. I'd want something like 3 things that were obviously impactful that our team intentionally spent their time on improving. How can we build practices to consistently highlight these 3 things?

**Comment by consideRatio** [comment]
Closing as stale and likely obsolete work thanks to the upstream page at https://2i2c.org/kpis/upstream/
