### ISSUE TITLE
Reach out to communities to help them transition from 2i2c-hubs-image

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2674]
After #2671 the following communities config files still reference quay.io/2i2c/2i2c-hubs-image:

- config/clusters/2i2c/aup.values.yaml
- config/clusters/2i2c/pfw.values.yaml (done in #3052)
- config/clusters/2i2c/ucmerced.values.yaml (staging hub without it established via #3218)
- config/clusters/ubc-eoas/common.values.yaml (done in #3020)

@yuvipanda suggested that:

> we should still reach out to the 4 communities still using this and move them to a different, more appropriate image.

**Comment by yuvipanda** [comment]
pfw has been decomissioned, so aup and ucmerced are the only ones left.
