### ISSUE TITLE
pangeo-hubs: help prometheus-server startup again (node pool changes, I lack permissions)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2695]
We have a prometheus-server that is OOMKilled and can't live on the core node pool because it runs out of memory, where the largest request we can make is 21.7Gi is already to little on the current n1-highmem-4 nodes that are specified to provide 26 GB of memory.

I suggest an upgrade to the n2-highmem-4 nodes like used by default for new daskhub clusters and in many others already, they provide 32GB of memory, and may help us get prometheus-server functional again.

Another option is to provide a new node pool for prometheus server by tainting it and letting prometheus server tolerate it, or both.

I can't work this because I lack access to pangeo-hubs cloud console.

**Comment by GeorgianaElena** [comment]
@consideRatio, we should all have access to pange-hubs, but not through our @2i2c google accounts, but though ones provided by columbia with `@columbia.edu` I think. Can you check if you have such an account?

**Comment by GeorgianaElena** [comment]
Btw, I added this issue and https://github.com/2i2c-org/infrastructure/issues/2688 to the sprint board with a `critical` label, so we take advantage that we're still planning the next sprint and we can plan them accordingly. cc @damianavila
