### ISSUE TITLE
Deploy grafana for the pilot hubs

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#27]
Grafana is useful in getting a quick view of things that are happening on the cluster, and keeping track of its usage. We should deploy one for these hubs!

**Comment by jamesgspercy** [comment]
I agree! This will be very useful.

**Comment by yuvipanda** [comment]
We have one grafana per cluster now:

1. grafana.cloudbank.2i2c.cloud
2. grafana.pilot.2i2c.cloud

There's prometheus running one per cluster.

Need to:

1. Add dashboards to them
2. Add github auth for them

**Comment by choldgraf** [comment]
Note that @ericvd-ucb and @ianabc both mentioned that this would be useful to have in the user-facing documentation as well, so that hub administrators (or hub champions like course instructors) could have an idea for what was happening on their hub. In particular, folks will want to be able to figure out how quickly they are using hub resources.

**Comment by choldgraf** [comment]
I'm closing this one, as we now have grafana deployed for each of our clusters/hubs.
