### ISSUE TITLE
Move R users of jupyter.utoronto.ca to r.datatools.utoronto.ca

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2729]
We moved UToronto to have multiple hubs as part of https://github.com/2i2c-org/infrastructure/issues/1712, and set up r.datatools.utoronto.ca with a rocker based image. As part of https://github.com/2i2c-org/infrastructure/issues/2583, we want to simplify the images we maintain. We had already communicated to UToronto users that R is going to go away from jupyter.utoronto.ca, and we should use this opportunity to do that now.

Based on in-person conversations with @ntaback, the following schedule should work:

1. UToronto announces to all users (via their own mechanisms) that R will go away on **August 15**. This should be sent out by **first week of July** so they have time. Auguest 14 is last day of class for summer of Utoronto, and september 7 is first day of fall classes ([source](https://www.artsci.utoronto.ca/current/dates-deadlines/academic-dates#academic-dates-deadlines-accordion-3)). 
2. We merge https://github.com/2i2c-org/utoronto-image/pull/54, getting rid of R and simplifying everything else, **on August 15**.
3. If there are missing R packages, we sort them out over the next few weeks as requests come in. @ntaback should be able to corral them to us as needed.

**Comment by yuvipanda** [comment]
https://2i2c.freshdesk.com/a/tickets/952 is the linked ticket. There is a plan outlined there on how to do this + timelines.

**Comment by yuvipanda** [comment]
I tried to find a list of users who have ever used rstudio, and found that this way:

1. `deployer exec-homes-shell utoronto prod`. This spins up a pod with the utoronto homes be mounted under `/home`
2. Run this command to find all user home directories with a `.rstudio` directory created in them. I think this happens only if the user has *ever* used rstudio: `k -n prod exec utoronto-prod-shell  -- /bin/bash -c "cd /home; find . -name '.rstudio' -maxdepth 2 -mindepth 2" > rstudio-homedirs-utoronto`. This must be run in a different tab, while (1) is still running. It'll output to a file *locally* named `rstudio-homedirs-utoronto`.
3. The home directories are escaped, unescape them by first making this following script and calling it `doirstudio.py`:
    ```python
    import sys
    from escapism import unescape

    for l in sys.stdin:
        print(unescape(l.split('/')[1], '-'))
    ```
4. Run it with: `cat rstudio-homedirs-utoronto| python doirstudio.py > users-with-rstudio.txt`
5. This produces a list of usernames, which may be either emails or LDAP oids (that would need to be mapped). There may be some duplicates as well. 

I saw about 40122 home directories and 12658 of them had `.rstudio` in them. I'll pass on this list to them.

**Comment by damianavila** [comment]
I have assigned @yuvipanda to this one since he has been working on this piece for some time. Additionally, I am adding @GeorgianaElena as a secondee to help @yuvipanda to get everything in place before the break.

**Comment by yuvipanda** [comment]
Yep, most important part of this is really to finish https://github.com/2i2c-org/utoronto-image/pull/54 and roll it out to staging. Nothing else needed from our side.

**Comment by damianavila** [comment]
There is a recent ticket that I think is relevant for this transition: https://2i2c.freshdesk.com/a/tickets/1185.

**Comment by yuvipanda** [comment]
Plan for tomorrow!

- [ ] Make sure that datatools.utoronto.ca is up and running (this is managed by the UToronto team, will await confirmation from them)
- [ ] Merge https://github.com/2i2c-org/infrastructure/pull/3582 to bring in new images to prod
- [ ] Merge https://github.com/2i2c-org/infrastructure/pull/3583 to fixup the home page
- [ ] Watch for issues.

**Comment by yuvipanda** [comment]
Soooo https://github.com/2i2c-org/infrastructure/pull/3531 nullifies https://github.com/2i2c-org/infrastructure/pull/3583, because the home page is never shown! So there's no redirect to their unified homepage, instead we just get shunted to the login page. This is important for nbgitpuller links to work for logged out users. We *can* work around this with some JS in their unified landing page, but I'd prefer to not. Let's communicate this to them and see what their desire is.

**Comment by yuvipanda** [comment]
<img width="1911" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/61e411e9-8d2f-4b4e-939c-c8f8078ba788">

The daily active user count for the R hub overtook the daily user count for the python hub today, reflecting real usage levels I think.

This has been completed!
