### ISSUE TITLE
[INCREASED HUB ACTIVITY] 2i2c climatematch

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#2753]
### Summary

The Climatematch community is expecting an increased hub activity starting with Wednesday **this week** until August 1st.

### Event Info

There are multiple triggers for the increased hub activity as specified in the https://2i2c.freshdesk.com/a/tickets/804 ticket:

- [additional nodes requested]: July 5-6 (Wednesday-Thursday this week) they are holding an instructor training event where they expect about 50 logins intermittently throughout the day.
- [no additional nodes requested] Next week they will be adding over 500 students to the course GitHub team and ask them to test access into the hub.
- [no additional nodes requested] The course officially begins on July 17. Between students, instructors, and content creators, thet expect about 700 active users during the two weeks of the live course. 
 - Activity will likely drop after August 1 but we will monitor usage after that, with potential renewal until the end of December to allow students to continue to work on projects.

### Hub info

- **Hub URL**:  https://climatematch.2i2c.cloud
- **Hub decommisioned after event?**:  No

**Comment by pnasrat** [comment]
I'll handle the increase in nodes for Wednesday.

**Comment by GeorgianaElena** [comment]
Thank you @pnasrat!

**Comment by pnasrat** [comment]
Looking at the climate match configuration. kubespawner allocates notebook servers with a limit of 7G and guarantee of 5G onto a pool of n1-highmem-2	2vcPUs	13G, so we can only fit 2 users per node at guarantee but if both burst memory it'll cause a reschedule. 

That seems low. I'm wondering why this isn't larger nodes more densely packed with some overhead capacity

700 active users at peak would need 700 nodes which isn't ideal in my mind. 

. A user profile isn't suitable for this setup as it's a class. CC @consideRatio for thoughts on sizing

**Comment by pnasrat** [comment]
Created initial pull request in #2757 to handle the instructor case but we should resolve the plan for actual node sizing for  next week   and the event itself.

**Comment by consideRatio** [comment]
> That seems low. I'm wondering why this isn't larger nodes more densely packed with some overhead capacity

Legacy reasons I presume. When there are 100+ users, having at minimum 10 users per node is essential to not run out of quotas of node disks or public IPs and avoid startup times I'd say.

> we should resolve the plan for actual node sizing for next week and the event itself.

I'm approving #2757, but like you I think there is a lot of room for improvements. I'd say that we should go for n2-highmem-16 machines with 128 GB RAM if the requests/limits are 5/7GB.

**Comment by yuvipanda** [comment]
@pnasrat @consideRatio I've documented that here now: https://github.com/2i2c-org/infrastructure/pull/2765. I agree we should make the node bigger now.

**Comment by pnasrat** [comment]
Note they have also requested notebook memory to be 16G

@yuvipanda you mentioned quota issues for using n2 machines yesterday do you have more specific information on that?

128/16 minus some overhead means about 7 notebooks for nodes so for concurrent 700 users we'd need 100 nodes for a synchronous workshop

It's unclear if 700 active users is sustained load or it'll be more intermittent usage of 700 unique users.

**Comment by pnasrat** [comment]
I've created #2775 with n1-highmem-32 (which would support 10 user servers per node, happy for feedback on machine type. I've also communicated with the community via support that we'll be changing the pool. Once that's done I'll increase the memory request to 16G as requested

**Comment by consideRatio** [comment]
I requested a quota increase for n2 machines, if that arrives, then I suggest use of `n2-highmem` over `n1` because they are faster and cheaper per CPU performance and per RAM, where its especially cheaper when considering RAM. n1-highmem has 1:6.5 in CPU:RAM while n2-highmem has a 1:8 CPU:RAM ratio.

A less impactful idea in my mind is to have affinity towards choosing subset of all the available `n2-highmem` machines, specifically 4 / 16 / 64 CPU, just to reduce some complexity and simplify offerings and such - not because its critical.

**Comment by consideRatio** [comment]
Approved! Apparently the same minute it was received.

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/479ceff7-0e7c-4a87-ad06-83cd19d4e85d)

For reference about quotas, the reason we had to request it is related to this project was relatively old. Newer project was initialized with a non-0 quota. For example a new project i created had 300 n2 and n1 quota in a few regions, but had 600 n1 quota in a few as well.

**Comment by pnasrat** [comment]
Looks like they've had fairly constant usage over the last 24 hours but not spiking at 500 concurrent but more like 10 so the single larger node is handling that with room to grow. 

![image](https://github.com/2i2c-org/infrastructure/assets/13798/d9fa39cd-4431-494b-81ff-a3175627323e)

**Comment by pnasrat** [comment]
Recommendation for early morning America/New_York TZ on 2023-07-17 to grow the min pool to 10, I'll be on support so I can take that.

**Comment by pnasrat** [comment]
@damianavila assigning to  you for potential end of event eng work after August 1

**Comment by GeorgianaElena** [comment]
@damianavila, I will get the min node pool size back to zero, to reduce costs but will keep the same memory guarantees, in case any of the users expects to be able to re-run the same workflows.
Also, there still seem to be some users left:


<img width="1410" alt="Screenshot 2023-08-04 at 09 04 17" src="https://github.com/2i2c-org/infrastructure/assets/7579677/32c13ef7-bc6c-4a87-93d5-d9cc81f41606">


Also, we might want to also double check with them the decomission date, which seems to be in two weeks per https://github.com/2i2c-org/leads/issues/110
