### ISSUE TITLE
`zones` in GCP terraform nodepool config is not actually optional

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#2759]
### Context

https://github.com/2i2c-org/infrastructure/blob/c365d39140351b2572d7f22ea9e408aa1f1341cd/terraform/gcp/variables.tf#L87

We have the above optional config to set a zone on nodepools, which defaults to `null` if not provided. However, I don't think this is actually optional, as I ran into a lot of errors leaving in undefined in PR https://github.com/2i2c-org/infrastructure/pull/2758, such as:

```
google_container_node_pool.notebook["neurohackademy"]: Creating...
╷
│ Error: Cannot determine zone: set in this resource, or set provider-level zone.
│ 
│   with google_container_node_pool.notebook["neurohackademy"],
│   on cluster.tf line 238, in resource "google_container_node_pool" "notebook":
│  238: resource "google_container_node_pool" "notebook" {
```

I think this is a bug in our terraform config.

**Comment by sgibson91** [comment]
I couldn't even avoid the above error by setting a zone: https://github.com/2i2c-org/infrastructure/pull/2758#issuecomment-1620491297

**Comment by pnasrat** [comment]
I'm happy to pair on investigating this or will do so myself at I experienced got other issues with google_container_node_pool resources so it seems like either state/resource mismatch or possibly new required fields that may be related

**Comment by yuvipanda** [comment]
Fixed in https://github.com/2i2c-org/infrastructure/pull/2758#issuecomment-1622684841
