### ISSUE TITLE
Add github users to Grafana dashboard for CarbonPlan

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#2761]
### Context

Re: https://2i2c.freshdesk.com/a/tickets/795

> I'd like to view the grafana dashboard for the CarbonPlan hub. The docs recommend reaching out to a 2i2c engineer to activate GitHub login - https://infrastructure.2i2c.org/topic/monitoring-alerting/grafana/#logging-in. Could Raphael Hagan (norlandrhagen) and I (maxrjones) please be given access via GitHub login?

I see that CarbonPlan already has grafana via github organizations set up. Is it also possible to add just individual users using the `support.values.yaml` or is a different kind of [Grafana configuration](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/github/) required?

**Comment by damianavila** [comment]
@jmunroe, I think this one might help you: https://infrastructure.2i2c.org/sre-guide/support/grafana-account/#

**Comment by jmunroe** [comment]
Very clear.  Issue resolved!
