### ISSUE TITLE
Create AWS Cost & Usage report monthly for 2i2c AWS consolidated billing

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2779]
Report name and content
Report name: 2i2c-aws-consolidated

2i2c-cloud-costs
S3 path prefix
aws-consolidated-rmonthly-report/2i2c-aws-consolidated/date-range/
Time granularity: Monthly

Report data integration enabled for Amazon Athena

https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/athena.html

**Comment by pnasrat** [comment]
Handoff - I created the report. Next steps for automated billing

1. Set up Athena https://docs.aws.amazon.com/cur/latest/userguide/use-athena-cf.html for 2i2c-sandbox account for consolidated billing. This doesn't have to happen everywhere so might not be worth terraform initially
2. Create SQL queries for billing similar to the BigQueryImporter https://docs.aws.amazon.com/cur/latest/userguide/cur-ate-run.html for monthly reporting
3. Use boto or another athena python Athena client to add  a AthenaCostUsageReportImporter https://github.com/2i2c-org/infrastructure/blob/master/deployer/billing/importers.py and tests

**Comment by pnasrat** [comment]
cc @yuvipanda for outline on how I think we can add AWS billing for the consolidated billing account, assigning to @damianavila to prioritize this work with other ongoing work.

**Comment by yuvipanda** [comment]
Closing based on https://github.com/2i2c-org/meta/issues/1028#issuecomment-2087793473 and https://github.com/2i2c-org/meta/issues/1028#issuecomment-2089063971
