### ISSUE TITLE
[LEAP] Jupyterhub - 'stalled' Jupyter Notebook cells

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#2780]
### Context

Reported in https://2i2c.freshdesk.com/a/tickets/812

> [Julius Busecke](https://2i2c.freshdesk.com/a/contacts/80068210960) reported via email
> a day ago (Thu, 6 Jul 2023 at 1:29 PM)
>
> I have experienced this from time to time, and hear a bunch of complaints about the following issue
> On the LEAP hub, when executing a cell, this is usually indicated by an `*` to the left of the cell. On many occasions however executing the cell will show the `*`, but the cell will never be executed actually. Often this is fixed by just re-executing the same cell.
>
> While this is not fatal, it can be quite irritating. I am not sure if that has something to do with a degraded response from the hub itself, since I have also observed a bunch of these around the time:
>
> [Screenshot of "Server unavailable or unreachable"]
>
> All of this usually is only temporary, but maybe you could look and see if anything sticks out?
>
> I experienced both of these in the past 5 minutes.

**Comment by jmunroe** [comment]
Given that this report was reference to a specific time, I took a look at logs in the 30 mins period around when the issue was reported:

<img width="1466" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/6181563/07832a20-79e8-40e4-89db-307a377b11b5">

We can see a spike in errors around the 1:33 pm mark suggesting that something is not work well.

I think the user was using
- Image: pangeo/pytorch-notebook:2023.05.18
- Machine: NVIDIA Tesla T4, 24GB RAM, 8 CPU
- Notebook: /AREAS/LEAP_TESTING/Samarth_Agrawal_DataProcessing.ipynb

The workflow involves Dask, zarr, xarray for preparing data for a pytorch pipeline.

**Comment by yuvipanda** [comment]
Can this be closed now, @jmunroe?

**Comment by jmunroe** [comment]
Yes. No further action is being taken.
