### ISSUE TITLE
Support reading datasets from Google Cloud Storage

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#280]
# Background

Reading from most cloud hosted repositories - like the [pangeo data catalog](https://pangeo-data.github.io/pangeo-datastore/) but also many other [intake based](https://intake.readthedocs.io/en/latest/quickstart.html) datasets requires that *we* pay for data access fees - also called [requester pays](https://cloud.google.com/storage/docs/requester-pays). The user server needs to be authenticated as our project so it can access these datasets. Currently, we disable this [for security reasons](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/security.html#audit-cloud-metadata-server-access).

On a per-hub basis, we should allow users to authenticate as our project so they can access these datasets. However, it'll incur a cost for us so we need to be careful!

# Expected timeline

This is currently blocking most common use cases of dask, so I'd like us to do this over the next few weeks.

# Technical plan of attack

Each hub will need its own [Google Cloud Service account](https://cloud.google.com/iam/docs/service-accounts), configured with *just enough* permissions to authenticate itself. We can do this with [GKE config connector](https://cloud.google.com/config-connector/docs/concepts/installation-types) and [GKE workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity). 

# Steps to complete this goal

## Terraform things

- [ ] [Install](https://cloud.google.com/config-connector/docs/concepts/installation-types) GKE config connector for each cluster
- [ ] [Enable workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable_on_cluster)
- [ ] Enable the services we will want to use with config connector ([1](https://cloud.google.com/config-connector/docs/how-to/getting-started), [2](https://cloud.google.com/config-connector/docs/how-to/getting-started#enable_the_service)

# Helm things

- [x] For each hub, create a [google cloud service account](https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iamserviceaccount) via config connector
- [x] For each hub, create a kubernetes service account as well. This will be provided to our user pods
- [x] Create an IAM policy binding to [bind](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to) the google cloud SA to the kubernetes SA
- [ ] Annotate each resource with [project id](https://cloud.google.com/config-connector/docs/how-to/organizing-resources/project-scoped-resources) so we don't need to set it at namespace level

**Comment by yuvipanda** [comment]
Almost all datasets use [requeser pays](https://cloud.google.com/storage/docs/requester-pays), so we should make sure our service account has enough credentials to do that.

**Comment by choldgraf** [comment]
@yuvipanda is this the reason for the Grenoble hub not having access?

How does this fit in with our billing model of "customer billing account pays for cloud resources, not 2i2c"?

**Comment by yuvipanda** [comment]
> How does this fit in with our billing model of "customer billing account pays for cloud resources, not 2i2c"?

Once they start paying us, they will get their own project. So any fees for this will get rolled into that. Of course, right now that money will come off 2i2c.



> What's the order of cost for requester fees? Do you know of a writeup for this?

The primary cost is [network charges](https://cloud.google.com/storage/pricing#network-pricing). It looks like it's actually free if it's in the same region! Our cluster is in `us-central1`, and I'm not sure where the source data is. Otherwise, it's $0.01 a GB, which can add up pretty easily. So we should put our users near their data.

**Comment by choldgraf** [comment]
Gotcha, so it'd be a "cloud charge" that'd behave the same as any other cloud charge like asking for a machine.

We should write up the boundary conditions for folks that specifically want to access Pangeo (like they need to use Google Cloud and they need to be in a certain region if they want to reduce costs)

**Comment by yuvipanda** [comment]
Yeah! It will also be nice if there was an easily accessible way to see which datasets produced by pangeo are on which cloud in what region.

**Comment by choldgraf** [comment]
I'd be surprised if this isn't something that @rabernat has thought about with Pangeo Forge as well

**Comment by yuvipanda** [comment]
@choldgraf totally! This issue actually is for any dataset hosted on Google Cloud, so I've updated title to match. Not pangeo specific.

**Comment by yuvipanda** [comment]
@choldgraf for now, how do we tell them to not fetch 5T of data? :D There isn't an easy way to surface this to the end user.

**Comment by roxyboy** [comment]
@yuvipanda At least for our pilot Jupyterhub, we can make sure not to fetch terabytes of data until we make the payment to 2i2c.

**Comment by choldgraf** [comment]
well, I think that if we're using a credits-based approach and they grab 5T of data, they'll quickly realize because the service will hit its limit and shut off until we re-charge. So maybe we need to:

1. Document the heck out of best-practices for this
2. Go with the "credits" approach so that we don't accidentally blow away somebody's whole budget

What do you think?

**Comment by yuvipanda** [comment]
@roxyboy haha, awesome. Try it out now and let me know how it goes?

**Comment by rabernat** [comment]
> Yeah! It will also be nice if there was an easily accessible way to see which datasets produced by pangeo are on which cloud in what region.

Everything is in GCS US-CENTRAL1

**Comment by roxyboy** [comment]
> @roxyboy haha, awesome. Try it out now and let me know how it goes?

We seem to able to call data from cloud now! Thank you!

**Comment by auraoupa** [comment]
Hi,
I'm a https://swot-ocean-pangeo.pilot.2i2c.cloud/ user and I am able to open data from pangeo catalog but not all of it.
The altimetry data cannot be opened (but can be opened from another cloud)
I tried this : 

```
from intake import open_catalog
cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/altimetry.yaml")
dssat  = cat["al"].to_dask()
```

for instance but the kernel dies everytime I do it. (default Python 3 kernel)
It is a small dataset (2.5Gb), so what could be the problem ?

Thanks for your help !
(I hope it is okay to post that here ...)

**Comment by yuvipanda** [comment]
@auraoupa the other data catalogs you are opening - are they smaller than 2.5GB? Kernel dying often just means too much memory being consumed...

**Comment by auraoupa** [comment]
Quite the opposite actually, I succeeded in opening 
```
cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/MEOM-NEMO.yaml")
ds  = cat["eNATL60_BLBT02_SSH"].to_dask()

```
which 1.7Tb !

**Comment by rabernat** [comment]
The difference here is the *in memory* requirements of the along-track datasets vs. the *lazy* memory requirements if the eNATL60_BLBT02_SSH dataset. Xarray loads all coordinates eagerly in order to do indexing. The 1D along-track datasets, despite being smaller than the gridded datasets, have more memory requirements at load time because their coordinate is as large as the data itself.

**Comment by auraoupa** [comment]
Ok I understand, it is true that the altimetry data I am trying to work with has more than 3 000 000 timesteps ...

**Comment by auraoupa** [comment]
Hi, me again ! Now that we have switched to a more production mode on https://meom-ige.2i2c.cloud/, I still want to access datasets from PANGEO catalog ! No kernel dying this time, the error message is 'Caller does not have serviceusage.services.use access to the Google Cloud project', does it have something to do with our GCP ?

**Comment by yuvipanda** [comment]
Aaah, good point. I'm working on it now.

**Comment by yuvipanda** [comment]
@auraoupa it should work now! I'm fiddling with doing some cluster level cleanup, so might have some downtime tomorrow. What is your general working TZ?

**Comment by auraoupa** [comment]
Thanks @yuvipanda ! I usually work from 9am to 6pm UTC+2 on week days, I will give it a try on Monday if you're done with the cluster cleanup ?

**Comment by yuvipanda** [comment]
@auraoupa oh it's fully functional now! You can keep using it, I'm testing out an alternate cluster setup. Once that's good I'll just move you over, you shouldn't see much disruption

**Comment by auraoupa** [comment]
Ok I thought you were still fiddling ;-) 
So I tested it and now the error is :
```
OSError: Forbidden: https://www.googleapis.com/download/storage/v1/b/pangeo-cnes/o/alti%2Fal%2F.zmetadata?alt=media
b'prod-user-sa@meom-ige-cnrs.iam.gserviceaccount.com does not have serviceusage.services.use access to the Google Cloud projec
```

**Comment by yuvipanda** [comment]
Can you share sample code / intake catalog that's causing this error?

**Comment by auraoupa** [comment]
Both 
`from intake import open_catalog
cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/altimetry.yaml")
dssat  = cat["al"].to_dask()`

and `cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/MEOM-NEMO.yaml")
ds  = cat["eNATL60_BLBT02_SSH"].to_dask()
`
are producing this error

**Comment by yuvipanda** [comment]
@auraoupa ah, hmm, ok. I think I'll just have to continue fiddling right now until this works out. Should be ready with the new cluster by monday - sorry about that!

**Comment by yuvipanda** [comment]
@auraoupa ok, try now! There should be more options for sizes, and I can execute the code you just shared :)

**Comment by auraoupa** [comment]
It is working fine now and the options for cluster sizes are here. Thanks a lot @yuvipanda for the quick fix, and working on it on the week end !

**Comment by yuvipanda** [comment]
yw, @auraoupa. Are you using dask-gateway? Or just dask with the large instances?

**Comment by auraoupa** [comment]
I usually use dask-gateway but can adapt if it is better for our cloud

**Comment by yuvipanda** [comment]
@auraoupa ah, no that's fine - dask-gateway has been working ok for you? We haven't been tuning the worker resource sizes there yet, so was asking mostly so we can do that together.

**Comment by auraoupa** [comment]
I didn't try yet to deploy dask-gateway on https://meom-ige.2i2c.cloud/ but I will gladly do it, what range of number of workers  can I ask for ? Can I do it from any instance ?
BTW, @roxyboy is launching local clusters from the large instance and it is working fine

**Comment by yuvipanda** [comment]
This is sorted out now, documented in https://github.com/2i2c-org/infrastructure/blob/master/docs/howto/features/cloud-access.md
