### ISSUE TITLE
nasa-cryo: Enable S3 Scratch Bucket for CryoCloud Hub

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2832]
via: https://2i2c.freshdesk.com/a/tickets/835

ICESat-2 Hackweek using the CryoCloud JupyterHub August 7-11. I think it would be very valuable to have a scratch bucket configured for participants (to auto-wipe data after a week or two)

Assigning @damianavila to schedule this before the hackweek.

**Comment by sgibson91** [comment]
If I'm reading the terraform correctly, this cluster should already have scratch buckets enabled

https://github.com/2i2c-org/infrastructure/blob/3d8a99502978148e87a1de925b822664a71a5fbe/terraform/aws/projects/nasa-cryo.tfvars#L16-L87

**Comment by sgibson91** [comment]
I think the real question here is why the environment variable to access the buckets is not showing up

**Comment by sgibson91** [comment]
I dug out the old uwhackweeks config and I think we are missing the `singleuser.extraEnv.SCRATCH_BUCKET` config

https://github.com/2i2c-org/infrastructure/pull/2235/files#diff-f1716f91b9a9fff5dc2970243b17185efcb99f608782122ac1f2cc48bff2a7eeL13-L16
