### ISSUE TITLE
Document features available to dask hubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#284]
Our dask hub features are woefully underdocumented. As of now, we provide:

1. A dask-gateway
2. Pre-emptible nodes for dask-workers (we should specify size and count)
3. Support for reading data stored in other projects in the cloud (#280). We should document the cost analysis of this, though
4. A 'scratch' bucket shared among all users in the hub and cleared every 7 days, useful for storing temporary storage.
5. Everything else provided by the 'base hub' on top of this.

We should document all this in a structured way.

**Comment by choldgraf** [comment]
I think that this information is now here: https://docs.2i2c.org/en/latest/about/distributions/index.html
