### ISSUE TITLE
Upgrade all k8s clusters to 1.25+

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2842]
Per https://2i2c.freshdesk.com/a/tickets/811, Kubernetes 1.24 will be unsupported starting January 2024. We should upgrade before that.

This is almost 6 months away, but we should go sooner than that.

Only cluster we actually have to do this for is arn:aws:eks:ca-central-1:259060176665:cluster/ubc-eoas

**Comment by consideRatio** [comment]
Ah, closing this in favor of #3224 with some more details.
