### ISSUE TITLE
Enable pulling from private nbgitpuller repos for Neurohackademy

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2848]
I couldn't quite figure out how to get our authenticated static website working again. So instead, for neurohackademy, we should:

1. Enable private github repo pulling for nbgitpuller access
2. Make an nbgitpuller link pointing to the private content (including the GitHub link)
3. We can distribute this link to end users, and it will be only available to authenticated users.

Ref https://github.com/2i2c-org/infrastructure/issues/2681#issuecomment-1629374195

**Comment by damianavila** [comment]
I think this one was completed by #2849 and #2762 and confirmed in #2681, so closing now (re-open if you disagree).
