### ISSUE TITLE
[EVENT] Smithsonian

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#2854]
### Summary

Teaching a course for about 20 users 7/24 - 8/5.  Having sufficient EC2 instances warmed up (8Gb and 1 cpu per user for around 20 users) would make the instructor's life a lot easier.

[Request received over email]

### Event Info

- **Community Representative:** @aewhite100
- **Event begin:** 2023-07-24
- **Event end:** 2023-08-05
- **Active times:** all day
- **Number of attendees:** 20
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**: https://smithsonian.2i2c.cloud/
- **Hub decommissioned after event?**: no

### Task List

**Before the event**

- [ ] Dates confirmed with the community representative and added to Hub Events Calendar.
- [ ] Quotas from the cloud provider are high-enough to handle expected usage.
- [ ] **One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  
- [ ] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [ ] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by sgibson91** [comment]
This has been scaled. I suggest we leave this open until the event is over and we can revert #2856

**Comment by jmunroe** [comment]
Thank you @sgibson91 !

**Comment by aewhite100** [comment]
Thanks again for the help everyone!

-Alex White
________________________________

**Comment by sgibson91** [comment]
Hey @aewhite100, your event appears to be over 🎉

We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!

- Did the infrastructure behave as expected?
- Anything that was confusing or could be improved?
- Any extra functionality you wish you would have had?
- Could you share a story about how you used the hub?

- Any other feedback that you'd like to share?

Lastly, are we good to begin scaling the cluster down?

**Comment by aewhite100** [comment]
Thanks Sarah. We are good to scale down now.

Everything worked exactly as expected. Students were able to get access to our hub quickly and easily. No extra functionality needed this time around.

This hub was used for an intercurricular course on data science and tropical biology held at the Smithsonian Tropical Research Institute in Panama (https://github.com/sidatasciencelab/UCSB_SI_scholars_STRI). All of our students are part of the UCSB-Smithsonian Scholars program (https://sidatasciencelab.github.io/education/si_scholars.html). Access to these compute resources is critical as we hold the course in remote locations and students are not always traveling with sophisticated compute hardware. The course was a huge success and our hub infrastructure was an important part of that success.

Thanks again,
Alex

Alexander E. White, PhD (he/him/his)
Biodiversity Research Data Scientist
Data Science Lab | https://datascience.si.edu/

Office of the Chief Information Officer
Smithsonian Institution | Washington D.C.


From: Sarah Gibson ***@***.***>
Date: Wednesday, August 9, 2023 at 6:01 AM
To: 2i2c-org/infrastructure ***@***.***>
Cc: White, Alexander E. ***@***.***>, Mention ***@***.***>
Subject: Re: [2i2c-org/infrastructure] [EVENT] Smithsonian (Issue #2854)
External Email - Exercise Caution

Hey @aewhite100<https://github.com/aewhite100>, your event appears to be over 🎉

We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!

  *   Did the infrastructure behave as expected?
  *   Anything that was confusing or could be improved?
  *   Any extra functionality you wish you would have had?
  *   Could you share a story about how you used the hub?
  *   Any other feedback that you'd like to share?

Lastly, are we good to begin scaling the cluster down?
