### ISSUE TITLE
Understand how we can best support Linux desktop on JupyterHub by talking to VICTOR folks

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2862]
The VICTOR folks are currently one of the heaviest users of our Linux Desktop feature on the JupyterHub. However, it's a custom image with a bunch of work to make repo2docker work with Linux Desktop. We should take the lessons learnt here, and make an upstream image of some sort.

I'm taking a call with them this wednesday to learn more about *how* they use it, and will report back here.

**Comment by yuvipanda** [comment]
I had a nice conversation with them! They love the linux desktop use case there, and are happy with the image. However, the current image has gotten quite complicated:

- There's a Linux PPA for Firefox.
- The building process is flaky because `mamba` takes too much memory, and github actions flakes quite often
- repo2docker files might not be the right choice here, because this is to support *both* python and linux desktop setups. There is exponential complication here.

We decided to take the following actions:

1. Split the image into two - one for python stuff (maybe based on pangeo docker image), and one for linux desktop stuff.
2. Offer profile options for both of these, so end users can pick and choose one when they start the project.

Given that there are at least 3 communities that are wanting linux desktop (VICTOR, CryoCloud / QGreenland (https://blog.jupyter.org/desktop-gis-software-in-the-cloud-with-jupyterhub-ddced297019a?postPublishedType=initial)) and NASA GHG (https://github.com/2i2c-org/infrastructure/issues/2799#issuecomment-1664457802)), I think we should support an *upstream* `jupyter-linux-desktop-notebook` docker image. Let's see how that goes.

**Comment by yuvipanda** [comment]
Based on this conversation, I've opened an upstream PR adding a linux-desktop-notebook to jupyter/docker-stacks!

**Comment by damianavila** [comment]
> Based on this conversation, I've opened an upstream PR adding a linux-desktop-notebook to jupyter/docker-stacks!

I was not able to locate that PR, when you have time can you link it here? Thanks!
