### ISSUE TITLE
Revert temp fix for leap health check 

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#2869]
### Context

Revert https://github.com/2i2c-org/infrastructure/pull/2865 once https://github.com/jupyterhub/kubespawner/issues/758 gets fixed/

**Comment by yuvipanda** [comment]
Until we fix this, we can't actually deploy this to other hubs.

**Comment by GeorgianaElena** [comment]
The temp fix doesn't exist anymore and we're redeployed unlisted_choice to leap. Closing this 🚀
