### ISSUE TITLE
Find 2 more communities that we think might benefit from `unlisted_choice`, demo the feature to them, and report back on how they would use it. Optionally, enable it for them as well.

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2874]

**Comment by yuvipanda** [comment]
I asked this to VEDA and they want it #3053

**Comment by abkfenris** [comment]
I know we're (OHW) is getting shut down at some point, but after seeing #3050 I'd love to have that option for our infrastructure team and tutorial presenters to be able test images in the future.

**Comment by GeorgianaElena** [comment]
@yuvipanda, the recent request in https://2i2c.freshdesk.com/a/tickets/935 made me think that this feature might be something that we wish to enable by default for communities that have a **staging hub** and **a profile list**, to allow them to test images before rolling them out on prod hubs?

**Comment by yuvipanda** [comment]
@GeorgianaElena yeah, I think perhaps enabling this in all staging hubs by default, and documenting that as the way to test images seems a good idea!

**Comment by yuvipanda** [comment]
Going to close this one, as we have a few communities that have this!
