### ISSUE TITLE
Meet with the community champion for LEAP to better understand how they would actually use the unlisted_choice feature

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#2876]

**Comment by jmunroe** [comment]
Email requesting a meet sent out.

**Comment by damianavila** [comment]
@jmunroe, can you capture the main ideas/follow-ups from the above content in independent new issues, and then we close this one? Thanks!

**Comment by jmunroe** [comment]
Here are three actions that follow from this meeting:

- https://github.com/2i2c-org/infrastructure/issues/2955 (suggestion for next sprint)
- https://github.com/2i2c-org/infrastructure/issues/2956 (backlog)
- https://github.com/2i2c-org/infrastructure/issues/2957 (backlog)
