### ISSUE TITLE
Meet with openscapes folks to understand their use of profiles and node sharing

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2882]

**Comment by damianavila** [comment]
@yuvipanda, did you meet with them?
If yes, did they mention the upcoming event: https://github.com/2i2c-org/infrastructure/issues/2841?

**Comment by yuvipanda** [comment]
@damianavila it's happening tomorrow.

**Comment by damianavila** [comment]
@yuvipanda, when you get back online, can you please update this issue with a summary of the content of that meeting? Thanks!

**Comment by jmunroe** [comment]
I have notes from that meeting: https://docs.google.com/document/d/1E_ugYVnFfXZh_kYdSF8zvMmLiF5hLa2V19_M606-JvE/edit?usp=sharing

**Comment by jmunroe** [comment]
Action items to be tracked coming out of that meeting:
- [ ] After the upcoming workshop, Yuvi to write up an issue to reduce the number of options on the Openscapes hub in advance of the October 17 event to only make the ‘medium machine’ is available
- [ ] 2i2c to create documentation to communicate what node share, cpu guarantee/limit, ram guarantee/limits means, how to assess memory used based on Grafana to make informed choices around resource usage.

**Comment by damianavila** [comment]
OK, let's keep this one open until both action items have issues associated with them.

**Comment by colliand** [comment]
The documentation request here overlaps with https://github.com/2i2c-org/meta/issues/659 and https://github.com/2i2c-org/meta/issues/660.

**Comment by yuvipanda** [comment]
This has very much driven our work on resource allocation (see #3030), and can be closed now.
