### ISSUE TITLE
Add funding info to imagebuilding-demo hub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2897]
This is funded by our binderhub work with GESIS, and we should credit it appropriately.

Per @arnim, we should include:

> Funded by the German Research Foundation (DFG), [CESSDA](http://www.cessda.eu/), and [GESIS](http://gesis.org/).
FKZ/project number:[460234259](https://gepris.dfg.de/gepris/projekt/460234259?language=en).

**Comment by arnim** [comment]
The important thing is that this can be used as a template for others to set up a hub that allows binder imports. Ideally, we should avoid any 2i2c-specific components and keep it as simple as possible.
