### ISSUE TITLE
AWS clusters: get `allowVolumeExpansion: true` by default in StorageClass, or document procedure to update it once

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2906]
We want our StorageClass resource to have `allowVolumeExpansion: true`, as that makes us able to increase the PVC's requested storage. This is a requirement for the troubleshooting docs [here for example](https://infrastructure.2i2c.org/howto/troubleshoot/prometheus/#running-out-of-disk-space).

I believe its not the default at least for AWS based clusters default StorageClass resource, but I think its the default for GCP based clusters.

**Comment by yuvipanda** [comment]
A lot of our prometheuses were down, so I did this now.

1. Make a script:
   ```bash
   #!/bin/bash
   echo "kubectl patch storageclass gp2 --patch '{\"allowVolumeExpansion\": true}'" | deployer use-cluster-credentials $1
   ```
2. Run this against all the clusters. This will just error out in GKE and Azure clusters, and that's fine:
   ```bash
   ls config/clusters | xargs -L1  ./wat.bash
   ```

**Comment by yuvipanda** [comment]
After that, I re-ran https://github.com/2i2c-org/infrastructure/actions/runs/5781619537 again, which completely passed this time. However, dynamic resizing only takes effect when the pod itself is recreated, so am doing that as well now.

**Comment by yuvipanda** [comment]
Given we've already manually done this for existing clusters, I think for new clusters, we should use https://github.com/2i2c-org/infrastructure/pull/2941 and manage storageclass explicitly. This alleviates r2r concerns that @sgibson91 raised in https://github.com/2i2c-org/infrastructure/pull/2718 as well as allows us to use the cheaper & better gp3 storageclass.
