### ISSUE TITLE
Timeouts when accessing prometheus metrics from grafana

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2934]
We have a few major issues with prometheus it seems:

- It seems prometheus has started to consumes more disk space
  #2930
- It seems prometheus regularly times out when grafana makes "last 30 days" requests for dashboards
  [Example query](https://grafana.pilot.2i2c.cloud/d/d560fa89-38bc-4253-964e-82573ea91d57/global-prometheus-health?orgId=1&from=now-30d&to=now)
- It seems we can no longer successfully access much historical data
  [Example query](https://grafana.pilot.2i2c.cloud/d/MMHgC_Qnz/cluster-information?orgId=1&from=now-7d&to=now&var-PROMETHEUS_DS=cloudbank)
  - Or maybe it was prometheus failing to scrape for a longer duration? It seems that it was a major gap between 2023-07-21 21:09 and 2023-08-05 18:58 UTC time for openscapes specifically.

**Comment by yuvipanda** [comment]
First and last bullet points are the same - the disk space has been full for a while, so there was no data collected. Let's focus discussion about that on https://github.com/2i2c-org/infrastructure/issues/2930.

**Comment by yuvipanda** [comment]
I've retitled this issue to focus purely on the grafana timeouts.

Looks like they are timing out at 30s mark. I looked in the nginx logs, and found that the error code is `499`, which means it's the *client* terminating the request. I raised the timeout in the grafana UI to 120s - the default for a prometheus *server* query termination. And now I see that this just caused a server restart. So at least, one part of the problem is that the grafana timeout is too small.

**Comment by yuvipanda** [comment]
The increased timeout in https://github.com/2i2c-org/infrastructure/pull/2942 now allows some more queries to load that weren't able to load before!

I think our next step is a 60s default timeout with nginx-ingress that needs to be raised, as that currently masks issues as well.

**Comment by yuvipanda** [comment]
<img width="1725" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/b819d669-db39-4c6c-a13b-a12faba60230">

This grafana panel showing CPU distribution in openscapes took 46s to load and was failing before this change.

**Comment by yuvipanda** [comment]
Evidence for nginx timeouts:

```
2023/08/07 17:30:38 [error] 2202#2202: *51229962 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.38.123, server: grafana.openscapes.2i2c.cloud, request: "POST /api/ds/query?ds_type=prometheus&requestId=Q113 HTTP/2.0", upstream: "http://192.168.60.215:3000/api/ds/query?ds_type=prometheus&requestId=Q113", host: "grafana.openscapes.2i2c.cloud", referrer: "https://grafana.openscapes.2i2c.cloud/d/hub-dashboard/jupyterhub-dashboard?orgId=1&viewPanel=11&from=now-90d&to=now"
192.168.38.123 - - [07/Aug/2023:17:30:38 +0000] "POST /api/ds/query?ds_type=prometheus&requestId=Q113 HTTP/2.0" 504 160 "https://grafana.openscapes.2i2c.cloud/d/hub-dashboard/jupyterhub-dashboard?orgId=1&viewPanel=11&from=now-90d&to=now" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0" 961 60.001 [support-support-grafana-80] [] 192.168.60.215:3000 0 60.001 504 fbb1f9a7c99e1114d422dc92ebe0785e
```

This is nginx that is fronting the grafana, timing out at 60s. Let's bump that up to 2min as well.

**Comment by yuvipanda** [comment]
Yay, with raising nginx timeout to 2min as well, more dashboards are now properly reporting than before. Here's a query that took 1m45s to run!

<img width="1724" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/0f61cc9e-cbc1-425f-9127-1c5f7010250a">

**Comment by consideRatio** [comment]
I think our config change in https://github.com/2i2c-org/infrastructure/pull/2731 influences whats discussed in https://www.youtube.com/watch?v=b_pEevMAC3I&t=12m20s (listen ~3 min from here), and that going for 10 minute blocks instead of ~2 hour blocks possibly scaled some work by a factor of 12 when querying etc. I figure the slow response _could be_ because of this factor of 12 change.

**Comment by yuvipanda** [comment]
This has been sorted out for the most part.
