### ISSUE TITLE
Create an actual flowchart to use existing and/or build your own image

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#2963]
Extracted from a Slack conversation that should (IMHO) inform this issue:

> This appears to me to be a breakdown of the sequence. Custom image generation by creating a repo should be an option for 'advanced users' but seems out of place as the first thing a community should try.  I would think that using the same image as 'Data-8' would be a better starting place. Here are the things I immediately notice when I try and comment on that issue:
I believe pointing new community reps to https://docs.2i2c.org/admin/howto/environment/ is too technical. But if not there, where should I be pointing users?
Which exact 'Data-8' image should be used? I know to look at the https://github.com/data-8 for general information but is t[here](https://docs.2i2c.org/about/distributions/education/#a-brief-overview-of-learning-hubs) a specific image I can get from there?   We reference it here as inspiration for what 2i2c does, but there is no specific information on what to do to get that?

I would recommend @jmunroe come up with a minimal flowchart based on the information he already has and then ask @yuvipanda to provide feedback on that proposal.

**Comment by yuvipanda** [comment]
I think @jnywong is working through this and this work is tracked elsewhere, so am going to close this here.
