### ISSUE TITLE
Performance issues in CosmicDS hub

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#2986]
### Context

Ref: https://github.com/2i2c-org/infrastructure/issues/2128

Particularly, https://github.com/2i2c-org/infrastructure/issues/2128#issuecomment-1661076249

> Hey @yuvipanda. Yes, you can go ahead and remove the generic auth now. The test did not go as well as hoped, and we were forced to revert back to our own deployment. There are a few facets to this that I had hoped we could talk about over our Zoom call, but many revolved around subpar performance when a handful of active users were on the hub, as well as a database communication issue which only seems to occur on the 2i2c hub and that we're hoping we can get access to the hub server logs to diagnose.

### Proposal

It seems a Zoom call would need to be scheduled in the future for getting details of the feedback provided above.

**Comment by yuvipanda** [comment]
@nmearl since https://github.com/2i2c-org/infrastructure/issues/2128#issuecomment-1690098583 was closed, let's move that conversation here.

You can look at the logs in the home directory - I think it's called `.jupyter-logs.txt` or similar.

**Comment by yuvipanda** [comment]
@nmearl great! I also sent you an email about your other authentication question!

**Comment by yuvipanda** [comment]
@nmearl ok, at least we no longer seem to require another refresh for the dashboard to load! Can you try that out?

Can you show me the repo used to build this image? Somehow the logs don't seem to be present still.

**Comment by nmearl** [comment]
@yuvipanda I confirm that the dashboard no longer needs another reload! Awesome.

The repo for the build image is [here](https://github.com/cosmicds/hub-user-image).

**Comment by yuvipanda** [comment]
yay! I'm going to close this one out now :)
