### ISSUE TITLE
Shared directories using up space?

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#2992]
### Context

In https://2i2c.freshdesk.com/a/tickets/890, it is reported that Neurohackademy are running out of space in their shared directories space. However, I cannot find anywhere in config or docs that describes how much space we set for these?

**Comment by yuvipanda** [comment]
This is same as space for all home directories, and it looks pretty low:

```
$  deployer exec-homes-shell 2i2c neurohackademy    
$ df -h
10.234.45.250:/homes/homes/neurohackademy  3.5T  3.3T   43G  99% /home
```

**Comment by yuvipanda** [comment]
I bumped up the capacity to 4T (https://github.com/2i2c-org/infrastructure/pull/2993) as otherwise I think this disk would've gotten full very soon.
