### ISSUE TITLE
Deploy `unlisted_choice` to NASA VEDA hub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3053]
From @j08lue on slack:

Great to see this released, @yuvipanda and @batpad! This is a power feature for very advanced users but maybe also less technical teams will use this in the future as a shortcut to sharing reproducible environments - we will see.
So, yes, please deploy this on the VEDA hub.
Do you have any 2i2c-side documentation of this feature yet? If not, we can just add some to the VEDA user docs for our needs.

**Comment by yuvipanda** [comment]
This has been deployed, and it was demo'd at the VEDA meeting today as well.

**Comment by j08lue** [comment]
I hope I did it justice - would like to prepare another demo for next time (early October), where I have an actual image ready.

**Comment by yuvipanda** [comment]
@j08lue yeah, a menu of custom images for people to choose from would be quite nice!
