### ISSUE TITLE
[INCREASED HUB ACTIVITY] UofToronto (Sept 11 to Dec 7)

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3073]
### Summary

In https://2i2c.freshdesk.com/a/tickets/930 an expected increased activity over the next few months is being reported for https://jupyter.utoronto.ca, related to STA130 at UofT, which has ~576 students.

### Event Info

There are multiple triggers for the increased hub activity as specified in the https://2i2c.freshdesk.com/a/tickets/930 ticket:

- ~576 students who will be working on (python) JuypterHub starting **Sept 11** from **Monday-Thursday** for **weekly Thursday 5 PM ET** assignments (and perhaps a few irregular submission dates as well)
- work on the course project will begin on **Oct 13**, with deadlines of **Oct 16, Nov 3, and Nov 13;**
- a final project due date of Dec 7, which **will necessitate increased JupyterHub usage** from the period of approximately **Nov 20 through Dec 7th**

#### Additional info
- The estimated required memory usage of this project is about 2MB

### Hub info

- **Hub URL**:  https://jupyter.utoronto.ca
- **Hub decommisioned after event?**:  No

**Comment by damianavila** [comment]
I have assigned @yuvipanda to lightly monitor next week's event given that he will be rotating through support during the start date (Sep 11th).

**Comment by yuvipanda** [comment]
We didn't have to do anything yay.
