### ISSUE TITLE
Deploy `unlisted_choice` to Openscapes staging

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3079]
### Context

Per @betolink's comment in https://github.com/2i2c-org/infrastructure/pull/3070#issuecomment-1706618062

**Comment by betolink** [comment]
Hi @GeorgianaElena, I'm trying to deploy the latest image and it's failing, I don't see the logs except for the ones provided by the hub.

```bash
2023-09-06T14:38:26Z [Normal] Container image "openscapes/python:510c78b" already present on machine
2023-09-06T14:40:10Z [Warning] Back-off restarting failed container
```
Is there something you can see on the Kubernetes side that may indicate why the container is not starting? I tested the image locally and it worked fine.

**Comment by betolink** [comment]
@GeorgianaElena, Yuvi found the following error on the Docker image 

```bash
cp: cannot stat '*.desktop': No such file or directory
```
So... I'm back to testing the image locally. This change is to include QGIS and the new `unlisted_choice`feature is going to be great to test these changes, thank you!!

**Comment by GeorgianaElena** [comment]
Yay! happy Yuvi was able to provide more details about what was going on!
