### ISSUE TITLE
Enable GitHub team method to grant/revoke user access to Research Delight hub

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#3099]
Following discussions with @damianavila and @jmunroe, I request an improvement to the research delight hub.

I want to be able to use the research delight hub for demonstrations with prospects. I suggest the following actions:

1. Create a `research delight team` inside the 2i2c GitHub organization.
2. Enable members of the `research delight team` to have access to the Research Delight hub. 
3. Enable @colliand and @jmunroe  to restrict `research delight team` members to have access to the GPU hardware profile. 

### Benefits

+ Partnerships can add and remove users to research delight. This enables demo usage for prospective sales.
+ 2i2c can invite users to access Research Delight to experiment with new features.
+ The demo usage of Research Delight should lower pressure for fast launches of new hub services.

**Comment by yuvipanda** [comment]
@colliand can you or James create the appropriate teams with names you desire, and then we can add them to the list of authorized teams?

**Comment by colliand** [comment]
Here is a team: https://github.com/orgs/2i2c-org/teams/research-delight-team

I'd like people in the 2i2c team to have access to all resources on research delight. I'd like people in the research-delight-team to NOT have access to the GPU. I'm not sure the best way to set this up (groups; membership in 2i2c org vs. research-delight-team team).

I'd like @jmunroe and @colliand to develop solid skills in managing team-based access and resource allocation.

**Comment by damianavila** [comment]
Assigned @yuvipanda to work on this one since he is already moving this conversation forward.

**Comment by yuvipanda** [comment]
This would require us to move from CILogon authentication to GitHub authentication for reserachdelight. I think that's ok.

**Comment by yuvipanda** [comment]
@colliand ok, https://github.com/2i2c-org/infrastructure/pull/3110 does this! I'd like you to create *another* team specifically for GPU access, and we can gate people on that.

**Comment by colliand** [comment]
Thanks Yuvi. Here is such a team: https://github.com/orgs/2i2c-org/teams/research-delight-gpu-team

**Comment by yuvipanda** [comment]
@colliand ok, done now. Should be made permanent when #3110 gets merged.

I don't know if we have enough documentation for this sort of access method. I leave that up to you and @jmunroe to figure out!

**Comment by colliand** [comment]
Thanks Yuvi for this rapid work. I wish you a nice weekend.
