### ISSUE TITLE
Write end user documentation (on 2i2c-org/docs repo) on specifying your own image

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3102]
This is focused on an end user, and designed to be a link given by community champions to *their* users. 

Example from @jbusecke at https://github.com/leap-stc/leap-stc.github.io/pull/80.

**Comment by consideRatio** [comment]
> This is focused on an end user, and designed to be a link given by community champions to _their_ users.

I appreciate this specification, I think it would be good if we are very mindful about the target audience for each piece of documentation we write. I think specificity that can help us maintain that specific doc page over time and the structure including it a lot easier.
