### ISSUE TITLE
[EVENT] SWOT Pangeo Grenoble

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#3126]
### Summary

Small demo of Dask XArray for a local event in Grenoble on Sept. 27

**_Configuration changes to profile required_** (please see next comment)

### Event Info

- **Community Representative:** @auraoupa
- **Event begin:** 27-Sept-2023
  - **In your timezone:** 
- **Event end:**  27-Sept-2023
  - **In your timezone:** 
- **Active times:** 
  - **In your timezone:** 
- **Number of attendees:** 60
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**: https://meom-ige.2i2c.cloud
- **Hub decommisioned after event?**:  no

### Task List

**Before the event**

- [ ] Dates confirmed with the community representative and added to Hub Events Calendar.
- [ ] Quotas from the cloud provider are high-enough to handle expected usage.
- [ ] **One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  
- [ ] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [ ] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by jmunroe** [comment]
Re: https://2i2c.freshdesk.com/a/tickets/958

The original request was to spin up a new hub just for this one demo event on their cluster (very similar to the DRAKKAR demo hub, now decommissioned).

I have suggested that rather than setting up a new hub and tearing it down, it would make more sense to use their main hub with a new profile option with node-sharing.

I have requested that @auraoupa create a new GitHub team in their https://github.com/meom-group organization with access restricted to just this new profile.

This hub currently is set up to use CILogon -> GitHub. I assume needs to be changed to just GitHub to support GitHub teams since that's what we recently did with the ResearchDelight hub.

I waiting on confirmation if this community wants a node group warmed up for the duration of the event (27-Sept-2023) or have the machines start as normal.

I am also waiting on confirmation of exactly how much RAM per user is needed for this demo as that will determine the machine type required for node-sharing.  60 participants are expected.

**Comment by jmunroe** [comment]
GitHub Teams:

- For the demo group only: https://github.com/orgs/demo-dask-grenoble2023/teams/demo
- And here is a new GH team to use for management of regular hub users:  https://github.com/orgs/meom-group/teams/hub-users

**Confirmed:** Please warm up the node poll to accommodate ~60 participants.

**Comment by auraoupa** [comment]
Hi ! Could it be possible to allow the authentification of the demo GH Team (https://github.com/orgs/demo-dask-grenoble2023/teams/demo) as soon as possible ? My co-presenter needs to connect to the hub and I will progressively add the participants in the list. Thanks !

**Comment by consideRatio** [comment]
I've condensed the information to:

1. Pre-start sufficient nodes to ensure no user needs to wait for startup is wanted
2. The required CPU/memory per user seems to be in the range of 8-16 CPU or 32-64 GB
3. Users of https://github.com/orgs/demo-dask-grenoble2023/teams/demo (demo-dask-grenoble2023:demo) should have temporary access
4. Users of https://github.com/orgs/meom-group/teams/hub-users (meom-group:hub-users) should remain having access like before

Technically my suggestion becomes that we add an option to start a server on a n2-highmem-64 machine (/64 CPU, 512GB), where users can request a share of ~16, ~32, or ~64 GB of memory.

This means that we can fit 32, 16, or 8 users per node. I'll make sure that two such nodes are started ahead of time for the event and already running, which would make the wait time a few seconds only for 64 users - but could incurr a few minutes of wait to fit all 50-60 users if larger node share options are selected.

I'll work on applying this now and write again once I'm done!

**Comment by consideRatio** [comment]
## Authentication

@auraoupa okay we are almost done, I need your help to complete this though. Are you an admin of the github organizations `meom-group` and `demo-dask-grenoble2023`?

We need to have an admin of these github organizations to press a "Grant" button when logging in next to `meom-group` and `demo-dask-grenoble2023`. It should be done in a screen looking like this (here `jupyterhub` has a "Grant" button next to it).

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/b320afbe-f0a1-4991-8fe6-52989907435f)

## Here is a procedure to follow

This should be done for the staging hub and the production hub, but once its done this doesn't need to be done by any other user.

**staging.meom-ige.2i2c.cloud**

1. Logout at https://staging.meom-ige.2i2c.cloud/hub/logout
2. Login at https://staging.meom-ige.2i2c.cloud/hub/login, but don't continue directly - press the Grant button next to "meom-group" and "demo-dask-grenoble2023" respectively.

**meom-ige.2i2c.cloud**

1. Logout at https://meom-ige.2i2c.cloud/hub/logout
2. Login at https://meom-ige.2i2c.cloud/hub/login, but don't continue directly - press the Grant button next to "meom-group" and "demo-dask-grenoble2023" respectively.

## Description of setup

When a github user only part of the `demo-dask-grenoble2023` organization's team `demo`, they will only see this option:
![image](https://github.com/2i2c-org/infrastructure/assets/3837114/c9b71e1f-93c7-4263-a395-805b0aaf0ab2)

When a github user part of `meom-group` organization's team `hub-users`, they will see that option and the ones that was around before.

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/5812baa7-ecfc-4c0c-88ec-66af8b45da8e)

**Comment by auraoupa** [comment]
Ok @consideRatio, I've granted access for both organization and both clouds, I hope it is ok ? As for Grenoble demo users, I think it would be best if they only had one option, the 32GB RAM, if it is still possible ? Thanks !

**Comment by consideRatio** [comment]
> As for Grenoble demo users, I think it would be best if they only had one option, the 32GB RAM, if it is still possible ?

I'll make it so that all users have one option, is that okay? It takes a bit of trickery to make it so that you can see the same thing but have different resource allocations.

**Comment by auraoupa** [comment]
Ok perfect, thanks

**Comment by consideRatio** [comment]
@auraoupa excellent. The change to only see the 32GB option should take effect in 5 minutes I think.

I'm ending my workday in Sweden now, but I'll check back on this early morning tomorrow.

**Comment by consideRatio** [comment]
(track deployment status in https://github.com/2i2c-org/infrastructure/actions/runs/6302246380, maybe takes a bit more than 5 minutes)

**Comment by aureliealbertmeom** [comment]
Hi @consideRatio and @jmunroe ! Just to let you know that yesterday's went fine ! I think people were pleased to run the tuto smoothly. I told them to scale down the cluster they launched otherwise one could take all the procs and ram of the warmed up nodes. We can now revert to the usual users of the deployment (https://github.com/orgs/meom-group/teams/hub-users). Thanks again for the nice deployment

**Comment by damianavila** [comment]
Since #3179 was merged, I am now going to close this one.
Feel free to reopen if you disagree.
