### ISSUE TITLE
Improve the high-level descriptions around the 2i2c Hub service

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#314]
# Background

There are two major places where we introduce and discuss the 2i2c Hub Service pilot:

- [the pilot documentation](http://pilot.2i2c.org/)
- [the 2i2c hubs page](https://2i2c.org/infrastructure/)

We should take a pass at both of them to make sure that we are discussing and highlighting aspects of our Hub Service that we wish. For example, here are a few things that I think we should improve:

- on 2i2c.org, the things we discuss don't quite match the services that we offer
- explain more the pilot project in general at an organizational level
- standardize on terminology for the pilot (is it a 2i2c Hub, a 2i2c Hub service, etc)
- update expectations around the Managed Service Plan, and link to it when we feel ready to do so
- Improve the "overview" section that describes what a 2i2c Hub is
- Explain more our justification for why we use the technology stack that we do, and why this is the right stack for others to use
- More generally, have a strategy for what information is on 2i2c.org, and what is on pilot.2i2c.org, and how will people flow between them

# Expected timeline

We should make iterative improvements to the documentation over the next several months, but should plan on a "deep dive" on the docs after we've had a moment for others to use the docs, run through a few customers, etc.

# Steps to complete this goal

The main thing we should do to complete this goal is have a deep dive on the docs as a group of one or more people, and make updates until we are satisfied with the "next iteration" of describing the hub services. We should also run the docs by a few others to get their feedback.

**Comment by yuvipanda** [comment]
I opened https://github.com/2i2c-org/2i2c-org.github.io/pull/42 to discuss nomenclature of what we offer.

**Comment by yuvipanda** [comment]
> More generally, have a strategy for what information is on 2i2c.org, and what is on pilot.2i2c.org, and how will people flow between them

I wrote about this a little bit in our page on [documentation structure](https://pilot-hubs.2i2c.org/en/latest/structure.html). I see the following structure:

1. Website - for people who are trying to understan *what* 2i2c does, and see if it is interesting to them. 
2. Pilot docs - for people who are *already* using our managed JupyterHubs, and need to figure out how to accomplish things they want to do. This could also be used by people in advanced stages of evaluating us.
3. Pilot hubs docs - for 2i2c operators, and others in the open source community who can benefit from this.

How does that sound?

**Comment by yuvipanda** [comment]
I think there's other useful tickets tracking this more specifically.
