### ISSUE TITLE
AWS billing permissions need to be migrated until December 2023

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3169]
### Context

We received a notice in https://2i2c.freshdesk.com/a/tickets/994 about our AWS billing policies needing to be updated until December 2023!

I don't think we have setup automated billing on AWS https://github.com/2i2c-org/infrastructure/issues/2779, right?

But I did found out a [`BillingFullAccess` policy](https://us-east-1.console.aws.amazon.com/iamv2/home#/policies/details/arn%3Aaws%3Aiam%3A%3A746653422107%3Apolicy%2FBillingFullAccess?section=policy_permissions) defined in 2i2c-sandbox main account, attached to @yuvipanda's account.

This is the policy that needs to be updated to use more fine-graided permissions, according to https://aws.amazon.com/blogs/aws-cloud-financial-management/changes-to-aws-billing-cost-management-and-account-consoles-permissions/.

Alternatively, aws provides a bulk migrator:
<img width="710" alt="Screenshot 2023-09-25 at 10 44 24" src="https://github.com/2i2c-org/infrastructure/assets/7579677/0c2b9be5-eb85-40c2-aa95-b161739f0d21">

### Updates and actions
- identify which are the fine-grained permissions we want
- ...?

**Comment by GeorgianaElena** [comment]
@consideRatio, makes sense! Thank you!

**Comment by yuvipanda** [comment]
I've evaluated this message, and found that we already attach the correct policy (https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/policies/details/arn%3Aaws%3Aiam%3A%3Aaws%3Apolicy%2Fjob-function%2FBilling?section=permissions&view=json) via the `tech` group to everyone. I've removed the policy that had issues, and can confirm I still have access.
