### ISSUE TITLE
[EVENT] CryoCloud upcoming small events

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3170]
### Summary

https://2i2c.freshdesk.com/a/tickets/993

#### NSIDC User Working Group meeting:
**Date for the event:** Sept 26
**Active times:** 11am - 3 pm PT
**How many people will attend the event:** 13
**Do you need to need hub infrastructure to be pre-initialized before the event?** If possible, but not required
Any other information that will help us prepare for the extra usage during the event - This will be a small demo to show how NSIDC data is accessed from the cloud 

#### Icesat-2 Science Team meeting workshop:
**Date for the event: ** Oct 5
** The active times for the event (e.g., 9am to 5pm US/Pacific): ** 12 pm - 530 pm PT
**How many people will attend the event:** 13
** Do you need to need hub infrastructure to be pre-initialized before the event?** Would be awesome, but not required

### Hub info

- **Hub URL**: 
- **Hub decommisioned after event?**: 

### Task List

**Before the event**

- [ ] Dates confirmed with the community representative and added to Hub Events Calendar.
- [ ] Quotas from the cloud provider are high-enough to handle expected usage.
- [ ] **One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  
- [ ] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [ ] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by damianavila** [comment]
Given the nature of small events, I have assigned to @GeorgianaElena and @sgibson91 who are/are going to be involved with the support cycle during the time these events will run. I expect the first one to be handled (monitored, actually) by @GeorgianaElena and the second one to be handled (monitored) by @sgibson91.

**Comment by GeorgianaElena** [comment]
The date of these events has passed. I am not aware of any tickets coming in during this period, so I believe things went ok. Closing.
