### ISSUE TITLE
[r.datatools.utoronto.ca] RStudio Knit to PDF takes a long time first time it is run

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3178]
### Context

Reported in https://2i2c.freshdesk.com/a/tickets/1001 as "knitting to PDF not working the first time" but then working on a second try.

Initial request from the community was to implement a mechanism to let the users know to try knitting a second time.

 @yuvipanda requested details about the errors seen the first time and the following screenshot was provided:

![screenshot-kintting](https://github.com/2i2c-org/infrastructure/assets/7579677/22f34c0d-80a1-4d66-bc03-8e55efd2dbc5)

### Actions

My initial efforts trying to get to the bottom of why the first try is unsuccessful revealed were to try to run a knit to pdf myself which in my case revealed that:

- there weren't any fatal errors and the pdf was generated at the end
- HOWEVER, it took ~3 to 4 min of installing various packages before that was succesfull
- from the [`tlmgr`](https://tug.org/texlive/doc/tlmgr.html#DESCRIPTION) logs at `/opt/texlive/texmf-var/web2c/tlmgr.log`, the packages installed were:
```bash
[Wed Sep 27 08:35:18 2023] install: amsmath
[Wed Sep 27 08:35:18 2023] install: latex-amsmath-dev
[Wed Sep 27 08:35:18 2023] command: mktexlsr
[Wed Sep 27 08:35:18 2023] command: mtxrun --generate
[Wed Sep 27 08:35:34 2023] install: iftex
[Wed Sep 27 08:35:34 2023] command: mktexlsr
[Wed Sep 27 08:35:35 2023] command: mtxrun --generate
[Wed Sep 27 08:36:03 2023] install: ec
[Wed Sep 27 08:36:03 2023] command: mktexlsr
[Wed Sep 27 08:36:03 2023] command: mtxrun --generate
[Wed Sep 27 08:36:22 2023] install: kvoptions
[Wed Sep 27 08:36:22 2023] command: mktexlsr
[Wed Sep 27 08:36:22 2023] command: mtxrun --generate
[Wed Sep 27 08:36:39 2023] install: ltxcmds
[Wed Sep 27 08:36:39 2023] command: mktexlsr
[Wed Sep 27 08:36:39 2023] command: mtxrun --generate
[Wed Sep 27 08:36:56 2023] install: kvsetkeys
[Wed Sep 27 08:36:56 2023] command: mktexlsr
[Wed Sep 27 08:36:56 2023] command: mtxrun --generate
[Wed Sep 27 08:37:13 2023] install: etoolbox
[Wed Sep 27 08:37:13 2023] command: mktexlsr
[Wed Sep 27 08:37:13 2023] command: mtxrun --generate
[Wed Sep 27 08:37:30 2023] install: xcolor
[Wed Sep 27 08:37:30 2023] command: mktexlsr
[Wed Sep 27 08:37:30 2023] command: mtxrun --generate
[Wed Sep 27 08:37:47 2023] install: geometry
[Wed Sep 27 08:37:47 2023] command: mktexlsr
[Wed Sep 27 08:37:47 2023] command: mtxrun --generate
[Wed Sep 27 08:38:04 2023] install: fancyvrb
[Wed Sep 27 08:38:04 2023] command: mktexlsr
[Wed Sep 27 08:38:04 2023] command: mtxrun --generate
[Wed Sep 27 08:38:21 2023] install: framed
[Wed Sep 27 08:38:21 2023] command: mktexlsr
[Wed Sep 27 08:38:21 2023] command: mtxrun --generate
[Wed Sep 27 08:38:39 2023] install: auxhook
[Wed Sep 27 08:38:40 2023] install: bigintcalc
[Wed Sep 27 08:38:40 2023] install: bitset
[Wed Sep 27 08:38:41 2023] install: etexcmds
[Wed Sep 27 08:38:41 2023] install: gettitlestring
[Wed Sep 27 08:38:41 2023] install: hycolor
[Wed Sep 27 08:38:42 2023] install: hyperref
[Wed Sep 27 08:38:43 2023] install: intcalc
[Wed Sep 27 08:38:43 2023] install: kvdefinekeys
[Wed Sep 27 08:38:44 2023] install: letltxmacro
[Wed Sep 27 08:38:44 2023] install: pdfescape
[Wed Sep 27 08:38:45 2023] install: refcount
[Wed Sep 27 08:38:45 2023] install: rerunfilecheck
[Wed Sep 27 08:38:46 2023] install: stringenc
[Wed Sep 27 08:38:46 2023] install: uniquecounter
[Wed Sep 27 08:38:47 2023] install: zapfding
[Wed Sep 27 08:38:47 2023] command: mktexlsr
[Wed Sep 27 08:38:47 2023] command: mtxrun --generate
[Wed Sep 27 08:38:47 2023] command: updmap-sys
[Wed Sep 27 08:39:05 2023] install: pdftexcmds
[Wed Sep 27 08:39:05 2023] command: mktexlsr
[Wed Sep 27 08:39:05 2023] command: mtxrun --generate
[Wed Sep 27 08:39:22 2023] install: infwarerr
[Wed Sep 27 08:39:22 2023] command: mktexlsr
[Wed Sep 27 08:39:22 2023] command: mtxrun --generate
[Wed Sep 27 08:39:41 2023] install: epstopdf-pkg
[Wed Sep 27 08:39:41 2023] command: mktexlsr
[Wed Sep 27 08:39:41 2023] command: mtxrun --generate
```
- the subsequent calls to knit to pdf, these packages are found and the generation happens almost instantly
- any restart of the user server undoes the installation

### Proposal

We should get the missing packages needed for pdf knitting into the user image at  https://github.com/2i2c-org/utoronto-r-image (either directly, or in the base rocker/geospatial image I imagine?)

According to https://wiki.archlinux.org/title/TeX_Live#Arch-packaged_TeX_Live, there are some texlive groups which contain various groups of packages .

**Comment by yuvipanda** [comment]
Based on the error message I see in the original (very blurry?!) screenshot, I think perhaps it's trying to download the 2023 version of texlive while 2022 is frozen. Is there a higher res version?

**Comment by yuvipanda** [comment]
I originally thought this might just require a rebuild, but looking at https://github.com/2i2c-org/utoronto-r-image I see it was rebuilt two weeks ago.

**Comment by GeorgianaElena** [comment]
> Based on the error message I see in the original (very blurry?!) screenshot,

@yuvipanda, I pasted below how every package install is logged. The tex live being frozen log is repeated before every install.

```bash
TeX Live 2022 is frozen
and will no longer be routinely updated.  This happens when a new
release is made, or will be made shortly.

For general status information about TeX Live, see its home page:
https://tug.org/texlive

TeX Live 2022 is frozen
and will no longer be routinely updated.  This happens when a new
release is made, or will be made shortly.

For general status information about TeX Live, see its home page:
https://tug.org/texlive

tlmgr: package repository https://www.texlive.info/tlnet-archive/2023/03/14/tlnet (not verified: gpg unavailable)
[1/2, ??:??/??:??] install: amsmath [31k]
[2/2, 00:01/00:01] install: latex-amsmath-dev [31k]
running mktexlsr ...
done running mktexlsr.
running mtxrun --generate ...
done running mtxrun --generate.
tlmgr: package log updated: /opt/texlive/texmf-var/web2c/tlmgr.log
tlmgr: command log updated: /opt/texlive/texmf-var/web2c/tlmgr-commands.log
```

**Comment by GeorgianaElena** [comment]
It looks like the texlive version installed is `TeX 3.141592653 (TeX Live 2022)` for some reason instead of a 2023 one, as specified by the geospatial:4.2.2 base image (based on verse:4.2.2)

https://github.com/rocker-org/rocker-versioned2/blob/c6152e1d5db5e29ee41d8bc0873de9b0ef17861b/dockerfiles/verse_4.2.2.Dockerfile#L8

https://github.com/rocker-org/rocker-versioned2/blob/c6152e1d5db5e29ee41d8bc0873de9b0ef17861b/dockerfiles/verse_4.2.2.Dockerfile#L8

**Comment by GeorgianaElena** [comment]
The `TeX Live 2022` is actually the version installed from the geospatial image through https://www.texlive.info/tlnet-archive/2023/03/14/tlnet/

**Comment by GeorgianaElena** [comment]
We could upgrade the base image from geospatial:4.2.2 to geospatial:4.3.0 which looks to come with a newer textlive version (the on e at https://www.texlive.info/tlnet-archive/2023/06/15/tlnet/)

https://github.com/rocker-org/rocker-versioned2/blob/c6152e1d5db5e29ee41d8bc0873de9b0ef17861b/dockerfiles/verse_4.3.0.Dockerfile#L8C15-L8C70

@yuvipanda, do you think a more up to date version of texlive might solve this?

**Comment by yuvipanda** [comment]
@GeorgianaElena I think we have two options:

1. Bump to 4.3.0, which should solve this. But it might also update version of R and libraries, and mid-semester might not be a good time
2. Explicitly use `tlmgr` to install 2023 in the current Dockerfile, and schedule 4.3.0 bump end of semester.

I suggest you ask them if we could do (1), as that would solve problems for now and in the future :D If not, let's do (2), and document this someplace?

**Comment by GeorgianaElena** [comment]
@yuvipanda, we got the green light to bump the base image to 4.3.0 during the Nov. 6 – 10 interval, when the Arts & Science is scheduled to have a reading week.

cc @damianavila to help with making sure we plan this appropriately.

**Comment by GeorgianaElena** [comment]
I also opened https://github.com/2i2c-org/utoronto-r-image/issues/9 for the specific upgrade task

**Comment by yuvipanda** [comment]
@GeorgianaElena great, thanks for following up!

**Comment by yuvipanda** [comment]
With https://github.com/2i2c-org/utoronto-r-image/pull/11, it is faster - but a couple packages (`epstopdf-pkg` and `framed`) still get installed at runtime.

I'll investigate and see if this should be patched upstream.

**Comment by yuvipanda** [comment]
This has been fixed.
