### ISSUE TITLE
Identifying and configuring a time to start performing the backup of homedirs (AWS only atm)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3186]
Its useful for us to **know and intentionally decide when backups are to be made**, I currently think of two reasons for this:

1. **Backup consistency**
   Backups made while the content is actively worked may become inconsistent, so we want to choose a time to start making the backup when we expect the least activity
2. **Ease of working with them**
   Backups made between a community's users typically activity periods will be easier to work with, because it allows us to say that "sometime between day A and day B during your nighttime" etc, as compared to "in the middle of the day, so maybe you want us to restore to the day 1 or 2 depending on when the corruption took place, can you check?"

I suggest we:

- [ ] make an estimate when low activity occur based on past usage for existing clusters
- [ ] establish procedure to ask for an estimate for new clusters

**Comment by yuvipanda** [comment]
The default is fine I think.
