### ISSUE TITLE
Update jupyterhub-configurator to a newer commit

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3197]
I saw that jupyterhub-configurator is using an outdated commit from 2021, even though there are quite a few of more recent from at least 2022.

**Comment by consideRatio** [comment]
Need to debug how things has changed using git history, as upgrading leads to a view looking like:

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/66843809-529d-4667-8722-58b4f0175e98)

Commits to compare: https://github.com/yuvipanda/jupyterhub-configurator/compare/ed7e3a0df1e3d625d10903ef7d7fd9c2fbb548db...main

**Comment by consideRatio** [comment]
Our config breaks against https://github.com/yuvipanda/jupyterhub-configurator/commit/f356175732d487c520415b84368b3368397d8b60 that removes `c.Configurator.schemas` that we use.

**Comment by consideRatio** [comment]
I didn't get this done quick enough and can't finalize any fix this week.

Whats known is:

- With jupyterhub 4.1.0 with our current commit for jupyterhub-configurator, we get stuck like this:
  ![image](https://github.com/2i2c-org/infrastructure/assets/3837114/feb4d979-b872-47b7-990b-748e71fdaebb)
  ![image](https://github.com/2i2c-org/infrastructure/assets/3837114/703d9688-105f-4209-b2f7-92c2c66d7784)

- With jupyterhub 4.1.0 with the latest commit for jupyterhub-configurator, we get stuck like this:
  ![image](https://github.com/2i2c-org/infrastructure/assets/3837114/be039ea4-4f7e-45d3-b9d2-09719ebaa1eb)
  Due to breaking changes in https://github.com/yuvipanda/jupyterhub-configurator/commit/f356175732d487c520415b84368b3368397d8b60 removing `Configurator.schemas` that we configure in our Dockerfile, by loading .json files we've mounted on the hub pod via:
  https://github.com/2i2c-org/infrastructure/blob/82e9f0dd0e81be9abe8cb71608e93e3d4f6e6de9/helm-charts/basehub/values.yaml#L611-L643

**Comment by yuvipanda** [comment]
I think we should just say jupyterhub-configurator is deprecated, leave it as is, and work on newer methodologies to handle the things it does - https://github.com/2i2c-org/infrastructure/issues/2564 has more information. My inclination is to mark this as wontfix.

**Comment by consideRatio** [comment]
The configurator's failure to function with JupyterHub 4.1.0 is blocking #3818, and its still actively used making removing it complicated. I don't want to have a z2jh upgrade blocked, and I don't want to quickly phase out the configurator and quickly phase in an alternative - due to that, I'd like to priotize this getting done.

**Comment by yuvipanda** [comment]
Ah, didn't realize it was blocking something else. Responded in https://github.com/2i2c-org/infrastructure/pull/3818#issuecomment-2013125250

**Comment by consideRatio** [comment]
I opened https://github.com/yuvipanda/jupyterhub-configurator/pull/19 and then backported that work into a branch called `backported-jh41-compatibility` that isn't breaking for our basehub chart to start using.

I'll mark this issue to be closed by #3818 now
