### ISSUE TITLE
nasa-ghg: need to refresh credentials (done), and provide engineers with access (to be confirmed)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3211]
I'm not confident about the situation here, but is nasa-ghg a cluster like nasa-veda with a need to update a token regularly etc? I don't have a user with access to the nasa-ghg account I think - or do I?

```
An error occurred (UnrecognizedClientException) when calling the DescribeCluster operation: The security token included in the request is invalid.

...

CalledProcessError: Command '['aws', 'eks', 'update-kubeconfig', 
'--name=nasa-ghg-hub', '--region=us-west-2']' returned non-zero exit status 254.
Error: Process completed with exit code 1.
```

This failure is from https://github.com/2i2c-org/infrastructure/actions/runs/6384535727/job/17327723133

**Comment by yuvipanda** [comment]
I thought i had created accounts for everyone but apparently I had not? I'll check and try to make sure everyone has access.

**Comment by consideRatio** [comment]
@yuvipanda I figure for a new SMCE based AWS account, we need to be setup with AWS IAM Users under the account - I'm not confident this is something we are allowed to do ourselves. Wasn't SMCE involved in providing us with IAM accounts for the nasa-veda AWS Account?

**Comment by consideRatio** [comment]
@sgibson91 resolved this for me and is now working to ensure everyone has an AWS IAM user in the nasa-ghg account, I'll re-generate the deployer credentials now!

**Comment by yuvipanda** [comment]
I just got my access back (I had let my password not be changed for 60 days). Let's keep this open until everyone else gets access too.

**Comment by yuvipanda** [comment]
Oh, and if we do miss the 60 day deadline, it's actually possible for us to reset each others's passwords! This does make things significantly easier :)

1. Someone in the team with access logs into the AWS console
2. Follow https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_passwords_admin-change-user.html#id_credentials_passwords_admin-change-user_console to reset the password for whoever's 60day window has lapsed
3. In addition, a `AccountDisabled` IAM Group will be automatically added to the user whenevere their credentials expire, and this will show up as a weird 'can not change password' error when the user logs in next. So the user should also be removed from this group. You can do so from under the 'Groups' tab in the AWS console when looking at the details of this user.

This + the fact that we're actually being paid extra for this makes this more palateble to me than some other orgs that mandate their own auth.

**Comment by consideRatio** [comment]
## Action points

Verify configured access to the smce-ghg-center AWS account (for nasa-ghg cluster), you need to have MFA activated via IAM -> Users -> "Add MFA" button as well.

- [x] `@consideRatio`
- [x] `@yuvipanda`
- [x] `@sgibson91`
- [ ] @GeorgianaElena
- [ ] @damianavila

**Comment by sgibson91** [comment]
@damianavila @GeorgianaElena if you can confirm that you have access to nasa-ghg AWS account and enabled MFA, then we can close this issue

**Comment by sgibson91** [comment]
I have opened https://github.com/2i2c-org/infrastructure/pull/3510 to capture the process to regenerate passwords for each other from https://github.com/2i2c-org/infrastructure/issues/3211#issuecomment-1747624787

**Comment by damianavila** [comment]
I do have access as well.

Btw, related comment: https://github.com/2i2c-org/infrastructure/issues/2434#issuecomment-1846220498
