### ISSUE TITLE
Cleanup 2i2c/cosmicds as its now running in 2i2c-aws-us/cosmicds ?

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3226]
I saw that we had a cosmicds namespace in the 2i2c cluster, and got stuck confused about why its `hub` pod hadn't been restarted recently as part of an upgrade.

It was migrated to the 2i2c-aws-us cluster before, should we cleanup its remnants in the 2i2c cluster?

**Comment by yuvipanda** [comment]
Yep it can be cleaned up now.

**Comment by yuvipanda** [comment]
Just did this.
