### ISSUE TITLE
Grafanas show empty due to how variables are refreshed

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3237]
A lot of Grafana dashbaords are currently showing 'no data'

<img width="1801" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/9ef3f766-edcc-4c31-bbac-fe168c2cdd2b">

But the data is there, the problem is how variables are refreshed. Particularly the $hub variable. Even though on the top left it says 'All' that's not actually true.

<img width="207" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/6c76d970-c6e3-4067-a91e-2841d6ea80b3">

Note that the dropdown doesn't actually contain any actual values.

If you go to settings -> variables -> `$hub` and scroll down, you'll see it's empty:

<img width="428" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/69348c17-d338-45fd-9ea0-7f803eaeaeb5">

And selecting `Run query` does not help either with refreshing the list of variables.

**Comment by consideRatio** [comment]
I ran into this ~2 minutes ago and didn't understand what was going on! Thanks for helping me understand this related to a grafana query issue!

**Comment by yuvipanda** [comment]
Temporary fix is:

1. Set time range to 30 days (smaller amount doesn't seem to work)
2. Go back into settings -> variables -> `$hub`
3. HIt 'run query' at the bottom. List of hub values should show up here now.

**Comment by consideRatio** [comment]
This is a hub response summary for a lot of different hubs. I think it could be relevant to increase the request from 10m as we have now (0.01 or 1%) to something a bit more, like 50m. But what we have now seems to not cause major trouble.

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/61aa93ff-37a5-4749-bd4a-a6e5b966226f)

The `ucmerced` and `temple` hub are active hubs with ~100 users, they have peaks around 100m, and regular usage at ~30m.

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/0eb6bdfb-4783-4099-a7af-77cc522f1f32)

Inactive hubs are typically idling at 10m.

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/86673360-3234-45e9-9ddd-c94d90fc22dd)

**Comment by yuvipanda** [comment]
Another workaround is to put `.*` in the 'custom all' value for the $hub variable:

<img width="331" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/88759b56-c725-4efc-96dc-6a3fce75d152">

**Comment by yuvipanda** [comment]
I've opened https://github.com/jupyterhub/grafana-dashboards/pull/91 which will implement the latest workaround for all hubs so we don't end up with 'no data'

**Comment by yuvipanda** [comment]
This PR has been deployed on the openscapes hub and tested.

**Comment by consideRatio** [comment]
PR merged upstream, re-deploying grafana dashboards via https://github.com/2i2c-org/infrastructure/actions/runs/6573134344

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/grafana-dashboards/pull/100 was a follow up PR that was needed
