### ISSUE TITLE
Investigate coalescing daskhub into basehub

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3252]
We provide a basehub chart, and a daskhub chart depending on basehub and dask-gateway. If we could provide basehub with some chart configuration to install dask-gateway directly instead of having two separate charts, it would be good for reasons motivated in #502.

To practically coalesce our daskhub into basehub is a big undertaking, so this is an issue focusing on initial steps if we want to work towards it.

## Action point ideas

- Review all coupling of chart config in [daskhub/values.yaml](https://github.com/2i2c-org/infrastructure/blob/HEAD/helm-charts/daskhub/values.yaml)
- Summarize how various parts in daskhub/values.yaml could translate to configuring a basehub depending on dask-gateway directly
- Evaluate if and how we could transition our existing daskhub chart installations
- Consider future action points

## History

- #362
- #502

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/pull/3826 is another reason to do this - we have some defaults in the 'daskhub' chart that don't have anything to do with dask.

**Comment by yuvipanda** [comment]
As I work on https://github.com/2i2c-org/meta/issues/854, this is clear as something that will help us move faster if resolved. In particular, right now, we have to decide at the *very* start of setting up a hub if it should need dask or not. This is unncessary point of friction. 

The same way that `binderhub-service` is now an optional item in `basehub`, so should be dask-gateway.

There are two parts here:

1. Turning `dask-gateway` into an optional part of `basehub`
2. Migrating all the existing `daskhub` installations

**Comment by yuvipanda** [comment]
Closing in favor of https://github.com/2i2c-org/infrastructure/issues/4087
