### ISSUE TITLE
Rename `researchdelight` to `showcase`

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#3258]
### Context

Background discussions led to the suggestion we should change the name of `researchdelight`. Further discussion in the meta repository chronicled in https://github.com/2i2c-org/meta/issues/713 led to the conclusion that we should rename this resources as `showcase`. 

### Proposal

Change `researchdelight` naming for the associated hub to `showcase`.

**Comment by jmunroe** [comment]
Completed in 
- https://github.com/2i2c-org/infrastructure/issues/3279
