### ISSUE TITLE
Q4 Goal - Reduce workload long term by identifying and working what accomplishes that

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3264]
## Goal description

In a metaphor, this goal is about taking the time to tie a shoe's loose shoelace in an marathon with a lot of distance to run still. Its not really about tieing shoelaces though, its about setting us up to perform well in the marathon and not running it distracted by a shoelace while risking an injury.

For @2i2c-org/engineering, this goal could be translated to:

_To identify and work anything we believe can be addressed promptly that we believe will reduce our workload long term, as that sets us up to scale our impact by freeing up our own capacity._

For me its a stressor to be aware about a loose shoelace when running. I see this goal as providing us with the time and focus to tie our shoelaces, or even take a short detour to pick up a bicycle to ride instead.

## Method

1. We work together to nominate work items that aligns with the goal.
2. The goal lead triages nominated work items and selects some work items to be assigned
3. The goal lead assigns selected work items to engineers during sprint meetings and when receiving a request for more work
4. Engineers works assigned work items, but also takes time to help others to bring their work to completion. Helping others can for example be to take time to discuss something or review of a PR for example. Helping others should be given a high priority.

### Before initial sprint

Erik nominates some initial items and selects a few to be assigned during the initial sprint.

### Initial sprint (Started Oct 18)

- Slack channel [`#23q4-goal-reduce-workload`](https://2i2c.slack.com/archives/C061F2RHYNS) created
- Goal introduction
- Initial work besides assigned work items
  1. @2i2c-org/engineering to go through [their own GitHub issues in 2i2c-org/infrastructure](https://github.com/2i2c-org/infrastructure/issues/created_by/@me), updating them for readability and closing anything we consider resolved or considered.
  2. @2i2c-org/engineering to identify issues among their own they believe aligns with the goal and labels them with `nominated-to-be-resolved-during-q4-2023`
- Erik to assign work items

### Future sprints

The goal lead assigns work items.

### Sprint issues

- #3318
- #3438
- #3439
- #3469

## Team composition

All engineers.

## Related

- [Nominated work items](https://github.com/2i2c-org/infrastructure/issues?q=is%3Aopen+is%3Aissue+label%3Anominated-to-be-resolved-during-q4-2023)
- [Selected work items](https://github.com/2i2c-org/infrastructure/issues?q=is%3Aopen+is%3Aissue+label%3Aselected-to-be-resolved-during-q4-2023)
- [Notes from Q4 goals working session, Tue Oct 10 2023](https://docs.google.com/document/d/1z2j2K1owlyH6o-In5Vh8pYNOwJgd74fry7iniUVUuio/edit)

**Comment by yuvipanda** [comment]
Think this one can be closed out now, @consideRatio?
