### ISSUE TITLE
Get rid of eksctl produced `cloud-user-sa`

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3273]
The following three hubs use a `cloud-user-sa` service account provisioned by eksctl to give hub users *full* S3 access:

- [x] uwhackweeks
- [x] carbonplan
- [ ] openscapes

This predates our more modern terraform based service accounts. We should get rid of these eksctl generated accounts and bring these hubs in line with the rest.

### Stop using the `cloud-user-sa` service account

- [ ] Stop using `cloud-user-sa` serviceaccount by removing `jupyterhub.singleuser.serviceAccountName` under `config/clusters/openscapes/common.yaml`. Make a PR, get this deployed. 
- [ ] Test to make sure you can still access `$SCRATCH_BUCKET` S3 bucket, by running `aws s3 ls $SCRATCH_BUCKET` in a jupyterlab terminal in the hub. This should not error out.

### Remove the IAM service account from AWS

- [ ] Render the `.jsonnet` file into a `.yaml` file with the `jsonnet` command in https://infrastructure.2i2c.org/hub-deployment-guide/new-cluster/aws/#create-and-render-an-eksctl-config-file
- [ ] Delete the iamserviceaccount with `eksctl delete iamserviceaccount -f openscapes.eksctlyaml --name cloud-user-rsa`
- [ ] Repeat the test from earlier to make sure that `aws s3 ls $SCRATCH_BUCKET` still works inside a terminal in the jupyterhub.
- [ ] Remove `namespaces` variable in `eksctl/openscapes.jsonnet`
- [ ] Remove `iam.serviceAccounts` in the main cluster definition in `eksctl/opencsapes.jsonnet`
- [ ] Make this into a PR, get it merged

### Celebrate

This is a celebration of the fact that we've been serving openscapes so long that they're using deprecated features! When done, we can close this issue :)

**Comment by consideRatio** [comment]
uwhacksweeks is removed already via https://github.com/2i2c-org/infrastructure/issues/2173, I opened #3291 to finalize the cleanup.

### Related code

https://github.com/2i2c-org/infrastructure/blob/682ef1f38cd6eb944761e65824c6d4d58688600e/eksctl/carbonplan.jsonnet#L70-L82

### Issue scope question

@yuvipanda is the scope narrowed to replacing how the permissions are granted? Currently carbonplan and openscapes has `arn:aws:iam::aws:policy/AmazonS3FullAccess` which includes creation of new buckets etc.

A wider scope could include:
- setup of scratch buckets
- narrowing permissions to scratch buckets only

I figure setup of scratch buckets makes sense as well as that is non-breaking and we provide environment variables etc about it.

**Comment by yuvipanda** [comment]
@consideRatio makes sense to just have it be 'remove `cloud-user-sa` and replicate it in terraform`.

**Comment by GeorgianaElena** [comment]
> makes sense to just have it be 'remove cloud-user-sa and replicate it in terraform`

@yuvipanda, by _"replicate it in terraform"_, do you mean replicate the buckets in https://s3.console.aws.amazon.com/s3/buckets?region=us-east-1# for example (carbonplan) in the terraform config?

If so, I understand that the the service account that we create via terraform will **not** have full access to the buckets like the old `cloud-user-sa`. Is this correct?

Do we wish to retain such access for the existing buckets to not introduce a breaking change? If so, should `extra_iam_policy` be enough?

Also, @consideRatio said _"arn:aws:iam::aws:policy/AmazonS3FullAccess which includes permission for them to create their own buckets etc."_ Do we wish to retain such permission in the future? Is this possible via our current terraform infra or do we need to tweak it to allow this.

I am trying to understand how complicated it would be to could get rid of `cloud-user-sa` together with https://github.com/2i2c-org/infrastructure/issues/3224. Thank you!

**Comment by yuvipanda** [comment]
@GeorgianaElena yeah, we would have to *communicate* with the affected communities about it. Primary differences would be that they would not be able to create buckets, and there *may* be a change in how they can access buckets in *other* projects as well (am no sure).

I don't think this should be resolved along with #3224, that is a big enough project by itself I think.

**Comment by GeorgianaElena** [comment]
> I don't think this should be resolved along with https://github.com/2i2c-org/infrastructure/issues/3224, that is a big enough project by itself I think.

Ok, makes sense! Thanks @yuvipanda!

**Comment by yuvipanda** [comment]
This can just simply be removed, as they are currently not using this functionality *at all*.

**Comment by yuvipanda** [comment]
I've updated this issue with action items left to do very specifically.
