### ISSUE TITLE
[leap] Nbgitpuller not working with a custom unlisted image

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3277]
### Context

Reported in https://2i2c.freshdesk.com/a/tickets/1049

- nbgitpuller links don't work if the server that is started uses an custom image passed through `unlisted_choice`.

   A link like https://leap.2i2c.cloud/user/georgianaelena/git-pull?repo=https%3A%2F%2Fgithub.com%2Fjbusecke%2Fleap-pangeo-demos&branch=main&redirects=1 returns a 404

- starting the server manually with the custom image and then pull the notebook and run it works

**Comment by GeorgianaElena** [comment]
_Opened this issue to track the time investment into its investigation_

### Update

1. I first thought it is an upstream issue, so I've started an investigation so I can open an issue upstream with enough details about what it's going on.

2. As part of this research, I've turned the custom unlisted image an option on the leap staging hub

3. The nbgitpuller link still doesn't work, even if it's part of the profile list


### Preliminary conclusion
There is something wrong with the user image and not with nbgitpuller or `unlisted_choice`. 
I found this troubleshoot info about the nbgitpuller 404 issue https://github.com/jupyterhub/nbgitpuller/blob/8bc05632884ff108e9486ff146f7d65fe1ba2eaf/docs/install.rst#troubleshooting that I plan to check next.

**Comment by consideRatio** [comment]
Nbgitpuller functionality is based on the user image, so its not possible to use unless the image chosen has it installed.

Nbgitpuller links created for jupyterhubs are just ways to redirect to the user's server and to trigger nbgitpuller in the user server to do work.

**Comment by GeorgianaElena** [comment]
Thanks @consideRatio, I've already checked that and they have nbgitpuller in the image https://github.com/jbusecke/pangeo_pyvista_docker_image/blob/5dbab10c9248e360e3f1f0999346013ac13c586f/environment.yml#L14, as the user iamge repo is based on the 2i2c template anyhow, so I believe it might be soemthing else.

**Comment by yuvipanda** [comment]
nbgitpuller works by preserving the `next` url parameter - perhaps using `unlisted_choice` doesn't preserve that parameter when submitted?

**Comment by GeorgianaElena** [comment]
Mhmhmh, waaait. They have a Dockerfile in that repo (https://github.com/jbusecke/pangeo_pyvista_docker_image/blob/5dbab10c9248e360e3f1f0999346013ac13c586f/Dockerfile) and there is no step there that is installing the packages in `environment.yaml`

**Comment by GeorgianaElena** [comment]
Confirmed from a user server that `nbgitpuller` doesn't seem to be there :/

**Comment by GeorgianaElena** [comment]
Closing this issue for now. I will reopen if any new info is available.
