### ISSUE TITLE
grafana information missing

### ISSUE THREAD

**Issue by BriannaLind** [2i2c-org/infrastructure#3280]
### Context

I am interested in monitoring the openscapes hub environment as it is being used [here](https://grafana.openscapes.2i2c.cloud/d/hub-dashboard/jupyterhub-dashboard?orgId=1&from=now-6h&to=now) but the information I was expecting is missing

![image](https://github.com/2i2c-org/infrastructure/assets/104585874/9c42dbe5-a27c-44d2-ad34-424d492a3858)

**Comment by consideRatio** [comment]
#3237 is opened to resolve this, and it includes a workaround!

**Comment by BriannaLind** [comment]
@consideRatio thanks a lot!!!

**Comment by BriannaLind** [comment]
@consideRatio do you need special permissions/be an administrator to 'see' the settings?  I am having a hard time finding 'settings'

**Comment by yuvipanda** [comment]
@BriannaLind I've temporarily fixed the openscapes grafana and all dashboards are running again! Hopefully we'll have a longer term fix soon.

Congrats on the good event!
