### ISSUE TITLE
Allow admins to specify arbitrary node types to try with `unlisted_choice`

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3287]
Based on https://2i2c.freshdesk.com/a/tickets/1054.

The idea is to allow admins to be able to type in an instance type name, and land a pod on an instance of that type. This is very helpful for trying out new GPUs, etc. On GCP, we can probably couple this with [node autoprovisioning](https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning) and `unlisted_choice`.

**Comment by yuvipanda** [comment]
I am going to timebox myself to see how complex this actually is though, especially as I think `unlisted_choice` shifts a lot of the burden onto the hub admin.

**Comment by consideRatio** [comment]
Okay please try to refine an estimation of the long term workload implications as well, that is my concern far more than the initial setup time.

**Comment by yuvipanda** [comment]
I spent some time working on this and exploring the space. My primary motivation is that we should make our systems as self serve as possible, and particularly empower hub admins to explore things without needing us to perform actions on their behalf. Then we can get a nice virtuous loop of:

admin tries something -> doesn't work -> they iterate -> works well -> we roll this out to people

Without us having to be involved throughout the process. I think this has worked well in `unlisted_choice`, and I think this would be a useful thing to explore here as well.

My primary concern was that last time we tried node autoprovisioning it was kinda janky! However, we also tried it in a far more expansive way, and this time I was exploring it in a far more constricted way.

This time, I basically wanted this UI to work for hub admins

<img width="650" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/4277e2a4-1de3-45ad-ab2e-be5374ae8871">

It's clearly marked as a fairly advanced feature, and if things break here it's on them. Only admins should be able to land on nodes created this way (not non-admin users), and it shouldn't affect non-autoprovisioned nodes. Given the amount of time I spent when sorting out https://github.com/pangeo-data/pangeo-docker-images/issues/387 for example, I think this will long term reduce amount of time everyone has to spend on trying out GPU / accelerator stuff too. Same for trialing ARM instances.

Anyway, in this more focused fashion, node autoprovisioner seems to be doing a bit better. I could get it to spawn me an e2 instance or an n2d instance (so cheaper AMD instances could be trialed), but nothing with GPUs or any other accelerators. So I'm going to park this for a bit and try again, probably next week. The diff was fairly small!

**Comment by consideRatio** [comment]
Autoprovisioning is [apparently influences the cluster autoscaler even if working to schedule pod that doesn't need it to create a new node pool](https://stackoverflow.com/a/62491730). That hindered scaleup as reported for LEAP in https://2i2c.freshdesk.com/a/tickets/1074 by "max cluster memory limit reached".

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/90fc3502-bdad-4f7c-8674-53faa297dc78)

There are currently no node pools created by the autoprovisioning system, so I'll go for a disable for the moment @yuvipanda.

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/271295fe-4738-4779-8ef9-b882b8f29302)

**Comment by consideRatio** [comment]
When toggling various options, its not obvious if the change is quick or similar. I learned that changing the settings of "node auto-provisioning" took around ~30 minutes, which I think may be the amount of time it takes to do a k8s control-plane upgrade. It makes sense that it would align, because they are influencing the cluster autoscaler they manage in the k8s control-plane.

I wonder if changes to that forces the k8s api-server to restart as well, then a zonal cluster would get a k8s api-server outgage making changes to node auto-provisioning as well.

**Comment by consideRatio** [comment]
It seems that enabling/disabling node auto-provisioning is something that requires restarting the control plane. For a regional GCP cluster this takes ~25-30 minutes I think and shouldn't cause disruptions, but it would for zonal clusters.

**Comment by consideRatio** [comment]
This machine has been failing to scale down, I think because of a lack of taints made it get system pods scheduled on it. I cordoned it and deleted some pods from it, hopefully it will get scaled down.

```
gke-leap-cluster-nap-e2-highmem-16-19-09f720d5-j254   Ready    <none>   5d5h    v1.25.10-gke.2700
```

```
Non-terminated Pods:          (13 in total)
  Namespace                   Name                                                              CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                                              ------------  ----------  ---------------  -------------  ---
  kube-system                 calico-node-kdd2r                                                 100m (0%)     0 (0%)      0 (0%)           0 (0%)         2d22h
  kube-system                 fluentbit-gke-cqcz5                                               100m (0%)     0 (0%)      200Mi (0%)       500Mi (0%)     5d5h
  kube-system                 gke-metadata-server-2jrzs                                         100m (0%)     100m (0%)   100Mi (0%)       100Mi (0%)     5d5h
  kube-system                 gke-metrics-agent-jzx87                                           6m (0%)       0 (0%)      100Mi (0%)       100Mi (0%)     5d5h
  kube-system                 ip-masq-agent-bff8t                                               10m (0%)      0 (0%)      16Mi (0%)        0 (0%)         5d5h
  kube-system                 konnectivity-agent-5db5c757c7-6pg94                               10m (0%)      0 (0%)      30Mi (0%)        125Mi (0%)     5d3h
  kube-system                 konnectivity-agent-5db5c757c7-mlwxq                               10m (0%)      0 (0%)      30Mi (0%)        125Mi (0%)     5d3h
  kube-system                 kube-proxy-gke-leap-cluster-nap-e2-highmem-16-19-09f720d5-j254    100m (0%)     0 (0%)      0 (0%)           0 (0%)         5d5h
  kube-system                 metrics-server-v0.5.2-56d9dd6d95-kb6z4                            50m (0%)      45m (0%)    125Mi (0%)       375Mi (0%)     21h
  kube-system                 netd-zfq6f                                                        0 (0%)        0 (0%)      0 (0%)           0 (0%)         5d5h
  kube-system                 pdcsi-node-9zjcm                                                  10m (0%)      0 (0%)      20Mi (0%)        100Mi (0%)     5d5h
  support                     support-cryptnono-vnf7n                                           5m (0%)       800m (5%)   100Mi (0%)       2Gi (1%)       5d5h
  support                     support-prometheus-node-exporter-tptcl                            10m (0%)      10m (0%)    30Mi (0%)        30Mi (0%)      5d5h
```

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/829b5437-ba68-4994-91d5-f4936106fb43)

**Comment by consideRatio** [comment]
There is an e2 node that keeps running, and I've failed to understand why the cluster-autoscaler drained a core node pool causing an outage in #3363 - I suspect it could be related to the use of the cluster-autoscaler specific to node auto-provisioning enabled though.

**Comment by yuvipanda** [comment]
Sorry @consideRatio I thought you already had it disabled! Yes, let's definitely disable it.

**Comment by yuvipanda** [comment]
I'm re-applying terraform from clean master so node autoprovisioning goes away.

**Comment by yuvipanda** [comment]
Done.

**Comment by yuvipanda** [comment]
Closed as wontfix, and i've already communicated this to LEAP.

**Comment by yuvipanda** [comment]
Thank you very much for helping deal with the issues that came out of this, @consideRatio. In the future, if I try something with node autoprovisioning (which still has very good promise), I will make sure to do that on a temporary dedicated cluster.
