### ISSUE TITLE
[UCMerced] Investigate fixing exporting to PDF from the R server of the staging hub

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3289]
### Context

Follow-up to https://github.com/2i2c-org/infrastructure/issues/3188.

According to the discussions on slack, current theory is that there is an issue with the upstream [rocker/binder](https://github.com/rocker-org/rocker-versioned2) image.

@yuvipanda has a suspicion that changing the latex command that notebook is using should fix the issue.

**Comment by yuvipanda** [comment]
So first, LaTeX is terrible when used as an intermediary to convert things to PDF. I just hate it with all my soul when used for this purpose, especially when inside containers. It spews out unreadable error messages that have nothing to do with PDF nor ipynb, and it's normal to hate it. 

Ok, with that out of the way...

So I think the fundamental problem is that nbconvert (jupyter uses this for PDF conversion) is looking for xetex while rocker uses some other variant. However, nbconvert's usage is probably basic enough that it should be able to use whatever rocker has. I'm going to try to see if we can configure nbconvert to use this other thing.

**Comment by yuvipanda** [comment]
So first I tried to find the default command nbconvert calls. I ran `jupyter nbconvert --help-all` and looked for `latex`. I get:

```
--PDFExporter.latex_command=<list-item-1>...
    Shell command used to compile latex.
    Default: ['xelatex', '{filename}', '-quiet']
```

So it calls xelatex. Let's see what ships by default with rocker

**Comment by yuvipanda** [comment]
Turns out the notebook latex is just hungry for a lot of latex packages that aren't in the base. I have written a small script that will iteratively try to convert a super simple notebook file into PDF, install the packages needed, try again, and keep trying again until it gets all the packages.

```
import sys
import subprocess

outfile = open("packages", "a")

while True:
    convert = subprocess.run(["jupyter", "nbconvert", "--to", "pdf", "Untitled.ipynb"], capture_output=True)
    if convert.returncode == 0:
        break
    print(convert.stdout)
    print(convert.stderr)
    for l in convert.stderr.decode().split("\n"):
        if not l.startswith('! LaTeX Error: File'):
            continue
        missing = l.split(' ')[4]
        missing = missing.strip("'").strip("`")
        missing = missing.split(".")[0]
        outfile.write(f"{missing}\n")
        subprocess.check_call(["tlmgr", "install", missing])
```

After fiddling with this for a while, I realized that I'm probably re-treading ground others have trodden before me and found https://github.com/jupyter/nbconvert/issues/1328 haha.

**Comment by yuvipanda** [comment]
AAAAND upstream fix https://github.com/rocker-org/rocker-versioned2/pull/714
