### ISSUE TITLE
[deployer] Allow skipping and forcing the creation/update of a cluster config file

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3294]
### Context

Follow-up to https://github.com/2i2c-org/infrastructure/issues/2187#issuecomment-1453407343.

Running `deployer generate dedicated-cluster` for aws or gcp clusters, will each generate some initial files that were templated for a new cluster, like terraform, support files and even an intial `cluster.yaml` file in the case of GCP.

These files are generated together from one command and in case a file already exists, it gets overridden.

### Proposal

We should not allow overriding existing files, except if a `force` flag exists. Alternativelly, we could always override if it exists, but provide a `skip` flag for each of them. 

However, I believe the first proposal is safer.

**Comment by consideRatio** [comment]
> We should not allow overriding existing files, except if a `force` flag exists.

Yes a clear :+1: for this path! I suggest emitting a warning instead of overwriting a file if they already exists, clarifying that they would be replaced or updated if `--force` is used.

**Comment by consideRatio** [comment]
Its easier to document use of a non-intrusive command than an intrusive command that may merit misc warnings about it. So this could be beneficial to have done before #2187 which in turn I think is relevant to reduce our long term workload.

**Comment by GeorgianaElena** [comment]
> Its easier to document use of a non-intrusive command than an intrusive command that may merit misc warnings about it. So this could be beneficial to have done before https://github.com/2i2c-org/infrastructure/issues/2187 which in turn I think is relevant to reduce our long term workload.

💯 Yes! Perfect! Thanks for labeling it @consideRatio!

**Comment by consideRatio** [comment]
> > We should not allow overriding existing files, except if a `force` flag exists.
> 
> Yes a clear 👍 for this path! I suggest emitting a warning instead of overwriting a file if they already exists, clarifying that they would be replaced or updated if `--force` is used.

A clarification: I think we shouldn't write/update anything unless all changes made can be done.

I got an idea btw, what about instead of introducing `--force` and checking for files etc, we instead check that `git state` is clean like a git rebase also does before its proceeds. If we do that, we know that whatever is changed can easily be reverted via `git reset --hard HEAD`, and that it also can be inspected easily via `git diff`.

The code to implement this is probably relatively simple and can be adopted as a general strategy for `generate` commands. I think its a great practice to isolate commits made by tooling as well, and this would help with such practice.

**Comment by GeorgianaElena** [comment]
> I got an idea btw, what about instead of introducing --force and checking for files etc, we instead check that git status is clean like a git rebase also does before its proceeds. 

Great idea @consideRatio! I was thinking, why not have both? I will first describe what I have in mind, then why I think having both will be beneficial.

### When running `deployer generate dedicated-cluster` the following checks should happen in this order:

1. run `git status`
   - use this to check if any of the files that this commands generates has not been modified and not committed
   - few important things in this step:
      - only the status of these files is important and not _all_ of them
      - by making sure there aren't things that have not been commited, we ensure we are not loosing work when `--force` is used to override a file, as a git restore will get the file back
 2.  check if any of the files this command is trying to generate already exist
     - if any of them already exists, emit a warning message and abort if a `--force` flag has not been used
     - if `--force` is used, overwrite them completely.
     
### Benefits of having both
The argument in favour of using just `git status` is that right now, the script behaves like it has `--force` enabled by default. But because we add the `git status` step, any changes can be easily reverted if we do not wish to override the files. Is this correct?

But what if, you override the files but are not aware of this? I'm thinking of a scenario where I want to deploy another `leap` cluster let's say, but on AWS this time. And by mistake, I use the generate command for gcp and override the initial cluster. Then continue with another mistake, commit the file and even do a `terraform apply`?

I admit that there must happen many mistakes in a row for this scenario to happen  And even if this happens, thanks to versioning we can revert all of it eventually, but not without work.

This is why I believe, it is worth to have the script only override files if `--force` is explicitly used to make it more mistake-proof ` and make sure we are intentionally overriding files. Also, adding this flag, is not something complicated and I think it's a small time investment now to avoid unintentional changes.

**Comment by consideRatio** [comment]
> The argument in favour of using just `git status` is that right now, the script behaves like it has `--force` enabled by default. But because we add the `git status` step, any changes can be easily reverted if we do not wish to override the files. Is this correct?

Yes, but I think there are some additional benefits. I've especially considered the benefits of doing just a _strict `git status` check_ where nothing is allowed to be dirty. Then the benefits could be:
- easy to document, understand, and maintain such dumb logic
- easy to inspect changes made with `git status` and `git diff` (not cluttered by other changes)
- easy to commit the changes made with `git commit -am "..."` (putting tool generated changes in its own is a nice practice to reduce the complexity of code review)
- easy and safe to cleanup the changes with `git reset --hard HEAD` and `git clean -fd`
- easy to re-use a simple "check_before_continuing_with_generate_command" function for all `deployer generate` commands, no matter if they generate new files or is expected to update files in place etc.

If having such logic only, then I figure a `--force` flag would mean "bypass the git status check". I can see this be relevant to use for some `deployer generate` commands where you may want to update a file multiple times in a row or similar before making a commit.

---

Very happy to go with what you decide @GeorgianaElena, you have given this a lot of thought!!
