### ISSUE TITLE
Consider tuning tcp kernel settings

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3299]
### Context

During the incident described in the draft at https://2i2c-org.pagerduty.com/postmortems/178733fa-6681-8b88-5346-a53369267478, we ran into the following error message on the LEAP hub:

```
TCP: out of memory -- consider tuning tcp_mem
```

After finding out about https://github.com/kubernetes/kubernetes/issues/62334 which raises the concern about kubelet not monitoring the tcp mem of the node, but only disk ram and cpu, the conclusion was that this is why the core node where this happened, appeared as ready for more than 30m even though the tcp oom was happening, and hub was not reachable.

### Proposal

@yuvipanda pointed out the https://github.com/berkeley-dsep-infra/datahub/pull/4488 might be a good example on how we could solve this on our end so that it doesn't happen again.

### Updates and actions

Summary of relevant resources:
- https://github.com/kubernetes/kubernetes/issues/62334
- https://github.com/berkeley-dsep-infra/datahub/pull/4488
- https://2i2c-org.pagerduty.com/postmortems/178733fa-6681-8b88-5346-a53369267478

**Comment by consideRatio** [comment]
:+1: for work in this direction.

### Preliminary research

1. What values should be overridden?
   The ones that can be read like these as a root user are considered to be overridden.
   ```
   sysctl net.core.netdev_max_backlog
   sysctl net.core.rmem_max
   sysctl net.core.wmem_max
   sysctl net.ipv4.tcp_rmem
   sysctl net.ipv4.tcp_wmem
   ```
2. What are the default values we override?
   - Are they the same for instances we use in GCP?
     `n2-highmem-[4,8,32]` all had the same values at least.
     ```
     # A n2-highmem-4 node, k8s v1.26.5-gke.2100, Intel Cascade Lake
     net.core.netdev_max_backlog = 1000
     net.core.rmem_max = 212992
     net.core.wmem_max = 212992
     net.ipv4.tcp_rmem = 4096        87380   6291456
     net.ipv4.tcp_wmem = 4096        16384   4194304
     ```
   - Are they the same for instances we use in AWS as well?
     `r5.xlarge` and `r5.4xlarge` had the same values at least.
     ```
     # A r5.xlarge node, v1.25.6-eks-48e63af, 
     net.core.netdev_max_backlog = 1000
     net.core.rmem_max = 212992
     net.core.wmem_max = 212992
     net.ipv4.tcp_rmem = 4096	131072	6291456
     net.ipv4.tcp_wmem = 4096	20480	   4194304
     ```
   - All but the middle value of `rcp_rmem and `rcp_wmem` seem to be the same
3. What is the meaning of the three values for `tcp_rmem` and `tcp_wmem`?

   >       tcp_mem (since Linux 2.4)
   >              This is a vector of 3 integers: [low, pressure, high].
   >              These bounds, measured in units of the system page size,
   >              are used by TCP to track its memory usage.  The defaults
   >              are calculated at boot time from the amount of available
   >              memory.  (TCP can only use low memory for this, which is
   >              limited to around 900 megabytes on 32-bit systems.  64-bit
   >              systems do not suffer this limitation.)
   >
   >              low    TCP doesn't regulate its memory allocation when the
   >                     number of pages it has allocated globally is below
   >                     this number.
   >
   >              pressure
   >                     When the amount of memory allocated by TCP exceeds
   >                     this number of pages, TCP moderates its memory
   >                     consumption.  This memory pressure state is exited
   >                     once the number of pages allocated falls below the
   >                     low mark.
   >
   >              high   The maximum number of pages, globally, that TCP
   >                     will allocate.  This value overrides any other
   >                     limits imposed by the kernel.

### Future research

4. Can we configure `sysctl` options via terraform, and does it require a re-creation of the node pool to do so?
   - It will require node restarts at least, because the change is applied on startup.
5. What values should we use? Should they be instance specific?

### Current conclusion

Changing these seems reasonable to me if we think it can help, but I note that

**Comment by shaneknapp** [comment]
for what we experienced, our 'solution' makes recovery easier, quicker and less painful.  the updated settings seem to help overall, and i'd recommend enabling them.

this doesn't fix the overall problem...

**Comment by consideRatio** [comment]
Final note - It seems that the kubelet metric to report tcp_mem is being developed now, which makes us be able to inspect it once k8s 1.31 or 1.32 perhaps is out and used: https://github.com/kubernetes/kubernetes/issues/62334#issuecomment-2144750275
