### ISSUE TITLE
[2i2c-uk:lis] Re-think memory allocation 

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3301]
### Ticket context

In https://2i2c.freshdesk.com/a/tickets/1066 an increase in RAM limit was requested because they are running out of RAM frequently and getting their kernels killed I believe.

### Current situation

The lis hub is on a shared cluster, with [n2-highmem-4](https://github.com/2i2c-org/infrastructure/blob/038a447e7f03a400088f9c524ba23e8f099c4b9f/terraform/gcp/projects/2i2c-uk.tfvars#L21-L27) nodes.

It's operating on [the default memory and cpu limits and guarantees from the basehub chart](https://github.com/2i2c-org/infrastructure/blob/038a447e7f03a400088f9c524ba23e8f099c4b9f/helm-charts/basehub/values.yaml#L285-L306), as there isn't anything configured in https://github.com/2i2c-org/infrastructure/blob/master/config/clusters/2i2c-uk/lis.values.yaml

### Grafana info
<img width="715" alt="Screenshot 2023-10-23 at 10 27 53" src="https://github.com/2i2c-org/infrastructure/assets/7579677/72b72e8c-2115-4dcf-886f-1465c1a69dad">
<img width="715" alt="Screenshot 2023-10-23 at 10 27 27" src="https://github.com/2i2c-org/infrastructure/assets/7579677/13757f69-e62e-4f4c-9a8f-035e396b5a26">
<img width="721" alt="Screenshot 2023-10-23 at 10 26 42" src="https://github.com/2i2c-org/infrastructure/assets/7579677/2d45fb69-69aa-4d1c-aa82-55b1a4674e59">
<img width="721" alt="Screenshot 2023-10-23 at 10 26 02" src="https://github.com/2i2c-org/infrastructure/assets/7579677/15bb2064-1dca-449b-91bd-70a263dbaa29">
<img width="1412" alt="Screenshot 2023-10-23 at 10 25 02" src="https://github.com/2i2c-org/infrastructure/assets/7579677/b68fdc0b-f134-4748-af99-5c06a17d9c7f">

### Action plan

@consideRatio, I was thinking to discuss this as a practical example during our next sync about node sharing in half on hour?

**Comment by consideRatio** [comment]
From video chat, a decision: to double the reqeust and limit
