### ISSUE TITLE
Q4 Reduced workload goal - Oct 18 Sprint tracking issue

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3318]
### Wed-Fri Oct 18-20

The sprint was introduced, we triaged issues in 2i2c-org/infrastructure. As goal lead I was still catching up with planning and adjustments to the available capacity allocations.

In direct communication with Yuvi and Georgiana, a focus towards resolving node sharing related aspects was established.

### Oct 23-31

Me and @GeorgianaElena met to discuss and overview node sharing related topics to work, notes available in [this hack.md document](https://hackmd.io/KZ6HugXlSuqubI8oXU-e9A?view).

- @yuvipanda fixed things in #3030 that we merged with the intent to let me and Georgiana work on it from there over time during this goal.
- @GeorgianaElena:
  - #3304
  - #3319, closes #3256
  - #3335, closes #3310
- @consideRatio:
  - #3313
    Initialized but not worked directly to completion because the work to do it grew and could be delayed without consequence to prioritize work that blocks other work
  - #3330, #3338, closed by #3337
    This blocks other refinements for the resource allocation logic
  - #2364
    Pending work about daemonset requests in misc clusters

Upcoming:
- https://github.com/2i2c-org/infrastructure/issues/3294
- https://github.com/2i2c-org/infrastructure/issues/3224
- https://github.com/2i2c-org/infrastructure/issues/3293
- https://github.com/2i2c-org/infrastructure/issues/2541

**Comment by GeorgianaElena** [comment]
@consideRatio, hope it's ok that I add https://github.com/2i2c-org/infrastructure/issues/3256 to the upcoming, since once https://github.com/2i2c-org/infrastructure/pull/3319 it's done, I think we can close that one.

**Comment by consideRatio** [comment]
Thank you @GeorgianaElena you are most welcome to contribute to updating this issue!!! :D

**Comment by damianavila** [comment]
Sprint 1 is done a long time ago, so closing it.
