### ISSUE TITLE
Fully turnkey cloud resources setup via Terraform for GCP

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#332]
# Background

Currently, bringing up a new project with all cloud resources set up requires a combination of Terraform and manual work. We should have this be totally automated instead.

# Expected timeline

We've to deploy the #207 hub, so we should use that as a test case to get this done.

Depends on #335 too

# Steps to complete this goal

- [x] Write docs on using the 'workspace' feature of Terraform
- [x] Document current cluster creation parameters
- [x] Automate installing support charts
- [ ] Set-up in-cluster NFS for home directory (#50), so we can remove the manual NFS VM setup
- [ ] Docker registries, based on outcome of https://github.com/2i2c-org/pilot-hubs/issues/331
- [ ] DNS (if possible)
- [x] Add other 2i2c engineers as admins

**Comment by choldgraf** [comment]
I believe that this is now complete, documented here: https://infrastructure.2i2c.org/en/latest/howto/operate/new-cluster/new-cluster.html
