### ISSUE TITLE
Leap (and other?) clusters has very slow network speeds

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3345]
When pulling `pangeo/base-notebook` from my computer in Sweden, it took 49 seconds. It should not take more than 1 minute to do it from a `n2-highmem-16` machine that isn't doing something else. It does though, and that slows startup times among other things.

This is from the `leap` cluster now for example.

```
  Normal  Pulling    7m36s  kubelet                                Pulling image "pangeo/base-notebook:latest
```

### Context

- #2947 

### Good initial diagnostic steps

- Test pull an image to various clusters node pools and measure how long it takes.

**Comment by yuvipanda** [comment]
My diagnosis is that the cluster is haunted and my suggestion is that we recreate the cluster in another zone, likely `us-central1-c`. This also gives us GPU access that we don't have.

**Comment by consideRatio** [comment]
@yuvipanda this was the LEAP cluster, and it has been seen in the 2i2c cluster, and I don't rule out we see it on more clusters as well. Due to that I don't want to focus on mitigating it for individual clusters any more.

**Comment by yuvipanda** [comment]
oooooh, i didn't realize it was the LEAP cluster! In that case I completely take everything I have said back.

**Comment by yuvipanda** [comment]
itcoocean on the aws hub may also have encountered this, although it could instead be just trying to open a really huge notebook.

**Comment by consideRatio** [comment]
I don't recall getting to the bottom of this, but I think it was remidiated by restarting things - such as nodes and the ingress controller.
