### ISSUE TITLE
Produce a report on image environments used by our hubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3346]
Based on a conversation with Richard Pope on Slack, it would be useful to write a script that generates the following report:

1. What images are in use across our hubs? 
2. What languages are present inside these?
3. What libraries are present inside these? We can also factor these out into common libraries + stuff unique to each image.

**Comment by richardjpope** [comment]
Possibly a separate task, but I'm also interested in which ones have S3 (or other data storage setups) associated with them?
