### ISSUE TITLE
Tracking issue for VEDA work on QGIS 

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3367]
As part of the VEDA team's priority planning, they have a JupyterHub related objective. There's no clear ask of us yet, but this issue is to track this and co-ordinate work.

The objective is described below:

# Objective 9: Improve JupyterHub for VEDA
## Suggested owners
2i2c, Greg, Brian?

## Motivation

JupyterHub is an important resource for users of VEDA platforms, providing both advanced science teams with resources for large-scale computation (still missing processing service on VEDA) and for onboarding new science users to cloud-based Earth data science.

Advanced usage is this PI expected to continue to be mostly on MAAP, while we prepare for bringing VEDA JupyterHub up to par and add more interoperability functionality.

## Some planned / drafted enhancements:

EGIS integration into VEDA QGIS
nbgitpuller-like bridge for launching QGIS with specific resources
Adding DaskHub to VEDA JupyterHub
Make QGIS in the browser available on VEDA JupyterHub
Custom image selection (automatically inject accepted images into spawner options, document for users)

## Dependencies
Support from 2i2c
Support from EGIS

## Success criteria
QGIS in the browser is available on VEDA JupyterHub
Documentation for custom image requests is available in the docs and discoverable for hub users
Other key improvements have been identified and implemented

**Comment by freitagb** [comment]
@yuvipanda - would we be able to add the QGIS image as is with the STAC API customization from @slesaad incorporated into the VEDA hub?

**Comment by yuvipanda** [comment]
@freitagb yep, we can just replicate that.

**Comment by yuvipanda** [comment]
This has been moved into https://github.com/NASA-IMPACT/veda-jupyterhub
