### ISSUE TITLE
Research and summarize approaches to sharing SRE duties

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#337]
# Background

In addition to doing development-focused work, we'll also need to do a variety of maintenance/operations and support for the 2i2c Managed Hubs. We want to do this in an equitable and efficient way.

There are many organizations that do similar things, and before we decide on something we should see what other patterns are out there, and summarize what we could learn from them.

# Expected time to complete

About 3 days to research and another 3 to write up and summarize

# Steps to complete this goal

Do some basic research on a few models for SRE amongst distributed teams, and write up major takeaways.

- [ ] "clinic duty" at wikimedia https://wikitech.wikimedia.org/wiki/SRE_Clinic_Duty
- [ ] add resources here!

**Comment by yuvipanda** [comment]
I think there's other more specific issues dealing with this now.
