### ISSUE TITLE
Let deployer emit list of clusters for use with `xargs`

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3374]
#3329 is about documenting how `xargs` can be used to do something once for each cluster. Currently though the strategy is to do `ls config/clusters | xargs ...` which makes a command be run "once per folder".

It would be nice to have a deployer command to replace the `ls` command, allowing us to also for example only get `gke` clusters or `aks` clusters etc.

I for example wanted to run a command once for each GKE cluster, but didn't want to be bugged by the EKS/AKS clusters that would return an error on the command i wanted to run for each cluster.

**Comment by yuvipanda** [comment]
Something like this exists now I believe.
