### ISSUE TITLE
[EVENT] Openscapes

### ISSUE THREAD

**Issue by betolink** [2i2c-org/infrastructure#3403]
### Summary

Next Thursday, November 16th, 2023. NASA Openscapes will host a workshop for 25 to 50 people from 3PM CT to 6PM CT
This is an in person event in Guadalajara, Mexico sponsored by the ICESAT-2 and GEDI missions in partnership with UNESCO.

### Event Info

- **Community Representative:** @betolink @jules32
- **Event begin:** 2023-11-16  3:00 PM CST (UTC-6)
- **Event end:** 2023-11-16  6:00 PM CST (UTC-6)
- **Active times:** 3:00 - 6:00 PM CST (UTC-6)
- **Number of attendees:** 25+ but less than 50
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**: https://openscapes.2i2c.cloud/
- **Hub decommisioned after event?**: NO

### Task List

**Before the event**

- [ ] Dates confirmed with the community representative and added to Hub Events Calendar.
- [ ] Quotas from the cloud provider are high-enough to handle expected usage.
- [ ] **One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  
- [ ] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [ ] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by damianavila** [comment]
Given the previous setup in https://github.com/2i2c-org/infrastructure/issues/3217 (according to Grafana we had ~30 users on that day), I presume we do not need to perform any changes to prepare for the event.

@GeorgianaElena and @consideRatio who were involved in the previous event, do you agree with me?

**Comment by GeorgianaElena** [comment]
> @GeorgianaElena and @consideRatio who were involved in the previous event, do you agree with me?

@damianavila, we prepared like this for the event: https://github.com/2i2c-org/infrastructure/pull/3262

@betolink, do you plan to use the Python environment during the event? Also, do you know which option from the resource allocation drop-down you might want to use?

You should be able to use the hub as it is, having this info will help with reducing the startup times, by scheduling on bigger nodes if the memory needs are high.

Thank you and sorry for following back so late on this issue!

**Comment by betolink** [comment]
Hi @GeorgianaElena, we are only going to use Python for this workshop, I think we'll have approx 25 to 35 participants using the 7GB allocation for approx 3 hours. Yeah I think it shouldn't be a problem, thanks for your help!

**Comment by damianavila** [comment]
Hey @betolink, your event appears to be over 🎉

We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!

- Did the infrastructure behave as expected?
- Anything that was confusing or could be improved?
- Any extra functionality you wish you would have had?
- Could you share a story about how you used the hub?
- Any other feedback that you'd like to share?
