### ISSUE TITLE
Allow using JupyterHub admin panel for adding users on Openscapes hub as well

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3413]
In https://github.com/2i2c-org/infrastructure/issues/3240, we moved *most* access to the openscapes hub to be via GitHub teams. This is great (yay), but has an unfortunate side-effect for the case of *workshops*. Mostly the admins don't know the user accounts before, and the process of github invites + the user having to *accept the invite*, while having never used GitHub before, can be a bit of a jam.

This is the issue to try to help deal with that.

One potential solution is to allow users *either* via GitHub teams, but *also* allow the escape hatch of using the JupyterHub admin panel (which does *not* require users accept an invite!). 

They have an event on Dec 10, so need to figure this out by then.

**Comment by consideRatio** [comment]
Here are some explicit resolutions to consider.

### Resolution 1 - Back to `allow_existing_users`

> One potential solution is to allow users either via GitHub teams, but also allow the escape hatch of using the JupyterHub admin panel (which does not require users accept an invite!).

This would be to combine `OAuthenticator.allow_existing_users` and `GitHubOAuthenticator.allowed_organizations` which since oauthenticator 16 is possible. It comes with a big downside though in my mind related to this warning.

```yaml
          # WARNING: Don't use allow_existing_users with config to allow an
          #          externally managed group of users, such as
          #          GitHubOAuthenticator.allowed_organizations, as it breaks a
          #          common expectations for an admin user.
          #
          #          The broken expectation is that removing a user from the
          #          externally managed group implies that the user won't have
          #          access any more. In practice the user will still have
          #          access if it had logged in once before, as it then exists
          #          in JupyterHub's database of users.
          #
          allow_existing_users: True
```

### Resolution 2 - Listing `allowed_users` in chart config

It would also be possible to configure `allowed_users` together with `allowed_organizations`, the downside of that it is that it requires our intervention.

### Resolution 3 - Overriding `GitHubOAuthenticator.check_allowed`

As of oauthenticator 16 and work by @GeorgianaElena and me, the authorization logic isn't so spread out any more. If the [`GitHubOAuthenticator.check_allowed`](https://github.com/jupyterhub/oauthenticator/blob/7015b0147cde257e69c6c552017610735557575b/oauthenticator/github.py#L168) returns True, then the user is authorized.

A custom authenticator class declared via `hub.extraConfig` could override `check_allowed` to fetch some list from somewhere, and also return true based on that.

**Comment by yuvipanda** [comment]
Thank you very much for the summary of options, @consideRatio.

I was thinking of option 3, and then using https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#list-pending-organization-invitations. This way, anyone with a *pending* invite will be allowed in as well! This has a few advantages:

1. Doesn't require end user to *accept* invite before they're let in
2. The GitHub invites *expire*, so if the user has not accepted the invite by a period of time (7 or 30 days?) they will no longer be allowed.

I think this is a reasonable solution to the problem without bringing the admin interface back into the equation, with the associated problems you listed. 

How does this sound to you, @erinmr? This means that end users can access the hub immediately after you *send* an invite, rather than only after they *accept* the invite. But if they don't accept the invite before it expires, they will no longer have access. This lets you keep your list clean and only filled with people who are *actively using the hub*, but not have a big extra step in the very beginning.

**Comment by erinmr** [comment]
I think the addition of Github here is adding complexity that we didn't intend. We don't like the Github team interface for adding users in workshops. In addition, we don't necessarily want every workshop attendee to be part of our organization which happens now. We don't want to manage two orgs. Currently, authorized users in 2i2c can add users to the hub easily, the new team set up isn't allowing this distribution of labor and I'm now adding every user :-/

**Comment by consideRatio** [comment]
Another idea: check_allowed override based on jupyterhub group membership.

The jupyterhub UI is not so good though, step 1 is to add users and then step 2 is to add them to the group to allow, and adding users to group is done one user at the time i think.

**Comment by colliand** [comment]
FYI @jmunroe as this discussion is relevant to the success of communities using 2i2c infrastructure.

**Comment by erinmr** [comment]
Thanks, @yuvipanda. I am thinking of this as an experiment and curious about the ways that these changes are surfacing these dependency points and really enthusiastic users too :-)

**Comment by yuvipanda** [comment]
I have written down a 'blameless postmortem' style timeline here: https://hackmd.io/tWfqVai4SDC1CbQ4mhfIbw

**Comment by yuvipanda** [comment]
After further conversations, we have decided that what would be useful is instead to allow users to log in even if they have a pending invite. We could do this if we're using credentials from a GitHub App, rather than an OAuth app. I'll close this issue and provide more info in https://github.com/2i2c-org/infrastructure/issues/3240
