### ISSUE TITLE
[EVENT] Openscapes 10 December

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3430]
Requested in https://2i2c.freshdesk.com/a/tickets/1121

### Event Info

- Space Station Synergies (full day, 8:00 am-3:00 pm PST) 

    expected usage: 14.8 GB per person

- Earthdata Cloud (half day, 1:00 - 4:30 pm PST)

    expected usage: 7.4 GB per person

- **Community Representative:**  [BriannaLind](https://github.com/BriannaLind)
- **Number of attendees:** ~50

**Comment by damianavila** [comment]
@GeorgianaElena, given https://github.com/2i2c-org/infrastructure/pull/3262 and https://github.com/2i2c-org/infrastructure/issues/3403#issuecomment-1814695693, both without issues, do you think we need any further preparation (ie. bigger box if the 7.4GB per person)?

**Comment by GeorgianaElena** [comment]
### Event Todos
I believe the todo list for this event is:

- [ ] Do something like https://github.com/2i2c-org/infrastructure/pull/3262 again. 

- [ ] Also, they've requested to make the `shared` directory be read-only for the duration of the event, as atm it is writable by all users (they requested this change in the past).

### Node choice reasoning

The reasoning for the node type choice is:

There are two events happening one with 14.8GB expected usage and another one with 7.4GB and they will also overlap. At 50 users, we would need:

  - ~25 `r5.xlarge` nodes to come up for the ~14.8GB profile. I believe the number of nodes it's pretty high and half of the users will experiment longer startup times because of this.
   - ~13 `r5.xlarge` nodes to come up for the 7,4GB profile. This number is decent enough, but because there are two events, we should consider choosing based on that.

In total, there will be around 40 nodes running by the time the second event starts.

But if we go with `r5.4xlarge` nodes with 4 times as much memory, then at 50 users, we would need:
   - ~7 `r5.4xlarge` nodes nodes to come up for the ~14.8GB profile
   - ~3 `r5.4xlarge` nodes to come up for the 7,4GB profile.
 
In total, there will be around 10 nodes running by the time the second event starts.
