### ISSUE TITLE
Stop unconditionally setting `cmd` to `jupyterhub-singleuser`

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3434]
in `basehub/values.yaml`, we set `cmd` to `jupyterhub-singleuser`, to account for images that may not have that correctly set up. However, this means that the `ENTRYPOINT` set up in the docker image is *not* run, causing issues with logging when using repo2docker (https://github.com/2i2c-org/infrastructure/pull/3433) as well as startup when using desktop-proxy.

We should evaluate if this is actually still needed, and if not, unset `jupyterhub-singleuser` as `cmd` in `basehub/values.yaml`

**Comment by consideRatio** [comment]
https://github.com/jupyterhub/kubespawner/issues/493#issuecomment-1148712835 has related discussion summarized.

I think the role of `jupyterhub-singleuser` has changed notably over time, where a key point is to configure `notebook` and `jupyter_server` to be jupyterhub aware, but that such awareness in at least `jupyter_server` of modern versions is handled by environment variables and a `jupyter_server` extension.

So, unsetting it is probably fine for all images that use `jupyter_server` of a modern enough version, but probably not for those using `notebook` as a server still.

**Comment by consideRatio** [comment]
> in `basehub/values.yaml`, we set `cmd` to `jupyterhub-singleuser`, to account for images that may not have that correctly set up. However, this means that the `ENTRYPOINT` set up in the docker image is _not_ run, causing issues with logging when using repo2docker (#3433) as well as startup when using desktop-proxy.

Currently z2jh's default is to set `singleuser.cmd` (`KubeSpawner.cmd`) to `jupyterhub-singleuser`, we don't do it in basehub. Setting it overrides docker images' `CMD`, but won't override docker images's ENTRYPOINT. I think we are fine with the current state of things and no action is required.

**Comment by yuvipanda** [comment]
fwiw we still definitely do it in basehub: https://github.com/2i2c-org/infrastructure/blob/a6e5a196b76719b20afaa4e6a551733db3b5863f/helm-charts/basehub/values.yaml#L282

**Comment by yuvipanda** [comment]
@consideRatio can this be closed now? I remember you took some actions here, but I'm not sure what.

**Comment by consideRatio** [comment]
I don't advocate any action related to this issue, so if you think its OK to close lets close!

Logs etc is resolved, but we have via z2jh set singleuser.cmd explicitly, which I think we should.

**Comment by yuvipanda** [comment]
@consideRatio as long as you don't think we need to actively make any changes, I'm all good! Thanks for closing.
