### ISSUE TITLE
Make prometheus-dirsize-reporter more robust

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3444]
https://github.com/yuvipanda/prometheus-dirsize-exporter is used for our `shared-dirsize-metrics` k8s Deployment that ships with each JupyterHub. It is currently crashing for some hubs (`nasa-veda` for example), and due to that never enters a ready state. This in turn makes our CI/CD pipeline fail when making upgrades to hubs as `help upgrade` waits for its deployed resources succesful startup.

This issue is meant to help us track and get various upstream work done in this project to help us resolve the short term need, but also to ensure the projects meets some key critiera we would appreciate seeing in any upstream project we rely on. Below I've picked out some issues that I think we should resolve.

## Immediate needs

- https://github.com/yuvipanda/prometheus-dirsize-exporter/issues/5 and https://github.com/yuvipanda/prometheus-dirsize-exporter/issues/6
  - Addressed by - https://github.com/yuvipanda/prometheus-dirsize-exporter/pull/7
  
## Other needs

- https://github.com/yuvipanda/prometheus-dirsize-exporter/issues/9
- https://github.com/yuvipanda/prometheus-dirsize-exporter/issues/10
- https://github.com/yuvipanda/prometheus-dirsize-exporter/issues/2
- https://github.com/yuvipanda/prometheus-dirsize-exporter/issues/11

**Comment by yuvipanda** [comment]
Thanks for opening this, @consideRatio and listing the various things that need to be done. I've just retitled the issue to sound a little gentler, hope that's ok.

**Comment by consideRatio** [comment]
Thank you @yuvipanda, it also reads more clearly!

**Comment by yuvipanda** [comment]
One round of robustness complete, let's close this.
