### ISSUE TITLE
Info about cost for external IPs on AWS - just info sharing - no action point

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3448]
Using `kubectl get node -o wide` in `nasa-ghg` (new) and `carbonplan` (old) I conclude that we have VM instances with public IPs in both old and new EKS clusters. We have been notified that we will be charged a bit per IP address in https://2i2c.freshdesk.com/a/tickets/1132. It seems that its a cost of around 3.5 USD per IP used for a month. This cost is mostly negligable, so I think we ought to do nothing about it.

>On July 28, 2023, we announced [1] a new charge for public IPv4 addresses that will come into effect starting February 1, 2024.
For details on your usage, you can look at the AWS Cost and Usage report. To monitor, analyze, and audit your use of public IPv4 addresses, you can look at Public IP Insights [2].
>
>You can also read our blog post, Identify and Optimize Public IPv4 Address Usage on AWS [3], for information on how to optimize your use of public IPv4 addresses.
>
>For more details on public IPv4 address pricing, please see the VPC pricing page [4].
>
>For questions, please reach out to AWS support [5].
>
>[1] https://aws.amazon.com/blogs/aws/new-aws-public-ipv4-address-charge-public-ip-insights/
>[2] https://aws.amazon.com/about-aws/whats-new/2023/07/aws-public-ip-insights-vpc-ip-address-manager/
>[3] https://aws.amazon.com/blogs/networking-and-content-delivery/identify-and-optimize-public-ipv4-address-usage-on-aws/
>[4] https://aws.amazon.com/vpc/pricing/
>[5] https://aws.amazon.com/support

**Comment by yuvipanda** [comment]
Thanks for the info, @consideRatio
