### ISSUE TITLE
Add back dirsize reporter for nasa-veda, nasa-ghg, gridsst, ubc-eoas

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3458]
They are disabled to mitigate upgrade failures stemming from `helm upgrade`'s `--wait` flag that makes the upgrades error since the pods are in a craashloop. Disabling them shouldn't have changed much since they weren't running reliably.

## Action point

- Await a resolution to https://github.com/yuvipanda/prometheus-dirsize-exporter/pull/7
- Revert #3459

**Comment by yuvipanda** [comment]
@consideRatio I believe this was done, right?

**Comment by consideRatio** [comment]
Nice catch @yuvipanda yes!
