### ISSUE TITLE
[Request deployment] New Hub: Tufts University

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#3470]
### The GitHub handle of the community representative

- @whumph-tufts; Will.Humphries@tufts.edu

### Hub important dates

- **Target Start Date:** 2023-12-08
- **Required Start Date:** 2023-12-15

### Hub Authentication Type

Institutional Provider via CILogon (e.g., username@institution.org)

### First Hub Administrators

- Will Humphries; Will.Humphries@tufts.edu
- Peter Nadel; Peter.Nadel@tufts.edu
- Kyle Monahan; Kyle.Monahan@tufts.edu

### [GitHub Auth only] How would you like to manage your users?

None

### Hub logo image URL

https://brand.tufts.edu/sites/g/files/lrezom786/files/styles/large/public/2022-09/tufts-ext.jpg

### Hub logo website URL

https://www.tufts.edu/

### Hub user image GitHub repository

Data8 style hub

### Hub user image tag and name

Latest Data8 software image

### Extra features you would like to enable

- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

GCP (default and preferred)

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

This is a request for a pilot deployment of an education hub designed to serve Data8-style instruction for Tufts University. 

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by colliand** [comment]
I add @pnadelofficial to the anchor issue. Thanks Peter! We look forward to working with you.

**Comment by sgibson91** [comment]
@colliand Since this hub will be using CILogon for authentication, and not GitHub, can you please update the "First Hub Admins" section with their institutional emails rather than GitHub handles please?

**Comment by sgibson91** [comment]
> ### Hub user image GitHub repository
> Data8 style hub
> 
> ### Hub user image tag and name
> Latest Data8 software image

@colliand Can you be more specific here please? I don't know what image the "latest Data8 style" is referring to

**Comment by colliand** [comment]
Emails added in anchor comment.

**Comment by colliand** [comment]
Sorry Sarah! For example: https://tuskegee.cloudbank.2i2c.cloud/hub/

I understand that educational hubs with "cloudbank" in their URL are set up to support Data8 instruction. Tufts wants that same software image for their pilot deployment.

**Comment by sgibson91** [comment]
Thank you Jim!

Yeah, I see we have a ["cloudbank-data8-image"](https://github.com/2i2c-org/cloudbank-data8-image) as well, I'm just not sure how much involvement we have in that and how much is just Sean!

**Comment by sgibson91** [comment]
A hub is available at https://tufts.2i2c.cloud

@colliand can you please let the community representatives know that they can test this out?

**Comment by damianavila** [comment]
@colliand, also see my related comment at https://github.com/2i2c-org/team-compass/issues/785#issuecomment-1850492393. Thanks!
