### ISSUE TITLE
Implement tiered access to VEDA Jupyterhub

### ISSUE THREAD

**Issue by freitagb** [2i2c-org/infrastructure#3491]
### Context

We currently have two tiers of users who have been granted access to the VEDA hub, internal team members and those external. In the interest of minimizing unanticipated costs, it would be great to limit the availability of compute resources available to external users until we have a better handle on cost monitoring. As I've just learned about this functionality i'm not exactly sure how this is implemented and need guidance on how to provide better requirements. cc @j08lue @wildintellect

**Comment by batpad** [comment]
Copied this issue over to https://github.com/NASA-IMPACT/veda-jupyterhub/issues/8 where it might be more appropriate to track (and cc'ed everyone marked on this ticket)

@yuvipanda if that looks fine, please close here in favour of the ticket, thanks!

**Comment by yuvipanda** [comment]
Going to close this as it's tracked in the veda-jupyterhub issue now. Thanks @batpad
