### ISSUE TITLE
Investigate valgrind processes dying on qcl hub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3495]
From https://2i2c.freshdesk.com/a/tickets/1161

> Several users are having issues where processes are seemingly randomly getting killed.
>
> Personally I was running profiling tests with valgrind (3 hour single threaded process using ~10% of the ram), and maybe 1 in 3 of these processed would be killed (exit process 127, not sure if thats helpful)
>
> Looking at grafana, I confirm that these are not out of memory kills... do you have any diagnostics, or watch dog tools that kill CPU hogging processes? This is somewhat of a critical issue for us as we need to run analysis that takes days to process

**Comment by yuvipanda** [comment]
This user's pod is no longer running, so we should first figure out where it was.

I can find all events related to this user's pod with the following query on stackdriver:

```
resource.type="k8s_cluster" OR resource.type="k8s_node" OR resource.type="k8s_pod" OR resource.type="k8s_container"
log_id("events")
jsonPayload.involvedObject.name="jupyter-jtkmckenna"
```

This shows me that the pod was assigned to `Successfully assigned prod/jupyter-jtkmckenna to gke-qcl-cluster-nb-n2-highmem-4-daaf2382-wgxm` so I can look at that node's logs.

We can then look at all the logs *on that node* (not k8s related) with:

```
resource.type="gce_instance"
labels."compute.googleapis.com/resource_name"="gke-qcl-cluster-nb-n2-highmem-4-daaf2382-wgxm"
```

I can then search through these messages, with `textPayload=~".*Kill.*"` on to the previous query, to see OOM kills (because those messages look like `[11686.043641] Out of memory: Kill process 2603 (flasherav) score 761 or sacrifice child`).

This produces no kills. Just to be sure, I removed the resource name check there, and it found nothing either.

So with this, we can confirm that these are *not* being OOM killed.

**Comment by yuvipanda** [comment]
I then looked at the notebook logs with `resource.labels.pod_name="jupyter-jtkmckenna"` and found nothing relevant there either.

**Comment by yuvipanda** [comment]
Since the whole pod didn't die, this isn't from the jupyterhub idle culler.

**Comment by jtkmckenna** [comment]
Another example of what I suspect is the same issue, (although they were batch processes that weren't being actively watched as closely), were the failure `cgrid` jobs (an in house python program). These would randomly get killed in a similar way (under the user carhels)

On Saturday:
"
2i2c crashed again right before 12 today when I tried to run the final CATF simulations. According to the history there were no out of memory kills, which there shouldn't have been.
![image](https://github.com/2i2c-org/infrastructure/assets/124043374/e6b2c0be-59d9-4338-8be2-5cd81e77df8e)

Now I cannot even restart the server again
![image](https://github.com/2i2c-org/infrastructure/assets/124043374/a92d0e23-ddc7-4e85-ac86-9933abc1fbcf)

get the feeling that they cannot handle close to 100% load for extended periods.

They rarely failed for me when I'm not running something hard.

Which brings me to the obvious question, why should we have a server if it only can handle light loads?

[2:53 PM]

Ok, got back in again but first my account was wiped clean. Logged out and back again and now I see my stuff again.

[4:56 PM]

Crashed again

![image](https://github.com/2i2c-org/infrastructure/assets/124043374/512f8ac4-5aa5-45b0-88dd-c88743487639)

**Comment by sgibson91** [comment]
We got a follow up ticket that this issue is now time critical https://2i2c.freshdesk.com/a/tickets/1163

**Comment by yuvipanda** [comment]
I've responded on the ticket with some suggestions and changes.

**Comment by jtkmckenna** [comment]
This solution is working well for us. The system seems stable and our executing until completion. Would it be add a system to ping us when we've had a server on for more than 24h (since we'll have to remember to shutdown our sessions now)

A https webhook to mattermost would be ideal for us https://developers.mattermost.com/integrate/webhooks/incoming/

This seems something grafana seems to directly support https://grafana.com/docs/grafana/latest/alerting/alerting-rules/manage-contact-points/webhook-notifier/

Would you like us to make a new ticket for a uptime alert webhook?

**Comment by yuvipanda** [comment]
We dealt with the uptime alert via freshdesk I think. Closing this as completed!
