### ISSUE TITLE
[docs] Clarify infrastructure documentation around Grafana access

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3505]
In the context of https://github.com/2i2c-org/infrastructure/issues/1850, some confusions were identified that could be solved by being more explicit in our documentation. The logging in section at https://infrastructure.2i2c.org/topic/monitoring-alerting/grafana/#logging-in should be explicit about:

- [ ] enabling GitHub authentication is a mechanism for giving **viewer** access to the **2i2c GitHub organization members** and potentially to other communities that might want and benefit from such authentication instead of the invite links.
- [ ] the `default` way to give access to communities is via invite links documented at https://infrastructure.2i2c.org/sre-guide/support/grafana-account/.

   But we could also have team members create their own individual admin or non admin accounts if they wished. We don't have a policy about this yet and the general practice is to either use the `admin` username for admin rights or authenticating through GitHub otherwise.

**Comment by sgibson91** [comment]
@GeorgianaElena I opened https://github.com/2i2c-org/infrastructure/pull/3513 to address this but I'm not really sure that I helped all that much?
