### ISSUE TITLE
Document how to setup an AWS account that is paid for by another organization

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3527]
As we do https://github.com/2i2c-org/infrastructure/issues/3394, we recognize there's missing documentation for the case when the AWS account is set up by an external organization and provided to us. We do this in several places, and it actually helps simplify everything as we don't have to do cloud billing in any way.

What we have done so far is:

1. Have the external org create one AWS IAM account with full permissions. Since we have one account per engineer, this should be for a specific engineer - whoever is setting up the hub.
2. Send credentials for this account to `support@2i2c.org`, encrypted [using these instructions](https://docs.2i2c.org/support/#send-us-encrypted-content)
3. This is accessed by the engineer, who decrypts it using [these instructions](https://infrastructure.2i2c.org/sre-guide/support/decrypt-age/)
4. This engineer creates and sends credentials for each engineer
5. Cluster setup continues as usual (following https://infrastructure.2i2c.org/hub-deployment-guide/new-cluster/aws/)

**Comment by damianavila** [comment]
Given the recent deployment @AIDEA775 was involved with (EarthScope), I think he will be a great resource to write these docs and this is why I have assigned it to this issue.
