### ISSUE TITLE
Document how to setup auth0 for specific hubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3533]
As part of https://github.com/2i2c-org/infrastructure/issues/3394, we're going to be using auth0 to authenticate users there. Note that this is not the complex auth0 setup we had earlier, but just a straight up use of the Auth0 authenticator from OAuthenticator, with credentials provided by the org. We are charging extra for this.

- [x] Document how to receive credentials for use here
- [x] Document how to set up these credentials in our config

**Comment by timdittmann** [comment]
@damianavila and @yuvipanda :
I will be on leave for a few weeks, please tag @hamilton-earthscope and @chad-earthscope when you are ready to receive the earthscope Auth0 credentials.  Happy holidays!

**Comment by yuvipanda** [comment]
@timdittmann most of us are on vacation already, so we will probably do that on jan 1st week as well. happy holidays to you too! Everything else has been set up i believe.

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/issues/3637 tracks upstream work, closing as we have docs now.
