### ISSUE TITLE
Automatically pull ghg-docs repo on server start on GHG hub (same as VEDA hub)

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3565]
Via https://github.com/2i2c-org/infrastructure/pull/3124 and follow-up PRs, the NASA VEDA hub automatically clones the [GHG Docs](https://github.com/US-GHG-Center/ghgc-docs) repo each time a user server starts. Per https://2i2c.freshdesk.com/a/tickets/1209, this behavior is desired for the GHG center hub as well.

**Comment by batpad** [comment]
Copied this issue over to the `veda-jupyterhub` repo: https://github.com/NASA-IMPACT/veda-jupyterhub/issues/7 .

@yuvipanda I think you can close here if that looks good / seems like the more appropriate place to track this.

**Comment by yuvipanda** [comment]
\o/ Great!
