### ISSUE TITLE
Migrate this repository's default branch from `master` to `main`?

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3581]
This has been done for most repositories in the jupyter / jupyterhub ecosystem, but I think not been done for this repository. We should do the migration as well.

I haven't done this before though, so am not sure what exactly it entails. I do think it's not too bad though?

EDIT: How to go about this is documented in https://github.com/jupyterhub/team-compass/issues/412

**Comment by consideRatio** [comment]
I think doing it is fine and reasonable, concrete steps to do it can be found in jh team-compass issue by Simon - these migrations have been quick and simple i'd say

**Comment by jmunroe** [comment]
This makes sense to me!  I've been noticing that I have to consciously remember that this repo is still using `master` and it routinely trips me up.
