### ISSUE TITLE
Draft notes from AKS upgrade

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3591]
### On the fly changes

- I created a `core_node_pool` variable to hold misc configuration on our core node pool
- I configured the new user node pool to use ephemeral (aka. `Temporary`) disks instead of persistent disks (aka. `OS`) based on seeing an Azure portal recommendation combined with knowing that we use ephemeral disks for our nodes in GKE for example.

### Misc observation

The `default_node_pool` is required, and its a system type of node pool, which makes it unable to scale to zero. Due to this we should make use of that specific node pool. We could upgrade it without re-creating the cluster it seems, but only with a new terraform provider for the cluster versioned v3+, but I failed to migrate to it from v2. A fixme note about this is added in terraform config files and discussion is tracked in https://github.com/2i2c-org/meta/issues/539.

---

The `default_node_pool` we use as a core node pool can only be upgraded one minor version at the time. I expected that I should be allowed to let it be behind 3 minor versions behind the control plane.

---

The following was observed to upgrade during k8s control plane upgrade, but not `coredns`.

```
daemonset/cloud-node-manager
daemonset/csi-azuredisk-node
daemonset/kube-proxy
deployment/konnectivity-agent
deployment/metrics-server
```

---

`calico-typha` forces three core nodes, and its deployment's configured replica's is controlled by a `tigera-operator` so it can't be edited directly but must be edited by the operator. I opened #3592 about this.

**Comment by yuvipanda** [comment]
Closing this one now, thanks for reporting back!
