### ISSUE TITLE
Provide way to repeatably deploy new clusters

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#36]
All clusters we support must have a few things in common:

1. Kubernetes clusters with multiple nodepools, autoscaling, etc
2. An NFS server (in-cluster, ideally) providing home directories
3. Prometheus & Grafana
4. An ingress controller + cert-manager, for HTTPS & wildcard DNS support

This should be as uniform as possible across the various places we deploy.

We should build terraform scripts and helm charts to automate this properly.

**Comment by yuvipanda** [comment]
The terraform scripts and support chart we have work remarkably well on GKE, with the exception of setting up the NFS server - that is still manual. #50 should solidify this.

**Comment by choldgraf** [comment]
Superceded by #645
