### ISSUE TITLE
[Support] nbgitpuller link breaks after update - University of Toronto

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3603]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/1229

### Ticket request type

Something is not working

### Ticket impact

🟥 Critical

### Short ticket description

Nbgitpuller links not working.

When the hub is:
- pointing to[ https://jupyter.utoronto.ca](https://jupyter.utoronto.ca/) or[ https://datatools.utoronto.ca](https://datatools.utoronto.ca/) it gives 404 or page not found
- pointing to[ https://r.datatools.utoronto.ca](https://r.datatools.utoronto.ca/) it thows  the following (see screenshot below)
![utoronto-nbgitpuller-error](https://github.com/2i2c-org/infrastructure/assets/7579677/7d863221-db5f-4e7d-9736-558158f9b8a5)

### (Optional) Investigation results

No investigation happened yet as I wanted to first open the issue for visibility.

**Comment by GeorgianaElena** [comment]
nbgitpuller works with https://r.datatools.utoronto.ca/ if the repo is public.

However the repo in the ticket is private and it was reported that it worked on Monday, I believe before the migration?

**Comment by GeorgianaElena** [comment]
I am confused of the fact that I don't see evidence that private GitHub pulling was setup for the toronto hub https://infrastructure.2i2c.org/howto/features/private-nbgitpuller/#allow-nbgitpuller-to-pull-from-private-github-repos

**Comment by GeorgianaElena** [comment]
Ahh, the GitHub app is not under the 2i2c org, this is why I couldn't find it. `git-credentials-helper` is setup at https://github.com/2i2c-org/infrastructure/blob/b6846fb9814bc613b8f442fc00f5faf2699ebe28/config/clusters/utoronto/common.values.yaml#L59-L65

**Comment by GeorgianaElena** [comment]
`git-credentials-helper` is available in the original utoronto hub image https://github.com/2i2c-org/utoronto-image/blob/14320bae73a0570aa1ab1b19c68758894b291979/environment.yml#L42 but not in the new r-image.

https://github.com/2i2c-org/utoronto-r-image/pull/17 should make it available

**Comment by GeorgianaElena** [comment]
Opened https://github.com/2i2c-org/infrastructure/pull/3604 to move the setup of the https://github.com/organizations/utoronto-2i2c/settings/apps/utoronto-jupyterhub-private-cloner app under the default hub, as I believe we need a new one for the R hub

**Comment by GeorgianaElena** [comment]
Hmm, the weird thing is that using nbgitpuller with a private repo on https://jupyter.utoronto.ca doesn't work either, although it seems to have everything setup 🤔

**Comment by GeorgianaElena** [comment]
I've opened https://github.com/2i2c-org/infrastructure/pull/3605 that registeres the new GitHub app created to be used for pulling by the r hub https://github.com/organizations/utoronto-2i2c/settings/apps/utoronto-r-hub-private-cloner

**Comment by GeorgianaElena** [comment]
I believe what remains now is to merge the PRs below:
- https://github.com/2i2c-org/utoronto-r-image/pull/17
- https://github.com/2i2c-org/infrastructure/pull/3605
- https://github.com/2i2c-org/infrastructure/pull/3604

and then update the r hub user image with a tag that has https://github.com/2i2c-org/utoronto-r-image/pull/17

**Comment by yuvipanda** [comment]
I merged and then reverted https://github.com/2i2c-org/infrastructure/pull/3606 - it turns out https://github.com/2i2c-org/utoronto-r-image/pull/17 was actually the only change needed! It does mean that the same GitHub app is used for both jupyter.utoronto.ca and r.datatools.utoronto.ca, but that's actually ok as it makes the migration from jupyter.utoronto.ca to r.datatools.utoronto.ca easier - people will not have to reinstall.

**Comment by yuvipanda** [comment]
I opened https://github.com/2i2c-org/infrastructure/pull/3608 to document. @GeorgianaElena do you think it's ok to delete the github app created for the R hub? 

We should probably try to bring the github app for the jupyter app to this org! But idk if that means everyone will have to reinstall the app?

**Comment by GeorgianaElena** [comment]
Thank you @yuvipanda for sorting this out! I've deleted the new app and will close this issue as it's now resolved 🚀
