### ISSUE TITLE
[Support] Deploy a nbgitpuller link for HHMI:Spyglass

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3624]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/1233

### Ticket request type

Feature Request

### Ticket impact

🟧 High

### Short ticket description

Configure the mysql database server that's running on the hhmi hub with `dj_local_conf.json` and `dj_local_conf_franklab_collaborators.json` from https://github.com/LorenFrankLab/hhmi-spyglass-image/blob/main/postBuild.

## Context

The ticket was initially framed as _"why running the https://github.com/LorenFrankLab/hhmi-spyglass-image/blob/main/postBuild script is not working"_.

## Desired behaviour - two scenarios

The community described that there are two scenarios they are after. They are described in more detail in https://2i2c.freshdesk.com/a/tickets/1233 and also context about the initial partnership agreement is provided there. Below is a bullet list summary.

### 1. _"Collaborator access to the hhmi database and data processing pipelines with the ability to pull data to the hub and use the compute to run analysis on the data."_

  - having things persist in storage is important 
  - give access to collaborators to the tutorial notebooks located in https://github.com/LorenFrankLab/spyglass/tree/master/notebooks
  - have the configuration file for the hhmi database and notebooks (`dj_local_conf_franklab_collaborators.json`) in the users' _$HOME/spyglass_ directory to connect and run the tutorials

🟦 **Next steps:** ?
- Use this [nbgitpuller link](https://hhmi.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FLorenFrankLab%2Fspyglass&urlpath=tree%2Fspyglass%2Fnotebooks&branch=master) to get the desired repository into each users' home directory and start them in the `notebooks` directory
- Use [singleuser.extraFiles](https://z2jh.jupyter.org/en/stable/resources/reference.html#singleuser-extrafiles) to mount these two files into the desired directory in the user's home dir

 ### 2. _"Create a binder link that would correspond to the preprint on the hhmi data processing pipelines so that anyone that reads the preprint can try out the pipelines."_

  - storage would not be persistent from session to session
  - the users would use the configuration file (`dj_local_conf.json`) to quickly connect to the local database and be able to run the tutorial notebooks.
  - no need for the user to select the amount of compute in this scenario (as it is set up now).
 
🟦 **Next steps:**?
  - ❗ Out of scope of the existing hub I believe
  - needs [a new hub with ephemeral storage](https://infrastructure.2i2c.org/howto/features/ephemeral/) as advertised by @colliand in the plan shared with the communty (and shared in the ticket)

**Comment by GeorgianaElena** [comment]
Got a timeline for this: it should be ready by mid-February.

Apart from mounting the two config files, I believe we also need to setup some storage for the database similar to https://infrastructure.2i2c.org/howto/features/per-user-db/#setting-up-the-backing-disk-for-the-database

**Comment by jmunroe** [comment]
I have been directly involved in setting up this community and the MySQL database up to this point. Please involve @jmunroe before taking action on this issue.

**Comment by GeorgianaElena** [comment]
@jmunroe, in this case, do you think you can communicate back to the community about the next steps via Freshdesk? 

There's two tickets: on that is linked here and one in Partnerships about the new hub.

Also, @jmunroe, please feel free to close this issue and open new ones with more relevant info and context.

> Please involve @jmunroe before taking action on this issue.

Also, cc @damianavila for the above ⬆️

**Comment by yuvipanda** [comment]
@jmunroe when you have a minute, can you communicate back to the community on freshdesk? Thanks.

**Comment by jmunroe** [comment]
I've retitled this issue to be more tightly focused on ensure that there is working nbgitpuller link for the Frank's group Spyglass preprint.

(I also respond to the the Freshdesk ticket)

There is dependency step having a new ephemeral hub `spyglass.hhmi.2i2c.cloud` running on the HHMI cluster. That tasks is being tracked in 
- [ ] #3643 

Concurrently,  @jmunroe will work with members LorenFrank group (Eric Denovellis and Chris Brozdowski to create a functional nbgitpuller link that will direct readers to `spyglass.hhmi.2i2c.cloud` and the notebooks as part of the Spyglass preprint. This ephemeral hub needs to have the MySQL database set up and a `df_local.json` configuration file for spyglass so that the reader gets a 'works-out-of-the-box' experience.

The goal for this task is 2024-01-31 .

**Comment by colliand** [comment]
Yay! I think I completed this task using the `nbgitpuller` link: https://spyglass.hhmi.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FLorenFrankLab%2Fspyglass&urlpath=lab%2Ftree%2Fspyglass%2Fnotebooks%2F01_Insert_Data.ipynb&branch=master

**Comment by jmunroe** [comment]
You and I are working on the same task at the same time!

**Comment by jmunroe** [comment]
I strongly think we want to expose a separate repo only the notebooks.  We also need to configure the database configuration file.

**Comment by jmunroe** [comment]
Copy/pasting from slack channel for our records:

> Example:  [Spyglass Magic Link](https://spyglass.hhmi.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fjmunroe%2Fspyglass-notebooks&urlpath=lab%2Ftree%2Fspyglass-notebooks%2Fnotebooks%2F01_Insert_Data.ipynb&branch=main)
> This an nbgitpuller link that directs the user to an non-persistent, unauthenticated JupyterHub spyglass.hhmi.2i2c.cloud set up to explore Spyglass based on the repo https://github.com/jmunroe/spyglass-notebooks . I suggest that this repo (or something very similar) to it is forked into the LorenFrank Github organization and a new 'magic link' is generated using nbgitpuller. (See README.md in the repo for additional instructions)
> Notes:
> - It is pulling from the same 'shared-readwrite' attached storage with the nwb/raw files as we had set up on hhmi.2i2c.cloud. But, to ensure that these do not get deleted by the first person to test out the site, they are mounted as 'read-only'.  Since the Spyglass software requires them to live in a read-writable directory, I've created some symlinks to set this up to work as expected.
> - You probably want to consider something like this for hhmi.2i2c.cloud as well to allow multiple concurrent users to go through the notebooks. Having multiple users attempting to write to the same directory is likely to cause problems.
> - I've created a local DataJoint configuration file in this new repo.  Since the 'configuration' of Spyglass has already occurred, I wonder if you want to edit notebook 00_Setup.ipynb to be make really clear that nothing needs to be set up if you are running through the notebooks on this JupyterHub.
> - Several of the notebooks have graphviz graphs but the command line program dot does not appear to install in the hhmi-spyglass-image.  I've added it to the the image maintained at https://github.com/2i2c-org/hhmi-spyglass-image . I also removed the postBuild -- I didn't think you want to clone the spyglass repo as part of this image (spyglass-neuro is being installed through pip). There may be additional issues with the image that I am working to resolved (I do have some confusion why the image lorenfrank/hhmi-spyglass-image didn't work completely for me but that could be just me)
> - We need to discuss memory usage of these notebooks.  Currently, each user only has 1GB of RAM configured -- we can increase that but still need to decide on an upper limit.  Also, I expect users to rapid start many of the example notebooks and not shutdown kernels from previously running notebooks. This is likely to the user to run out of available RAM even if we increase it.  Is there a smaller subset of the notebooks that you really want to draw attention to?
> - Local storage. This hub is set up with no persistent storage. Files can be written in the home directory but will be removed when the server is stopped.  Note though that multiple users are running on the same node. If each user consume a certain amount of (even temporary) disk space, this may impact other users on the same node. 
> - This idea of 'nodes' may not always be clear during testing: multiple, independent, authenticated users, will be put onto the same virtual machine node. Their containers are isolated but they are sharing the same finite disk on the virtual machine. We can adjust that as needed.  When there are lots and lots of users, the system will automatically scale by adding new nodes as needed (and scale back down afterwards) but there can still be contention for disk space on a single node.
> - Additional testing is required before sharing widely and especially simulating multiple synchronous users ('incogito/InPrivate' web browsing is useful for launching several separate sessions).  2i2c can adjust the amount of RAM and disk space but I think I will need assistance. In particular, sometime one of the notebooks 'doesn't work' (throws errors) but I don't know if that supposed to happen or if it is a configuration issue.


Response:

> Thank you again for all this work. I am impressed with how fast things pulled together.  Let me try to answer these questions and provide some context:
> 1. Our intention is that the pypi package install work for non-developers and be the version that the public uses. In practice, people in the lab have been using the source git repo so we have been tardy on making consistent releases. This has led to some gaps in making sure the package dependencies work for the pypi release which we will rectify. I would like to use the pypi package for the jupyter hub and magic link though.
> 2. We are in the process of making a release that will address some of those problems shortly (I would say within the next week). I would like to not rush it too much as I am fixing the design of one of the pipelines. It is almost done, but I need to test things out and would like to not release things into production that would confuse people in our lab too much.
> 3. That leads me to the forthcoming announcement timing with 
> [@Kristen Ratan](https://2i2c.slack.com/team/UQLDBQ5CZ)
> . Is there a particular timeline for that? I would also like to make sure the link works as we expect before it gets sent out to the wider public. It is obviously exciting but I think a link that doesn’t work as we want won’t be useful for advertising spyglass. As I understand it, we also wanted to collect some data from the link to see how many users, etc. How far away is that from being set up?
> 4. Related to the link, the 1 GB RAM configuration won’t be sufficient based on my experience with the jupyter hub. 3 GB seemed to work fine as far as I could tell.
> 5. How much disk space is allocated for all users? Spyglass does tend to be both disk and memory intensive but it’s hard to tell what the user experience would be like in this case. I would kind of guess that we wouldn’t get too many concurrent users, but I have no idea what the demand will be. I think we need to first make sure things run and then test how it scales.
>

**Comment by jmunroe** [comment]
@yuvipanda Could you increase the available RAM on spyglass.hhmi.2i2c.cloud per user to be 3.4GB (so it matches what we make available on hhmi.2i2c.cloud)

**Comment by jmunroe** [comment]
This issue is now waiting for input in the #hhmi_pilot Slack channel.  Next steps after receiving that input:
- [ ] Move spyglass-notebooks repo out of from @jmunroe to the LorenFrank org
- [ ] Revise the lorenfrank/hhmi-spyglass-image quay.io image so it has the correct versions of software
- [ ] LorenFrank team to create nbgitpuller link based on notes/support from @jmunroe 
- [ ] Evaluate RAM and disk space based on testing and update config as needed\
- [ ] Get signoff from LorenFrank team that content is ready for widespread sharing
- [ ] share nbgitpuller magic link

**Comment by jmunroe** [comment]
This specific task is completed.

Anticipated steps for the initiative are tracked in:
- https://github.com/2i2c-org/meta/issues/789
