### ISSUE TITLE
[Support] Consider deploying real time collaboration to temple university

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3649]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/1230

### Ticket request type

Feature Request

### Ticket impact

🟨 Medium

### Short ticket description

Temple wants us to possibly deploy real time collaboration on their hub by April for some final projects. We don't have RTC enabled anywhere yet, will need to investigate if this is possible.

**Comment by consideRatio** [comment]
> will need to investigate if this is possible

Its doable now if multiple users access the same server, which for example can be done by admin users if accessing others servers is enabled. For this I think only a package needs to be installed in the user environment, see [`jupyterlab-collaborative`](https://jupyterlab-realtime-collaboration.readthedocs.io/en/latest/).

But this isn't great or so easy for 2i2c to help communities with.

## Long term fix

JupyterHub 5 will come with REST API functionality to let users share access to their servers, and this is the kind of function we should aim for I think. Can we get it done before april - maybe. We can work towards getting JupyterHub 5 out as soon as possible as a first step.

For details on this kind of setup, see https://github.com/jupyterhub/jupyterhub/pull/4594 and the documentation it adds.

**Comment by yuvipanda** [comment]
Ah so right now, this requires admin users right now?

In that case, I think we should provide them this information (that it requires jupyterhub 5 and further work, and the links you have). And that we can try again next semester, but will not be possible this time.

**Comment by yuvipanda** [comment]
I've provided that information, and asked them to try again next semester
