### ISSUE TITLE
[Support] Possible to add single google user who doesn't have temple credentials to temple hub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3650]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/1230

### Ticket request type

Feature Request

### Ticket impact

🟨 Medium

### Short ticket description

Temple wants to know if we can add a single user who does *not* have temple credentials, but does have google auth. 

### (Optional) Investigation results

I simply tried to add myself in the JupyterHub admin interface, but because `allow_existing_users` is false, that doesn't actually work. We could just turn this on and it should be ok?

**Comment by consideRatio** [comment]
Adding the username to allowed_users would work here i think, or use of allow_existing_users.

i think use of allow_existing_users should be avoided though as it makes reducing permissions impossible if for example only a subset of users previously allowed remain allowed at a later point in time via "allowed_domains" or similar.

Of course, use of allowed_users is less user friendly to update our config to add individual users though.

**Comment by yuvipanda** [comment]
We aren't going to do this right now.
