### ISSUE TITLE
[Request deployment] New Cluster: projectpythia.2i2c.cloud

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#3652]
## Phase 1: Account setup (**READY**)

This is applicable for cases where this is a dedicated cluster. The following table lists the information before this phase can start.

| Question | Answer |
| - | - |
| Cloud Provider | AWS |
| Will 2i2c pay for cloud costs and recover them via invoice? |  No |
| AWS Account ID | 590183926898 |
| Target Start Date | 2024-05-15 |
| Community Representatives | @jmunroe |
| Technical Contacts added to Airtable? | Yes |

Docs at https://infrastructure.2i2c.org/hub-deployment-guide/cloud-accounts/

Procedure: https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase1/aws-external-account/

@jmunroe is the account owner and can create 

## Phase 2: Cluster setup (**READY**)

This assumes all engineers have access to this new account, and will be able to set up the cluster + support, without any new hubs being set up.

| Question | Answer | 
| - | - |
| Region / Zone of the cluster | us-west-2 | 
| Name of cluster | `projectpythia` | 
| Is GPU required? | Yes | 

Docs at https://infrastructure.2i2c.org/hub-deployment-guide/new-cluster/new-cluster/
and https://infrastructure.2i2c.org/hub-deployment-guide/deploy-support/configure-support/

**Comment by haroldcampbell** [comment]
This can be delay in favour of the catalyst hubs. @jmunroe shared that perspective on [slack](https://2i2c.slack.com/archives/C055A1J1DRP/p1709313097763919?thread_ts=1709237695.196689&cid=C055A1J1DRP).

**Comment by haroldcampbell** [comment]
Phase 1 and Phase 2 are currently ready, but they need to be split into separate tickets. @jmunroe will split this before the planning meeting. This has lower priority than the 4 catalyst requets

**Comment by colliand** [comment]
2024-05-09. @jmunroe points that this is an example of a cross-team dependency. This is completed on the operations board but not closed.
