### ISSUE TITLE
basehub: switch default value of nfs.pv.enabled to false (without changing any final values)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3654]
@sgibson91 discovered that setting `nfs.enabled=false` where you wouldn't want to declare anything else still required `nfs.pv.enabled=false` to be set.

The reason for this is detailed in https://github.com/2i2c-org/infrastructure/pull/3646#discussion_r1471011667, and I think the fix is explicitly start setting `nfs.pv.enabled=true` alongside setting other fields that are required under `nfs.pv` such as `nfs.pv.serverIP`, and defaulting to `nfs.pv.enabled=false` in basehub.

This aligns with the Helm chart best practice of making charts renderable without being passed any config. Now it wouldn't be, because `nfs.enabled=true` and `nfs.pv.enabled=true` by default while we still havn't set the then required `nfs.pv.serverIP`.

**Comment by yuvipanda** [comment]
When this is fixed, this documentation change should be undone (https://github.com/2i2c-org/infrastructure/pull/3656)
