### ISSUE TITLE
Get a shared understanding of our cloud costs

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#3658]
### Context

This is part of the billing goal specification outlined here: https://docs.google.com/document/d/1Ig5fQNJd_Gy9dteCbj8vvsKtxANQb3QUGC6ABYPf08c/edit#heading=h.rw2jk1cur24

### Proposal

Task: Have a shared understanding of our cloud costs
How:
* Outline differences between cloud providers
* Discuss dedicated vs shared clusters
Who: the whole @2i2c-org/engineering team, with the main inputs coming from @yuvipanda 
Dependencies: None
Value: All of our engineers understand the cloud cost associated with the usage of our infrastructure
Measure of success: All the engineers have a shared and basic understanding of how cloud cost works on a per-cloud basis and also take into consideration the differences between our dedicated and shared clusters

### Dependencies
- [ ] https://github.com/2i2c-org/infrastructure/issues/3725
- [ ] https://github.com/2i2c-org/infrastructure/issues/3726

**Comment by damianavila** [comment]
I have assigned this one to @yuvipanda as the current SPoF on this topic and @consideRatio to assist him in moving the issue forward during the sprint.

This will need participation from all the @2i2c-org/engineering team, so I expect feedback from @sgibson91, @GeorgianaElena, and @AIDEA775 as well.

**Comment by yuvipanda** [comment]
I posted this slack, but posting again here:

1. I start writing some documentation and open it up for comments. I've already completed an outline in https://hackmd.io/VMCH0IVOT76n0ac4FA8Qug, and will start filling that in ASAP. I don't entirely know what I know, so it's likely missing some more useful information! If that is obvious, please let me know. I'll post a message here with my progress each day, and would appreciate you all spending at least 15-20 minutes looking through that, and providing feedback. Today, that would just be on the structure.
2. We have a sync meeting (on the 15th is my proposal) that gets recorded to finalize, and have discussions.

Hopefully this makes for a much stronger shared understanding of billing across the engineering organization, and we can go ahead to our next step. How does that sound?

**Comment by yuvipanda** [comment]
My goal here for 2024Q1S2 sprint is to complete the section on 'general overview of cloud costs', so we can all operate from a base shared understanding of how cloud costs work. We couldn't find a spot to meet synchronously, but I've already received a round of feedback on the document. I'll ask for another round of feedback once it's functionally complete.

I would say that the next step here is to do https://github.com/2i2c-org/infrastructure/issues/3725 and https://github.com/2i2c-org/infrastructure/issues/3726, as that is *operational* 'how to' documentation that helps unblock the cloud cost process for dedicated clusters. And it can be primarily done by others, not just me.

**Comment by yuvipanda** [comment]
This has been split into https://github.com/2i2c-org/infrastructure/issues/3761 and https://github.com/2i2c-org/infrastructure/issues/3760 as well

**Comment by yuvipanda** [comment]
Going to close this in favor of https://github.com/2i2c-org/infrastructure/issues/3759
