### ISSUE TITLE
Iterate on docs for working with object storage

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3665]
I think our [working with object storage docs](https://docs.2i2c.org/user/topics/data/cloud/#working-with-object-storage) should explicitly distinguish the following scenarios:

1. __its a 2i2c hub's user environment and its 2i2c hub's associated cloud bucket__

   In this case, writing data should work straight away as credentials should be setup and available for the user as long as the user environment image has relevant cloud CLI tools installed like `aws`, `gcloud`, or `az`.
   
   I know that the `pangeo/pangeo-notebook` is an image that includes the `aws` CLI of relevance for the showcase hub with an AWS bucket.

2. __its their environment / laptop and its 2i2c hub's associated cloud bucket__
   In this case, they need to acquire and configure credentials manually first. They could either get temporary credentials by extracting such from a 2i2c user environment, or use dedicated credentials in the cloud project setup for them personally.
   
   Extracting temporary credentials is discussed in https://github.com/2i2c-org/features/issues/22 and isn't an established  and user friendly procedure yet.

3. __its their environment / laptop and its their cloud bucket__

   I don't think its in scope for 2i2c to help with this or write docs focused on this situation.

**Comment by jnywong** [comment]
Closed by https://github.com/2i2c-org/docs/issues/226
