### ISSUE TITLE
Clearly specify who is responsible for image management for VEDA, GHG and ESDIS hubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3685]
This is a follow-up from a slack conversation about who is responsible for bumping up image tags in the NASA VEDA hubs, and in general image maintenance.

I had said:

> The way I currently think of the seperation is:
> 1. Someone (not 2i2c) is currently responsible for actually rebuilding the image.
> 2. 2i2c is responsible for deploying the image. The two ways to do this are: 1. email [support@2i2c.org](mailto:support@2i2c.org) with a new tag after it has been tested, or 2. just make a PR, updating it in https://github.com/2i2c-org/infrastructure/blob/2a17dfb1d0fc2cfc5d6202cd2af582e090fdabce/config/clusters/nasa-veda/common.values.yaml#L70 (and similar for the GHG hub).
>
> (2)(2) is preferred, as I can just hit merge (assuming it comes from someone we already know).

The image is at https://github.com/NASA-IMPACT/veda-jh-environments.

This issue is to track and codify answers to the following questions:

1. Where do requests for changes to the image go?
2. Who is responsible for evaluating and making those changes?
3. Who is responsible for periodic image updates (bumping up base image tag versions mostly)? And testing them?
4. Who is responsible for updating the image tag used in the JupyterHub config?

**Comment by batpad** [comment]
Now tracked in https://github.com/NASA-IMPACT/veda-jupyterhub/issues/5

**Comment by yuvipanda** [comment]
Thanks @batpad. Closing this here.
