### ISSUE TITLE
[Support] Setup `gh-scoped-creds` for Openscapes

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3693]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/1277

### Ticket request type

Feature Request

### Ticket impact

🟨 Medium

### Short ticket description

This came out of https://github.com/2i2c-org/infrastructure/issues/3614.

Set up `gh-scoped-creds` for use by openscapes. We already have some engineering facing documentation for this in our repo.

**Comment by consideRatio** [comment]
I marked the freshdesk ticket as pending, linking to this issue. Respond to the freshdesk issue after resolving this issue.

**Comment by sgibson91** [comment]
I have done this in #3706 but have not deployed it yet as I don't want to overwrite changes made in #3705 (for #3695)

- GitHub app public link: https://github.com/apps/openscapes-github-push-access

**Comment by colliand** [comment]
FYI @jnywong as this issue overlaps with a documentation task you are working on during the upcoming week.

**Comment by jnywong** [comment]
Thanks @colliand ! Yeah installing a GH App to the GH org of a user community is not well explained in our user docs. T

There's an associated task with updating the `infrastructure` repo with the GH App client ID whenever a community wishes to use `gh-scoped-creds` (see [Infrastructure Guide](https://infrastructure.2i2c.org/howto/features/github/)). Will 2i2c engineering continue to take ownership of this task? And does this generally get picked up via FreshDesk?

**Comment by sgibson91** [comment]
closed by https://github.com/2i2c-org/infrastructure/pull/3706

I'm closing this as the technical work has been completed. @jnywong would you like to track your question in a different/dedicated issue?

**Comment by jnywong** [comment]
> closed by #3706
> 
> I'm closing this as the technical work has been completed. @jnywong would you like to track your question in a different/dedicated issue?

Done!
