### ISSUE TITLE
[Support] Setup persistent S3 bucket for openscapes

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3694]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/1278

### Ticket request type

Feature Request

### Ticket impact

🟨 Medium

### Short ticket description

This also came out of https://github.com/2i2c-org/infrastructure/issues/3614

Setup a persistent S3 bucket for use by users on this hub.

### (Optional) Investigation results

https://github.com/2i2c-org/infrastructure/issues/3273 is related, and may need to be resolved first.

**Comment by yuvipanda** [comment]
This needs https://github.com/2i2c-org/infrastructure/issues/3273 first.

**Comment by yuvipanda** [comment]
We don't actually need #3273 here I think - we can just follow the current instructions as they are.

**Comment by sgibson91** [comment]
PR https://github.com/2i2c-org/infrastructure/pull/3832 is ready for review and has been deployed to the staging hub for testing
