### ISSUE TITLE
[Support] Add `nasa-openscapes-workshops` org to access list for openscapes

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3695]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/1284

### Ticket request type

Feature Request

### Ticket impact

🟨 Medium

### Short ticket description

This came out of https://github.com/2i2c-org/infrastructure/issues/3614

Add a GitHub org + some specific teams to the access list for openscapes.

This is a new org, so we may need to do the additional steps required to make sure that we have access to those.

**Comment by yuvipanda** [comment]
I've temporarily invited @sgibson91, @GeorgianaElena and @consideRatio to be owners of this org so it is easier for them to get this done.

**Comment by sgibson91** [comment]
I've taken this on, but @yuvipanda is it also possible to get access to the https://github.com/nasa-openscapes org as well? I've nervous that in reforcing the auth flow to grant permissions to the new org, I've revoked permissions to the existing org and want to double check.

**Comment by yuvipanda** [comment]
@sgibson91 you have been invited to that org as well!

**Comment by sgibson91** [comment]
Thanks Yuvi! I confirmed that both orgs have maintained access to the OAuth app. Erik had a question in #3705 about whether user servers should be restricted to specific teams. That's a question for the community and I don't really want to be interacting with Freshdesk when I'm not on rotation.

**Comment by yuvipanda** [comment]
The community has reported that this is not working, via freshdesk.

**Comment by sgibson91** [comment]
@yuvipanda did #3716 fix this? Can it be closed again?

**Comment by yuvipanda** [comment]
Yes it did!
