### ISSUE TITLE
[Deadline: July 23] [New Hub] NeuroHackademy 2024

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#3713]
**Note**: Refined by @yuvipanda. non-standard format of this new hub issue is due to the fact we are bringing back an old hub.

1. Revert https://github.com/2i2c-org/infrastructure/pull/3539
2. Remove all the bits about the configurator (because we will be using profiles)
3. Move the hub to `2i2c-aws-us` cluster (because GPUs are needed, and I don't think the 2i2c GCP cluster is in a region with GPUs)
4. Add a standard GPU profile

**Comment by jmunroe** [comment]
See 
- https://github.com/2i2c-org/infrastructure/issues/2681

for the last time we set up a hub for this group.

**Comment by yuvipanda** [comment]
@jmunroe can I ask you to make a new hub request here so we can get this prioritized?

**Comment by arokem** [comment]
Can I make an additional request related to this hub? We'd love for there to be an option for users to commission GPU instances for some sessions (but not all). Is it possible to add a selection menu on startup with instance type?

CC: @noahbenson

**Comment by yuvipanda** [comment]
@arokem hey! we can add a profile list at startup, and restrict users based on github team memberships. Does that work for you?

**Comment by arokem** [comment]
A profile list at startup would be great. I don't think that we need to restrict this by group, though. We'll teach all the members of the hub how to use this list and how to make sure that they are using the right resources for each session.

**Comment by yuvipanda** [comment]
@arokem sounds good. BTW, I know we have historically run this on Google Cloud - if needed, are you ok with us running this on AWS?

**Comment by arokem** [comment]
Yes, that would be fine! In fact, many of the open datasets we work with are already in AWS, so there might even be some advantage to going with AWS.

**Comment by yuvipanda** [comment]
@arokem great, I'll just move this to AWS.

**Comment by GeorgianaElena** [comment]
@arokem, I've deployed the hub and it's running at https://neurohackademy.2i2c.cloud/ 🚀 

I've reused the info from last year on logo, links, funding, authentication and also the user image. Can you please look around and let me know what I should be updating and if there's anything that doesn't work so I can update it?
Thank you!

**Comment by arokem** [comment]
Works great! A few things to update: 

- We need to grant access based on membership in this GitHub organization: https://github.com/NeuroHackademy2024. We'll add all our participants sometime next week. 
- Could you please remind me where I find the documentation for how to update the user image? We might need to introduce a couple of small changes to that. 
- We will also want to update the curriculum repo. Is that a configuration I can access? The repo doesn't exist yet, but I'll create it early next week.

Thanks!

**Comment by GeorgianaElena** [comment]
@arokem, thank you for the feedback!

> We need to grant access based on membership in this GitHub organization: https://github.com/NeuroHackademy2024. We'll add all our participants sometime next week.

I've just switched the authentication and authorization on the hub to grant access to this org. If you logout and log back into the hub, and [make sure you grant the right permissions](https://infrastructure.2i2c.org/hub-deployment-guide/configure-auth/github-orgs/#granting-access-to-the-oauth-app) to the OAuth app, it should take effect. 

> Could you please remind me where I find the documentation for how to update the user image? We might need to introduce a couple of small changes to that.

When using a profile list, the configurator (which is what was used for previous hubs) won't be available and updating the user image will have to go through the 2i2c support process (https://docs.2i2c.org/support/) and we will update the image and tag.

But I've added a new profile to the spawn page that says "bring your own image" that you can use to start a custom image. This can be used for testing the image and once you're happy with it, we can remove the profile option and update the default one, before the workshop. Does that sound good to you?

> We will also want to update the curriculum repo. Is that a configuration I can access? The repo doesn't exist yet, but I'll create it early next week.

Once the repo is ready, just let us now via the support email and we will update it.

**Comment by yuvipanda** [comment]
@arokem I suggest you make PRs to https://github.com/2i2c-org/infrastructure/blob/main/config/clusters/2i2c-aws-us/neurohackademy.values.yaml with image tag changes - much faster than going through support, especially given I know you can probably make the change fairly easily :)
