### ISSUE TITLE
[Support] Finalize earthscope domain migration, a documentation thing remains

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3715]
There is a documentation matter remaining to resolve the ticket https://2i2c.freshdesk.com/a/tickets/1280, this issue tracks that.

Yuvi is aware what this is about in more detail,. I created this to not loose track of this and leave a freshdesk ticket stranded.

**Comment by yuvipanda** [comment]
Fixed by #3883
