### ISSUE TITLE
Build a process for regular effort estimation for the prioritization of ideas in the Delivery Flow

### ISSUE THREAD

**Issue by Gman0909** [2i2c-org/infrastructure#3724]
### Context

As part of our efforts to improve our processes for delivering value to our communities, we're looking to introduce a [Delivery Flow](https://miro.com/app/board/uXjVNvlBa6E=/?share_link_id=790400174185) process to help us prioritize high-value work aligned with strategic objectives. 

As part of the Delivery Flow, ideas for potential projects are assigned a set of values to help prioritize them:

- **Impact**: How wide ranging is the impact of this feature on 2i2c or the entities it serves.
- **Request** frequency: how many individual community partners or other customers have mentioned this, or outright requested it. The more requests, the more we should pay attention.
- **Strategic alignment**: How close is this idea to the goals of the organization, 	its mission, and value proposition? We should always aim to prioritize ideas that are closely aligned with those guiding principles.
- **Effort**: How much effort would this take to implement.

The ideas, once assigned those values, can be sorted by their overall value/effort score, giving us an additional level of context when deciding where to put our efforts:

![image](https://github.com/2i2c-org/infrastructure/assets/12699608/78dfc562-8e1f-451f-9166-b9fd697ccdbd)

We are currently missing an expert to estimate the Effort value.

### Proposal

We should assign an expert with engineering expertise to regularly canvas the [Ideas board](https://2i2c.productboard.com/feature-board/7803674-product-ideas) and add their best guess into the Effort column. 

@Gman0909 has had an initial discussion with @damianavila on the subject.

**Comment by damianavila** [comment]
@haroldcampbell, quick (and probably not easy to answer 😉 ) question: how we could make sure we incorporate pieces of this recurring task in the upcoming sprints so we can unblock @Gman0909?

**Comment by yuvipanda** [comment]
As we're refining my role at 2i2c some more, this looks like something I would like to participate in. @Gman0909 thoughts on doing a sync session to go through this so I can understand how I can be helpful here?

**Comment by yuvipanda** [comment]
Me and @Gman0909 have a meeting scheduled next thursday to push forward on this.

**Comment by yuvipanda** [comment]
The goal for the meeting is both:

1. Do a round of prioritization, so I can understand how to do that in a way that's useful
2. Build a recurring process for this so it's done on a consistent basis

**Comment by yuvipanda** [comment]
Me and @Gman0909 did a round of prioritization, and I have a better understanding of the process now.

@Gman0909 now that we have a recurring monthly 1:1, do you think that's enough to count as process for making sure this can be done regularly? I'm also open to us trying to have a **different** process for that - maybe an asynchronous check-in every 2 or 3 weeks?

**Comment by Gman0909** [comment]
@yuvipanda Yes, for now I think that will be enough. I think we can close this issue.
