### ISSUE TITLE
[Request deployment] New Hub: Bioinformatics Hub of Kenya Initiative

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#3821]
This a part of the Catalyst Project on the catalystproject-af cluster. Please use standard catalyst profile developed in 
- https://github.com/2i2c-org/infrastructure/issues/3631

URL: bhki.af.catalystproject.2i2.cloud

### The GitHub handle of the community representative

pending

### Technical support contacts listed

- [ ] Technical contact present

### Hub important dates

pending

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

pending

### [GitHub Auth only] How would you like to manage your users?

None

### [GitHub Teams Auth only] Profile restriction based on team membership

pending

### Hub logo image URL

pending

### Hub logo website URL

pending

### Hub user image tag and name

pending

### Extra features you would like to enable

- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

None

### (Optional) Billing and Cloud account

None

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by jmunroe** [comment]
Please use 

Michael Kofia Landi, @LandiMi2

**Comment by jmunroe** [comment]
@LandiMi2 can you test the hub? It was deployed at https://bhki.af.catalystproject.2i2c.cloud/

Also, you are invited to the Github team https://github.com/orgs/CatalystProject-Hubs/teams/bhki

**Comment by LandiMi2** [comment]
@jmunroe , I did try to login, but it seems I have not been added to the list of allowed users for this hub(error message).  This [link](https://github.com/orgs/CatalystProject-Hubs/teams/bhki) is broken.

**Comment by LandiMi2** [comment]
@jmunroe Yes, I tested the hub, and it is okay. I joined the GitHub team too. Thanks. I'll be meeting Katherine next week for more information.
