### ISSUE TITLE
Make hidden files viewable/editable in the hub

### ISSUE THREAD

**Issue by JILPulvino** [2i2c-org/infrastructure#384]
# Summary

In wanting to make edits to a .gitignore file, it seems that being able to view and edit the file in the hub requires changing the name of the file to remove the `.` in the terminal, editing the file, and then changing the name back. This isn't difficult, and all files can be identified using `ls -a` in the terminal, but it would be nice to maybe be able to choose to show all hidden files by default for admins.

# User Stories

- As a repo admin, it enables me to more easily edit hidden files, namely the .gitignore.

# Acceptance criteria

Users can toggle to reveal hidden files on or off.

# Important information

Appears this is possible in sagemaker? https://stackoverflow.com/questions/52222461/how-to-edit-gitignore-in-jupyter-lab

**Comment by damianavila** [comment]
More details available here: https://github.com/jupyterlab/jupyterlab/issues/2049.
It seems there is a way to set up the config to show hidden files BUT there is not a toggleable option to show/hidden on the fly.

**Comment by choldgraf** [comment]
I wonder if https://github.com/jupyterlab/jupyterlab/pull/9687 would also provide a solution for this...

**Comment by damianavila** [comment]
Maybe... but that still feels like a workaround, IMHO.

**Comment by choldgraf** [comment]
definitely a workaround, but at least then it would be _possible_. Currently I don't know of any way to edit hidden files/folders in JupyterLab which is (IMO) super annoying

**Comment by yuvipanda** [comment]
This is enabled now!
