### ISSUE TITLE
Document setting `paid_by_us` when creating `cluster.yaml` file

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3853]
A subtask of https://github.com/2i2c-org/infrastructure/issues/3711.

We should insert into the appropriate location of our documentation for creating a cluster.yaml to set `billing.paid_by_us`. So #3711 can act as a cleanup of our backlog, and after that this can just be set up for new clusters as they come up.

**Comment by consideRatio** [comment]
- GCP: There is a deployer script to generate cluster.yaml, that script makes use of a template, and the template is updated to include billing.paid_by_us.
- AWS: Updated documentation about this

**Comment by consideRatio** [comment]
- closed by #3946
