### ISSUE TITLE
Rename of `paid_by_us` to `paid_by_2i2c`

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3861]
We have `gcp.billing.paid_by_us` and I'm to introduce `aws.billing.paid_by_us` in cluster.yaml files. I'm considering the naming for clarity. I think changing this name won't have complicated consequences.

I think `paid_by_2i2c` is an improvement because then we don't assume who is "us".

OK to proceed at some point in time? I'm not doing this now, just look to enable doing it later.

**Comment by yuvipanda** [comment]
Sounds good to me, just go for it if you feel like.
