### ISSUE TITLE
[EPIC] EarthScope: Restrict access to profiles based on scopes granted

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3900]
EarthScope wants to restrict access to profiles based on specific scopes granted to them.

I think the sustainable pathway to this is to do this based on *group* membership. This matches with a lot of the new work going on upstream. We can start this out in Earthscope, but eventually be able to expand this in other places. It also will eventually help us get rid of the hacky setup for restricting access to profiles based on GitHub Teams (https://github.com/2i2c-org/infrastructure/blob/120e88dfe77fe6b32520bbfc14297c5b2010cd3f/helm-charts/basehub/values.yaml#L979), but that's not a direct part of this ticket.

https://2i2c.freshdesk.com/a/tickets/1453 has additional information, and is our ongoing conversation with them.

The steps here are:

## ✅  Deploy latest OAuthenticator

https://github.com/jupyterhub/oauthenticator/pull/708 was merged a couple months ago, allowing OAuthenticator to manage JupyterHub groups based on results from the OAuth2 provider. This I believe will be deployed whenever https://github.com/2i2c-org/infrastructure/pull/3818 goes out. This allows us some more information about group management.

## Switch to using `GenericOAuthenticator` for using Auth0

https://github.com/jupyterhub/oauthenticator/pull/708 is specifically for GenericOAuthenticator. In https://github.com/2i2c-org/infrastructure/pull/3883, we move EarthScope from Auth0Authenticator to GenericOAuthenticator, so we can make use of this feature. 

Note: While there's upstream work from me to move this functionality away from just GenericOAuthenticator (https://github.com/jupyterhub/oauthenticator/pull/735), I definitely do **not** want us to block this work on that. Those changes will be made in a backwards compatible way, and we can roll them out as and when that gets released.

## Enable mapping granted scopes to JupyterHub user groups

This would be setting the equivalent of the following config:

```
GenericOAuthenticator:
  claims_groups_key: "scope"
  manage_groups: true
```

This should turn scopes granted by oauth2 into groups, and we should be able to see that in the JupyterHub admin UI.

## Enable restricting scopes based on JupyterHub user groups

This would likely be a straight port of our GitHub code (https://github.com/2i2c-org/infrastructure/blob/120e88dfe77fe6b32520bbfc14297c5b2010cd3f/helm-charts/basehub/values.yaml#L979) but to use JupyterHub groups. At this point, this will be only in earthscope, but primed for proper upstream contribution.
```[tasklist]
### Tasks
```

**Comment by haroldcampbell** [comment]
The outstanding work is to review and merge the draft PR.

**Comment by yuvipanda** [comment]
@GeorgianaElena would you be able to work with me on this?

**Comment by GeorgianaElena** [comment]
@yuvipanda, sure!

**Comment by yuvipanda** [comment]
This has been completed.
