### ISSUE TITLE
[preventive support] opensci had requestor_pays permissions configured - not supported on AWS

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3931]
I'm out of time to look into this further now, but opensci is an AWS cluster, and while we have a `requestor_pays` flag under `hub_cloud_permissions` for GCP, we don't respect such flag on AWS. So, I think there could be a broken expectation as we seem to have setup something that won't work.

https://github.com/2i2c-org/infrastructure/blob/dab06b9fa79cab504aa80f7fc4d32b3d96d7e393/terraform/aws/projects/opensci.tfvars#L17-L28

**Comment by GeorgianaElena** [comment]
@consideRatio, I believe creating buckets with  requestor_pays : true was mistakenly coming as default from the templates. Now it should have been removed, so I don't believe this community ever asked for this feature and it should be safe to be removed completely.

Also, searching after `opensci` in issues and in freshdesk tickets revealed no such request.

**Comment by consideRatio** [comment]
Excellent, thank you @GeorgianaElena for getting to the bottom of this!
