### ISSUE TITLE
Help with review for JupyterHub 5 release

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3953]
I know Min is working towards a JupyterHub 5 release, I think time should be invested towards helping him with any review effort needed.

This isn't a single sprint thing with clearly defined tasks, but the definition of done is that JupyterHub 5 has been released and become seemingly stable.

## Related

- https://github.com/jupyterhub/jupyterhub/issues/4788

**Comment by yuvipanda** [comment]
This is done because JupyterHub 5.0 is out now!
