### ISSUE TITLE
[Feature Enablement] Allow access to an external S3 bucket from CryoCloud

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3978]
# Source of request

https://2i2c.freshdesk.com/a/tickets/1508

# Feature to enable

Allow access to buckets in other AWS projects from the hub. https://infrastructure.2i2c.org/howto/features/buckets/#granting-access-to-cloud-buckets-in-other-cloud-accounts-projects

# Hub

`nasa-cryo`, staging and production hubs.

# Information needed for feature enablement to be completed

| Question | Answer | Note |
| - | - | - |
| Name of bucket | `sliderule-public` | |
| Has the appropriate policy been attached at the source? | yes | step 1 & 2 have been completed, we can go to 3 |

# How to test

We can test on the staging hub, to avoid disruption

1. Terraform apply and manually deploy to staging
2. Install [aws cli](https://infrastructure.2i2c.org/howto/features/buckets/#testing-access-to-buckets) in the image if needed.
3. Run `aws s3 ls s3://<name-of-bucket>` to see if it works

**Comment by yuvipanda** [comment]
I'm also testing how our new 'definitons of ready' described via https://github.com/2i2c-org/meta/issues/953 can help here. This is a possible template for 'Feature enablement', that we can tweak.

**Comment by consideRatio** [comment]
I think we lack some docs to help the community managing the external bucket to grant access to the specific IAM role for users on the hub.

I think historically, maybe the assumption has been that they grant public __read__ access as long as __requester pays__ for it or similar, but they may want to grant only the hub user's associated IAM role access (read __or readwrite__ etc), __not necessarily to anyone__.

I suspect that the docs currently written as...

```
3. In the `.tfvars` file for the cluster hosting the hub, add `extra_iam_policy`
   as a key to the hub under `hub_cloud_permissions`. This is used to set any additional
   IAM permissions granted to the users of the hub. In this case, you should copy the
   exact policy that was applied to the bucket in step 2, but remove the "Principal" key.
   So it would look something like:
```

... we may actually just be needing to specify that we allow our IAM role to pay for access costs to the external bucket or similar, and that the permissions on what kind of access we have, is determined in the external bucket's access policy.
