### ISSUE TITLE
Automate cloud billing CSV transformation (GCP + AWS)

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3989]
Part of https://github.com/2i2c-org/infrastructure/issues/3958

Given we know what CS&S needs to bill, and we already have manual instructions for cloud cost data (insert link), write a deployer subcommand that takes as input:

1. A local path to CSV file generated from the cloud UI
2. Transposes that to the format CS&S wants
3. Outputs a CSV file to be manually uploaded to appropriate google drive location

After this, we update the manual billing instructions with these two extra steps.

These will be two different commands, so they will output two different CSVs - one for GCP, one for AWS. We will ignore Azure. 

We will create a google drive directory that will be linked to from the instructions as the place to upload. A naming convention will be codified by the output file name of the script, but it will also be documented as well.

This will likely be a different 'verb' / command (transform), rather than be added on to the 'generate' verb we have

# Considerations

1. Outputting a new CSV file instead of merging with existing billing google sheet, to avoid clobbering that sheet and to avoid it becoming unmanageble over time as more stuff gets apended to it. As this is not scoped to integrate with the google sheets api (with the `gsheets` package or otherwise), doing this would be out of scope as well.
2. We want to keep this simple and scoped, so we are not going to automate uploading this to google sheets
3. We can come back to the bigquery automation later if needed, but this will remove chances of copy paste errors without adding another human into the loop (for verification / independent control) or depending on more complex automation (bigquery).

# Schema of the output CSV

1. Name of project
2. One column for each month found in the input CSV - direct copy of the 'subtotal' column from the input CSV (GCP), for AWS (to be determined)
3. One column with total $$$ for all the things found

(@sgibson91 wrote most of this, I was just transcribing)

**Comment by sgibson91** [comment]
Super rough draft of this for GCP available in https://github.com/2i2c-org/infrastructure/pull/3992

**Comment by sgibson91** [comment]
The technical aspect of this issue is ready to be reviewed in https://github.com/2i2c-org/infrastructure/pull/3992
I will open another PR to update our process docs https://infrastructure.2i2c.org/howto/bill/

**Comment by sgibson91** [comment]
Documentation is ready to be reviewed https://github.com/2i2c-org/infrastructure/pull/4063

**Comment by sgibson91** [comment]
I also added a minimal readme to the cloud costs google drive folder https://docs.google.com/document/d/1Dqvom9-oU4dgCy59UFMU5R8LWxYK4JmUKZ5usVqSrRo/edit?usp=drive_link
