### ISSUE TITLE
Change our code review policy to increase autonomy (along with psychological safety) for engineers

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3997]
### Description

Reviewing PRs in this repository is important for at least the following reasons:

1. Spreads knowledge around the team, so no single person becomes a bottleneck. It also helps develop good working relationships over time.
2. Helps catch issues before they hit production (via typos, architecture review, testing, etc). This will never be 100%, but the goal is to catch the obvious issues.

These are important reasons, and we should continue doing code review. However, we are also a **very** small engineering team with limited resources, and *proper* code review takes a lot of time. We should explicitly make time for review in our sprint planning process (I think @damianavila is going to create a different issue for that, as follow-up from https://github.com/2i2c-org/infrastructure/pull/3918).. Part of that is being more discerning about *what* needs review, and what does not. By eliminating reviews that don't directly help with the two stated goals earlier, we can free up more capacity for reviews that do.

### Scope

This issue is scoped specifically to:

1. This repository (infrastructure/) and https://github.com/2i2c-org/default-hub-homepage.
2. **Clearly** defining criteria for PRs that can be 'safely' self merged. 

### Why is this important?

1. Increasing engineering capacity is an important part of extending our organizational runway. By reducing the overall amount of things engineering has to do, we increase our capacity quite a bit :)
2. Code review is very important, and when done correctly, takes a lot of time. This allows us to focus our efforts on *where* code review gives us most bang for the buck, and 

### Measures and definition of done

This will mostly include expansion of this documentation section: https://infrastructure.2i2c.org/contributing/code-review/#self-merging-as-a-2i2c-engineer

We can call this done after 1 round of the following tasks are complete. We can re-evaluate in 3 months to see how it goes.

```[tasklist]
- [ ] Restructure https://infrastructure.2i2c.org/contributing/code-review/#self-merging-as-a-2i2c-engineer to be a top level item
- [ ] Review last 3 months of merged PRs to understand where review added value
- [ ] Identify clear criteria for a few more kinds of PRs that can be self-merged
- [ ] Form a shared team understanding, and update the documentation to match that
```

**Comment by yuvipanda** [comment]
This initiative is attached to this goal: https://github.com/2i2c-org/meta/issues/989

**Comment by yuvipanda** [comment]
I've been adding a few recently:

- https://github.com/2i2c-org/infrastructure/pull/3981
- https://github.com/2i2c-org/infrastructure/pull/3972
- https://github.com/2i2c-org/infrastructure/pull/3966

**Comment by choldgraf** [comment]
A quick thought here on the way to approach this topic. We recently [added decision making principles](https://compass.2i2c.org/operations/governance/#make-it-safe-to-try) that have a few relevant pieces for this topic:

- Make it safe to try
- Bias towards action
- Trust one another

That makes me feel like our guidelines for teams should _start with the assumption that team members take action_, and describes the specific places where they might want to slow down, rather than assuming they're moving slowly and telling them when to speed up.[^1]

[^1]: This is also a departure from the tone of [our engineering review guidelines](https://compass.2i2c.org/engineering/reviewing/#merge-and-code-review-policy)

So what do you think about approaching the same question from the opposite direction:

- Assume that most infrastructure PRs can be self-merged without review when you think they are safe to do so.
- Here are some circumstances that might bias you towards waiting for feedback:
	- You need feedback to resolve critical questions.
	- The PR probably has wide-ranging impacts on 2i2c's active infrastructure.
	- The PR makes a change that we need others on the engineering team to know about, in order to share knowledge and skills.

And iterate on the guidelines from that approach.

**Comment by yuvipanda** [comment]
I spent the last 4 days thinking about this, and I think the way you're suggesting is actually the way to go here, @choldgraf.

**Comment by damianavila** [comment]
> I spent the last 4 days thinking about this, and I think the way you're suggesting is actually the way to go here, @choldgraf.

I concur, I think @choldgraf's suggestion is the right direction to follow.

> This is also a departure from the tone of [our engineering review guidelines](https://compass.2i2c.org/engineering/reviewing/#merge-and-code-review-policy) [↩](https://github.com/2i2c-org/infrastructure/issues/3997#user-content-fnref-1-fffc8c00d41f085d404a9a029b63c451)

Yep, we need to change the tone over there.

In general, I think this change would increase our velocity and free-up some of our capacity, and both things are benefits that outweight the costs we are gonna pay for a reduced review surface.

**Comment by consideRatio** [comment]
Thank you @yuvipanda, do you think its OK to let this issue capture the need for guidance on how to request review in situations when you will need it for makes sense to self-merge?

## Attempted summary of this topic

- We are heading towards autonomy to decide if you self-merge or not, and this requires some guidance when it makes sense to request review help
- We need clarity on how we can request review help
  (This is meant to capture what @GeorgianaElena said in the retro meeting today)
- We benefit from a agreed meaning on what draft / non-draft means

## Idea on a path forward

1. We use our best judgement with regards to what can be self-merged or not
2. We bootstrap documentation on strategies to get things merged, where for example a "direct self-merge" is one, and a "delayed self-review self-merge" is another", and a "request and wait for ... and then re-evaluate" etc are example strategies.
3. We define and iterate on guidance on what could make sense to request additional review for and how to balance between strategies to get things merged.

**Comment by aprilmj** [comment]
I think we fast-tracked this "initiative" during the team meeting last week, and that it may be done. @yuvipanda am I wrong about that?

**Comment by yuvipanda** [comment]
Yes i plan on working on this today

**Comment by sgibson91** [comment]
A thought I had: If we plan to pivot to more self-merging and have a deny list, should we remove the requirement in the GitHub UI for requiring a reviewer for merge?

**Comment by yuvipanda** [comment]
@sgibson91 done!

**Comment by yuvipanda** [comment]
I've done the 1:1 conversations I wanted to do about this, and it's now up at #4308
