### ISSUE TITLE
Discuss the Initiatives process and boards among the engineers

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#4002]
### Context

We have received feedback about the need from engineers to understand better the Initiatives process and how to interact with the Initiatives board.
After some conversation with @aprilmj, we have decide to move forward with the sharing of information with a dedicated sync meeting where April will explain the core of the Initiatives process and be open to questions and feedback from the engineers.

### Proposal

At minimum, we need to:
* [x] Discuss about the content and format of the meeting (done by @aprilmj and @damianavila)
* [x] Find a time slot to maximize engineers attendance
* [ ] Actual meeting

**Comment by yuvipanda** [comment]
I've also added all the engineers as 'assigned' as this would take up capacity from them too during the sprint.

**Comment by damianavila** [comment]
I sent an invite for next Tuesday May 14th that I think will work for everyone, hopefully.
Please accept or reject the invitation.
If we do not get enough positive confirmations, we will need another way to find a suitable spot.

**Comment by damianavila** [comment]
OK, after some [coordination bits](https://2i2c.slack.com/archives/C055A1J1DRP/p1715096009972939), we have found a suitable time slot for next Tue 14th.
Invitations were sent to every engineer's calendar, let me know if you did not receive it.

**Comment by damianavila** [comment]
The meeting was sucessfully held and there was even a follow up thread in the Initiatives slack: https://2i2c.slack.com/archives/C06G5FAAT63/p1715704278693159

Closing now.
