### ISSUE TITLE
k8s maintenance: k8s control plane upgrades on GKE clusters, and opportunistic node pool upgrades

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4006]
## Pre-work status

```shell
# distilled from running this 13:26 Swedish time may 8
# deployer config get-clusters --provider=gcp | xargs -I {} deployer use-cluster-credentials {} "kubectl version"
# deployer config get-clusters --provider=gcp | xargs -I {} deployer use-cluster-credentials {} "kubectl get pod -A | grep jupyter- | wc -l"         

1. All clusters have control planes with v1.27.12-gke.1115000.
2. Currently (13.27 UTC+2) active user server pods are:
   2i2c: 3
   2i2c-uk: 0
   awi-ciroh: 2
   catalystproject-latam: 0
   cloudbank: 8
   hhmi: 1
   leap: 6
   linked-earth: 0
   meom-ige: 0
   pangeo-hubs: 0
   qcl: 6
```

## Links

- hackmd: https://hackmd.io/xJ6O5J4BQSaoDbq2AHsp7g?edit
- about tainting user nodes: https://github.com/2i2c-org/infrastructure/pull/3447

## Pre folloupw work status

```
Currently (13.27 UTC+2) active user server pods are:
   2i2c: 14
   awi-ciroh: 1
   cloudbank: 27
   hhmi: 0
   leap: 5
   qcl: 5
```

## Upgrade to be performed

- 2i2c
  - [x] Blocked by: imagebuilding-demo resource allocation overhead fix
  - [x] Control plane updated
  - [x] New core node pool added
  - [x] Old core node pool deleted
  - [x] New user node pools added
  - [x] Old user node pools deleted
- 2i2c-uk
  - [x] Doesn't need a resource allocation fix
  - [x] Control plane updated
  - [x] New core node pool added
  - [x] Old core node pool deleted
  - [x] New user node pools added
  - [x] Old user node pools deleted
- awi-ciroh
  - [x] Doesn't need a resource allocation fix
  - [x] Control plane updated
  - [x] New core node pool added
  - [x] Old core node pool deleted
  - [x] New user node pools added
  - [x] Old user node pools deleted
- catalystproject-latam
  - [x] Doesn't need a resource allocation fix
  - [x] Control plane updated
  - [x] New core node pool added
  - [x] Old core node pool deleted
  - [x] New user node pools added
  - [x] Old user node pools deleted
- cloudbank
  - [x] Doesn't need a resource allocation fix
  - [x] Control plane updated
  - [x] New core node pool added
  - [x] Old core node pool deleted
  - [x] New user node pools added
  - [x] Old user node pools deleted
- hhmi
  - [x] Blocked by: resource allocation overhead fix
  - [x] Control plane updated
  - [x] New core node pool added
  - [x] Old core node pool deleted
  - [x] New user node pools added
  - [x] Old user node pools deleted
- leap
  - [x] Doesn't need a resource allocation fix
  - [x] Control plane updated
  - [x] New core node pool added
  - [x] Old core node pool deleted
  - [x] New user node pools added
  - [x] Old user node pools deleted
- linked-earth
  - [x] Doesn't need a resource allocation fix
  - [x] Control plane updated
  - [x] New core node pool added
  - [x] Old core node pool deleted
  - [x] New user node pools added
  - [x] Old user node pools deleted
- meom-ige
  - [x] Doesn't need a resource allocation fix
  - [x] Control plane updated
  - [x] New core node pool added
  - [x] Old core node pool deleted
  - [x] New user node pools added
  - [x] Old user node pools deleted
- pangeo-hubs
  - [x] Doesn't need a resource allocation fix
  - [x] Control plane updated
  - [x] New core node pool added
  - [x] Old core node pool deleted
  - [x] New user node pools added
  - [x] Old user node pools deleted
- qcl
  - [x] Doesn't need a resource allocation fix
  - [x] Control plane updated
  - [x] New core node pool added
  - [x] Old core node pool deleted
  - [x] New user node pools added
  - [ ] Old user node pools deleted

## Related PRs

- #4042
- #4044
- #4051
- #4053
- #4048
- #4059
- #4062
- #4069
- #4070
- #4071

**Comment by haroldcampbell** [comment]
This card is a pairing task with @consideRatio and either @sgibson91 or @GeorgianaElena.

**Comment by yuvipanda** [comment]
@consideRatio did you find someone to pair with on this one?

**Comment by consideRatio** [comment]
I checked with @sgibson91 - and we may do a work session today or next weeks!

**Comment by consideRatio** [comment]
We've got ~5 GKE clusters upgraded (need to delete a user node pool being phased out also), but have stopped trying to upgrade other clusters because we need to tune cpu/memory requests so that user servers will fit to schedule even if k8s/daemonsets in GKE 1.29 eat up a bit more of the nodes' remaining allocatable cpu/memory.

**Comment by consideRatio** [comment]
I've gone through each cluster/hub and checked for needed updates of resource allocations and only 2i2c and hhmi are blocked by that.

I've proceeded with upgrades for the other clusters - but now the introduction of resource allocation choices without tuning them to provide additional overhead isn't going to work well.
