### ISSUE TITLE
k8s maintenance: k8s node pool upgrades on EKS clusters

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4009]
#4007 upgraded all control planes to 1.29, but we need to bring the node pools to 1.29 as well. Documentation on how to do this was updated in #4099 and is made available at https://infrastructure.2i2c.org/howto/upgrade-cluster/aws/ - where step 4 about upgrading the control plane is already done.

### Clusters with node groups to upgrade

- [x] 2i2c-aws-us
- [x] catalystproject-africa
- [x] earthscope
- [x] gridsst
- [x] jupyter-meets-the-earth
- [ ] nasa-cryo
   - Waiting for old user server node group to drain so it can then be deleted
- [x] nasa-esdis
- [ ] nasa-ghg
  - ~~Can't be upgraded due to missing public ssh key, tracked in #4122~~
  - Waiting for old user server node group to drain so it can then be deleted
- [x] nasa-veda
- [x] openscapes
- [x] opensci
- [x] smithsonian
- [x] ubc-eoas
- [x] victor

**Comment by yuvipanda** [comment]
Should be paired with someone else (TBD)

**Comment by consideRatio** [comment]
@sgibson91 agreed to do this work this during this sprint. I'm around to discuss anything if requested.

**Comment by sgibson91** [comment]
Most clusters are done, there are only the remaining clusters which have some user servers still up

| Cluster | Number of running singleuser servers |
| :--- | :--- |
| nasa-cryo | 2 |
| nasa-ghg | 3 |

**Comment by sgibson91** [comment]
2 of the nasa-cryo user servers have been up for >2days and 1 of the nasa-ghg user serves has been up for 36 hours. I suspect these might be abandoned so maybe they're fine to kick off?

**Comment by consideRatio** [comment]
> 2 of the nasa-cryo user servers have been up for >2days and 1 of the nasa-ghg user serves has been up for 36 hours. I suspect these might be abandoned so maybe they're fine to kick off?

You could do a [rolling upgrade without using drain](https://infrastructure.2i2c.org/howto/upgrade-cluster/aws/#performing-rolling-upgrades-using-drain-or-not) on the node pool they are using, and in the "taint and wait step" you push the changes up to that point and get a PR merged - leaving only a comment saying we need to also delete a node pool, something that hopefully can be done next week at least.

**Comment by sgibson91** [comment]
I've done that for nasa-cryo. I was about to do it for nasa-ghg, but the public ssh key isn't in the repo and so eksctl commands failed 😕

**Comment by sgibson91** [comment]
Is there a way to reverse this command?

```
kubectl taint node manual-phaseout:NoSchedule -l alpha.eksctl.io/nodegroup-name=nb-r5-4xlarge
```

**Comment by consideRatio** [comment]
@sgibson91 ah hmmm okay!

Hmmmm, deleting a taint can be done by `kubectl edit node <node name>`, maybe there is a one-liner kubectl also but I've not found out yet though.

**Comment by sgibson91** [comment]
Thanks Erik. I used that command to remove the taint, and have opened https://github.com/2i2c-org/infrastructure/issues/4122

**Comment by sgibson91** [comment]
Upgrading the core node group for nasa-ghg was also going to remove node group "nb-c5-4xlarge", which I believe comes from https://github.com/2i2c-org/infrastructure/pull/4100, so I used `--exclude="nb-c5-4xlarge"` to leave this alone

**Comment by sgibson91** [comment]
I've put in a reminder for myself on Tuesday to check if the old node groups have drained (Monday is a holiday in the UK and I'll be coming back from a weekend away)

**Comment by sgibson91** [comment]
> Hmmmm, deleting a taint can be done by `kubectl edit node <node name>`, maybe there is a one-liner kubectl also but I've not found out yet though.

@consideRatio I learned a one-liner! Example, to remove the `node-role.kubernetes.io/control-plane` taint from all nodes (I don't know _why_ you'd want to do this, but it's the example that came up in my course).

```
kubectl taint nodes --all node-role.kubernetes.io/control-plane-
```

The key is the extra `-` at the end which is the syntax for removing a taint

**Comment by consideRatio** [comment]
Thank you for sharing this @sgibson91!!
