### ISSUE TITLE
403: Forbidden trying to log into Pangeo JupyterHub for all users

### ISSUE THREAD

**Issue by scottyhq** [2i2c-org/infrastructure#4043]
### Context

First reported by @cspencerjones here
https://discourse.pangeo.io/t/cant-log-in-to-pangeo-google-cloud-hub/4208

https://github.com/2i2c-org/infrastructure/blob/2a475a35e03104e70910d9fbc1907211d1d5a4a0/config/clusters/pangeo-hubs/common.values.yaml#L40

I am listed as an administrator on this hub and also see the same error message, so something must have changed recently causing authentication issues

<img width="1059" alt="Screenshot 2024-05-08 at 9 45 00 AM" src="https://github.com/2i2c-org/infrastructure/assets/3924836/160e6426-595f-4e42-a39b-7e86a2ba96ef">

**Comment by sgibson91** [comment]
Hi @scottyhq - Thanks for the issue, but problems like this should go via our support process https://docs.2i2c.org/support/

**Comment by sgibson91** [comment]
https://2i2c.freshdesk.com/a/tickets/1571

**Comment by consideRatio** [comment]
```
User scottyhq does not have any auth_state set, profile_list filtering not available
User scottyhq is part of groups 
[W 2024-05-08 16:54:56.672 JupyterHub web:1873] 403 GET /hub/spawn (10.128.0.52): 
    Your JupyterHub group membership is insufficient to launch any server profiles.
    
    JupyterHub groups you are a member of are .
    
    If you are part of additional groups, log out of this JupyterHub and log back in to refresh that information.
```

**Comment by sgibson91** [comment]
@consideRatio Yeah, that's the same error I got when I tried to login too. I'm reverting the groups PR to see if that fixed.

**Comment by consideRatio** [comment]
@scottyhq pangeo-hubs staging and prod should function again, but users that saw the 403 needs to logout and then login again.

**Comment by scottyhq** [comment]
Wonderful! Thank you both for such a quick fix. Confirmed all is working again.
