### ISSUE TITLE
monero cryptnono detector does not start on GKE 1.29

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4052]
Tracked in https://github.com/cryptnono/cryptnono/issues/34

**Comment by yuvipanda** [comment]
With #4056, I've disabled the bpftrace based monero detector and enabled the much more comprehensive execwhacker. execwhacker also is far more effective against cryptominers than the monero detector was.

I've also verified that there are no non-running pods with `deployer config get-clusters | xargs -I{} -L1 deployer use-cluster-credentials {} 'kubectl get pod -A | grep -v Running'`

This issue can be closed now.
