### ISSUE TITLE
Incident Report - First spin up of nodes for jupyterhub takes a few minutes

### ISSUE THREAD

**Issue by sean-morris** [2i2c-org/infrastructure#406]
# Summary

Just before the demo started for Palomar, I logged into the demo and palomar hubs. A message appeared telling me there was insuffient memory and appeared to be hanging. This eventually resolved itself; the system was automatically spinning up after being spun down  overnight, I imagine. Yuvi also stepped in to spin up a few more nodes in order to avoid a slow down during the demo.

## What went wrong

Nothing actually went wrong -- it was just a little scary!  It took about five minutes to resolve itself and come up. 

## Where we got lucky

We happened to be doing introductions and all was good when we moved towards the actual demo!

## Action items

I am not sure there are actions items here but we (Yuvi and me) thought we should post the incident. 

### Process improvements

1. The person running and / or supporting the demo should login with a sufficient amount of time before the demo to make sure the nodes are up for the demo.
2. Develop a sense of how many nodes may be needed to run a demo based on the number of people involved

### Documentation improvements

1. Document how to spin nodes before they are needed

### Technical improvements

None

**Comment by damianavila** [comment]
@yuvipanda, how are you handling the pre-warm of the nodes to be ready for the events?
Are you adjusting placeholder pods? Maybe something else to trigger the autoscaling process?

**Comment by yuvipanda** [comment]
For today since there wasn't time I just went in and manually scaled them up by setting minimum node count to 3. I'll go back and put it down to 0 again. 

How to do pre-warm is something we should figure out. I've been experimenting with node placeholders (https://github.com/berkeley-dsep-infra/datahub/tree/staging/node-placeholder) instead of user-placeholders, and it's multiple orders of magnitude more effective

**Comment by damianavila** [comment]
> For today since there wasn't time I just went in and manually scaled them up by setting minimum node count to 3. I'll go back and put it down to 0 again.

Gotcha!

> I've been experimenting with node placeholders (https://github.com/berkeley-dsep-infra/datahub/tree/staging/node-placeholder) instead of user-placeholders, and it's multiple orders of magnitude more effective

That URL is 404 for me, but I am really tempted by the concept of node placeholders...

**Comment by yuvipanda** [comment]
@damianavila the link should work now! https://github.com/berkeley-dsep-infra/datahub/pull/2337 has a lot more context.

Some chat context in https://matrix.to/#/!IrRJzNeYwTiocwdjaf:gitter.im/$9qTc8pUpZiQn3wP1-19n-0ENKJ8YtZmJZx0K_q8L5WM?via=gitter.im&via=matrix.org&via=matrix.nrp-nautilus.io. Has been far more reliable than pod placeholders.

**Comment by damianavila** [comment]
Thanks for the context! I briefly looked at the first link and it sounds great!

> Has been far more reliable than pod placeholders.

Glad to see it was been working reliably.

**Comment by choldgraf** [comment]
We've added a lot of extra documentation about pre-warming clusters for workshops etc, so I think we can close this one
