### ISSUE TITLE
[New Hub] LEAP public

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4088]
Ref https://2i2c.freshdesk.com/a/tickets/1551

## Phase 2: Cluster

This should be on the existing LEAP cluster

## Phase 3 : Hub setup

There's going to be one hub.

#### Phase 3.1: Initial setup (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Name of the hub | leap-public | |
| Dask gateway? | no | |
| Splash image |   https://leap-stc.github.io/_static/LEAP_logo.png |  |
| URL |  https://leap-stc.github.io |  | 
| Authentication Mechanism | GitHubOAuthenticator | |
| Admin Users | Same as existing LEAP hub | | 
| URL of the hub | public.leap.2i2c.cloud |
| Persistent Home Directory | no | 

#### Phase 3.2: Object storage access (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Scratch bucket enabled? |  no |  |
| Persistent bucket enabled? | no |  |
| Requestor pays requests to external buckets allowed? | no | |  

##### Environments

Adapted from existing LEAP profiles

| Display Name | Description | Overrides | 
| - | - | - |
| Pangeo Notebook | Python with Geoscience Packages | `image: pangeo/pangeo-notebook:2024.05.21` |  
| Pangeo Tensorflow ML Notebook | Python with Geoscience Packages and Tensorflow (no GPU) | `image: pangeo/ml-notebook:2024.05.21` |  
| Pangeo PyTorch ML Notebook | Python with Geoscience Packages and PyTorch (no GPU) | `image: pangeo/pytorch-notebook:2024.05.21` |  

##### Resource Allocation

Generate with `deployer generate resource-allocation choices --num-allocations 4 n2-highmem-4`.

#### Phase 3.4: Authentication finetuning

| Question | Answer |
| - | - |
| Authentication Mechanism | GitHubOAuthenticator |
| Allowed Teams | https://github.com/orgs/leap-stc/teams/leap-pangeo-public-access |

#### Additional customizations

This needs a new nodepool. Let's call it `public-n2-highmem-4`, and make it `n2-highmem-4` instances. This should be set explicitly in `singleuser.nodeSelector` to make sure all users end up on these nodes.

**Comment by yuvipanda** [comment]
@AIDEA775 I've spent a little more time refining this further, let me know if it looks complete to you now

**Comment by consideRatio** [comment]
Great work on this @AIDEA775! This seems to have been completed - ready to close?

**Comment by AIDEA775** [comment]
We haven't received a response in Freshdesk, so I will close this because the deploy is done. I will request that if any other changes are needed, a new ticket should be generated.
