### ISSUE TITLE
[Support] Revise profile options for unam.latam.catalystproject.2i2c.cloud

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#4089]
Re: https://2i2c.freshdesk.com/a/tickets/1588

We need add some additional resource allocations related for unam.latam.catalystproject.2i2c.cloud to support high memory (120G, 500G) science work.

The user-nodepool already has n2-highmem-16 and n2-highmem-64 machine types configured.  Please add these two machines as additional options under `resource_allocation` for catalystproject-latam/unam

This request is only for UNAM and not all Catalyst Project hubs. 

(If there is not engineering capacity for this request in this next sprint, @jmunroe is able to complete the task)

**Comment by haroldcampbell** [comment]
@jmunroe this needs a bit more refinement for this card.
