### ISSUE TITLE
[Request deployment] New Hub: UW ISEA

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#4090]
This hub will serve the ISEA Hackweek hosted by the University of Washington during July 2024. 
https://www.amplifylearn.ai/isea/

### Hub important dates

- **Target Start Data:** 2024-06-22
- **Required Start Date:** 2024-07-01
- **Shutdown Date:** 2024-07-31

## Phase 2: Cluster

Deploy on 2i2c-aws-us

#### Phase 3.1: Initial setup (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Name of the hub | isea | |
| Dask gateway | no | |
| Splash image | AmplifyLearn.AI logo | see comment below   |
| URL | https://www.amplifylearn.ai/isea/ | |
| funded_by | [Institute of Education Sciences](https://ies.ed.gov/) (IES)  |  | 
| Authentication Mechanism | GitHub (via GitHubOAuthenticator) |
| Admin Users | @lovenoor  | 

At the end of this phase, both 2i2c engineers and the admin users mentioned can login to the hub.

#### Phase 3.2: Object storage access  (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Scratch bucket enabled? |  no |  |
| Persistent bucket enabled? | no |  |
| Requestor pays requests to external buckets allowed? | no | |  

#### Phase 3.3: Profile List (**READY**)

These are the standard profile list options we want to start with. Can be customized later

| Question | Answer | Notes |
| - | - | - |
| profileList used? | no | | 
| Image? |  jupyter/scipy-notebook | Use latest available date tag for [jupyter/scipy-notebook](https://quay.io/repository/jupyter/scipy-notebook?tab=tags)
| RStudio (with Rocker)? |  no  |  |
| Allow users to specify any image they want to use? | no | Enable `unlisted_choice`| 
| Max RAM option allowed |   guarantee: 384M   limit: 1.5G  |  (this is the same as the cloudbank hubs) |
| GPU enabled? | no | |
| Default Interface | JupyterLab | |
| Allow multiple concurrent servers per user? | no | Translates to `allowNamedServers` |
 

#### Phase 3.4: Authentication tuning (**READY**)

| Question | Answer |
| - | - |
| Authentication Mechanism | GitHub (via GitHubOAuthenticator) |
| Org based access? | no |
| List of GitHub orgs / teams to be granted access |   |
| Initial hub admin user | @lovenoor |
| Note: | Other users can be added through the JupyterHub interface  (expected ~30 users total) |

#### Phase 3.5: Profile List finetuning

| Question | Answer | Notes |
| - | - | - |
| Custom image to be specified?  | N/A  |

**Comment by colliand** [comment]
FYI @lovenoor. This issue will track 2i2c's deployment of the ISEA hub.

**Comment by colliand** [comment]
The anchor comment in this issue will be refactored by @jmunroe to follow 2i2c's recent improvements on the hub turn up process.

**Comment by jmunroe** [comment]
Hi @lovenoor .  Is this a suitable logo to use a 'Splash Image' for this hub? If not, please let us what you would prefer.

![llogo](https://github.com/2i2c-org/infrastructure/assets/6181563/df7f288d-0ca3-4bbb-9fef-2a98892ac0f6)

I'll recommend that you go with a [jupyter/scipy-notebook](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-scipy-notebook) image which has a number of useful Python packages for data science (including pandas, numpy, seaborn, sklearn, statsmodels, and random) that it looks like you have introduced in the slides.

If your hackweek projects end up wanting to investigate frameworks like pytorch or tensorflow, it is very easy to also deploy a different prebuilt image. See https://jupyter-docker-stacks.readthedocs.io for additional information.

The RAM per user is set to max out at just 1.5G but we can increase this if you anticipate more memory per user.
Your participants can either be dropped into a single predefined image that you control or you could give them a list of different image choices (and amounts of available memory).  This tradeoff is more of a pedagogical choice for you: what do you want to make available for your participants.  It also can be changed after the hub is deployed.

**Comment by lovenoor** [comment]
Hi James,

Yes, the splash image is suitable.

For now, the jupyter image seems sufficient. Will let you know if we need
to change things up.

Lavi

*Lovenoor (Lavi) Aulck*
*Data Scientist - Finance, Planning & Budgeting*
*Managing Director - Innovation Science for Education Analytics*
*University of Washington*

**Comment by AIDEA775** [comment]
Hi @lovenoor, the hub was deployed here: https://isea.aws.2i2c.cloud/. Can you log in?

**Comment by lovenoor** [comment]
Hi Alejandro,

It looks like I'm able to log in.

Lavi

*Lovenoor (Lavi) Aulck*
*Data Scientist - Finance, Planning & Budgeting*
*Managing Director - Innovation Science for Education Analytics*
*University of Washington*
