### ISSUE TITLE
Run a knowledge sharing session about binderhub technical architecture

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4113]
During https://github.com/2i2c-org/infrastructure/issues/4086, @GeorgianaElena spoke about how the knowledge of binderhub's technical architecture is not evenly distributed in the team. Given we're getting more and more into running binderhub reliably for many of our users, this needs to be better distributed so everyone can feel comfortable working on this.

This task tracks a possible synchronous session walking through the various parts of binderhub and how they interact with each other, followed by a quick Q&A session. The goal is for the team members who would like to participate to gain more familiarity with binderhub and feel a little more comfortable working on it.

**Comment by haroldcampbell** [comment]
@yuvipanda is it possible to schedule this earlier for this week?

**Comment by yuvipanda** [comment]
Given other priorities, I've now actually scheduled two 1:1 calls (with @sgibson91 and @GeorgianaElena). This should primarily unblock @sgibson91 to pick up https://github.com/2i2c-org/infrastructure/issues/4246 and https://github.com/2i2c-org/infrastructure/issues/4247.

**Comment by haroldcampbell** [comment]
Hey @yuvipanda should we push this back to committed so that @sgibson91 can work on https://github.com/2i2c-org/infrastructure/issues/4238? Looking for guidance here.

**Comment by yuvipanda** [comment]
Me and @sgibson91 had a 1hr session on this, that @GeorgianaElena also attended. https://drive.google.com/file/d/1MJR6AQGt5aqat4pD1QHfZWP24vSErqww/view?usp=sharing is the video for this.

**Comment by sgibson91** [comment]
Is there anyone else who needs the training, or can we consider this closed?

**Comment by yuvipanda** [comment]
I'm going to call this done for now. I can catch up with @GeorgianaElena more as needed.
