### ISSUE TITLE
Build a system for systematically doing recurring maintenance tasks consistently

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4114]
We have many recurring maintenance tasks that we need to do to ensure smooth running of all the infrastructure we maintain. Ideally, these get done *consistently*, so they are low stress and can morph into the background. However, because we don't have a reliable and trustworthy process to make sure this gets done, instead usually these just stay *not done* until they *almost* become problems, and then they get done in a more high stress manner.

The goal of this process improvement is to incrementally build a system that will consistently make sure that recurring maintenance tasks are intentionally scheduled into our sprints as appropriate. We'll have to build trust in such a system, both in terms of it providing tasks for us to pick up, as well as scheduling and getting those tasks completed. It should also make sure that there are no single bottlenecks for the various tasks.

```[tasklist]
- [ ] Make a list of recurring maintenance tasks and their recurrance schedules
- [ ] Design a process for handling recurring SMCE credential regeneration
- [ ] Design a process for handling Kubernetes upgrades
- [ ] Design a process for handling support chart version upgrades
```

**Comment by yuvipanda** [comment]
https://calendar.google.com/calendar/embed?src=c_62d7c67afde2b63bf53536f7923fcc59e7c1a6d8361f24385bd5c792e68f121b%40group.calendar.google.com&ctz=America%2FLos_Angeles is the public calendar, and I'm currently the owner for it. It has entries for SMCE regeneration now (every 7 weeks), and for support chart upgrades (every 2 months, up from current every 1 month). I've an upcoming meeting with Erik to discuss how to schedule k8s nodes.

**Comment by yuvipanda** [comment]
I've added the following sentence to the sprint refinement meeting that happens every other week:

> Look at the recurring engineering tasks calendar (https://calendar.google.com/calendar/embed?src=c_62d7c67afde2b63bf53536f7923fcc59e7c1a6d8361f24385bd5c792e68f121b%40group.calendar.google.com&ctz=America%2FLos_Angeles) and make sure tasks coming up in next two sprints are accounted for

I'm also going to turn this task away from an EPIC into something smaller, as I don't think we need to try get this to be 'perfect'. Just good enough will do.

**Comment by yuvipanda** [comment]
Documentation on how to regenerate these credentials is at https://github.com/2i2c-org/infrastructure/issues/2434

**Comment by haroldcampbell** [comment]
@yuvipanda is this something that should be assigned to you? Is this something that we missed in the last planning meeting?

**Comment by consideRatio** [comment]
https://github.com/2i2c-org/infrastructure/issues/3958 will result in something that requires recurrent scheduling of work, practically such as work tracked by the EPIC https://github.com/2i2c-org/infrastructure/issues/4184 for Q2

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/issues/4289 is the follow-up, am going to close this.

**Comment by yuvipanda** [comment]
@haroldcampbell yes unfortunately we did miss it.
