### ISSUE TITLE
Help deploy and test hubs decision logic ignore some files

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4116]
Some changes to `deployer/*` shouldn't trigger a re-deploy of everything as it currently does via [`discover_modified_common_files`](https://github.com/2i2c-org/infrastructure/blob/e8f25c80457aaaab6134d578217d0c2b4145b44f/deployer/commands/generate/helm_upgrade/decision.py#L18-L62)

The issue is that this code currently only checks for matching patterns, and not also considering a few exclusion patterns:

https://github.com/2i2c-org/infrastructure/blob/e8f25c80457aaaab6134d578217d0c2b4145b44f/deployer/commands/generate/helm_upgrade/decision.py#L55-L58

Ideally we'd support something like we have in here:

https://github.com/2i2c-org/infrastructure/blob/e8f25c80457aaaab6134d578217d0c2b4145b44f/.github/workflows/deploy-hubs.yaml#L14-L28

**Comment by sgibson91** [comment]
Can't we just put the deployer in it's own repo? I feel like that would solve 99% of the cases when an unwanted full redeploy is triggered.
