### ISSUE TITLE
nasa-ghg cluster missing public ssh key from the repo

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4122]
### Context

While working on #4009, I realised that the public key for the nasa-ghg cluster is missing from the repo, which means we cannot run eksctl commands against it. The private key is still in the repo.

How can we regenerate ssh keys and update clusters?

**Comment by sgibson91** [comment]
I used the following command to see if I could find when it had been deleted, but it didn't turn up anything, which implies that it never got added in the first place?

```
git log --full-history -- eksctl/nasa-ghg.key.pub
```

**Comment by consideRatio** [comment]
This cluster likely hasn't been upgraded before, so its reasonable!

**Comment by consideRatio** [comment]
@sgibson91 I was too curious about this and tried to re-generate a non-missing public key from a private key and see if it became the same, and it became the same - so the information in private keys all thats needed to add it back by re-generating it.

```bash
sops -d encrypted-private-key > secret.tmp.key
chmod 0600 secret.tmp.key
ssh-keygen -f secret.tmp.key -y > public-key-file
rm secret.tmp.key
```

Above is based on this post combined with some sops decryption stuff:
https://www.baeldung.com/linux/public-key-from-private-key

**Comment by sgibson91** [comment]
Thanks! This is working now!
