### ISSUE TITLE
[New Hub] binderhub-ui-demo.2i2c.cloud

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4133]
A part of https://github.com/2i2c-org/infrastructure/issues/4109.

## Phase 2: Cluster

This should be on the 2i2c cluster on GCP

#### Phase 3.1: Initial setup (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Name of the hub | binderhub-ui-demo | |
| Dask gateway? | no | |
| BinderHub UI? | yes | | 
| Authentication Mechanism | CILogon | |
| Admin Users | NA | Because BinderHub UI will be used | 
| Persistent Home Directory | no | Because BinderHub UI will be used |

#### Phase 3.2: Object storage access (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Scratch bucket enabled? |  no |  |
| Persistent bucket enabled? | no |  |
| Requestor pays requests to external buckets allowed? | no | |  

#### Phase 3.3: Profile List (**READY**)

N/A, as BinderHub UI will be used

#### Phase 3.31: Resource configuration (**READY**)

No profile list, properties set under `singleuser`

| Question | Answer |
| - | -|
| memory limit | 1G |
| memory request | 256M |
| CPU limit | 0.25 |
 
#### Phase 3.4: Authentication tuning (**READY**)

| Question | Answer |
| - | - |
| Authentication Mechanism | CILogonOAuthenticator |
| IDP restrictions? | No |

#### Phase 3.5: Profile List finetuning (**NA**)

NA, as BinderHub UI will be used

#### Phase 3.6: BinderHub config

| Question | Answer |
| - | - |
| Allowed Repositories? | All |
| Banner Message | Testing binderhub used 2i2c | 
| BinderHub About Message | Testing binderhub used by 2i2c |

## Process note

This is the first hub of this sort we have deployed! So we don't actually know all the questions that need to be answered to 'fully specifiy' it, from an engineering perspective. So if you are working on this, and feel you need to make a choice that isn't explicitly already made here, **please raise it for visibility**! You don't have to make the choice yourself - we can do that as a team. And raising this will also help make sure we can fully specify these kinds of hubs in the future.

I'd suggest three ways to raise issues you encounter here:

1. Post in the `#engineering` channel
2. Post in this issue
3. DM me (@yuvipanda), and we can find synchronous time (over chat or video) to make those choices and report back as needed.

## Follow up issues

In priority order

- [ ] https://github.com/2i2c-org/infrastructure/issues/4167
- [ ] https://github.com/2i2c-org/infrastructure/issues/4168
- [ ] https://github.com/2i2c-org/infrastructure/issues/4169

**Comment by consideRatio** [comment]
| Question | Answer |
| - | - |
| Allowed Repositories? | All |
| Banner Message | Testing binderhub used 2i2c | 
| BinderHub About Message | Testing binderhub used by 2i2c |

These haven't been setup yet as part of #4086, and there is some finetuning work remaining - for example handling a FIXME note and thinking about UI aspects exposed and making decisions about domain names clear (we've now made example.local for the binderhub and hub.example.local for the hub, and avoided going for a path to expose both with a single domain with subpaths such as /services/binder etc).

**Comment by consideRatio** [comment]
Failing health check is one issue to think about as well: https://github.com/2i2c-org/infrastructure/actions/runs/9307796142/job/25620397449

**Comment by yuvipanda** [comment]
@consideRatio I've opened separate issues to tackle two of the things you reported here, and prioritized them accordingly in the initiatives task (and the board). 

As for using two domains instead of 1, I think that's the way to go. Let's decide to stick with that, and codify that as needed in our runbook documentation. Don't think we need extensive discussion there. I don't see an issue for 'document how to spin up an ephemeral hub', so I created https://github.com/2i2c-org/infrastructure/issues/4169 (with a note on documenting such choices).

I think once the FIXMEs are handled, the about text is setup and follow up issues created (and prioritized appropriately), we can then close this issue.

**Comment by yuvipanda** [comment]
Messages handled in https://github.com/2i2c-org/infrastructure/pull/4196.

Opened https://github.com/2i2c-org/binderhub-service/issues/113 to figure out the leftover FIXME.

A decision has been made about home pages in https://github.com/2i2c-org/infrastructure/issues/4169. I've recorded these choices in https://github.com/2i2c-org/infrastructure/issues/4169, which will be used to make the runbook.

**Comment by yuvipanda** [comment]
Alright, I think we can close this one out! I've made sure the tasklist in https://github.com/2i2c-org/infrastructure/issues/4109 is up to date (and prioritized) as well.

Great job, @GeorgianaElena and @consideRatio!
