### ISSUE TITLE
[New Hub] binder.pythia.2i2c.cloud

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4134]
A part of https://github.com/2i2c-org/infrastructure/issues/4109.

## Phase 2: Cluster

This should be on the Project Pythia cluster on **AWS**.

#### Phase 3.1: Initial setup (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Name of the hub | pythia-binder | |
| Dask gateway? | no | |
| URL | binder.pythia.2i2c.cloud | | 
| BinderHub UI? | yes | | 
| Authentication Mechanism | None | |
| Admin Users | NA | Because BinderHub UI will be used | 
| Persistent Home Directory | no ||

#### Phase 3.2: Object storage access (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Scratch bucket enabled? |  no |  |
| Persistent bucket enabled? | no |  |
| Requestor pays requests to external buckets allowed? | no | |  

#### Phase 3.3: Profile List (**READY**)

N/A, as BinderHub UI will be used

#### Phase 3.31: Resource configuration (**READY**)

No profile list, properties set under `singleuser`

| Question | Answer |
| - | -|
| memory limit | 1G |
| memory request | 256M |
| CPU limit | 0.25 |
 
#### Phase 3.4: Authentication tuning (**READY**)

| Question | Answer |
| - | - |
| Authentication Mechanism | None |

#### Phase 3.5: Profile List finetuning (**NA**)

NA, as BinderHub UI will be used

#### Phase 3.6: BinderHub config (**NOT READY**)

| Question | Answer |
| - | - |
| Allowed Repositories? | `^ProjectPythia/.*$` |
| Banner Message | "" | 
| BinderHub About Message | Binder for use with Project Pythia |

## Note

This differs from #4133 in two ways, described in https://github.com/2i2c-org/infrastructure/issues/4134#issuecomment-2164360396

**Comment by yuvipanda** [comment]
@ktyle you may be interested in this issue :)

**Comment by jmunroe** [comment]
I think the resources on this binder.projectpythia.2i2c.cloud hub should be the same as those in https://github.com/2i2c-org/infrastructure/issues/4005 (including GPU)

Also, for Project Pythia, access to this binder should be restricted. The main use case would be integration with a CI/CD pipeline using GitHub actions.

**Comment by yuvipanda** [comment]
Me and @jmunroe will further refine this in a while. #4133 is higher priority to get done first. I've also learnt more about the structuring of project pythia as well, which helps!

**Comment by yuvipanda** [comment]
I spoke to @jmunroe again today to refine this, and it's complete. No GPUs needed right now. And this is almost equivalent to a mybinder.org style experience, so **no login**.

Differences from #4133 would include:

1. No login, so no logged out homepage.
2. An allowed list of repos that can be launched. This requires that `binderhub-service` bring in the latest version of the binderhub package, as this functionality was only merged a few days ago (in https://github.com/jupyterhub/binderhub/pull/1105).
