### ISSUE TITLE
[Support] catalystproject-latam, plnc: transition to community provided domain name

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4163]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/1591

### Ticket request type

Feature Request

### Ticket impact

🟩 Low

### Short ticket description

The new domain name to use is `hub.pln.villena.cl`, and we transition away from `plnc.latam.catalystproject.2i2c.cloud.` which should instead redirect to the new.

Related docs: https://infrastructure.2i2c.org/sre-guide/support/community-domains/#preparing-the-configuration-change

**Comment by yuvipanda** [comment]
I'm doing this myself because this has been in support for more than 2 weeks, but this is a pattern we should work very hard to avoid.

**Comment by jmunroe** [comment]
I see no issues in using this domain even though it is personally managed. Please make the necessary changes.
