### ISSUE TITLE
[Support] Answer questsions from Kitware

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4172]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/1596

### Ticket request type

Technical questions

### Ticket impact

🟩 Low

### Short ticket description

https://2i2c.freshdesk.com/a/tickets/1596 has some questions that I had answered, but some that were not. We should answer them.

**Comment by yuvipanda** [comment]
I'm just going to answer them this time, because I don't want to bounce them to a community location after making them wait so long. But I've made that clear too.

**Comment by haroldcampbell** [comment]
To be closed by end of week if no response (June 21)

**Comment by yuvipanda** [comment]
I shepherded this through to a close

> Yes, that helps a lot! [...] I appreciate all your help and quick responses. I hope you have a great weekend!

from them!
