### ISSUE TITLE
Temporary pause of Openscapes 2i2c Hub until Cloud Credits renewed

### ISSUE THREAD

**Issue by jules32** [2i2c-org/infrastructure#4180]
### Context

Hi 2i2c Team, 

For your awareness, I've pressed the "Shutdown Hub" button for our Hub and will work with you to continue once our Cloud Credits are renewed. Thank you very much, Julie

I shared [this message on NASA-Openscapes GitHub Discussions](https://github.com/NASA-Openscapes/2i2cAccessPolicies/discussions/11) 

> Hi everyone, unfortunately, we need to temporarily pause the 2i2c Hub until we get more cloud credits. We anticipate this pause will be very brief and will be resolved by tomorrow; we submitted a request to AWS/NASA for more credits on April 26 and they are aware that we have just ~$400 left and pausing until we have more credits. I am really sorry that this will disrupt your work in the meantime, and we’ll have it back as soon as possible. We’ll learn from the evolving credits process going forward to make sure we don’t have these kinds of disruptions.

<img width="1104" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/5891909/cc5772a7-6492-4696-8881-6dade3a013f9">

**Comment by jules32** [comment]
We have updated progress, documented here: https://github.com/NASA-Openscapes/2i2cAccessPolicies/discussions/11

**Comment by yuvipanda** [comment]
This has been handled
