### ISSUE TITLE
Taint our eksctl generated GPU node pools correctly

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#4209]
### Context

Currently, the binder builder pods [get scheduled on user nodes](https://github.com/2i2c-org/infrastructure/blob/949549de6b9f0665608b2ab5cf30b07452814f8d/helm-charts/basehub/values.yaml#L47-L49).

I there there are a couple of issues with this:

### 1. The GPU nodes created are also labeled as user nodes, so the builder pods can run on them also.
   On GCP, we seem to be [adding an additional taint to the GPU nodes](https://github.com/2i2c-org/infrastructure/blob/949549de6b9f0665608b2ab5cf30b07452814f8d/terraform/gcp/cluster.tf#L322-L327), but we don't do the same in AWS. I don't think this is ideal.

### 2. I think the autoscaler should spin off the smallest type of node that satisfies a resource request
- is this true @2i2c-org/engineering?
   - relevant docs that I found:
      - gcp https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler#operating_criteria
      - 
- But @jmunroe has experienced the following weird situation on aws: 
   ```
    1. Cluster has only one core node running (no user nodes)
    2. James wants to build an image on that hub and triggers the creation of a builder pod
    3. That builder pod triggers the spin off of a GPU node???
   ```
    Why did the autoscaler chose to create the biggest type of machine in the user node pool?

### Proposal

I think we should make sure we taint GPU nodes appropriately so that only allow user servers that explicitly request GPUs get scheduled on those.

**Comment by yuvipanda** [comment]
> I think we should make sure we taint GPU nodes appropriately so that only allow user servers that explicitly request GPUs get scheduled on those.

I thought we already did that. We should do a timeboxed investigation to see if taints aren't being applied. And if they aren't, add them.

This may be affecting other clusters as well, increasing their cloud cost.

I'll add this to the backlog and prioritize it appropriately.

Also I absolutely commend the format and amount of information in this issue, @GeorgianaElena. It's *exactly right*!

**Comment by GeorgianaElena** [comment]
> I thought we already did that. We should do a timeboxed investigation to see if taints aren't being applied. And if they aren't, add them.

I checked the taints of a gpu node on the projectpithia cluster this morning and it didn't had any gpu specific taints:

```bash
Name:               ip-192-168-48-89.us-west-2.compute.internal
Roles:              <none>
Labels:             alpha.eksctl.io/cluster-name=projectpythia
                    alpha.eksctl.io/instance-id=i-0f35cdb24d2dcf32d
                    alpha.eksctl.io/nodegroup-name=nb-g4dn-xlarge
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=g4dn.xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-west-2
                    failure-domain.beta.kubernetes.io/zone=us-west-2b
                    hub.jupyter.org/node-purpose=user
                    k8s.dask.org/node-purpose=scheduler
                    k8s.io/cloud-provider-aws=37c23011e7c2b0bb1a0ee38411c43bc6
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-192-168-48-89.us-west-2.compute.internal
                    kubernetes.io/os=linux
                    node-lifecycle=on-demand
                    node.kubernetes.io/instance-type=g4dn.xlarge
                    topology.ebs.csi.aws.com/zone=us-west-2b
                    topology.kubernetes.io/region=us-west-2
                    topology.kubernetes.io/zone=us-west-2b
Annotations:        alpha.kubernetes.io/provided-node-ip: 192.168.48.89
                    csi.volume.kubernetes.io/nodeid: {"ebs.csi.aws.com":"i-0f35cdb24d2dcf32d"}
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 12 Jun 2024 10:41:14 +0300
Taints:             hub.jupyter.org/dedicated=user:NoSchedule
                    hub.jupyter.org_dedicated=user:NoSchedule
Unschedulable:      false
```

**Comment by sgibson91** [comment]
@GeorgianaElena I will pick this up when I finish my other tasks

**Comment by sgibson91** [comment]
I applied a taint to the GPU nodegroup on the Pythia cluster and got the binder build pod to avoid that nodegroup. However, the build pod still picked the r5.16xlarge nodegroup to build on, then when the user server was ready, that was put on the r5.xlarge node group. I wonder if the largest sized instance will always be used to build binders because we can't know ahead of time how much space they would need?

**Comment by sgibson91** [comment]
I have properly tainted all the GPU nodes for the eksctl clusters we run and updated our documentation as well.

However, I'm not sure this answers point (2)

> I think the autoscaler should spin off the smallest type of node that satisfies a resource request

As I mentioned in my above comment, I managed to prevent the Pythia Binder instance from spawning build pods on the GPU nodes, but it was still selecting the largest available node.

I'd like guidance on how we can move this issue towards closure.

**Comment by yuvipanda** [comment]
@sgibson91 I suggest making a different issue about 'spin up binderhub build pods on appropriately sized nodes' and then close this one out as completed. I think almost everything else directly pins to specific nodepools for this reason.

**Comment by sgibson91** [comment]
I have opened https://github.com/2i2c-org/infrastructure/issues/4241 to track the remaining work here
