### ISSUE TITLE
Add a `--skip-update` flag to our deployer

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4221]
Tracks https://github.com/2i2c-org/infrastructure/pull/4141

**Comment by haroldcampbell** [comment]
@AIDEA775 are you blocked or waiting for @yuvipanda to review?

**Comment by AIDEA775** [comment]
@haroldcampbell I'm waiting for a review. A few hours ago I sent news commits and a comment

**Comment by yuvipanda** [comment]
This was done. Thanks @AIDEA775
