### ISSUE TITLE
Spin up binder build pods on appropriately sized nodes

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4241]
### Context

Split from #4209 

From @GeorgianaElena's original issue:

### I think the autoscaler should spin off the smallest type of node that satisfies a resource request
- is this true @2i2c-org/engineering?
   - relevant docs that I found:
      - gcp https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler#operating_criteria
      - 
- But @jmunroe has experienced the following weird situation on aws: 
   ```
    1. Cluster has only one core node running (no user nodes)
    2. James wants to build an image on that hub and triggers the creation of a builder pod
    3. That builder pod triggers the spin off of a GPU node???
   ```
    Why did the autoscaler chose to create the biggest type of machine in the user node pool?

### Current state

We have now appropriately tainted GPU nodes on AWS so that binder build pods cannot request them, but they are still requesting the largest available node size, e.g., `r5.16xlarge`. We should also see if this is true for binder deployments on GCP.

**Comment by yuvipanda** [comment]
After speaking to @jmunroe, we decided for now that *all binderhub UI enabled hubs should be restricted to the smallest nodes we have*. I believe this is r5.xlarge on AWS and `n2-highmem-4` on GCP. Both user and build pods should be made to target these with node selectors

**Comment by GeorgianaElena** [comment]
@yuvipanda, should we document this as being the recommended practice on all binderhubUI hubs?

**Comment by yuvipanda** [comment]
@GeorgianaElena yes we should!
