### ISSUE TITLE
[New Hub] [Deadline July 7] HPOSS 'Small' Binder

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4246]
A part of https://github.com/2i2c-org/infrastructure/issues/4109.

## Phase 1: Account

Done

## Phase 2: Cluster

Use existing opensci cluster

#### Phase 3.1: Initial setup (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Name of the hub | small-binder | |
| Dask gateway? | no | |
| URL | binder.opensci.2i2c.cloud | (may change) | 
| BinderHub UI? | yes | | 
| Authentication Mechanism | None | |
| Admin Users | NA | Because BinderHub UI will be used | 
| Persistent Home Directory | no ||

#### Phase 3.2: Object storage access (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Scratch bucket enabled? |  no |  |
| Persistent bucket enabled? | no |  |
| Requestor pays requests to external buckets allowed? | no | |  

#### Phase 3.3: Profile List (**READY**)

N/A, as BinderHub UI will be used

#### Phase 3.31: Resource configuration (**READY**)

No profile list, properties set under `singleuser`

| Question | Answer |
| - | -|
| memory limit | 4G |
| memory request | 2G |
| CPU limit | 2 |
 
#### Phase 3.4: Authentication tuning (**READY**)

| Question | Answer |
| - | - |
| Authentication Mechanism | None |

#### Phase 3.5: Profile List finetuning (**NA**)

NA, as BinderHub UI will be used

#### Phase 3.6: BinderHub config (**NOT READY**)

| Question | Answer |
| - | - |
| Allowed Repositories? | `^2i2c-org/.*$` |
| Banner Message | TBD | 
| BinderHub About Message | TBD |

**Comment by yuvipanda** [comment]
Per @jmunro, banner message should direct people to email `support@` for allow-listing more repos.

Pick openscapes and NASA-IMPACT / VEDA as things to start with. We put this list in 'about'.

**Comment by consideRatio** [comment]
@yuvipanda could you confirm/update authentication mechanism answers in 3.1 and 3.4?

We also have a TBD section in 3.6 - i propose if we know only some repo's are allowed, we declare something now and then change it to verify we get that functionality setup right at all.

**Comment by consideRatio** [comment]
Could you also consider the question above for the big binder issue?

**Comment by yuvipanda** [comment]
@consideRatio done

**Comment by sgibson91** [comment]
> Name of the hub	staging	
> URL	binder.opensci.2i2c.cloud

Is the name of the hub correct, should it be binder or at least containing binder? I presume since this is an existing cluster, there is already a staging hub.

**Comment by yuvipanda** [comment]
Failure of copy paste, sorry @sgibson91. I've called it `small-binder` now, will update the other issue as well.

**Comment by sgibson91** [comment]
https://binder.opensci.2i2c.cloud
