### ISSUE TITLE
[New Hub] [Deadline: July 7] HPOSS 'Big' Binder

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4247]
Requires: https://github.com/2i2c-org/infrastructure/issues/4242

#### Phase 3.1: Initial setup (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Name of the hub | big-binder | |
| Dask gateway? | no | |
| URL | big.binder.opensci.2i2c.cloud | (may change) | 
| BinderHub UI? | yes | | 
| Authentication Mechanism | Github | |
| Admin Users | NA | Because BinderHub UI will be used | 
| Persistent Home Directory | no ||

#### Phase 3.2: Object storage access (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Scratch bucket enabled? |  no |  |
| Persistent bucket enabled? | no |  |
| Requestor pays requests to external buckets allowed? | no | |  

#### Phase 3.3: Profile List (**READY**)

N/A, as BinderHub UI will be used

#### Phase 3.31: Resource configuration (**READY**)

No profile list, properties set under `singleuser`

| Question | Answer |
| - | -|
| memory limit | 1G |
| memory request | 256M |
| CPU limit | 0.25 |
 
#### Phase 3.4: Authentication tuning (**READY**)

| Question | Answer |
| - | - |
| Authentication Mechanism | GitHub |

#### Phase 3.5: Profile List finetuning (**NA**)

NA, as BinderHub UI will be used

#### Phase 3.6: BinderHub config (**NOT READY**)

| Question | Answer |
| - | - |
| Allowed Repositories? | everything |
| Banner Message | TBD | 
| BinderHub About Message | TBD |

**Comment by haroldcampbell** [comment]
- Replicate do everything else other than dask basically
- Enable Dask after Geo is done

**Comment by yuvipanda** [comment]
For authentication, we should create a new GitHub org + team and use that to gate access.

**Comment by consideRatio** [comment]
Thank you @yuvipanda!

**Comment by sgibson91** [comment]
> Name of the hub	staging	
> URL	big.binder.opensci.2i2c.cloud

Again, I presume the name of the hub here should be `big-binder` or something, not staging

**Comment by yuvipanda** [comment]
yep done

**Comment by sgibson91** [comment]
I setup the GitHub OAuth app for this hub in the new GitHub organisation that I created, because the "New Org OAuth App" button was greyed out, which I guess means we've hit our limit.

**Comment by sgibson91** [comment]
https://big.binder.opensci.2i2c.cloud
