### ISSUE TITLE
Collect all Q2 billing data of all dedicated clusters AWS - Part 2 (Deadline July 4th)

### ISSUE THREAD

**Issue by haroldcampbell** [2i2c-org/infrastructure#4255]
This is the second part of issue [Collect all Q2 billing data of all dedicated clusters AWS #4201](https://github.com/2i2c-org/infrastructure/issues/4201).

```[tasklist]
## Tasks
- [x] @yuvipanda to add @sgibson91 to `#billing` slack channel
- [ ] Repeat [billing process](https://infrastructure.2i2c.org/howto/bill/#get-a-community-dedicated-aws-accounts-s-costs) when June is complete (i.e. first week of July) and send information to CS&S
```

**Comment by haroldcampbell** [comment]
@yuvipanda and @sgibson91 I've split [infra/4201](https://github.com/2i2c-org/infrastructure/issues/4201) and moved the incomplete task items to this tasks.

@yuvipanda may I ask you to refine this further, please? If you feel it is sufficiently refined then, please move it to Refined.

**Comment by sgibson91** [comment]
@haroldcampbell I can refine these as I know what needs to be done

**Comment by consideRatio** [comment]
I've added @GeorgianaElena and @sgibson91 to the #billing slack channel
