### ISSUE TITLE
Collect all Q2 billing data of all dedicated clusters GCP - Part 2 (Deadline July 4th)

### ISSUE THREAD

**Issue by haroldcampbell** [2i2c-org/infrastructure#4256]
This card tracks the second part of the knowledge transfer for GCP that was in [Collect all Q2 billing data of all dedicated clusters GCP #4202](https://github.com/2i2c-org/infrastructure/issues/4202)

```[tasklist]
### Tasks
- [x] @yuvipanda to add @sgibson91 to `#billing` slack channel
- [ ] Repeat [billing process](https://infrastructure.2i2c.org/howto/bill/#get-a-community-dedicated-gcp-projects-costs) when June is complete (i.e. first week of July) and send info to CS&S
```

**Comment by haroldcampbell** [comment]
@yuvipanda and @sgibson91 I've split https://github.com/2i2c-org/infrastructure/issues/4202 and moved the incomplete task items to this tasks.

@yuvipanda may I ask you to refine this further, please? If you feel it is sufficiently refined then, please move it to Refined.

**Comment by sgibson91** [comment]
@haroldcampbell I can refine these as I know what needs to be done

**Comment by consideRatio** [comment]
I've added @GeorgianaElena and @sgibson91 to the #billing slack channel
