### ISSUE TITLE
[New Hub] LABI Catalyst Project

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#4258]
This is for the [Latin America Bioimaging (LABI)](https://labi.lat/) as a part of the Catalyst Project on the catastproject-latam cluster. Please use standard catalyst profile described in

- https://github.com/2i2c-org/infrastructure/issues/3631

#### Hub Champion
Andres Olivera <aolivera.labi@gmail.com>

#### Phase 3.1: Initial setup (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Name of the hub | labi | |
| Dask gateway? | no | |
| Splash image | https://catalystproject.cloud/_static/catalyst-logo-dark-bg-white.png | |
| URL | https://catalystproject.cloud  | Used for both URL and funded_by | |
| Authentication Mechanism | GitHub (via GitHubOAuthenticator) | |
| Admin Users | aolivera.labi@gmail.com | | 

At the end of this phase, both 2i2c engineers and the admin users mentioned can login to the hub.

#### Phase 3.2: Object storage access (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Scratch bucket enabled? |  Yes |  |
| Persistent bucket enabled? | no |  |
| Requestor pays requests to external buckets allowed? | no | |  

#### Phase 3.3: Profile List (**READY**)

These are the standard profile list options we want to start with. Please INCLUDE these additional machine types:
- n1-highmem-4 + 1 nvidia-tesla-T4 GPU (for small workloads)
- n2-highmem-16 + 4 nvidia-tesla-T4 GPUs (for large workloads)

| Question | Answer | Notes |
| - | - | - |
| ProfileList  |  Standard Catalyst Profile | https://github.com/2i2c-org/infrastructure/issues/3631 |
 
#### Phase 3.4: Authentication tuning (**READY**)

| Question | Answer |
| - | - |
| Authentication Mechanism | GitHub (via GitHubOAuthenticator) |
| Org based access? | yes |
| List of GitHub orgs / teams to be granted access | https://github.com/orgs/CatalystProject-Hubs/teams/labi |

#### Phase 3.5: Profile List finetuning (**N/A**)

| Question | Answer | Notes |
| - | - | - |

**Comment by haroldcampbell** [comment]
Hi @AIDEA775 do you have a view on when this is likely to be done? I need to communicate outwards to Taj.

**Comment by AIDEA775** [comment]
@haroldcampbell I will complete this today.

**Comment by AIDEA775** [comment]
This hub was deployed without admins until Andres Olivera (aolivera.labi@gmail.com) accepts the invitation to the Github team.

**Comment by jmunroe** [comment]
We received GitHub ids via email from LABI this afternoon:

> On LABI's side the people who will be involved in the beginning are Paúl Hernandez (GitHub user: paul-hernandez-herrera, [paul.hernandez@uaslp.mx](mailto:paul.hernandez@uaslp.mx)) and me, Andrés Olivera (GitHub user: aolivera-labi, [aolivera.labi@gmail.com](mailto:aolivera.labi@gmail.com)).

I think these two can be set up as hub champions with admin rights.

**Comment by AIDEA775** [comment]
Thanks @consideRatio! I also invited paul-hernandez-herrera to the Github Team
