### ISSUE TITLE
Enable `auth_state` for NASA VEDA

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4279]
This will help complete https://github.com/NASA-IMPACT/veda-jupyterhub/issues/19.

VEDA uses GitHubOAuthenticator, but currently does not have `auth_state` and `populate_teams_in_auth_state` enabled. We need to turn both on, and log everyone out, so we can offer separate profile options to different users in the future more easily.

**Comment by consideRatio** [comment]
The "log everyone out" isn't trivial, but I think it can be done by resetting the cookie secret for the hub like described in https://z2jh.jupyter.org/en/stable/resources/reference.html#hub-cookiesecret (kubectl edit on a k8s secret, then remove a key/value pair related to cookie secret, then redeploy).

I'll explore the consequences of doing this for a user with a running server in openveda staging now.

**Comment by sgibson91** [comment]
@consideRatio We have documentation on the hub cookie secret here https://infrastructure.2i2c.org/hub-deployment-guide/configure-auth/github-orgs/#enabling-team-based-access-on-hub-with-pre-existing-users
