### ISSUE TITLE
Regenerate SMCE Credentials for 3 clusters

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4285]
This is a recurring task that must be done every ~55 days.

AWS credentials for our hub deployer must be renewed for the following clusters:

- [x] NASA VEDA
- [x] GHG Center
- [x] ESDIS

**Comment by yuvipanda** [comment]
Incidentally there was a VEDA outage today so I ended up doing https://github.com/2i2c-org/infrastructure/pull/4286. But still needs to be done for the other two.

**Comment by yuvipanda** [comment]
#2434 has more documentation on this.

Someone other than me or @consideRatio should pick this up.

**Comment by yuvipanda** [comment]
and we can do password resets if that is needed by whoever picks this up :)

**Comment by sgibson91** [comment]
Step-by-step instructions for how to do this are in the body of this issue https://github.com/2i2c-org/infrastructure/issues/2434 - but should be incorporated into our docs, maybe at this page https://infrastructure.2i2c.org/howto/regenerate-smce-password/
