### ISSUE TITLE
Q2 billing data collection - dedicated clusters (Deadline July 10th)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4288]
## Definition of done

- Billing data for dedicated clusters' Q2 months are collected according to [instructions](https://infrastructure.2i2c.org/howto/bill/#communities-with-dedicated-cloud-accounts).
- `#billing` slack notified about the new billing data collected

Q2 months are April, May, June.

**Comment by consideRatio** [comment]
@yuvipanda proposed this is worked by @GeorgianaElena during the sprint starting July 4th -- to be decided during a future iteration planning.

**Comment by GeorgianaElena** [comment]
I'll be off next week, so I can't take this one unfortunately.

**Comment by sgibson91** [comment]
Yes, I assigned myself to the previous issue because I knew Georgiana wouldn't be available and we had already done the important knowledge share part.

**Comment by yuvipanda** [comment]
I think @GeorgianaElena can do this once she comes back from her time off - so not during this sprint, but post vacation. The deadline provided to CS&S was July 10th.

**Comment by consideRatio** [comment]
> We'll pike July 10th as our deadline, and make 100% sure it's with you before that.

We should still get this done no later than July 9th based on that commitment right? That is why i wrote July 9th.

**Comment by consideRatio** [comment]
@sgibson91 is it correct that the work remaining here covers all Q2 months, and that the google spreadsheet shouldn't be updated when doing dedicated billing things any more?

**Comment by sgibson91** [comment]
@consideRatio Yes

**Comment by consideRatio** [comment]
After the development of new tooling, this isn't something I've done before - I'll go for it.

**Comment by sgibson91** [comment]
@consideRatio when I originally wrote the new command, I decided not to exclude shared clusters in order to reduce the number of assumptions the code made - I may have now changed my mind. Please ping me to discuss if you want.

**Comment by sgibson91** [comment]
I propose we delay our sync chat until you have run through the instructions and generated the CSV files. It will be easier to see what I'm talking about then.

**Comment by consideRatio** [comment]
https://drive.google.com/drive/u/1/folders/1_xXZ2ndEOplZidG_mj6nmUTzsOuxARcL includes the generated files now, and I have raw files to look at as well.

I've not communicated in #billing about this yet, and I figure we coordinate about that.

**Comment by consideRatio** [comment]
Communicate in billing to James and Harold!
