### ISSUE TITLE
`deployer exec` feature - exec into a shell with the NFS storage filesystem root mounted

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4291]
When performing a EFS backup restoration, the restore was done to a new folder in the root of the EFS filesystem. In order to relocate that I had to get a shell where I had the full EFS filesystem mounted - not just a folder associated with a hub's files.

Currently we can quickly exec into a k8s pod with a hub's file system mounted via a command like `deployer exec homes nasa-cryo prod`, but we can't quickly get the cluster's entire filesystem mounted with a command like `deployer exec homes nasa-cryo` or similar.

I think a development of the deployer makes sense to do, to allow us to get a shell with the entire filesystem, as it enables us to relocate restored files in the root to where they should be restored.

## Workaround ideas

<details>

### Idea 1 (doesn't work)

A workaround until then is to update the deployer script's command `deployer exec homes <cluster> <hub>` to do it.

It doesnt work as the deployer references a PVC that is tied to the hub subpath, and there isn't a pvc not tied to the hub subpath.

### Idea 2

Declare the volume by not referencing the PVC, but something like this instead: https://kubernetes.io/docs/concepts/storage/volumes/#nfs
</details>

**Comment by yuvipanda** [comment]
For the specific case that triggered this, I was able to complete the task with the following diff:

```diff
diff --git a/deployer/commands/exec/infra_components.py b/deployer/commands/exec/infra_components.py
index 7ea1fba3..edb33ee2 100644
--- a/deployer/commands/exec/infra_components.py
+++ b/deployer/commands/exec/infra_components.py
@@ -36,7 +36,7 @@ def homes(
             "automountServiceAccountToken": False,
             "volumes": [
                 # This PVC is created by basehub
-                {"name": "home", "persistentVolumeClaim": {"claimName": "home-nfs"}}
+                {"name": "home", "nfs": {"server": "fs-0872256335d483d5f.efs.us-west-2.amazonaws.com", "path": "/"}}
             ],
             "containers": [
                 {
```

I picked up the server name from our config.

We can prioritize this if it becomes a deeply recurring task.

**Comment by yuvipanda** [comment]
We should implement this as a `deployer exec root-homes <cluster> <hub>` for simplicity.

Instead of binding the to the PVC, we should directly use NFS in the pod definition (https://kubernetes.io/docs/concepts/storage/volumes/#nfs)

The server and path information should be gleaned from:

1. directly looking at the realized config files - available under `basehub.nfs.pv.serverIP` and `basehub.nfs.pv.baseShareName`
2. Making k8s API calls to find the PVC, find the PV attached to it, and getting the same information from them.

My preference is for (1).

**Comment by GeorgianaElena** [comment]
This is what it shows:

![Image](https://github.com/user-attachments/assets/63424f3c-256b-43e5-8f83-c1c9e5dc463a)

**Comment by GeorgianaElena** [comment]
The comment was intended for the PR #4438   sorry 😅
