### ISSUE TITLE
Design a simple system where users can ask for access to HPOSS Binders

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4310]
Now that the two HPOSS binders are up, we need a system where folks can request that:

1. New repos be added to 'small' binder
2. New users be added to 'big' binder

As discussed with @jmunroe, to begin with, we should:

1. Set up a *new* support queue in Freshdesk
2. Set a banner message in small binder saying 'Want to launch a NASA related repository you care about from this Binder instance? Please email <freshdesk-queue-email> with information and we will get back to you!'
3. Set a **logged out home page announcement** in big binder saying 'Are you affiliated with NASA in some way and want to get access to this instance? Please email <freshdesk-queue-email> with information and we will get back to you'

I (Yuvi) will be responsible for handling these as part of support initially, if we get swarmed we'll bring up a better system.

**Comment by sgibson91** [comment]
- I've setup a new support email in Freshdesk called binder-requests@2i2c.org
- I've created a new group also called "Binder Requests" and assigned Yuvi to it (we can change membership as and when we see fit)
- I have setup an automation that will assign tickets sent to binder-requests@2i2c.org to the "Binder Requests" group
- I have created a new view in Freshdesk called "All unresolved Binder Request tickets" that should... show all unresolved tickets in the Binder Requests group 😄

**Comment by sgibson91** [comment]
I need extra help to verify the binder-requests@2i2c.org email address works. I think it will involve signing into our Google Workspace as admin to set a forwarding rule, but I don't appear to have admin access.

However, for now sending mail to 2i2corgbinder-requests@2i2c.freshdesk.com will work.

**Comment by consideRatio** [comment]
> I need extra help to verify the [binder-requests@2i2c.org](mailto:binder-requests@2i2c.org) email address so it will work. I think it will involve signing into our Google Workspace as admin to set a forwarding rule, but I don't appear to have admin access.

I also lacked access @sgibson91 - I wasn't confident on what to do if I had though, was it to setup email forwarding from binder-requests@2i2c.org to 2i2corgbinder-requests@2i2c.freshdesk.com ?

**Comment by jmunroe** [comment]
My solution for creating these kind of forwarding emails to FreshDesk has been to create a Google Group under the 2i2c org with the FreshDesk email address the only member  of the group.

**Comment by sgibson91** [comment]
@consideRatio it was to follow these steps https://support.freshdesk.com/en/support/solutions/articles/37541-forward-and-convert-your-support-emails-to-tickets-in-freshdesk#Verify-and-set-up-forwarding-rules-for-the-Freshdesk-mail-server

But I will try @jmunroe's solution too - thank you!

**Comment by sgibson91** [comment]
That worked - thank you James!
