### ISSUE TITLE
Identify and fix existing setups of access GCP buckets via google groups

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4319]
https://github.com/2i2c-org/infrastructure/issues/4318 was about documenting a permissions detail fix influencing non-2i2c users without other cloud permissions setup for them - this issue is about fixing the detail in existing setups.

I think leap and catalystproject-latam has this setup, and we can identify this by looking at GCP projects buckets and their permissions granted. We could also look at google groups we've created.

## Related

- Docs on setting up bucket access using google groups: https://infrastructure.2i2c.org/howto/features/buckets/#allowing-authenticated-access-to-buckets-from-outside-the-jupyterhub

**Comment by consideRatio** [comment]
Done - this was relevant for LEAP and catalystproject-latam.

Ping @jbusecke --- this likely resolved an issue I recall you had observed for users not granted permissions to the GCP project in any other way besides being part of a google group meant to provide permissions to work against a bucket.

**Comment by jbusecke** [comment]
Ah good to know. I assume there is nothing we need to change on our end in terms of how the [user is supposed to authenticate](https://leap-stc.github.io/guides/hub_guides.html#uploading-large-original-data-from-an-hpc-system-no-browser-access-on-the-system-available)? Will try to test that with somebody at LEAP.
