### ISSUE TITLE
Move remaining hubs on catalystproject-latam to new filestore

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4368]
Once https://github.com/2i2c-org/infrastructure/issues/4337 is done, time to move the rest of the hubs. Should follow the same process that is tested on the staging hub.

```[tasklist]
### Tasks
- [x] cabana
- [x] cicada
- [x] gita
- [x] iner
- [x] labi
- [x] nnb-ccg
- [x] plnc
- [x] unam
- [x] unitefa-conicet
- [x] uprrp
```

---

The process here would be:

1. Wait for a hub to have no active users
2. Stop new users from accessing the hub (I suggest by doing a `k -n <hub-name> delete svc proxy-public`)
3. Do one final `rclone`
4. Deploy the change to point to the new filestore IP. This should also bring back proxy-public svc and restore access.

(4) further needs:

1. `k delete pv <hub-name>-home-nfs --wait=false`
2. `k -n <hub-name> delete pvc home-nfs --wait=false`
3. `k -n <hub-name> delete pod -l component=shared-dirsize-metrics`
4. `k -n <hub-name> delete pod -l component=shared-volume-metrics`

This is because PersistentVolumes are _not_ editable, and we must delete and recreate them to allow the new deploy with new IP to succeed. And this is the sequence of the objects _dependent_ on the PV, and we need to delete all these for it to finish.

**Comment by sgibson91** [comment]
Mostly done, just have to wait for unitefa-conicet to empty out
