### ISSUE TITLE
Copy mybinder.org's build resource limits to all our binderhub-service deployments

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4371]
I spoke to @jmunroe, and we decided that for now we want to simply copy the resource limits that mybinder.org employs for its build setup to all our binderhub-service deployments.

This includes:

1. https://github.com/jupyterhub/mybinder.org-deploy/blob/a820075a32266f6b84bc25c9eaea78f870ed39de/mybinder/values.yaml#L192 `memory_limit` and `memory_request`
2. https://github.com/jupyterhub/mybinder.org-deploy/blob/a820075a32266f6b84bc25c9eaea78f870ed39de/mybinder/values.yaml#L315 for the docker dind pods (we may have to configure this in a slightly different place)

**Comment by consideRatio** [comment]
If this is deployed, I think we'll break things, so I'd like to send this back to the refinement process.

1. We have binderhub-service configuring the daemonset starting a docker daemon pod on each _user node with a _small size of 4 cpu_.
2. With this change, the daemonset pods is configured to request notable amount of CPU and memory.
3. I think that makes user pods also meant to schedule on those nodes and requesting ~100% will stop fitting on the node.

The reason this config works well on mybinder.org-deploy is based on the assumption that no user will request a large portion of the node, but have situations where this assumption is broken within in the clusters where binderhub-service deployments run.

**Comment by consideRatio** [comment]
Hmmm, we could add the limits and declare requests at 0 still without issues (declaring a limit without requests puts the request at the limit). I'll do that as it seems like an improvement.

**Comment by sgibson91** [comment]
I reverted PR #4416 and am reopening this issue because @jnywong reported Docker exit code 127 (OOM) errors.

**Comment by yuvipanda** [comment]
Thanks @sgibson91.

I'm going to leave this open for @consideRatio to investigate in a timeboxed manner when he's back.

**Comment by yuvipanda** [comment]
I actually have changed my mind. 

Given the resources available to us and the priorities of the limited engineering team, I now have decided we're just going to close this as not done for now. We can revisit later in the future if we run into issues.

Let's not spend any more time on this for now.
