### ISSUE TITLE
Create a deployment and service accounts in the support/ chart for gcp-filestore-backup to run

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4395]
Once https://github.com/2i2c-org/infrastructure/issues/4394 is done, we need to create enough kubernetes resources that can deploy this service. That would need to be a deployment that's running the image as a container, and a service account attached to it (so we can grant it the required cloud permissions).

The service account must have configurable annotations (so we can use [workload identity](https://cloud.google.com/iam/docs/workload-identity-federation) to give it cloud permissions), and the deployment must set [strategy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy) to 'Recreate' (so we minimize chances of two instances running together).

This should be disabled by default, and enable-able per-cluster as needed.

**Comment by sgibson91** [comment]
Dropping this here to remind me that I need to authenticate gcloud in the Dockerfile at some point https://github.com/2i2c-org/infrastructure/blob/91d0af07311408efa3716d8570eeacc1e7e0d7e0/helm-charts/basehub/templates/static/deployment.yaml#L62-L67
