### ISSUE TITLE
Test and document AWS EFS home directory restore functionality

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4424]
Backups are only useful if we know they work, and can actively restore them.

https://docs.aws.amazon.com/aws-backup/latest/devguide/restoring-efs.html has documentation on how to restore an EFS backup.

We should test to make sure we can, and then write the smallest amount of documentation possible to make sure we can do so in times of disaster. We should rely on linking out to the cloud provider documentation as much as possible, this doesn't have to be super detailed.

In the long run, we should test these once every 6 months or so. But that's out of scope for this ticket

**Comment by sgibson91** [comment]
### How did I test?

I created another backup to reduce the amount of dataloss and then followed the restore instructions and they worked.
