### ISSUE TITLE
Test and document GCP filestore home directory restore functionality

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4425]
Backups are only useful if we know they work, and can actively restore them.

https://cloud.google.com/filestore/docs/backup-restore#restore has documentation on how to enable and restore a filestore backup.

We should test to make sure we can restore from backups (once enabled), and then write the smallest amount of documentation possible to make sure we can do so in times of disaster. We should rely on linking out to the cloud provider documentation as much as possible, this doesn't have to be super detailed.

In the long run, we should test these once every 6 months or so.

**Comment by sgibson91** [comment]
I also expanded the scope of this issue to include documenting how to enable the backups for GCP as well, since that task wasn't captured anywhere
