### ISSUE TITLE
Enable cost allocation tags on openscapes AWS account

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4473]
Once https://github.com/2i2c-org/infrastructure/issues/4464, https://github.com/2i2c-org/infrastructure/issues/4485 and https://github.com/2i2c-org/infrastructure/issues/4482 are done, we need to 'enable' using the various tags we have set up as a 'cost allocation tag'.

This will need to be done via terraform: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_cost_allocation_tag. 

The following tags would need to be 'activated':

- `2i2c:hub-name`
- `2i2c:node-purpose`
- `aws:eks:cluster-name` (autogenerated by AWS)
- `kubernetes.io/created-for/pvc/name` (allows us to track cost of hub db PVC and prometheus PVC)
- `kubernetes.io/created-for/pvc/namespace` (same as above)
- `kubernetes.io/cluster/openscapeshub` (enables us to track disks used by PVCs)

## Definition of done

Looking at https://us-east-1.console.aws.amazon.com/billing/home#/tags after logging into the openscapes account should show these tags being activated

**Comment by consideRatio** [comment]
Issue blocked blocked pending issue resolutions:
- https://github.com/2i2c-org/infrastructure/issues/4464
- https://github.com/2i2c-org/infrastructure/issues/4485
- https://github.com/2i2c-org/infrastructure/issues/4482
