### ISSUE TITLE
Make new EFS and switch workshop hub to it on openscapes

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4475]
Equivalent of https://github.com/2i2c-org/infrastructure/issues/4461 for the workshop hub.

- [x] Make a new EFS filesystem for `workshop` hub
- [x] Migrate existing data from the existing EFS to this new EFS (see notes below)
- [ ] Switch workshop hub to the new EFS

## Definition of Done

- [ ] `workshop` hub is using the new EFS for home directory storage
- [x] Permissions *and* ownership of all files match between source and destination after copying files.

## Making the copy

You can wait for users to not be active on the workshop hub (next workshop is in October, so nobody should be), kill new logins (by deleting the `proxy-public` service), and make the copy. Redeploying (with the new EFS) should bring the hub back up. 

Take care around permissions and mode - we used `rclone` for a similar project last time, and ended up with ownership stuck to `root`. Consider using `rsync` with the `--archive` and `--progress` flags for doing the copy instead this time.

**Comment by GeorgianaElena** [comment]
I've copied the homdirs of the workshop hub using DataSync instead as per https://infrastructure.2i2c.org/hub-deployment-guide/hubs/move-hubs/across-clusters/#efs. While doing the copying, there was an option to  keep original file ownership and permissions, so I've selected that. Afterwards, I checked the files permissions and they were ok.

Note that I haven't deleted the contents of the workshop dir from the initial EFS. It wasn't clear from this issue and was reluctant to do it.
