### ISSUE TITLE
[Documentation] Document how to enable budget alerts on AWS

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#4481]
While doing the budget alerts for Azure, I realized that docs on AWS are missing https://infrastructure.2i2c.org/howto/budget-alerts. This relates to https://github.com/2i2c-org/meta/issues/952#issuecomment-2245179856

So I believe this issue is a follow up to https://github.com/2i2c-org/meta/issues/1256 and part of the bigger epic https://github.com/2i2c-org/meta/issues/1239

**Comment by consideRatio** [comment]
Declared this as internal engineering, because https://github.com/2i2c-org/meta/issues/1239 was internal engineering
