### ISSUE TITLE
Decomission old AWI-CIROH infrastructure

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4483]
https://github.com/2i2c-org/infrastructure/issues/4238 is complete. We wait until Monday, July 29 and see if there are any user reported issues. If not, we decomission the old infrastructure.
- [x] We wait until Monday, July 29
- [x] Decomission the `awi-ciroh` terraform workspace. May need a git checkout from before https://github.com/2i2c-org/infrastructure/pull/4444 was merged
- [x] Look at the `awi-ciroh` GCP project, make sure it's completely empty and all resources (including ones that were manually created for the transfer) are deleted
- [ ] Rename the `awi-ciroh-2` terraform workspace to `awi-ciroh`

**Comment by sgibson91** [comment]
Shit, I just remembered we were supposed to wait until Monday.

**Comment by sgibson91** [comment]
This is blocked now also anyway

```
 Error: Error trying to delete bucket awi-ciroh-scratch containing objects without `force_destroy` set to true
│ 
│ 
╵
╷
│ Error: Error trying to delete bucket awi-ciroh-persistent containing objects without `force_destroy` set to true
│ 
│ 
╵
╷
│ Error: Cannot destroy cluster because deletion_protection is set to true. Set it to false to proceed with cluster deletion.
│ 
│ 
╵
╷
│ Error: Error trying to delete bucket awi-ciroh-persistent-staging containing objects without `force_destroy` set to true
│ 
```

I tried adding the relevant variables in the appropriate places in our code, but unless these variables are _already in terraform state_, it has no effect.

**Comment by sgibson91** [comment]
I used the Asset Inventory to check which resources where left over: https://console.cloud.google.com/iam-admin/asset-inventory/resources A lot of what's left in here are default resources (I think, I'm looking at the LogBuckets there) and enabled APIs.

I deleted two object storage buckets, three VM instances, and a BigQuery service account that weren't cleaned up by terraform.

**Comment by sgibson91** [comment]
I followed these steps to rename the workspace https://discuss.hashicorp.com/t/how-to-change-the-name-of-a-workspace/24010/2

**Comment by yuvipanda** [comment]
Thank you, @sgibson91!
