### ISSUE TITLE
Add a AWS tag to the core nodepool on openscapes cluster

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4486]
Similar to https://github.com/2i2c-org/infrastructure/issues/4482, we want to apply a specific tag to the `core` nodepool on openscapes cluster so we can track the shared costs for all hubs.

- [ ] Add a tag `2i2c:node-purpose` set to value `core` for the core nodepool

## Definition of done

The running EC2 instances of the core nodepool have this tag. You can verify it by looking at the instances on the AWS console

**Comment by sgibson91** [comment]
So... the AWS console says there aren't _any_ nodegroups?

https://us-west-2.console.aws.amazon.com/eks/home?region=us-west-2#/clusters/openscapeshub?selectedTab=cluster-compute-tab

![Image](https://github.com/user-attachments/assets/d069bec5-9f7d-47d9-a0da-f2a61e8128b1)

Running `k get node --label-columns=alpha.eksctl.io/nodegroup-name` does show the new nodegroup though

```
NAME                                           STATUS   ROLES    AGE    VERSION               NODEGROUP-NAME
ip-192-168-48-107.us-west-2.compute.internal   Ready    <none>   7m3s   v1.29.3-eks-ae9a62a   core-b
```

I'm pretty sure this is complete but I will leave it open until we can verify.

**Comment by yuvipanda** [comment]
@sgibson91 We use ['unmanaged' nodegroups](https://eksctl.io/usage/nodegroup-unmanaged/) with eksctl, while these are [managed nodegroups](https://eksctl.io/usage/nodegroup-managed/). Those pieces of documentation should hopefully help.

**Comment by sgibson91** [comment]
![Image](https://github.com/user-attachments/assets/fb334e2f-86e5-4e21-b7ed-1d1b9346052d)

I honestly think figuring out how to verify this in the console was more work than completing the task 😅
