### ISSUE TITLE
Provide more information during CI failures

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#449]
# Background

When we use the deployer script and something fail related to the `helm upgrade` command, we are left quite clueless on what failed without manual inspection.

To make sure that isn't the case is the core goal.

# Expected timeline

End of july perhaps? It depends on the 

# Steps to complete this goal

- [ ] Decide if the following action points are reasonable
- [ ] Add a command to the deployer script to setup credentials to access k8s
- [ ] Get https://github.com/jupyterhub/action-k8s-namespace-report/pull/6 merged so we can limit what pods may be irrelevant to show information about for example and we shouldn't print logs about them.
- [ ] Run https://github.com/jupyterhub/action-k8s-namespace-report on failures to deploy in our github CI system (which would require k8s access to be setup)
- [ ] Consider security implications: k8s-namespace-report will emit logs and such which can be sensitive for example if debugging mode or high loglevels are set. Is there something that we should do to make this acceptable?
  - Related: https://github.com/jupyterhub/action-k8s-namespace-report/issues/7

**Comment by damianavila** [comment]
+1 on the idea to get more information for debugging purposes.

> Consider security implications: k8s-namespace-report will emit logs and such which can be sensitive for example if debugging mode or high loglevels are set. Is there something that we should do to make this acceptable?

Maybe the action could push the report to someplace with auth? And it only prints a link to where that log is now "securely" saved? I would not be comfortable deploying something that allows anyone to access the logs and extract sensitive info from there...

**Comment by consideRatio** [comment]
Maybe we could provide more logs and use k8s namespace report or similar, but I think its a bit risky to expose logs from user pods etc so I suggest we just close this. If needed, we manually retry a deploy instead to see the failures.
