### ISSUE TITLE
Add AWS tags to scratch and persistent buckets on openscapes cluster

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4502]
Similar to https://github.com/2i2c-org/infrastructure/issues/4464, we want to tag the S3 buckets we set up for the hubs with the `2i2c:hub-name` AWS tag (via terraform) to point to the hub that the bucket is set up for.

**Comment by consideRatio** [comment]
@yuvipanda this is completed based on the description of scratch/persistent, but there is also another bucket - I opted to not tag it for now.

```terraform
  "prod-homedirs-archive" : {
    "archival_storageclass_after" : 3,
    "delete_after" : 185,
  },
```

Should I leave this untagged or tag it to belong to `prod`

**Comment by yuvipanda** [comment]
Let's leave that untagged for now @consideRatio
