### ISSUE TITLE
[Spike][2h] Follow the Django tutorial

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#4505]
Follow the Django tutorial for 2h and see if it feels interesting/engaging enough to be picking up Django-related work in the near future.

## Definition of done

- [x] Do the tutorial in a time-boxed fashion 2h
- [x] Have a discussion with @yuvipanda about reflections about the tutorial, progress, etc.

**Comment by yuvipanda** [comment]
And @jnywong has offered to help if needed!

**Comment by jnywong** [comment]
Yep @GeorgianaElena do not hesitate 😊
