### ISSUE TITLE
[EVENT] PACE Hackweek

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#4507]
### The link towards the Freshdesk ticket this event was reported

https://2i2c.freshdesk.com/a/tickets/1861

### The GitHub handle or name of the community representative

@tsnow03

### The date when the event will start

2024-08-04

### The date when the event will end

2024-08-08

### What hours of the day will participants be active? (e.g., 5am - 5pm US/Pacific)

830am – 5pm US/Eastern

### Are we three weeks before the start date of the event?

- [ ] Yes
- [X] No

### Number of attendees

45

### Make sure to add the event into the calendar

- [X] Done

### Does the hub already exist?

- [X] Yes
- [ ] No

### The URL of the hub that will be used for the event

https://hub.cryointhecloud.com

### Will this hub be decommissioned after the event is over?

- [ ] Yes
- [X] No

### Was all the info filled in above?

- [X] Yes
- [ ] No

### Quotas from the cloud provider are high-enough to handle expected usage?

- [x] Yes
- [ ] No

**Comment by tsnow03** [comment]
Adding @itcarroll as a community representative

**Comment by yuvipanda** [comment]
Let's close this, since we didn't actually take any action here. We can track other individual bits separately when needed.
