### ISSUE TITLE
[Blocked] Write an Athena Query to split out per-hub S3 cos

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4511]
Based on https://github.com/2i2c-org/infrastructure/issues/4465, we're going to be using [AWS Athena](https://aws.amazon.com/athena/) to [query billing data](https://docs.aws.amazon.com/cur/latest/userguide/cur-query-athena.html)

For this task, we need to write an SQL query that provides these 4 columns as output

- start_time
- end_time
- hub_name
- cost

If there is any S3 cost that isn't assigned to a hub, that should also be reported.

What goes into this query should be guided by item 2 of definition of done below.

## Definition of done

1. SQL query when executed provides information for all 3 hubs on the openscapes cluster
2. If you add the cost values for all the hubs, they *must* add up to what shows up under 'S3' in 'Cost Explorer' under 'Billing' in the AWS console.

## Resources

- [Query Editor](https://us-west-2.console.aws.amazon.com/athena/home?region=us-west-2)
- Workshop with example Athena SQL queries against billing data - https://wellarchitectedlabs.com/cost-optimization/cur_queries/
- [Data dictionary for columns in billing export](https://docs.aws.amazon.com/cur/latest/userguide/data-dictionary.html)

**Comment by consideRatio** [comment]
Preliminary closed, but can be reopened if Athena becomes relevant.
