### ISSUE TITLE
Backup JupyterHub databases

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#452]
# Background

We currently use the default sqlite database backend for JupyterHub, held in a small PVC disk attached to each hub. Most important information here is list of allowed users - for most of our hubs, this is the only place they are in. 

We currently don't back this up! We should.

# Options

There are two options from my perspective.

1. Move to a postgresql server. 1 db per cluster, with 1 db per hub.
2. Use something like [litestream](https://litestream.io/) to backup sqlite to object storage.

I very much prefer (2) - it's a lot simpler, and fits our use case (backup) very well.

**Comment by yuvipanda** [comment]
To do (2), we'll need to give each hub pod some way to write to a GCP bucket. Not sure what's the easiest way to do that is

**Comment by damianavila** [comment]
> we'll need to give each hub pod some way to write to a GCP bucket.

And I guess it is the same for an S3 bucket on the AWS-based deployments, right?

**Comment by yuvipanda** [comment]
> And I guess it is the same for an S3 bucket on the AWS-based deployments, right?

Yep!

**Comment by yuvipanda** [comment]
The primary problem here is to avoid 'leaking' one hub credentials to another. Each hub should be able to backup its own database (in a write-only fashion) and nothing else. So the service account provisioned for each hub should have write access *only* to its object, and nothing else. And we should just put everything in a centralized GCS for simplicity.

So, we need to:

1. Create a GCS bucket for storing these databases
2. As part of the deployer, create a Service Account with access to a prefix in this bucket for each hub
3. Write a sidecar that backs up the database (and any additional files) to this prefix on the bucket

**Comment by yuvipanda** [comment]
We could've used https://kubernetes.io/docs/concepts/storage/volume-snapshots/ but it isn't available in most clouds yet (since it requires migrating to a CSI driver for storage), and I'm worried that kubernetes errors might make it not work. I would rather have the backup mechanism be on a pathway that isn't dependent on kubernetes

**Comment by damianavila** [comment]
> I would rather have the backup mechanism be on a pathway that isn't dependent on kubernetes

I agree with that!

**Comment by choldgraf** [comment]
Setting this one as a low priority for now, since I don't think that this is actively problematic right now (but would be eventually, so we should keep track of it and prioritize higher in the future once some of our bigger infrastructure issues are improved)
