### ISSUE TITLE
[Wait until Aug 1] Deploy `jupyterhub-fancy-profiles` to production VEDA hub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4522]
As part of https://github.com/NASA-IMPACT/veda-jupyterhub/issues/34, we want to deploy `jupyterhub-fancy-profiles` to the VEDA production hub. They have been testing this on the staging hub, and it's good to move it now.

See also https://github.com/2i2c-org/meta/issues/1368

## Timeline

Wait until Thursday (Aug 1) before doing this

## Tasks

```[tasklist]
- [x] Move the profileList from the VEDA `staging.yaml` to `common.yaml`
- [x] Move the hub.image from the VEDA `staging.yaml` to `common.yaml`
```

## Definition of done

- Logging into the VEDA JupyterHub shows the jupyterhub-fancy-profiles

**Comment by yuvipanda** [comment]
@batpad let us know if there are any objections or blockers.

**Comment by sgibson91** [comment]
I think `hub.extraConfig.enable-fancy-profiles` also needs to be moved as well?
