### ISSUE TITLE
[Blocked] Write an Athena Query to split out 'fixed' compute cost

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4524]
Based on https://github.com/2i2c-org/infrastructure/issues/4465, we're going to be using [AWS Athena](https://aws.amazon.com/athena/) to [query billing data](https://docs.aws.amazon.com/cur/latest/userguide/cur-query-athena.html)

For this task, we need to write an SQL query that provides these 4 columns as output

- start_time
- end_time
- cost

This should count:

- EC2 costs with `2i2c:node-purpose` set to `core`
- EKS master server costs (filtered by EKS cluster name)
- Disks in our support namespace (tagged by `kubernetes.io/created-for/pvc/namespace` (`support`) and `kubernetes.io/cluster/openscapeshub` set to `owned`)

## Definition of done

1. SQL query when executed provides information for all 3 hubs on the openscapes cluster
2. The total cost is reasonably flat through time

## Resources

- [Query Editor](https://us-west-2.console.aws.amazon.com/athena/home?region=us-west-2)
- Workshop with example Athena SQL queries against billing data - https://wellarchitectedlabs.com/cost-optimization/cur_queries/
- [Data dictionary for columns in billing export](https://docs.aws.amazon.com/cur/latest/userguide/data-dictionary.html)

**Comment by consideRatio** [comment]
Preliminary closed, but can be reopened if Athena becomes relevant.
