### ISSUE TITLE
Enable backfilling cost tagging for AWS Openscapes account

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4525]
After https://github.com/2i2c-org/infrastructure/issues/4473 is done, we will need to enable backfilling costs for the current month. There isn't much point enabling backfilling costs for much longer than that, because we have created new resources for a few things (EFS, nodegroups) that we can't trust values going back. So let's backfill it just for July.

https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-allocation-backfill.html describes how to request backfill through the web interface.

It may take ~1-2 days for this to complete.

## Definition of done

- In the 'filter' options in the right sidebar of the [AWS Cost Explorer](https://docs.aws.amazon.com/cost-management/latest/userguide/ce-what-is.html) allows filtering by *all* the tags specified in https://github.com/2i2c-org/infrastructure/issues/4473

**Comment by consideRatio** [comment]
- While #4473 is done now, we should also await #4464 before doing this.

**Comment by consideRatio** [comment]
![image](https://github.com/user-attachments/assets/69347b81-8136-43f0-b2ef-ef46a132e655)

All of the tasks we waited for has been completed, backfilling task started successfully!

**Comment by consideRatio** [comment]
Success!

![Image](https://github.com/user-attachments/assets/b8764c43-f53a-4139-80f4-5c573997fed4)
