### ISSUE TITLE
Support getting VEDA S3 buckets being properly accessed from VEDA hubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4535]
As part of https://github.com/NASA-IMPACT/veda-jupyterhub/issues/53, we need to merge and `terraform apply` some PRs like https://github.com/2i2c-org/infrastructure/pull/4533.

This is part of https://github.com/2i2c-org/meta/issues/1368.

The VEDA team will make appropriate PRs (like https://github.com/2i2c-org/infrastructure/pull/4533), but currently it requires someone from 2i2c engineering to apply them

This issue is to track (on behalf of 2i2c engineering) providing support for reviewing and merging these PRs

## Definition of done

- https://github.com/NASA-IMPACT/veda-jupyterhub/issues/53 is closed.

**Comment by wildintellect** [comment]
@yuvipanda the PR is ready. Note: after we test this out on staging, and confirm we're happy with all the permissions on both side we'll be doing a second PR to allow this bucket on additional NASA VEDA related hubs.

**Comment by yuvipanda** [comment]
Great, @wildintellect. Please tag @sgibson91 in PRs so she gets notified, and she'll merge them. Note she's in the UK timezone so that may affect when these happen.

**Comment by yuvipanda** [comment]
Sarah did this with #4609

**Comment by smohiudd** [comment]
I tested out the veda s3 bucket access in production and and I'm able to get access now. Thanks
