### ISSUE TITLE
[Spike] [2h] Investigate how we can alert if a backup has not been performed

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4536]
Since we are doing GCP backups ourselves, we *must* investigate and be alerted if the backups fail for some reason.

We need to alert if:

- No backups in the last 32 hours (given we are making a backup every 24h, this gives us an 8h slack)
- Backups older than 8 days (or however many days we are keeping them + 1)

This spike should investigate:

- [ ] Are there metrics in https://cloud.google.com/monitoring/api/metrics_gcp we can use to alert on these two conditions?
- [ ] If there are no metrics, examine [cloud logging](https://cloud.google.com/logging?hl=en) to see if there's anything there that we can use to watch for backup failures or deletions. This can be used to make alerts too, via https://cloud.google.com/logging/docs/alerting/log-based-alerts.

## Definition of done

We know if we can use any of the existing GCP features to alert here, or if we need to build that out ourselves.

**Comment by sgibson91** [comment]
https://github.com/user-attachments/assets/ab9b0ef7-deb1-4fac-bcf5-62fef8ea413b

I looked through metrics in the Logs Explorer and there doesn't appear to be anything useful pertaining to the Filestore there either.

**Comment by sgibson91** [comment]
I'm not wholly confident, but I don't think there's anything built-in for us to monitor backups given that we're not using the Backup & DR service
