### ISSUE TITLE
[openscapes] Fix EFS encryption state

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#4542]
### Context

While doing the tagging of the EFS, from the console of the project it appears that the new EFS instances I've created for the staging and workhop hubs are not encrypted https://us-west-2.console.aws.amazon.com/efs/home?region=us-west-2#/file-systems.

When allowing [multiple EFS creation](https://github.com/2i2c-org/infrastructure/blob/7765977332818d5f4869ff8ef4919766bcc5a661/terraform/aws/efs.tf#L45-L72) I've followed [the settings of the original one](https://github.com/2i2c-org/infrastructure/blob/7765977332818d5f4869ff8ef4919766bcc5a661/terraform/aws/single-efs-setup.tf#L5-L21), that hadn't had the `encrypt` argument explicitly set to true but for some reason it is enabled.

The `encrypt` argument is optional and probably defaults to false per https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system#argument-reference

We should consider enabling encryption if this is the standard practice.

**Warning:** This is a destructive process, but we have confirmed that no users have used the workshop hub yet, so this is safe to recreate

### Tasklist
```[tasklist]
- [x] check for data in staging EFS that needs to be migrated
- [x] if required, migrate staging data
- [x] encrypt the staging and workshop efs instances
```

### Definition of Done

- [x] Checking the EFS encryption state in the AWS console shows it as encrypted for all EFS

**Comment by yuvipanda** [comment]
Yes, let's definitely do this now before these get much use so all the three filesystems match.

**Comment by yuvipanda** [comment]
workshop hub currently doesn't have active users so if this needs migration that's fine. However we should make sure we don't lose any data.

We should also check to see if this causes recreate issues in other projects.

**Comment by sgibson91** [comment]
I have just confirmed that enabling encryption will force a replacement of the filesystems, so this task will involve migrating any existing data.

We established in the iteration planning meeting that the workshop hub has had no users, so that should be safe to delete/recreate.

**Comment by sgibson91** [comment]
I have started a shell with home dirs mounted using `deployer exec homes`, then I am using `kubectl cp <pod-with-shell>:/home local-dir>` to make a local backup. I can then move the files back after the filestores have been encrypted.
