### ISSUE TITLE
(4/4) [Spike] [1h] Test Grafana datasource by a query from Grafana

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4550]
This is task 4/4 in #4546, which is part of the big epic #4453.

This task is dependent on task 3/4 #4549 has been completed, and completed with a technically positive outcome where we think that the datasource could work as it is.

---

The query below has run successfully from the Amazon Athena query editor UI, with `s3://openscapes-cost-usage-report/athena/` as the "Query result location".

Test using the same query from Grafana to verify that you successfully can work against the added Athena datasource. It may be that this needs to be tweaked, but I'm unable to determine if/how at this point in time.

```sql
SELECT
    line_item_usage_type,
    sum(split_line_item_split_cost) AS "cost"
FROM "athenacurcfn_2i2c_cost_export"."2i2c_cost_export"
WHERE split_line_item_split_cost >0.0
GROUP BY
    line_item_usage_type
```

To run a query, I think the steps are to login to https://grafana.openscapes.2i2c.cloud/ as `admin`, create a testing dashboard, and within it create a testing panel - perhaps of a table type, and declare this as a query for it.

## Definition of done

- [ ] A query was successfully executed against Athena

or

- [ ] You've tried to make it work up at most 1h without success, and then wrote a comment in this issue about it failing and optionally if you have ideas on why.

**Comment by GeorgianaElena** [comment]
With https://github.com/2i2c-org/infrastructure/pull/4620, the query in the top comment ran without throwing any error.

The panel is at https://grafana.openscapes.2i2c.cloud/d/cdusj7n6063nkc/athena-test-query?orgId=1&from=1723612631281&to=1723634231281&viewPanel=1 and below. 

<img width="718" alt="Screenshot 2024-08-14 at 14 20 41" src="https://github.com/user-attachments/assets/e66eb6c9-9a1a-43c3-9e6f-59a240b44a15">
