### ISSUE TITLE
Enable higher limits for  `/dev/shm` for all users

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4563]
Per https://2i2c.freshdesk.com/a/tickets/1943, we learn that GPU users need more shared memory than the default that's made available by containers. We already had this enabled for jupyter-meets-the-earth, and we are enabling this for cryocloud. This has also been needed for linux desktop users.

I don't think there's anything negative in simply enabling this for everyone, as the memory usage enabled by this is accounted for in the memory use of the container as a whole.

We should replicate https://github.com/2i2c-org/infrastructure/pull/4564 in our basehub configuration.

## Definition of done

- [x] `extraVolumes` and `extraVolumeMounts` are set up in basehub to have an entry for `/dev/shm` (same as https://github.com/2i2c-org/infrastructure/pull/4564)
- [x] Any overrides of `extraVolumes` and `extraVolumeMounts` in our config for individual hubs has the added entry for `/dev/shm` replicated
- [x] Any documentation that asks for modifying `extraVolumeMounts` is modified to add the `/dev/shm`
- [x] Test on instance with running `df -h | grep shm` should indicate larger size than 64M

## Future work

https://github.com/jupyterhub/kubespawner/pull/843 will enable us to use dicts for extraVolumes and extraVolumeMounts, so we don't have to copy paste these overrides everywhere.

**Comment by haroldcampbell** [comment]
@jnywong + @yuvipanda  would it be possible to create a blog post related to this issue?

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/meta/issues/1390 is the blog post issue.

**Comment by sgibson91** [comment]
On hub with change rolled out:

![Image](https://github.com/user-attachments/assets/842e7cd4-67d2-43c4-bf06-1da3ddc5f271)

On hub without change rolled out:

![Image](https://github.com/user-attachments/assets/ce0cf3ab-a898-4a53-83d0-d0cf824acbd8)

**Comment by sgibson91** [comment]
I'm running into the below issue trying to get this deployed and I think generally GitHub Actions is having a rough day. I'm seeing messages such as "received request to deprovision".

- https://github.com/2i2c-org/infrastructure/issues/4379
- https://github.com/actions/runner-images/issues/9959
