### ISSUE TITLE
[Aug 9] Regenerate NASA SMCE credentials

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4577]
This is a recurring task that must be done every ~55 days.

AWS credentials for our hub deployer must be renewed for the following clusters:
- [x] Due Aug 9
- [x] NASA VEDA
- [x] GHG Center
- [x] ESDIS

https://github.com/2i2c-org/infrastructure/issues/4285 was the previous time this was done

**Comment by GeorgianaElena** [comment]
Unfortunatelly I can't work on this because my IAM user has expired. I've emailed them to get help with this, but it might take a while.

@sgibson91 has agreed to take this and in return I will work on https://github.com/2i2c-org/infrastructure/issues/4576. Thank you!

**Comment by maxrjones** [comment]
@sgibson91 @yuvipanda I'm having trouble with credentials on the VEDA Hub and am posting it here since it seems like it could be related. The following code worked yesterday on the prod Hub and still works today on the staging Hub, but is failing now on prod with `ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden`. Could you offer guidance on how to get the auth working again?

```
import fsspec
import xarray as xr

with fsspec.open('s3://gesdisc-cumulus-prod-protected/GPM_L3/GPM_3IMERGDE.07/2024/02/3B-DAY-E.MS.MRG.3IMERG.20240211-S000000-E235959.V07B.nc4') as f:
    ds = xr.open_dataset(f)
```

**Comment by maxrjones** [comment]
> @sgibson91 @yuvipanda I'm having trouble with credentials on the VEDA Hub and am posting it here since it seems like it could be related. The following code worked yesterday on the prod Hub and still works today on the staging Hub, but is failing now on prod with `ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden`. Could you offer guidance on how to get the auth working again?
> 
> ```
> import fsspec
> import xarray as xr
> 
> with fsspec.open('s3://gesdisc-cumulus-prod-protected/GPM_L3/GPM_3IMERGDE.07/2024/02/3B-DAY-E.MS.MRG.3IMERG.20240211-S000000-E235959.V07B.nc4') as f:
>     ds = xr.open_dataset(f)
> ```

@sgibson91, nevermind - please ignore this comment because this was entirely a user error. I assumed a different role to be able to write to a bucket, which made me not able to use the magic behind VEDA's data access. Sorry for the noise!
