### ISSUE TITLE
Increase prometheus retention duration to 3 years for all our clusters

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4584]
We initially set our prometheus retention to 1 year. However, since this is also where metrics about usage lie, we've gotten a few requests from communities (including one from cryocloud) to increase that.

Retention is currently set to 366d. Let's set it to 3 years (`1098d`) instead. 

## Definition of done

- [x] Retention config is set to 1098d in two places in the base support chart
- [x] Any retention overrides in specific clusters are discovered, and removed (so everyone gets an even 3y)
- [x] Prometheus servers are actively running on all clusters after this change is made
- [x] New issue is created to check on disk space usage on the prometheus servers a month later

**Comment by sgibson91** [comment]
Clusters checked for running prometheus servers:

- [x] 2i2c
- [ ] 2i2c-aws-us
- [ ] 2i2c-uk
- [ ] awi-ciroh
- [ ] catalystproject-africa
- [ ] catalystproject-latam
- [ ] cloudbank
- [ ] earthscope
- [ ] gridsst
- [ ] hhmi
- [ ] jupyter-health
- [ ] jupyter-meets-the-earth
- [ ] kitware
- [ ] leap
- [ ] linked-earth
- [ ] nasa-cryo
- [ ] nasa-esdis
- [ ] nasa-ghg
- [ ] nasa-veda
- [ ] openscapes
- [ ] opensci
- [ ] pangeo-hubs
- [ ] pchub
- [ ] projectpythia
- [ ] smithsonian
- [ ] ubc-eoas
- [ ] utoronto
- [ ] victor

**Comment by sgibson91** [comment]
New issue opened: https://github.com/2i2c-org/infrastructure/issues/4632
