### ISSUE TITLE
Upgrade jupyterhub-fancy-profiles version on imagebuilding-demo

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4585]
Following on from https://github.com/2i2c-org/infrastructure/issues/4522, we want to upgrade jupyterhub-fancy-profiles on the other two hubs we have it running:

- `imagebuilding-demo`
- sciencecore

The second has users, so let's deploy to the first one!

This would involve replicating the changes from https://github.com/2i2c-org/infrastructure/issues/4522 to the imagebuilding-demo hub config. Since imagebuilding is enabled there (unlike VEDA), you probably also need to intentionally enable dynamic image building - see https://github.com/yuvipanda/jupyterhub-fancy-profiles/pull/58/files#diff-26e325937baab623ebecf944e3691cfc6d509853168cf154a403089ea6a93a1e for what that may look like.

## Definition of done

- [x] Imagebuilding demo hub has new version of jupyterhub-fancy-profiles
- [x] dynamic image building, unlisted choice and selecting an existing image work
- [x] There's another issue opened about upgrading this in the sciencecore hub

**Comment by sgibson91** [comment]
So I haven't applied any changes yet, but already I'm struggling to build an image. I'm not sure if the imagebuilding-demo has restricted repos it can build? I can't see anything specified in config.



![Image](https://github.com/user-attachments/assets/92840c3c-5871-45e3-9b5e-ae64d0716f81)

**Comment by sgibson91** [comment]
I am pretty sure that #4634 covered what is being ask to be done here, but @yuvipanda please ping me if I missed something.

---

I am still receiving the above error trying to use the dynamic image building option. But since it was present before I began any of the work in this issue, I'll close it and open another one with a spike to investigate what's going on here.

The pre-defined images and selecting an existing image both work.

**Comment by sgibson91** [comment]
I'm actually getting the same error message on sciencecore for https://github.com/binder-examples/requirements.... Am I just being really dumb and not using this feature correctly?

**Comment by sgibson91** [comment]
Ok, you're supposed only provide binder-examples/requirements, not the full URL. That is... very counter-intuitive if you're coming from mybinder.org and/or are prone to just copy-pasting URLs.

**Comment by sgibson91** [comment]
Yeah, so dynamic image building works fine

**Comment by sgibson91** [comment]
New issue for sciencecore: https://github.com/2i2c-org/infrastructure/issues/4635

**Comment by yuvipanda** [comment]
I don't see the ability to build images anymore: 

<img width="1068" alt="image" src="https://github.com/user-attachments/assets/03520f3b-6ba5-4f21-b03f-2b1f7b49459a">
