### ISSUE TITLE
Collect billing data for July for all shared clusters

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4587]
Follow instructions in  https://infrastructure.2i2c.org/howto/bill/#communities-with-dedicated-cloud-accounts for dedicated cluster billing for July 2024.

## To investigate

Neurohackedamy has a dedicated nodepool in the 2i2c-aws-us cluster now, so we'll need to account for that. I don't think we had that in AWS before.

## Definition of done

The `#billing` channel is notified after costs have been updated.

This is the `2i2c` and `2i2c-aws-us` clusters.

**Comment by sgibson91** [comment]
I'm having difficulty with neurohackademy's dedicated node pool. If I don't make any edits to the spreadsheet, the total cost verification method works out correctly. If I try to assign all the dedicated user node group costs just to neurohackademy, I end up around $130 short.

**Comment by sgibson91** [comment]
It turns out that my logic is good, but excel isn't very good at updating formulae
