### ISSUE TITLE
Create new cluster and hub issues for NOAA Fisheries

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4682]
We have a new hub on a new AWS org for NOAA Fisheries.

Credentials in https://2i2c.freshdesk.com/a/tickets/2063.

This issue is to track refining creating new hub issues for this.

## Definition of done

- [x] The request is acknowledged in freshdesk
- [ ] New hub issues are created and refined

**Comment by yuvipanda** [comment]
Based on prior other discussion with openscapes, this should basically match the openscapes config. No workshop hub.

**Comment by yuvipanda** [comment]
I dug through my emails for a deadline, and found 'second week of september as soft launch target'. Internally that means I'd set us a Sep 5 deadline, so this gets completed this coming sprint.

**Comment by consideRatio** [comment]
I've opened and preliminary refined:
- https://github.com/2i2c-org/infrastructure/issues/4690
- https://github.com/2i2c-org/infrastructure/issues/4696
- https://github.com/2i2c-org/infrastructure/issues/4697

Further refinment is required for them to be ready, and that is blocked by a response to my message in https://2i2c.freshdesk.com/a/tickets/2063.

**Comment by consideRatio** [comment]
Some final details to be locked in remains, but this is mostly done now and pending response about details in https://2i2c.freshdesk.com/a/tickets/2063.

**Comment by consideRatio** [comment]
(I set the status of this as unplanned)

**Comment by consideRatio** [comment]
With help from @sgibson91 to followup on the final detail, this is completed.
