### ISSUE TITLE
[New Hub] [Phase 1] [5th Sep deadline] Cloud Account Setup - nmfs-openscapes

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4690]
### What is the 'ready to work' status of this phase?

READY

## Important

The AWS account itself is already setup us, so we don't create it - but, we should still do various things such as providing 2i2c engineers access etc as part of [the runbook](https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase1/#available-runbooks).

Currently, the community isn't setup in airtable. Yuvi asks that its added into airtable by the person performing this task. I'll clarify who is a community champion and authorized technical contact, and this issue is blocked on that atm.

## Default template

This phase is applicable for cases where a community is being setup on a
dedicated cluster. The following table lists the information that must
be provided before this phase can be marked as READY and begin.
Use the Notes column to provide any other contextual information.

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Cloud Provider | `AWS` | |
| Will 2i2c pay for cloud costs? | `No` | |
| Name of cloud account | nmfs-openscapes | https://891612562472.signin.aws.amazon.com/console |
| Have the Community been defined in [AirTable](https://airtable.com/appbjBTRIbgRiElkr/tblYGygEo5PQBSUYt/viw2HbovmDNUzCCKx)? | `No`, but should be | Please figure out how to add the community "NMFS Openscapes" into airtable, along with Andy and Julia as community reps and authorized techical contacts (aka. support requesters) |
| Community Representatives | `andy` and `julia`, using a `@openscapes.org` email | Andy Teucher is `ateucher` on github, Julia Stewart Lowndes is `jules32` on github - they are presumed by Erik to be both community reps and technical contacts |
| Have the Technical Contacts been added to the [AirTable](https://airtable.com/appbjBTRIbgRiElkr/pagD3XyZjqBunYMnC)? | `No`, but should be | Please add and Andy and Julia! |

Available runbooks:
- https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase1/#available-runbooks

**Comment by consideRatio** [comment]
Blocked by question to Yuvi at slack on defining the community in airtable: https://github.com/2i2c-org/infrastructure/issues/4690

**Comment by sgibson91** [comment]
- New IAM accounts have been created for engineers and passwords distributed
- Information has been added to AirTable
