### ISSUE TITLE
[New Hub] [Phase 2] [11th Sep deadline] Cluster Setup - nmfs-openscapes

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4696]
<details><summary>Issue unrelated priority wish</summary>

If https://github.com/2i2c-org/infrastructure/issues/4711 and https://github.com/2i2c-org/infrastructure/issues/4710 could be done before than this, it would help work in cost allocation efforts, as this setup then would be a setup properly tagged AWS resources for cost tracking purposes.</details>

### What is the 'ready to work' status of this phase?

READY

### Required information for setting up a cluster for a new community or a set of communities.

This phase assumes all engineers have access to the relevant account,
and will be able to set up the cluster + support without issue. No hubs
are to be deployed during this phase. The following table lists the
information that must be provided before this phase can be marked as
READY and begin. Use the Notes column to provide any other contextual
information.

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Region/Zone of the cluster | `us-west-2` | They have mentioned aws-west-2, but they mean AWS region us-west-2 |
| Name of the cluster | `nmfs-openscapes` | |
| Are GPUs required? | `No` | Based on openscapes being setup like that, as suggested via https://github.com/2i2c-org/infrastructure/issues/4682#issuecomment-2310691491 |

Available runbooks:
- https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase2/
- https://infrastructure.2i2c.org/hub-deployment-guide/deploy-support/

**Comment by sgibson91** [comment]
Confirmed in Freshdesk that the desired region is **aws-west-2**

**Comment by haroldcampbell** [comment]
@sgibson91 please link the FreshDesk ticket

**Comment by sgibson91** [comment]
https://2i2c.freshdesk.com/a/tickets/2063

**Comment by consideRatio** [comment]
I realize it wasn't clear if we should mimic openscapes infra with dedicated node pools for staging/prod and dedicated EFS storage for staging/prod etc, as was introduced for cost allocation.

It was clear we should look at openscapes when setting this up, so I've went with that choice now.
