### ISSUE TITLE
terraform, aws: add `2i2c:hub-name` tags to buckets

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4710]
- Check if existing buckets can be updated with tags via terraform, if it is, then that is a requirement for this issue to be done.
  EDIT: buckets tag can get updated with tags easily, anything in terraform can!

- Try to mix in the tag `2i2c:hub-name` into other tags applied to buckets in some way.

  How isn't obvious, because the `user_buckets` variable isn't directly tied to a hub - maybe we need to be more explicit about it though and listing that? I'm not sure - its part of this issue to figure out what is a reasonable path forward to still tag each bucket with `2i2c:hub-name=one-hub-name`

## Definition of done

- [x] It's determined if we can update existing buckets with tags
  We can!
- [ ] Terraform files are adjusted so that new hubs don't risk not getting the `2i2c:hub-name` tag set on their new buckets

**Comment by yuvipanda** [comment]
We moved this back to 'up next' because it is unclear what the target of this is. I see those tags are already applied for openscapes.

**Comment by consideRatio** [comment]
The target is to ensure its easy to retroactively enable cost attribution in our AWS clusters, by in the context of buckets getting them attributed to a specific hub automatically.

**Comment by consideRatio** [comment]
Its not straightforward to get this done though, so maybe having this explicitly set is the way to go.

I'll go for a close now since I no longer think getting it done automatic is the way to go, which this issue was written assuming it was.
