### ISSUE TITLE
Cost Explorer API (7/n): come up with strategy on how to account costs in openscapes and new AWS clusters respectively

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4712]
I've discussed with Yuvi about 2i2c:hub-name tag not capturing much costs (~30 USD / month out of ~1k) in a Erik/Yuvi 1on1. For a new hub setup where we think we have all AWS resources tagged with wanted tags (#4711), we can have one strategy on providing a graph, but the strategy we provide for openscapes must be adjusted as we don't have all relevant tags there.

Yuvi's guidance was that we are to proceed with solving this for openscapes as well as for new hubs, where openscapes may need additional patch work.

## Definition of done

- A strategy on how to account such costs for openscapes is provided
~~- A strategy on how to account such costs for future very thoroughly tagged hubs is provided~~

**Comment by haroldcampbell** [comment]
Moving the "A strategy on how to account such costs for future very thoroughly tagged hubs is provided" goal to a separate issue.

**Comment by consideRatio** [comment]
I've ended up also doing the removed goal, the strategies for openscapes and future clusters aligned well enough with some tweaks that I simply felt it was too much wasted time not to think of the future already.

**Comment by consideRatio** [comment]
With https://github.com/2i2c-org/infrastructure/issues/4453#issuecomment-2334552406, I consider this completed!
