### ISSUE TITLE
Do cloud cost reporting for August

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4721]
To be refined by someone else.

 
- [ ] For GCP dedicated projects
- [ ] For AWS dedicated projects
- [ ] For GCP shared cluster
- [ ] For AWS shared cluster

**Comment by GeorgianaElena** [comment]
Closing this in favour of https://github.com/2i2c-org/infrastructure/issues/4732 and https://github.com/2i2c-org/infrastructure/issues/4733
