### ISSUE TITLE
[devseed] Setup chartpress for jupyterhub-home-nfs helm chart

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4725]
Chartpress (https://github.com/jupyterhub/chartpress) is a tool for automatically building and publishing helm charts and their images. We should set up this automation for the jupyterhub-home-nfs project.

### Definition of Done

- [ ] jupyterhub-home-nfs can successfully use chartpress to automatically build and publish the helm chart

**Comment by sunu** [comment]
https://github.com/sunu/jupyter-home-nfs is now configured to build and publish docker images and helm chart using chartpress.
