### ISSUE TITLE
[devseed] `jupyterhub-home-nfs` is enabled for VEDA's staging hub

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4727]
Enable jupyterhub-home-nfs for VEDA staging hub so that the AWS EBS volume is created ready for data migration. We should also set some reasonable quotas here considering the staging hub will not be heavily used.

### Definition of Done

- [ ] The jupyterhub-home-nfs helm chart is enabled and successfully deployed for the VEDA staging hub
- [ ] An EBS volume exists ready for data migration
- [ ] Some reasonable quotas are set on the storage

**Comment by sunu** [comment]
@sgibson91 Just to clarify, we purposefully don't use dynamic storage provisioning in the jupyterhub-home-nfs helm chart to make sure we can reuse the same disk even when all state within the k8s cluster is lost (like if we have to delete and recreate the cluster).

So, the helm chart expects a pre-provisioned disk. We will have to create the AWS EBS volume ourselves and provide a reference to it to the helm chart. The EBS volume won't be created automatically by the helm chart.

**Comment by sgibson91** [comment]
Thank you for that ontext @sunu! In which case, I have opened https://github.com/2i2c-org/infrastructure/issues/4735 and updated https://github.com/2i2c-org/infrastructure/issues/4729 That update rolls a lot of what was refined here into that issue, so I think we can close this one.
