### ISSUE TITLE
Team policy for sharing access to GCP, Azure, and AWS projects

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#475]
### Description

We should define team practices in this repository for tracking which Cloud Projects we have access to, and to ensure that team members are able to access these resources themselves.

We have some information [in this google sheet](https://docs.google.com/spreadsheets/d/1NSaAKLG2_njXxs6JlGUAhSWeHONz9QSGLVwEK790IZo/edit#gid=0), but it isn't easily discoverable from our DevOps docs. We should update that sheet, potentially make it specific to Cloud Vendor projects/accounts, and document it in our DevOps guide.

Ref: https://github.com/2i2c-org/team-compass/issues/116#issuecomment-863446240

### Benefit

Centralizing this information and putting it in the DevOps guide should make it more "top of mind", since we already have our list of running hubs there, it seems natural that a reference for running _projects_ (or accounts, etc) would be there as well.

### Implementation details

I think that this could be done by the following actions:

- [ ] Remove the `User accounts` tab from [this google sheet](https://docs.google.com/spreadsheets/d/1NSaAKLG2_njXxs6JlGUAhSWeHONz9QSGLVwEK790IZo/edit#gid=0) and put it into a Bitwarden account that we can use to share credentails for single accounts (see #17)
- [ ] Re-brand that sheet as "Cloud Projects / Accounts we manage" and make sure it is updated
- [ ] Move the documentation about this from `team-compass` to `pilot-hubs`
- [ ] Figure out if / how this relates to other documentation we might have around secrets
- [ ] Make sure there's a section in our onboarding docs about how to access these accounts

More generally, I wonder if it would be possible to find mechanisms in each cloud provider to control these resources at a *group* level, so that our onboard could just be "add this person to group X in GCP, Y in Azure, and Z in AWS" and they'd get access to these projects automatically.

edit: this issue was co-opted by @choldgraf to expand its scope a bit and add more details

**Comment by yuvipanda** [comment]
> I am thinking about putting all the access keys in some encrypted file in the repo, thoughts?

What do you think of using https://cloud.google.com/secret-manager under the two-eye-two-see-org GCP project as a password manager?



> Btw, the Azure story is not clear to me neither... can somebody drop some lights there 😉

Currently we only manage utoronto for Azure, and access is managed by IT there...

**Comment by damianavila** [comment]
> What do you think of using https://cloud.google.com/secret-manager under the two-eye-two-see-org GCP project as a password manager?

I guess we can try it... it feels a little bit weird to put AWS credentials in GCP stuff... well, actually, it is fun :wink: !

> Currently we only manage utoronto for Azure, and access is managed by IT there...

Got it! cc/ @sgibson91

**Comment by choldgraf** [comment]
After https://github.com/2i2c-org/pilot-hubs/issues/708 I decided to update this issue a bit and clarify some next steps to take. I'll add it to our team process backlog so that we can focus efforts on sorting this one out. I hope my edits are acceptable to you @damianavila !
