### ISSUE TITLE
Transition to r7i instances from r5 instances

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4750]
The r7i (i as in intel, previously omitted) is a step up from r6 instances, which is a step up from r5 instances.

- Going from r5 to r6 is said to increase performance with 15%, and the prices are the same.
- Going from r6 to r7i is said to increase price performance with 15% (the price increased with 5%).
- Use of r7i is detailed to provide a 25% higher networking speed limit
- Use of r7i is said to be more network performant

I propose we default to using r7i going onward, and phase that in instead of our r5 machines. We can do this in the next k8s upgrade with little extra effort besides specifying that instead of specifying r5 when re-creating node pools.

## Definition of done

- [x] New clusters defaulting to r7i machines instead of r5 machines.
  #4751
- [ ] (optional) All existing clusters prepared somehow to transition to use r7i instead of r5 machines in next k8s upgrade
- [ ] All existing clusters setup to transition to use r7i instead of r5 machines

## References

- [AWS R5 Docs](https://aws.amazon.com/ec2/instance-types/r5/)
- [AWS R6 Docs](https://aws.amazon.com/ec2/instance-types/r6/)
- [AWS R7i Docs](https://aws.amazon.com/ec2/instance-types/r7i/)

**Comment by yuvipanda** [comment]
We have a lot of other current initiatives in the air, so let's keep this simple and not actually work on this right now. I want us to keep our focus and deliver on the major initiatives we are doing right now, and not get too side tracked. I think for now,

1. [This PR](https://github.com/2i2c-org/infrastructure/pull/4751) needs to be reverted, so we don't have a mixed set of instance sizes
2. If there's any hub that's using this, that also needs to be changed back to the previous standard.

**Comment by yuvipanda** [comment]
I created https://github.com/2i2c-org/infrastructure/issues/4817 to track the work in reverting this.
