### ISSUE TITLE
Add cert-manager upgrade to our recurring internal engineering tasks calendar

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4763]
I propose we schedule the following task recurringly:

## Goal

Get cert-manager updated from time to time, for example every six months.

## Recurring task

- Check the hardcoded version in the deployer:
  https://github.com/2i2c-org/infrastructure/blob/724fefeaa0e1432d5e437cd261004c5f3d711a5f/deployer/commands/deployer.py#L69-L76
- Read cert-managers release notes and upgrade steps to upgrade to the next minor version at https://cert-manager.io/docs/release-notes/
- Get all our deployments version of cert manager upgraded to the latest version.
  Note that to get a `deployer deploy-support` to run on all clusters without extra things, you can do a simple change like in #4766, where you add the labels `deployer:skip-deploy-hubs` and `deployer:deploy-support`.

**Comment by yuvipanda** [comment]
This should be rolled into the support upgrade process: https://github.com/2i2c-org/infrastructure/issues/4684
