### ISSUE TITLE
[16 Dec] Check disk space of Prometheus servers for each cluster

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4813]
### Context

We are regularly checking the disk space of our prometheus servers for each cluster to monitor them running out of disk space.

Use [grafana](https://grafana.pilot.2i2c.cloud/d/d560fa89-38bc-4253-964e-82573ea91d57/global-prometheus-health?orgId=1) to establish how much disk space each prometheus server has left. You can then you [this spreadsheet](https://docs.google.com/spreadsheets/d/1zTpIHlCKVjoL4vij_y6bPVUWmsYL-NDB66nXzM1FqDk/edit?usp=sharing) to establish if the disk size should be increased or not.

### Definition of Done

- [x] Each cluster's prometheus server has been checked for disk space
- [ ] Any servers running low on space have had their disks expanded

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by jnywong** [comment]
Sarah and I took a quick look today and everything looks good. I will open another issue to remind us to check again in 3 month's time.

![Image](https://github.com/user-attachments/assets/54c57ee4-6fa1-4aae-a4e3-52a1ca021efa)
