### ISSUE TITLE
[New Hub] [Phase 2] Cluster Setup - Queens University

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#4823]
### What is the 'ready to work' status of this phase?

READY

Depends on 
- https://github.com/2i2c-org/infrastructure/issues/4822

### Required information for setting up a cluster for a new community or a set of communities.

Due date for hub deployment: Sep 30, 2024

This phase assumes all engineers have access to the relevant account,
and will be able to set up the cluster + support without issue. No hubs
are to be deployed during this phase. The following table lists the
information that must be provided before this phase can be marked as
READY and begin. Use the Notes column to provide any other contextual
information.

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Region/Zone of the cluster | `canadacentral` | Same region as UToronto |
| Name of the cluster | `queensu` | |
| Are GPUs required? | `No` | |

Available runbooks:
- https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase2/
- https://infrastructure.2i2c.org/hub-deployment-guide/deploy-support/
```[tasklist]
### Tasks
- [ ] Deploy AKS
- [ ] Refine https://github.com/2i2c-org/infrastructure/issues/4824 (Hub Turnup Phase 3)
```

**Comment by haroldcampbell** [comment]
There is higher risk since we are deploying in their cloud

**Comment by sgibson91** [comment]
I am down to only one error, but I have no idea how to solve it
