### ISSUE TITLE
[New Hub] [Phase 1] Cloud Account Setup - dubois 

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#4825]
### What is the 'ready to work' status of this phase?

READY

### Required information for setting up a cloud account for a new community on a dedicated cluster.

Context:

_Software Service for W.E.B Dubois Data Visualization Project at U.C. Merced. An Education Hub with ephemeral home director storage for your community, running on a dedicated cluster. Period of performance: From 2024-09-01 until 2025-06-30._

If a 'shared' deployment is an option, we might be able to skip this step of the turn up.  Should we deploy this on either `2i2c` or `2i2c-aws-us` since those cluster already have shared ephemeral hubs?

**This is _separate_ from our existing UCMerced deployment is to be billed independently.**

This phase is applicable for cases where a community is being setup on a
dedicated cluster. The following table lists the information that must
be provided before this phase can be marked as READY and begin.
Use the Notes column to provide any other contextual information.

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Cloud Provider |AWS/GCP | I don't think there is a preference here from the community. |
| Will 2i2c pay for cloud costs? | Yes | |
| Name of cloud account | | |
| Community Representative(s) (GitHub handles or email) | | |
| Have the Technical Contacts been added to the [AirTable](https://airtable.com/appbjBTRIbgRiElkr/pagD3XyZjqBunYMnC)? | `Yes/No` | |

Available runbooks:
- https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase1/#available-runbooks

**Comment by haroldcampbell** [comment]
Additional context from @jmunroe 
- The team needs to make a recommendation regarding the cluster. 
- There isn't a large dataset.
- @jmunroe feels like this could live on the 2i2c AWS shared cluster, unless there is a good reason to do otherwise. The Eng team can make the call to make the final decision.
- The request is to have this deployed soonest.

**Comment by haroldcampbell** [comment]
@haroldcampbell  with pair with someone from Eng to update AirTable

**Comment by sgibson91** [comment]
Yuvi said during the sprint planning meeting that a shared cluster is not permissible, so we will be setting up a new AWS account. I'm guessing under our SSO org and we will pass-through cloud costs.

- https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase1/new-aws-account/

**Comment by sgibson91** [comment]
I have created a project called `ucmerced-dubois` on GCP.

@jmunroe should I copy the current UCMerced technical contacts in AirTable for this deployment, or are there any new contacts I need to know about?

**Comment by jmunroe** [comment]
UCMerced is a completely separate and independent from this dubois project. The only technical should be Charlie Eaton.

**Comment by sgibson91** [comment]
In light of that, the project is now just called `dubois`.

**Comment by sgibson91** [comment]
I have added Charlie to AirTable using the _AWESOME_ "Add Contact" button @haroldcampbell added this morning ❤ 

That entry still needs to be linked to hubs `dubois:staging` and `dubois:prod` as Harold continues to debug and improve that feature.

**Comment by haroldcampbell** [comment]
I've updated the form the make the Authorized Support Initiator a require field. Without this information the hubs don't get pulled in automatically.
