### ISSUE TITLE
[New Hub] [Phase 2] Cluster Setup - dubois

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#4826]
### What is the 'ready to work' status of this phase?

Depends on
- https://github.com/2i2c-org/infrastructure/issues/4825

If a _shared_ cluster is an option here (see #4825) then we can skip this step of the turn up.

READY

### Required information for setting up a cluster for a new community or a set of communities.

This phase assumes all engineers have access to the relevant account,
and will be able to set up the cluster + support without issue. No hubs
are to be deployed during this phase. The following table lists the
information that must be provided before this phase can be marked as
READY and begin. Use the Notes column to provide any other contextual
information.

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Region/Zone of the cluster | `us-central1` | |
| Name of the cluster | `dubois` | |
| Are GPUs required? | `No` | |

Available runbooks:
- https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase2/
- https://infrastructure.2i2c.org/hub-deployment-guide/deploy-support/
```[tasklist]
### Tasks
- [x] Refine https://github.com/2i2c-org/infrastructure/issues/4827 once cluster info has been determined
```

**Comment by sgibson91** [comment]
Since we have not gone the shared cluster route, I am going to recommend some options to fill in the table here:

- Region/zone: `us-central1`
- Cluster name: `dubois`
- GPUs? `No`
