### ISSUE TITLE
[New Hub] [Phase 2] Cluster Setup - strudel

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#4830]
### What is the 'ready to work' status of this phase?

READY

### Required information for setting up a cluster for a new community or a set of communities.

Depends on
- https://github.com/2i2c-org/infrastructure/issues/4829

This phase assumes all engineers have access to the relevant account,
and will be able to set up the cluster + support without issue. No hubs
are to be deployed during this phase. The following table lists the
information that must be provided before this phase can be marked as
READY and begin. Use the Notes column to provide any other contextual
information.

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Region/Zone of the cluster | `us-west2` | Under 2i2c SSO|
| Name of the cluster | `strudel` | |
| Are GPUs required? | `No` | |

Available runbooks:
- https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase2/
- https://infrastructure.2i2c.org/hub-deployment-guide/deploy-support/

**Comment by sgibson91** [comment]
- AWS, us-west2 SSO subproject
- No GPUs
