### ISSUE TITLE
AWS cost attribution (2a/4): deploy to nasa-cryo

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4874]
By following the docs from #4873, deploy the cost attribution system to the nasa-cryo cluster.

## Definition of done

- [x] https://grafana.cryointhecloud.2i2c.cloud/ has a dashboard available
- [x] Any relevant documentation updates have been made, or an issue capturing that has been opened and refined to be scheduled as a followup

**Comment by sgibson91** [comment]
https://infrastructure.2i2c.org/howto/cost-attribution/

**Comment by sgibson91** [comment]
Should I be creating hub-specific node groups for nasa-cryo?

**Comment by sgibson91** [comment]
This is now unblocked as we'll just deploy to another cluster, as decided on slack. Let's go for nasa-veda.

**Comment by sgibson91** [comment]
VEDA has the same issue. On Monday, I'll try with earthscope.

**Comment by sgibson91** [comment]
I'm getting a warning about a deprecated argument which I'll ignore for now in favour of just getting another deployment rolled out.

```
│ Warning: Argument is deprecated
│ 
│   with aws_iam_role.aws_ce_grafana_backend_iam_role,
│   on aws-ce-grafana-backend-iam.tf line 2, in resource "aws_iam_role" "aws_ce_grafana_backend_iam_role":
│    2: resource "aws_iam_role" "aws_ce_grafana_backend_iam_role" {
│ 
│ The inline_policy argument is deprecated. Use the aws_iam_role_policy resource instead. If Terraform should exclusively manage all inline policy associations (the current behavior of
│ this argument), use the aws_iam_role_policies_exclusive resource as well.
```

**Comment by sgibson91** [comment]
Nope, earthscope is linked too. I'm officially calling this blocked.

```
│ Error: updating Cost Explorer Cost Allocation Tag (alpha.eksctl.io/cluster-name): operation error Cost Explorer: UpdateCostAllocationTagsStatus, https response error StatusCode: 400, RequestID: bfd27b73-b16a-4040-9771-dec05e88b6d5, api error AccessDeniedException: Failed to update Cost Allocation Tag: Linked account doesn't have access to cost allocation tags.
```
