### ISSUE TITLE
AWS cost attribution (4/4): communicate about the functionality via a blog post and share it with the communities

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4879]
Now that we have a cost attribution strategy and UI, we want to make sure the out communities know about it. We should write a blog post highlighting the background to this work - how it addresses one of the more pressing concerns for hub admins, managing to keep a handle on runaway costs - some of the functional highlights, and showing off some of the UI.

- [x] @consideRatio  to get together with @jnywong to help her download the most important functional and technical highlights
- [ ] @jnywong to write and publish a blog post showing off the new functionality.
- [ ] Amplify the post on linkedin and other socials.

**Comment by haroldcampbell** [comment]
There is a dependency on feedback from the community on the work that we previously released.

**Comment by Gman0909** [comment]
@haroldcampbell please check if this is sufficiently refined

**Comment by jnywong** [comment]
Thanks for the knowledge exchange @consideRatio ! 

I will queue this piece of work up into my next sprint and reach out to you if I have any further questions.
