### ISSUE TITLE
[Support] dirsize-reporter lags for some dirs on nasa-cryo

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#4882]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/2186

### Ticket request type

Something is not working

### Ticket impact

🟨 Medium

### Short ticket description

The [Grafana dashboard of nasa-cryo that is showing the home directory size](https://grafana.cryointhecloud.2i2c.cloud/d/688c04dba0500904/home-directory-usage-dashboard?orgId=1) is not reporting accurate data for some users.

`tsnow03` and `jdmillstei` should have GB of data and instead it is reported as MB of data.

### (Optional) Investigation results

- The last time the size of the home directories for `tsnow03` and `jdmillstei` was 1y, respectively 2y ago according to Grafana
- I checked and their directories and they don't contain anything with odd permissions that would make the reported skip them
- More users shows dirsize values that were last updated a long time ago. This is also happening on other clusters as well
- The dirseize-reported node doesn't show any logs because  --enable-detailed-processing-time-metric is not passed to the command. Maybe we should temp enable it and see what info it shows
- A describe of the `shared-dirsize-metrics` pod in nasa-cryo shows that was recently oom killed and it has ~100 pod restarts. This is related to what @consideRatio has noticed in https://github.com/2i2c-org/infrastructure/issues/2950.
```
 Last State:     Terminated
 Reason:       OOMKilled
  Exit Code:    137
```

Maybe the pod gets killed and doesn't manage to get through all of the directories, hence the outdated data? This needs to be verified and we should consider increasing the pods' available metric.

**Comment by consideRatio** [comment]
I think you are spot on with:

> Maybe the pod gets killed and doesn't manage to get through all of the directories, hence the outdated data?

**Comment by yuvipanda** [comment]
I think we should increase the memory limit / request here until it works again.

**Comment by consideRatio** [comment]
Pending verification of not crashing now after #4945 is merged. I think it requires several hours but not more than a day to know it works.

A confirmation can be done by looking at https://grafana.cryointhecloud.2i2c.cloud/d/688c04dba0500904/home-directory-usage-dashboard?orgId=1, where tsnow03 should have more than 10Mb of usage reported, and the shared-dirsize-metrics pod in `prod` shouldn't have a restart observed.

**Comment by consideRatio** [comment]
While it doesn't go OOM, it doesn't work either.

In nasa-cryo it seems to use more and more memory and then manages to garbage collect a bit. Here is the change after going from 256Mi limit to 512Mi limit.

![Image](https://github.com/user-attachments/assets/49dbd05a-55da-44cc-a661-ecc3564bd7f4)

**Comment by consideRatio** [comment]
This is now reporting correctly, but it took a lot of hours - I think more than hours actually.

![Image](https://github.com/user-attachments/assets/1bff4bb3-9962-4c74-aa3a-f3b90b3612cf)

**Comment by consideRatio** [comment]
I responded in freshdesk as well, closing as completed.
