### ISSUE TITLE
[Oct 14] Move jupyterhub-home-nfs into the 2i2c-org GitHub repo

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4888]
In https://github.com/sunu/jupyter-home-nfs/issues/2, we agreed to move the jupyter-home-nfs project (which provides per-user home directory quotas) into the 2i2c-org GitHub org. This ticket is to make that actually happen.

## Definition of done

- [ ] Repository has been moved into the 2i2c-org

**Comment by sgibson91** [comment]
Hey @sunu - I remember you said you were OOO at the beginning of Oct. Since this issue requires us to coordinate a little, can you recommend a date we can do this?

**Comment by sunu** [comment]
Hi @sgibson91, yes, I'll be OOO from tomorrow and all of next week. We can do the move on Monday 14th October if that works for you.

**Comment by sgibson91** [comment]
The project is now in the 2i2c GitHub org! 🎉 https://github.com/2i2c-org/jupyter-home-nfs
