### ISSUE TITLE
[Spike] Refine strudel phase 2 and phase 3

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4890]
We want to set up a hub for strudel, but the new hub issues are not actually filled up with enough information for Engineering to work on.

Historically, this has been me talking directly to partnerships, researching, or talking to the community to figure it out.

This spike is to have someone other than me do it and fill out phase 2 and phase 3 of strudel.

## Definition of Done

- [x] Phase 2 of Strudel new hub is refined and marked as ready
- [ ] Phase 3 of Strudel new hub is refined and marked as ready

**Comment by colliand** [comment]
FYI. I copy paste from the STRUDEL running notes:

GitHub organization
https://github.com/strudel-science
https://github.com/orgs/strudel-science/teams
