### ISSUE TITLE
Add 2i2c staff as admins to all hubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#49]
### Summary

Currently, we must manually add 2i2c engineers as "admin users" for all of the hubs that we deploy. For example, here we manually list these users:

https://github.com/2i2c-org/pilot-hubs/blob/master/config/hubs/2i2c.cluster.yaml#L93

Instead of this, we should have a *single list of 2i2c Engineers* and automatically add this list as admins on all of our hubs.

### Value

This would de-duplicate information across our hub configuration, and reduce the amount of toil that is needed to add new admins to hubs.

### Tasks to complete

- [ ] Patch the deploy script the "hacky way" to do this, even though we know this would be best done in upstream improvements
- [ ] Open an issue in JupyterHub to ask about best practices around this topic (potentially just pointing to @GeorgianaElena's issue here if that covers all we need to do: https://github.com/jupyterhub/jupyterhub/issues/3525)

**Comment by choldgraf** [comment]
Setting this one to medium priority since it's more of a "improve our practices in general" thing rather than a mission-critical improvement

**Comment by choldgraf** [comment]
A few next steps on this one:

- Patch the deploy script the "hacky way", even though we know this would be best done in upstream improvements
- Open an issue in JupyterHubland to ask about best practices around this topic (potentially just pointing to @GeorgianaElena's issue here: https://github.com/jupyterhub/jupyterhub/issues/3525)
