### ISSUE TITLE
AWS cost attribution (feedback 1): Distinguish total AWS account cost from the 2i2c cluster attributed costs

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4925]
`aws-ce-grafana-backend` currently reports only the costs we confidently say are associated with 2i2c managed cloud resources in the AWS account, but we know we miss out on small things.

Due to that, it would be good to show the total AWS account cost as well. For an AWS account untouched by the community, the difference should be costs not successfully attributed as 2i2c costs.

## Definition of done

- `aws-ce-grafana-backend` provides total cost data in some way
- The cost attribution dashboard is able to present the total AWS account cost separate from the 2i2c attributable costs in some way that makes sense

**Comment by consideRatio** [comment]
@Gman0909 @jnywong the total costs panel is now distinguishing total account costs from total attributable costs, where the attributable costs represents almost all costs associated with 2i2c activity in a community's cloud account - but not exactly everything.

An example of a cost not captured by looking at tags as cloud infrastrucutre is use of the Cost Explorer API - it could have been used by us to present cost info in grafana or it could have been used by someone else, and we cant distinguish that by using a AWS tag like we do for everything else.

![Image](https://github.com/user-attachments/assets/80c58550-323f-474d-9170-09503f453713)

**Comment by jnywong** [comment]
Wow that's a great job!
