### ISSUE TITLE
AWS cost attribution (2c.2/4): [Spike 2h] Figure out how to define an infinity query variable

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#4944]
See https://github.com/2i2c-org/infrastructure/pull/4934#issuecomment-2393608154 for context 

### Definition of Done
- [x] there are panels of cost per component per hub correctly being rendered
- [x] there is a variable defined in grafonnet, similar to the one created by hand in the openscapes grafana

![Image](https://github.com/user-attachments/assets/67a3a8c3-4dd9-42c9-9ffe-9bd15773606e)

**Comment by consideRatio** [comment]
As part of going for this, I went for https://github.com/jupyterhub/grafana-dashboards/pull/142 as the grafonnet docs are only available for that version, and I also didn't want to invest time exploring whats available in an older version when it could boil down to needing the new version.

**Comment by consideRatio** [comment]
For things to work properly, we actually needed grafonnet v11.1.0, so I figure I want to verify things work after we have https://github.com/jupyterhub/grafana-dashboards/pull/142.

**Comment by consideRatio** [comment]
Verified success!
