### ISSUE TITLE
AWS cost attribution: documentation about opting in to have hub specific infra for compute and home storage

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#5000]
## Historical context

In https://github.com/2i2c-org/infrastructure/issues/4928#issuecomment-2417091407, it was decided to not split compute or home storage per hub as part of aws cost allocation cluster rollout tracked by https://github.com/2i2c-org/infrastructure/issues/4878.

Currently this split has only happened for:
- [x] openscapes
- [ ] partly for victor: nodepools were split, but not home storage 

### 1. Splitting the nodegroups and home storage of existing clusters is not a simple operation and requires care.

We don't have documentation about this, but the following issues can serve as guidelines on what needs to have for _all_ clusters:
- https://github.com/2i2c-org/infrastructure/issues/4482
- https://github.com/2i2c-org/infrastructure/issues/4485
- https://github.com/2i2c-org/infrastructure/issues/4461
- https://github.com/2i2c-org/infrastructure/issues/4475
- https://github.com/2i2c-org/infrastructure/issues/4464

### 2. Splitting nodegroups per hub will be less cost efficient and will increase the average startup time

Hubs will not share nodes anymore, which means node packing will be less efficient and there might be more users on average waiting for a new node to come up than before.

## Proposal

Splitting the compute and home storage cost per hub is presented as an opt-in feature to communities and we only do it for 
new and **existing** communities that explicitly request it.

## Definition of Done
```[tasklist]
- [ ] get feedback on the proposal above from @yuvipanda 
- [ ] create **community facing documentation** about the pros and cons of having compute and home storage cost split per hub
- [ ] create **engineering facing documentation** about how to split compute and home storage cost per hub
```

**Comment by GeorgianaElena** [comment]
I've refined this and added it to the refined column on the P&S board

**Comment by GeorgianaElena** [comment]
Closing this in favor of #5074 #5075, #5077, #5078
