### ISSUE TITLE
Coalesce daskhub into basehub

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#502]
# Background

We currently have two Helm charts - `basehub` and `daskhub`. But, what if someone wants another Helm chart installed, such as [`jupyterhub-ssh`](https://github.com/yuvipanda/jupyterhub-ssh) etc? It would be unsustainable to create more Helm charts for each permutation of these needs.

I think a single custom Helm chart, like basehub, can be extended to cover all our needs with dependency charts. I think so as the chart is just a combination of things listed below that can be fully controlled via passed values. Each installation of a Helm chart have control over values, and indirectly everything!
- default values
- listed dependencies - where we have the freedom to have them enabled/disabled by values [thanks to `tags` and `condition`](https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags).
- custom templates - where we have the freedom to have them enabled/disabled by values

# Value outcomes

- JMTE could add `jupyterhub-ssh` as a opt-in chart dependency without needing to fork away further.
- 2i2c pilot-hubs could handle needs like JMTE's better in the future where another Helm chart is wanted as a dependency for some hubs but not all.

# Expected timeline

I'm very unsure. It could take a while as lots of 2i2c hubs would be influenced on a technical level.

# Thoughts of the scope of work I can contribute with

I consider this to be quite 2i2c specific and that it would be out of scope for me to drive this change for all 2i2c deployments with my JMTE based funding. I suggest that I contribute with review rather than driving this change all the way to completion.

# Steps to complete this goal

- [ ] Prerequisite: we evaluate if this is a reasonable strategy and worth going for.
- [ ] We coalesce the daskhub Helm chart into the basehub Helm chart, making the dask-gateway Helm chart dependency listed in Chart.yaml an opt in dependency.

**Comment by yuvipanda** [comment]
Thanks for opening this. See https://github.com/2i2c-org/pilot-hubs/issues/362 for some more info.

> # Background
> 
> We currently have two Helm charts - `basehub` and `daskhub`. But, what if someone wants another Helm chart installed, such as [`jupyterhub-ssh`](https://github.com/yuvipanda/jupyterhub-ssh) etc? It would be unsustainable to create more Helm charts for each permutation of these needs.
> 
> I think a single custom Helm chart, like basehub, can be extended to cover all our needs with dependency charts. I think so as the chart is just a combination of things listed below that can be fully controlled via passed values. Each installation of a Helm chart have control over values, and indirectly everything!
> 
>     * default values
> 
>     * listed dependencies - where we have the freedom to have them enabled/disabled by values [thanks to `tags` and `condition`](https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags).
> 
>     * custom templates - where we have the freedom to have them enabled/disabled by values
> 
> 
> # Value outcomes
> 
>     * JMTE could add `jupyterhub-ssh` as a opt-in chart dependency without needing to fork away further.
> 
>     * 2i2c pilot-hubs could handle needs like JMTE's better in the future where another Helm chart is wanted as a dependency for some hubs but not all.
> 
> 
> # Expected timeline
> 
> I'm very unsure. It could take a while as lots of 2i2c hubs would be influenced on a technical level.
> # Thoughts of the scope of work I can contribute with
> 
> I consider this to be quite 2i2c specific and that it would be out of scope for me to drive this change for all 2i2c deployments with my JMTE based funding. I suggest that I contribute with review rather than driving this change all the way to completion.
> # Steps to complete this goal
> 
>     * [ ]  Prerequisite: we evaluate if this is a reasonable strategy and worth going for.
> 
>     * [ ]  We coalesce the daskhub Helm chart into the basehub Helm chart, making the dask-gateway Helm chart dependency listed in Chart.yaml an opt in dependency.

I think this is a great start!

**Comment by choldgraf** [comment]
@yuvipanda is this issue something that you'd be interested in putting some time into this week? And is there a concrete next step or specific deliverable/action we could add for this sprint?

**Comment by yuvipanda** [comment]
We need to move the config from https://github.com/2i2c-org/pilot-hubs/blob/master/hub-templates/daskhub/values.yaml#L8 to `basehub/values.yaml`. Everything under `dask-gateway` can be moved directly, Almost all of the rest is to support dask-gateway working with networkpolicy. We'll have to copy paste that set of networkpolicy options for each hub that has dask-gateway enabled and network policy enabled. Perhaps that's ok for now?

Removing `daskhub` as a hub-template will probably require a redeploy of all the current hubs using that hub-template, with a manual bit of work to preserve list of currently added hub users. This can be done one at a time though, so we can co-ordinate with any users of the hubs in question.

**Comment by consideRatio** [comment]
I'll go for a close here in favor of #3252 linking back to this.
