### ISSUE TITLE
[Platform Initiative] Roll out jupyterhub-fancy-profiles for all hubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#5054]
The profile selection screen is what users see after they log in to the hub - so it's the 'logged in homepage' of the hub. Currently, most hubs use the standard profile screen that comes with kubespawner, so it looks like this:

![Image](https://github.com/user-attachments/assets/efecc964-db76-4b61-a6e2-38f67c33bbf7)

As part of the GESIS grant, we created [jupyterhub-fancy-profiles](https://github.com/yuvipanda/jupyterhub-fancy-profiles), a more modern (and backwards compatible) replacement for the profile selector. It looks like this:

![Image](https://github.com/user-attachments/assets/33903387-3939-4356-b2bf-ed658f9ad228)

![Image](https://github.com/user-attachments/assets/e283e1c1-4906-4d0b-8b13-3c6e99fdd518)

It also allows for connecting to a binderhub backend to allow for dynamic image building on the fly, and is a pre-requisite for enabling 'build-your-own' image features.

We have rolled this out to a few well used hubs (primarily NASA VEDA) for a few months without issue. This initiative tracks rolling this out to *all* our communities

## Backwards compatibility

`jupyterhub-fancy-profiles` is designed to be fully backwards compatible with the existing upstream profiles work, so config change is needed.

## Hubs affected

- [x] ohw
- [x] ucmerced
- [x] itccocean
- [x] ncar-cisl
- [x] showcase
- [x] lis
- [x] awi-ciroh
- [x] catalystproject-africa (all)
- [x] catalystproject-latam (all)
- [x] dubois
- [x] earthscope
- [x] gridsst
- [x] hhmi
- [x] jupyter-meets-the-earth
- [x] kitware
- [x] leap
- [x] nasa-cryo
- [x] nasa-ghg
- [x] nasa-veda
- [x] nmfs-openscapes
- [x] openscapes
- [x] opensci/sciencecore
- [x] pangeo-hubs
- [x] pchub
- [x] projectpythia
- [x] queensu
- [x] smithsonian
- [x] strudel
- [x] ubc-eoas
- [x] victor

## Definition of done

- [x] `jupyterhub-fancy-profiles` is rolled out to *all* existing hubs
- [x] It is on by default for all new hubs
- [x] We write a blog post announcing this change

**Comment by yuvipanda** [comment]
I've been testing this on a bunch of different hubs today, and fixed a couple minor bugs that I discovered (along with @oliverroick). I will roll this out early in the morning tomorrow (thursday) and watch for support tickets if they come!

**Comment by yuvipanda** [comment]
I'm going to roll it out by hand, testing each hub as I go. I made a list of hubs this should go out to on the issue description

**Comment by yuvipanda** [comment]
Before:

![Image](https://github.com/user-attachments/assets/fed161e6-12c1-420c-95cf-feb30b74490c)

After:

![Image](https://github.com/user-attachments/assets/4c917038-580f-4614-b895-6fdcc3e1fd60)

**Comment by yuvipanda** [comment]
Blog post at https://github.com/2i2c-org/2i2c-org.github.io/pull/338. I think once that's done, we can mark this initiative as completed.

**Comment by jnywong** [comment]
https://github.com/2i2c-org/2i2c-org.github.io/pull/338 merged.

I've also updated the Service Guide docs to reflect this change https://github.com/2i2c-org/docs/pull/247. 

Marking this as complete 🎉
