### ISSUE TITLE
[Nov 18] Regenerate SMCE credentials

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#5057]
## Definition of Done

SMCE credentials have been regenerated for:

- [x] NASA VEDA hub
- [x] NASA GHG hub

**Comment by GeorgianaElena** [comment]
@yuvipanda, there's [an issue template](https://github.com/2i2c-org/infrastructure/issues/new?template=10_smce_regenerate.md) to make these recurrent tasks faster to open. There's one for billing as well.
