### ISSUE TITLE
Automate hub deployment for all our clusters

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#507]
### Description

When a kubernetes cluster is present, we can automate the creation of a hub on top of it. We should do this for hubs on all of the clusters that we run.

### Benefit

Keeping all the hubs in sync makes sure we don't end up in a situation where some hubs need a lot of work for hub upgrades. It also reduces the amount of manual steps that we need to take in order to deploy a given hub.

### Implementation

We should ensure that our post-deploy tests don't leave running servers behind costing money. 

#### Google Cloud Hubs

- [x] Deploy basic GCP hubs

**Specific Hubs**

- [x] https://github.com/2i2c-org/pilot-hubs/issues/577

#### AWS Hubs

- [x] https://github.com/2i2c-org/pilot-hubs/issues/647

#### Azure hubs

- [x] https://github.com/2i2c-org/infrastructure/issues/841

**Comment by yuvipanda** [comment]
With #582 everything except AWS hubs are autodeployed.

**Comment by damianavila** [comment]
> With #582 everything except AWS hubs are autodeployed.

AFAIK #582 is not automating any Azure deployment, right?

**Comment by yuvipanda** [comment]
@damianavila yeah, but we don't have any Azure deployments merged yet -  #287 is unmerged.

**Comment by damianavila** [comment]
#287 was actually merged a long time ago, I guess you are referring to #513, right?
In any case, I get what you saying :wink:

**Comment by sgibson91** [comment]
RE AWS hubs: following code needs to be ported into deployer for authentication https://github.com/yuvipanda/hubploy/blob/dfc00254abb30d8887230472e83b405ff5872933/hubploy/auth.py#L107

**Comment by choldgraf** [comment]
Thanks @sgibson91 - I've separated out the top comment into a section for each major cloud provider in case we need to track more provider-specific tasks.

**Comment by choldgraf** [comment]
OK I believe that we've got an issue for each major cloud provider listed in the top comment, and each issue is resolved! So perhaps we can close this one?

**Comment by damianavila** [comment]
Yep, I think we can close this one! (we can always re-open if someone disagrees 😉 ).
