### ISSUE TITLE
Upgrade AWS clusters k8s version from 1.29 to 1.30

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#5114]
We should upgrade the k8s version to 1.30 on AWS clusters.

### Resources

https://infrastructure.2i2c.org/howto/upgrade-cluster/aws/

### Definition of Done

The following clusters have their k8s version upgraded to 1.30:
- [x] 2i2c-aws-us https://github.com/2i2c-org/infrastructure/pull/5106
- [x] catalystproject-africa https://github.com/2i2c-org/infrastructure/pull/5110
- [x] gridsst https://github.com/2i2c-org/infrastructure/pull/5136
- [x] jupyter-health https://github.com/2i2c-org/infrastructure/pull/5130
- [x] kitware https://github.com/2i2c-org/infrastructure/pull/5128
- [x] openscapes https://github.com/2i2c-org/infrastructure/pull/5138
- [x] opensci https://github.com/2i2c-org/infrastructure/pull/5124
- [x] projectpythia https://github.com/2i2c-org/infrastructure/pull/5140
- [x] smithsonian https://github.com/2i2c-org/infrastructure/pull/5123
- [x] ubc-eoas #5121

**Comment by consideRatio** [comment]
Changes in https://github.com/2i2c-org/infrastructure/pull/5129 have no impact on cluster upgrades except that you now won't execute 4 EKS addon upgrade commands, but instead one single - the three with `eksctl util ...` have been removed.

**Comment by sgibson91** [comment]
Clusters that have a tainted node to be removed:

- openscapes
