### ISSUE TITLE
[New Hub] [Phase 1] Cloud Account Setup - NASA-MAAP

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5197]
### What is the 'ready to work' status of this phase?

READY

### Context

NASA-MAAP will need to be separated cost-wise from VEDA, so we will be reproducing the scenario where we have a new AWS account to deploy into from NASA SMCE. 2i2c staff don't have permission to do that so we will be relying on @freitagb and @wildintellect (and possibly @jjfrench) to add us to that account when it is ready.

Please ensure the following engineers have access:

- georgianaelena@2i2c.org
- sgibson@2i2c.org
- yuvipanda@2i2c.org

We have all completed the necessary SMCE training since we have access to VEDA and GHG.

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Cloud Provider | `AWS` | |
| Will 2i2c pay for cloud costs? | `No` | |
| Name of cloud account | _TBA_ | |
| Community Representative(s) (GitHub handles or email) | @freitagb @wildintellect  | |
| Have the Technical Contacts been added to the [AirTable](https://airtable.com/appbjBTRIbgRiElkr/pagD3XyZjqBunYMnC)? | `Yes/No` | |

### Definition of Done

At least _two_ of the below engineers have access to an SMCE account for deploying a cluster into (please check off when you have access)

- [x] @sgibson91 
- [x] @GeorgianaElena 
- [x] @yuvipanda

**Comment by GeorgianaElena** [comment]
I was just able to login into the AWS account created for this cluster 🚀
@sgibson91, I see that you already had checked out the box in the top comment. Can you confirm that you also have access please? I will ping @yuvipanda on slack as well about this.

**Comment by sgibson91** [comment]
Yep, I have access!
