### ISSUE TITLE
[New Hub] [Phase 2] Cluster Setup - MAAP

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5198]
### What is the 'ready to work' status of this phase?

READY - depends on https://github.com/2i2c-org/infrastructure/issues/5197

### Required information for setting up a cluster for a new community or a set of communities.

This phase assumes all engineers have access to the relevant account,
and will be able to set up the cluster + support without issue. No hubs
are to be deployed during this phase. The following table lists the
information that must be provided before this phase can be marked as
READY and begin. Use the Notes column to provide any other contextual
information.

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Region/Zone of the cluster | `us-west-2` | |
| Name of the cluster | `maap` | |
| Are GPUs required? | `Yes` | Based on copying the current VEDA setup as advised in #5142 |

Available runbooks:
- https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase2/
- https://infrastructure.2i2c.org/hub-deployment-guide/new-cluster/smce/#aws-with-nasa-smce
- https://infrastructure.2i2c.org/hub-deployment-guide/deploy-support/

> [!warning]
> Also remember the additional runbook to get an MFA exemption for the `hub-continuous-deployer` user
> - https://infrastructure.2i2c.org/hub-deployment-guide/new-cluster/smce/#getting-a-mfa-exemption-for-our-hub-continuous-deployer-user

**Comment by GeorgianaElena** [comment]
This is currently blocked waiting for an MFA exemption for the hub-continuous-deployer user
