### ISSUE TITLE
[New Hub] [Phase 3] Hub Setup - maap.2i2c.cloud

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5199]
### Context

Depends on:
- https://github.com/2i2c-org/infrastructure/issues/5197
- https://github.com/2i2c-org/infrastructure/issues/5198

> [!note]
> This community may also want a dedicated URL, e.g.:
> - hub.openveda.cloud -> VEDA
> - hub.ghg.center -> GHG

### How many hubs will be deployed?

2 - staging and prod

### Which cluster will the hub(s) be deployed on?

SMCE MAAP account (official name TBD)

### Hub Setup Information

For each hub to be deployed, copy the tables below and fill them in.
The tables must be complete for each hub to be considered READY to be
deployed. For a staging/prod pair, a statement such as "Same as staging
but for production" will suffice for the prod hub's specification. Use
the Notes column to provide any contextual information.

Available runbooks:
- https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase3/

#### Phase 3.1: Initial setup

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Name of the hub | staging | |
| Dask gateway? | `Yes` | |
| Splash image URL | https://maap-project.org/wp-content/uploads/2021/10/nasamaaplogo3.png | |
| Homepage URL | https://maap-project.org/ | | 
| Funded by? | Copy what's in VEDA config | |
| Authentication Mechanism | GitHub | |
| Admin Users (GitHub handles or emails, depending on Mechanism) | @freitagb @wildintellect | |

At the end of this phase, both 2i2c engineers and the admin users mentioned can login to the hub.

#### Phase 3.2: Object storage access

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Scratch bucket enabled? | `Yes` |  |
| Persistent bucket enabled? | `No` |  |
| Requester pays requests to external buckets allowed? | `No` | |  

At the end of this phase, both 2i2c engineers and the admin users mentioned can access any object storage setup.

#### Phase 3.3: Profile List

These are the standard profile list options to start with. They can be customized later.
Use the Notes column to provide extra information, such as specific image tags to use, or `deployer generate resource-allocation choices` command to use for RAM, etc.

> [!note]
> Replicate VEDA profile list - this includes fancy profiles

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Pangeo Notebook?  | `Yes` | Modified by VEDA  |
| RStudio (with Rocker)? | `Yes` |  |
| Allow users to specify any image they want to use? | `Yes` | If Yes, enable `unlisted_choice`. | 
| Max RAM option allowed | | |
| GPU enabled? | `Yes` | |
| Default Interface | `JupyterLab` | |
| Allow multiple concurrent servers per user? | `Yes/No` | If yes, enable `allowNamedServers`. |
| Dynamic Image Building? | Enabled | |
At the end of this phase, the admin users mentioned should be able to start a server with their desired environment(s).

#### Phase 3.4: Authentication tuning

| Question | Answer | Notes |
| :--- | :--- | :-- |
| Authentication Mechanism | GitHub | |
| GitHub Teams based access? | `Yes` | |
| List of GitHub Teams to be granted access (if required) | _TBA_ | Double check with Yuvi |

#### Phase 3.5: Profile List finetuning

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Custom image to be specified? | `Yes` | QGIS Linux desktop (copy VEDA) |

### Hub 2: prod (`READY`)

Same as staging

**Comment by wildintellect** [comment]
All the teams listed on https://github.com/orgs/MAAP-Project/teams should get access. "data","maap-all", "platform"
I'll make a new team called GPU for GPU access.

**Comment by yuvipanda** [comment]
@wildintellect we can't actually see the teams, because we aren't members. I assume the teams are:

- MAAP-Project:data
- MAAP-Project:maap-all
- MAAP-Project:platform
- MAAP-Project:gpu (just for GPU)

Does that seem right?

**Comment by wildintellect** [comment]
yes those are correct
