### ISSUE TITLE
Openscapes Hub - deploying a new repository with new python 3.9 environment

### ISSUE THREAD

**Issue by amfriesz** [2i2c-org/infrastructure#562]
I'm using nbgitpuller to generate the link to deploy (is that the right term?) a new repository on the Openscapes hub. This new repository has a new environment that is using Python 3.9 and has additional packages relative to the original HLS repository. 

The repository I'm try to deploy is here: https://github.com/amfriesz/lpdaac_cloud_data_access.

The completed nbgitpuller link generator form looks like this:
![image](https://user-images.githubusercontent.com/7210313/127336177-95a842d1-f79b-4a3f-b5ae-edd88a697ee2.png)

The link generated is: https://openscapes.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Famfriesz%2Flpdaac_cloud_data_access.git&urlpath=lab%2Ftree%2Flpdaac_cloud_data_access.git%2F&branch=main

The content from the repository is available from the link, but the environment is running python 3.7 and doesn't contain some of the required python packages found in the environment.yml file (e.g. boto3 and stackstac).

Is there a way to deploy a new environment, specified in the environment.yml, on the Openscapes hub? If so, could I get some guidance on how to do so?

**Comment by choldgraf** [comment]
Hey @amfriesz  - right now there is one environment for the whole hub...are you asking if it's possible to define different environments for each nbgitpuller link?

**Comment by amfriesz** [comment]
I was thinking about defining different environment for each nbgitpuller link, but updating the hub would work too. Can the hub have multiple environments or kernels available? Say, a py 3.7 and a py 3.9 environment?

**Comment by choldgraf** [comment]
Hmmm I'm not sure right now whether it's possible to install multiple environments per hub. Will look into that. One option you could explore is having users install the environment during their session directly from the environment.yml files. This usually won't take too long and is just a step people have to run in, e.g., the first cell of a notebook.

**Comment by amfriesz** [comment]
I did try to create a new environment in the notebook (and in the terminal). The env gets created, but the kernel is not available to run even after I activate the env.

Create the environment
![image](https://user-images.githubusercontent.com/7210313/127398500-c4d96b3c-ad6b-4d99-b9ec-c6f5a19bf58d.png)

Activate new environment
![image](https://user-images.githubusercontent.com/7210313/127398558-573fe98a-6438-4d9a-be47-8d5b47f947e7.png)

py39 Kernel not available
![image](https://user-images.githubusercontent.com/7210313/127398765-3806dde7-d5e0-4cf0-ba60-95e2c56be288.png)

**Comment by choldgraf** [comment]
Hmmmm - that's a great point, I'm not sure how to install and activate a new conda environment _interactively_ without restarting JupyterLab. Lemme ask the team and see what they think, I've also asked around on Twitter to see if others have done this.

Is it really important to have both versions of Python available? Would one option be to just upgrade to 3.9?

**Comment by amfriesz** [comment]
@choldgraf, since the hub is not being heavily used at this time, I don't think upgrading to 3.9 would hurt anything. Also, during our last Openscapes tag-up it was brought to my attention that the following issue is open: https://github.com/2i2c-org/pilot/issues/81. I think it is related to this discussion we're having.

**Comment by abkfenris** [comment]
We use [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) to allow user managed conda environments on the [OceanHackWeek hub](https://oceanhackweek.github.io/ohw-resources/prep/conda/#create-your-own-environment-on-jupyterhub). It takes a min for the new kernels to show up, but it doesn't require a restart of JupyterLab.

**Comment by choldgraf** [comment]
I believe that this is now resolved - closing this but please reopen if there is more to do
