### ISSUE TITLE
Automatic image builds for OpenScapes hub

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#588]
# Summary

- need merge rights to merge these PRs
- these PRs make it possible for them to maintain their own image for their hub
- look into OpenScapes modifying their own image

https://github.com/amfriesz/lpdaac_hls_tutorial/pull/2
https://github.com/amfriesz/lpdaac_hls_tutorial/pull/1

**Comment by yuvipanda** [comment]
This is community managed via https://github.com/nasa-Openscapes/corn now
