### ISSUE TITLE
Create a process around identifying what quotas are needed for a cluster and ensuring they are requested

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#591]
# Summary

In https://github.com/2i2c-org/pilot-hubs/issues/590 we discovered that we were hitting quota limits on the CarbonPlan cluster and had to request more. We should incorporate an assessment of quotas into our team hub processes so that we don't hit these limits in an unexpected way.

# Tasks to complete

- [ ] Provide some guidelines about when / how to request quotas on the various cloud providers
- [ ] Document this in `pilot-hubs/`

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/pilot-hubs/issues/589 is related
