### ISSUE TITLE
Move 2i2c domains to our Google Cloud account

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#593]
# Background

Currently, 2i2c.org and 2i2c.cloud are registerd on namecheap in @colliand's account. Google Cloud now supports managing domains as part of a cloud project via [Cloud Domains](https://cloud.google.com/domains/docs/overview). We should move our Google Cloud project (two-eye-two-see) so access control becomes simplified.

# Steps to complete this goal

- [ ] [Import](https://cloud.google.com/dns/docs/migrating) our current DNS records from namecheap to Google Cloud DNS
- [ ] Change the nameserver on our namecheap account to point to the Google Cloud DNS nameserver. This lets us do the migration of the domain registrar without any downtime
- [ ] Move the domain registrar from namecheap to Google CloudDomains. This might require some co-ordination with @colliand
- [x] Close https://github.com/2i2c-org/meta/issues/176 as this supercedes it

**Comment by damianavila** [comment]
Do you want to move all the stuff to Google cloud DNS regardless of the cluster we are talking about, right?
I mean... AWS and Azure ones are included in this migration?

**Comment by choldgraf** [comment]
Also to be clear - this issue is talking about **moving away from namecheap entirely**, is that right? I've added a cross-link to an issue that this supercedes if that is true (https://github.com/2i2c-org/meta/issues/176)

**Comment by yuvipanda** [comment]
@damianavila currently everything is in namecheap.com. We only have two domains - 2i2c.cloud and 2i2c.org. This just moves the registrar. I don't think we can easily put them in multiple registrars.

@choldgraf yeah, this supersedes that. I'll close that one.

**Comment by damianavila** [comment]
> @damianavila currently everything is in namecheap.com. We only have two domains - 2i2c.cloud and 2i2c.org. 

Yep, I know :wink:

> I don't think we can easily put them in multiple registrars.

I am not advocating for that... just asking if this was an all-or-nothing migration since I think having some things in one place and some others in a new one would be the wrong move 😉  .

**Comment by damianavila** [comment]
I think you are correct @choldgraf 😉  .

**Comment by damianavila** [comment]
Recently, we had several issues at the time to add a new team member to Namecheap.
We are bottlenecked on @colliand providing us access on a case-by-case basis which makes him a SPoF.
Raising the priority of this one to be solved by Q1 2024 given this is probably expiring again by end of April 2024.

**Comment by colliand** [comment]
I have updated management roles in Namecheap for @damianavila @sgibson91 @yuvipanda @GeorgianaElena @consideRatio to `full access`. I hope this removes the SPoF highlighted above. I will be available to assist with the transfer of domain management from Namecheap to Google.

**Comment by damianavila** [comment]
Thanks for taking care of this, @colliand!!

**Comment by jmunroe** [comment]
Is this discussion on domain registration still valid given the acquisition by Squarespace of Google Domains?

Are we continuing with namecheap.com or moving somewhere else?
