### ISSUE TITLE
Major development Managed Hub Service v1

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#610]
# Summary

We should agree on the major development to do as a part of our Managed JupyterHub Service. This includes the major use-cases that we want to explicitly support, as well as features, tools, etc that we want to offer as a part of our JupyterHubs.

# Acceptance criteria

This issue should contain a list of features and infrastructure setup we consider essential for 'v1', and track their progress for various cloud providers. The table should be ordered by priority.

## Feature matrix

| Feature | GCP | AWS | Azure |
| - | - | - | - |
| Self-serve images [issue](https://github.com/2i2c-org/pilot-hubs/issues/493) | | | |
| GitHub Org / Team auth support [issue](https://github.com/2i2c-org/pilot-hubs/issues/598) | | | |
| Access cloud object storage [issue](https://github.com/2i2c-org/pilot-hubs/issues/372) | |  | |
| Educational institution based auth support [issue](https://github.com/2i2c-org/pilot-hubs/issues/315) | | | 
| Grafana with useful metrics [issue](https://github.com/2i2c-org/pilot-hubs/issues/616) | | | |
| Self-serve resource config (RAM, CPU, etc) [issue](https://github.com/2i2c-org/pilot-hubs/issues/312) | | | |
| Basic cloud costs monitoring and reporting [issue](https://github.com/2i2c-org/pilot-hubs/issues/328) | | | 
| Monitoring for hub downtime [issue](https://github.com/2i2c-org/pilot-hubs/issues/609) | | | |
| Automated deployment from CI [issue](https://github.com/2i2c-org/pilot-hubs/issues/507) |✅ | [issue](https://github.com/2i2c-org/pilot-hubs/issues/381) | |
| Autoscaling [issue](https://github.com/2i2c-org/pilot-hubs/issues/644) | ✅ | ✅ | |
| Automated cluster setup [issue](https://github.com/2i2c-org/pilot-hubs/issues/645) | ✅ | [issue](https://github.com/2i2c-org/pilot-hubs/issues/627) | [issue](https://github.com/2i2c-org/pilot-hubs/issues/512) |
| Automated user homes setup [issue](https://github.com/2i2c-org/pilot-hubs/issues/640) | [issue](https://github.com/2i2c-org/pilot-hubs/issues/50) | [issue](https://github.com/2i2c-org/pilot-hubs/issues/622) | |
| Backup user home directories [issue](https://github.com/2i2c-org/pilot-hubs/issues/641) | | [issue](https://github.com/2i2c-org/pilot-hubs/issues/623) | [issue](https://github.com/2i2c-org/pilot-hubs/issues/624) |
| Backup jupyterhub databases  [issue](https://github.com/2i2c-org/pilot-hubs/issues/452)| | | |
| Put user image near cluster for faster pulls [issue](https://github.com/2i2c-org/pilot-hubs/issues/626) | | | |
| Cheaper instances for dask-gateway [issue](https://github.com/2i2c-org/pilot-hubs/issues/642) |✅ |✅ | [issue](https://github.com/2i2c-org/pilot-hubs/issues/621) |
| Placeholders for faster node spinup [issue](https://github.com/2i2c-org/pilot-hubs/issues/643) | | | |
| Appropriate resource requests for core pods [issue](https://github.com/2i2c-org/pilot-hubs/issues/90) | | | |
| Cluster upgrade policy + implementation [issue](https://github.com/2i2c-org/pilot-hubs/issues/412) | | | |
| z2jh upgrade policy + implementation [issue](https://github.com/2i2c-org/pilot-hubs/issues/233) | | | |

**Comment by choldgraf** [comment]
This conversation made me think that it'd be helpful for us to have a structured way of doing higher-level planning. It feels like using issues to track other issues is a bit problematic, because then you have issues at different levels of abstraction that are nested within one another. I wrote up a proposal for one way we could track this here: https://github.com/2i2c-org/team-compass/issues/182

**Comment by yuvipanda** [comment]
I think a lot has progressed since this issue, closing.

**Comment by choldgraf** [comment]
That is an understatement 😅
