### ISSUE TITLE
Decomission grenoble hub deployment on 2i2c cluster

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#612]
We don't need to delete the 2i2c cluster, but we will need to delete the `grenoble` deployment.

Something like:

```
helm delete grenoble --namespace grenoble
helm delete namespace grenoble
```

But we should do that after this has been successfully deployed and the SWOT folk confirm.

_Originally posted by @sgibson91 in https://github.com/2i2c-org/pilot-hubs/issues/580#issuecomment-894236185_

### Context

The SWOT team were originally using a hub on the 2i2c cluster, but then was set up with their own (MEOM IGE). But the original deployment was never fully decommissioned.

# Tasks

- [x] Confirm that the new SWOT hub is working as expected
- [x] Decommission this cluster:
  -  1. Login to the 2i2c cluster
	  2. Run `kubectl get namespace` to confirm that a namespace called `grenoble` does indeed exist
	  3. Then run:
	  ```
	  helm delete grenoble --namespace grenoble
	  kubectl delete namespace grenoble
	  ```

**Comment by choldgraf** [comment]
I believe that this is complete, as I don't see any grenoble-related stuff in our list of running hubs or our 2i2c cluster config

**Comment by damianavila** [comment]
I would say the first item (new hub working as expected) is OK but I am not sure if the decommission already happened because that would not be evident from the list of running hubs or the cluster config file.

@sgibson91 do you remember if you run those helm commands at some point in the past?

**Comment by sgibson91** [comment]
I didn't, no

**Comment by choldgraf** [comment]
Ah ok - in that case I'm re-opening this and will add it to our team backlog so we can track it. If that cluster isn't decommissioned isn't it incurring a cost for either us or the Grenoble team?

**Comment by sgibson91** [comment]
Grenoble moved from a hub on the 2i2c shared cluster to their own cluster called meom-ige. The old hub needs deleting from the 2i2c cluster, IIRC. (I think that's what we uncovered in the original issue?)

**Comment by choldgraf** [comment]
@sgibson91 what confuses me is that we'd have a hub on our cluster, but that is not listed in our configuration. I thought if it wasn't in the config, it wouldn't be on the cluster.

What is the next step here? Can somebody either post it as a comment, or update the top comment?

**Comment by sgibson91** [comment]
No, you have to explicitly run the helm delete commands to remove a hub. There's no CI/CD to remove a hub if an entry is removed.

**Comment by sgibson91** [comment]
The config was removed in your Pr here: https://github.com/2i2c-org/infrastructure/pull/580/files#diff-832800fd850edde7602f90233d8710dfcdc5e28d829fd1c316325be265cc4f0bL399

But if `helm delete` wasn't run, then the hub still exists.

**Comment by sgibson91** [comment]
Next steps are:

1. Login to the 2i2c cluster
2. Run `kubectl get namespace` to confirm that a namespace called `grenoble` does indeed exist
3. Then run:
```
helm delete grenoble --namespace grenoble
helm delete namespace grenoble
```

**Comment by choldgraf** [comment]
thanks @sgibson91 - I've updated the top comment + added this to our backlog so that we can track this and get it done when somebody has a bit of extra time.

**Comment by sgibson91** [comment]
I've completed this

**Comment by choldgraf** [comment]
yay 🎉 thank you @sgibson91 :-)
