### ISSUE TITLE
Automate EFS creation for AWS

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#622]
### Description

We use [EFS](https://aws.amazon.com/efs/) for home directory storage on AWS, and it works really well. We have a script to set it up for use with kops (https://github.com/2i2c-org/pilot-hubs/blob/master/kops/setup-efs.py) but not with eksctl. It should be a fully automatically set up, ideally with terraform. 

### Benefit

This is another step in automating our deployment infrastructure so that we can deploy new hubs with less complexity and new steps. It also further professionalizes our infrastructure to be more reliable and consistent.

### Implementation

This should be an addition to the AWS Terraform code.

We have a `kops` implementation of this here: https://github.com/2i2c-org/pilot-hubs/blob/master/kops/setup-efs.py

But we should use `eksctl` instead if possible.

### Tasks

- [ ] Setup terraform for EFS creation: https://github.com/2i2c-org/infrastructure/blob/master/terraform/aws/efs.tf
- [ ] #623

**Comment by choldgraf** [comment]
I believe that this is now completed? https://github.com/2i2c-org/infrastructure/blob/master/terraform/aws/efs.tf

**Comment by yuvipanda** [comment]
Yep!

**Comment by damianavila** [comment]
I do not think #623 is actually completed, right? When I look into the terraform code, I do not see any references to the backup and I _think_ that does not come by default...
I do not see the issue closed but it seems @choldgraf wanted to close it.

**Comment by choldgraf** [comment]
@damianavila I was just trying to clean up issues that I thought were dangling and that had already been resolved. If this hasn't been addressed, we should decide how important #623 is and whether we should prioritize it. What do you think?

**Comment by damianavila** [comment]
> we should decide how important #623 is and whether we should prioritize it. What do you think?

Yep, let's continue the conversation in #623.
