### ISSUE TITLE
Use cloud provider registries for user images instead of quay.io

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#626]
### Description

Right now, we put custom user images on [quay.io](https://quay.io/). We should explore using the registries that are provided by individual cloud providers instead.

### Benefit

The main benefit here is performance. For a hub on a given cloud provide, if images are served from the same provider, they will pull faster than images served from quay.io.

https://github.com/2i2c-org/pilot-hubs/issues/331 should help determine how much of a performance hit this is.

### Tasks to complete

- [ ] Wait for https://github.com/jupyterhub/repo2docker-action/issues/65 needs to land so we can actually support pushing to the cloud native registries.
- [ ] Explore how much of an improvement we get by pulling from the cloud native registries, and decide what to do next.

**Comment by GeorgianaElena** [comment]
@yuvipanda, shouldn't jupyterhub/repo2docker-action#65 be fixed by https://github.com/jupyterhub/repo2docker-action/pull/73?

**Comment by GeorgianaElena** [comment]
I was experimenting with using the repo2docker action to push images to a private aws ecr registry over here https://github.com/GeorgianaElena/test-repo2docker-action and don't seem to be able to make it work. I'm wondering if it's because I misunderstood things and this isn't yet possible because some important piece of jupyterhub/repo2docker-action#65 is missing?

**Comment by sgibson91** [comment]
> I'm wondering if it's because I misunderstood things and this isn't yet possible because some important piece of [jupyterhub/repo2docker-action#65](https://github.com/jupyterhub/repo2docker-action/issues/65) is missing?

If this is true, I'd look to see what [docker/build-push-action](https://github.com/docker/build-push-action) is doing behind the scenes, as it does support pushing to multiple registries
