### ISSUE TITLE
Create reference documentation

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#628]
Does it make sense to have a `reference` section that simply describes the major components of our hub template? (e.g. "where does XXX come from?" "where is YYY configured?") or is it enough to just use lots of comments in our YAML?

_Originally posted by @choldgraf in https://github.com/2i2c-org/pilot-hubs/issues/613#issuecomment-902157723_

**Comment by damianavila** [comment]
I would say, it depends... docs are really nice to people in intro stages... after some familiarization yaml comments are probably enough. Not sure how to mix both scenearios.

**Comment by choldgraf** [comment]
We have a reference section in our infra docs now: https://infrastructure.2i2c.org/en/latest/

closing this since it's an MVP, we can open issues for specific stuff in later issues
