### ISSUE TITLE
Documenting use of nfs-server-provisioner

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#629]
### Description

We recently deployed `nfs-server-provisioner` in our support chart so that we can deploy in-cluster NFS servers for our hubs. This is **only used for Google Cloud** because its filesystem service is much more expensive than other cloud providers.

We should document this practice, as well as some other important information about the NFS servers. Here are a few questions that @sgibson91 brought up:

How is user data stored longer term when using the `nfs-server-provisioner` helm chart?

1. What are the common ways data loss can occur? Does deleting the PV delete the backing disk?
2. Can we resize them later if required? If so, how?
3. Will we have one disk per hub or one per cluster?
4. How can we do backups?

### Benefit

It is important that we document our team practices in general, but particular when they deviate from the "standard / expected" behavior. In this case, we are using managed services for filesystems in both AWS and Azure, but manually deploying NFS in Google Cloud. At the least, this should be documented so others aren't surprised.

More generally, as @sgibson91 notes:

> Losing user home dirs is always the worst case scenario, so we need to make sure we understand what is happening here.

Now that we are manually deploying NFS, it means we are on the hook for its behavior in a stronger way. It is really important that we understand what's going on because losing user data is a worst-case scenario.

### Implementation

I think this could be a "Filesystems and local storage" section in the Hub Engineer's guide: https://pilot-hubs.2i2c.org/en/latest/

**Comment by choldgraf** [comment]
**Note**: this one is probably a little bit less impactful right now, since we are temporarily using Google FileStore instead of our in-cluster NFS server. So this support component isn't currently in-production (I believe). We should re-visit this one when we make a switch back to in-cluster NFS on Google Cloud.
