### ISSUE TITLE
Provide an easy way to switch between RStudio, Notebook & Lab

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#633]
# Description

Currently, if you wanna switch between JupyterLab / RStudio / Notebook,
you have to *edit the URL*. This is not very user friendly.

Instead, it should be easy for folks to switch between these interfaces via the GUI. 

# Benefit / value

This would be useful for anyone who doesn't already know the right `url` pattern to use, or who isn't comfortable hand-editing URLs in general. This is probably "almost everybody" because clicking buttons is much easier than remembering what URL to use.

This would also be a useful way for others to **discover** what other interfaces are available on a hub.

# Implementation details

Here are a few places where this work could happen:

## Classic Notebook

We need a notebook extension that does the following:

1. Shows other UI options more visibly (currently they're under 'New ->').
   A bit more in-your-face in the tree view
2. Adds an easy way to 'open current notebook in JupyterLab'

## JupyterLab

The launcher already provides an easy way to get to RStudio, so we don't
actually need to do anything there for that. But...

1. Add an entry for classic notebook in the launcher, so people can switch
   back if needed
2. Add an easy way to 'open current notebook in classic notebook'

## RStudio

We don't have a lot of expertise in modifying & extending RStudio. Similar
switching functionality would be great, and might be provided by writing
[RStudio Extensions](https://rstudio.github.io/rstudio-extensions/index.html)

## Home page

We should allow users to choose the interface they wanna get into from the
home page - similar to what we do in the [UToronto Hub](https://jupyter.utoronto.ca)

**Comment by GeorgianaElena** [comment]
We now have the configurator 🚀 so we can consider this one resolved 🎉

**Comment by damianavila** [comment]
I think this one is aimed toward changing the UI on the fly once you have already launched a pod, maybe?

**Comment by GeorgianaElena** [comment]
Yes, let's reopen. Sorry about it.

**Comment by yuvipanda** [comment]
Tracked in https://2i2c.productboard.com/feature-board/7803674-product-ideas/features/26289312/detail now.
