### ISSUE TITLE
Design a secure method to receive secret keys

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#639]
### Description

Sometimes, we need to receive secret info (like OAuth keys!) from community champions / university IT to finish setting up our infrastructure. This needs to be encrypted both at rest and in transit. 

### Value / benefit

- We can receive secrets in a secret fashion
- We should receive it in a way that allows anyone from the 2i2c team to decrypt it, and isn't tied to anyone in particular

### Tasks to complete

- [ ] Choose what kinds of transfer options we want to officially recommend
- [ ] Work out a process for each and document it

**Comment by choldgraf** [comment]
A few options that @yuvipanda recently gave to the team at U. Toronto, and we might consider re-using as "officially recommended" options:

- [keybase.io](https://keybase.io/)
- [age](https://github.com/FiloSottile/age#encrypting-to-a-github-user) encrypted with a key that we publish in a public space (Yuvi sent https://github.com/yuvipanda.keys). Once encrypted, the encrypted text can be sent via the support chat.
- GPG key (see [one blog post for info on how to do this](https://yanhan.github.io/posts/2017-09-27-how-to-use-gpg-to-encrypt-stuff/)

I feel like the first two options are the most reasonable, though both of them we shouldn't expect a Community Representative to have any background with and we should write documentation to step people through each.

**Comment by damianavila** [comment]
> I feel like the first two options are the most reasonable, though both of them we shouldn't expect a Community Representative to have any background with and we should write documentation to step people through each.

Maybe just the first option is sort of reasonable?

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/docs/pull/164 and https://github.com/2i2c-org/infrastructure/pull/1698 add support for `age` so we can be given secret credentials. This doesn't mean we can't have other setups in the future, but this at least gives us one secure method that is not a single point of failure.

**Comment by sgibson91** [comment]
> > I feel like the first two options are the most reasonable, though both of them we shouldn't expect a Community Representative to have any background with and we should write documentation to step people through each.
> 
> Maybe just the first option is sort of reasonable?

+1'ing keybase.io as well, since I already use it
