### ISSUE TITLE
Automate user homes setup

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#640]
### Description

Right now we are often manually deploying the NFS server that provides users their "home directory". This should be automated across all of the cloud providers as a part of the hub setup process.

### Value / benefit

This is a process we follow for *every single* hub that we deploy, and so it is important to automate it in order to reduce the complexity and manual steps associated with each hub.

### Implementation details

This will be different for each cloud provider, as they all provide their own filesystem setup. In some cases we may also have to manually deploy filesystems which will be extra complexity to track.

### Tasks to complete

- [ ] AWS: https://github.com/2i2c-org/pilot-hubs/issues/622
- [x] Google Cloud: #50
- [ ] Azure: need to create issue

**Comment by yuvipanda** [comment]
This is now done via Google Filestore on GCP, EFS on AWS and Azure File on Azure.
