### ISSUE TITLE
Autoscaling for our hubs

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#644]
### Description

We should set up autoscaling for our hub infrastructure, so that when a hub's resource limits are reached, a new node is requested and the hub can grow to accommodate the extra demand.

### Value / benefit

This is important in order to take advantage of the benefits of Kubernetes in general - without autoscaling we effectively are just running a single VM at a fixed cost. It is applicable to almost every hub because they all autoscale no matter how big or small.

### Implementation details

This will be cloud provider-specific for each type of hub/cluster, so we should track each one separately.

### Tasks to complete

- [x] Google Cloud
- [x] AWS
- [ ] Azure

**Comment by yuvipanda** [comment]
This has generally been done.
