### ISSUE TITLE
Automate cluster setup for major cloud providers

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#645]
### Description

The first step in creating a hub is creating a Kubernetes cluster. This provisions the cloud infrastructure + the Kubernetes engine that is needed to deploy applications like JupyterHub or Dask Gateway in the cloud. This should be automated for every major cloud provider we wish to support.

### Value / benefit

This is a pre-requisite for deploying infrastructure in the cloud, so is a critical issue across all of them.

### Implementation details

This is going to be cloud provider-specific. In some cases we'll use the provider services (e.g. `eksctl`) and in others we will need to hand-deploy clusters (e.g. with `kops`). We'll discuss that in each provider-specific issue.

### Tasks to complete

- [x] https://github.com/2i2c-org/pilot-hubs/issues/627
- [x] https://github.com/2i2c-org/pilot-hubs/issues/512
- [x] Google Cloud

**Comment by yuvipanda** [comment]
I'd say this is done
