### ISSUE TITLE
Small cleanup tasks following z2jh 1.1.3 bump

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#658]
These are small cleanup tasks following the z2jh 1.1.3 bump. Thanks @damianavila for catching these are still relevant tasks from #539!

- [x] hub.services..apiToken is now automatically generated, and a bug in jupyterhub is fixed so it can be set to a blank even if it wouldn't be autogenerated by z2jh. I recall @GeorgianaElena ran into this bug before and perhaps there is some cleanup that can be done (`georgiana`: [this is the PR](https://github.com/2i2c-org/pilot-hubs/pull/445) where that discussion + change happened).
- [ ] KubeSpawner now intelligently sort environment variables to help them resolve. This can make our logic to set SCRATCH_BUCKET environment variables less complicated if i recall correctly.

**Comment by consideRatio** [comment]
I looked through the point about SCRATCH_BUCKET, and I think it looks ok!

**Comment by damianavila** [comment]
> I looked through the point about SCRATCH_BUCKET, and I think it looks ok!

So we do not need a follow-up simplification, @consideRatio?

**Comment by consideRatio** [comment]
I could no longer identify what i referred to. But if you see logic about environment variables being declared for singleuser servers, ordered in a way to force them to ve evaluated in a certain sequence as they depend on each other, that is no longer needed - kubespawner now resolves the evaluation order needed if envs depend on other envs.

**Comment by consideRatio** [comment]
I didn't have an action point to clarify any more, and not having one, I felt I should close the issue. Looking back at https://github.com/jupyterhub/kubespawner/pull/510 I find my link to another issue which seem to capture the detail of what I wanted to get done.

This was: https://github.com/2i2c-org/infrastructure/issues/442

**Comment by damianavila** [comment]
Super, thanks for linking #442!
