### ISSUE TITLE
Debug node autoprovisioning: did not match Pod's node affinity

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#677]
### Description

In #670 we enabled node auto-provisioning. In practice what we are seeing when trying to create pods is the following message:

```
Events:
  Type     Reason             Age   From                 Message
  ----     ------             ----  ----                 -------
  Warning  FailedScheduling   38s   prod-user-scheduler  0/2 nodes are available: 2 node(s) didn't match node selector.
  Warning  FailedScheduling   38s   prod-user-scheduler  0/2 nodes are available: 2 node(s) didn't match node selector.
  Normal   NotTriggerScaleUp  38s   cluster-autoscaler   pod didn't trigger scale-up: 1 node(s) didn't match Pod's node affinity
```

And this is preventing any new node from coming up.

### Value / benefit

We need to spin nodes up!

### Updates

- **2021-09-13** - We've decided to manually provision the Pangeo cluster for now, so we have a bit more time to debug this one. Bumped down to `medium` impact now.

**Comment by sgibson91** [comment]
I did the following:

`kubectl get pod jupyter-sgibson91 -o yaml > mypod.yaml`

Edited the yaml and removed the `nodeSelector`

`kubectl apply -f mypod.yaml`

And that seemed to spin up fine

**Comment by tylerpotts** [comment]
@sgibson91 For what it's worth, in QHub we haven't tried node auto-provisioning. Instead we have node pools that are explicitly defined and pods get scheduled on them. Wish we could be of more help here

**Comment by sgibson91** [comment]
Thanks @tylerpotts - that is 2i2c's default too. But when I raised the question about appropriate machine sizes for those pool in #666 we found out Pangeo are using auto-provisioning and we didn't really have any data to hand for optimising the machine sizes to expected load.

**Comment by tylerpotts** [comment]
@sgibson91 We have been recently struggling with the problem of optimizing workload to node size as well. For the most part we have been allocating a single node per user pod/dask pod which has helped somewhat when it comes to the larger scale clusters.

As far as determining the allocatable  resources available on the nodes, we have quite a bit of research detailed here that you may find useful: https://github.com/Quansight/qhub/issues/792. Unfortunately there doesn't seem to be a linear formula, as kubernetes reserves variable amounts of millicpu and RAM depending on the size of the node

**Comment by choldgraf** [comment]
I've added an update to the top comment, to reflect that we're manually provisioning the Pangeo hub for now!
