### ISSUE TITLE
Add documentation about best-practices in deploying hubs on AWS

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#696]
Once #691 lands, we should add a piece of documentation to explain how to do automatic deployment of AWS hubs.

Some places that need to be updated:
*  https://pilot-hubs.2i2c.org/en/latest/howto/operate/new-hub/index.html
*  https://pilot-hubs.2i2c.org/en/latest/howto/operate/new-hub/aws.html#deploy-the-new-hub

We should also mention awscli and kops [here](https://pilot-hubs.2i2c.org/en/latest/reference/tools.html) since those tools are used by the CI now (and yourself if you are deploying locally).

**Comment by choldgraf** [comment]
adding this one to the sprint board since @damianavila mentioned he'd like to tackle it this time around
