### ISSUE TITLE
Migrate our hubs to use the repo2docker action

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#710]
### Description

Some of our hubs integrate their user image files along with the hub configuration / deployment. For example [the utoronto hub image is a sub-folder in the deployment repository](https://github.com/utoronto-2i2c/jupyterhub-deploy/tree/staging/deployments/utoronto/image).

For these hubs, we should create a user image repository that uses the repo2docker action, and configure the hubs to use the image that this builds.

### Value / benefit

This will have a few benefits:

1. It more cleanly separates the environment image config from the hub config
2. It is a place that a hub administrator may be able to update on their own
3. It separates out the "image building" CI/CD from the hub deployment CI/CD
4. It standardizes our stack on the same set of tooling / patterns
5. It's a better path forward for organizations to replicate their own infrastructure

### Implementation details

As an example, here's what I think we'd need to do for U. Toronto.

1. Clone the repo2docker action to a new repository (maybe called `2i2c-org/image-utoronto`). Here's the action: https://github.com/jupyterhub/repo2docker-action

2. Update the new repository with the files from https://github.com/utoronto-2i2c/jupyterhub-deploy/tree/0579feaae80d4a8e46726fb3d3dc6b5ce2c9d933/deployments/utoronto/image

3. Configure the repository to push to the same registry that the Toronto hub currently uses (probably Azure). Here's where the image is configured:

   https://github.com/utoronto-2i2c/jupyterhub-deploy/blob/0579feaae80d4a8e46726fb3d3dc6b5ce2c9d933/deployments/utoronto/hubploy.yaml#L1-L6

4. Confirm that the image builds and pushes
5. configure the *staging hub* to pull from the new built image location
6. confirm that the environment is the same on staging
7. deploy the configuration change to production

### Updates and tasks

- [x] Confirm that the above steps are correct
- [x] Determine which other hubs we want to convert to this process
  - We decided that the images we've already converted are good enough for now.
- [ ] Do the conversions
  - [x] https://github.com/2i2c-org/infrastructure/issues/854
  - [ ] The 2i2c base user image: https://github.com/2i2c-org/infrastructure/tree/master/images/user

**Comment by damianavila** [comment]
How this one is intermixed with the standard process @GeorgianaElena was working on for user images?
I am worried that the work needed to complete this one would not be useful in the future because there is already machinery in place to address this need (just trying to avoid duplication for work/code if possible having #638 as the general encompassing context).

**Comment by choldgraf** [comment]
I _think_ that this issue is just applying the process that @GeorgianaElena set up to our pre-existing hubs. @GeorgianaElena correct me if I'm wrong and it looks like my suggestion here does not match what you had in mind for that action!

But in general, I think the medium-term plan is: for any hub that needs their own custom environment, we host that environment in a dedicated repository (rather than in a Dockerfile that is embedded with the hub config) that uses the repo2docker action to build/push to a registry automatically.

**Comment by damianavila** [comment]
> But in general, I think the medium-term plan is: for any hub that needs their own custom environment, we host that environment in a dedicated repository (rather than in a Dockerfile that is embedded with the hub config) that uses the repo2docker action to build/push to a registry automatically.

Fair enough, I just wanted to be sure we were not duplicating work :wink:

**Comment by choldgraf** [comment]
What other hubs do we need to perform this action for? We have completed this step for UToronto, are there others that we want to prioritize in order to close this issue? If not, I think we should just close it

**Comment by damianavila** [comment]
Although... someone could argue we may want to have our own user image converted as well before closing this one: https://github.com/2i2c-org/infrastructure/tree/master/images/user and I would agree with that...

**Comment by choldgraf** [comment]
wohoo! 🎉
