### ISSUE TITLE
Add a conditional check for whether to run `helm dep up` in our deploy scripts

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#716]
### Description

In closing https://github.com/2i2c-org/pilot-hubs/issues/556, we've added an automatic step to run `helm dep up` as part of our deploys, to ensure that we don't have outdated local charts. One drawback is that this slows down the deploys a bit, even though this step may not always be needed.

To resolve this, we can add a conditional check to decide if the local version of the chart is out of date with latest version we need. Only if the answer is "yes" do we run `helm dep up`.

It's unclear how much benefit this would give us, since the deployment process already takes some time. So let's **time box this and decide by January 2022 whether we really need this change**.

### Value / benefit

The main benefit is that this would save us some time when doing deploys, in cases where we unnecessarily run `helm dep up`.

**Comment by sgibson91** [comment]
Yeah, this is because when I was working in the deployer, I ended up with a circular dependency when I separated out various functions into their own files: https://github.com/2i2c-org/infrastructure/pull/1054
