### ISSUE TITLE
Document our Azure cluster deployment setup

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#718]
### Description

In https://github.com/2i2c-org/pilot-hubs/pull/513 @yuvipanda added some terraform infrastructure to manage the auto-deployment of clusters on Azure. We need to document this setup.

We should at least have this information:

- When and how to use this terraform setup to deploy a new cluster (even if we can piggy back on some pre-existing docs)

And ideally also:

- High-level overview of the structure of the config (or at least anything idiosynchratic or non-standard)

### Value / benefit

Documenting will make it clearer how to use the deployment, so that other team members can learn how it's structured and how to use it themselves.

### Implementation details

Here's an example of one of the terraform files that was created:

https://github.com/2i2c-org/pilot-hubs/pull/513/files#diff-a72b7b93508224bfaeef0ffa2613d32b06136b4b3c4b8d7f32557def0f2e216e

And our current terraform docs for Google Cloud, which this will probably follow similarly:

https://devops.2i2c.org/en/latest/howto/operate/new-cluster/google-cloud.html

**Comment by choldgraf** [comment]
Assigning @yuvipanda and @sgibson91 as I think they are the only ones with the expertise of Azure and/or our TF setup to be able to document this properly :-)

**Comment by sgibson91** [comment]
So the workflow for either Azure or GCP are so similar, I'm tempted to just have a single "new cluster" page that has panels Azure/GCP specific things. Otherwise, we will end up having to maintain a lot of the same documentation around _terraform_ stuff but in 2 places.

**Comment by yuvipanda** [comment]
@sgibson91 big +1 on having a single page with panels!
