### ISSUE TITLE
Dynamically ensure secrets are encrypted with sops

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#719]
### Description

@damianavila and I noted that when writing documentation, we often find ourselves repeatedly putting in note blocks saying something like "Remember to sops-encrypt this before committing!". As we manage more hubs/clusters (increase in complexity) and acknowledging that humans are always capable of mistakes, it would be nice so have some kind of automated method of ensuring that secrets have been encrypted before a commit is made.

Here are some resources:

- The [mybinder.org-deploy repo](https://github.com/jupyterhub/mybinder.org-deploy) ensures their secrets are encrypted (with git-crypt) using a [.gitattributes file](https://github.com/jupyterhub/mybinder.org-deploy/blob/master/.gitattributes) and there is some mention of .gitattributes in the [sops README](https://github.com/mozilla/sops#48showing-diffs-in-cleartext-in-git) (not quite the same use-case but at least demonstrates that sops and .gitattributes are compatible)
- [This blog post](https://levelup.gitconnected.com/using-sops-and-git-hook-to-share-secrets-part-2-38518be67a14) discusses setting up git-hooks to handle encrypting for certain git commands

### Value / benefit

- The engineering team are less likely to accidentally leak secrets through forgetting to encrypt them before committing
- Less toil in workflows and less repetition in our docs

**Comment by yuvipanda** [comment]
We are using https://pre-commit.com/ in a bunch of other Jupyter repos - perhaps that can be leveraged here too?

**Comment by yuvipanda** [comment]
https://github.com/k8s-at-home/sops-pre-commit seems helpful

**Comment by sgibson91** [comment]
I feel twitchy about sending secrets to an external server though? We're then vulnerable to any security breaches pre-commit.com experiences. Whereas a local git-hook, it our own machines we need to worry about. (But maybe I'm being over-cautious)

**Comment by yuvipanda** [comment]
@sgibson91 pre-commit is just a way of managing multiple git hooks locally, there's no external server involved. https://github.com/jupyterhub/jupyterhub/blob/main/.pre-commit-config.yaml is the config for JupyterHub, and it runs a bunch of checks before each commit on your local machine only. I think there is https://pre-commit.ci/ which is the external service that runs some pre-commit stuff (like black) on CI, but as you said we shouldn't use that.

**Comment by sgibson91** [comment]
Ah yes, sorry, I thought you were suggesting pre-commit.ci! (Didn't twig the different URL)

**Comment by damianavila** [comment]
I use pre-commit (local 😜 ) before and it worked well for checking stuff (ie. avoid people committing massive amounts of data that git can not manage).

**Comment by yuvipanda** [comment]
Apparently I forgot I had mentioned https://github.com/k8s-at-home/sops-pre-commit, wrote https://github.com/yuvipanda/pre-commit-hook-ensure-sops, and had it set up here. @sgibson91 and @consideRatio also set up an appropriate .gitignore setup as an added layer. I think this is good to be closed.
