### ISSUE TITLE
Automatically deploy grafana charts to all our grafanas

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#739]
### Description

https://github.com/jupyterhub/grafana-dashboards contains very helpful grafana dashboards for operating a JupyterHub. However, they need to be deployed (and kept up to date) for each grafana installation we have. This should be a CI step.

### Value / benefit

We'll have consistently useful graphs in all our grafanas. Right now, most of the grafana installations are empty!

### Implementation details

A new deployment only needs to happen every time a new change to github.com/jupyterhub/grafana-dashboards is pushed, and that is fairly infrequent. So perhaps we can have it on a cron, or just require manual triggering?

**Comment by GeorgianaElena** [comment]
I think a separate workflow would be better if we want to go with a manual triggering. I don't *think* it's possible yet to manually trigger just a workflow job.
