### ISSUE TITLE
[Incident] Pangeo Hub does not have FTP access

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#740]
# Summary

@rabernat's class uses FTP to grab some data from a NOAA server. This port was blocked by our singleuser network policy. We updated the network egress policy for singleuser to allow TCP protocol on port 21. This at least allowed us the login to the FTP server, but receiving the data wouldn't work because the FTP server works in passive mode and tries to assign a random port to return the requested data.

## Timeline (if relevant)

If it makes sense to include a timeline for this incident, then do so below.

All times in BST.

### 2021-10-06 15:00

Ryan notified @sgibson91  of a support ticket that was raised the previous date and had not been responded to yet. He provided the ftp command he was running and the error he received.

### 15:20

Sarah and @consideRatio begin a video debugging session.

Things tried:

- Updating firewall rules in GCP console
- Going through basehub and daskhub network policy configs to ascertain which ports are allowed/disallowed
  - https://github.com/2i2c-org/pilot-hubs/issues/741
  - https://github.com/2i2c-org/pilot-hubs/pull/743
  - https://github.com/2i2c-org/pilot-hubs/issues/745
- Explicitly allow port 21 in Pangeo config, this allowed us to connect to the FTP server at least but the data couldn't be retrieved
  - https://github.com/2i2c-org/pilot-hubs/pull/744

### 17:00

Investigation interrupted by roadmapping meeting 😁 

---

# After-action report

## What went wrong

Our network policies blocked access to FTP. It wasn't as simple a fix as opening the FTP port since it most often works in "passive" mode where a second, random port is opened for the data transfer. The meant the only solution was to allow unrestricted access to the internet from `singleuser` pods, but restrict traffic _within_ the cluster.

## Where we got lucky

N/A

### Process improvements

N/A

### Documentation improvements

N/A

### Technical improvements

1. To allow FTP we need to open all outbound ports. Discussion on this here: https://github.com/2i2c-org/pilot-hubs/issues/741
2. Some further simplification of our network policies can be achieved with a new release of dask-gateway https://github.com/2i2c-org/pilot-hubs/issues/745

# Actions

- [x] Incident has been dealt with or is over
- [x] Sections above are filled out
- [x] Incident title and after-action report is cleaned up
- [x] All actionable items above have linked GitHub Issues

**Comment by yuvipanda** [comment]
https://github.com/berkeley-dsep-infra/datahub/issues/2825 has more details on the FTP situation, and in https://github.com/berkeley-dsep-infra/datahub/issues/2825 there's discussion about just removing the outbound port restrictions. I think my inclination is that as long as we don't allow arbitrary access *inside* the cluster (where the user server can just hit the prometheus server, for example!) port restrictions are pointless. So if we can allow unrestricted access to the *internet* but not local cluster network we're all good.
