### ISSUE TITLE
Plan for rolling out GitHub Teams authentication

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#750]
### Description

We recently added the ability to use a JupyterHub custom authenticator as well as GitHub Teams (for one example, see https://github.com/2i2c-org/pilot-hubs/issues/598).

However, this takes a bit more "manual fiddling" than the Auth0 workflow, and is still relatively new, so we should decide how we'd like to expose this feature to our communities.

### Value / benefit

We want to do three things:

- Make this feature available to the communities that would most-benefit from it
- Roll it out in a way that doesn't cause unexpected bugs for us
- Roll it out in a way that is sustainable given the amount of setup time that it has

### Implementation details

I propose that we make this authentication a feature of our **Research Hubs** for now. I have a few reasons for this:

1. We have fewer research hubs in general thus far
2. Research hubs are probably more interested in using GitHub Teams (compared with university SSO for educational hubs)
3. We generate more resources from research hubs, and this feels like something where we take on extra labor, and so we should be getting compensated more for it.

### Tasks to complete

- [ ] Do folks think that restricting this authentication approach to research-based hubs is an acceptable path forward?
- [ ] Write up this policy in our service and team documentation

**Comment by damianavila** [comment]
> I propose that we make this authentication a feature of our Research Hubs for now.

I think that is a great start.

**Comment by jules32** [comment]
Adding my support for this idea!

GitHub Teams would be a really nice way to be able to add/remove access for users in bulk to 2i2c. With NASA Openscapes we have separate teams of tutorial developers, workshop participants, and assistants, all of which have different time durations in the Hub, and it would nicely streamline management (the way we're doing now with GitHub repositories).

**Comment by damianavila** [comment]
At today's cycle meeting we have a little conversation about the need to advertise GitHub Teams auth (which means creating user-facing docs). Added this issue to the backlog.

**Comment by sgibson91** [comment]
I think the following issue should be rolled into the documentation of this feature:

* https://github.com/2i2c-org/infrastructure/issues/1245

Some of the screenshots I made here will be useful for documenting this feature:

* https://github.com/2i2c-org/infrastructure/issues/1702#issuecomment-1286706091

While, I realise this is user facing and will end up in docs.2i2c.org, I may take this on when I tackle the restructuring of our infrastructure docs as well

* https://github.com/2i2c-org/infrastructure/issues/1757
