### ISSUE TITLE
New Hub: Demo Hub for 2i2c

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#777]
### Hub Description

A relatively simple Demonstration hub that the @2i2c-org/2i2c-team can use to try things out. I'd propose that we use this hub for:

- Trying things out from a user-facing perspective
- Providing quick access to people that want to know what it's like to use a 2i2c hub
- Doing / creating demos of how functionality works

We have a similar hub for the CloudBank federation that I think Berkeley has used to help demonstrate things.

It would have a basic image that is built by a repo2docker-action repository, that we can also use to show off what the process looks like. Other than this, the hub shouldn't deviate from the basic hub offering.

### Community Representative(s)

There would be no official community representatives for this hub, since 

### Important dates

No important dates, I think this would keep going semi-indefinitely

### Target start date

11/01/2021

### Preferred Cloud Provider

Google Cloud Platform

### Do you have your own billing account?

- [ ] Yes, I have my own billing account.

### Hub Authentication Type

GitHub Authentication (e.g., @mygithubhandle)

### Hub logo

2i2c logo

### Hub logo URL

2i2c.org

### Hub image service

quay.io

### Hub image

Doesn't exist yet

### Extra features you'd like to enable

- [ ] Dedicated Scalable Dask Cluster with [Dask Gateway](https://gateway.dask.org/)

**Comment by yuvipanda** [comment]
This is done - http://demo.2i2c.cloud/
