### ISSUE TITLE
Investigate conda-store to understand if / how it could be used in JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#786]
### Description

For https://github.com/2i2c-org/meta/issues/252, https://github.com/2i2c-org/infrastructure/issues/85, https://github.com/2i2c-org/infrastructure/issues/620, and https://github.com/pangeo-data/jupyter-earth/issues/79, we want to spend some time investigating [conda-store](https://github.com/Quansight/conda-store). We should have a deeper understanding of what it is and how it works, so we can figure out where (and if) it can be helpfully deployed for us. It's also important to see if we can contribute back upstream productively, as community ownership & governance is very important for long term sustainability of projects.

Yuvi will try to write a [TLJH plugin](https://github.com/yuvipanda/tljh-conda-store) to get conda-store to work with TLJH. The goal of this exercise is to learn more about conda-store and how it might be used in a JupyterHub. This helps him understand what it takes to deploy the simplest possible production JupyterHub with a working conda-store implementation, and might independently be useful for TLJH users as well.

### Value / benefit

Getting conda-store to work with tljh helps me fill out https://hackmd.io/_hQdrilJQFCGExUqYgwY3Q?edit with a quick evaluation of conda-store, to help understand how it can fit our use cases. It also helps figure out how upstream collaboration would work, as we'll need to send patches upstream for sure - https://github.com/Quansight/conda-store/pull/196 is a start.

Ultimately, this will help us figure out how much resources we can spend on improving and using conda-store.

### Tasks to complete

- [x] Try implementing a TLJH plugin for conda-store
- [x] Write up major things that were learned along the way

### Updates

- Started https://hackmd.io/_hQdrilJQFCGExUqYgwY3Q?edit with notes about my understanding of conda-forge 
- Opened https://github.com/Quansight/conda-store/pull/196

**Comment by yuvipanda** [comment]
Thanks a lot for the merge and the new release, @costrouc! I'll continue to open issues and PRs as I go along :)

And thanks for responding on the hackmd too! I'd love for you to transition to FastAPI (or another async framework) - I think from sync to async, especially in a process involving db transactions, becomes difficult after it reaches critical mass. And currently, almost all the server side software in this space (dask-gateway, jupyter, etc) are async, so it would be great to follow suit - helps with code re-use too wherever possible.

**Comment by yuvipanda** [comment]
So, the hub environment in TLJH uses a virtualenv, and conda isn't really installable in anything other than conda environments. The `setup.py` doesn't actually work in a fresh python environment due to https://github.com/conda/conda/issues/10691. I fell into that rabbit hole a tiny bit (see https://github.com/conda/conda/pull/11014) but have pulled back. I think conda-store can't run in the same environment as the hub as that is a virtualenv, but we can create a new conda env for conda-store to run out of instead.

**Comment by damianavila** [comment]
> I think conda-store can't run in the same environment as the hub as that is a virtualenv, but we can create a new conda env for conda-store to run out of instead.

How about installing miniconda as part of the bootstrapping TLJH is doing? Then you can create the conda env and install conda store on it (modulo conda-store does not need to run from the base environment which would be already available after installing miniconda).

**Comment by yuvipanda** [comment]
@damianavila that's what I ended up doing https://github.com/yuvipanda/tljh-conda-store/blob/0ea1a4ad6018447f995deb02b571f740dffaee40/tljh_conda_store/__init__.py#L40

**Comment by damianavila** [comment]
So, mamba is there, nice! 
Btw, that code makes sense to me.

**Comment by choldgraf** [comment]
Thanks for this update @yuvipanda - it sounds like next steps with `conda-store` need to wait for finding a community that has the right use-case for it. I'll close this one and we can open a new one to track new implementation when the time is right. If you'd rather keep this one open feel free to re-open!

**Comment by damianavila** [comment]
@yuvipanda, first of all, thanks for the summary! I think the next step section is a reasonable one.

> Our current efforts
> are probably better put towards moving more folks into https://github.com/jupyterhub/repo2docker-action
> and perhaps https://github.com/yuvipanda/jupyterhub-configurator.

Makes sense to me.
Although I would love to read more about your experiences with tljh-conda-store in the future!

> In binderhub, we simply use kubernetes
> directly with an idempotency property rather than celery for similar effect.

Btw, do you have a link that I can take a look at about this piece? 😉
