### ISSUE TITLE
Tidy up Pangeo's Namecheap entry and URLs, especially for grafana

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#821]
### Summary

There's a bit of a name-clash for the grafana deployment on pangeo-hubs at the moment since I wasn't very clever when setting up the COESSING hub.

https://github.com/2i2c-org/infrastructure/blob/6cf0a3ff3c9edf2154791e26c269dbbf681d5234/config/hubs/pangeo-hubs.cluster.yaml#L13-L16

This is the plan for the URLs/Namecheap entry moving forward:

- [x] https://github.com/2i2c-org/infrastructure/issues/679
- [x] Move `pangeo-grafana.pangeo.2i2c.cloud` to `grafana.gcp.pangeo.2i2c.cloud`: https://github.com/2i2c-org/infrastructure/pull/847
- [x] Update our A record in Namecheap to be a wildcard record (`*.gcp.pangeo`) since `pangeo-grafana.pangeo.2i2c.cloud`, `staging.pangeo.2i2c.cloud` and `pangeo.2i2c.cloud` all point to the same IP address. This will be simpler to maintain.
- [x] Update the `pangeo.io` DNS zone accordingly

If we move forward with https://github.com/2i2c-org/infrastructure/issues/427 at some point, I will make these URLs `*.gcp.pangeo` so we can have `*.aws.pangeo` in the future.

**Comment by damianavila** [comment]
@sgibson91 is there any place in the docs (or maybe is some specific issue) where all the URLs and DNS providers playing together on the pangeo deployment is described. I think I got most of it from reading several related issues but I do not remember one with a short summary (and consolidated information) for the next reader 😉  .

**Comment by sgibson91** [comment]
No, but in short it is `*us-central1-b.gcp.pangeo.io` are CNAMES for `*gcp.pangeo.2i2c.cloud`. Nothing else is going on.

**Comment by damianavila** [comment]
Great, that was the "missing" implicit (now explicit) thing, I think 😉 .
