### ISSUE TITLE
Pangeo still having network policy issues

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#825]
### Description

Pangeo is still having issues when trying to spin up a dask cluster. Now the timeout is coming from a `cluster.get_client()` call and it looks like it's trying to connect to the traefik pod.

https://discourse.pangeo.io/t/trying-to-open-gateway-cluster/1912/9

(Apologies for the poor quality/zoomed out quality of this screenshot)

<img width="1145" alt="Screenshot 2021-11-10 at 19 20 44" src="https://user-images.githubusercontent.com/44771837/141179386-56eea8b4-0882-4d65-b480-015c1052f1f1.png">

### Value / benefit

Dask needs to work...

### Tasks to complete

- [x] Add another egress rule to singleuser, this time probably to traefik

**Comment by choldgraf** [comment]
Many thanks @sgibson91 🙂 and thank for adding in the notebook test as well!
