### ISSUE TITLE
Terraform reference docs show "No Inputs/No Outputs"

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#837]
### Description

Currently our terraform reference docs aren't very helpful! https://infrastructure.2i2c.org/en/latest/reference/terraform.html

These are supposed to be auto-generated docs from our terraform files which, in the long run, will be easier to maintain as our terraform tooling grows/adapts.

Is this currently not working because: something was always broken with the build and I only just noticed (couldn't find anything in the albeit quick issue search I performed), or have we overwritten something in our docs deployment process that we need to bring back?

### Value / benefit

- Auto-updating reference docs that we don't have to spend so much time maintaining is great!
- An empty reference page doesn't look super professional.
- A functional reference page will help the team keep on top of our terraform tooling.

### Tasks to complete

- [ ] Identify why this information isn't showing up
- [ ] ...add next steps as needed when we figure this out

**Comment by damianavila** [comment]
> Is this currently not working because: something was always broken with the build and I only just noticed (couldn't find anything in the albeit quick issue search I performed), or have we overwritten something in our docs deployment process that we need to bring back?

We removed that section here, IIRC: https://github.com/2i2c-org/infrastructure/pull/485

**Comment by sgibson91** [comment]
Which I approved... Thank you for jogging my memory @damianavila!

**Comment by pnasrat** [comment]
I also got confused by this. Looking at https://github.com/2i2c-org/infrastructure/blob/master/docs/conf.py the autogeneration is still being run, however `terraform-docs` only works if run in the individual subdirs (aws, gcp) not recursively like the method expects

**Comment by pnasrat** [comment]
Ok so at one point in time there was a main.tf under terraform/ so terraform-docs worked, I suspect this has been broken since e248f1366de8025381f4d91a7001dc7615391558 

Is it worth fixing this - updating conf.py to iterate across each of the subdirs and calling terraform-docs to generate a separate markdown for each and writing an index file, or should the conf.py generation be removed as this has been broken for maybe 18 months or more.

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/issues/2172 is relevant. I think it's ok to remove it in favor of inline docs.
