### ISSUE TITLE
Increase RAM for prometheus server on pangeo-hubs cluster

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#845]
### Description

The Prometheus server on the `pangeo-hubs` cluster is currently in `CrashLoopBackOff` has the amount of data it needs to load at startup is greater than the amount of RAM - causing an OOMKilled event. This is blocking CD upgrades and the deploy-support action times out. We need to feed the prometheus server more RAM in order for it to start up correctly and CI deploys can recommence.

### Value / benefit

It would be nice to get automated deploys for pangeo back

### Tasks to complete

- [x] Figure out _how_ to increase RAM for the prometheus server and implement it: https://github.com/2i2c-org/infrastructure/pull/846
- [ ] Document that process here https://infrastructure.2i2c.org/en/latest/topic/troubleshooting.html: https://github.com/2i2c-org/infrastructure/issues/845

**Comment by yuvipanda** [comment]
https://github.com/berkeley-dsep-infra/datahub/blob/cf2cd20bee913b6a07e9ea3bae629099041bfdde/support/values.yaml#L74 lists the amount of RAM I give prometheus on the fairly big berkeley install. I don't think it needs to be this much - just keep increasing it until it works? :D

Once it comes back up, the 'Cluster Information' dashboard actually has panes that show prometheus memory usage. we can use that to figure out a better and more appropriate limit. Here's 7 days prometheus RAM usage on the berkeley cluster

![Uploading image.png…]()

**Comment by sgibson91** [comment]
Thanks @yuvipanda! Is there anything that could make the upgrade difficult, e.g. PVCs that need to be deleted/recreated or should it just be a straightforward upgrade?

**Comment by sgibson91** [comment]
Opened https://github.com/2i2c-org/infrastructure/pull/846 to bump the memory limit for pangeo

**Comment by sgibson91** [comment]
Opened https://github.com/2i2c-org/infrastructure/issues/845 for docs update
