### ISSUE TITLE
Handling options around dask nodes in Terraform

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#849]
### Description

Our terraform config is currently configured such that if dask nodepools are not explicitly defined, they are automatically derived from the definition of the notebook nodepools instead. This works great when we're deploying a cluster we know will have dask hubs deployed to it, but makes it very difficult to turn off dask nodepools if we know we don't need them (e.g., Justice Innovation Lab). Since terraform is not a _procedural_ language, this level of flexibility may be beyond it's capabilities, but none of us would be in this job if we didn't enjoy pushing the boundaries of what our tools could do 😉 

I see three possible solutions:

1. Introduce a new boolean variable, like `dasknodes_mimic_notebooks` and use this in our `for_each` statements to decide whether or not to create dask nodepools alongside notebook nodepools.
   * When `true`, we would see the behaviour that we have currently
   * When `false`, you could **EITHER** define a set of `dask_nodes` that differ from the notebook nodes to create those specific nodepools **OR** fallback onto the default value `dask_nodes = {}` were _no_ dask nodepools are created.
2. Break the link between the notebook nodepools and the dask nodepools. Any cluster that requires dask nodepools must have them explicitly defined in their `tfvars` file.
3. Do nothing. Our nodepools are created with 0 nodes, so if no dask processes exist to create a dask node, then they effectively cost nothing.

### Value / benefit

- I think if option 1 works, this will give us the flexibility in cluster deployment that we're looking for, but does increase complexity by adding an extra variable.
- Option 2 would make our `tfvars` files longer but arguably clearer since everything is then explicit
- Option 3 feels sub-optimal, though I can't really put into words why

### Implementation details

Whichever option we take, we should implement this across both GCP and Azure terraform configurations. It's bad enough to be maintaining separate config files without having them do different things.

### Tasks to complete

- [x] Decide which option to try first
  - **Result:** Option 2
- [ ] Implement it!

**Comment by yuvipanda** [comment]
Thanks for writing this up in detail, @sgibson91. I think (2) is a good bet to keep overall complexity down, by just repeating ourselves a little bit. As you mentioned elsewhere, Terraform is maybe not the best language to do anything complex in - although I had wished that setting defaults was not too complex for it. Oh well.

(2) will also help if we end up sizing the dask nodes different from any notebook nodes, which we might as well do after observing how they are used.

**Comment by sgibson91** [comment]
@yuvipanda Gave that a go in https://github.com/2i2c-org/infrastructure/pull/850

**Comment by damianavila** [comment]
I also think option 2 is a good compromise.
