### ISSUE TITLE
Support nbgitpuller pulling from private repositories

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#851]
### Description

Being able to pull from private GitHub repositories is a very commonly asked for and used feature of nbgitpuller. This was implemented for University of Toronto (https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/44), and is well used there (I think). To move the UToronto hub to this repo (https://github.com/2i2c-org/infrastructure/issues/638), we should enable this feature generally for whatever hubs that want it.

### Value / benefit

Instructors can use private git repos with nbgitpuller. I think this is a blocker for migrating utoronto as well.

### Implementation details

https://github.com/yuvipanda/git-credential-helpers is the project used to enable this functionality

- [ ] Make sure it is installed in the user image
- [ ] Create a GitHub App that can be used specifically for this hub to support pulling. Some more docs need to be added on what exac
- [ ] Enable the appropriate gitconifg needed in the helm chart. https://github.com/utoronto-2i2c/jupyterhub-deploy/blob/26aa3d542bc8bcd4639dad8728484aede946f1ed/hub/values.yaml#L43 is how it is currently done on utoronto, but we should instead use https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#singleuser-extrafiles to inject this file.
- [ ] Document this publicly somewhere (blog post, docs, etc)

**Comment by choldgraf** [comment]
In our team meeting today I believe @yuvipanda said he'd like to give this one a shot in this cycle, so we've added it to the sprint board! We also discussed that this pattern should be documented in a blog post or something more discoverable for others, so I've added an item about that to the tasks above.
