### ISSUE TITLE
Set up a repo2docker-action repository for the U. Toronto Hub

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#854]
### Description

The U. Toronto Hub currently defines the environment for the hub within the hub's repository. We should separate this out into a dedicated repository that uses the repo2docker-action to build.
 
ref https://github.com/2i2c-org/infrastructure/issues/710

### Value / benefit

This would let us disentangle the environment from the deployment infrastructure for U. Toronto, which will make it simpler to change one or the other. It'll also make it easier for people to inspect and debug the environment

### Implementation details

Environment image documentation is here: https://docs.2i2c.org/en/latest/admin/howto/environment.html

### Tasks to complete

- [ ] Let's just use quay.io for the user image, rather than setup the Azure Container registry. This should involve splitting out the current image into its own repo and using the repo2docker action to build it. There might be complications here due to image size - we need to watch for that.

**Comment by yuvipanda** [comment]
Image is now on quay: https://quay.io/repository/2i2c/utoronto-image

Built from github.com/2i2c-org/utoronto-image/
