### ISSUE TITLE
Create a staging hub for the UToronto cluster

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#867]
### Description

Once https://github.com/2i2c-org/infrastructure/issues/853 is done, we should deploy a staging hub onto the cluster that we've set up for U. T.

### Implementation details

- Add hub config to this repo, starting with just the instructions in https://infrastructure.2i2c.org/en/latest/howto/operate/new-hub/index.html#to-add-a-new-hub. The current config is at https://github.com/utoronto-2i2c/jupyterhub-deploy/blob/staging/hub/values.yaml, https://github.com/utoronto-2i2c/jupyterhub-deploy/blob/staging/deployments/utoronto/config/common.yaml and https://github.com/utoronto-2i2c/jupyterhub-deploy/blob/staging/deployments/utoronto/config/prod.yaml. I've looked through it, and here are the specific things we need to actually move - a lot of the config there we already have, and can be ignored.. This should give us a mostly functional *staging hub* we can test on.
- Use AzureAD Authenticator. Copy the secrets from https://github.com/utoronto-2i2c/jupyterhub-deploy/tree/staging/deployments/utoronto/secrets, and the config from https://github.com/utoronto-2i2c/jupyterhub-deploy/blob/26aa3d542bc8bcd4639dad8728484aede946f1ed/hub/values.yaml#L143. We do this already for our GitHub auth for the pangeo hubs. We can take over the staging hub URL to test this, as adding new URLs requires intervention from Toronto IT we would like to avoid.
- Set admin users from https://github.com/utoronto-2i2c/jupyterhub-deploy/blob/26aa3d542bc8bcd4639dad8728484aede946f1ed/deployments/utoronto/config/common.yaml#L4 - that's the only list of admin users that actually has any effect

**Comment by choldgraf** [comment]
FYI @GeorgianaElena - I factored out the staging hub into a standalone issue, and closed the other issue about deploying the new cluster, since those are discrete steps that we can track. Just letting you know so it's not confusing!

**Comment by GeorgianaElena** [comment]
Thanks @choldgraf This will also cleanup the sprint board from scatter PRs :sweat_smile:

**Comment by GeorgianaElena** [comment]
Update on this: there is a staging hub running at https://staging.utoronto.2i2c.cloud deployed from the infrastructure repository :tada: 

HOWEVER, the login doesn't work quite yet, and still needs investigation. I will reopen this issue, to have a central place for posting updates about this.
