### ISSUE TITLE
Migrate the U Toronto production hub to our new U Toronto cluster

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#868]
Once we have the staging hub set up and confirmed it works as-expected, we need to migrate the U Toronto production hub to the new cluster along with all of the user data. Here are some implementation steps:

- [x] Take down the current hub. I usually just delete the proxy service to make it stop working.
- [x] Copy the JupyterHub database
- [x] Delete all user pods from the old cluster
- [x] Do one final rsync  to catch all the user changes since the last rsync. However long this takes is the total amount of downtime we'll have.
- [x] Point utoronto.2i2c.cloud to the new cluster's production hub. jupyter.utoronto.ca is a CNAME pointing to utoronto.2i2c.cloud, which we control. So we don't need to involve university IT here either.

**Comment by GeorgianaElena** [comment]
All steps have been taken and the hub is now migrated :tada: Let's hope no issues surface :crossed_fingers:
