### ISSUE TITLE
Unable to change the permission to any file to lower than 555 

### ISSUE THREAD

**Issue by tcchiao** [2i2c-org/infrastructure#871]
### Description

I'm unable to set the permission to files lower than 555 using `chmod`. 

Example below showing be trying to set the permission to `test.txt` to 400 but it ended up being 555 instead. I am able to change it to something less restrictive, but not more. 
![Screen Shot 2021-12-05 at 5 29 32 PM](https://user-images.githubusercontent.com/6431831/144773323-a03d545c-1a4f-4464-a6e5-2026e00690f7.png)

### Value / benefit

This is preventing me from using my ssh key to access github content with the error `Permissions 0555 for '/home/jovyan/.ssh/{filename}' are too open.`. Since using ssh keys should be a common access pattern among users, removing this lower bound on permission would be helpful. 

### Tasks to complete

- [ ] allow user to set permission to more restrictive access.

**Comment by damianavila** [comment]
@tcchiao, could you please open send a support email following the guidelines outlined here: https://docs.2i2c.org/en/latest/support.html. Thanks!!

**Comment by tcchiao** [comment]
Ah sounds good will do, thanks!
