### ISSUE TITLE
Copy UToronto home dirs into the new cluster

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#876]
Once we have the staging hub set up and confirmed it works as-expected, start copying the home directories from the NFS setup they currently live in.

- [x] We should mount the Azure File system in the NFS VM, and use rsync to copy

**Comment by GeorgianaElena** [comment]
> We should mount the Azure File system in the NFS VM, and use rsync to copy

@yuvipanda, wondering if you know if there are any Azure docs about how to do this. I know we have our own docs about migrating data from one hub to another here https://infrastructure.2i2c.org/en/latest/howto/operate/move-hub.html and probably this migration to AzureFiles would be a combination of those steps

**Comment by sgibson91** [comment]
I'd see if these help

- https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-linux?tabs=smb311
- https://docs.microsoft.com/en-us/azure/storage/files/storage-files-how-to-mount-nfs-shares

**Comment by yuvipanda** [comment]
I've done the following:

1. Grant access to our new AzureFile from the existing VNet the NFS VM is in using the [azure portal](https://portal.azure.com/#blade/Microsoft_Azure_FileStorage/FileShareMenuBlade/overview/storageAccountId/%2Fsubscriptions%2Fead3521a-d994-4a44-a68d-b16e35642d5b%2FresourceGroups%2F2i2c-utoronto-cluster%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2F2i2cutorontohubstorage/path/homes/protocol/NFS) ot facilitate mounting the AzureFile in the NFS VM, so we can copy them over. Documentation on how to do that is in https://docs.microsoft.com/en-us/azure/storage/files/storage-files-networking-endpoints?tabs=azure-portal#restrict-public-endpoint-access.
2. I've mounted the AzureFile onto the NFS VM with the following commands, run inside the NFS VM (copy pasted [from the portal](https://portal.azure.com/#blade/Microsoft_Azure_FileStorage/FileShareMenuBlade/overview/storageAccountId/%2Fsubscriptions%2Fead3521a-d994-4a44-a68d-b16e35642d5b%2FresourceGroups%2F2i2c-utoronto-cluster%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2F2i2cutorontohubstorage/path/homes/protocol/NFS)):
    ```bash
     sudo mkdir -p /mnt/new-nfs
     sudo mount -t nfs 2i2cutorontohubstorage.file.core.windows.net:/2i2cutorontohubstorage/homes /mnt/new-nfs -o vers=4,minorversion=1,sec=sys
     sudo mkdir /mnt/new-nfs/prod
     sudo chown 1000:1000 /mnt/new-nfs/prod
    ```
3. I've started a `screen` inside the NFS VM, and started the rsync process `time rsync -rah --progress /export/jupyterhub-2i2c-nfs-data-disk-1/homes/ /mnt/new-nfs/prod/`. You can connect to see progress with `screen -r` after sshing into the VM

**Comment by yuvipanda** [comment]
I've also manually increased the size of the file share from 100 (hardcoded in our terraform config now) to 1024 (as that's how big the current UofT disk is). I want to change this into Terraform but of course Azure is a thousand monkeys on a thousand typewriters and i can't https://www.torivar.com/2020/12/19/terraform-azure-file-share/

**Comment by GeorgianaElena** [comment]
> I've done the following:

Million thanks for starting this process @yuvipanda and sharing the steps!

> I've also manually increased the size of the file share from 100 (hardcoded in our terraform config now) to 1024 (as that's how big the current UofT disk is). I want to change this into Terraform but of course Azure is a thousand monkeys on a thousand typewriters and i can't https://www.torivar.com/2020/12/19/terraform-azure-file-share/

You mean the quota listed here, right?
https://github.com/2i2c-org/infrastructure/blob/e26c5cddd92528415792a1dbd29a9359fb237431/terraform/azure/storage.tf#L13
Does this mean that running a `terraform apply` will change back to the initial share size?

**Comment by GeorgianaElena** [comment]
We hit some unexpected slowness during the `rsync` file copy, but @yuvipanda did some quick optimization that sped up the process. We should document that :tada: Will open an issue about it soon, but until then, I believe this issue can be closed.
