### ISSUE TITLE
UToronto hub homepage customization

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#877]
The homepage of UofT's hub is built from [a repository](https://github.com/utoronto-2i2c/homepage) different than [the one](https://github.com/2i2c-org/pilot-homepage) used by the pilot hubs. This means that the new hub's homepage will look a little different than it had.

Normally, just a slight change in aspects wouldn't be an issue, but there is information in the old homepage, like the link towards the UToronto support service that we need to provide for the new hub also.

**Comment by choldgraf** [comment]
@GeorgianaElena good catch - will this require changing the deployment infrastructure for our CI/CD, or is this more a matter of updating something in the Toronto hub's configuration?

**Comment by GeorgianaElena** [comment]
@choldgraf, it just be just a matter of special casing this config bit: https://github.com/2i2c-org/infrastructure/blob/6201d79a6c566adc61e0636139e7ca00d5ad2245/deployer/hub.py#L336-L340

**Comment by damianavila** [comment]
It should be possible to configure that argument through the hub config as we do with the auth class: https://github.com/2i2c-org/infrastructure/blob/6201d79a6c566adc61e0636139e7ca00d5ad2245/deployer/hub.py#L425-L426
Right?

**Comment by yuvipanda** [comment]
Our current template customizations https://github.com/2i2c-org/pilot-homepage are actually just modifications from the utoronto repo - you can see that our pilot-homepage repo is actually forked from that!

We can port the functionality of https://github.com/utoronto-2i2c/homepage/pull/5 into https://github.com/2i2c-org/pilot-homepage, but make it a template variable we can specify? Like we do here: https://github.com/2i2c-org/pilot-homepage/blob/a700295784f54413e84072aa4575529251d9636d/templates/login.html#L26. Should help us specify 'announcements' everywhere.
