### ISSUE TITLE
(optional) Stress test the U Toronto hub

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#883]
This isn't a strictly required step, but once we have the Toronto hub set up as we wish, we should try stress-testing it to convince ourselves that it won't break when people start using it.

**Comment by GeorgianaElena** [comment]
Found this related PR https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/60 from some time ago

**Comment by yuvipanda** [comment]
We didn't do it this time, but migration is complete!
