### ISSUE TITLE
Summary of numbers of users in Pilot Hub

### ISSUE THREAD

**Issue by ericvd-ucb** [2i2c-org/infrastructure#893]
### Description

As is the case of multiple instances with educational hubs, we necessarily have measures of number of users, and amount of use.  For the evaluation of the Cloudbank Pilot, we need to get some summary statistics on users.  

### Value / benefit

- This sort of data could be useful to anyone running an educational hub
- if it was easy to build some metrics that are understandable to a wide audience 

For the cloudbank pilot this would be fundamental information for reporting on the pilot
For 2i2c I hope this kind of summary would be useful over time

### Implementation details

- can we count over some time periods
Minimum
- number of users

after that
- number of starts
- time on hub
- number of assignments / files
- cloud spend/consumption

**Comment by sean-morris** [comment]
@choldgraf Does grafana give us any extra information that we can use here? I also posted this question to the dsep-pilot-hubs slack.

**Comment by yuvipanda** [comment]
Since this was opened, we actually got much better user metrics in grafana! https://grafana.cloudbank.2i2c.cloud/d/hub-dashboard/jupyterhub-dashboard?orgId=1

<img width="1899" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/b168b817-98cd-49df-a080-fae9ee8b4f2a">
