### ISSUE TITLE
[discuss] Should we change our policy for self-merging `infrastructure/` PRs?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#913]
In our Review / Merge policy, we note that PRs should be merged *by the PR author* (https://infrastructure.2i2c.org/en/latest/contributing/code-review.html#changing-active-infrastructure-in-general). This is because we assume the PR author has the most context for what infrastructure might change.

However, this also puts up a barrier towards getting PRs merged in general, and we have had a few instances where a PR had 1+ approvals, but was not merged. In general, we probably want to encourage merges if they have approvals, so here are a few thoughts:

### Two ideas

- Loosen the restriction around who can merge a PR in `infrastructure/` to define a more strict subset that requires a self-merge. E.g., "If a PR will be deployed via CI/CD, anybody can merge it, but if a PR requires a manual deploy, the PR author must merge it"
- Come up with a team practice that encourages that PR author to merge things in more quickly after there are approvals, to discourage the existence of dangling PRs that are just waiting for someone to press the button.

ref #908

**Comment by yuvipanda** [comment]
> Come up with a team practice that encourages that PR author to merge things in more quickly after there are approvals, to discourage the existence of dangling PRs that are just waiting for someone to press the button.

I like this one. At wikimedia once a puppet PR (similar to PRs in this repos) is approved, it needs to be merged within 24h. There was a nagios alert that'll nag on IRC if this isn't the case.

**Comment by sgibson91** [comment]
> If a PR will be deployed via CI/CD, anybody can merge it

I'm nervous about this since there's no guarantee CI/CD will succeed and may still require manual intervention

**Comment by GeorgianaElena** [comment]
> I'm nervous about this since there's no guarantee CI/CD will succeed and may still require manual intervention

Me too! Also, I remember that when we created our Review / Merge policy and decided that the PR author should merge the PR it wasn't just because the author has the most context but also to make it easier for reviewers too.

For me, if I am to merge someone else's PR I get very nervous and try to make sure that at least I have the right setup in place for manual intervention in case the automated deploy fails (esp since now we're hiding the sensitive output when a health check fails) and the changes work on staging. But this adds some overhead.

> Come up with a team practice that encourages that PR author to merge things in more quickly after there are approvals, to discourage the existence of dangling PRs that are just waiting for someone to press the button.

I like this one too :sparkler: ! I think that we're already kind of doing this, but having it written down might encourage the behavior more.

**Comment by choldgraf** [comment]
It sounds like folks in general like the idea of encouraging more rapid merges for dangling PRs.

What if we wrote a little GitHub action that would run every 2 days, pull a list of all open PRs, and for any that have an approval, post a message in our `hub-development` channel saying "PR `{ pr name }` by `@name` has an approval and is awaiting merge!"

**Comment by sgibson91** [comment]
You know I love a bot - though I would suggest consolidating all PRs that need attention into a single "summary" message to reduce noise

**Comment by choldgraf** [comment]
Check it out y'all! https://github.com/2i2c-org/infrastructure/pull/921 :-)

**Comment by yuvipanda** [comment]
I *think* the bot has had the intended effect, so I'm going to close this :) Thanks for writing it, @choldgraf!
