### ISSUE TITLE
Re-enable the openscapes hub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#916]
Currently the hub is 'shut down' - no new user pods can start, because the image is set to busybox:latest to prevent users from starting. This causes our CD to fail: https://github.com/2i2c-org/infrastructure/runs/4700441743?check_suite_focus=true

**Comment by choldgraf** [comment]
Note that this was deployed via the configurator, by @betolink so that's likely where the fix to update this would be. He should feel free to update this image whenever he likes (the hub should be secure now, so it is safe for interactive sessions to work again)

**Comment by betolink** [comment]
I just updated the image @choldgraf , it should work now =)

**Comment by choldgraf** [comment]
it worked for me! closing this one
