### ISSUE TITLE
Archive original UofT hub repository

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#917]
We should decide what to do about the original UToronto repo :arrow_right: https://github.com/utoronto-2i2c/jupyterhub-deploy. Maybe it makes sense to archive it.

We also have a specific GitHub org for it. ~I believe the only things that's still being used from there is the `homepage` repo.~ The repos in this org are not longer used.

**Comment by sgibson91** [comment]
Can we move the `homepage` repo into `2i2c-org`?

1. I think it'll be nice to have everything in the same org
2. In the future, we may want to generalise the `homepage` repo to work with other community hubs

**Comment by yuvipanda** [comment]
I thought we already used https://github.com/2i2c-org/pilot-homepage for the home page too?

**Comment by GeorgianaElena** [comment]
> I thought we already used https://github.com/2i2c-org/pilot-homepage for the home page too?

YES we are! But apparently 2022 me forgot what 2021 me did :facepalm:

**Comment by sgibson91** [comment]
> apparently 2022 me forgot what 2021 me did 🤦

So relatable ❤️

**Comment by yuvipanda** [comment]
Adding a note saying 'do not use this' and archiving them seems the best way forward.
