### ISSUE TITLE
Add grafana dashboards for resource usage

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#92]
In a recent incident, one of the nodes ran out of memory and CPU. This wasn't immediately obvious from the grafana dashboards. We should think about the resources we need to track across the nodes, and have a dashboard for particularly important ones.

**Comment by yuvipanda** [comment]
http://grafana.pilot.2i2c.cloud/d/GqFAtZRZz/hub-metrics?orgId=1&refresh=30s&from=now-30m&to=now now I've metrics per hub

**Comment by choldgraf** [comment]
amazing! should this be closed?

also do I have a U/P for the pilot grafana? I can't seem to find it

**Comment by yuvipanda** [comment]
I need to setup GitHub auth for Grafana I think.

We'll also have many clusters, with many Prometheus instances. But I'd like to have just one Grafana for them all. grafana.mybinder.org does this, but all the Prometheus instances it talks to are public. We can't do that, so will need to put in some form of auth around our Prometheus instances.

**Comment by choldgraf** [comment]
We've now got grafana set up for each of our hubs, so I'm going to close this. We should still add a single grafana for all hubs but I'll put that into a new issue
