### ISSUE TITLE
Define a community representative for the University of Toronto

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#927]
### Description of problem and opportunity to address it

**Problem description**

We do not currently have a community representative defined for the U. Toronto Hub. As a result, it is unclear who has decision rights about making changes to the hub, and it's also unclear who hub users should contact in order to make requests for changes etc.

We should define one or two community representatives for this hub, and encode them somewhere explicit.

### Implementation guide and constraints

- We should reach out to Nathan + Jeremy to ask them who should be the community representatives for Toronto.
- We might need to answer https://github.com/2i2c-org/infrastructure/issues/820 before implementing this as well.

### Updates and ongoing work

- [x] Reach out to UToronto and ask them to name some community representatives
- [ ] Figure out where to encode this information (e.g., https://github.com/2i2c-org/infrastructure/issues/820)

**Comment by choldgraf** [comment]
### Update: email sent

I've sent an email to Jeremy, Avi, and Nathan to see if they can choose a community representative

**Comment by choldgraf** [comment]
@consideRatio yep that makes sense to me. I think that @colliand may also be involved with this one because he's going to speak with them about models of engagement as well. I'll add him here so we don't lose track of it (hope that's OK @colliand !)

**Comment by consideRatio** [comment]
@choldgraf I'm looking at https://2i2c.freshdesk.com/a/tickets/37 about following up who is the community representative for this hub. To your knowledge, is that decided? If so, I can resolve that ticket finally.

**Comment by consideRatio** [comment]
Now that there is a community rep defined, this issue can be considered resolved.

There is an action point not resolved, but that is covered by another issue:

> Figure out where to encode this information (e.g., https://github.com/2i2c-org/infrastructure/issues/820)

---

For reference, this is the response from Jim on Slack: https://2i2c.slack.com/archives/C028WU9PFBN/p1657296960339779
