### ISSUE TITLE
 Logging out of 2i2c demo hub does not actually log you out

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#957]
### Description of problem and opportunity to address it

**Context to understand the problem**
When logging out of the new 2i2c demo hub demo.pilot.2i2c.cloud, you're not actually being logged out on an Identity Provider level, so a second attempt to login might show you the CILogon login page, but you won't be able to change the IDP id.

**Problem or idea**
We're currently logging out users at a hub and Auth0 session level, which is enough for hub not using CILogon. But with CILogon we're adding another auth proxy level that so we need to support logging out from the IDP too.

**Proposed solution**
I believe we should implement the logout at an Identity Provider Session Layer too (https://auth0.com/docs/authenticate/login/logout).

**What's the value and who would benefit**
This would allow users to do change the IDP, or account when logging in using CILogon.

**Comment by GeorgianaElena** [comment]
Unfortunately, I couldn't wasn't able to find a way to logout users out of CILogon through Auth0. The solution suggested in the [Auth0 docs](https://auth0.com/docs/authenticate/login/logout/log-users-out-of-idps), to use the `federated` query param didn't work not matter how hard I tried to hack into it. I believe it is because there isn't federated logout support in Auth0 for CILogon -> https://auth0.com/docs/authenticate/login/logout/log-users-out-of-idps#federated-logout-support.

### Possible workarounds
1. Ask users go to `https://cilogon.org/logout` if they want to use other an account from the same Identity Provider they have used befor
2. When closing the user's Auth0 session, instead of redirecting them back to the hub home page, redirect them to the CILogon logout page. This means however that they would need to navigate themselves back the hub home page.
https://github.com/2i2c-org/infrastructure/blob/066f166de3b40af7dfcec9565a788163db5416a8/deployer/auth.py#L154

**Comment by damianavila** [comment]
Mmm.. both workarounds feel broken but I think I would probably go with option 1 because it feels less disruptive, IMHO.

**Comment by choldgraf** [comment]
Agree w/ @damianavila

**Comment by GeorgianaElena** [comment]
Closed by https://github.com/2i2c-org/infrastructure/pull/974
