### ISSUE TITLE
Stop using `pilot` in `foo.pilot.2i2c.cloud` for new hubs

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#989]
### Description of problem and opportunity to address it

**Context to understand the problem**
Currently, the hubs on our shared cluster follow the pattern `<hubname>.pilot.2i2c.cloud`.

However, we are past our pilot phase, and calling it a `pilot` may cause organizations to make assumptions about the quality or reliability of our hubs. Moreover, `pilot` isn't particularly descriptive, it's more of an implementation details from 2i2c's perspective rather than something that a hub's user cares about.

**Proposed solution**
We should instead use the pattern `<foo>.hub.2i2c.cloud`. This will be:

- more memorable
- a clear indication that there's a hub at the URL
- less tied to the "phase of 2i2c's service"

### Implementation guide and constraints

- We should probably set up a redirect so that `*.2i2c.cloud` redirects to `*.hub.2i2c.cloud`
- One reason we might **not** want to do this is if we explicitly want to have different hubs on different parts of our infrastructure (e.g. `alpha.2i2c.cloud` as well). But thus far I don't think we're doing this.
- As part of this, we should also rename `github.com/2i2c-org/pilot` to `https://github.com/2i2c-org/user-guide` or something like this.

**Comment by choldgraf** [comment]
Could I get some feedback from the @2i2c-org/tech-team on this one? I don't think that making this change will be too difficult and the longer we keep it as `pilot`, the more annoyance there will be if/when we change it.

**Comment by yuvipanda** [comment]
Another option is to just move them to <hub-name>.2i2c.cloud.

**Comment by choldgraf** [comment]
@yuvipanda I'm +1 on that as well! I defer to the preference/judgment of others here, just think that we should move away from the word `pilot`

**Comment by sgibson91** [comment]
No pushback from me about removing `pilot` - I suspect no one has had the time to action this yet :D

**Comment by consideRatio** [comment]
@choldgraf is there any remaining action points besides this for this issue then?

**Comment by choldgraf** [comment]
@consideRatio I think it would be "documenting the new practice of not using `pilot` in our new hub setup docs, to formalize this plan from our team". Does that make sense?

**Comment by consideRatio** [comment]
@choldgraf can I assign you to fix that? I note that you have done a lot of work recently to migrate docs across the 2i2c org

**Comment by choldgraf** [comment]
@consideRatio sure thing 👍 

Ah one question I thought up for redirects. What about:

- `grafana.pilot.2i2c.cloud`
- `demo.pilot.2i2c.cloud`
- `staging.pilot.2i2c.cloud`

or other hubs that are 2i2c-specific? Is that worth re-naming? I don't feel strongly but wanted to note it

**Comment by choldgraf** [comment]
In my opinion `demo.pilot.2i2c.org` would could move without worry about old links breaking, we have shared this in a very limited fashion.

I don't think this is a huge priority, but the main thing I am worrying about is the feedback I got from some communities that the word "pilot" conveys "unreliable and unstable"

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/pull/1129 moves a few of these

**Comment by yuvipanda** [comment]
@choldgraf demo.2i2c.cloud works now! Can you tell the rocky mountain lab folks to use the new URL?

**Comment by choldgraf** [comment]
done! think we can close one?

**Comment by choldgraf** [comment]
I'm going to assume the answer is yes!
