### ISSUE TITLE
basehub: ensure default values are set for all values used by templates

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#994]
The basehub helm chart makes use of values as seen in the templates.

https://github.com/2i2c-org/infrastructure/blob/fcd83405e42847b7b322d7d91b94e84a21c0d2b1/helm-charts/basehub/templates/docs-service-deployment.yaml#L1-L4

Not all values, for example these, are not provided with a default value in the basehub helm charts values.yaml file. This has a few downsides.

1. We are forced to write something like this ...
   ```yaml
   {{ if .Values.docs_service }}
   {{ if .Values.docs_service.enabled }}
   ```
   ... instead of just ...
   ```yaml
   {{ if .Values.docs_service.enabled }}
   ```
   ... because we have to check for the existance of a mapping/dictionary named docs_service
2. We are making it hard for anyone looking at values.yaml to understand what is configurable.
   This would be helpful to have for anyone configuring the helm chart, and if we are to create a schema for the helm chart - then we need to define it for the available options - see #937

---

### Action point
- [ ] Go through all basehub's templates and verify that values.yaml has an entry for all referenced configuration.

**Comment by choldgraf** [comment]
Agree! Do we want to track this as a part of #879 or is it for the future?

**Comment by consideRatio** [comment]
I consider it an standalone task that can be done quickly and unrelated to anything else, besides perhaps #937 which will want to do this as a sub-task if its not already done by then.

**Comment by choldgraf** [comment]
Mostly I want to make sure that we don't lose track of it, since #879 is the space for planning and coordinating this chunk of work...but if you think it'll be straightforward to loop back on it in the future then sounds good.
