### ISSUE TITLE
Document setting up GPUs on our clusters and access for our hubs

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#996]
### October 2023 Update

A lot of work has happened around our GPU deployment process: https://infrastructure.2i2c.org/howto/features/gpu/

Only docs for Azure seem to be missing now, but we don't often deploy there and the clusters we do run are educational without a need for GPUs.

---

### Description of problem and opportunity to address it

**Problem or idea**

We are beginning to run GPU-enabled nodes on some of our clusters, specifically those used for research. Getting this up-and-running for the first time took a lot of time and effort and we need to ensure that the next time we agree to this, the amount of time invested is less by sharing our lessons learned from this event.

**Proposed solution**

We should create a new section in our infrastructure docs on setting up GPUs, that captures the lessons learned from https://github.com/2i2c-org/infrastructure/issues/930

It should be generalised with Notes on specifics for cloud providers where they differ.

**What's the value and who would benefit**

This will reduce the amount of toil for any future 2i2c engineer to setup GPUs on a cluster.

### Implementation guide and constraints

- [ ] Create a new section/topic in our infrastructure docs
- [ ] Include the lessons learned for Azure from https://github.com/2i2c-org/infrastructure/issues/930
- [ ] There were also helpful links for GCP and AWS dropped in the above issue and we should capture those too

**Comment by choldgraf** [comment]
To start with, can we think of the minimal documentation addition that we can make while the experience from #930 is still fresh? Like perhaps to start we could just add a "GPUs" topic to [the infrastructure docs](https://infrastructure.2i2c.org/en/latest/) and then paste in snippets of gotchas and the basic process that you followed, and we can then iterate on it from there. I feel like now is the best time to do this while it's fresh.

If that feels too hacky / quick - another option is to paste this kind of text into this issue and we can clean it up later. E.g.:

- A short step-by-step guide of what we did
- Where did we run into problems that were unintuitive to fix
- Links to comments in GitHub etc where we had useful analysis and insight
- Links to the final config that got it working

**Comment by sgibson91** [comment]
**Step-by-step with gotchas:**

Step 1) Update terraform to deploy new nodepools with GPU machines for the nodebooks and dasknodes (if apllicable)
Step 2) Deploy the provider-specific daemonset that would pull the appropriate image for the drivers onto the nodes
  - GOTCHA: You may need 2 daemonsets: one to retrieve, one to install. Azure only needed one because their GPUs come with some machinery pre-installed.
Step 3) Create a new JupyterHub profile to use the GPU machines
  - GOTCHA: Use `extra_resource_limits: {"nvidia.com/gpu": "1"}` in the profile so the server actually requests the GPU resources
  - GOTCHA: Use `environment: { "NVIDIA_DRIVER_CAPABILITIES": "compute,utility" }` so tools like TensorFlow can see the GPUs
  - GOTCHA: If you see a message that says something like "pod didn't trigger scale-up... back-off after failed scale-up", check your cloud quotas. Cloud providers often have quotas for how many instances of machine families you can have in one location at a given time, often you (or the owner of the subscription/project) will need to request an increase of that quota before you can request the machine type. https://discourse.jupyter.org/t/backoff-after-failed-scale-up/3331

**GitHub links:**

There were almost too many comments to individually link to every one of them. The most discussion happened here:

- https://github.com/2i2c-org/infrastructure/issues/930
- This is a good analysis on daemonsets: https://github.com/2i2c-org/infrastructure/pull/932#issuecomment-1014683833

**Final working config for JupyterHub:**

https://github.com/2i2c-org/infrastructure/blob/fdfbce56ca42215636faf2a2343caf18a51cfa62/config/clusters/azure.carbonplan.cluster.yaml#L137-L149

**Comment by yuvipanda** [comment]
We've mad a bunch of progress, particularly at https://github.com/2i2c-org/infrastructure/blob/master/docs/howto/features/gpu.md. Here's what is left to do:

- [ ] Document how to setup GPU nodepools for GCP (we only have docs for AWS at this point!)
- [ ] Document *requirements* for the *image* used in GPU nodes
- [ ] Document this as a feature users can request during hub setup (@damianavila)
- [ ] Document that we don't currently support this on Azure (AFAIK)

**Comment by yuvipanda** [comment]
Aaah, whoops sorry @sgibson91! In that case we should document that too, I'll edit my comment

**Comment by sgibson91** [comment]
I think we are only missing the Azure docs now! https://infrastructure.2i2c.org/howto/features/gpu/

**Comment by yuvipanda** [comment]
I'm going to close this now, as we have no further work planned right now. If and when we do need Azure GPU, we can open another issue to track that then.
